Mixed Criticality Orchestrator: mc_orchestrator/json-3.7.3/test/thirdparty/Fuzzer/afl/afl_driver.cpp File Reference
afl_driver.cpp File Reference
#include <assert.h>
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <signal.h>
#include <sys/resource.h>
#include <sys/time.h>
Macros
#define CHECK_ERROR(cond, error_message)
Functions
int LLVMFuzzerTestOneInput (const uint8_t *Data, size_t Size)
__attribute__ ((weak)) int LLVMFuzzerInitialize(int *argc
int __afl_persistent_loop (unsigned int)
void __afl_manual_init ()
size_t GetPeakRSSMb ()
static void SetSigaction (int signum, void(*callback)(int, siginfo_t *, void *))
static void write_extra_stats ()
static void crash_handler (int, siginfo_t *, void *)
static void maybe_initialize_extra_stats ()
static void maybe_duplicate_stderr ()
int main (int argc, char **argv)
Variables
char *** argv
static volatile char AFL_PERSISTENT [] = "##SIG_AFL_PERSISTENT##"
static volatile char suppress_warning2 = AFL_PERSISTENT[0]
static volatile char AFL_DEFER_FORKSVR [] = "##SIG_AFL_DEFER_FORKSRV##"
static volatile char suppress_warning1 = AFL_DEFER_FORKSVR[0]
static const size_t kMaxAflInputSize = 1 << 20
static uint8_t AflInputBuf [kMaxAflInputSize]
static FILE * extra_stats_file = NULL
static uint32_t previous_peak_rss = 0
static time_t slowest_unit_time_secs = 0
static const int kNumExtraStats = 2
static const char * kExtraStatsFormatString
Macro Definition Documentation
CHECK_ERROR
#define CHECK_ERROR (cond, error_message)
Value:
  if (!(cond)) {                                                               \
    fprintf(stderr, (error_message));                                          \
    abort();                                                                   \
  }
Definition at line 78 of file afl_driver.cpp.
Function Documentation
__afl_manual_init()
void __afl_manual_init ()
Definition at line 8 of file AFLDriverTest.cpp.
 {}
Referenced by main().
__afl_persistent_loop()
int __afl_persistent_loop (unsigned int)
Definition at line 10 of file AFLDriverTest.cpp.
{
   return 0;
 }
Referenced by main().
__attribute__()
__attribute__ ((weak))
crash_handler()
static void crash_handler (int , siginfo_t * , void *) static
Definition at line 158 of file afl_driver.cpp.
{
   // Make sure we don't try calling write_extra_stats again if we crashed while
   // trying to call it.
   static bool first_crash = true;
   CHECK_ERROR(first_crash,
               "Crashed in crash signal handler. This is a bug in the fuzzer.");
   first_crash = false;
   write_extra_stats();
 }
References CHECK_ERROR, and write_extra_stats().
Referenced by maybe_initialize_extra_stats().
GetPeakRSSMb()
size_t GetPeakRSSMb ()
Definition at line 113 of file afl_driver.cpp.
                       {
   struct rusage usage;
   if (getrusage(RUSAGE_SELF, &usage))
     return 0;
   if (LIBFUZZER_LINUX) {
     // ru_maxrss is in KiB
     return usage.ru_maxrss >> 10;
   } else if (LIBFUZZER_APPLE) {
     // ru_maxrss is in bytes
     return usage.ru_maxrss >> 20;
   }
   assert(0 && "GetPeakRSSMb() is not implemented for your platform");
   return 0;
 }
References assert().
Referenced by fuzzer::Fuzzer::PrintFinalStats(), fuzzer::Fuzzer::PrintStats(), fuzzer::Fuzzer::RssLimitCallback(), fuzzer::RssThread(), and write_extra_stats().
LLVMFuzzerTestOneInput()
int LLVMFuzzerTestOneInput (const uint8_t * Data, size_t Size)
Definition at line 28 of file fuzzer-parse_bson.cpp.
 {
     try
     {
         // step 1: parse input
         std::vector<uint8_t> vec1(data, data + size);
         json j1 = json::from_bson(vec1);
         if (j1.is_discarded())
         {
             return 0;
         }
         try
         {
             // step 2: round trip
             std::vector<uint8_t> vec2 = json::to_bson(j1);
             // parse serialization
             json j2 = json::from_bson(vec2);
             // serializations must match
             assert(json::to_bson(j2) == vec2);
         }
         catch (const json::parse_error&)
         {
             // parsing a BSON serialization must not fail
             assert(false);
         }
     }
     catch (const json::parse_error&)
     {
         // parse errors are ok, because input may be random bytes
     }
     catch (const json::type_error&)
     {
         // type errors can occur during parsing, too
     }
     catch (const json::out_of_range&)
     {
         // out of range errors can occur during parsing, too
     }
     // return 0 - non-zero return values are reserved for future use
     return 0;
 }
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 241 of file afl_driver.cpp.
{
   fprintf(stderr, "======================= INFO =========================\n"
                   "This binary is built for AFL-fuzz.\n"
                   "To run the target function on a single input execute this:\n"
                   "  %s < INPUT_FILE\n"
                   "To run the fuzzing execute this:\n"
                   "  afl-fuzz [afl-flags] %s [N] "
                   "-- run N fuzzing iterations before "
                   "re-spawning the process (default: 1000)\n"
                   "======================================================\n",
           argv[0], argv[0]);
   if (LLVMFuzzerInitialize)
     LLVMFuzzerInitialize(&argc, &argv);
   // Do any other expensive one-time initialization here.
   maybe_duplicate_stderr();
   maybe_initialize_extra_stats();
   __afl_manual_init();
   int N = 1000;
   if (argc >= 2)
     N = atoi(argv[1]);
   assert(N > 0);
   time_t unit_time_secs;
   int num_runs = 0;
   while (__afl_persistent_loop(N)) {
     ssize_t n_read = read(0, AflInputBuf, kMaxAflInputSize);
     if (n_read > 0) {
       // Copy AflInputBuf into a separate buffer to let asan find buffer
       // overflows. Don't use unique_ptr/etc to avoid extra dependencies.
       uint8_t *copy = new uint8_t[n_read];
       memcpy(copy, AflInputBuf, n_read);
       struct timeval unit_start_time;
       CHECK_ERROR(gettimeofday(&unit_start_time, NULL) == 0,
                   "Calling gettimeofday failed");
       num_runs++;
       LLVMFuzzerTestOneInput(copy, n_read);
       struct timeval unit_stop_time;
       CHECK_ERROR(gettimeofday(&unit_stop_time, NULL) == 0,
                   "Calling gettimeofday failed");
       // Update slowest_unit_time_secs if we see a new max.
       unit_time_secs = unit_stop_time.tv_sec - unit_start_time.tv_sec;
       if (slowest_unit_time_secs < unit_time_secs)
         slowest_unit_time_secs = unit_time_secs;
       delete[] copy;
     }
   }
   fprintf(stderr, "%s: successfully executed %d input(s)\n", argv[0], num_runs);
 }
References __afl_manual_init(), __afl_persistent_loop(), AflInputBuf, argv, assert(), CHECK_ERROR, kMaxAflInputSize, LLVMFuzzerInitialize(), LLVMFuzzerTestOneInput(), maybe_duplicate_stderr(), maybe_initialize_extra_stats(), N, and slowest_unit_time_secs.
maybe_duplicate_stderr()
static void maybe_duplicate_stderr () static
Definition at line 223 of file afl_driver.cpp.
{
   char* stderr_duplicate_filename =
       getenv("AFL_DRIVER_STDERR_DUPLICATE_FILENAME");
   if (!stderr_duplicate_filename)
     return;
   FILE* stderr_duplicate_stream =
       freopen(stderr_duplicate_filename, "a+", stderr);
   if (!stderr_duplicate_stream) {
     fprintf(
         stderr,
         "Failed to duplicate stderr to AFL_DRIVER_STDERR_DUPLICATE_FILENAME");
     abort();
   }
 }
Referenced by main().
maybe_initialize_extra_stats()
static void maybe_initialize_extra_stats () static
Definition at line 176 of file afl_driver.cpp.
{
   // If AFL_DRIVER_EXTRA_STATS_FILENAME isn't set then we have nothing to do.
   char *extra_stats_filename = getenv("AFL_DRIVER_EXTRA_STATS_FILENAME");
   if (!extra_stats_filename)
     return;
   // Open the file and find the previous peak_rss_mb value.
   // This is necessary because the fuzzing process is restarted after N
   // iterations are completed. So we may need to get this value from a previous
   // process to be accurate.
   extra_stats_file = fopen(extra_stats_filename, "r");
   // If extra_stats_file already exists: read old stats from it.
   if (extra_stats_file) {
     int matches = fscanf(extra_stats_file, kExtraStatsFormatString,
                          &previous_peak_rss, &slowest_unit_time_secs);
     // Make sure we have read a real extra stats file and that we have used it
     // to set slowest_unit_time_secs and previous_peak_rss.
     CHECK_ERROR(matches == kNumExtraStats, "Extra stats file is corrupt");
     CHECK_ERROR(fclose(extra_stats_file) == 0, "Failed to close file");
     // Now open the file for writing.
     extra_stats_file = fopen(extra_stats_filename, "w");
     CHECK_ERROR(extra_stats_file,
                 "Failed to open extra stats file for writing");
   } else {
     // Looks like this is the first time in a fuzzing job this is being called.
     extra_stats_file = fopen(extra_stats_filename, "w+");
     CHECK_ERROR(extra_stats_file, "failed to create extra stats file");
   }
   // Make sure that crash_handler gets called on any kind of fatal error.
   int crash_signals[] = {SIGSEGV, SIGBUS, SIGABRT, SIGILL, SIGFPE,  SIGINT,
                          SIGTERM};
   const size_t num_signals = sizeof(crash_signals) / sizeof(crash_signals[0]);
   for (size_t idx = 0; idx < num_signals; idx++)
     SetSigaction(crash_signals[idx], crash_handler);
   // Make sure it gets called on other kinds of exits.
   atexit(write_extra_stats);
 }
References CHECK_ERROR, crash_handler(), extra_stats_file, kExtraStatsFormatString, kNumExtraStats, previous_peak_rss, SetSigaction(), slowest_unit_time_secs, and write_extra_stats().
Referenced by main().
SetSigaction()
static void SetSigaction (int signum, void(*)(int, siginfo_t *, void *) callback) static
Definition at line 129 of file afl_driver.cpp.
{
   struct sigaction sigact;
   memset(&sigact, 0, sizeof(sigact));
   sigact.sa_sigaction = callback;
   if (sigaction(signum, &sigact, 0)) {
     fprintf(stderr, "libFuzzer: sigaction failed with %d\n", errno);
     exit(1);
   }
 }
Referenced by maybe_initialize_extra_stats().
write_extra_stats()
static void write_extra_stats () static
Definition at line 142 of file afl_driver.cpp.
{
   uint32_t peak_rss = GetPeakRSSMb();
   if (peak_rss < previous_peak_rss)
     peak_rss = previous_peak_rss;
   int chars_printed = fprintf(extra_stats_file, kExtraStatsFormatString,
                               peak_rss, slowest_unit_time_secs);
   CHECK_ERROR(chars_printed != 0, "Failed to write extra_stats_file");
   CHECK_ERROR(fclose(extra_stats_file) == 0,
               "Failed to close extra_stats_file");
 }
References CHECK_ERROR, extra_stats_file, GetPeakRSSMb(), kExtraStatsFormatString, previous_peak_rss, and slowest_unit_time_secs.
Referenced by crash_handler(), and maybe_initialize_extra_stats().
Variable Documentation
AFL_DEFER_FORKSVR
volatile char AFL_DEFER_FORKSVR[] = "##SIG_AFL_DEFER_FORKSRV##" static
Definition at line 96 of file afl_driver.cpp.
AFL_PERSISTENT
volatile char AFL_PERSISTENT[] = "##SIG_AFL_PERSISTENT##" static
Definition at line 91 of file afl_driver.cpp.
AflInputBuf
uint8_t AflInputBuf[kMaxAflInputSize] static
Definition at line 102 of file afl_driver.cpp.
Referenced by main().
argv
char*** argv
Definition at line 87 of file afl_driver.cpp.
Referenced by fuzzer::FuzzerDriver(), LLVMFuzzerInitialize(), and main().
extra_stats_file
FILE* extra_stats_file = NULL static
Definition at line 105 of file afl_driver.cpp.
Referenced by maybe_initialize_extra_stats(), and write_extra_stats().
kExtraStatsFormatString
const char* kExtraStatsFormatString static
Initial value:
= "peak_rss_mb            : %u\n"
                                             "slowest_unit_time_sec  : %u\n"
Definition at line 109 of file afl_driver.cpp.
Referenced by maybe_initialize_extra_stats(), and write_extra_stats().
kMaxAflInputSize
const size_t kMaxAflInputSize = 1 << 20 static
Definition at line 101 of file afl_driver.cpp.
Referenced by main().
kNumExtraStats
const int kNumExtraStats = 2 static
Definition at line 108 of file afl_driver.cpp.
Referenced by maybe_initialize_extra_stats().
previous_peak_rss
uint32_t previous_peak_rss = 0 static
Definition at line 106 of file afl_driver.cpp.
Referenced by maybe_initialize_extra_stats(), and write_extra_stats().
slowest_unit_time_secs
time_t slowest_unit_time_secs = 0 static
Definition at line 107 of file afl_driver.cpp.
Referenced by main(), maybe_initialize_extra_stats(), and write_extra_stats().
suppress_warning1
volatile char suppress_warning1 = AFL_DEFER_FORKSVR[0] static
Definition at line 98 of file afl_driver.cpp.
suppress_warning2
volatile char suppress_warning2 = AFL_PERSISTENT[0] static
Definition at line 93 of file afl_driver.cpp.