Mixed Criticality Orchestrator: mc_orchestrator/json-3.7.3/benchmarks/src/benchmarks.cpp File Reference
benchmarks.cpp File Reference
#include "benchmark/benchmark.h"
#include <nlohmann/json.hpp>
#include <fstream>
Typedefs
using json = nlohmann::json
Functions
static void ParseFile (benchmark::State &state, const char *filename)
BENCHMARK_CAPTURE (ParseFile, jeopardy, "data/jeopardy/jeopardy.json")
BENCHMARK_CAPTURE (ParseFile, canada, "data/nativejson-benchmark/canada.json")
BENCHMARK_CAPTURE (ParseFile, citm_catalog, "data/nativejson-benchmark/citm_catalog.json")
BENCHMARK_CAPTURE (ParseFile, twitter, "data/nativejson-benchmark/twitter.json")
BENCHMARK_CAPTURE (ParseFile, floats, "data/numbers/floats.json")
BENCHMARK_CAPTURE (ParseFile, signed_ints, "data/numbers/signed_ints.json")
BENCHMARK_CAPTURE (ParseFile, unsigned_ints, "data/numbers/unsigned_ints.json")
BENCHMARK_CAPTURE (ParseFile, small_signed_ints, "data/numbers/small_signed_ints.json")
static void ParseString (benchmark::State &state, const char *filename)
BENCHMARK_CAPTURE (ParseString, jeopardy, "data/jeopardy/jeopardy.json")
BENCHMARK_CAPTURE (ParseString, canada, "data/nativejson-benchmark/canada.json")
BENCHMARK_CAPTURE (ParseString, citm_catalog, "data/nativejson-benchmark/citm_catalog.json")
BENCHMARK_CAPTURE (ParseString, twitter, "data/nativejson-benchmark/twitter.json")
BENCHMARK_CAPTURE (ParseString, floats, "data/numbers/floats.json")
BENCHMARK_CAPTURE (ParseString, signed_ints, "data/numbers/signed_ints.json")
BENCHMARK_CAPTURE (ParseString, unsigned_ints, "data/numbers/unsigned_ints.json")
BENCHMARK_CAPTURE (ParseString, small_signed_ints, "data/numbers/small_signed_ints.json")
static void Dump (benchmark::State &state, const char *filename, int indent)
BENCHMARK_CAPTURE (Dump, jeopardy/-, "data/jeopardy/jeopardy.json", -1)
BENCHMARK_CAPTURE (Dump, jeopardy/4, "data/jeopardy/jeopardy.json", 4)
BENCHMARK_CAPTURE (Dump, canada/-, "data/nativejson-benchmark/canada.json", -1)
BENCHMARK_CAPTURE (Dump, canada/4, "data/nativejson-benchmark/canada.json", 4)
BENCHMARK_CAPTURE (Dump, citm_catalog/-, "data/nativejson-benchmark/citm_catalog.json", -1)
BENCHMARK_CAPTURE (Dump, citm_catalog/4, "data/nativejson-benchmark/citm_catalog.json", 4)
BENCHMARK_CAPTURE (Dump, twitter/-, "data/nativejson-benchmark/twitter.json", -1)
BENCHMARK_CAPTURE (Dump, twitter/4, "data/nativejson-benchmark/twitter.json", 4)
BENCHMARK_CAPTURE (Dump, floats/-, "data/numbers/floats.json", -1)
BENCHMARK_CAPTURE (Dump, floats/4, "data/numbers/floats.json", 4)
BENCHMARK_CAPTURE (Dump, signed_ints/-, "data/numbers/signed_ints.json", -1)
BENCHMARK_CAPTURE (Dump, signed_ints/4, "data/numbers/signed_ints.json", 4)
BENCHMARK_CAPTURE (Dump, unsigned_ints/-, "data/numbers/unsigned_ints.json", -1)
BENCHMARK_CAPTURE (Dump, unsigned_ints/4, "data/numbers/unsigned_ints.json", 4)
BENCHMARK_CAPTURE (Dump, small_signed_ints/-, "data/numbers/small_signed_ints.json", -1)
BENCHMARK_CAPTURE (Dump, small_signed_ints/4, "data/numbers/small_signed_ints.json", 4)
BENCHMARK_MAIN ()
Typedef Documentation
json
using json = nlohmann::json
Definition at line 5 of file benchmarks.cpp.
Function Documentation
BENCHMARK_CAPTURE() [1/32]
BENCHMARK_CAPTURE (Dump , canada/- , "data/nativejson-benchmark/canada.json" , - 1)
BENCHMARK_CAPTURE() [2/32]
BENCHMARK_CAPTURE (Dump , canada/ 4, "data/nativejson-benchmark/canada.json" , 4)
BENCHMARK_CAPTURE() [3/32]
BENCHMARK_CAPTURE (Dump , citm_catalog/- , "data/nativejson-benchmark/citm_catalog.json" , - 1)
BENCHMARK_CAPTURE() [4/32]
BENCHMARK_CAPTURE (Dump , citm_catalog/ 4, "data/nativejson-benchmark/citm_catalog.json" , 4)
BENCHMARK_CAPTURE() [5/32]
BENCHMARK_CAPTURE (Dump , floats/- , "data/numbers/floats.json" , - 1)
BENCHMARK_CAPTURE() [6/32]
BENCHMARK_CAPTURE (Dump , floats/ 4, "data/numbers/floats.json" , 4)
BENCHMARK_CAPTURE() [7/32]
BENCHMARK_CAPTURE (Dump , jeopardy/- , "data/jeopardy/jeopardy.json" , - 1)
BENCHMARK_CAPTURE() [8/32]
BENCHMARK_CAPTURE (Dump , jeopardy/ 4, "data/jeopardy/jeopardy.json" , 4)
BENCHMARK_CAPTURE() [9/32]
BENCHMARK_CAPTURE (Dump , signed_ints/- , "data/numbers/signed_ints.json" , - 1)
BENCHMARK_CAPTURE() [10/32]
BENCHMARK_CAPTURE (Dump , signed_ints/ 4, "data/numbers/signed_ints.json" , 4)
BENCHMARK_CAPTURE() [11/32]
BENCHMARK_CAPTURE (Dump , small_signed_ints/- , "data/numbers/small_signed_ints.json" , - 1)
BENCHMARK_CAPTURE() [12/32]
BENCHMARK_CAPTURE (Dump , small_signed_ints/ 4, "data/numbers/small_signed_ints.json" , 4)
BENCHMARK_CAPTURE() [13/32]
BENCHMARK_CAPTURE (Dump , twitter/- , "data/nativejson-benchmark/twitter.json" , - 1)
BENCHMARK_CAPTURE() [14/32]
BENCHMARK_CAPTURE (Dump , twitter/ 4, "data/nativejson-benchmark/twitter.json" , 4)
BENCHMARK_CAPTURE() [15/32]
BENCHMARK_CAPTURE (Dump , unsigned_ints/- , "data/numbers/unsigned_ints.json" , - 1)
BENCHMARK_CAPTURE() [16/32]
BENCHMARK_CAPTURE (Dump , unsigned_ints/ 4, "data/numbers/unsigned_ints.json" , 4)
BENCHMARK_CAPTURE() [17/32]
BENCHMARK_CAPTURE (ParseFile , canada , "data/nativejson-benchmark/canada.json")
BENCHMARK_CAPTURE() [18/32]
BENCHMARK_CAPTURE (ParseFile , citm_catalog , "data/nativejson-benchmark/citm_catalog.json")
BENCHMARK_CAPTURE() [19/32]
BENCHMARK_CAPTURE (ParseFile , floats , "data/numbers/floats.json")
BENCHMARK_CAPTURE() [20/32]
BENCHMARK_CAPTURE (ParseFile , jeopardy , "data/jeopardy/jeopardy.json")
BENCHMARK_CAPTURE() [21/32]
BENCHMARK_CAPTURE (ParseFile , signed_ints , "data/numbers/signed_ints.json")
BENCHMARK_CAPTURE() [22/32]
BENCHMARK_CAPTURE (ParseFile , small_signed_ints , "data/numbers/small_signed_ints.json")
BENCHMARK_CAPTURE() [23/32]
BENCHMARK_CAPTURE (ParseFile , twitter , "data/nativejson-benchmark/twitter.json")
BENCHMARK_CAPTURE() [24/32]
BENCHMARK_CAPTURE (ParseFile , unsigned_ints , "data/numbers/unsigned_ints.json")
BENCHMARK_CAPTURE() [25/32]
BENCHMARK_CAPTURE (ParseString , canada , "data/nativejson-benchmark/canada.json")
BENCHMARK_CAPTURE() [26/32]
BENCHMARK_CAPTURE (ParseString , citm_catalog , "data/nativejson-benchmark/citm_catalog.json")
BENCHMARK_CAPTURE() [27/32]
BENCHMARK_CAPTURE (ParseString , floats , "data/numbers/floats.json")
BENCHMARK_CAPTURE() [28/32]
BENCHMARK_CAPTURE (ParseString , jeopardy , "data/jeopardy/jeopardy.json")
BENCHMARK_CAPTURE() [29/32]
BENCHMARK_CAPTURE (ParseString , signed_ints , "data/numbers/signed_ints.json")
BENCHMARK_CAPTURE() [30/32]
BENCHMARK_CAPTURE (ParseString , small_signed_ints , "data/numbers/small_signed_ints.json")
BENCHMARK_CAPTURE() [31/32]
BENCHMARK_CAPTURE (ParseString , twitter , "data/nativejson-benchmark/twitter.json")
BENCHMARK_CAPTURE() [32/32]
BENCHMARK_CAPTURE (ParseString , unsigned_ints , "data/numbers/unsigned_ints.json")
BENCHMARK_MAIN()
BENCHMARK_MAIN ()
Dump()
static void Dump (benchmark::State & state, const char * filename, int indent) static
Definition at line 78 of file benchmarks.cpp.
 {
     std::ifstream f(filename);
     std::string str((std::istreambuf_iterator<char>(f)), std::istreambuf_iterator<char>());
     json j = json::parse(str);
     while (state.KeepRunning())
     {
         j.dump(indent);
     }
     state.SetBytesProcessed(state.iterations() * j.dump(indent).size());
 }
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::dump(), benchmark::State::iterations(), benchmark::State::KeepRunning(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parse(), and benchmark::State::SetBytesProcessed().
ParseFile()
static void ParseFile (benchmark::State & state, const char * filename) static
Definition at line 11 of file benchmarks.cpp.
 {
     while (state.KeepRunning())
     {
         state.PauseTiming();
         auto* f = new std::ifstream(filename);
         auto* j = new json();
         state.ResumeTiming();
         *j = json::parse(*f);
         state.PauseTiming();
         delete f;
         delete j;
         state.ResumeTiming();
     }
     std::ifstream file(filename, std::ios::binary | std::ios::ate);
     state.SetBytesProcessed(state.iterations() * file.tellg());
 }
References benchmark::State::iterations(), benchmark::State::KeepRunning(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parse(), benchmark::State::PauseTiming(), benchmark::State::ResumeTiming(), and benchmark::State::SetBytesProcessed().
ParseString()
static void ParseString (benchmark::State & state, const char * filename) static
Definition at line 44 of file benchmarks.cpp.
 {
     std::ifstream f(filename);
     std::string str((std::istreambuf_iterator<char>(f)), std::istreambuf_iterator<char>());
     while (state.KeepRunning())
     {
         state.PauseTiming();
         auto* j = new json();
         state.ResumeTiming();
         *j = json::parse(str);
         state.PauseTiming();
         delete j;
         state.ResumeTiming();
     }
     state.SetBytesProcessed(state.iterations() * str.size());
 }
References benchmark::State::iterations(), benchmark::State::KeepRunning(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parse(), benchmark::State::PauseTiming(), benchmark::State::ResumeTiming(), and benchmark::State::SetBytesProcessed().