Mixed Criticality Orchestrator: fuzzer::TraceState Class Reference
fuzzer::TraceState Class Reference
Public Member Functions
TraceState (MutationDispatcher &MD, const FuzzingOptions &Options, const Fuzzer *F)
void TraceMemcmpCallback (size_t CmpSize, const uint8_t *Data1, const uint8_t *Data2)
void TraceSwitchCallback (uintptr_t PC, size_t ValSizeInBits, uint64_t Val, size_t NumCases, uint64_t *Cases)
int TryToAddDesiredData (uint64_t PresentData, uint64_t DesiredData, size_t DataSize)
int TryToAddDesiredData (const uint8_t *PresentData, const uint8_t *DesiredData, size_t DataSize)
void StartTraceRecording ()
void StopTraceRecording ()
void AddMutation (uint32_t Pos, uint32_t Size, const uint8_t *Data)
void AddMutation (uint32_t Pos, uint32_t Size, uint64_t Data)
void AddInterestingWord (const uint8_t *Data, size_t Size)
Private Member Functions
bool IsTwoByteData (uint64_t Data)
bool WantToHandleOneMoreMutation ()
Private Attributes
size_t NumMutations
TraceBasedMutation Mutations [kMaxMutations]
std::set< Word > InterestingWords
MutationDispatcher & MD
const FuzzingOptions Options
const Fuzzer * F
std::map< Word, size_t > AutoDictUnitCounts
size_t AutoDictAdds = 0
Static Private Attributes
static const size_t kMaxMutations = 1 << 16
Detailed Description
Definition at line 40 of file FuzzerTraceState.cpp.
Constructor & Destructor Documentation
TraceState()
fuzzer::TraceState::TraceState (MutationDispatcher & MD, const FuzzingOptions & Options, const Fuzzer * F) inline
Definition at line 42 of file FuzzerTraceState.cpp.
       : MD(MD), Options(Options), F(F) {}
Member Function Documentation
AddInterestingWord()
void fuzzer::TraceState::AddInterestingWord (const uint8_t * Data, size_t Size) inline
Definition at line 108 of file FuzzerTraceState.cpp.
{
     if (!RecordingMemmem || !F->InFuzzingThread()) return;
     if (Size <= 1) return;
     Size = std::min(Size, Word::GetMaxSize());
     Word W(Data, Size);
     InterestingWords.insert(W);
   }
References F, fuzzer::FixedWord< 27 >::GetMaxSize(), fuzzer::Fuzzer::InFuzzingThread(), InterestingWords, and fuzzer::RecordingMemmem.
Referenced by __sanitizer_weak_hook_memmem(), __sanitizer_weak_hook_strcasestr(), and __sanitizer_weak_hook_strstr().
AddMutation() [1/2]
void fuzzer::TraceState::AddMutation (uint32_t Pos, uint32_t Size, const uint8_t * Data) inline
Definition at line 96 of file FuzzerTraceState.cpp.
{
     if (NumMutations >= kMaxMutations) return;
     auto &M = Mutations[NumMutations++];
     M.Pos = Pos;
     M.W.Set(Data, Size);
   }
References kMaxMutations, Mutations, NumMutations, and fuzzer::TraceBasedMutation::Pos.
Referenced by AddMutation(), and TryToAddDesiredData().
AddMutation() [2/2]
void fuzzer::TraceState::AddMutation (uint32_t Pos, uint32_t Size, uint64_t Data) inline
Definition at line 103 of file FuzzerTraceState.cpp.
{
     assert(Size <= sizeof(Data));
     AddMutation(Pos, Size, reinterpret_cast<uint8_t*>(&Data));
   }
References AddMutation(), and assert().
IsTwoByteData()
bool fuzzer::TraceState::IsTwoByteData (uint64_t Data) inline private
Definition at line 117 of file FuzzerTraceState.cpp.
{
     int64_t Signed = static_cast<int64_t>(Data);
     Signed >>= 16;
     return Signed == 0 || Signed == -1L;
   }
Referenced by TraceSwitchCallback().
StartTraceRecording()
void fuzzer::TraceState::StartTraceRecording () inline
Definition at line 56 of file FuzzerTraceState.cpp.
{
     if (!Options.UseMemcmp)
       return;
     RecordingMemcmp = Options.UseMemcmp;
     RecordingMemmem = Options.UseMemmem;
     NumMutations = 0;
     InterestingWords.clear();
     MD.ClearAutoDictionary();
   }
References fuzzer::MutationDispatcher::ClearAutoDictionary(), InterestingWords, MD, NumMutations, Options, fuzzer::RecordingMemcmp, fuzzer::RecordingMemmem, fuzzer::FuzzingOptions::UseMemcmp, and fuzzer::FuzzingOptions::UseMemmem.
Referenced by fuzzer::Fuzzer::StartTraceRecording().
StopTraceRecording()
void fuzzer::TraceState::StopTraceRecording () inline
Definition at line 66 of file FuzzerTraceState.cpp.
{
     if (!RecordingMemcmp)
       return;
     RecordingMemcmp = false;
     for (size_t i = 0; i < NumMutations; i++) {
       auto &M = Mutations[i];
       if (Options.Verbosity >= 2) {
         AutoDictUnitCounts[M.W]++;
         AutoDictAdds++;
         if ((AutoDictAdds & (AutoDictAdds - 1)) == 0) {
           typedef std::pair<size_t, Word> CU;
           std::vector<CU> CountedUnits;
           for (auto &I : AutoDictUnitCounts)
             CountedUnits.push_back(std::make_pair(I.second, I.first));
           std::sort(CountedUnits.begin(), CountedUnits.end(),
                     [](const CU &a, const CU &b) { return a.first > b.first; });
           Printf("AutoDict:\n");
           for (auto &I : CountedUnits) {
             Printf("   %zd ", I.first);
             PrintASCII(I.second.data(), I.second.size());
             Printf("\n");
           }
         }
       }
       MD.AddWordToAutoDictionary({M.W, M.Pos});
     }
     for (auto &W : InterestingWords)
       MD.AddWordToAutoDictionary({W});
   }
References fuzzer::MutationDispatcher::AddWordToAutoDictionary(), AutoDictAdds, AutoDictUnitCounts, InterestingWords, MD, Mutations, NumMutations, Options, fuzzer::PrintASCII(), fuzzer::Printf(), fuzzer::RecordingMemcmp, and fuzzer::FuzzingOptions::Verbosity.
Referenced by fuzzer::Fuzzer::StopTraceRecording().
TraceMemcmpCallback()
void fuzzer::TraceState::TraceMemcmpCallback (size_t CmpSize, const uint8_t * Data1, const uint8_t * Data2)
Definition at line 195 of file FuzzerTraceState.cpp.
{
   if (!RecordingMemcmp || !F->InFuzzingThread()) return;
   CmpSize = std::min(CmpSize, Word::GetMaxSize());
   int Added2 = TryToAddDesiredData(Data1, Data2, CmpSize);
   int Added1 = TryToAddDesiredData(Data2, Data1, CmpSize);
   if ((Added1 || Added2) && Options.Verbosity >= 3) {
     Printf("MemCmp Added %d%d: ", Added1, Added2);
     if (Added1) PrintASCII(Data1, CmpSize);
     if (Added2) PrintASCII(Data2, CmpSize);
     Printf("\n");
   }
 }
References F, fuzzer::FixedWord< 27 >::GetMaxSize(), fuzzer::Fuzzer::InFuzzingThread(), Options, fuzzer::PrintASCII(), fuzzer::Printf(), fuzzer::RecordingMemcmp, TryToAddDesiredData(), and fuzzer::FuzzingOptions::Verbosity.
Referenced by __sanitizer_weak_hook_memcmp(), __sanitizer_weak_hook_strcmp(), and __sanitizer_weak_hook_strncmp().
TraceSwitchCallback()
void fuzzer::TraceState::TraceSwitchCallback (uintptr_t PC, size_t ValSizeInBits, uint64_t Val, size_t NumCases, uint64_t * Cases)
Definition at line 209 of file FuzzerTraceState.cpp.
{
   if (F->InFuzzingThread()) return;
   size_t ValSize = ValSizeInBits / 8;
   bool TryShort = IsTwoByteData(Val);
   for (size_t i = 0; i < NumCases; i++)
     TryShort &= IsTwoByteData(Cases[i]);
   if (Options.Verbosity >= 3)
     Printf("TraceSwitch: %p %zd # %zd; TryShort %d\n", PC, Val, NumCases,
            TryShort);
   for (size_t i = 0; i < NumCases; i++) {
     TryToAddDesiredData(Val, Cases[i], ValSize);
     if (TryShort)
       TryToAddDesiredData(Val, Cases[i], 2);
   }
 }
References Cases, F, fuzzer::Fuzzer::InFuzzingThread(), IsTwoByteData(), Options, PC, fuzzer::Printf(), TryToAddDesiredData(), and fuzzer::FuzzingOptions::Verbosity.
TryToAddDesiredData() [1/2]
int fuzzer::TraceState::TryToAddDesiredData (const uint8_t * PresentData, const uint8_t * DesiredData, size_t DataSize)
Definition at line 173 of file FuzzerTraceState.cpp.
{
   if (NumMutations >= kMaxMutations || !WantToHandleOneMoreMutation()) return 0;
   ScopedDoingMyOwnMemmem scoped_doing_my_own_memmem;
   const uint8_t *UnitData;
   auto UnitSize = F->GetCurrentUnitInFuzzingThead(&UnitData);
   int Res = 0;
   const uint8_t *Beg = UnitData;
   const uint8_t *End = Beg + UnitSize;
   for (const uint8_t *Cur = Beg; Cur < End; Cur++) {
     Cur = (uint8_t *)SearchMemory(Cur, End - Cur, PresentData, DataSize);
     if (!Cur)
       break;
     size_t Pos = Cur - Beg;
     assert(Pos < UnitSize);
     AddMutation(Pos, DataSize, DesiredData);
     Res++;
   }
   return Res;
 }
References AddMutation(), assert(), F, fuzzer::Fuzzer::GetCurrentUnitInFuzzingThead(), kMaxMutations, NumMutations, fuzzer::SearchMemory(), and WantToHandleOneMoreMutation().
TryToAddDesiredData() [2/2]
int fuzzer::TraceState::TryToAddDesiredData (uint64_t PresentData, uint64_t DesiredData, size_t DataSize)
Definition at line 150 of file FuzzerTraceState.cpp.
{
   if (NumMutations >= kMaxMutations || !WantToHandleOneMoreMutation()) return 0;
   ScopedDoingMyOwnMemmem scoped_doing_my_own_memmem;
   const uint8_t *UnitData;
   auto UnitSize = F->GetCurrentUnitInFuzzingThead(&UnitData);
   int Res = 0;
   const uint8_t *Beg = UnitData;
   const uint8_t *End = Beg + UnitSize;
   for (const uint8_t *Cur = Beg; Cur < End; Cur++) {
     Cur = (uint8_t *)SearchMemory(Cur, End - Cur, &PresentData, DataSize);
     if (!Cur)
       break;
     size_t Pos = Cur - Beg;
     assert(Pos < UnitSize);
     AddMutation(Pos, DataSize, DesiredData);
     AddMutation(Pos, DataSize, DesiredData + 1);
     AddMutation(Pos, DataSize, DesiredData - 1);
     Res++;
   }
   return Res;
 }
References AddMutation(), assert(), F, fuzzer::Fuzzer::GetCurrentUnitInFuzzingThead(), kMaxMutations, NumMutations, fuzzer::SearchMemory(), and WantToHandleOneMoreMutation().
Referenced by TraceMemcmpCallback(), and TraceSwitchCallback().
WantToHandleOneMoreMutation()
bool fuzzer::TraceState::WantToHandleOneMoreMutation () inline private
Definition at line 127 of file FuzzerTraceState.cpp.
{
     const size_t FirstN = 64;
     // Gladly handle first N mutations.
     if (NumMutations <= FirstN) return true;
     size_t Diff = NumMutations - FirstN;
     size_t DiffLog = sizeof(long) * 8 - __builtin_clzl((long)Diff);
     assert(DiffLog > 0 && DiffLog < 64);
     bool WantThisOne = MD.GetRand()(1 << DiffLog) == 0;  // 1 out of DiffLog.
     return WantThisOne;
   }
References assert(), fuzzer::MutationDispatcher::GetRand(), MD, and NumMutations.
Referenced by TryToAddDesiredData().
Member Data Documentation
AutoDictAdds
size_t fuzzer::TraceState::AutoDictAdds = 0 private
Definition at line 147 of file FuzzerTraceState.cpp.
Referenced by StopTraceRecording().
AutoDictUnitCounts
std::map<Word, size_t> fuzzer::TraceState::AutoDictUnitCounts private
Definition at line 146 of file FuzzerTraceState.cpp.
Referenced by StopTraceRecording().
F
const Fuzzer* fuzzer::TraceState::F private
Definition at line 145 of file FuzzerTraceState.cpp.
Referenced by AddInterestingWord(), TraceMemcmpCallback(), TraceSwitchCallback(), and TryToAddDesiredData().
InterestingWords
std::set<Word> fuzzer::TraceState::InterestingWords private
Definition at line 142 of file FuzzerTraceState.cpp.
Referenced by AddInterestingWord(), StartTraceRecording(), and StopTraceRecording().
kMaxMutations
const size_t fuzzer::TraceState::kMaxMutations = 1 << 16 static private
Definition at line 138 of file FuzzerTraceState.cpp.
Referenced by AddMutation(), and TryToAddDesiredData().
MD
MutationDispatcher& fuzzer::TraceState::MD private
Definition at line 143 of file FuzzerTraceState.cpp.
Referenced by StartTraceRecording(), StopTraceRecording(), and WantToHandleOneMoreMutation().
Mutations
TraceBasedMutation fuzzer::TraceState::Mutations[kMaxMutations] private
Definition at line 140 of file FuzzerTraceState.cpp.
Referenced by AddMutation(), and StopTraceRecording().
NumMutations
size_t fuzzer::TraceState::NumMutations private
Definition at line 139 of file FuzzerTraceState.cpp.
Referenced by AddMutation(), StartTraceRecording(), StopTraceRecording(), TryToAddDesiredData(), and WantToHandleOneMoreMutation().
Options
const FuzzingOptions fuzzer::TraceState::Options private
Definition at line 144 of file FuzzerTraceState.cpp.
Referenced by StartTraceRecording(), StopTraceRecording(), TraceMemcmpCallback(), and TraceSwitchCallback().
The documentation for this class was generated from the following file:
mc_orchestrator/json-3.7.3/test/thirdparty/Fuzzer/FuzzerTraceState.cpp