Mixed Criticality Orchestrator: PodmanPodUsageCommand Class Reference
PodmanPodUsageCommand Class Reference
#include <mco_podman_commands.hpp>
Public Member Functions
PodmanPodUsageCommand (const std::string &app_name_)
~PodmanPodUsageCommand ()=default
bool Execute () const override
Public Member Functions inherited from Command
virtual ~Command ()=default
Private Attributes
std::string app_name_
Detailed Description
Definition at line 74 of file mco_podman_commands.hpp.
Constructor & Destructor Documentation
PodmanPodUsageCommand()
PodmanPodUsageCommand::PodmanPodUsageCommand (const std::string & app_name_)
Definition at line 214 of file mco_podman_commands.cpp.
{
     this->app_name_ = app_name;
 }
~PodmanPodUsageCommand()
PodmanPodUsageCommand::~PodmanPodUsageCommand () default
Member Function Documentation
Execute()
bool PodmanPodUsageCommand::Execute () const override virtual
Implements Command.
Definition at line 218 of file mco_podman_commands.cpp.
{
     // Get pod name from the database
     // Get pod name from the database
     string pod_name = DatabaseHandler::GetInstance().ReadData(this->app_name_, kPodName);
     //cout << "POD NAME"<< pod_name;
     // Using jq to filter pod stats for the specific pod and output in a readable format
     string command = kPodmanPodUsage + "| jq -c '.[] | select(.Name == \"" + pod_name + "-"+ app_name_ +"\")' > " + kOutputFile;
    // string command = "podman pod stats --no-stream --format json | jq '.[] | select(.Name == \"app4-pod-0-app4\")' > " + kOutputFile;
     int response = system(command.c_str());
     if (response == kSuccess) {
         string msg = "Pod usage details have been generated";
         cout << msg << endl;
         // Open the file and read the filtered JSON output
         ifstream file(kOutputFile);
         // Read the entire file into a string
         string json_str((istreambuf_iterator<char>(file)), istreambuf_iterator<char>());
         file.close();
         json pod_info;
         // Parse the content as JSON
         try {
             pod_info = json::parse(json_str); // Parse the JSON data directly from the string
         } catch (const json::parse_error& e) {
             cerr << "Error parsing JSON: " << e.what() << endl;
             return false;
         }
         if (!pod_info.is_null()) {
             string cpu = pod_info["CPU"];
             string memory = pod_info["MemUsage"];
             msg = "Pod name: " + pod_name + " CPU: " + cpu + " Memory: " + memory;
             cout << msg << endl;
             DatabaseHandler::GetInstance().AddData("cache", msg);
             return true;
         } else {
             msg = "Pod name not found in usage details";
             cout << msg << endl;
             DatabaseHandler::GetInstance().AddData("cache", msg);
             return false;
         }
     } else {
         string msg = "Failed to generate pod usage details";
         cout << msg << endl;
         DatabaseHandler::GetInstance().AddData("cache", msg);
         return false;
     }
 }
References DatabaseHandler::AddData(), DatabaseHandler::GetInstance(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::is_null(), kOutputFile, kPodmanPodUsage, kPodName, kSuccess, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parse(), DatabaseHandler::ReadData(), and nlohmann::detail::exception::what().
Member Data Documentation
app_name_
std::string PodmanPodUsageCommand::app_name_ private
Definition at line 76 of file mco_podman_commands.hpp.
The documentation for this class was generated from the following files:
mc_orchestrator/runtime/inc/mco_podman_commands.hpp
mc_orchestrator/runtime/src/mco_podman_commands.cpp