Mixed Criticality Orchestrator: BluechiStartQmUnitCommand Class Reference
BluechiStartQmUnitCommand Class Reference
#include <mco_bluechi_commands.hpp>
Public Member Functions
BluechiStartQmUnitCommand (const std::string &app_name_)
~BluechiStartQmUnitCommand ()=default
bool Execute () const override
Public Member Functions inherited from Command
virtual ~Command ()=default
Private Attributes
std::string app_name_
Detailed Description
Definition at line 64 of file mco_bluechi_commands.hpp.
Constructor & Destructor Documentation
BluechiStartQmUnitCommand()
BluechiStartQmUnitCommand::BluechiStartQmUnitCommand (const std::string & app_name_)
Definition at line 210 of file mco_bluechi_commands.cpp.
{
     this->app_name_ = app_name;
 }
~BluechiStartQmUnitCommand()
BluechiStartQmUnitCommand::~BluechiStartQmUnitCommand () default
Member Function Documentation
Execute()
bool BluechiStartQmUnitCommand::Execute () const override virtual
Implements Command.
Definition at line 214 of file mco_bluechi_commands.cpp.
{
     string container_path = DatabaseHandler::GetInstance().ReadData(infotainment, this->app_name_, kYamlPath);
     string category = DatabaseHandler::GetInstance().ReadData(infotainment, this->app_name_, kCategory);
     //string container_path = DatabaseHandler::GetInstance().ReadData(this->app_name_, kYamlPath);
     // cout<<container_path<<endl;
     string dest_path = kQmSystemdPath + container_path.substr(container_path.find_last_of("/\\") + 1);
     cout << "Copying file to: " << dest_path << endl;
     // Using system command to copy the file
     string copy_command = "sudo cp " + container_path + " " + dest_path;
     int result = system(copy_command.c_str());
     if (result != kSuccess) {
         cerr << "Failed to copy the file." << endl;
         return 1;
     }
     // Reload systemd daemon
     string command = kBluechiGenerateServiceFile + kQmNodeName;
     result = system(command.c_str());
     if (result != kSuccess) {
         cerr << "Failed to reload systemd daemon." << endl;
         return 1;
     }
     // Start the service (assuming service file name is the same as the container file)
     string service_file = app_name_ + ".service";
     cout << service_file << endl;
     string start_service_cmd = kBluechiApplyPods + kQmNodeName + " " + service_file;
     // Start the service
     result = system(start_service_cmd.c_str());
     if (result != kSuccess) {
         cerr << "Failed to start the service." << endl;
         return 1;
     }
     if(category == "games"){
     DatabaseHandler::GetInstance().qm_infotainment_games_stopped_apps_.erase(this->app_name_);
     DatabaseHandler::GetInstance().UpdateRunningApps(kQmInfoGamesStoppedApps, DatabaseHandler::GetInstance().qm_infotainment_games_stopped_apps_);
     DatabaseHandler::GetInstance().qm_infotainment_games_running_apps_.emplace(this->app_name_);
     DatabaseHandler::GetInstance().UpdateRunningApps(kQmInfoGamesRunningApps, DatabaseHandler::GetInstance().qm_infotainment_games_running_apps_);
     } else if(category == "ott"){
     DatabaseHandler::GetInstance().qm_infotainment_ott_stopped_apps_.erase(this->app_name_);
     DatabaseHandler::GetInstance().UpdateRunningApps(kQmInfoOttStoppedApps, DatabaseHandler::GetInstance().qm_infotainment_ott_stopped_apps_);
     DatabaseHandler::GetInstance().qm_infotainment_ott_running_apps_.emplace(this->app_name_);
     DatabaseHandler::GetInstance().UpdateRunningApps(kQmInfoOttRunningApps, DatabaseHandler::GetInstance().qm_infotainment_ott_running_apps_);
     } else {}
     string priority = DatabaseHandler::GetInstance().ReadData(infotainment, this->app_name_, kAppPriority);
     if(priority == "high"){
         DatabaseHandler::GetInstance().priority_high_qm_running_apps_.emplace(this->app_name_);
         DatabaseHandler::GetInstance().UpdateRunningApps(kPriorityHighQmRunningApps, DatabaseHandler::GetInstance().priority_high_qm_running_apps_);
     } else if(priority == "medium"){
         DatabaseHandler::GetInstance().priority_medium_qm_running_apps_.emplace(this->app_name_);
         DatabaseHandler::GetInstance().UpdateRunningApps(kPriorityMediumQmRunningApps, DatabaseHandler::GetInstance().priority_medium_qm_running_apps_);
     } else if(priority == "low"){
         DatabaseHandler::GetInstance().priority_low_qm_running_apps_.emplace(this->app_name_);
         DatabaseHandler::GetInstance().UpdateRunningApps(kPriorityLowQmRunningApps, DatabaseHandler::GetInstance().priority_low_qm_running_apps_);
     } else {}
     // DatabaseHandler::GetInstance().asil_b_running_apps_.emplace(this->app_name_);
     // DatabaseHandler::GetInstance().UpdateRunningApps(kAsilRunningApps, DatabaseHandler::GetInstance().asil_b_running_apps_);
     return true;
 }
References DatabaseHandler::GetInstance(), infotainment, kAppPriority, kBluechiApplyPods, kBluechiGenerateServiceFile, kCategory, kPriorityHighQmRunningApps, kPriorityLowQmRunningApps, kPriorityMediumQmRunningApps, kQmInfoGamesRunningApps, kQmInfoGamesStoppedApps, kQmInfoOttRunningApps, kQmInfoOttStoppedApps, kQmNodeName, kQmSystemdPath, kSuccess, kYamlPath, DatabaseHandler::priority_high_qm_running_apps_, DatabaseHandler::priority_low_qm_running_apps_, DatabaseHandler::priority_medium_qm_running_apps_, DatabaseHandler::qm_infotainment_games_running_apps_, DatabaseHandler::qm_infotainment_games_stopped_apps_, DatabaseHandler::qm_infotainment_ott_running_apps_, DatabaseHandler::qm_infotainment_ott_stopped_apps_, DatabaseHandler::ReadData(), result, and DatabaseHandler::UpdateRunningApps().
Member Data Documentation
app_name_
std::string BluechiStartQmUnitCommand::app_name_ private
Definition at line 66 of file mco_bluechi_commands.hpp.
The documentation for this class was generated from the following files:
mc_orchestrator/runtime/inc/mco_bluechi_commands.hpp
mc_orchestrator/runtime/src/mco_bluechi_commands.cpp