Mixed Criticality Orchestrator: httplib::detail::stream_line_reader Class Reference
httplib::detail::stream_line_reader Class Reference
#include <httplib.h>
Public Member Functions
stream_line_reader (Stream &strm, char *fixed_buffer, size_t fixed_buffer_size)
const char * ptr () const
size_t size () const
bool end_with_crlf () const
bool getline ()
Private Member Functions
void append (char c)
Private Attributes
Stream & strm_
char * fixed_buffer_
const size_t fixed_buffer_size_
size_t fixed_buffer_used_size_ = 0
std::string glowable_buffer_
Detailed Description
Definition at line 2238 of file httplib.h.
Constructor & Destructor Documentation
stream_line_reader()
httplib::detail::stream_line_reader::stream_line_reader (Stream & strm, char * fixed_buffer, size_t fixed_buffer_size) inline
Definition at line 2607 of file httplib.h.
     : strm_(strm), fixed_buffer_(fixed_buffer),
       fixed_buffer_size_(fixed_buffer_size) {}
Member Function Documentation
append()
void httplib::detail::stream_line_reader::append (char c) inline private
Definition at line 2659 of file httplib.h.
{
   if (fixed_buffer_used_size_ < fixed_buffer_size_ - 1) {
     fixed_buffer_[fixed_buffer_used_size_++] = c;
     fixed_buffer_[fixed_buffer_used_size_] = '\0';
   } else {
     if (glowable_buffer_.empty()) {
       assert(fixed_buffer_[fixed_buffer_used_size_] == '\0');
       glowable_buffer_.assign(fixed_buffer_, fixed_buffer_used_size_);
     }
     glowable_buffer_ += c;
   }
 }
References assert(), c, fixed_buffer_, fixed_buffer_size_, fixed_buffer_used_size_, and glowable_buffer_.
Referenced by getline().
end_with_crlf()
bool httplib::detail::stream_line_reader::end_with_crlf () const inline
Definition at line 2628 of file httplib.h.
{
   auto end = ptr() + size();
   return size() >= 2 && end[-2] == '\r' && end[-1] == '\n';
 }
References ptr(), and size().
Referenced by httplib::detail::read_headers().
getline()
bool httplib::detail::stream_line_reader::getline () inline
Definition at line 2633 of file httplib.h.
{
   fixed_buffer_used_size_ = 0;
   glowable_buffer_.clear();
   for (size_t i = 0;; i++) {
     char byte;
     auto n = strm_.read(&byte, 1);
     if (n < 0) {
       return false;
     } else if (n == 0) {
       if (i == 0) {
         return false;
       } else {
         break;
       }
     }
     append(byte);
     if (byte == '\n') { break; }
   }
   return true;
 }
References append(), fixed_buffer_used_size_, glowable_buffer_, n, httplib::Stream::read(), and strm_.
Referenced by httplib::Server::process_request(), httplib::detail::read_content_chunked(), httplib::detail::read_headers(), and httplib::ClientImpl::read_response_line().
ptr()
const char * httplib::detail::stream_line_reader::ptr () const inline
Definition at line 2612 of file httplib.h.
{
   if (glowable_buffer_.empty()) {
     return fixed_buffer_;
   } else {
     return glowable_buffer_.data();
   }
 }
References fixed_buffer_, and glowable_buffer_.
Referenced by end_with_crlf(), httplib::Server::process_request(), httplib::detail::read_content_chunked(), httplib::detail::read_headers(), and httplib::ClientImpl::read_response_line().
size()
size_t httplib::detail::stream_line_reader::size () const inline
Definition at line 2620 of file httplib.h.
{
   if (glowable_buffer_.empty()) {
     return fixed_buffer_used_size_;
   } else {
     return glowable_buffer_.size();
   }
 }
References fixed_buffer_used_size_, and glowable_buffer_.
Referenced by end_with_crlf(), httplib::Server::process_request(), httplib::detail::read_content_chunked(), and httplib::detail::read_headers().
Member Data Documentation
fixed_buffer_
char* httplib::detail::stream_line_reader::fixed_buffer_ private
Definition at line 2251 of file httplib.h.
Referenced by append(), and ptr().
fixed_buffer_size_
const size_t httplib::detail::stream_line_reader::fixed_buffer_size_ private
Definition at line 2252 of file httplib.h.
Referenced by append().
fixed_buffer_used_size_
size_t httplib::detail::stream_line_reader::fixed_buffer_used_size_ = 0 private
Definition at line 2253 of file httplib.h.
Referenced by append(), getline(), and size().
glowable_buffer_
std::string httplib::detail::stream_line_reader::glowable_buffer_ private
Definition at line 2254 of file httplib.h.
Referenced by append(), getline(), ptr(), and size().
strm_
Stream& httplib::detail::stream_line_reader::strm_ private
Definition at line 2250 of file httplib.h.
Referenced by getline().
The documentation for this class was generated from the following file:
mc_orchestrator/httplib/httplib.h