Mixed Criticality Orchestrator: PodmanDeletePodCommand Class Reference
PodmanDeletePodCommand Class Reference
#include <mco_podman_commands.hpp>
Public Member Functions
PodmanDeletePodCommand (const std::string &app_name_)
~PodmanDeletePodCommand ()=default
bool Execute () const override
Public Member Functions inherited from Command
virtual ~Command ()=default
Private Attributes
std::string app_name_
Detailed Description
Definition at line 54 of file mco_podman_commands.hpp.
Constructor & Destructor Documentation
PodmanDeletePodCommand()
PodmanDeletePodCommand::PodmanDeletePodCommand (const std::string & app_name_)
Definition at line 117 of file mco_podman_commands.cpp.
{
     this->app_name_ = app_name;
 }
~PodmanDeletePodCommand()
PodmanDeletePodCommand::~PodmanDeletePodCommand () default
Member Function Documentation
Execute()
bool PodmanDeletePodCommand::Execute () const override virtual
Implements Command.
Definition at line 121 of file mco_podman_commands.cpp.
{
     // This method should contain the logic to delete a pod
     string command = kPodmanDeletePods + DatabaseHandler::GetInstance().ReadData(this->app_name_, kPodName) ;
     system(command.c_str());
     if(!DatabaseHandler::GetInstance().running_apps_.empty()) {
         // Updating the list of running apps and deleted apps in the database
         DatabaseHandler::GetInstance().running_apps_.erase(this->app_name_);
         DatabaseHandler::GetInstance().UpdateRunningApps(kRunningApps, DatabaseHandler::GetInstance().running_apps_);
         DatabaseHandler::GetInstance().deleted_apps_.emplace(this->app_name_);
         DatabaseHandler::GetInstance().UpdateRunningApps(kDeletedApps, DatabaseHandler::GetInstance().deleted_apps_);
         string app_priority = DatabaseHandler::GetInstance().ReadData(this->app_name_, kAppPriority);
         if(app_priority == kHighPriority){
             DatabaseHandler::GetInstance().priority_high_apps_.erase(this->app_name_);
             DatabaseHandler::GetInstance().UpdateRunningApps(kPriorityHighApps, DatabaseHandler::GetInstance().priority_high_apps_);
         } else if(app_priority == kMediumPriority){
             DatabaseHandler::GetInstance().priority_medium_apps_.erase(this->app_name_);
             DatabaseHandler::GetInstance().UpdateRunningApps(kPriorityMediumApps, DatabaseHandler::GetInstance().priority_medium_apps_);
         } else if(app_priority == kLowPriority){
             DatabaseHandler::GetInstance().priority_low_apps_.erase(this->app_name_);
             DatabaseHandler::GetInstance().UpdateRunningApps(kPriorityLowApps, DatabaseHandler::GetInstance().priority_low_apps_);
         } else {}
     } else {
         string msg = "No running apps to delete";
         // LOG(INFO) << msg;
         cout << msg << endl;
     }
     DatabaseHandler::GetInstance().ModifyValue(this->app_name_, kPodName, "");  // Reset the pod name
     DatabaseHandler::GetInstance().ModifyValue(this->app_name_, kPodRunningStatus, "false"); // Reset the running status
     string msg = "Pod is successfully deleted";
     // LOG(INFO) << msg;
     cout << msg << endl;
     return true;
    cout << "Podman has deleted the pods" << endl;
    return true;
 }
References DatabaseHandler::deleted_apps_, DatabaseHandler::GetInstance(), kAppPriority, kDeletedApps, kHighPriority, kLowPriority, kMediumPriority, kPodmanDeletePods, kPodName, kPodRunningStatus, kPriorityHighApps, kPriorityLowApps, kPriorityMediumApps, kRunningApps, DatabaseHandler::ModifyValue(), DatabaseHandler::priority_high_apps_, DatabaseHandler::priority_low_apps_, DatabaseHandler::priority_medium_apps_, DatabaseHandler::ReadData(), DatabaseHandler::running_apps_, and DatabaseHandler::UpdateRunningApps().
Member Data Documentation
app_name_
std::string PodmanDeletePodCommand::app_name_ private
Definition at line 56 of file mco_podman_commands.hpp.
The documentation for this class was generated from the following files:
mc_orchestrator/runtime/inc/mco_podman_commands.hpp
mc_orchestrator/runtime/src/mco_podman_commands.cpp