Mixed Criticality Orchestrator: RespawnPodObserver Class Reference
RespawnPodObserver Class Reference
Public Member Functions
void Update (int avg_cpuUtilization, int avg_memoryUtilization) override
void RespawnAllPods ()
Public Member Functions inherited from Observer
virtual ~Observer ()
Private Attributes
int pod_respawn_cpu_threshold = stoi(config_parameters["pod_respawn_cpu_threshold"])
int pod_respawn_memory_threshold = stoi(config_parameters["pod_respawn_memory_threshold"])
int respawn_counter = 0
Detailed Description
Definition at line 218 of file mco_resource_monitor_handler.cpp.
Member Function Documentation
RespawnAllPods()
void RespawnPodObserver::RespawnAllPods () inline
Definition at line 260 of file mco_resource_monitor_handler.cpp.
{
         // Save existing app name to the database
         ConfigHandler configHandler;
         configHandler.SaveAppNameToDatabase();
         // Call the execute method of ApplyPodCommand
         list<string> running_apps = DatabaseHandler::GetInstance().ReadListData(kRunningApps);
         string container_runtime = config_parameters["container_runtime"];
         string msg = "";
         Invoker invoker;
         for (const auto& app : running_apps) {
             invoker.SetCommand(CommandFactory::CreateCommand(container_runtime, "ApplyPod", app));
             if(!invoker.Invoke()) {
                 msg = "Failed to spawn pod";
                 cout << msg << endl;
                 // LOG(ERROR) << msg;
                 return;
             }
         }
         msg = "All pods respawnned successfully";
         cout << msg << endl;
         // LOG(INFO) << msg;
         UpdateEvent(msg);
     }
References config_parameters, CommandFactory::CreateCommand(), DatabaseHandler::GetInstance(), Invoker::Invoke(), kRunningApps, DatabaseHandler::ReadListData(), ConfigHandler::SaveAppNameToDatabase(), Invoker::SetCommand(), and UpdateEvent().
Update()
void RespawnPodObserver::Update (int avg_cpuUtilization, int avg_memoryUtilization) inline override virtual
Implements Observer.
Definition at line 225 of file mco_resource_monitor_handler.cpp.
{
         // Logic to check if the resource utilization is high
         if(avg_cpuUtilization < pod_respawn_cpu_threshold){
             cout << "CPU utilization is below threshold" << endl;
             is_cpu_utilization_below_pod_respawn_threshold = true;
         } else{
             cout<< "CPU utilization is above threshold" << endl;
             is_cpu_utilization_below_pod_respawn_threshold = false;
         }
         if(avg_memoryUtilization < pod_respawn_memory_threshold){
             cout << "Memory utilization is below threshold" << endl;
             is_memory_utilization_below_pod_respawn_threshold = true;
         } else{
             cout<< "Memory utilization is above threshold" << endl;
             is_memory_utilization_below_pod_respawn_threshold = false;
         }
         // Check if CPU and Memory utilization is below threshold
         if(!(is_cpu_utilization_high or is_memory_utilization_high)){
             // Check if pod is already running
             if(is_memory_utilization_below_pod_respawn_threshold and is_cpu_utilization_below_pod_respawn_threshold) {
                 respawn_counter++;
                 if(respawn_counter >= 20) {
                     string msg = "Respawnning QM pod as CPU and Memory utilization is below threshold";
                     cout << msg << endl;
                     respawn_counter = 0;
                     RespawnAllPods();
                 }
             } else {
                 respawn_counter = 0;
             }
         }
     }
References is_cpu_utilization_below_pod_respawn_threshold, is_cpu_utilization_high, is_memory_utilization_below_pod_respawn_threshold, and is_memory_utilization_high.
Member Data Documentation
pod_respawn_cpu_threshold
int RespawnPodObserver::pod_respawn_cpu_threshold = stoi(config_parameters["pod_respawn_cpu_threshold"]) private
Definition at line 220 of file mco_resource_monitor_handler.cpp.
pod_respawn_memory_threshold
int RespawnPodObserver::pod_respawn_memory_threshold = stoi(config_parameters["pod_respawn_memory_threshold"]) private
Definition at line 221 of file mco_resource_monitor_handler.cpp.
respawn_counter
int RespawnPodObserver::respawn_counter = 0 private
Definition at line 222 of file mco_resource_monitor_handler.cpp.
The documentation for this class was generated from the following file:
mc_orchestrator/bl/src/mco_resource_monitor_handler.cpp