Mixed Criticality Orchestrator: nlohmann::detail::binary_writer< BasicJsonType, CharType > Class Template Reference
nlohmann::detail::binary_writer< BasicJsonType, CharType > Class Template Reference
serialization to CBOR and MessagePack values
#include <binary_writer.hpp>
Public Member Functions
binary_writer (output_adapter_t< CharType > adapter)
create a binary writer
void write_bson (const BasicJsonType &j)
void write_cbor (const BasicJsonType &j)
void write_msgpack (const BasicJsonType &j)
void write_ubjson (const BasicJsonType &j, const bool use_count, const bool use_type, const bool add_prefix=true)
binary_writer (output_adapter_t< CharType > adapter)
create a binary writer
void write_bson (const BasicJsonType &j)
void write_cbor (const BasicJsonType &j)
void write_msgpack (const BasicJsonType &j)
void write_ubjson (const BasicJsonType &j, const bool use_count, const bool use_type, const bool add_prefix=true)
Static Public Member Functions
template<typename C = CharType, enable_if_t< std::is_signed< C >::value and std::is_signed< char >::value > * = nullptr>
static constexpr CharType to_char_type (std::uint8_t x) noexcept
template<typename C = CharType, enable_if_t< std::is_signed< C >::value and std::is_unsigned< char >::value > * = nullptr>
static CharType to_char_type (std::uint8_t x) noexcept
template<typename C = CharType, enable_if_t< std::is_unsigned< C >::value > * = nullptr>
static constexpr CharType to_char_type (std::uint8_t x) noexcept
template<typename InputCharType , typename C = CharType, enable_if_t< std::is_signed< C >::value and std::is_signed< char >::value and std::is_same< char, typename std::remove_cv< InputCharType >::type >::value > * = nullptr>
static constexpr CharType to_char_type (InputCharType x) noexcept
template<typename C = CharType, enable_if_t< std::is_signed< C >::value and std::is_signed< char >::value > * = nullptr>
static constexpr CharType to_char_type (std::uint8_t x) noexcept
template<typename C = CharType, enable_if_t< std::is_signed< C >::value and std::is_unsigned< char >::value > * = nullptr>
static CharType to_char_type (std::uint8_t x) noexcept
template<typename C = CharType, enable_if_t< std::is_unsigned< C >::value > * = nullptr>
static constexpr CharType to_char_type (std::uint8_t x) noexcept
template<typename InputCharType , typename C = CharType, enable_if_t< std::is_signed< C >::value and std::is_signed< char >::value and std::is_same< char, typename std::remove_cv< InputCharType >::type >::value > * = nullptr>
static constexpr CharType to_char_type (InputCharType x) noexcept
Private Types
using string_t = typename BasicJsonType::string_t
using string_t = typename BasicJsonType::string_t
Private Member Functions
void write_bson_entry_header (const string_t &name, const std::uint8_t element_type)
Writes the given element_type and name to the output adapter.
void write_bson_boolean (const string_t &name, const bool value)
Writes a BSON element with key name and boolean value value.
void write_bson_double (const string_t &name, const double value)
Writes a BSON element with key name and double value value.
void write_bson_string (const string_t &name, const string_t &value)
Writes a BSON element with key name and string value value.
void write_bson_null (const string_t &name)
Writes a BSON element with key name and null value.
void write_bson_integer (const string_t &name, const std::int64_t value)
Writes a BSON element with key name and integer value.
void write_bson_unsigned (const string_t &name, const std::uint64_t value)
Writes a BSON element with key name and unsigned value.
void write_bson_object_entry (const string_t &name, const typename BasicJsonType::object_t &value)
Writes a BSON element with key name and object value.
void write_bson_array (const string_t &name, const typename BasicJsonType::array_t &value)
Writes a BSON element with key name and array value.
void write_bson_element (const string_t &name, const BasicJsonType &j)
Serializes the JSON value j to BSON and associates it with the key name.
void write_bson_object (const typename BasicJsonType::object_t &value)
template<typename NumberType , typename std::enable_if< std::is_floating_point< NumberType >::value, int >::type = 0>
void write_number_with_ubjson_prefix (const NumberType n, const bool add_prefix)
template<typename NumberType , typename std::enable_if< std::is_unsigned< NumberType >::value, int >::type = 0>
void write_number_with_ubjson_prefix (const NumberType n, const bool add_prefix)
template<typename NumberType , typename std::enable_if< std::is_signed< NumberType >::value and not std::is_floating_point< NumberType >::value, int >::type = 0>
void write_number_with_ubjson_prefix (const NumberType n, const bool add_prefix)
CharType ubjson_prefix (const BasicJsonType &j) const noexcept
determine the type prefix of container values
template<typename NumberType , bool OutputIsLittleEndian = false>
void write_number (const NumberType n)
void write_bson_entry_header (const string_t &name, const std::uint8_t element_type)
Writes the given element_type and name to the output adapter.
void write_bson_boolean (const string_t &name, const bool value)
Writes a BSON element with key name and boolean value value.
void write_bson_double (const string_t &name, const double value)
Writes a BSON element with key name and double value value.
void write_bson_string (const string_t &name, const string_t &value)
Writes a BSON element with key name and string value value.
void write_bson_null (const string_t &name)
Writes a BSON element with key name and null value.
void write_bson_integer (const string_t &name, const std::int64_t value)
Writes a BSON element with key name and integer value.
void write_bson_unsigned (const string_t &name, const std::uint64_t value)
Writes a BSON element with key name and unsigned value.
void write_bson_object_entry (const string_t &name, const typename BasicJsonType::object_t &value)
Writes a BSON element with key name and object value.
void write_bson_array (const string_t &name, const typename BasicJsonType::array_t &value)
Writes a BSON element with key name and array value.
void write_bson_element (const string_t &name, const BasicJsonType &j)
Serializes the JSON value j to BSON and associates it with the key name.
void write_bson_object (const typename BasicJsonType::object_t &value)
template<typename NumberType , typename std::enable_if< std::is_floating_point< NumberType >::value, int >::type = 0>
void write_number_with_ubjson_prefix (const NumberType n, const bool add_prefix)
template<typename NumberType , typename std::enable_if< std::is_unsigned< NumberType >::value, int >::type = 0>
void write_number_with_ubjson_prefix (const NumberType n, const bool add_prefix)
template<typename NumberType , typename std::enable_if< std::is_signed< NumberType >::value and not std::is_floating_point< NumberType >::value, int >::type = 0>
void write_number_with_ubjson_prefix (const NumberType n, const bool add_prefix)
CharType ubjson_prefix (const BasicJsonType &j) const noexcept
determine the type prefix of container values
template<typename NumberType , bool OutputIsLittleEndian = false>
void write_number (const NumberType n)
Static Private Member Functions
static std::size_t calc_bson_entry_header_size (const string_t &name)
static std::size_t calc_bson_string_size (const string_t &value)
static std::size_t calc_bson_integer_size (const std::int64_t value)
static constexpr std::size_t calc_bson_unsigned_size (const std::uint64_t value) noexcept
static std::size_t calc_bson_array_size (const typename BasicJsonType::array_t &value)
static std::size_t calc_bson_element_size (const string_t &name, const BasicJsonType &j)
Calculates the size necessary to serialize the JSON value j with its name.
static std::size_t calc_bson_object_size (const typename BasicJsonType::object_t &value)
Calculates the size of the BSON serialization of the given JSON-object j.
static constexpr CharType get_cbor_float_prefix (float)
static constexpr CharType get_cbor_float_prefix (double)
static constexpr CharType get_msgpack_float_prefix (float)
static constexpr CharType get_msgpack_float_prefix (double)
static constexpr CharType get_ubjson_float_prefix (float)
static constexpr CharType get_ubjson_float_prefix (double)
static std::size_t calc_bson_entry_header_size (const string_t &name)
static std::size_t calc_bson_string_size (const string_t &value)
static std::size_t calc_bson_integer_size (const std::int64_t value)
static constexpr std::size_t calc_bson_unsigned_size (const std::uint64_t value) noexcept
static std::size_t calc_bson_array_size (const typename BasicJsonType::array_t &value)
static std::size_t calc_bson_element_size (const string_t &name, const BasicJsonType &j)
Calculates the size necessary to serialize the JSON value j with its name.
static std::size_t calc_bson_object_size (const typename BasicJsonType::object_t &value)
Calculates the size of the BSON serialization of the given JSON-object j.
static constexpr CharType get_cbor_float_prefix (float)
static constexpr CharType get_cbor_float_prefix (double)
static constexpr CharType get_msgpack_float_prefix (float)
static constexpr CharType get_msgpack_float_prefix (double)
static constexpr CharType get_ubjson_float_prefix (float)
static constexpr CharType get_ubjson_float_prefix (double)
Private Attributes
const bool is_little_endian = binary_reader<BasicJsonType>::little_endianess()
whether we can assume little endianess
output_adapter_t< CharType > oa = nullptr
the output
Detailed Description
template<typename BasicJsonType, typename CharType>
class nlohmann::detail::binary_writer< BasicJsonType, CharType >
serialization to CBOR and MessagePack values
Definition at line 26 of file binary_writer.hpp.
Member Typedef Documentation
string_t [1/2]
template<typename BasicJsonType , typename CharType > using nlohmann::detail::binary_writer< BasicJsonType, CharType >::string_t = typename BasicJsonType::string_t private
Definition at line 28 of file binary_writer.hpp.
string_t [2/2]
template<typename BasicJsonType , typename CharType > using nlohmann::detail::binary_writer< BasicJsonType, CharType >::string_t = typename BasicJsonType::string_t private
Definition at line 11320 of file json.hpp.
Constructor & Destructor Documentation
binary_writer() [1/2]
template<typename BasicJsonType , typename CharType > nlohmann::detail::binary_writer< BasicJsonType, CharType >::binary_writer (output_adapter_t< CharType > adapter) inline explicit
create a binary writer
Parameters
[in] adapter output adapter to write to
Definition at line 36 of file binary_writer.hpp.
                                                                : oa(adapter)
     {
         assert(oa);
     }
References assert(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa.
binary_writer() [2/2]
template<typename BasicJsonType , typename CharType > nlohmann::detail::binary_writer< BasicJsonType, CharType >::binary_writer (output_adapter_t< CharType > adapter) inline explicit
create a binary writer
Parameters
[in] adapter output adapter to write to
Definition at line 11328 of file json.hpp.
                                                                : oa(adapter)
     {
         assert(oa);
     }
References assert(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa.
Member Function Documentation
calc_bson_array_size() [1/2]
template<typename BasicJsonType , typename CharType > static std::size_t nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_array_size (const typename BasicJsonType::array_t & value) inline static private
Returns
The size of the BSON-encoded array value
Definition at line 862 of file binary_writer.hpp.
     {
         std::size_t array_index = 0ul;
         const std::size_t embedded_document_size = std::accumulate(std::begin(value), std::end(value), 0ul, [&array_index](std::size_t result, const typename BasicJsonType::array_t::value_type & el)
         {
             return result + calc_bson_element_size(std::to_string(array_index++), el);
         });
         return sizeof(std::int32_t) + embedded_document_size + 1ul;
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_element_size(), result, and httplib::to_string().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_element_size(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_array().
calc_bson_array_size() [2/2]
template<typename BasicJsonType , typename CharType > static std::size_t nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_array_size (const typename BasicJsonType::array_t & value) inline static private
Returns
The size of the BSON-encoded array value
Definition at line 12154 of file json.hpp.
     {
         std::size_t array_index = 0ul;
         const std::size_t embedded_document_size = std::accumulate(std::begin(value), std::end(value), 0ul, [&array_index](std::size_t result, const typename BasicJsonType::array_t::value_type & el)
         {
             return result + calc_bson_element_size(std::to_string(array_index++), el);
         });
         return sizeof(std::int32_t) + embedded_document_size + 1ul;
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_element_size(), result, and nlohmann::to_string().
calc_bson_element_size() [1/2]
template<typename BasicJsonType , typename CharType > static std::size_t nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_element_size (const string_t & name, const BasicJsonType & j) inline static private
Calculates the size necessary to serialize the JSON value j with its name.
Returns
The calculated size for the BSON document entry for j with the given name.
Definition at line 897 of file binary_writer.hpp.
     {
         const auto header_size = calc_bson_entry_header_size(name);
         switch (j.type())
         {
             case value_t::object:
                 return header_size + calc_bson_object_size(*j.m_value.object);
             case value_t::array:
                 return header_size + calc_bson_array_size(*j.m_value.array);
             case value_t::boolean:
                 return header_size + 1ul;
             case value_t::number_float:
                 return header_size + 8ul;
             case value_t::number_integer:
                 return header_size + calc_bson_integer_size(j.m_value.number_integer);
             case value_t::number_unsigned:
                 return header_size + calc_bson_unsigned_size(j.m_value.number_unsigned);
             case value_t::string:
                 return header_size + calc_bson_string_size(*j.m_value.string);
             case value_t::null:
                 return header_size + 0ul;
             // LCOV_EXCL_START
             default:
                 assert(false);
                 return 0ul;
                 // LCOV_EXCL_STOP
         }
     }
References nlohmann::detail::array, assert(), nlohmann::detail::boolean, nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_array_size(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_entry_header_size(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_integer_size(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_object_size(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_string_size(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_unsigned_size(), nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::object, and nlohmann::detail::string.
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_array_size().
calc_bson_element_size() [2/2]
template<typename BasicJsonType , typename CharType > static std::size_t nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_element_size (const string_t & name, const BasicJsonType & j) inline static private
Calculates the size necessary to serialize the JSON value j with its name.
Returns
The calculated size for the BSON document entry for j with the given name.
Definition at line 12189 of file json.hpp.
     {
         const auto header_size = calc_bson_entry_header_size(name);
         switch (j.type())
         {
             case value_t::object:
                 return header_size + calc_bson_object_size(*j.m_value.object);
             case value_t::array:
                 return header_size + calc_bson_array_size(*j.m_value.array);
             case value_t::boolean:
                 return header_size + 1ul;
             case value_t::number_float:
                 return header_size + 8ul;
             case value_t::number_integer:
                 return header_size + calc_bson_integer_size(j.m_value.number_integer);
             case value_t::number_unsigned:
                 return header_size + calc_bson_unsigned_size(j.m_value.number_unsigned);
             case value_t::string:
                 return header_size + calc_bson_string_size(*j.m_value.string);
             case value_t::null:
                 return header_size + 0ul;
             // LCOV_EXCL_START
             default:
                 assert(false);
                 return 0ul;
                 // LCOV_EXCL_STOP
         }
     }
References nlohmann::detail::array, assert(), nlohmann::detail::boolean, nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_array_size(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_entry_header_size(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_integer_size(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_object_size(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_string_size(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_unsigned_size(), nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::object, and nlohmann::detail::string.
calc_bson_entry_header_size() [1/2]
template<typename BasicJsonType , typename CharType > static std::size_t nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_entry_header_size (const string_t & name) inline static private
Returns
The size of a BSON document entry header, including the id marker and the entry name size (and its null-terminator).
Definition at line 715 of file binary_writer.hpp.
     {
         const auto it = name.find(static_cast<typename string_t::value_type>(0));
         if (JSON_HEDLEY_UNLIKELY(it != BasicJsonType::string_t::npos))
         {
             JSON_THROW(out_of_range::create(409,
                                             "BSON key cannot contain code point U+0000 (at byte " + std::to_string(it) + ")"));
         }
         return /*id*/ 1ul + name.size() + /*zero-terminator*/1u;
     }
References nlohmann::detail::out_of_range::create(), JSON_HEDLEY_UNLIKELY, JSON_THROW, and httplib::to_string().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_element_size().
calc_bson_entry_header_size() [2/2]
template<typename BasicJsonType , typename CharType > static std::size_t nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_entry_header_size (const string_t & name) inline static private
Returns
The size of a BSON document entry header, including the id marker and the entry name size (and its null-terminator).
Definition at line 12007 of file json.hpp.
     {
         const auto it = name.find(static_cast<typename string_t::value_type>(0));
         if (JSON_HEDLEY_UNLIKELY(it != BasicJsonType::string_t::npos))
         {
             JSON_THROW(out_of_range::create(409,
                                             "BSON key cannot contain code point U+0000 (at byte " + std::to_string(it) + ")"));
         }
         return /*id*/ 1ul + name.size() + /*zero-terminator*/1u;
     }
References nlohmann::detail::out_of_range::create(), JSON_HEDLEY_UNLIKELY, JSON_THROW, and nlohmann::to_string().
calc_bson_integer_size() [1/2]
template<typename BasicJsonType , typename CharType > static std::size_t nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_integer_size (const std::int64_t value) inline static private
Returns
The size of the BSON-encoded integer value
Definition at line 792 of file binary_writer.hpp.
     {
         return (std::numeric_limits<std::int32_t>::min)() <= value and value <= (std::numeric_limits<std::int32_t>::max)()
                ? sizeof(std::int32_t)
                : sizeof(std::int64_t);
     }
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_element_size().
calc_bson_integer_size() [2/2]
template<typename BasicJsonType , typename CharType > static std::size_t nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_integer_size (const std::int64_t value) inline static private
Returns
The size of the BSON-encoded integer value
Definition at line 12084 of file json.hpp.
     {
         return (std::numeric_limits<std::int32_t>::min)() <= value and value <= (std::numeric_limits<std::int32_t>::max)()
                ? sizeof(std::int32_t)
                : sizeof(std::int64_t);
     }
calc_bson_object_size() [1/2]
template<typename BasicJsonType , typename CharType > static std::size_t nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_object_size (const typename BasicJsonType::object_t & value) inline static private
Calculates the size of the BSON serialization of the given JSON-object j.
Parameters
[in] j JSON value to serialize
Precondition
j.type() == value_t::object
Definition at line 985 of file binary_writer.hpp.
     {
         std::size_t document_size = std::accumulate(value.begin(), value.end(), 0ul,
                                     [](size_t result, const typename BasicJsonType::object_t::value_type & el)
         {
             return result += calc_bson_element_size(el.first, el.second);
         });
         return sizeof(std::int32_t) + document_size + 1ul;
     }
References result.
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_element_size(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_object().
calc_bson_object_size() [2/2]
template<typename BasicJsonType , typename CharType > static std::size_t nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_object_size (const typename BasicJsonType::object_t & value) inline static private
Calculates the size of the BSON serialization of the given JSON-object j.
Parameters
[in] j JSON value to serialize
Precondition
j.type() == value_t::object
Definition at line 12277 of file json.hpp.
     {
         std::size_t document_size = std::accumulate(value.begin(), value.end(), 0ul,
                                     [](size_t result, const typename BasicJsonType::object_t::value_type & el)
         {
             return result += calc_bson_element_size(el.first, el.second);
         });
         return sizeof(std::int32_t) + document_size + 1ul;
     }
References result.
calc_bson_string_size() [1/2]
template<typename BasicJsonType , typename CharType > static std::size_t nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_string_size (const string_t & value) inline static private
Returns
The size of the BSON-encoded string in value
Definition at line 762 of file binary_writer.hpp.
     {
         return sizeof(std::int32_t) + value.size() + 1ul;
     }
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_element_size().
calc_bson_string_size() [2/2]
template<typename BasicJsonType , typename CharType > static std::size_t nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_string_size (const string_t & value) inline static private
Returns
The size of the BSON-encoded string in value
Definition at line 12054 of file json.hpp.
     {
         return sizeof(std::int32_t) + value.size() + 1ul;
     }
calc_bson_unsigned_size() [1/2]
template<typename BasicJsonType , typename CharType > static constexpr std::size_t nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_unsigned_size (const std::uint64_t value) inline static constexpr private noexcept
Returns
The size of the BSON-encoded unsigned integer in j
Definition at line 820 of file binary_writer.hpp.
     {
         return (value <= static_cast<std::uint64_t>((std::numeric_limits<std::int32_t>::max)()))
                ? sizeof(std::int32_t)
                : sizeof(std::int64_t);
     }
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_element_size().
calc_bson_unsigned_size() [2/2]
template<typename BasicJsonType , typename CharType > static constexpr std::size_t nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_unsigned_size (const std::uint64_t value) inline static constexpr private noexcept
Returns
The size of the BSON-encoded unsigned integer in j
Definition at line 12112 of file json.hpp.
     {
         return (value <= static_cast<std::uint64_t>((std::numeric_limits<std::int32_t>::max)()))
                ? sizeof(std::int32_t)
                : sizeof(std::int64_t);
     }
get_cbor_float_prefix() [1/4]
template<typename BasicJsonType , typename CharType > static constexpr CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_cbor_float_prefix (double) inline static constexpr private
Definition at line 1021 of file binary_writer.hpp.
     {
         return to_char_type(0xFB);  // Double-Precision Float
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type().
get_cbor_float_prefix() [2/4]
template<typename BasicJsonType , typename CharType > static constexpr CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_cbor_float_prefix (double) inline static constexpr private
Definition at line 12313 of file json.hpp.
     {
         return to_char_type(0xFB);  // Double-Precision Float
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type().
get_cbor_float_prefix() [3/4]
template<typename BasicJsonType , typename CharType > static constexpr CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_cbor_float_prefix (float) inline static constexpr private
Definition at line 1016 of file binary_writer.hpp.
     {
         return to_char_type(0xFA);  // Single-Precision Float
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_cbor().
get_cbor_float_prefix() [4/4]
template<typename BasicJsonType , typename CharType > static constexpr CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_cbor_float_prefix (float) inline static constexpr private
Definition at line 12308 of file json.hpp.
     {
         return to_char_type(0xFA);  // Single-Precision Float
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type().
get_msgpack_float_prefix() [1/4]
template<typename BasicJsonType , typename CharType > static constexpr CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_msgpack_float_prefix (double) inline static constexpr private
Definition at line 1035 of file binary_writer.hpp.
     {
         return to_char_type(0xCB);  // float 64
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type().
get_msgpack_float_prefix() [2/4]
template<typename BasicJsonType , typename CharType > static constexpr CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_msgpack_float_prefix (double) inline static constexpr private
Definition at line 12327 of file json.hpp.
     {
         return to_char_type(0xCB);  // float 64
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type().
get_msgpack_float_prefix() [3/4]
template<typename BasicJsonType , typename CharType > static constexpr CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_msgpack_float_prefix (float) inline static constexpr private
Definition at line 1030 of file binary_writer.hpp.
     {
         return to_char_type(0xCA);  // float 32
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_msgpack().
get_msgpack_float_prefix() [4/4]
template<typename BasicJsonType , typename CharType > static constexpr CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_msgpack_float_prefix (float) inline static constexpr private
Definition at line 12322 of file json.hpp.
     {
         return to_char_type(0xCA);  // float 32
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type().
get_ubjson_float_prefix() [1/4]
template<typename BasicJsonType , typename CharType > static constexpr CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_ubjson_float_prefix (double) inline static constexpr private
Definition at line 1249 of file binary_writer.hpp.
     {
         return 'D';  // float 64
     }
get_ubjson_float_prefix() [2/4]
template<typename BasicJsonType , typename CharType > static constexpr CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_ubjson_float_prefix (double) inline static constexpr private
Definition at line 12541 of file json.hpp.
     {
         return 'D';  // float 64
     }
get_ubjson_float_prefix() [3/4]
template<typename BasicJsonType , typename CharType > static constexpr CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_ubjson_float_prefix (float) inline static constexpr private
Definition at line 1244 of file binary_writer.hpp.
     {
         return 'd';  // float 32
     }
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::ubjson_prefix(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number_with_ubjson_prefix().
get_ubjson_float_prefix() [4/4]
template<typename BasicJsonType , typename CharType > static constexpr CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_ubjson_float_prefix (float) inline static constexpr private
Definition at line 12536 of file json.hpp.
     {
         return 'd';  // float 32
     }
to_char_type() [1/8]
template<typename BasicJsonType , typename CharType > template<typename InputCharType , typename C = CharType, enable_if_t< std::is_signed< C >::value and std::is_signed< char >::value and std::is_same< char, typename std::remove_cv< InputCharType >::type >::value > * = nullptr> static constexpr CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type (InputCharType x) inline static constexpr noexcept
Definition at line 1322 of file binary_writer.hpp.
     {
         return x;
     }
to_char_type() [2/8]
template<typename BasicJsonType , typename CharType > template<typename InputCharType , typename C = CharType, enable_if_t< std::is_signed< C >::value and std::is_signed< char >::value and std::is_same< char, typename std::remove_cv< InputCharType >::type >::value > * = nullptr> static constexpr CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type (InputCharType x) inline static constexpr noexcept
Definition at line 12614 of file json.hpp.
     {
         return x;
     }
to_char_type() [3/8]
template<typename BasicJsonType , typename CharType > template<typename C = CharType, enable_if_t< std::is_signed< C >::value and std::is_signed< char >::value > * = nullptr> static constexpr CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type (std::uint8_t x) inline static constexpr noexcept
Definition at line 1293 of file binary_writer.hpp.
     {
         return *reinterpret_cast<char*>(&x);
     }
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump_escaped(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_cbor_float_prefix(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_msgpack_float_prefix(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_array(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_boolean(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_object(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_cbor(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_msgpack(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number_with_ubjson_prefix(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_ubjson().
to_char_type() [4/8]
template<typename BasicJsonType , typename CharType > template<typename C = CharType, enable_if_t< std::is_signed< C >::value and std::is_unsigned< char >::value > * = nullptr> static CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type (std::uint8_t x) inline static noexcept
Definition at line 1300 of file binary_writer.hpp.
     {
         static_assert(sizeof(std::uint8_t) == sizeof(CharType), "size of CharType must be equal to std::uint8_t");
         static_assert(std::is_pod<CharType>::value, "CharType must be POD");
         CharType result;
         std::memcpy(&result, &x, sizeof(x));
         return result;
     }
References result.
to_char_type() [5/8]
template<typename BasicJsonType , typename CharType > template<typename C = CharType, enable_if_t< std::is_unsigned< C >::value > * = nullptr> static constexpr CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type (std::uint8_t x) inline static constexpr noexcept
Definition at line 1311 of file binary_writer.hpp.
     {
         return x;
     }
to_char_type() [6/8]
template<typename BasicJsonType , typename CharType > template<typename C = CharType, enable_if_t< std::is_signed< C >::value and std::is_signed< char >::value > * = nullptr> static constexpr CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type (std::uint8_t x) inline static constexpr noexcept
Definition at line 12585 of file json.hpp.
     {
         return *reinterpret_cast<char*>(&x);
     }
to_char_type() [7/8]
template<typename BasicJsonType , typename CharType > template<typename C = CharType, enable_if_t< std::is_signed< C >::value and std::is_unsigned< char >::value > * = nullptr> static CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type (std::uint8_t x) inline static noexcept
Definition at line 12592 of file json.hpp.
     {
         static_assert(sizeof(std::uint8_t) == sizeof(CharType), "size of CharType must be equal to std::uint8_t");
         static_assert(std::is_pod<CharType>::value, "CharType must be POD");
         CharType result;
         std::memcpy(&result, &x, sizeof(x));
         return result;
     }
References result.
to_char_type() [8/8]
template<typename BasicJsonType , typename CharType > template<typename C = CharType, enable_if_t< std::is_unsigned< C >::value > * = nullptr> static constexpr CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type (std::uint8_t x) inline static constexpr noexcept
Definition at line 12603 of file json.hpp.
     {
         return x;
     }
ubjson_prefix() [1/2]
template<typename BasicJsonType , typename CharType > CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::ubjson_prefix (const BasicJsonType & j) const inline private noexcept
determine the type prefix of container values
Note
This function does not need to be 100% accurate when it comes to integer limits. In case a number exceeds the limits of int64_t, this will be detected by a later call to function write_number_with_ubjson_prefix. Therefore, we return 'L' for any value that does not fit the previous limits.
Definition at line 1173 of file binary_writer.hpp.
     {
         switch (j.type())
         {
             case value_t::null:
                 return 'Z';
             case value_t::boolean:
                 return j.m_value.boolean ? 'T' : 'F';
             case value_t::number_integer:
             {
                 if ((std::numeric_limits<std::int8_t>::min)() <= j.m_value.number_integer and j.m_value.number_integer <= (std::numeric_limits<std::int8_t>::max)())
                 {
                     return 'i';
                 }
                 if ((std::numeric_limits<std::uint8_t>::min)() <= j.m_value.number_integer and j.m_value.number_integer <= (std::numeric_limits<std::uint8_t>::max)())
                 {
                     return 'U';
                 }
                 if ((std::numeric_limits<std::int16_t>::min)() <= j.m_value.number_integer and j.m_value.number_integer <= (std::numeric_limits<std::int16_t>::max)())
                 {
                     return 'I';
                 }
                 if ((std::numeric_limits<std::int32_t>::min)() <= j.m_value.number_integer and j.m_value.number_integer <= (std::numeric_limits<std::int32_t>::max)())
                 {
                     return 'l';
                 }
                 // no check and assume int64_t (see note above)
                 return 'L';
             }
             case value_t::number_unsigned:
             {
                 if (j.m_value.number_unsigned <= static_cast<std::uint64_t>((std::numeric_limits<std::int8_t>::max)()))
                 {
                     return 'i';
                 }
                 if (j.m_value.number_unsigned <= static_cast<std::uint64_t>((std::numeric_limits<std::uint8_t>::max)()))
                 {
                     return 'U';
                 }
                 if (j.m_value.number_unsigned <= static_cast<std::uint64_t>((std::numeric_limits<std::int16_t>::max)()))
                 {
                     return 'I';
                 }
                 if (j.m_value.number_unsigned <= static_cast<std::uint64_t>((std::numeric_limits<std::int32_t>::max)()))
                 {
                     return 'l';
                 }
                 // no check and assume int64_t (see note above)
                 return 'L';
             }
             case value_t::number_float:
                 return get_ubjson_float_prefix(j.m_value.number_float);
             case value_t::string:
                 return 'S';
             case value_t::array:
                 return '[';
             case value_t::object:
                 return '{';
             default:  // discarded values
                 return 'N';
         }
     }
References nlohmann::detail::array, nlohmann::detail::boolean, nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_ubjson_float_prefix(), nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::object, and nlohmann::detail::string.
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_ubjson().
ubjson_prefix() [2/2]
template<typename BasicJsonType , typename CharType > CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::ubjson_prefix (const BasicJsonType & j) const inline private noexcept
determine the type prefix of container values
Note
This function does not need to be 100% accurate when it comes to integer limits. In case a number exceeds the limits of int64_t, this will be detected by a later call to function write_number_with_ubjson_prefix. Therefore, we return 'L' for any value that does not fit the previous limits.
Definition at line 12465 of file json.hpp.
     {
         switch (j.type())
         {
             case value_t::null:
                 return 'Z';
             case value_t::boolean:
                 return j.m_value.boolean ? 'T' : 'F';
             case value_t::number_integer:
             {
                 if ((std::numeric_limits<std::int8_t>::min)() <= j.m_value.number_integer and j.m_value.number_integer <= (std::numeric_limits<std::int8_t>::max)())
                 {
                     return 'i';
                 }
                 if ((std::numeric_limits<std::uint8_t>::min)() <= j.m_value.number_integer and j.m_value.number_integer <= (std::numeric_limits<std::uint8_t>::max)())
                 {
                     return 'U';
                 }
                 if ((std::numeric_limits<std::int16_t>::min)() <= j.m_value.number_integer and j.m_value.number_integer <= (std::numeric_limits<std::int16_t>::max)())
                 {
                     return 'I';
                 }
                 if ((std::numeric_limits<std::int32_t>::min)() <= j.m_value.number_integer and j.m_value.number_integer <= (std::numeric_limits<std::int32_t>::max)())
                 {
                     return 'l';
                 }
                 // no check and assume int64_t (see note above)
                 return 'L';
             }
             case value_t::number_unsigned:
             {
                 if (j.m_value.number_unsigned <= static_cast<std::uint64_t>((std::numeric_limits<std::int8_t>::max)()))
                 {
                     return 'i';
                 }
                 if (j.m_value.number_unsigned <= static_cast<std::uint64_t>((std::numeric_limits<std::uint8_t>::max)()))
                 {
                     return 'U';
                 }
                 if (j.m_value.number_unsigned <= static_cast<std::uint64_t>((std::numeric_limits<std::int16_t>::max)()))
                 {
                     return 'I';
                 }
                 if (j.m_value.number_unsigned <= static_cast<std::uint64_t>((std::numeric_limits<std::int32_t>::max)()))
                 {
                     return 'l';
                 }
                 // no check and assume int64_t (see note above)
                 return 'L';
             }
             case value_t::number_float:
                 return get_ubjson_float_prefix(j.m_value.number_float);
             case value_t::string:
                 return 'S';
             case value_t::array:
                 return '[';
             case value_t::object:
                 return '{';
             default:  // discarded values
                 return 'N';
         }
     }
References nlohmann::detail::array, nlohmann::detail::boolean, nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_ubjson_float_prefix(), nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::object, and nlohmann::detail::string.
write_bson() [1/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson (const BasicJsonType & j) inline
Parameters
[in] j JSON value to serialize
Precondition
j.type() == value_t::object
Definition at line 45 of file binary_writer.hpp.
     {
         switch (j.type())
         {
             case value_t::object:
             {
                 write_bson_object(*j.m_value.object);
                 break;
             }
             default:
             {
                 JSON_THROW(type_error::create(317, "to serialize to BSON, top-level type must be object, but is " + std::string(j.type_name())));
             }
         }
     }
References nlohmann::detail::type_error::create(), JSON_THROW, nlohmann::detail::object, and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_object().
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::to_bson().
write_bson() [2/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson (const BasicJsonType & j) inline
Parameters
[in] j JSON value to serialize
Precondition
j.type() == value_t::object
Definition at line 11337 of file json.hpp.
     {
         switch (j.type())
         {
             case value_t::object:
             {
                 write_bson_object(*j.m_value.object);
                 break;
             }
             default:
             {
                 JSON_THROW(type_error::create(317, "to serialize to BSON, top-level type must be object, but is " + std::string(j.type_name())));
             }
         }
     }
References nlohmann::detail::type_error::create(), JSON_THROW, nlohmann::detail::object, and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_object().
write_bson_array() [1/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_array (const string_t & name, const typename BasicJsonType::array_t & value) inline private
Writes a BSON element with key name and array value.
Definition at line 877 of file binary_writer.hpp.
     {
         write_bson_entry_header(name, 0x04); // array
         write_number<std::int32_t, true>(static_cast<std::int32_t>(calc_bson_array_size(value)));
         std::size_t array_index = 0ul;
         for (const auto& el : value)
         {
             write_bson_element(std::to_string(array_index++), el);
         }
         oa->write_character(to_char_type(0x00));
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_array_size(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), httplib::to_string(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_element(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_element().
write_bson_array() [2/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_array (const string_t & name, const typename BasicJsonType::array_t & value) inline private
Writes a BSON element with key name and array value.
Definition at line 12169 of file json.hpp.
     {
         write_bson_entry_header(name, 0x04); // array
         write_number<std::int32_t, true>(static_cast<std::int32_t>(calc_bson_array_size(value)));
         std::size_t array_index = 0ul;
         for (const auto& el : value)
         {
             write_bson_element(std::to_string(array_index++), el);
         }
         oa->write_character(to_char_type(0x00));
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_array_size(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), nlohmann::to_string(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_element(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header().
write_bson_boolean() [1/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_boolean (const string_t & name, const bool value) inline private
Writes a BSON element with key name and boolean value value.
Definition at line 742 of file binary_writer.hpp.
     {
         write_bson_entry_header(name, 0x08);
         oa->write_character(value ? to_char_type(0x01) : to_char_type(0x00));
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_element().
write_bson_boolean() [2/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_boolean (const string_t & name, const bool value) inline private
Writes a BSON element with key name and boolean value value.
Definition at line 12034 of file json.hpp.
     {
         write_bson_entry_header(name, 0x08);
         oa->write_character(value ? to_char_type(0x01) : to_char_type(0x00));
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header().
write_bson_double() [1/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_double (const string_t & name, const double value) inline private
Writes a BSON element with key name and double value value.
Definition at line 752 of file binary_writer.hpp.
     {
         write_bson_entry_header(name, 0x01);
         write_number<double, true>(value);
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_element().
write_bson_double() [2/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_double (const string_t & name, const double value) inline private
Writes a BSON element with key name and double value value.
Definition at line 12044 of file json.hpp.
     {
         write_bson_entry_header(name, 0x01);
         write_number<double, true>(value);
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header().
write_bson_element() [1/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_element (const string_t & name, const BasicJsonType & j) inline private
Serializes the JSON value j to BSON and associates it with the key name.
Parameters
name The name to associate with the JSON entity j within the current BSON document
Returns
The size of the BSON entry
Definition at line 942 of file binary_writer.hpp.
     {
         switch (j.type())
         {
             case value_t::object:
                 return write_bson_object_entry(name, *j.m_value.object);
             case value_t::array:
                 return write_bson_array(name, *j.m_value.array);
             case value_t::boolean:
                 return write_bson_boolean(name, j.m_value.boolean);
             case value_t::number_float:
                 return write_bson_double(name, j.m_value.number_float);
             case value_t::number_integer:
                 return write_bson_integer(name, j.m_value.number_integer);
             case value_t::number_unsigned:
                 return write_bson_unsigned(name, j.m_value.number_unsigned);
             case value_t::string:
                 return write_bson_string(name, *j.m_value.string);
             case value_t::null:
                 return write_bson_null(name);
             // LCOV_EXCL_START
             default:
                 assert(false);
                 return;
                 // LCOV_EXCL_STOP
         }
     }
References nlohmann::detail::array, assert(), nlohmann::detail::boolean, nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::object, nlohmann::detail::string, nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_array(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_boolean(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_double(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_integer(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_null(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_object_entry(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_string(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_unsigned().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_array(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_object().
write_bson_element() [2/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_element (const string_t & name, const BasicJsonType & j) inline private
Serializes the JSON value j to BSON and associates it with the key name.
Parameters
name The name to associate with the JSON entity j within the current BSON document
Returns
The size of the BSON entry
Definition at line 12234 of file json.hpp.
     {
         switch (j.type())
         {
             case value_t::object:
                 return write_bson_object_entry(name, *j.m_value.object);
             case value_t::array:
                 return write_bson_array(name, *j.m_value.array);
             case value_t::boolean:
                 return write_bson_boolean(name, j.m_value.boolean);
             case value_t::number_float:
                 return write_bson_double(name, j.m_value.number_float);
             case value_t::number_integer:
                 return write_bson_integer(name, j.m_value.number_integer);
             case value_t::number_unsigned:
                 return write_bson_unsigned(name, j.m_value.number_unsigned);
             case value_t::string:
                 return write_bson_string(name, *j.m_value.string);
             case value_t::null:
                 return write_bson_null(name);
             // LCOV_EXCL_START
             default:
                 assert(false);
                 return;
                 // LCOV_EXCL_STOP
         }
     }
References nlohmann::detail::array, assert(), nlohmann::detail::boolean, nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::object, nlohmann::detail::string, nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_array(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_boolean(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_double(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_integer(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_null(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_object_entry(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_string(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_unsigned().
write_bson_entry_header() [1/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header (const string_t & name, const std::uint8_t element_type) inline private
Writes the given element_type and name to the output adapter.
Definition at line 730 of file binary_writer.hpp.
     {
         oa->write_character(to_char_type(element_type)); // boolean
         oa->write_characters(
             reinterpret_cast<const CharType*>(name.c_str()),
             name.size() + 1u);
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, and nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_array(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_boolean(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_double(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_integer(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_null(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_object_entry(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_string(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_unsigned().
write_bson_entry_header() [2/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header (const string_t & name, const std::uint8_t element_type) inline private
Writes the given element_type and name to the output adapter.
Definition at line 12022 of file json.hpp.
     {
         oa->write_character(to_char_type(element_type)); // boolean
         oa->write_characters(
             reinterpret_cast<const CharType*>(name.c_str()),
             name.size() + 1u);
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, and nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type().
write_bson_integer() [1/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_integer (const string_t & name, const std::int64_t value) inline private
Writes a BSON element with key name and integer value.
Definition at line 802 of file binary_writer.hpp.
     {
         if ((std::numeric_limits<std::int32_t>::min)() <= value and value <= (std::numeric_limits<std::int32_t>::max)())
         {
             write_bson_entry_header(name, 0x10); // int32
             write_number<std::int32_t, true>(static_cast<std::int32_t>(value));
         }
         else
         {
             write_bson_entry_header(name, 0x12); // int64
             write_number<std::int64_t, true>(static_cast<std::int64_t>(value));
         }
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_element().
write_bson_integer() [2/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_integer (const string_t & name, const std::int64_t value) inline private
Writes a BSON element with key name and integer value.
Definition at line 12094 of file json.hpp.
     {
         if ((std::numeric_limits<std::int32_t>::min)() <= value and value <= (std::numeric_limits<std::int32_t>::max)())
         {
             write_bson_entry_header(name, 0x10); // int32
             write_number<std::int32_t, true>(static_cast<std::int32_t>(value));
         }
         else
         {
             write_bson_entry_header(name, 0x12); // int64
             write_number<std::int64_t, true>(static_cast<std::int64_t>(value));
         }
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header().
write_bson_null() [1/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_null (const string_t & name) inline private
Writes a BSON element with key name and null value.
Definition at line 784 of file binary_writer.hpp.
     {
         write_bson_entry_header(name, 0x0A);
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_element().
write_bson_null() [2/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_null (const string_t & name) inline private
Writes a BSON element with key name and null value.
Definition at line 12076 of file json.hpp.
     {
         write_bson_entry_header(name, 0x0A);
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header().
write_bson_object() [1/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_object (const typename BasicJsonType::object_t & value) inline private
Parameters
[in] j JSON value to serialize
Precondition
j.type() == value_t::object
Definition at line 1000 of file binary_writer.hpp.
     {
         write_number<std::int32_t, true>(static_cast<std::int32_t>(calc_bson_object_size(value)));
         for (const auto& el : value)
         {
             write_bson_element(el.first, el.second);
         }
         oa->write_character(to_char_type(0x00));
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_object_size(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_element().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_object_entry().
write_bson_object() [2/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_object (const typename BasicJsonType::object_t & value) inline private
Parameters
[in] j JSON value to serialize
Precondition
j.type() == value_t::object
Definition at line 12292 of file json.hpp.
     {
         write_number<std::int32_t, true>(static_cast<std::int32_t>(calc_bson_object_size(value)));
         for (const auto& el : value)
         {
             write_bson_element(el.first, el.second);
         }
         oa->write_character(to_char_type(0x00));
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_object_size(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_element().
write_bson_object_entry() [1/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_object_entry (const string_t & name, const typename BasicJsonType::object_t & value) inline private
Writes a BSON element with key name and object value.
Definition at line 852 of file binary_writer.hpp.
     {
         write_bson_entry_header(name, 0x03); // object
         write_bson_object(value);
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_object().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_element().
write_bson_object_entry() [2/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_object_entry (const string_t & name, const typename BasicJsonType::object_t & value) inline private
Writes a BSON element with key name and object value.
Definition at line 12144 of file json.hpp.
     {
         write_bson_entry_header(name, 0x03); // object
         write_bson_object(value);
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_object().
write_bson_string() [1/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_string (const string_t & name, const string_t & value) inline private
Writes a BSON element with key name and string value value.
Definition at line 770 of file binary_writer.hpp.
     {
         write_bson_entry_header(name, 0x02);
         write_number<std::int32_t, true>(static_cast<std::int32_t>(value.size() + 1ul));
         oa->write_characters(
             reinterpret_cast<const CharType*>(value.c_str()),
             value.size() + 1);
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_element().
write_bson_string() [2/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_string (const string_t & name, const string_t & value) inline private
Writes a BSON element with key name and string value value.
Definition at line 12062 of file json.hpp.
     {
         write_bson_entry_header(name, 0x02);
         write_number<std::int32_t, true>(static_cast<std::int32_t>(value.size() + 1ul));
         oa->write_characters(
             reinterpret_cast<const CharType*>(value.c_str()),
             value.size() + 1);
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header().
write_bson_unsigned() [1/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_unsigned (const string_t & name, const std::uint64_t value) inline private
Writes a BSON element with key name and unsigned value.
Definition at line 830 of file binary_writer.hpp.
     {
         if (value <= static_cast<std::uint64_t>((std::numeric_limits<std::int32_t>::max)()))
         {
             write_bson_entry_header(name, 0x10 /* int32 */);
             write_number<std::int32_t, true>(static_cast<std::int32_t>(value));
         }
         else if (value <= static_cast<std::uint64_t>((std::numeric_limits<std::int64_t>::max)()))
         {
             write_bson_entry_header(name, 0x12 /* int64 */);
             write_number<std::int64_t, true>(static_cast<std::int64_t>(value));
         }
         else
         {
             JSON_THROW(out_of_range::create(407, "integer number " + std::to_string(value) + " cannot be represented by BSON as it does not fit int64"));
         }
     }
References nlohmann::detail::out_of_range::create(), JSON_THROW, httplib::to_string(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_element().
write_bson_unsigned() [2/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_unsigned (const string_t & name, const std::uint64_t value) inline private
Writes a BSON element with key name and unsigned value.
Definition at line 12122 of file json.hpp.
     {
         if (value <= static_cast<std::uint64_t>((std::numeric_limits<std::int32_t>::max)()))
         {
             write_bson_entry_header(name, 0x10 /* int32 */);
             write_number<std::int32_t, true>(static_cast<std::int32_t>(value));
         }
         else if (value <= static_cast<std::uint64_t>((std::numeric_limits<std::int64_t>::max)()))
         {
             write_bson_entry_header(name, 0x12 /* int64 */);
             write_number<std::int64_t, true>(static_cast<std::int64_t>(value));
         }
         else
         {
             JSON_THROW(out_of_range::create(407, "integer number " + std::to_string(value) + " cannot be represented by BSON as it does not fit int64"));
         }
     }
References nlohmann::detail::out_of_range::create(), JSON_THROW, nlohmann::to_string(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header().
write_cbor() [1/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_cbor (const BasicJsonType & j) inline
Parameters
[in] j JSON value to serialize
Definition at line 65 of file binary_writer.hpp.
     {
         switch (j.type())
         {
             case value_t::null:
             {
                 oa->write_character(to_char_type(0xF6));
                 break;
             }
             case value_t::boolean:
             {
                 oa->write_character(j.m_value.boolean
                                     ? to_char_type(0xF5)
                                     : to_char_type(0xF4));
                 break;
             }
             case value_t::number_integer:
             {
                 if (j.m_value.number_integer >= 0)
                 {
                     // CBOR does not differentiate between positive signed
                     // integers and unsigned integers. Therefore, we used the
                     // code from the value_t::number_unsigned case here.
                     if (j.m_value.number_integer <= 0x17)
                     {
                         write_number(static_cast<std::uint8_t>(j.m_value.number_integer));
                     }
                     else if (j.m_value.number_integer <= (std::numeric_limits<std::uint8_t>::max)())
                     {
                         oa->write_character(to_char_type(0x18));
                         write_number(static_cast<std::uint8_t>(j.m_value.number_integer));
                     }
                     else if (j.m_value.number_integer <= (std::numeric_limits<std::uint16_t>::max)())
                     {
                         oa->write_character(to_char_type(0x19));
                         write_number(static_cast<std::uint16_t>(j.m_value.number_integer));
                     }
                     else if (j.m_value.number_integer <= (std::numeric_limits<std::uint32_t>::max)())
                     {
                         oa->write_character(to_char_type(0x1A));
                         write_number(static_cast<std::uint32_t>(j.m_value.number_integer));
                     }
                     else
                     {
                         oa->write_character(to_char_type(0x1B));
                         write_number(static_cast<std::uint64_t>(j.m_value.number_integer));
                     }
                 }
                 else
                 {
                     // The conversions below encode the sign in the first
                     // byte, and the value is converted to a positive number.
                     const auto positive_number = -1 - j.m_value.number_integer;
                     if (j.m_value.number_integer >= -24)
                     {
                         write_number(static_cast<std::uint8_t>(0x20 + positive_number));
                     }
                     else if (positive_number <= (std::numeric_limits<std::uint8_t>::max)())
                     {
                         oa->write_character(to_char_type(0x38));
                         write_number(static_cast<std::uint8_t>(positive_number));
                     }
                     else if (positive_number <= (std::numeric_limits<std::uint16_t>::max)())
                     {
                         oa->write_character(to_char_type(0x39));
                         write_number(static_cast<std::uint16_t>(positive_number));
                     }
                     else if (positive_number <= (std::numeric_limits<std::uint32_t>::max)())
                     {
                         oa->write_character(to_char_type(0x3A));
                         write_number(static_cast<std::uint32_t>(positive_number));
                     }
                     else
                     {
                         oa->write_character(to_char_type(0x3B));
                         write_number(static_cast<std::uint64_t>(positive_number));
                     }
                 }
                 break;
             }
             case value_t::number_unsigned:
             {
                 if (j.m_value.number_unsigned <= 0x17)
                 {
                     write_number(static_cast<std::uint8_t>(j.m_value.number_unsigned));
                 }
                 else if (j.m_value.number_unsigned <= (std::numeric_limits<std::uint8_t>::max)())
                 {
                     oa->write_character(to_char_type(0x18));
                     write_number(static_cast<std::uint8_t>(j.m_value.number_unsigned));
                 }
                 else if (j.m_value.number_unsigned <= (std::numeric_limits<std::uint16_t>::max)())
                 {
                     oa->write_character(to_char_type(0x19));
                     write_number(static_cast<std::uint16_t>(j.m_value.number_unsigned));
                 }
                 else if (j.m_value.number_unsigned <= (std::numeric_limits<std::uint32_t>::max)())
                 {
                     oa->write_character(to_char_type(0x1A));
                     write_number(static_cast<std::uint32_t>(j.m_value.number_unsigned));
                 }
                 else
                 {
                     oa->write_character(to_char_type(0x1B));
                     write_number(static_cast<std::uint64_t>(j.m_value.number_unsigned));
                 }
                 break;
             }
             case value_t::number_float:
             {
                 oa->write_character(get_cbor_float_prefix(j.m_value.number_float));
                 write_number(j.m_value.number_float);
                 break;
             }
             case value_t::string:
             {
                 // step 1: write control byte and the string length
                 const auto N = j.m_value.string->size();
                 if (N <= 0x17)
                 {
                     write_number(static_cast<std::uint8_t>(0x60 + N));
                 }
                 else if (N <= (std::numeric_limits<std::uint8_t>::max)())
                 {
                     oa->write_character(to_char_type(0x78));
                     write_number(static_cast<std::uint8_t>(N));
                 }
                 else if (N <= (std::numeric_limits<std::uint16_t>::max)())
                 {
                     oa->write_character(to_char_type(0x79));
                     write_number(static_cast<std::uint16_t>(N));
                 }
                 else if (N <= (std::numeric_limits<std::uint32_t>::max)())
                 {
                     oa->write_character(to_char_type(0x7A));
                     write_number(static_cast<std::uint32_t>(N));
                 }
                 // LCOV_EXCL_START
                 else if (N <= (std::numeric_limits<std::uint64_t>::max)())
                 {
                     oa->write_character(to_char_type(0x7B));
                     write_number(static_cast<std::uint64_t>(N));
                 }
                 // LCOV_EXCL_STOP
                 // step 2: write the string
                 oa->write_characters(
                     reinterpret_cast<const CharType*>(j.m_value.string->c_str()),
                     j.m_value.string->size());
                 break;
             }
             case value_t::array:
             {
                 // step 1: write control byte and the array size
                 const auto N = j.m_value.array->size();
                 if (N <= 0x17)
                 {
                     write_number(static_cast<std::uint8_t>(0x80 + N));
                 }
                 else if (N <= (std::numeric_limits<std::uint8_t>::max)())
                 {
                     oa->write_character(to_char_type(0x98));
                     write_number(static_cast<std::uint8_t>(N));
                 }
                 else if (N <= (std::numeric_limits<std::uint16_t>::max)())
                 {
                     oa->write_character(to_char_type(0x99));
                     write_number(static_cast<std::uint16_t>(N));
                 }
                 else if (N <= (std::numeric_limits<std::uint32_t>::max)())
                 {
                     oa->write_character(to_char_type(0x9A));
                     write_number(static_cast<std::uint32_t>(N));
                 }
                 // LCOV_EXCL_START
                 else if (N <= (std::numeric_limits<std::uint64_t>::max)())
                 {
                     oa->write_character(to_char_type(0x9B));
                     write_number(static_cast<std::uint64_t>(N));
                 }
                 // LCOV_EXCL_STOP
                 // step 2: write each element
                 for (const auto& el : *j.m_value.array)
                 {
                     write_cbor(el);
                 }
                 break;
             }
             case value_t::object:
             {
                 // step 1: write control byte and the object size
                 const auto N = j.m_value.object->size();
                 if (N <= 0x17)
                 {
                     write_number(static_cast<std::uint8_t>(0xA0 + N));
                 }
                 else if (N <= (std::numeric_limits<std::uint8_t>::max)())
                 {
                     oa->write_character(to_char_type(0xB8));
                     write_number(static_cast<std::uint8_t>(N));
                 }
                 else if (N <= (std::numeric_limits<std::uint16_t>::max)())
                 {
                     oa->write_character(to_char_type(0xB9));
                     write_number(static_cast<std::uint16_t>(N));
                 }
                 else if (N <= (std::numeric_limits<std::uint32_t>::max)())
                 {
                     oa->write_character(to_char_type(0xBA));
                     write_number(static_cast<std::uint32_t>(N));
                 }
                 // LCOV_EXCL_START
                 else if (N <= (std::numeric_limits<std::uint64_t>::max)())
                 {
                     oa->write_character(to_char_type(0xBB));
                     write_number(static_cast<std::uint64_t>(N));
                 }
                 // LCOV_EXCL_STOP
                 // step 2: write each element
                 for (const auto& el : *j.m_value.object)
                 {
                     write_cbor(el.first);
                     write_cbor(el.second);
                 }
                 break;
             }
             default:
                 break;
         }
     }
References nlohmann::detail::array, nlohmann::detail::boolean, nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_cbor_float_prefix(), N, nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, nlohmann::detail::object, nlohmann::detail::string, nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number().
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::to_cbor(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_cbor().
write_cbor() [2/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_cbor (const BasicJsonType & j) inline
Parameters
[in] j JSON value to serialize
Definition at line 11357 of file json.hpp.
     {
         switch (j.type())
         {
             case value_t::null:
             {
                 oa->write_character(to_char_type(0xF6));
                 break;
             }
             case value_t::boolean:
             {
                 oa->write_character(j.m_value.boolean
                                     ? to_char_type(0xF5)
                                     : to_char_type(0xF4));
                 break;
             }
             case value_t::number_integer:
             {
                 if (j.m_value.number_integer >= 0)
                 {
                     // CBOR does not differentiate between positive signed
                     // integers and unsigned integers. Therefore, we used the
                     // code from the value_t::number_unsigned case here.
                     if (j.m_value.number_integer <= 0x17)
                     {
                         write_number(static_cast<std::uint8_t>(j.m_value.number_integer));
                     }
                     else if (j.m_value.number_integer <= (std::numeric_limits<std::uint8_t>::max)())
                     {
                         oa->write_character(to_char_type(0x18));
                         write_number(static_cast<std::uint8_t>(j.m_value.number_integer));
                     }
                     else if (j.m_value.number_integer <= (std::numeric_limits<std::uint16_t>::max)())
                     {
                         oa->write_character(to_char_type(0x19));
                         write_number(static_cast<std::uint16_t>(j.m_value.number_integer));
                     }
                     else if (j.m_value.number_integer <= (std::numeric_limits<std::uint32_t>::max)())
                     {
                         oa->write_character(to_char_type(0x1A));
                         write_number(static_cast<std::uint32_t>(j.m_value.number_integer));
                     }
                     else
                     {
                         oa->write_character(to_char_type(0x1B));
                         write_number(static_cast<std::uint64_t>(j.m_value.number_integer));
                     }
                 }
                 else
                 {
                     // The conversions below encode the sign in the first
                     // byte, and the value is converted to a positive number.
                     const auto positive_number = -1 - j.m_value.number_integer;
                     if (j.m_value.number_integer >= -24)
                     {
                         write_number(static_cast<std::uint8_t>(0x20 + positive_number));
                     }
                     else if (positive_number <= (std::numeric_limits<std::uint8_t>::max)())
                     {
                         oa->write_character(to_char_type(0x38));
                         write_number(static_cast<std::uint8_t>(positive_number));
                     }
                     else if (positive_number <= (std::numeric_limits<std::uint16_t>::max)())
                     {
                         oa->write_character(to_char_type(0x39));
                         write_number(static_cast<std::uint16_t>(positive_number));
                     }
                     else if (positive_number <= (std::numeric_limits<std::uint32_t>::max)())
                     {
                         oa->write_character(to_char_type(0x3A));
                         write_number(static_cast<std::uint32_t>(positive_number));
                     }
                     else
                     {
                         oa->write_character(to_char_type(0x3B));
                         write_number(static_cast<std::uint64_t>(positive_number));
                     }
                 }
                 break;
             }
             case value_t::number_unsigned:
             {
                 if (j.m_value.number_unsigned <= 0x17)
                 {
                     write_number(static_cast<std::uint8_t>(j.m_value.number_unsigned));
                 }
                 else if (j.m_value.number_unsigned <= (std::numeric_limits<std::uint8_t>::max)())
                 {
                     oa->write_character(to_char_type(0x18));
                     write_number(static_cast<std::uint8_t>(j.m_value.number_unsigned));
                 }
                 else if (j.m_value.number_unsigned <= (std::numeric_limits<std::uint16_t>::max)())
                 {
                     oa->write_character(to_char_type(0x19));
                     write_number(static_cast<std::uint16_t>(j.m_value.number_unsigned));
                 }
                 else if (j.m_value.number_unsigned <= (std::numeric_limits<std::uint32_t>::max)())
                 {
                     oa->write_character(to_char_type(0x1A));
                     write_number(static_cast<std::uint32_t>(j.m_value.number_unsigned));
                 }
                 else
                 {
                     oa->write_character(to_char_type(0x1B));
                     write_number(static_cast<std::uint64_t>(j.m_value.number_unsigned));
                 }
                 break;
             }
             case value_t::number_float:
             {
                 oa->write_character(get_cbor_float_prefix(j.m_value.number_float));
                 write_number(j.m_value.number_float);
                 break;
             }
             case value_t::string:
             {
                 // step 1: write control byte and the string length
                 const auto N = j.m_value.string->size();
                 if (N <= 0x17)
                 {
                     write_number(static_cast<std::uint8_t>(0x60 + N));
                 }
                 else if (N <= (std::numeric_limits<std::uint8_t>::max)())
                 {
                     oa->write_character(to_char_type(0x78));
                     write_number(static_cast<std::uint8_t>(N));
                 }
                 else if (N <= (std::numeric_limits<std::uint16_t>::max)())
                 {
                     oa->write_character(to_char_type(0x79));
                     write_number(static_cast<std::uint16_t>(N));
                 }
                 else if (N <= (std::numeric_limits<std::uint32_t>::max)())
                 {
                     oa->write_character(to_char_type(0x7A));
                     write_number(static_cast<std::uint32_t>(N));
                 }
                 // LCOV_EXCL_START
                 else if (N <= (std::numeric_limits<std::uint64_t>::max)())
                 {
                     oa->write_character(to_char_type(0x7B));
                     write_number(static_cast<std::uint64_t>(N));
                 }
                 // LCOV_EXCL_STOP
                 // step 2: write the string
                 oa->write_characters(
                     reinterpret_cast<const CharType*>(j.m_value.string->c_str()),
                     j.m_value.string->size());
                 break;
             }
             case value_t::array:
             {
                 // step 1: write control byte and the array size
                 const auto N = j.m_value.array->size();
                 if (N <= 0x17)
                 {
                     write_number(static_cast<std::uint8_t>(0x80 + N));
                 }
                 else if (N <= (std::numeric_limits<std::uint8_t>::max)())
                 {
                     oa->write_character(to_char_type(0x98));
                     write_number(static_cast<std::uint8_t>(N));
                 }
                 else if (N <= (std::numeric_limits<std::uint16_t>::max)())
                 {
                     oa->write_character(to_char_type(0x99));
                     write_number(static_cast<std::uint16_t>(N));
                 }
                 else if (N <= (std::numeric_limits<std::uint32_t>::max)())
                 {
                     oa->write_character(to_char_type(0x9A));
                     write_number(static_cast<std::uint32_t>(N));
                 }
                 // LCOV_EXCL_START
                 else if (N <= (std::numeric_limits<std::uint64_t>::max)())
                 {
                     oa->write_character(to_char_type(0x9B));
                     write_number(static_cast<std::uint64_t>(N));
                 }
                 // LCOV_EXCL_STOP
                 // step 2: write each element
                 for (const auto& el : *j.m_value.array)
                 {
                     write_cbor(el);
                 }
                 break;
             }
             case value_t::object:
             {
                 // step 1: write control byte and the object size
                 const auto N = j.m_value.object->size();
                 if (N <= 0x17)
                 {
                     write_number(static_cast<std::uint8_t>(0xA0 + N));
                 }
                 else if (N <= (std::numeric_limits<std::uint8_t>::max)())
                 {
                     oa->write_character(to_char_type(0xB8));
                     write_number(static_cast<std::uint8_t>(N));
                 }
                 else if (N <= (std::numeric_limits<std::uint16_t>::max)())
                 {
                     oa->write_character(to_char_type(0xB9));
                     write_number(static_cast<std::uint16_t>(N));
                 }
                 else if (N <= (std::numeric_limits<std::uint32_t>::max)())
                 {
                     oa->write_character(to_char_type(0xBA));
                     write_number(static_cast<std::uint32_t>(N));
                 }
                 // LCOV_EXCL_START
                 else if (N <= (std::numeric_limits<std::uint64_t>::max)())
                 {
                     oa->write_character(to_char_type(0xBB));
                     write_number(static_cast<std::uint64_t>(N));
                 }
                 // LCOV_EXCL_STOP
                 // step 2: write each element
                 for (const auto& el : *j.m_value.object)
                 {
                     write_cbor(el.first);
                     write_cbor(el.second);
                 }
                 break;
             }
             default:
                 break;
         }
     }
References nlohmann::detail::array, nlohmann::detail::boolean, nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_cbor_float_prefix(), N, nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, nlohmann::detail::object, nlohmann::detail::string, nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_cbor(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number().
write_msgpack() [1/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_msgpack (const BasicJsonType & j) inline
Parameters
[in] j JSON value to serialize
Definition at line 309 of file binary_writer.hpp.
     {
         switch (j.type())
         {
             case value_t::null: // nil
             {
                 oa->write_character(to_char_type(0xC0));
                 break;
             }
             case value_t::boolean: // true and false
             {
                 oa->write_character(j.m_value.boolean
                                     ? to_char_type(0xC3)
                                     : to_char_type(0xC2));
                 break;
             }
             case value_t::number_integer:
             {
                 if (j.m_value.number_integer >= 0)
                 {
                     // MessagePack does not differentiate between positive
                     // signed integers and unsigned integers. Therefore, we used
                     // the code from the value_t::number_unsigned case here.
                     if (j.m_value.number_unsigned < 128)
                     {
                         // positive fixnum
                         write_number(static_cast<std::uint8_t>(j.m_value.number_integer));
                     }
                     else if (j.m_value.number_unsigned <= (std::numeric_limits<std::uint8_t>::max)())
                     {
                         // uint 8
                         oa->write_character(to_char_type(0xCC));
                         write_number(static_cast<std::uint8_t>(j.m_value.number_integer));
                     }
                     else if (j.m_value.number_unsigned <= (std::numeric_limits<std::uint16_t>::max)())
                     {
                         // uint 16
                         oa->write_character(to_char_type(0xCD));
                         write_number(static_cast<std::uint16_t>(j.m_value.number_integer));
                     }
                     else if (j.m_value.number_unsigned <= (std::numeric_limits<std::uint32_t>::max)())
                     {
                         // uint 32
                         oa->write_character(to_char_type(0xCE));
                         write_number(static_cast<std::uint32_t>(j.m_value.number_integer));
                     }
                     else if (j.m_value.number_unsigned <= (std::numeric_limits<std::uint64_t>::max)())
                     {
                         // uint 64
                         oa->write_character(to_char_type(0xCF));
                         write_number(static_cast<std::uint64_t>(j.m_value.number_integer));
                     }
                 }
                 else
                 {
                     if (j.m_value.number_integer >= -32)
                     {
                         // negative fixnum
                         write_number(static_cast<std::int8_t>(j.m_value.number_integer));
                     }
                     else if (j.m_value.number_integer >= (std::numeric_limits<std::int8_t>::min)() and
                              j.m_value.number_integer <= (std::numeric_limits<std::int8_t>::max)())
                     {
                         // int 8
                         oa->write_character(to_char_type(0xD0));
                         write_number(static_cast<std::int8_t>(j.m_value.number_integer));
                     }
                     else if (j.m_value.number_integer >= (std::numeric_limits<std::int16_t>::min)() and
                              j.m_value.number_integer <= (std::numeric_limits<std::int16_t>::max)())
                     {
                         // int 16
                         oa->write_character(to_char_type(0xD1));
                         write_number(static_cast<std::int16_t>(j.m_value.number_integer));
                     }
                     else if (j.m_value.number_integer >= (std::numeric_limits<std::int32_t>::min)() and
                              j.m_value.number_integer <= (std::numeric_limits<std::int32_t>::max)())
                     {
                         // int 32
                         oa->write_character(to_char_type(0xD2));
                         write_number(static_cast<std::int32_t>(j.m_value.number_integer));
                     }
                     else if (j.m_value.number_integer >= (std::numeric_limits<std::int64_t>::min)() and
                              j.m_value.number_integer <= (std::numeric_limits<std::int64_t>::max)())
                     {
                         // int 64
                         oa->write_character(to_char_type(0xD3));
                         write_number(static_cast<std::int64_t>(j.m_value.number_integer));
                     }
                 }
                 break;
             }
             case value_t::number_unsigned:
             {
                 if (j.m_value.number_unsigned < 128)
                 {
                     // positive fixnum
                     write_number(static_cast<std::uint8_t>(j.m_value.number_integer));
                 }
                 else if (j.m_value.number_unsigned <= (std::numeric_limits<std::uint8_t>::max)())
                 {
                     // uint 8
                     oa->write_character(to_char_type(0xCC));
                     write_number(static_cast<std::uint8_t>(j.m_value.number_integer));
                 }
                 else if (j.m_value.number_unsigned <= (std::numeric_limits<std::uint16_t>::max)())
                 {
                     // uint 16
                     oa->write_character(to_char_type(0xCD));
                     write_number(static_cast<std::uint16_t>(j.m_value.number_integer));
                 }
                 else if (j.m_value.number_unsigned <= (std::numeric_limits<std::uint32_t>::max)())
                 {
                     // uint 32
                     oa->write_character(to_char_type(0xCE));
                     write_number(static_cast<std::uint32_t>(j.m_value.number_integer));
                 }
                 else if (j.m_value.number_unsigned <= (std::numeric_limits<std::uint64_t>::max)())
                 {
                     // uint 64
                     oa->write_character(to_char_type(0xCF));
                     write_number(static_cast<std::uint64_t>(j.m_value.number_integer));
                 }
                 break;
             }
             case value_t::number_float:
             {
                 oa->write_character(get_msgpack_float_prefix(j.m_value.number_float));
                 write_number(j.m_value.number_float);
                 break;
             }
             case value_t::string:
             {
                 // step 1: write control byte and the string length
                 const auto N = j.m_value.string->size();
                 if (N <= 31)
                 {
                     // fixstr
                     write_number(static_cast<std::uint8_t>(0xA0 | N));
                 }
                 else if (N <= (std::numeric_limits<std::uint8_t>::max)())
                 {
                     // str 8
                     oa->write_character(to_char_type(0xD9));
                     write_number(static_cast<std::uint8_t>(N));
                 }
                 else if (N <= (std::numeric_limits<std::uint16_t>::max)())
                 {
                     // str 16
                     oa->write_character(to_char_type(0xDA));
                     write_number(static_cast<std::uint16_t>(N));
                 }
                 else if (N <= (std::numeric_limits<std::uint32_t>::max)())
                 {
                     // str 32
                     oa->write_character(to_char_type(0xDB));
                     write_number(static_cast<std::uint32_t>(N));
                 }
                 // step 2: write the string
                 oa->write_characters(
                     reinterpret_cast<const CharType*>(j.m_value.string->c_str()),
                     j.m_value.string->size());
                 break;
             }
             case value_t::array:
             {
                 // step 1: write control byte and the array size
                 const auto N = j.m_value.array->size();
                 if (N <= 15)
                 {
                     // fixarray
                     write_number(static_cast<std::uint8_t>(0x90 | N));
                 }
                 else if (N <= (std::numeric_limits<std::uint16_t>::max)())
                 {
                     // array 16
                     oa->write_character(to_char_type(0xDC));
                     write_number(static_cast<std::uint16_t>(N));
                 }
                 else if (N <= (std::numeric_limits<std::uint32_t>::max)())
                 {
                     // array 32
                     oa->write_character(to_char_type(0xDD));
                     write_number(static_cast<std::uint32_t>(N));
                 }
                 // step 2: write each element
                 for (const auto& el : *j.m_value.array)
                 {
                     write_msgpack(el);
                 }
                 break;
             }
             case value_t::object:
             {
                 // step 1: write control byte and the object size
                 const auto N = j.m_value.object->size();
                 if (N <= 15)
                 {
                     // fixmap
                     write_number(static_cast<std::uint8_t>(0x80 | (N & 0xF)));
                 }
                 else if (N <= (std::numeric_limits<std::uint16_t>::max)())
                 {
                     // map 16
                     oa->write_character(to_char_type(0xDE));
                     write_number(static_cast<std::uint16_t>(N));
                 }
                 else if (N <= (std::numeric_limits<std::uint32_t>::max)())
                 {
                     // map 32
                     oa->write_character(to_char_type(0xDF));
                     write_number(static_cast<std::uint32_t>(N));
                 }
                 // step 2: write each element
                 for (const auto& el : *j.m_value.object)
                 {
                     write_msgpack(el.first);
                     write_msgpack(el.second);
                 }
                 break;
             }
             default:
                 break;
         }
     }
References nlohmann::detail::array, nlohmann::detail::boolean, nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_msgpack_float_prefix(), N, nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, nlohmann::detail::object, nlohmann::detail::string, nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number().
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::to_msgpack(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_msgpack().
write_msgpack() [2/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_msgpack (const BasicJsonType & j) inline
Parameters
[in] j JSON value to serialize
Definition at line 11601 of file json.hpp.
     {
         switch (j.type())
         {
             case value_t::null: // nil
             {
                 oa->write_character(to_char_type(0xC0));
                 break;
             }
             case value_t::boolean: // true and false
             {
                 oa->write_character(j.m_value.boolean
                                     ? to_char_type(0xC3)
                                     : to_char_type(0xC2));
                 break;
             }
             case value_t::number_integer:
             {
                 if (j.m_value.number_integer >= 0)
                 {
                     // MessagePack does not differentiate between positive
                     // signed integers and unsigned integers. Therefore, we used
                     // the code from the value_t::number_unsigned case here.
                     if (j.m_value.number_unsigned < 128)
                     {
                         // positive fixnum
                         write_number(static_cast<std::uint8_t>(j.m_value.number_integer));
                     }
                     else if (j.m_value.number_unsigned <= (std::numeric_limits<std::uint8_t>::max)())
                     {
                         // uint 8
                         oa->write_character(to_char_type(0xCC));
                         write_number(static_cast<std::uint8_t>(j.m_value.number_integer));
                     }
                     else if (j.m_value.number_unsigned <= (std::numeric_limits<std::uint16_t>::max)())
                     {
                         // uint 16
                         oa->write_character(to_char_type(0xCD));
                         write_number(static_cast<std::uint16_t>(j.m_value.number_integer));
                     }
                     else if (j.m_value.number_unsigned <= (std::numeric_limits<std::uint32_t>::max)())
                     {
                         // uint 32
                         oa->write_character(to_char_type(0xCE));
                         write_number(static_cast<std::uint32_t>(j.m_value.number_integer));
                     }
                     else if (j.m_value.number_unsigned <= (std::numeric_limits<std::uint64_t>::max)())
                     {
                         // uint 64
                         oa->write_character(to_char_type(0xCF));
                         write_number(static_cast<std::uint64_t>(j.m_value.number_integer));
                     }
                 }
                 else
                 {
                     if (j.m_value.number_integer >= -32)
                     {
                         // negative fixnum
                         write_number(static_cast<std::int8_t>(j.m_value.number_integer));
                     }
                     else if (j.m_value.number_integer >= (std::numeric_limits<std::int8_t>::min)() and
                              j.m_value.number_integer <= (std::numeric_limits<std::int8_t>::max)())
                     {
                         // int 8
                         oa->write_character(to_char_type(0xD0));
                         write_number(static_cast<std::int8_t>(j.m_value.number_integer));
                     }
                     else if (j.m_value.number_integer >= (std::numeric_limits<std::int16_t>::min)() and
                              j.m_value.number_integer <= (std::numeric_limits<std::int16_t>::max)())
                     {
                         // int 16
                         oa->write_character(to_char_type(0xD1));
                         write_number(static_cast<std::int16_t>(j.m_value.number_integer));
                     }
                     else if (j.m_value.number_integer >= (std::numeric_limits<std::int32_t>::min)() and
                              j.m_value.number_integer <= (std::numeric_limits<std::int32_t>::max)())
                     {
                         // int 32
                         oa->write_character(to_char_type(0xD2));
                         write_number(static_cast<std::int32_t>(j.m_value.number_integer));
                     }
                     else if (j.m_value.number_integer >= (std::numeric_limits<std::int64_t>::min)() and
                              j.m_value.number_integer <= (std::numeric_limits<std::int64_t>::max)())
                     {
                         // int 64
                         oa->write_character(to_char_type(0xD3));
                         write_number(static_cast<std::int64_t>(j.m_value.number_integer));
                     }
                 }
                 break;
             }
             case value_t::number_unsigned:
             {
                 if (j.m_value.number_unsigned < 128)
                 {
                     // positive fixnum
                     write_number(static_cast<std::uint8_t>(j.m_value.number_integer));
                 }
                 else if (j.m_value.number_unsigned <= (std::numeric_limits<std::uint8_t>::max)())
                 {
                     // uint 8
                     oa->write_character(to_char_type(0xCC));
                     write_number(static_cast<std::uint8_t>(j.m_value.number_integer));
                 }
                 else if (j.m_value.number_unsigned <= (std::numeric_limits<std::uint16_t>::max)())
                 {
                     // uint 16
                     oa->write_character(to_char_type(0xCD));
                     write_number(static_cast<std::uint16_t>(j.m_value.number_integer));
                 }
                 else if (j.m_value.number_unsigned <= (std::numeric_limits<std::uint32_t>::max)())
                 {
                     // uint 32
                     oa->write_character(to_char_type(0xCE));
                     write_number(static_cast<std::uint32_t>(j.m_value.number_integer));
                 }
                 else if (j.m_value.number_unsigned <= (std::numeric_limits<std::uint64_t>::max)())
                 {
                     // uint 64
                     oa->write_character(to_char_type(0xCF));
                     write_number(static_cast<std::uint64_t>(j.m_value.number_integer));
                 }
                 break;
             }
             case value_t::number_float:
             {
                 oa->write_character(get_msgpack_float_prefix(j.m_value.number_float));
                 write_number(j.m_value.number_float);
                 break;
             }
             case value_t::string:
             {
                 // step 1: write control byte and the string length
                 const auto N = j.m_value.string->size();
                 if (N <= 31)
                 {
                     // fixstr
                     write_number(static_cast<std::uint8_t>(0xA0 | N));
                 }
                 else if (N <= (std::numeric_limits<std::uint8_t>::max)())
                 {
                     // str 8
                     oa->write_character(to_char_type(0xD9));
                     write_number(static_cast<std::uint8_t>(N));
                 }
                 else if (N <= (std::numeric_limits<std::uint16_t>::max)())
                 {
                     // str 16
                     oa->write_character(to_char_type(0xDA));
                     write_number(static_cast<std::uint16_t>(N));
                 }
                 else if (N <= (std::numeric_limits<std::uint32_t>::max)())
                 {
                     // str 32
                     oa->write_character(to_char_type(0xDB));
                     write_number(static_cast<std::uint32_t>(N));
                 }
                 // step 2: write the string
                 oa->write_characters(
                     reinterpret_cast<const CharType*>(j.m_value.string->c_str()),
                     j.m_value.string->size());
                 break;
             }
             case value_t::array:
             {
                 // step 1: write control byte and the array size
                 const auto N = j.m_value.array->size();
                 if (N <= 15)
                 {
                     // fixarray
                     write_number(static_cast<std::uint8_t>(0x90 | N));
                 }
                 else if (N <= (std::numeric_limits<std::uint16_t>::max)())
                 {
                     // array 16
                     oa->write_character(to_char_type(0xDC));
                     write_number(static_cast<std::uint16_t>(N));
                 }
                 else if (N <= (std::numeric_limits<std::uint32_t>::max)())
                 {
                     // array 32
                     oa->write_character(to_char_type(0xDD));
                     write_number(static_cast<std::uint32_t>(N));
                 }
                 // step 2: write each element
                 for (const auto& el : *j.m_value.array)
                 {
                     write_msgpack(el);
                 }
                 break;
             }
             case value_t::object:
             {
                 // step 1: write control byte and the object size
                 const auto N = j.m_value.object->size();
                 if (N <= 15)
                 {
                     // fixmap
                     write_number(static_cast<std::uint8_t>(0x80 | (N & 0xF)));
                 }
                 else if (N <= (std::numeric_limits<std::uint16_t>::max)())
                 {
                     // map 16
                     oa->write_character(to_char_type(0xDE));
                     write_number(static_cast<std::uint16_t>(N));
                 }
                 else if (N <= (std::numeric_limits<std::uint32_t>::max)())
                 {
                     // map 32
                     oa->write_character(to_char_type(0xDF));
                     write_number(static_cast<std::uint32_t>(N));
                 }
                 // step 2: write each element
                 for (const auto& el : *j.m_value.object)
                 {
                     write_msgpack(el.first);
                     write_msgpack(el.second);
                 }
                 break;
             }
             default:
                 break;
         }
     }
References nlohmann::detail::array, nlohmann::detail::boolean, nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_msgpack_float_prefix(), N, nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, nlohmann::detail::object, nlohmann::detail::string, nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_msgpack(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number().
write_number() [1/2]
template<typename BasicJsonType , typename CharType > template<typename NumberType , bool OutputIsLittleEndian = false> void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number (const NumberType n) inline private
Definition at line 1270 of file binary_writer.hpp.
     {
         // step 1: write number to array of length NumberType
         std::array<CharType, sizeof(NumberType)> vec;
         std::memcpy(vec.data(), &n, sizeof(NumberType));
         // step 2: write array to output (with possible reordering)
         if (is_little_endian != OutputIsLittleEndian)
         {
             // reverse byte order prior to conversion if necessary
             std::reverse(vec.begin(), vec.end());
         }
         oa->write_characters(vec.data(), sizeof(NumberType));
     }
References array, nlohmann::detail::binary_writer< BasicJsonType, CharType >::is_little_endian, n, and nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa.
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_cbor(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_msgpack(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number_with_ubjson_prefix().
write_number() [2/2]
template<typename BasicJsonType , typename CharType > template<typename NumberType , bool OutputIsLittleEndian = false> void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number (const NumberType n) inline private
Definition at line 12562 of file json.hpp.
     {
         // step 1: write number to array of length NumberType
         std::array<CharType, sizeof(NumberType)> vec;
         std::memcpy(vec.data(), &n, sizeof(NumberType));
         // step 2: write array to output (with possible reordering)
         if (is_little_endian != OutputIsLittleEndian)
         {
             // reverse byte order prior to conversion if necessary
             std::reverse(vec.begin(), vec.end());
         }
         oa->write_characters(vec.data(), sizeof(NumberType));
     }
References array, nlohmann::detail::binary_writer< BasicJsonType, CharType >::is_little_endian, n, and nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa.
write_number_with_ubjson_prefix() [1/6]
template<typename BasicJsonType , typename CharType > template<typename NumberType , typename std::enable_if< std::is_floating_point< NumberType >::value, int >::type = 0> void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number_with_ubjson_prefix (const NumberType n, const bool add_prefix) inline private
Definition at line 1047 of file binary_writer.hpp.
     {
         if (add_prefix)
         {
             oa->write_character(get_ubjson_float_prefix(n));
         }
         write_number(n);
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_ubjson_float_prefix(), n, nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_ubjson().
write_number_with_ubjson_prefix() [2/6]
template<typename BasicJsonType , typename CharType > template<typename NumberType , typename std::enable_if< std::is_unsigned< NumberType >::value, int >::type = 0> void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number_with_ubjson_prefix (const NumberType n, const bool add_prefix) inline private
Definition at line 1060 of file binary_writer.hpp.
     {
         if (n <= static_cast<std::uint64_t>((std::numeric_limits<std::int8_t>::max)()))
         {
             if (add_prefix)
             {
                 oa->write_character(to_char_type('i'));  // int8
             }
             write_number(static_cast<std::uint8_t>(n));
         }
         else if (n <= (std::numeric_limits<std::uint8_t>::max)())
         {
             if (add_prefix)
             {
                 oa->write_character(to_char_type('U'));  // uint8
             }
             write_number(static_cast<std::uint8_t>(n));
         }
         else if (n <= static_cast<std::uint64_t>((std::numeric_limits<std::int16_t>::max)()))
         {
             if (add_prefix)
             {
                 oa->write_character(to_char_type('I'));  // int16
             }
             write_number(static_cast<std::int16_t>(n));
         }
         else if (n <= static_cast<std::uint64_t>((std::numeric_limits<std::int32_t>::max)()))
         {
             if (add_prefix)
             {
                 oa->write_character(to_char_type('l'));  // int32
             }
             write_number(static_cast<std::int32_t>(n));
         }
         else if (n <= static_cast<std::uint64_t>((std::numeric_limits<std::int64_t>::max)()))
         {
             if (add_prefix)
             {
                 oa->write_character(to_char_type('L'));  // int64
             }
             write_number(static_cast<std::int64_t>(n));
         }
         else
         {
             JSON_THROW(out_of_range::create(407, "integer number " + std::to_string(n) + " cannot be represented by UBJSON as it does not fit int64"));
         }
     }
References nlohmann::detail::out_of_range::create(), JSON_THROW, n, nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), httplib::to_string(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number().
write_number_with_ubjson_prefix() [3/6]
template<typename BasicJsonType , typename CharType > template<typename NumberType , typename std::enable_if< std::is_signed< NumberType >::value and not std::is_floating_point< NumberType >::value, int >::type = 0> void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number_with_ubjson_prefix (const NumberType n, const bool add_prefix) inline private
Definition at line 1113 of file binary_writer.hpp.
     {
         if ((std::numeric_limits<std::int8_t>::min)() <= n and n <= (std::numeric_limits<std::int8_t>::max)())
         {
             if (add_prefix)
             {
                 oa->write_character(to_char_type('i'));  // int8
             }
             write_number(static_cast<std::int8_t>(n));
         }
         else if (static_cast<std::int64_t>((std::numeric_limits<std::uint8_t>::min)()) <= n and n <= static_cast<std::int64_t>((std::numeric_limits<std::uint8_t>::max)()))
         {
             if (add_prefix)
             {
                 oa->write_character(to_char_type('U'));  // uint8
             }
             write_number(static_cast<std::uint8_t>(n));
         }
         else if ((std::numeric_limits<std::int16_t>::min)() <= n and n <= (std::numeric_limits<std::int16_t>::max)())
         {
             if (add_prefix)
             {
                 oa->write_character(to_char_type('I'));  // int16
             }
             write_number(static_cast<std::int16_t>(n));
         }
         else if ((std::numeric_limits<std::int32_t>::min)() <= n and n <= (std::numeric_limits<std::int32_t>::max)())
         {
             if (add_prefix)
             {
                 oa->write_character(to_char_type('l'));  // int32
             }
             write_number(static_cast<std::int32_t>(n));
         }
         else if ((std::numeric_limits<std::int64_t>::min)() <= n and n <= (std::numeric_limits<std::int64_t>::max)())
         {
             if (add_prefix)
             {
                 oa->write_character(to_char_type('L'));  // int64
             }
             write_number(static_cast<std::int64_t>(n));
         }
         // LCOV_EXCL_START
         else
         {
             JSON_THROW(out_of_range::create(407, "integer number " + std::to_string(n) + " cannot be represented by UBJSON as it does not fit int64"));
         }
         // LCOV_EXCL_STOP
     }
References nlohmann::detail::out_of_range::create(), JSON_THROW, n, nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), httplib::to_string(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number().
write_number_with_ubjson_prefix() [4/6]
template<typename BasicJsonType , typename CharType > template<typename NumberType , typename std::enable_if< std::is_floating_point< NumberType >::value, int >::type = 0> void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number_with_ubjson_prefix (const NumberType n, const bool add_prefix) inline private
Definition at line 12339 of file json.hpp.
     {
         if (add_prefix)
         {
             oa->write_character(get_ubjson_float_prefix(n));
         }
         write_number(n);
     }
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_ubjson_float_prefix(), n, nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number().
write_number_with_ubjson_prefix() [5/6]
template<typename BasicJsonType , typename CharType > template<typename NumberType , typename std::enable_if< std::is_unsigned< NumberType >::value, int >::type = 0> void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number_with_ubjson_prefix (const NumberType n, const bool add_prefix) inline private
Definition at line 12352 of file json.hpp.
     {
         if (n <= static_cast<std::uint64_t>((std::numeric_limits<std::int8_t>::max)()))
         {
             if (add_prefix)
             {
                 oa->write_character(to_char_type('i'));  // int8
             }
             write_number(static_cast<std::uint8_t>(n));
         }
         else if (n <= (std::numeric_limits<std::uint8_t>::max)())
         {
             if (add_prefix)
             {
                 oa->write_character(to_char_type('U'));  // uint8
             }
             write_number(static_cast<std::uint8_t>(n));
         }
         else if (n <= static_cast<std::uint64_t>((std::numeric_limits<std::int16_t>::max)()))
         {
             if (add_prefix)
             {
                 oa->write_character(to_char_type('I'));  // int16
             }
             write_number(static_cast<std::int16_t>(n));
         }
         else if (n <= static_cast<std::uint64_t>((std::numeric_limits<std::int32_t>::max)()))
         {
             if (add_prefix)
             {
                 oa->write_character(to_char_type('l'));  // int32
             }
             write_number(static_cast<std::int32_t>(n));
         }
         else if (n <= static_cast<std::uint64_t>((std::numeric_limits<std::int64_t>::max)()))
         {
             if (add_prefix)
             {
                 oa->write_character(to_char_type('L'));  // int64
             }
             write_number(static_cast<std::int64_t>(n));
         }
         else
         {
             JSON_THROW(out_of_range::create(407, "integer number " + std::to_string(n) + " cannot be represented by UBJSON as it does not fit int64"));
         }
     }
References nlohmann::detail::out_of_range::create(), JSON_THROW, n, nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), nlohmann::to_string(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number().
write_number_with_ubjson_prefix() [6/6]
template<typename BasicJsonType , typename CharType > template<typename NumberType , typename std::enable_if< std::is_signed< NumberType >::value and not std::is_floating_point< NumberType >::value, int >::type = 0> void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number_with_ubjson_prefix (const NumberType n, const bool add_prefix) inline private
Definition at line 12405 of file json.hpp.
     {
         if ((std::numeric_limits<std::int8_t>::min)() <= n and n <= (std::numeric_limits<std::int8_t>::max)())
         {
             if (add_prefix)
             {
                 oa->write_character(to_char_type('i'));  // int8
             }
             write_number(static_cast<std::int8_t>(n));
         }
         else if (static_cast<std::int64_t>((std::numeric_limits<std::uint8_t>::min)()) <= n and n <= static_cast<std::int64_t>((std::numeric_limits<std::uint8_t>::max)()))
         {
             if (add_prefix)
             {
                 oa->write_character(to_char_type('U'));  // uint8
             }
             write_number(static_cast<std::uint8_t>(n));
         }
         else if ((std::numeric_limits<std::int16_t>::min)() <= n and n <= (std::numeric_limits<std::int16_t>::max)())
         {
             if (add_prefix)
             {
                 oa->write_character(to_char_type('I'));  // int16
             }
             write_number(static_cast<std::int16_t>(n));
         }
         else if ((std::numeric_limits<std::int32_t>::min)() <= n and n <= (std::numeric_limits<std::int32_t>::max)())
         {
             if (add_prefix)
             {
                 oa->write_character(to_char_type('l'));  // int32
             }
             write_number(static_cast<std::int32_t>(n));
         }
         else if ((std::numeric_limits<std::int64_t>::min)() <= n and n <= (std::numeric_limits<std::int64_t>::max)())
         {
             if (add_prefix)
             {
                 oa->write_character(to_char_type('L'));  // int64
             }
             write_number(static_cast<std::int64_t>(n));
         }
         // LCOV_EXCL_START
         else
         {
             JSON_THROW(out_of_range::create(407, "integer number " + std::to_string(n) + " cannot be represented by UBJSON as it does not fit int64"));
         }
         // LCOV_EXCL_STOP
     }
References nlohmann::detail::out_of_range::create(), JSON_THROW, n, nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), nlohmann::to_string(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number().
write_ubjson() [1/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_ubjson (const BasicJsonType & j, const bool use_count, const bool use_type, const bool add_prefix = true) inline
Parameters
[in] j JSON value to serialize
[in] use_count whether to use '#' prefixes (optimized format)
[in] use_type whether to use '$' prefixes (optimized format)
[in] add_prefix whether prefixes need to be used for this value
Definition at line 551 of file binary_writer.hpp.
     {
         switch (j.type())
         {
             case value_t::null:
             {
                 if (add_prefix)
                 {
                     oa->write_character(to_char_type('Z'));
                 }
                 break;
             }
             case value_t::boolean:
             {
                 if (add_prefix)
                 {
                     oa->write_character(j.m_value.boolean
                                         ? to_char_type('T')
                                         : to_char_type('F'));
                 }
                 break;
             }
             case value_t::number_integer:
             {
                 write_number_with_ubjson_prefix(j.m_value.number_integer, add_prefix);
                 break;
             }
             case value_t::number_unsigned:
             {
                 write_number_with_ubjson_prefix(j.m_value.number_unsigned, add_prefix);
                 break;
             }
             case value_t::number_float:
             {
                 write_number_with_ubjson_prefix(j.m_value.number_float, add_prefix);
                 break;
             }
             case value_t::string:
             {
                 if (add_prefix)
                 {
                     oa->write_character(to_char_type('S'));
                 }
                 write_number_with_ubjson_prefix(j.m_value.string->size(), true);
                 oa->write_characters(
                     reinterpret_cast<const CharType*>(j.m_value.string->c_str()),
                     j.m_value.string->size());
                 break;
             }
             case value_t::array:
             {
                 if (add_prefix)
                 {
                     oa->write_character(to_char_type('['));
                 }
                 bool prefix_required = true;
                 if (use_type and not j.m_value.array->empty())
                 {
                     assert(use_count);
                     const CharType first_prefix = ubjson_prefix(j.front());
                     const bool same_prefix = std::all_of(j.begin() + 1, j.end(),
                                                          [this, first_prefix](const BasicJsonType & v)
                     {
                         return ubjson_prefix(v) == first_prefix;
                     });
                     if (same_prefix)
                     {
                         prefix_required = false;
                         oa->write_character(to_char_type('$'));
                         oa->write_character(first_prefix);
                     }
                 }
                 if (use_count)
                 {
                     oa->write_character(to_char_type('#'));
                     write_number_with_ubjson_prefix(j.m_value.array->size(), true);
                 }
                 for (const auto& el : *j.m_value.array)
                 {
                     write_ubjson(el, use_count, use_type, prefix_required);
                 }
                 if (not use_count)
                 {
                     oa->write_character(to_char_type(']'));
                 }
                 break;
             }
             case value_t::object:
             {
                 if (add_prefix)
                 {
                     oa->write_character(to_char_type('{'));
                 }
                 bool prefix_required = true;
                 if (use_type and not j.m_value.object->empty())
                 {
                     assert(use_count);
                     const CharType first_prefix = ubjson_prefix(j.front());
                     const bool same_prefix = std::all_of(j.begin(), j.end(),
                                                          [this, first_prefix](const BasicJsonType & v)
                     {
                         return ubjson_prefix(v) == first_prefix;
                     });
                     if (same_prefix)
                     {
                         prefix_required = false;
                         oa->write_character(to_char_type('$'));
                         oa->write_character(first_prefix);
                     }
                 }
                 if (use_count)
                 {
                     oa->write_character(to_char_type('#'));
                     write_number_with_ubjson_prefix(j.m_value.object->size(), true);
                 }
                 for (const auto& el : *j.m_value.object)
                 {
                     write_number_with_ubjson_prefix(el.first.size(), true);
                     oa->write_characters(
                         reinterpret_cast<const CharType*>(el.first.c_str()),
                         el.first.size());
                     write_ubjson(el.second, use_count, use_type, prefix_required);
                 }
                 if (not use_count)
                 {
                     oa->write_character(to_char_type('}'));
                 }
                 break;
             }
             default:
                 break;
         }
     }
References nlohmann::detail::array, assert(), nlohmann::detail::boolean, nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, nlohmann::detail::object, nlohmann::detail::string, nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::ubjson_prefix(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number_with_ubjson_prefix().
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::to_ubjson(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_ubjson().
write_ubjson() [2/2]
template<typename BasicJsonType , typename CharType > void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_ubjson (const BasicJsonType & j, const bool use_count, const bool use_type, const bool add_prefix = true) inline
Parameters
[in] j JSON value to serialize
[in] use_count whether to use '#' prefixes (optimized format)
[in] use_type whether to use '$' prefixes (optimized format)
[in] add_prefix whether prefixes need to be used for this value
Definition at line 11843 of file json.hpp.
     {
         switch (j.type())
         {
             case value_t::null:
             {
                 if (add_prefix)
                 {
                     oa->write_character(to_char_type('Z'));
                 }
                 break;
             }
             case value_t::boolean:
             {
                 if (add_prefix)
                 {
                     oa->write_character(j.m_value.boolean
                                         ? to_char_type('T')
                                         : to_char_type('F'));
                 }
                 break;
             }
             case value_t::number_integer:
             {
                 write_number_with_ubjson_prefix(j.m_value.number_integer, add_prefix);
                 break;
             }
             case value_t::number_unsigned:
             {
                 write_number_with_ubjson_prefix(j.m_value.number_unsigned, add_prefix);
                 break;
             }
             case value_t::number_float:
             {
                 write_number_with_ubjson_prefix(j.m_value.number_float, add_prefix);
                 break;
             }
             case value_t::string:
             {
                 if (add_prefix)
                 {
                     oa->write_character(to_char_type('S'));
                 }
                 write_number_with_ubjson_prefix(j.m_value.string->size(), true);
                 oa->write_characters(
                     reinterpret_cast<const CharType*>(j.m_value.string->c_str()),
                     j.m_value.string->size());
                 break;
             }
             case value_t::array:
             {
                 if (add_prefix)
                 {
                     oa->write_character(to_char_type('['));
                 }
                 bool prefix_required = true;
                 if (use_type and not j.m_value.array->empty())
                 {
                     assert(use_count);
                     const CharType first_prefix = ubjson_prefix(j.front());
                     const bool same_prefix = std::all_of(j.begin() + 1, j.end(),
                                                          [this, first_prefix](const BasicJsonType & v)
                     {
                         return ubjson_prefix(v) == first_prefix;
                     });
                     if (same_prefix)
                     {
                         prefix_required = false;
                         oa->write_character(to_char_type('$'));
                         oa->write_character(first_prefix);
                     }
                 }
                 if (use_count)
                 {
                     oa->write_character(to_char_type('#'));
                     write_number_with_ubjson_prefix(j.m_value.array->size(), true);
                 }
                 for (const auto& el : *j.m_value.array)
                 {
                     write_ubjson(el, use_count, use_type, prefix_required);
                 }
                 if (not use_count)
                 {
                     oa->write_character(to_char_type(']'));
                 }
                 break;
             }
             case value_t::object:
             {
                 if (add_prefix)
                 {
                     oa->write_character(to_char_type('{'));
                 }
                 bool prefix_required = true;
                 if (use_type and not j.m_value.object->empty())
                 {
                     assert(use_count);
                     const CharType first_prefix = ubjson_prefix(j.front());
                     const bool same_prefix = std::all_of(j.begin(), j.end(),
                                                          [this, first_prefix](const BasicJsonType & v)
                     {
                         return ubjson_prefix(v) == first_prefix;
                     });
                     if (same_prefix)
                     {
                         prefix_required = false;
                         oa->write_character(to_char_type('$'));
                         oa->write_character(first_prefix);
                     }
                 }
                 if (use_count)
                 {
                     oa->write_character(to_char_type('#'));
                     write_number_with_ubjson_prefix(j.m_value.object->size(), true);
                 }
                 for (const auto& el : *j.m_value.object)
                 {
                     write_number_with_ubjson_prefix(el.first.size(), true);
                     oa->write_characters(
                         reinterpret_cast<const CharType*>(el.first.c_str()),
                         el.first.size());
                     write_ubjson(el.second, use_count, use_type, prefix_required);
                 }
                 if (not use_count)
                 {
                     oa->write_character(to_char_type('}'));
                 }
                 break;
             }
             default:
                 break;
         }
     }
References nlohmann::detail::array, assert(), nlohmann::detail::boolean, nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, nlohmann::detail::object, nlohmann::detail::string, nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::ubjson_prefix(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number_with_ubjson_prefix(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_ubjson().
Member Data Documentation
is_little_endian
template<typename BasicJsonType , typename CharType > const bool nlohmann::detail::binary_writer< BasicJsonType, CharType >::is_little_endian = binary_reader<BasicJsonType>::little_endianess() private
whether we can assume little endianess
Definition at line 1329 of file binary_writer.hpp.
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number().
oa
template<typename BasicJsonType , typename CharType > output_adapter_t< CharType > nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa = nullptr private
the output
Definition at line 1332 of file binary_writer.hpp.
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::binary_writer(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_array(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_boolean(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_object(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_string(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_cbor(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_msgpack(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number_with_ubjson_prefix(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_ubjson().
The documentation for this class was generated from the following files:
mc_orchestrator/json-3.7.3/include/nlohmann/detail/output/binary_writer.hpp
mc_orchestrator/json-3.7.3/single_include/nlohmann/json.hpp