Mixed Criticality Orchestrator: nlohmann::detail::lexer< BasicJsonType > Class Template Reference
nlohmann::detail::lexer< BasicJsonType > Class Template Reference
lexical analysis
#include <lexer.hpp>
Public Types
enum token_type {
token_type::uninitialized, token_type::literal_true, token_type::literal_false, token_type::literal_null,
token_type::value_string, token_type::value_unsigned, token_type::value_integer, token_type::value_float,
token_type::begin_array, token_type::begin_object, token_type::end_array, token_type::end_object,
token_type::name_separator, token_type::value_separator, token_type::parse_error, token_type::end_of_input,
token_type::literal_or_value, token_type::uninitialized, token_type::literal_true, token_type::literal_false,
token_type::literal_null, token_type::value_string, token_type::value_unsigned, token_type::value_integer,
token_type::value_float, token_type::begin_array, token_type::begin_object, token_type::end_array,
token_type::end_object, token_type::name_separator, token_type::value_separator, token_type::parse_error,
token_type::end_of_input, token_type::literal_or_value
}
token types for the parser
enum token_type {
token_type::uninitialized, token_type::literal_true, token_type::literal_false, token_type::literal_null,
token_type::value_string, token_type::value_unsigned, token_type::value_integer, token_type::value_float,
token_type::begin_array, token_type::begin_object, token_type::end_array, token_type::end_object,
token_type::name_separator, token_type::value_separator, token_type::parse_error, token_type::end_of_input,
token_type::literal_or_value, token_type::uninitialized, token_type::literal_true, token_type::literal_false,
token_type::literal_null, token_type::value_string, token_type::value_unsigned, token_type::value_integer,
token_type::value_float, token_type::begin_array, token_type::begin_object, token_type::end_array,
token_type::end_object, token_type::name_separator, token_type::value_separator, token_type::parse_error,
token_type::end_of_input, token_type::literal_or_value
}
token types for the parser
Public Member Functions
lexer (detail::input_adapter_t &&adapter)
lexer (const lexer &)=delete
lexer (lexer &&)=delete
lexer & operator= (lexer &)=delete
lexer & operator= (lexer &&)=delete
~lexer ()=default
constexpr number_integer_t get_number_integer () const noexcept
return integer value
constexpr number_unsigned_t get_number_unsigned () const noexcept
return unsigned integer value
constexpr number_float_t get_number_float () const noexcept
return floating-point value
string_t & get_string ()
return current string value (implicitly resets the token; useful only once)
constexpr position_t get_position () const noexcept
return position of last read token
std::string get_token_string () const
constexpr const JSON_HEDLEY_RETURNS_NON_NULL char * get_error_message () const noexcept
return syntax error message
bool skip_bom ()
skip the UTF-8 byte order mark
token_type scan ()
lexer (detail::input_adapter_t &&adapter)
lexer (const lexer &)=delete
lexer (lexer &&)=delete
lexer & operator= (lexer &)=delete
lexer & operator= (lexer &&)=delete
~lexer ()=default
constexpr number_integer_t get_number_integer () const noexcept
return integer value
constexpr number_unsigned_t get_number_unsigned () const noexcept
return unsigned integer value
constexpr number_float_t get_number_float () const noexcept
return floating-point value
string_t & get_string ()
return current string value (implicitly resets the token; useful only once)
constexpr position_t get_position () const noexcept
return position of last read token
std::string get_token_string () const
constexpr const char * get_error_message () const noexcept
return syntax error message
bool skip_bom ()
skip the UTF-8 byte order mark
token_type scan ()
Static Public Member Functions
JSON_HEDLEY_RETURNS_NON_NULL static const JSON_HEDLEY_CONST char * token_type_name (const token_type t) noexcept
return name of values of type token_type (only used for errors)
static const char * token_type_name (const token_type t) noexcept
return name of values of type token_type (only used for errors)
Private Types
using number_integer_t = typename BasicJsonType::number_integer_t
using number_unsigned_t = typename BasicJsonType::number_unsigned_t
using number_float_t = typename BasicJsonType::number_float_t
using string_t = typename BasicJsonType::string_t
using number_integer_t = typename BasicJsonType::number_integer_t
using number_unsigned_t = typename BasicJsonType::number_unsigned_t
using number_float_t = typename BasicJsonType::number_float_t
using string_t = typename BasicJsonType::string_t
Private Member Functions
int get_codepoint ()
get codepoint from 4 hex characters following \u
bool next_byte_in_range (std::initializer_list< int > ranges)
check if the next byte(s) are inside a given range
token_type scan_string ()
scan a string literal
token_type scan_number ()
scan a number literal
token_type scan_literal (const char *literal_text, const std::size_t length, token_type return_type)
void reset () noexcept
reset token_buffer; current character is beginning of token
std::char_traits< char >::int_type get ()
void unget ()
unget current character (read it again on next get)
void add (int c)
add a character to token_buffer
int get_codepoint ()
get codepoint from 4 hex characters following \u
bool next_byte_in_range (std::initializer_list< int > ranges)
check if the next byte(s) are inside a given range
token_type scan_string ()
scan a string literal
token_type scan_number ()
scan a number literal
token_type scan_literal (const char *literal_text, const std::size_t length, token_type return_type)
void reset () noexcept
reset token_buffer; current character is beginning of token
std::char_traits< char >::int_type get ()
void unget ()
unget current character (read it again on next get)
void add (int c)
add a character to token_buffer
Static Private Member Functions
static JSON_HEDLEY_PURE char get_decimal_point () noexcept
return the locale-dependent decimal point
static void strtof (float &f, const char *str, char **endptr) noexcept
static void strtof (double &f, const char *str, char **endptr) noexcept
static void strtof (long double &f, const char *str, char **endptr) noexcept
static char get_decimal_point () noexcept
return the locale-dependent decimal point
static void strtof (float &f, const char *str, char **endptr) noexcept
static void strtof (double &f, const char *str, char **endptr) noexcept
static void strtof (long double &f, const char *str, char **endptr) noexcept
Private Attributes
detail::input_adapter_t ia = nullptr
input adapter
std::char_traits< char >::int_type current = std::char_traits<char>::eof()
the current character
bool next_unget = false
whether the next get() call should just return current
position_t position {}
the start position of the current token
std::vector< char > token_string {}
raw input token string (for error messages)
string_t token_buffer {}
buffer for variable-length tokens (numbers, strings)
const char * error_message = ""
a description of occurred lexer errors
number_integer_t value_integer = 0
number_unsigned_t value_unsigned = 0
number_float_t value_float = 0
const char decimal_point_char = '.'
the decimal point
Detailed Description
template<typename BasicJsonType>
class nlohmann::detail::lexer< BasicJsonType >
lexical analysis
This class organizes the lexical analysis during JSON deserialization.
Definition at line 31 of file lexer.hpp.
Member Typedef Documentation
number_float_t [1/2]
template<typename BasicJsonType > using nlohmann::detail::lexer< BasicJsonType >::number_float_t = typename BasicJsonType::number_float_t private
Definition at line 35 of file lexer.hpp.
number_float_t [2/2]
template<typename BasicJsonType > using nlohmann::detail::lexer< BasicJsonType >::number_float_t = typename BasicJsonType::number_float_t private
Definition at line 7165 of file json.hpp.
number_integer_t [1/2]
template<typename BasicJsonType > using nlohmann::detail::lexer< BasicJsonType >::number_integer_t = typename BasicJsonType::number_integer_t private
Definition at line 33 of file lexer.hpp.
number_integer_t [2/2]
template<typename BasicJsonType > using nlohmann::detail::lexer< BasicJsonType >::number_integer_t = typename BasicJsonType::number_integer_t private
Definition at line 7163 of file json.hpp.
number_unsigned_t [1/2]
template<typename BasicJsonType > using nlohmann::detail::lexer< BasicJsonType >::number_unsigned_t = typename BasicJsonType::number_unsigned_t private
Definition at line 34 of file lexer.hpp.
number_unsigned_t [2/2]
template<typename BasicJsonType > using nlohmann::detail::lexer< BasicJsonType >::number_unsigned_t = typename BasicJsonType::number_unsigned_t private
Definition at line 7164 of file json.hpp.
string_t [1/2]
template<typename BasicJsonType > using nlohmann::detail::lexer< BasicJsonType >::string_t = typename BasicJsonType::string_t private
Definition at line 36 of file lexer.hpp.
string_t [2/2]
template<typename BasicJsonType > using nlohmann::detail::lexer< BasicJsonType >::string_t = typename BasicJsonType::string_t private
Definition at line 7166 of file json.hpp.
Member Enumeration Documentation
token_type [1/2]
template<typename BasicJsonType > enum nlohmann::detail::lexer::token_type strong
token types for the parser
Enumerator
uninitialized
indicating the scanner is uninitialized
literal_true
the true literal
literal_false
the false literal
literal_null
the null literal
value_string
a string – use get_string() for actual value
value_unsigned
an unsigned integer – use get_number_unsigned() for actual value
value_integer
a signed integer – use get_number_integer() for actual value
value_float
an floating point number – use get_number_float() for actual value
begin_array
the character for array begin [
begin_object
the character for object begin {
end_array
the character for array end ]
end_object
the character for object end }
name_separator
the name separator :
value_separator
the value separator ,
parse_error
indicating a parse error
end_of_input
indicating the end of the input buffer
literal_or_value
a literal or the begin of a value (only for diagnostics)
uninitialized
indicating the scanner is uninitialized
literal_true
the true literal
literal_false
the false literal
literal_null
the null literal
value_string
a string – use get_string() for actual value
value_unsigned
an unsigned integer – use get_number_unsigned() for actual value
value_integer
a signed integer – use get_number_integer() for actual value
value_float
an floating point number – use get_number_float() for actual value
begin_array
the character for array begin [
begin_object
the character for object begin {
end_array
the character for array end ]
end_object
the character for object end }
name_separator
the name separator :
value_separator
the value separator ,
parse_error
indicating a parse error
end_of_input
indicating the end of the input buffer
literal_or_value
a literal or the begin of a value (only for diagnostics)
Definition at line 40 of file lexer.hpp.
     {
         uninitialized,
         literal_true,
         literal_false,
         literal_null,
         value_string,
         value_unsigned,
         value_integer,
         value_float,
         begin_array,
         begin_object,
         end_array,
         end_object,
         name_separator,
         value_separator,
         parse_error,
         end_of_input,
         literal_or_value
     };
token_type [2/2]
template<typename BasicJsonType > enum nlohmann::detail::lexer::token_type strong
token types for the parser
Enumerator
uninitialized
indicating the scanner is uninitialized
literal_true
the true literal
literal_false
the false literal
literal_null
the null literal
value_string
a string – use get_string() for actual value
value_unsigned
an unsigned integer – use get_number_unsigned() for actual value
value_integer
a signed integer – use get_number_integer() for actual value
value_float
an floating point number – use get_number_float() for actual value
begin_array
the character for array begin [
begin_object
the character for object begin {
end_array
the character for array end ]
end_object
the character for object end }
name_separator
the name separator :
value_separator
the value separator ,
parse_error
indicating a parse error
end_of_input
indicating the end of the input buffer
literal_or_value
a literal or the begin of a value (only for diagnostics)
uninitialized
indicating the scanner is uninitialized
literal_true
the true literal
literal_false
the false literal
literal_null
the null literal
value_string
a string – use get_string() for actual value
value_unsigned
an unsigned integer – use get_number_unsigned() for actual value
value_integer
a signed integer – use get_number_integer() for actual value
value_float
an floating point number – use get_number_float() for actual value
begin_array
the character for array begin [
begin_object
the character for object begin {
end_array
the character for array end ]
end_object
the character for object end }
name_separator
the name separator :
value_separator
the value separator ,
parse_error
indicating a parse error
end_of_input
indicating the end of the input buffer
literal_or_value
a literal or the begin of a value (only for diagnostics)
Definition at line 7170 of file json.hpp.
     {
         uninitialized,
         literal_true,
         literal_false,
         literal_null,
         value_string,
         value_unsigned,
         value_integer,
         value_float,
         begin_array,
         begin_object,
         end_array,
         end_object,
         name_separator,
         value_separator,
         parse_error,
         end_of_input,
         literal_or_value
     };
Constructor & Destructor Documentation
lexer() [1/6]
template<typename BasicJsonType > nlohmann::detail::lexer< BasicJsonType >::lexer (detail::input_adapter_t && adapter) inline explicit
Definition at line 107 of file lexer.hpp.
         : ia(std::move(adapter)), decimal_point_char(get_decimal_point()) {}
lexer() [2/6]
template<typename BasicJsonType > nlohmann::detail::lexer< BasicJsonType >::lexer (const lexer< BasicJsonType > &) delete
lexer() [3/6]
template<typename BasicJsonType > nlohmann::detail::lexer< BasicJsonType >::lexer (lexer< BasicJsonType > &&) delete
~lexer() [1/2]
template<typename BasicJsonType > nlohmann::detail::lexer< BasicJsonType >::~lexer () default
lexer() [4/6]
template<typename BasicJsonType > nlohmann::detail::lexer< BasicJsonType >::lexer (detail::input_adapter_t && adapter) inline explicit
Definition at line 7237 of file json.hpp.
         : ia(std::move(adapter)), decimal_point_char(get_decimal_point()) {}
lexer() [5/6]
template<typename BasicJsonType > nlohmann::detail::lexer< BasicJsonType >::lexer (const lexer< BasicJsonType > &) delete
lexer() [6/6]
template<typename BasicJsonType > nlohmann::detail::lexer< BasicJsonType >::lexer (lexer< BasicJsonType > &&) delete
~lexer() [2/2]
template<typename BasicJsonType > nlohmann::detail::lexer< BasicJsonType >::~lexer () default
Member Function Documentation
add() [1/2]
template<typename BasicJsonType > void nlohmann::detail::lexer< BasicJsonType >::add (int c) inline private
add a character to token_buffer
Definition at line 1311 of file lexer.hpp.
     {
         token_buffer.push_back(std::char_traits<char>::to_char_type(c));
     }
References c, and nlohmann::detail::lexer< BasicJsonType >::token_buffer.
Referenced by nlohmann::detail::lexer< BasicJsonType >::next_byte_in_range(), nlohmann::detail::lexer< BasicJsonType >::scan_number(), and nlohmann::detail::lexer< BasicJsonType >::scan_string().
add() [2/2]
template<typename BasicJsonType > void nlohmann::detail::lexer< BasicJsonType >::add (int c) inline private
add a character to token_buffer
Definition at line 8441 of file json.hpp.
     {
         token_buffer.push_back(std::char_traits<char>::to_char_type(c));
     }
References c, and nlohmann::detail::lexer< BasicJsonType >::token_buffer.
get() [1/2]
template<typename BasicJsonType > std::char_traits<char>::int_type nlohmann::detail::lexer< BasicJsonType >::get () inline private
Definition at line 1247 of file lexer.hpp.
     {
         ++position.chars_read_total;
         ++position.chars_read_current_line;
         if (next_unget)
         {
             // just reset the next_unget variable and work with current
             next_unget = false;
         }
         else
         {
             current = ia->get_character();
         }
         if (JSON_HEDLEY_LIKELY(current != std::char_traits<char>::eof()))
         {
             token_string.push_back(std::char_traits<char>::to_char_type(current));
         }
         if (current == '\n')
         {
             ++position.lines_read;
             position.chars_read_current_line = 0;
         }
         return current;
     }
References nlohmann::detail::position_t::chars_read_current_line, nlohmann::detail::position_t::chars_read_total, nlohmann::detail::lexer< BasicJsonType >::current, nlohmann::detail::lexer< BasicJsonType >::ia, JSON_HEDLEY_LIKELY, nlohmann::detail::position_t::lines_read, nlohmann::detail::lexer< BasicJsonType >::next_unget, nlohmann::detail::lexer< BasicJsonType >::position, and nlohmann::detail::lexer< BasicJsonType >::token_string.
Referenced by nlohmann::detail::lexer< BasicJsonType >::get_codepoint(), nlohmann::detail::lexer< BasicJsonType >::next_byte_in_range(), nlohmann::detail::lexer< BasicJsonType >::scan(), nlohmann::detail::lexer< BasicJsonType >::scan_literal(), nlohmann::detail::lexer< BasicJsonType >::scan_number(), nlohmann::detail::lexer< BasicJsonType >::scan_string(), and nlohmann::detail::lexer< BasicJsonType >::skip_bom().
get() [2/2]
template<typename BasicJsonType > std::char_traits<char>::int_type nlohmann::detail::lexer< BasicJsonType >::get () inline private
Definition at line 8377 of file json.hpp.
     {
         ++position.chars_read_total;
         ++position.chars_read_current_line;
         if (next_unget)
         {
             // just reset the next_unget variable and work with current
             next_unget = false;
         }
         else
         {
             current = ia->get_character();
         }
         if (JSON_HEDLEY_LIKELY(current != std::char_traits<char>::eof()))
         {
             token_string.push_back(std::char_traits<char>::to_char_type(current));
         }
         if (current == '\n')
         {
             ++position.lines_read;
             position.chars_read_current_line = 0;
         }
         return current;
     }
References nlohmann::detail::position_t::chars_read_current_line, nlohmann::detail::position_t::chars_read_total, nlohmann::detail::lexer< BasicJsonType >::current, nlohmann::detail::lexer< BasicJsonType >::ia, JSON_HEDLEY_LIKELY, nlohmann::detail::position_t::lines_read, nlohmann::detail::lexer< BasicJsonType >::next_unget, nlohmann::detail::lexer< BasicJsonType >::position, and nlohmann::detail::lexer< BasicJsonType >::token_string.
get_codepoint() [1/2]
template<typename BasicJsonType > int nlohmann::detail::lexer< BasicJsonType >::get_codepoint () inline private
get codepoint from 4 hex characters following \u
For input "\u c1 c2 c3 c4" the codepoint is: (c1 * 0x1000) + (c2 * 0x0100) + (c3 * 0x0010) + c4 = (c1 << 12) + (c2 << 8) + (c3 << 4) + (c4 << 0)
Furthermore, the possible characters '0'..'9', 'A'..'F', and 'a'..'f' must be converted to the integers 0x0..0x9, 0xA..0xF, 0xA..0xF, resp. The conversion is done by subtracting the offset (0x30, 0x37, and 0x57) between the ASCII value of the character and the desired integer value.
Returns
codepoint (0x0000..0xFFFF) or -1 in case of an error (e.g. EOF or non-hex character)
Definition at line 150 of file lexer.hpp.
     {
         // this function only makes sense after reading `\u`
         assert(current == 'u');
         int codepoint = 0;
         const auto factors = { 12u, 8u, 4u, 0u };
         for (const auto factor : factors)
         {
             get();
             if (current >= '0' and current <= '9')
             {
                 codepoint += static_cast<int>((static_cast<unsigned int>(current) - 0x30u) << factor);
             }
             else if (current >= 'A' and current <= 'F')
             {
                 codepoint += static_cast<int>((static_cast<unsigned int>(current) - 0x37u) << factor);
             }
             else if (current >= 'a' and current <= 'f')
             {
                 codepoint += static_cast<int>((static_cast<unsigned int>(current) - 0x57u) << factor);
             }
             else
             {
                 return -1;
             }
         }
         assert(0x0000 <= codepoint and codepoint <= 0xFFFF);
         return codepoint;
     }
References assert(), nlohmann::detail::lexer< BasicJsonType >::current, and nlohmann::detail::lexer< BasicJsonType >::get().
Referenced by nlohmann::detail::lexer< BasicJsonType >::scan_string().
get_codepoint() [2/2]
template<typename BasicJsonType > int nlohmann::detail::lexer< BasicJsonType >::get_codepoint () inline private
get codepoint from 4 hex characters following \u
For input "\u c1 c2 c3 c4" the codepoint is: (c1 * 0x1000) + (c2 * 0x0100) + (c3 * 0x0010) + c4 = (c1 << 12) + (c2 << 8) + (c3 << 4) + (c4 << 0)
Furthermore, the possible characters '0'..'9', 'A'..'F', and 'a'..'f' must be converted to the integers 0x0..0x9, 0xA..0xF, 0xA..0xF, resp. The conversion is done by subtracting the offset (0x30, 0x37, and 0x57) between the ASCII value of the character and the desired integer value.
Returns
codepoint (0x0000..0xFFFF) or -1 in case of an error (e.g. EOF or non-hex character)
Definition at line 7280 of file json.hpp.
     {
         // this function only makes sense after reading `\u`
         assert(current == 'u');
         int codepoint = 0;
         const auto factors = { 12u, 8u, 4u, 0u };
         for (const auto factor : factors)
         {
             get();
             if (current >= '0' and current <= '9')
             {
                 codepoint += static_cast<int>((static_cast<unsigned int>(current) - 0x30u) << factor);
             }
             else if (current >= 'A' and current <= 'F')
             {
                 codepoint += static_cast<int>((static_cast<unsigned int>(current) - 0x37u) << factor);
             }
             else if (current >= 'a' and current <= 'f')
             {
                 codepoint += static_cast<int>((static_cast<unsigned int>(current) - 0x57u) << factor);
             }
             else
             {
                 return -1;
             }
         }
         assert(0x0000 <= codepoint and codepoint <= 0xFFFF);
         return codepoint;
     }
References assert(), nlohmann::detail::lexer< BasicJsonType >::current, and nlohmann::detail::lexer< BasicJsonType >::get().
get_decimal_point() [1/2]
template<typename BasicJsonType > static JSON_HEDLEY_PURE char nlohmann::detail::lexer< BasicJsonType >::get_decimal_point () inline static private noexcept
return the locale-dependent decimal point
Definition at line 124 of file lexer.hpp.
     {
         const auto loc = localeconv();
         assert(loc != nullptr);
         return (loc->decimal_point == nullptr) ? '.' : *(loc->decimal_point);
     }
References assert().
get_decimal_point() [2/2]
template<typename BasicJsonType > static char nlohmann::detail::lexer< BasicJsonType >::get_decimal_point () inline static private noexcept
return the locale-dependent decimal point
Definition at line 7254 of file json.hpp.
     {
         const auto loc = localeconv();
         assert(loc != nullptr);
         return (loc->decimal_point == nullptr) ? '.' : *(loc->decimal_point);
     }
References assert().
get_error_message() [1/2]
template<typename BasicJsonType > constexpr const JSON_HEDLEY_RETURNS_NON_NULL char* nlohmann::detail::lexer< BasicJsonType >::get_error_message () const inline constexpr noexcept
return syntax error message
Definition at line 1383 of file lexer.hpp.
     {
         return error_message;
     }
References nlohmann::detail::lexer< BasicJsonType >::error_message.
Referenced by nlohmann::detail::parser< BasicJsonType >::exception_message().
get_error_message() [2/2]
template<typename BasicJsonType > constexpr const char* nlohmann::detail::lexer< BasicJsonType >::get_error_message () const inline constexpr noexcept
return syntax error message
Definition at line 8513 of file json.hpp.
     {
         return error_message;
     }
References nlohmann::detail::lexer< BasicJsonType >::error_message.
get_number_float() [1/2]
template<typename BasicJsonType > constexpr number_float_t nlohmann::detail::lexer< BasicJsonType >::get_number_float () const inline constexpr noexcept
return floating-point value
Definition at line 1334 of file lexer.hpp.
     {
         return value_float;
     }
References nlohmann::detail::lexer< BasicJsonType >::value_float.
Referenced by nlohmann::detail::parser< BasicJsonType >::sax_parse_internal().
get_number_float() [2/2]
template<typename BasicJsonType > constexpr number_float_t nlohmann::detail::lexer< BasicJsonType >::get_number_float () const inline constexpr noexcept
return floating-point value
Definition at line 8464 of file json.hpp.
     {
         return value_float;
     }
References nlohmann::detail::lexer< BasicJsonType >::value_float.
get_number_integer() [1/2]
template<typename BasicJsonType > constexpr number_integer_t nlohmann::detail::lexer< BasicJsonType >::get_number_integer () const inline constexpr noexcept
return integer value
Definition at line 1322 of file lexer.hpp.
     {
         return value_integer;
     }
References nlohmann::detail::lexer< BasicJsonType >::value_integer.
Referenced by nlohmann::detail::parser< BasicJsonType >::sax_parse_internal().
get_number_integer() [2/2]
template<typename BasicJsonType > constexpr number_integer_t nlohmann::detail::lexer< BasicJsonType >::get_number_integer () const inline constexpr noexcept
return integer value
Definition at line 8452 of file json.hpp.
     {
         return value_integer;
     }
References nlohmann::detail::lexer< BasicJsonType >::value_integer.
get_number_unsigned() [1/2]
template<typename BasicJsonType > constexpr number_unsigned_t nlohmann::detail::lexer< BasicJsonType >::get_number_unsigned () const inline constexpr noexcept
return unsigned integer value
Definition at line 1328 of file lexer.hpp.
     {
         return value_unsigned;
     }
References nlohmann::detail::lexer< BasicJsonType >::value_unsigned.
Referenced by nlohmann::detail::parser< BasicJsonType >::sax_parse_internal().
get_number_unsigned() [2/2]
template<typename BasicJsonType > constexpr number_unsigned_t nlohmann::detail::lexer< BasicJsonType >::get_number_unsigned () const inline constexpr noexcept
return unsigned integer value
Definition at line 8458 of file json.hpp.
     {
         return value_unsigned;
     }
References nlohmann::detail::lexer< BasicJsonType >::value_unsigned.
get_position() [1/2]
template<typename BasicJsonType > constexpr position_t nlohmann::detail::lexer< BasicJsonType >::get_position () const inline constexpr noexcept
return position of last read token
Definition at line 1350 of file lexer.hpp.
     {
         return position;
     }
References nlohmann::detail::lexer< BasicJsonType >::position.
Referenced by nlohmann::detail::parser< BasicJsonType >::parse(), nlohmann::detail::parser< BasicJsonType >::sax_parse(), and nlohmann::detail::parser< BasicJsonType >::sax_parse_internal().
get_position() [2/2]
template<typename BasicJsonType > constexpr position_t nlohmann::detail::lexer< BasicJsonType >::get_position () const inline constexpr noexcept
return position of last read token
Definition at line 8480 of file json.hpp.
     {
         return position;
     }
References nlohmann::detail::lexer< BasicJsonType >::position.
get_string() [1/2]
template<typename BasicJsonType > string_t& nlohmann::detail::lexer< BasicJsonType >::get_string () inline
return current string value (implicitly resets the token; useful only once)
Definition at line 1340 of file lexer.hpp.
     {
         return token_buffer;
     }
References nlohmann::detail::lexer< BasicJsonType >::token_buffer.
Referenced by nlohmann::detail::parser< BasicJsonType >::sax_parse_internal().
get_string() [2/2]
template<typename BasicJsonType > string_t& nlohmann::detail::lexer< BasicJsonType >::get_string () inline
return current string value (implicitly resets the token; useful only once)
Definition at line 8470 of file json.hpp.
     {
         return token_buffer;
     }
References nlohmann::detail::lexer< BasicJsonType >::token_buffer.
get_token_string() [1/2]
template<typename BasicJsonType > std::string nlohmann::detail::lexer< BasicJsonType >::get_token_string () const inline
return the last read token (for errors only). Will never contain EOF (an arbitrary value that is not a valid char value, often -1), because 255 may legitimately occur. May contain NUL, which should be escaped.
Definition at line 1358 of file lexer.hpp.
     {
         // escape control characters
         std::string result;
         for (const auto c : token_string)
         {
             if ('\x00' <= c and c <= '\x1F')
             {
                 // escape control characters
                 std::array<char, 9> cs{{}};
                 (std::snprintf)(cs.data(), cs.size(), "<U+%.4X>", static_cast<unsigned char>(c));
                 result += cs.data();
             }
             else
             {
                 // add character as is
                 result.push_back(c);
             }
         }
         return result;
     }
References c, result, and nlohmann::detail::lexer< BasicJsonType >::token_string.
Referenced by nlohmann::detail::parser< BasicJsonType >::exception_message(), nlohmann::detail::parser< BasicJsonType >::parse(), nlohmann::detail::parser< BasicJsonType >::sax_parse(), and nlohmann::detail::parser< BasicJsonType >::sax_parse_internal().
get_token_string() [2/2]
template<typename BasicJsonType > std::string nlohmann::detail::lexer< BasicJsonType >::get_token_string () const inline
return the last read token (for errors only). Will never contain EOF (an arbitrary value that is not a valid char value, often -1), because 255 may legitimately occur. May contain NUL, which should be escaped.
Definition at line 8488 of file json.hpp.
     {
         // escape control characters
         std::string result;
         for (const auto c : token_string)
         {
             if ('\x00' <= c and c <= '\x1F')
             {
                 // escape control characters
                 std::array<char, 9> cs{{}};
                 (std::snprintf)(cs.data(), cs.size(), "<U+%.4X>", static_cast<unsigned char>(c));
                 result += cs.data();
             }
             else
             {
                 // add character as is
                 result.push_back(c);
             }
         }
         return result;
     }
References c, result, and nlohmann::detail::lexer< BasicJsonType >::token_string.
next_byte_in_range() [1/2]
template<typename BasicJsonType > bool nlohmann::detail::lexer< BasicJsonType >::next_byte_in_range (std::initializer_list< int > ranges) inline private
check if the next byte(s) are inside a given range
Adds the current byte and, for each passed range, reads a new byte and checks if it is inside the range. If a violation was detected, set up an error message and return false. Otherwise, return true.
Parameters
[in] ranges list of integers; interpreted as list of pairs of inclusive lower and upper bound, respectively
Precondition
The passed list ranges must have 2, 4, or 6 elements; that is, 1, 2, or 3 pairs. This precondition is enforced by an assertion.
Returns
true if and only if no range violation was detected
Definition at line 198 of file lexer.hpp.
     {
         assert(ranges.size() == 2 or ranges.size() == 4 or ranges.size() == 6);
         add(current);
         for (auto range = ranges.begin(); range != ranges.end(); ++range)
         {
             get();
             if (JSON_HEDLEY_LIKELY(*range <= current and current <= *(++range)))
             {
                 add(current);
             }
             else
             {
                 error_message = "invalid string: ill-formed UTF-8 byte";
                 return false;
             }
         }
         return true;
     }
References nlohmann::detail::lexer< BasicJsonType >::add(), assert(), nlohmann::detail::lexer< BasicJsonType >::current, nlohmann::detail::lexer< BasicJsonType >::error_message, nlohmann::detail::lexer< BasicJsonType >::get(), and JSON_HEDLEY_LIKELY.
Referenced by nlohmann::detail::lexer< BasicJsonType >::scan_string().
next_byte_in_range() [2/2]
template<typename BasicJsonType > bool nlohmann::detail::lexer< BasicJsonType >::next_byte_in_range (std::initializer_list< int > ranges) inline private
check if the next byte(s) are inside a given range
Adds the current byte and, for each passed range, reads a new byte and checks if it is inside the range. If a violation was detected, set up an error message and return false. Otherwise, return true.
Parameters
[in] ranges list of integers; interpreted as list of pairs of inclusive lower and upper bound, respectively
Precondition
The passed list ranges must have 2, 4, or 6 elements; that is, 1, 2, or 3 pairs. This precondition is enforced by an assertion.
Returns
true if and only if no range violation was detected
Definition at line 7328 of file json.hpp.
     {
         assert(ranges.size() == 2 or ranges.size() == 4 or ranges.size() == 6);
         add(current);
         for (auto range = ranges.begin(); range != ranges.end(); ++range)
         {
             get();
             if (JSON_HEDLEY_LIKELY(*range <= current and current <= *(++range)))
             {
                 add(current);
             }
             else
             {
                 error_message = "invalid string: ill-formed UTF-8 byte";
                 return false;
             }
         }
         return true;
     }
References nlohmann::detail::lexer< BasicJsonType >::add(), assert(), nlohmann::detail::lexer< BasicJsonType >::current, nlohmann::detail::lexer< BasicJsonType >::error_message, nlohmann::detail::lexer< BasicJsonType >::get(), and JSON_HEDLEY_LIKELY.
operator=() [1/4]
template<typename BasicJsonType > lexer& nlohmann::detail::lexer< BasicJsonType >::operator= (lexer< BasicJsonType > &&) delete
operator=() [2/4]
template<typename BasicJsonType > lexer& nlohmann::detail::lexer< BasicJsonType >::operator= (lexer< BasicJsonType > &&) delete
operator=() [3/4]
template<typename BasicJsonType > lexer& nlohmann::detail::lexer< BasicJsonType >::operator= (lexer< BasicJsonType > &) delete
operator=() [4/4]
template<typename BasicJsonType > lexer& nlohmann::detail::lexer< BasicJsonType >::operator= (lexer< BasicJsonType > &) delete
reset() [1/2]
template<typename BasicJsonType > void nlohmann::detail::lexer< BasicJsonType >::reset () inline private noexcept
reset token_buffer; current character is beginning of token
Definition at line 1230 of file lexer.hpp.
     {
         token_buffer.clear();
         token_string.clear();
         token_string.push_back(std::char_traits<char>::to_char_type(current));
     }
References nlohmann::detail::lexer< BasicJsonType >::current, nlohmann::detail::lexer< BasicJsonType >::token_buffer, and nlohmann::detail::lexer< BasicJsonType >::token_string.
Referenced by nlohmann::detail::lexer< BasicJsonType >::scan_number(), and nlohmann::detail::lexer< BasicJsonType >::scan_string().
reset() [2/2]
template<typename BasicJsonType > void nlohmann::detail::lexer< BasicJsonType >::reset () inline private noexcept
reset token_buffer; current character is beginning of token
Definition at line 8360 of file json.hpp.
     {
         token_buffer.clear();
         token_string.clear();
         token_string.push_back(std::char_traits<char>::to_char_type(current));
     }
References nlohmann::detail::lexer< BasicJsonType >::current, nlohmann::detail::lexer< BasicJsonType >::token_buffer, and nlohmann::detail::lexer< BasicJsonType >::token_string.
scan() [1/2]
template<typename BasicJsonType > token_type nlohmann::detail::lexer< BasicJsonType >::scan () inline
Definition at line 1410 of file lexer.hpp.
     {
         // initially, skip the BOM
         if (position.chars_read_total == 0 and not skip_bom())
         {
             error_message = "invalid BOM; must be 0xEF 0xBB 0xBF if given";
             return token_type::parse_error;
         }
         // read next character and ignore whitespace
         do
         {
             get();
         }
         while (current == ' ' or current == '\t' or current == '\n' or current == '\r');
         switch (current)
         {
             // structural characters
             case '[':
                 return token_type::begin_array;
             case ']':
                 return token_type::end_array;
             case '{':
                 return token_type::begin_object;
             case '}':
                 return token_type::end_object;
             case ':':
                 return token_type::name_separator;
             case ',':
                 return token_type::value_separator;
             // literals
             case 't':
                 return scan_literal("true", 4, token_type::literal_true);
             case 'f':
                 return scan_literal("false", 5, token_type::literal_false);
             case 'n':
                 return scan_literal("null", 4, token_type::literal_null);
             // string
             case '\"':
                 return scan_string();
             // number
             case '-':
             case '0':
             case '1':
             case '2':
             case '3':
             case '4':
             case '5':
             case '6':
             case '7':
             case '8':
             case '9':
                 return scan_number();
             // end of input (the null byte is needed when parsing from
             // string literals)
             case '\0':
             case std::char_traits<char>::eof():
                 return token_type::end_of_input;
             // error
             default:
                 error_message = "invalid literal";
                 return token_type::parse_error;
         }
     }
References nlohmann::detail::lexer< BasicJsonType >::begin_array, nlohmann::detail::lexer< BasicJsonType >::begin_object, nlohmann::detail::position_t::chars_read_total, nlohmann::detail::lexer< BasicJsonType >::current, nlohmann::detail::lexer< BasicJsonType >::end_array, nlohmann::detail::lexer< BasicJsonType >::end_object, nlohmann::detail::lexer< BasicJsonType >::end_of_input, nlohmann::detail::lexer< BasicJsonType >::error_message, nlohmann::detail::lexer< BasicJsonType >::get(), nlohmann::detail::lexer< BasicJsonType >::literal_false, nlohmann::detail::lexer< BasicJsonType >::literal_null, nlohmann::detail::lexer< BasicJsonType >::literal_true, nlohmann::detail::lexer< BasicJsonType >::name_separator, nlohmann::detail::lexer< BasicJsonType >::parse_error, nlohmann::detail::lexer< BasicJsonType >::position, nlohmann::detail::lexer< BasicJsonType >::scan_literal(), nlohmann::detail::lexer< BasicJsonType >::scan_number(), nlohmann::detail::lexer< BasicJsonType >::scan_string(), nlohmann::detail::lexer< BasicJsonType >::skip_bom(), and nlohmann::detail::lexer< BasicJsonType >::value_separator.
Referenced by nlohmann::detail::parser< BasicJsonType >::get_token().
scan() [2/2]
template<typename BasicJsonType > token_type nlohmann::detail::lexer< BasicJsonType >::scan () inline
Definition at line 8540 of file json.hpp.
     {
         // initially, skip the BOM
         if (position.chars_read_total == 0 and not skip_bom())
         {
             error_message = "invalid BOM; must be 0xEF 0xBB 0xBF if given";
             return token_type::parse_error;
         }
         // read next character and ignore whitespace
         do
         {
             get();
         }
         while (current == ' ' or current == '\t' or current == '\n' or current == '\r');
         switch (current)
         {
             // structural characters
             case '[':
                 return token_type::begin_array;
             case ']':
                 return token_type::end_array;
             case '{':
                 return token_type::begin_object;
             case '}':
                 return token_type::end_object;
             case ':':
                 return token_type::name_separator;
             case ',':
                 return token_type::value_separator;
             // literals
             case 't':
                 return scan_literal("true", 4, token_type::literal_true);
             case 'f':
                 return scan_literal("false", 5, token_type::literal_false);
             case 'n':
                 return scan_literal("null", 4, token_type::literal_null);
             // string
             case '\"':
                 return scan_string();
             // number
             case '-':
             case '0':
             case '1':
             case '2':
             case '3':
             case '4':
             case '5':
             case '6':
             case '7':
             case '8':
             case '9':
                 return scan_number();
             // end of input (the null byte is needed when parsing from
             // string literals)
             case '\0':
             case std::char_traits<char>::eof():
                 return token_type::end_of_input;
             // error
             default:
                 error_message = "invalid literal";
                 return token_type::parse_error;
         }
     }
References nlohmann::detail::lexer< BasicJsonType >::begin_array, nlohmann::detail::lexer< BasicJsonType >::begin_object, nlohmann::detail::position_t::chars_read_total, nlohmann::detail::lexer< BasicJsonType >::current, nlohmann::detail::lexer< BasicJsonType >::end_array, nlohmann::detail::lexer< BasicJsonType >::end_object, nlohmann::detail::lexer< BasicJsonType >::end_of_input, nlohmann::detail::lexer< BasicJsonType >::error_message, nlohmann::detail::lexer< BasicJsonType >::get(), nlohmann::detail::lexer< BasicJsonType >::literal_false, nlohmann::detail::lexer< BasicJsonType >::literal_null, nlohmann::detail::lexer< BasicJsonType >::literal_true, nlohmann::detail::lexer< BasicJsonType >::name_separator, nlohmann::detail::lexer< BasicJsonType >::parse_error, nlohmann::detail::lexer< BasicJsonType >::position, nlohmann::detail::lexer< BasicJsonType >::scan_literal(), nlohmann::detail::lexer< BasicJsonType >::scan_number(), nlohmann::detail::lexer< BasicJsonType >::scan_string(), nlohmann::detail::lexer< BasicJsonType >::skip_bom(), and nlohmann::detail::lexer< BasicJsonType >::value_separator.
scan_literal() [1/2]
template<typename BasicJsonType > token_type nlohmann::detail::lexer< BasicJsonType >::scan_literal (const char * literal_text, const std::size_t length, token_type return_type) inline private
Parameters
[in] literal_text the literal text to expect
[in] length the length of the passed literal text
[in] return_type the token type to return on success
Definition at line 1210 of file lexer.hpp.
     {
         assert(current == literal_text[0]);
         for (std::size_t i = 1; i < length; ++i)
         {
             if (JSON_HEDLEY_UNLIKELY(get() != literal_text[i]))
             {
                 error_message = "invalid literal";
                 return token_type::parse_error;
             }
         }
         return return_type;
     }
References assert(), nlohmann::detail::lexer< BasicJsonType >::current, nlohmann::detail::lexer< BasicJsonType >::error_message, nlohmann::detail::lexer< BasicJsonType >::get(), JSON_HEDLEY_UNLIKELY, and nlohmann::detail::lexer< BasicJsonType >::parse_error.
Referenced by nlohmann::detail::lexer< BasicJsonType >::scan().
scan_literal() [2/2]
template<typename BasicJsonType > token_type nlohmann::detail::lexer< BasicJsonType >::scan_literal (const char * literal_text, const std::size_t length, token_type return_type) inline private
Parameters
[in] literal_text the literal text to expect
[in] length the length of the passed literal text
[in] return_type the token type to return on success
Definition at line 8340 of file json.hpp.
     {
         assert(current == literal_text[0]);
         for (std::size_t i = 1; i < length; ++i)
         {
             if (JSON_HEDLEY_UNLIKELY(get() != literal_text[i]))
             {
                 error_message = "invalid literal";
                 return token_type::parse_error;
             }
         }
         return return_type;
     }
References assert(), nlohmann::detail::lexer< BasicJsonType >::current, nlohmann::detail::lexer< BasicJsonType >::error_message, nlohmann::detail::lexer< BasicJsonType >::get(), JSON_HEDLEY_UNLIKELY, and nlohmann::detail::lexer< BasicJsonType >::parse_error.
scan_number() [1/2]
template<typename BasicJsonType > token_type nlohmann::detail::lexer< BasicJsonType >::scan_number () inline private
scan a number literal
This function scans a string according to Sect. 6 of RFC 7159.
The function is realized with a deterministic finite state machine derived from the grammar described in RFC 7159. Starting in state "init", the input is read and used to determined the next state. Only state "done" accepts the number. State "error" is a trap state to model errors. In the table below, "anything" means any character but the ones listed before.
state 0 1-9 e E + - . anything
init zero any1 [error] [error] minus [error] [error]
minus zero any1 [error] [error] [error] [error] [error]
zero done done exponent done done decimal1 done
any1 any1 any1 exponent done done decimal1 done
decimal1 decimal2 [error] [error] [error] [error] [error] [error]
decimal2 decimal2 decimal2 exponent done done done done
exponent any2 any2 [error] sign sign [error] [error]
sign any2 any2 [error] [error] [error] [error] [error]
any2 any2 any2 done done done done done
The state machine is realized with one label per state (prefixed with "scan_number_") and goto statements between them. The state machine contains cycles, but any cycle can be left when EOF is read. Therefore, the function is guaranteed to terminate.
During scanning, the read bytes are stored in token_buffer. This string is then converted to a signed integer, an unsigned integer, or a floating-point number.
Returns
token_type::value_unsigned, token_type::value_integer, or token_type::value_float if number could be successfully scanned, token_type::parse_error otherwise
Note
The scanner is independent of the current locale. Internally, the locale's decimal point is used instead of . to work with the locale-dependent converters.
Definition at line 879 of file lexer.hpp.
     {
         // reset token_buffer to store the number's bytes
         reset();
         // the type of the parsed number; initially set to unsigned; will be
         // changed if minus sign, decimal point or exponent is read
         token_type number_type = token_type::value_unsigned;
         // state (init): we just found out we need to scan a number
         switch (current)
         {
             case '-':
             {
                 add(current);
                 goto scan_number_minus;
             }
             case '0':
             {
                 add(current);
                 goto scan_number_zero;
             }
             case '1':
             case '2':
             case '3':
             case '4':
             case '5':
             case '6':
             case '7':
             case '8':
             case '9':
             {
                 add(current);
                 goto scan_number_any1;
             }
             // all other characters are rejected outside scan_number()
             default:            // LCOV_EXCL_LINE
                 assert(false);  // LCOV_EXCL_LINE
         }
 scan_number_minus:
         // state: we just parsed a leading minus sign
         number_type = token_type::value_integer;
         switch (get())
         {
             case '0':
             {
                 add(current);
                 goto scan_number_zero;
             }
             case '1':
             case '2':
             case '3':
             case '4':
             case '5':
             case '6':
             case '7':
             case '8':
             case '9':
             {
                 add(current);
                 goto scan_number_any1;
             }
             default:
             {
                 error_message = "invalid number; expected digit after '-'";
                 return token_type::parse_error;
             }
         }
 scan_number_zero:
         // state: we just parse a zero (maybe with a leading minus sign)
         switch (get())
         {
             case '.':
             {
                 add(decimal_point_char);
                 goto scan_number_decimal1;
             }
             case 'e':
             case 'E':
             {
                 add(current);
                 goto scan_number_exponent;
             }
             default:
                 goto scan_number_done;
         }
 scan_number_any1:
         // state: we just parsed a number 0-9 (maybe with a leading minus sign)
         switch (get())
         {
             case '0':
             case '1':
             case '2':
             case '3':
             case '4':
             case '5':
             case '6':
             case '7':
             case '8':
             case '9':
             {
                 add(current);
                 goto scan_number_any1;
             }
             case '.':
             {
                 add(decimal_point_char);
                 goto scan_number_decimal1;
             }
             case 'e':
             case 'E':
             {
                 add(current);
                 goto scan_number_exponent;
             }
             default:
                 goto scan_number_done;
         }
 scan_number_decimal1:
         // state: we just parsed a decimal point
         number_type = token_type::value_float;
         switch (get())
         {
             case '0':
             case '1':
             case '2':
             case '3':
             case '4':
             case '5':
             case '6':
             case '7':
             case '8':
             case '9':
             {
                 add(current);
                 goto scan_number_decimal2;
             }
             default:
             {
                 error_message = "invalid number; expected digit after '.'";
                 return token_type::parse_error;
             }
         }
 scan_number_decimal2:
         // we just parsed at least one number after a decimal point
         switch (get())
         {
             case '0':
             case '1':
             case '2':
             case '3':
             case '4':
             case '5':
             case '6':
             case '7':
             case '8':
             case '9':
             {
                 add(current);
                 goto scan_number_decimal2;
             }
             case 'e':
             case 'E':
             {
                 add(current);
                 goto scan_number_exponent;
             }
             default:
                 goto scan_number_done;
         }
 scan_number_exponent:
         // we just parsed an exponent
         number_type = token_type::value_float;
         switch (get())
         {
             case '+':
             case '-':
             {
                 add(current);
                 goto scan_number_sign;
             }
             case '0':
             case '1':
             case '2':
             case '3':
             case '4':
             case '5':
             case '6':
             case '7':
             case '8':
             case '9':
             {
                 add(current);
                 goto scan_number_any2;
             }
             default:
             {
                 error_message =
                     "invalid number; expected '+', '-', or digit after exponent";
                 return token_type::parse_error;
             }
         }
 scan_number_sign:
         // we just parsed an exponent sign
         switch (get())
         {
             case '0':
             case '1':
             case '2':
             case '3':
             case '4':
             case '5':
             case '6':
             case '7':
             case '8':
             case '9':
             {
                 add(current);
                 goto scan_number_any2;
             }
             default:
             {
                 error_message = "invalid number; expected digit after exponent sign";
                 return token_type::parse_error;
             }
         }
 scan_number_any2:
         // we just parsed a number after the exponent or exponent sign
         switch (get())
         {
             case '0':
             case '1':
             case '2':
             case '3':
             case '4':
             case '5':
             case '6':
             case '7':
             case '8':
             case '9':
             {
                 add(current);
                 goto scan_number_any2;
             }
             default:
                 goto scan_number_done;
         }
 scan_number_done:
         // unget the character after the number (we only read it to know that
         // we are done scanning a number)
         unget();
         char* endptr = nullptr;
         errno = 0;
         // try to parse integers first and fall back to floats
         if (number_type == token_type::value_unsigned)
         {
             const auto x = std::strtoull(token_buffer.data(), &endptr, 10);
             // we checked the number format before
             assert(endptr == token_buffer.data() + token_buffer.size());
             if (errno == 0)
             {
                 value_unsigned = static_cast<number_unsigned_t>(x);
                 if (value_unsigned == x)
                 {
                     return token_type::value_unsigned;
                 }
             }
         }
         else if (number_type == token_type::value_integer)
         {
             const auto x = std::strtoll(token_buffer.data(), &endptr, 10);
             // we checked the number format before
             assert(endptr == token_buffer.data() + token_buffer.size());
             if (errno == 0)
             {
                 value_integer = static_cast<number_integer_t>(x);
                 if (value_integer == x)
                 {
                     return token_type::value_integer;
                 }
             }
         }
         // this code is reached if we parse a floating-point number or if an
         // integer conversion above failed
         strtof(value_float, token_buffer.data(), &endptr);
         // we checked the number format before
         assert(endptr == token_buffer.data() + token_buffer.size());
         return token_type::value_float;
     }
References nlohmann::detail::lexer< BasicJsonType >::add(), assert(), nlohmann::detail::lexer< BasicJsonType >::current, nlohmann::detail::lexer< BasicJsonType >::decimal_point_char, nlohmann::detail::lexer< BasicJsonType >::error_message, nlohmann::detail::lexer< BasicJsonType >::get(), nlohmann::detail::lexer< BasicJsonType >::parse_error, nlohmann::detail::lexer< BasicJsonType >::reset(), nlohmann::detail::lexer< BasicJsonType >::strtof(), nlohmann::detail::lexer< BasicJsonType >::token_buffer, nlohmann::detail::lexer< BasicJsonType >::unget(), nlohmann::detail::lexer< BasicJsonType >::value_float, nlohmann::detail::lexer< BasicJsonType >::value_integer, and nlohmann::detail::lexer< BasicJsonType >::value_unsigned.
Referenced by nlohmann::detail::lexer< BasicJsonType >::scan().
scan_number() [2/2]
template<typename BasicJsonType > token_type nlohmann::detail::lexer< BasicJsonType >::scan_number () inline private
scan a number literal
This function scans a string according to Sect. 6 of RFC 7159.
The function is realized with a deterministic finite state machine derived from the grammar described in RFC 7159. Starting in state "init", the input is read and used to determined the next state. Only state "done" accepts the number. State "error" is a trap state to model errors. In the table below, "anything" means any character but the ones listed before.
state 0 1-9 e E + - . anything
init zero any1 [error] [error] minus [error] [error]
minus zero any1 [error] [error] [error] [error] [error]
zero done done exponent done done decimal1 done
any1 any1 any1 exponent done done decimal1 done
decimal1 decimal2 [error] [error] [error] [error] [error] [error]
decimal2 decimal2 decimal2 exponent done done done done
exponent any2 any2 [error] sign sign [error] [error]
sign any2 any2 [error] [error] [error] [error] [error]
any2 any2 any2 done done done done done
The state machine is realized with one label per state (prefixed with "scan_number_") and goto statements between them. The state machine contains cycles, but any cycle can be left when EOF is read. Therefore, the function is guaranteed to terminate.
During scanning, the read bytes are stored in token_buffer. This string is then converted to a signed integer, an unsigned integer, or a floating-point number.
Returns
token_type::value_unsigned, token_type::value_integer, or token_type::value_float if number could be successfully scanned, token_type::parse_error otherwise
Note
The scanner is independent of the current locale. Internally, the locale's decimal point is used instead of . to work with the locale-dependent converters.
Definition at line 8009 of file json.hpp.
     {
         // reset token_buffer to store the number's bytes
         reset();
         // the type of the parsed number; initially set to unsigned; will be
         // changed if minus sign, decimal point or exponent is read
         token_type number_type = token_type::value_unsigned;
         // state (init): we just found out we need to scan a number
         switch (current)
         {
             case '-':
             {
                 add(current);
                 goto scan_number_minus;
             }
             case '0':
             {
                 add(current);
                 goto scan_number_zero;
             }
             case '1':
             case '2':
             case '3':
             case '4':
             case '5':
             case '6':
             case '7':
             case '8':
             case '9':
             {
                 add(current);
                 goto scan_number_any1;
             }
             // all other characters are rejected outside scan_number()
             default:            // LCOV_EXCL_LINE
                 assert(false);  // LCOV_EXCL_LINE
         }
 scan_number_minus:
         // state: we just parsed a leading minus sign
         number_type = token_type::value_integer;
         switch (get())
         {
             case '0':
             {
                 add(current);
                 goto scan_number_zero;
             }
             case '1':
             case '2':
             case '3':
             case '4':
             case '5':
             case '6':
             case '7':
             case '8':
             case '9':
             {
                 add(current);
                 goto scan_number_any1;
             }
             default:
             {
                 error_message = "invalid number; expected digit after '-'";
                 return token_type::parse_error;
             }
         }
 scan_number_zero:
         // state: we just parse a zero (maybe with a leading minus sign)
         switch (get())
         {
             case '.':
             {
                 add(decimal_point_char);
                 goto scan_number_decimal1;
             }
             case 'e':
             case 'E':
             {
                 add(current);
                 goto scan_number_exponent;
             }
             default:
                 goto scan_number_done;
         }
 scan_number_any1:
         // state: we just parsed a number 0-9 (maybe with a leading minus sign)
         switch (get())
         {
             case '0':
             case '1':
             case '2':
             case '3':
             case '4':
             case '5':
             case '6':
             case '7':
             case '8':
             case '9':
             {
                 add(current);
                 goto scan_number_any1;
             }
             case '.':
             {
                 add(decimal_point_char);
                 goto scan_number_decimal1;
             }
             case 'e':
             case 'E':
             {
                 add(current);
                 goto scan_number_exponent;
             }
             default:
                 goto scan_number_done;
         }
 scan_number_decimal1:
         // state: we just parsed a decimal point
         number_type = token_type::value_float;
         switch (get())
         {
             case '0':
             case '1':
             case '2':
             case '3':
             case '4':
             case '5':
             case '6':
             case '7':
             case '8':
             case '9':
             {
                 add(current);
                 goto scan_number_decimal2;
             }
             default:
             {
                 error_message = "invalid number; expected digit after '.'";
                 return token_type::parse_error;
             }
         }
 scan_number_decimal2:
         // we just parsed at least one number after a decimal point
         switch (get())
         {
             case '0':
             case '1':
             case '2':
             case '3':
             case '4':
             case '5':
             case '6':
             case '7':
             case '8':
             case '9':
             {
                 add(current);
                 goto scan_number_decimal2;
             }
             case 'e':
             case 'E':
             {
                 add(current);
                 goto scan_number_exponent;
             }
             default:
                 goto scan_number_done;
         }
 scan_number_exponent:
         // we just parsed an exponent
         number_type = token_type::value_float;
         switch (get())
         {
             case '+':
             case '-':
             {
                 add(current);
                 goto scan_number_sign;
             }
             case '0':
             case '1':
             case '2':
             case '3':
             case '4':
             case '5':
             case '6':
             case '7':
             case '8':
             case '9':
             {
                 add(current);
                 goto scan_number_any2;
             }
             default:
             {
                 error_message =
                     "invalid number; expected '+', '-', or digit after exponent";
                 return token_type::parse_error;
             }
         }
 scan_number_sign:
         // we just parsed an exponent sign
         switch (get())
         {
             case '0':
             case '1':
             case '2':
             case '3':
             case '4':
             case '5':
             case '6':
             case '7':
             case '8':
             case '9':
             {
                 add(current);
                 goto scan_number_any2;
             }
             default:
             {
                 error_message = "invalid number; expected digit after exponent sign";
                 return token_type::parse_error;
             }
         }
 scan_number_any2:
         // we just parsed a number after the exponent or exponent sign
         switch (get())
         {
             case '0':
             case '1':
             case '2':
             case '3':
             case '4':
             case '5':
             case '6':
             case '7':
             case '8':
             case '9':
             {
                 add(current);
                 goto scan_number_any2;
             }
             default:
                 goto scan_number_done;
         }
 scan_number_done:
         // unget the character after the number (we only read it to know that
         // we are done scanning a number)
         unget();
         char* endptr = nullptr;
         errno = 0;
         // try to parse integers first and fall back to floats
         if (number_type == token_type::value_unsigned)
         {
             const auto x = std::strtoull(token_buffer.data(), &endptr, 10);
             // we checked the number format before
             assert(endptr == token_buffer.data() + token_buffer.size());
             if (errno == 0)
             {
                 value_unsigned = static_cast<number_unsigned_t>(x);
                 if (value_unsigned == x)
                 {
                     return token_type::value_unsigned;
                 }
             }
         }
         else if (number_type == token_type::value_integer)
         {
             const auto x = std::strtoll(token_buffer.data(), &endptr, 10);
             // we checked the number format before
             assert(endptr == token_buffer.data() + token_buffer.size());
             if (errno == 0)
             {
                 value_integer = static_cast<number_integer_t>(x);
                 if (value_integer == x)
                 {
                     return token_type::value_integer;
                 }
             }
         }
         // this code is reached if we parse a floating-point number or if an
         // integer conversion above failed
         strtof(value_float, token_buffer.data(), &endptr);
         // we checked the number format before
         assert(endptr == token_buffer.data() + token_buffer.size());
         return token_type::value_float;
     }
References nlohmann::detail::lexer< BasicJsonType >::add(), assert(), nlohmann::detail::lexer< BasicJsonType >::current, nlohmann::detail::lexer< BasicJsonType >::decimal_point_char, nlohmann::detail::lexer< BasicJsonType >::error_message, nlohmann::detail::lexer< BasicJsonType >::get(), nlohmann::detail::lexer< BasicJsonType >::parse_error, nlohmann::detail::lexer< BasicJsonType >::reset(), nlohmann::detail::lexer< BasicJsonType >::strtof(), nlohmann::detail::lexer< BasicJsonType >::token_buffer, nlohmann::detail::lexer< BasicJsonType >::unget(), nlohmann::detail::lexer< BasicJsonType >::value_float, nlohmann::detail::lexer< BasicJsonType >::value_integer, and nlohmann::detail::lexer< BasicJsonType >::value_unsigned.
scan_string() [1/2]
template<typename BasicJsonType > token_type nlohmann::detail::lexer< BasicJsonType >::scan_string () inline private
scan a string literal
This function scans a string according to Sect. 7 of RFC 7159. While scanning, bytes are escaped and copied into buffer token_buffer. Then the function returns successfully, token_buffer is not null-terminated (as it may contain \0 bytes), and token_buffer.size() is the number of bytes in the string.
Returns
token_type::value_string if string could be successfully scanned, token_type::parse_error otherwise
Note
In case of errors, variable error_message contains a textual description.
Definition at line 235 of file lexer.hpp.
     {
         // reset token_buffer (ignore opening quote)
         reset();
         // we entered the function by reading an open quote
         assert(current == '\"');
         while (true)
         {
             // get next character
             switch (get())
             {
                 // end of file while parsing string
                 case std::char_traits<char>::eof():
                 {
                     error_message = "invalid string: missing closing quote";
                     return token_type::parse_error;
                 }
                 // closing quote
                 case '\"':
                 {
                     return token_type::value_string;
                 }
                 // escapes
                 case '\\':
                 {
                     switch (get())
                     {
                         // quotation mark
                         case '\"':
                             add('\"');
                             break;
                         // reverse solidus
                         case '\\':
                             add('\\');
                             break;
                         // solidus
                         case '/':
                             add('/');
                             break;
                         // backspace
                         case 'b':
                             add('\b');
                             break;
                         // form feed
                         case 'f':
                             add('\f');
                             break;
                         // line feed
                         case 'n':
                             add('\n');
                             break;
                         // carriage return
                         case 'r':
                             add('\r');
                             break;
                         // tab
                         case 't':
                             add('\t');
                             break;
                         // unicode escapes
                         case 'u':
{
                             const int codepoint1 = get_codepoint();
                             int codepoint = codepoint1; // start with codepoint1
                             if (JSON_HEDLEY_UNLIKELY(codepoint1 == -1))
{
                                 error_message = "invalid string: '\\u' must be followed by 4 hex digits";
                                 return token_type::parse_error;
                             }
                             // check if code point is a high surrogate
                             if (0xD800 <= codepoint1 and codepoint1 <= 0xDBFF)
{
                                 // expect next \uxxxx entry
                                 if (JSON_HEDLEY_LIKELY(get() == '\\' and get() == 'u'))
{
                                     const int codepoint2 = get_codepoint();
                                     if (JSON_HEDLEY_UNLIKELY(codepoint2 == -1))
{
                                         error_message = "invalid string: '\\u' must be followed by 4 hex digits";
                                         return token_type::parse_error;
                                     }
                                     // check if codepoint2 is a low surrogate
                                     if (JSON_HEDLEY_LIKELY(0xDC00 <= codepoint2 and codepoint2 <= 0xDFFF))
{
                                         // overwrite codepoint
                                         codepoint = static_cast<int>(
                                                         // high surrogate occupies the most significant 22 bits
                                                         (static_cast<unsigned int>(codepoint1) << 10u)
                                                         // low surrogate occupies the least significant 15 bits
                                                         + static_cast<unsigned int>(codepoint2)
                                                         // there is still the 0xD800, 0xDC00 and 0x10000 noise
                                                         // in the result so we have to subtract with:
                                                         // (0xD800 << 10) + DC00 - 0x10000 = 0x35FDC00
                                                         - 0x35FDC00u);
                                     }
                                     else
{
                                         error_message = "invalid string: surrogate U+DC00..U+DFFF must be followed by U+DC00..U+DFFF";
                                         return token_type::parse_error;
                                     }
                                 }
                                 else
{
                                     error_message = "invalid string: surrogate U+DC00..U+DFFF must be followed by U+DC00..U+DFFF";
                                     return token_type::parse_error;
                                 }
                             }
                             else
{
                                 if (JSON_HEDLEY_UNLIKELY(0xDC00 <= codepoint1 and codepoint1 <= 0xDFFF))
{
                                     error_message = "invalid string: surrogate U+DC00..U+DFFF must follow U+D800..U+DBFF";
                                     return token_type::parse_error;
                                 }
                             }
                             // result of the above calculation yields a proper codepoint
                             assert(0x00 <= codepoint and codepoint <= 0x10FFFF);
                             // translate codepoint into bytes
                             if (codepoint < 0x80)
{
                                 // 1-byte characters: 0xxxxxxx (ASCII)
                                 add(codepoint);
                             }
                             else if (codepoint <= 0x7FF)
{
                                 // 2-byte characters: 110xxxxx 10xxxxxx
                                 add(static_cast<int>(0xC0u | (static_cast<unsigned int>(codepoint) >> 6u)));
                                 add(static_cast<int>(0x80u | (static_cast<unsigned int>(codepoint) & 0x3Fu)));
                             }
                             else if (codepoint <= 0xFFFF)
{
                                 // 3-byte characters: 1110xxxx 10xxxxxx 10xxxxxx
                                 add(static_cast<int>(0xE0u | (static_cast<unsigned int>(codepoint) >> 12u)));
                                 add(static_cast<int>(0x80u | ((static_cast<unsigned int>(codepoint) >> 6u) & 0x3Fu)));
                                 add(static_cast<int>(0x80u | (static_cast<unsigned int>(codepoint) & 0x3Fu)));
                             }
                             else
{
                                 // 4-byte characters: 11110xxx 10xxxxxx 10xxxxxx 10xxxxxx
                                 add(static_cast<int>(0xF0u | (static_cast<unsigned int>(codepoint) >> 18u)));
                                 add(static_cast<int>(0x80u | ((static_cast<unsigned int>(codepoint) >> 12u) & 0x3Fu)));
                                 add(static_cast<int>(0x80u | ((static_cast<unsigned int>(codepoint) >> 6u) & 0x3Fu)));
                                 add(static_cast<int>(0x80u | (static_cast<unsigned int>(codepoint) & 0x3Fu)));
                             }
                             break;
                         }
                         // other characters after escape
                         default:
                             error_message = "invalid string: forbidden character after backslash";
                             return token_type::parse_error;
                     }
                     break;
                 }
                 // invalid control characters
                 case 0x00:
                 {
                     error_message = "invalid string: control character U+0000 (NUL) must be escaped to \\u0000";
                     return token_type::parse_error;
                 }
                 case 0x01:
                 {
                     error_message = "invalid string: control character U+0001 (SOH) must be escaped to \\u0001";
                     return token_type::parse_error;
                 }
                 case 0x02:
                 {
                     error_message = "invalid string: control character U+0002 (STX) must be escaped to \\u0002";
                     return token_type::parse_error;
                 }
                 case 0x03:
                 {
                     error_message = "invalid string: control character U+0003 (ETX) must be escaped to \\u0003";
                     return token_type::parse_error;
                 }
                 case 0x04:
                 {
                     error_message = "invalid string: control character U+0004 (EOT) must be escaped to \\u0004";
                     return token_type::parse_error;
                 }
                 case 0x05:
                 {
                     error_message = "invalid string: control character U+0005 (ENQ) must be escaped to \\u0005";
                     return token_type::parse_error;
                 }
                 case 0x06:
                 {
                     error_message = "invalid string: control character U+0006 (ACK) must be escaped to \\u0006";
                     return token_type::parse_error;
                 }
                 case 0x07:
                 {
                     error_message = "invalid string: control character U+0007 (BEL) must be escaped to \\u0007";
                     return token_type::parse_error;
                 }
                 case 0x08:
                 {
                     error_message = "invalid string: control character U+0008 (BS) must be escaped to \\u0008 or \\b";
                     return token_type::parse_error;
                 }
                 case 0x09:
                 {
                     error_message = "invalid string: control character U+0009 (HT) must be escaped to \\u0009 or \\t";
                     return token_type::parse_error;
                 }
                 case 0x0A:
                 {
                     error_message = "invalid string: control character U+000A (LF) must be escaped to \\u000A or \\n";
                     return token_type::parse_error;
                 }
                 case 0x0B:
                 {
                     error_message = "invalid string: control character U+000B (VT) must be escaped to \\u000B";
                     return token_type::parse_error;
                 }
                 case 0x0C:
                 {
                     error_message = "invalid string: control character U+000C (FF) must be escaped to \\u000C or \\f";
                     return token_type::parse_error;
                 }
                 case 0x0D:
                 {
                     error_message = "invalid string: control character U+000D (CR) must be escaped to \\u000D or \\r";
                     return token_type::parse_error;
                 }
                 case 0x0E:
                 {
                     error_message = "invalid string: control character U+000E (SO) must be escaped to \\u000E";
                     return token_type::parse_error;
                 }
                 case 0x0F:
                 {
                     error_message = "invalid string: control character U+000F (SI) must be escaped to \\u000F";
                     return token_type::parse_error;
                 }
                 case 0x10:
                 {
                     error_message = "invalid string: control character U+0010 (DLE) must be escaped to \\u0010";
                     return token_type::parse_error;
                 }
                 case 0x11:
                 {
                     error_message = "invalid string: control character U+0011 (DC1) must be escaped to \\u0011";
                     return token_type::parse_error;
                 }
                 case 0x12:
                 {
                     error_message = "invalid string: control character U+0012 (DC2) must be escaped to \\u0012";
                     return token_type::parse_error;
                 }
                 case 0x13:
                 {
                     error_message = "invalid string: control character U+0013 (DC3) must be escaped to \\u0013";
                     return token_type::parse_error;
                 }
                 case 0x14:
                 {
                     error_message = "invalid string: control character U+0014 (DC4) must be escaped to \\u0014";
                     return token_type::parse_error;
                 }
                 case 0x15:
                 {
                     error_message = "invalid string: control character U+0015 (NAK) must be escaped to \\u0015";
                     return token_type::parse_error;
                 }
                 case 0x16:
                 {
                     error_message = "invalid string: control character U+0016 (SYN) must be escaped to \\u0016";
                     return token_type::parse_error;
                 }
                 case 0x17:
                 {
                     error_message = "invalid string: control character U+0017 (ETB) must be escaped to \\u0017";
                     return token_type::parse_error;
                 }
                 case 0x18:
                 {
                     error_message = "invalid string: control character U+0018 (CAN) must be escaped to \\u0018";
                     return token_type::parse_error;
                 }
                 case 0x19:
                 {
                     error_message = "invalid string: control character U+0019 (EM) must be escaped to \\u0019";
                     return token_type::parse_error;
                 }
                 case 0x1A:
                 {
                     error_message = "invalid string: control character U+001A (SUB) must be escaped to \\u001A";
                     return token_type::parse_error;
                 }
                 case 0x1B:
                 {
                     error_message = "invalid string: control character U+001B (ESC) must be escaped to \\u001B";
                     return token_type::parse_error;
                 }
                 case 0x1C:
                 {
                     error_message = "invalid string: control character U+001C (FS) must be escaped to \\u001C";
                     return token_type::parse_error;
                 }
                 case 0x1D:
                 {
                     error_message = "invalid string: control character U+001D (GS) must be escaped to \\u001D";
                     return token_type::parse_error;
                 }
                 case 0x1E:
                 {
                     error_message = "invalid string: control character U+001E (RS) must be escaped to \\u001E";
                     return token_type::parse_error;
                 }
                 case 0x1F:
                 {
                     error_message = "invalid string: control character U+001F (US) must be escaped to \\u001F";
                     return token_type::parse_error;
                 }
                 // U+0020..U+007F (except U+0022 (quote) and U+005C (backspace))
                 case 0x20:
                 case 0x21:
                 case 0x23:
                 case 0x24:
                 case 0x25:
                 case 0x26:
                 case 0x27:
                 case 0x28:
                 case 0x29:
                 case 0x2A:
                 case 0x2B:
                 case 0x2C:
                 case 0x2D:
                 case 0x2E:
                 case 0x2F:
                 case 0x30:
                 case 0x31:
                 case 0x32:
                 case 0x33:
                 case 0x34:
                 case 0x35:
                 case 0x36:
                 case 0x37:
                 case 0x38:
                 case 0x39:
                 case 0x3A:
                 case 0x3B:
                 case 0x3C:
                 case 0x3D:
                 case 0x3E:
                 case 0x3F:
                 case 0x40:
                 case 0x41:
                 case 0x42:
                 case 0x43:
                 case 0x44:
                 case 0x45:
                 case 0x46:
                 case 0x47:
                 case 0x48:
                 case 0x49:
                 case 0x4A:
                 case 0x4B:
                 case 0x4C:
                 case 0x4D:
                 case 0x4E:
                 case 0x4F:
                 case 0x50:
                 case 0x51:
                 case 0x52:
                 case 0x53:
                 case 0x54:
                 case 0x55:
                 case 0x56:
                 case 0x57:
                 case 0x58:
                 case 0x59:
                 case 0x5A:
                 case 0x5B:
                 case 0x5D:
                 case 0x5E:
                 case 0x5F:
                 case 0x60:
                 case 0x61:
                 case 0x62:
                 case 0x63:
                 case 0x64:
                 case 0x65:
                 case 0x66:
                 case 0x67:
                 case 0x68:
                 case 0x69:
                 case 0x6A:
                 case 0x6B:
                 case 0x6C:
                 case 0x6D:
                 case 0x6E:
                 case 0x6F:
                 case 0x70:
                 case 0x71:
                 case 0x72:
                 case 0x73:
                 case 0x74:
                 case 0x75:
                 case 0x76:
                 case 0x77:
                 case 0x78:
                 case 0x79:
                 case 0x7A:
                 case 0x7B:
                 case 0x7C:
                 case 0x7D:
                 case 0x7E:
                 case 0x7F:
                 {
                     add(current);
                     break;
                 }
                 // U+0080..U+07FF: bytes C2..DF 80..BF
                 case 0xC2:
                 case 0xC3:
                 case 0xC4:
                 case 0xC5:
                 case 0xC6:
                 case 0xC7:
                 case 0xC8:
                 case 0xC9:
                 case 0xCA:
                 case 0xCB:
                 case 0xCC:
                 case 0xCD:
                 case 0xCE:
                 case 0xCF:
                 case 0xD0:
                 case 0xD1:
                 case 0xD2:
                 case 0xD3:
                 case 0xD4:
                 case 0xD5:
                 case 0xD6:
                 case 0xD7:
                 case 0xD8:
                 case 0xD9:
                 case 0xDA:
                 case 0xDB:
                 case 0xDC:
                 case 0xDD:
                 case 0xDE:
                 case 0xDF:
                 {
                     if (JSON_HEDLEY_UNLIKELY(not next_byte_in_range({0x80, 0xBF})))
                     {
                         return token_type::parse_error;
                     }
                     break;
                 }
                 // U+0800..U+0FFF: bytes E0 A0..BF 80..BF
                 case 0xE0:
                 {
                     if (JSON_HEDLEY_UNLIKELY(not (next_byte_in_range({0xA0, 0xBF, 0x80, 0xBF}))))
                     {
                         return token_type::parse_error;
                     }
                     break;
                 }
                 // U+1000..U+CFFF: bytes E1..EC 80..BF 80..BF
                 // U+E000..U+FFFF: bytes EE..EF 80..BF 80..BF
                 case 0xE1:
                 case 0xE2:
                 case 0xE3:
                 case 0xE4:
                 case 0xE5:
                 case 0xE6:
                 case 0xE7:
                 case 0xE8:
                 case 0xE9:
                 case 0xEA:
                 case 0xEB:
                 case 0xEC:
                 case 0xEE:
                 case 0xEF:
                 {
                     if (JSON_HEDLEY_UNLIKELY(not (next_byte_in_range({0x80, 0xBF, 0x80, 0xBF}))))
                     {
                         return token_type::parse_error;
                     }
                     break;
                 }
                 // U+D000..U+D7FF: bytes ED 80..9F 80..BF
                 case 0xED:
                 {
                     if (JSON_HEDLEY_UNLIKELY(not (next_byte_in_range({0x80, 0x9F, 0x80, 0xBF}))))
                     {
                         return token_type::parse_error;
                     }
                     break;
                 }
                 // U+10000..U+3FFFF F0 90..BF 80..BF 80..BF
                 case 0xF0:
                 {
                     if (JSON_HEDLEY_UNLIKELY(not (next_byte_in_range({0x90, 0xBF, 0x80, 0xBF, 0x80, 0xBF}))))
                     {
                         return token_type::parse_error;
                     }
                     break;
                 }
                 // U+40000..U+FFFFF F1..F3 80..BF 80..BF 80..BF
                 case 0xF1:
                 case 0xF2:
                 case 0xF3:
                 {
                     if (JSON_HEDLEY_UNLIKELY(not (next_byte_in_range({0x80, 0xBF, 0x80, 0xBF, 0x80, 0xBF}))))
                     {
                         return token_type::parse_error;
                     }
                     break;
                 }
                 // U+100000..U+10FFFF F4 80..8F 80..BF 80..BF
                 case 0xF4:
                 {
                     if (JSON_HEDLEY_UNLIKELY(not (next_byte_in_range({0x80, 0x8F, 0x80, 0xBF, 0x80, 0xBF}))))
                     {
                         return token_type::parse_error;
                     }
                     break;
                 }
                 // remaining bytes (80..C1 and F5..FF) are ill-formed
                 default:
                 {
                     error_message = "invalid string: ill-formed UTF-8 byte";
                     return token_type::parse_error;
                 }
             }
         }
     }
References nlohmann::detail::lexer< BasicJsonType >::add(), assert(), nlohmann::detail::lexer< BasicJsonType >::current, nlohmann::detail::lexer< BasicJsonType >::error_message, nlohmann::detail::lexer< BasicJsonType >::get(), nlohmann::detail::lexer< BasicJsonType >::get_codepoint(), JSON_HEDLEY_LIKELY, JSON_HEDLEY_UNLIKELY, nlohmann::detail::lexer< BasicJsonType >::next_byte_in_range(), nlohmann::detail::lexer< BasicJsonType >::parse_error, nlohmann::detail::lexer< BasicJsonType >::reset(), and nlohmann::detail::lexer< BasicJsonType >::value_string.
Referenced by nlohmann::detail::lexer< BasicJsonType >::scan().
scan_string() [2/2]
template<typename BasicJsonType > token_type nlohmann::detail::lexer< BasicJsonType >::scan_string () inline private
scan a string literal
This function scans a string according to Sect. 7 of RFC 7159. While scanning, bytes are escaped and copied into buffer token_buffer. Then the function returns successfully, token_buffer is not null-terminated (as it may contain \0 bytes), and token_buffer.size() is the number of bytes in the string.
Returns
token_type::value_string if string could be successfully scanned, token_type::parse_error otherwise
Note
In case of errors, variable error_message contains a textual description.
Definition at line 7365 of file json.hpp.
     {
         // reset token_buffer (ignore opening quote)
         reset();
         // we entered the function by reading an open quote
         assert(current == '\"');
         while (true)
         {
             // get next character
             switch (get())
             {
                 // end of file while parsing string
                 case std::char_traits<char>::eof():
                 {
                     error_message = "invalid string: missing closing quote";
                     return token_type::parse_error;
                 }
                 // closing quote
                 case '\"':
                 {
                     return token_type::value_string;
                 }
                 // escapes
                 case '\\':
                 {
                     switch (get())
                     {
                         // quotation mark
                         case '\"':
                             add('\"');
                             break;
                         // reverse solidus
                         case '\\':
                             add('\\');
                             break;
                         // solidus
                         case '/':
                             add('/');
                             break;
                         // backspace
                         case 'b':
                             add('\b');
                             break;
                         // form feed
                         case 'f':
                             add('\f');
                             break;
                         // line feed
                         case 'n':
                             add('\n');
                             break;
                         // carriage return
                         case 'r':
                             add('\r');
                             break;
                         // tab
                         case 't':
                             add('\t');
                             break;
                         // unicode escapes
                         case 'u':
{
                             const int codepoint1 = get_codepoint();
                             int codepoint = codepoint1; // start with codepoint1
                             if (JSON_HEDLEY_UNLIKELY(codepoint1 == -1))
{
                                 error_message = "invalid string: '\\u' must be followed by 4 hex digits";
                                 return token_type::parse_error;
                             }
                             // check if code point is a high surrogate
                             if (0xD800 <= codepoint1 and codepoint1 <= 0xDBFF)
{
                                 // expect next \uxxxx entry
                                 if (JSON_HEDLEY_LIKELY(get() == '\\' and get() == 'u'))
{
                                     const int codepoint2 = get_codepoint();
                                     if (JSON_HEDLEY_UNLIKELY(codepoint2 == -1))
{
                                         error_message = "invalid string: '\\u' must be followed by 4 hex digits";
                                         return token_type::parse_error;
                                     }
                                     // check if codepoint2 is a low surrogate
                                     if (JSON_HEDLEY_LIKELY(0xDC00 <= codepoint2 and codepoint2 <= 0xDFFF))
{
                                         // overwrite codepoint
                                         codepoint = static_cast<int>(
                                                         // high surrogate occupies the most significant 22 bits
                                                         (static_cast<unsigned int>(codepoint1) << 10u)
                                                         // low surrogate occupies the least significant 15 bits
                                                         + static_cast<unsigned int>(codepoint2)
                                                         // there is still the 0xD800, 0xDC00 and 0x10000 noise
                                                         // in the result so we have to subtract with:
                                                         // (0xD800 << 10) + DC00 - 0x10000 = 0x35FDC00
                                                         - 0x35FDC00u);
                                     }
                                     else
{
                                         error_message = "invalid string: surrogate U+DC00..U+DFFF must be followed by U+DC00..U+DFFF";
                                         return token_type::parse_error;
                                     }
                                 }
                                 else
{
                                     error_message = "invalid string: surrogate U+DC00..U+DFFF must be followed by U+DC00..U+DFFF";
                                     return token_type::parse_error;
                                 }
                             }
                             else
{
                                 if (JSON_HEDLEY_UNLIKELY(0xDC00 <= codepoint1 and codepoint1 <= 0xDFFF))
{
                                     error_message = "invalid string: surrogate U+DC00..U+DFFF must follow U+D800..U+DBFF";
                                     return token_type::parse_error;
                                 }
                             }
                             // result of the above calculation yields a proper codepoint
                             assert(0x00 <= codepoint and codepoint <= 0x10FFFF);
                             // translate codepoint into bytes
                             if (codepoint < 0x80)
{
                                 // 1-byte characters: 0xxxxxxx (ASCII)
                                 add(codepoint);
                             }
                             else if (codepoint <= 0x7FF)
{
                                 // 2-byte characters: 110xxxxx 10xxxxxx
                                 add(static_cast<int>(0xC0u | (static_cast<unsigned int>(codepoint) >> 6u)));
                                 add(static_cast<int>(0x80u | (static_cast<unsigned int>(codepoint) & 0x3Fu)));
                             }
                             else if (codepoint <= 0xFFFF)
{
                                 // 3-byte characters: 1110xxxx 10xxxxxx 10xxxxxx
                                 add(static_cast<int>(0xE0u | (static_cast<unsigned int>(codepoint) >> 12u)));
                                 add(static_cast<int>(0x80u | ((static_cast<unsigned int>(codepoint) >> 6u) & 0x3Fu)));
                                 add(static_cast<int>(0x80u | (static_cast<unsigned int>(codepoint) & 0x3Fu)));
                             }
                             else
{
                                 // 4-byte characters: 11110xxx 10xxxxxx 10xxxxxx 10xxxxxx
                                 add(static_cast<int>(0xF0u | (static_cast<unsigned int>(codepoint) >> 18u)));
                                 add(static_cast<int>(0x80u | ((static_cast<unsigned int>(codepoint) >> 12u) & 0x3Fu)));
                                 add(static_cast<int>(0x80u | ((static_cast<unsigned int>(codepoint) >> 6u) & 0x3Fu)));
                                 add(static_cast<int>(0x80u | (static_cast<unsigned int>(codepoint) & 0x3Fu)));
                             }
                             break;
                         }
                         // other characters after escape
                         default:
                             error_message = "invalid string: forbidden character after backslash";
                             return token_type::parse_error;
                     }
                     break;
                 }
                 // invalid control characters
                 case 0x00:
                 {
                     error_message = "invalid string: control character U+0000 (NUL) must be escaped to \\u0000";
                     return token_type::parse_error;
                 }
                 case 0x01:
                 {
                     error_message = "invalid string: control character U+0001 (SOH) must be escaped to \\u0001";
                     return token_type::parse_error;
                 }
                 case 0x02:
                 {
                     error_message = "invalid string: control character U+0002 (STX) must be escaped to \\u0002";
                     return token_type::parse_error;
                 }
                 case 0x03:
                 {
                     error_message = "invalid string: control character U+0003 (ETX) must be escaped to \\u0003";
                     return token_type::parse_error;
                 }
                 case 0x04:
                 {
                     error_message = "invalid string: control character U+0004 (EOT) must be escaped to \\u0004";
                     return token_type::parse_error;
                 }
                 case 0x05:
                 {
                     error_message = "invalid string: control character U+0005 (ENQ) must be escaped to \\u0005";
                     return token_type::parse_error;
                 }
                 case 0x06:
                 {
                     error_message = "invalid string: control character U+0006 (ACK) must be escaped to \\u0006";
                     return token_type::parse_error;
                 }
                 case 0x07:
                 {
                     error_message = "invalid string: control character U+0007 (BEL) must be escaped to \\u0007";
                     return token_type::parse_error;
                 }
                 case 0x08:
                 {
                     error_message = "invalid string: control character U+0008 (BS) must be escaped to \\u0008 or \\b";
                     return token_type::parse_error;
                 }
                 case 0x09:
                 {
                     error_message = "invalid string: control character U+0009 (HT) must be escaped to \\u0009 or \\t";
                     return token_type::parse_error;
                 }
                 case 0x0A:
                 {
                     error_message = "invalid string: control character U+000A (LF) must be escaped to \\u000A or \\n";
                     return token_type::parse_error;
                 }
                 case 0x0B:
                 {
                     error_message = "invalid string: control character U+000B (VT) must be escaped to \\u000B";
                     return token_type::parse_error;
                 }
                 case 0x0C:
                 {
                     error_message = "invalid string: control character U+000C (FF) must be escaped to \\u000C or \\f";
                     return token_type::parse_error;
                 }
                 case 0x0D:
                 {
                     error_message = "invalid string: control character U+000D (CR) must be escaped to \\u000D or \\r";
                     return token_type::parse_error;
                 }
                 case 0x0E:
                 {
                     error_message = "invalid string: control character U+000E (SO) must be escaped to \\u000E";
                     return token_type::parse_error;
                 }
                 case 0x0F:
                 {
                     error_message = "invalid string: control character U+000F (SI) must be escaped to \\u000F";
                     return token_type::parse_error;
                 }
                 case 0x10:
                 {
                     error_message = "invalid string: control character U+0010 (DLE) must be escaped to \\u0010";
                     return token_type::parse_error;
                 }
                 case 0x11:
                 {
                     error_message = "invalid string: control character U+0011 (DC1) must be escaped to \\u0011";
                     return token_type::parse_error;
                 }
                 case 0x12:
                 {
                     error_message = "invalid string: control character U+0012 (DC2) must be escaped to \\u0012";
                     return token_type::parse_error;
                 }
                 case 0x13:
                 {
                     error_message = "invalid string: control character U+0013 (DC3) must be escaped to \\u0013";
                     return token_type::parse_error;
                 }
                 case 0x14:
                 {
                     error_message = "invalid string: control character U+0014 (DC4) must be escaped to \\u0014";
                     return token_type::parse_error;
                 }
                 case 0x15:
                 {
                     error_message = "invalid string: control character U+0015 (NAK) must be escaped to \\u0015";
                     return token_type::parse_error;
                 }
                 case 0x16:
                 {
                     error_message = "invalid string: control character U+0016 (SYN) must be escaped to \\u0016";
                     return token_type::parse_error;
                 }
                 case 0x17:
                 {
                     error_message = "invalid string: control character U+0017 (ETB) must be escaped to \\u0017";
                     return token_type::parse_error;
                 }
                 case 0x18:
                 {
                     error_message = "invalid string: control character U+0018 (CAN) must be escaped to \\u0018";
                     return token_type::parse_error;
                 }
                 case 0x19:
                 {
                     error_message = "invalid string: control character U+0019 (EM) must be escaped to \\u0019";
                     return token_type::parse_error;
                 }
                 case 0x1A:
                 {
                     error_message = "invalid string: control character U+001A (SUB) must be escaped to \\u001A";
                     return token_type::parse_error;
                 }
                 case 0x1B:
                 {
                     error_message = "invalid string: control character U+001B (ESC) must be escaped to \\u001B";
                     return token_type::parse_error;
                 }
                 case 0x1C:
                 {
                     error_message = "invalid string: control character U+001C (FS) must be escaped to \\u001C";
                     return token_type::parse_error;
                 }
                 case 0x1D:
                 {
                     error_message = "invalid string: control character U+001D (GS) must be escaped to \\u001D";
                     return token_type::parse_error;
                 }
                 case 0x1E:
                 {
                     error_message = "invalid string: control character U+001E (RS) must be escaped to \\u001E";
                     return token_type::parse_error;
                 }
                 case 0x1F:
                 {
                     error_message = "invalid string: control character U+001F (US) must be escaped to \\u001F";
                     return token_type::parse_error;
                 }
                 // U+0020..U+007F (except U+0022 (quote) and U+005C (backspace))
                 case 0x20:
                 case 0x21:
                 case 0x23:
                 case 0x24:
                 case 0x25:
                 case 0x26:
                 case 0x27:
                 case 0x28:
                 case 0x29:
                 case 0x2A:
                 case 0x2B:
                 case 0x2C:
                 case 0x2D:
                 case 0x2E:
                 case 0x2F:
                 case 0x30:
                 case 0x31:
                 case 0x32:
                 case 0x33:
                 case 0x34:
                 case 0x35:
                 case 0x36:
                 case 0x37:
                 case 0x38:
                 case 0x39:
                 case 0x3A:
                 case 0x3B:
                 case 0x3C:
                 case 0x3D:
                 case 0x3E:
                 case 0x3F:
                 case 0x40:
                 case 0x41:
                 case 0x42:
                 case 0x43:
                 case 0x44:
                 case 0x45:
                 case 0x46:
                 case 0x47:
                 case 0x48:
                 case 0x49:
                 case 0x4A:
                 case 0x4B:
                 case 0x4C:
                 case 0x4D:
                 case 0x4E:
                 case 0x4F:
                 case 0x50:
                 case 0x51:
                 case 0x52:
                 case 0x53:
                 case 0x54:
                 case 0x55:
                 case 0x56:
                 case 0x57:
                 case 0x58:
                 case 0x59:
                 case 0x5A:
                 case 0x5B:
                 case 0x5D:
                 case 0x5E:
                 case 0x5F:
                 case 0x60:
                 case 0x61:
                 case 0x62:
                 case 0x63:
                 case 0x64:
                 case 0x65:
                 case 0x66:
                 case 0x67:
                 case 0x68:
                 case 0x69:
                 case 0x6A:
                 case 0x6B:
                 case 0x6C:
                 case 0x6D:
                 case 0x6E:
                 case 0x6F:
                 case 0x70:
                 case 0x71:
                 case 0x72:
                 case 0x73:
                 case 0x74:
                 case 0x75:
                 case 0x76:
                 case 0x77:
                 case 0x78:
                 case 0x79:
                 case 0x7A:
                 case 0x7B:
                 case 0x7C:
                 case 0x7D:
                 case 0x7E:
                 case 0x7F:
                 {
                     add(current);
                     break;
                 }
                 // U+0080..U+07FF: bytes C2..DF 80..BF
                 case 0xC2:
                 case 0xC3:
                 case 0xC4:
                 case 0xC5:
                 case 0xC6:
                 case 0xC7:
                 case 0xC8:
                 case 0xC9:
                 case 0xCA:
                 case 0xCB:
                 case 0xCC:
                 case 0xCD:
                 case 0xCE:
                 case 0xCF:
                 case 0xD0:
                 case 0xD1:
                 case 0xD2:
                 case 0xD3:
                 case 0xD4:
                 case 0xD5:
                 case 0xD6:
                 case 0xD7:
                 case 0xD8:
                 case 0xD9:
                 case 0xDA:
                 case 0xDB:
                 case 0xDC:
                 case 0xDD:
                 case 0xDE:
                 case 0xDF:
                 {
                     if (JSON_HEDLEY_UNLIKELY(not next_byte_in_range({0x80, 0xBF})))
                     {
                         return token_type::parse_error;
                     }
                     break;
                 }
                 // U+0800..U+0FFF: bytes E0 A0..BF 80..BF
                 case 0xE0:
                 {
                     if (JSON_HEDLEY_UNLIKELY(not (next_byte_in_range({0xA0, 0xBF, 0x80, 0xBF}))))
                     {
                         return token_type::parse_error;
                     }
                     break;
                 }
                 // U+1000..U+CFFF: bytes E1..EC 80..BF 80..BF
                 // U+E000..U+FFFF: bytes EE..EF 80..BF 80..BF
                 case 0xE1:
                 case 0xE2:
                 case 0xE3:
                 case 0xE4:
                 case 0xE5:
                 case 0xE6:
                 case 0xE7:
                 case 0xE8:
                 case 0xE9:
                 case 0xEA:
                 case 0xEB:
                 case 0xEC:
                 case 0xEE:
                 case 0xEF:
                 {
                     if (JSON_HEDLEY_UNLIKELY(not (next_byte_in_range({0x80, 0xBF, 0x80, 0xBF}))))
                     {
                         return token_type::parse_error;
                     }
                     break;
                 }
                 // U+D000..U+D7FF: bytes ED 80..9F 80..BF
                 case 0xED:
                 {
                     if (JSON_HEDLEY_UNLIKELY(not (next_byte_in_range({0x80, 0x9F, 0x80, 0xBF}))))
                     {
                         return token_type::parse_error;
                     }
                     break;
                 }
                 // U+10000..U+3FFFF F0 90..BF 80..BF 80..BF
                 case 0xF0:
                 {
                     if (JSON_HEDLEY_UNLIKELY(not (next_byte_in_range({0x90, 0xBF, 0x80, 0xBF, 0x80, 0xBF}))))
                     {
                         return token_type::parse_error;
                     }
                     break;
                 }
                 // U+40000..U+FFFFF F1..F3 80..BF 80..BF 80..BF
                 case 0xF1:
                 case 0xF2:
                 case 0xF3:
                 {
                     if (JSON_HEDLEY_UNLIKELY(not (next_byte_in_range({0x80, 0xBF, 0x80, 0xBF, 0x80, 0xBF}))))
                     {
                         return token_type::parse_error;
                     }
                     break;
                 }
                 // U+100000..U+10FFFF F4 80..8F 80..BF 80..BF
                 case 0xF4:
                 {
                     if (JSON_HEDLEY_UNLIKELY(not (next_byte_in_range({0x80, 0x8F, 0x80, 0xBF, 0x80, 0xBF}))))
                     {
                         return token_type::parse_error;
                     }
                     break;
                 }
                 // remaining bytes (80..C1 and F5..FF) are ill-formed
                 default:
                 {
                     error_message = "invalid string: ill-formed UTF-8 byte";
                     return token_type::parse_error;
                 }
             }
         }
     }
References nlohmann::detail::lexer< BasicJsonType >::add(), assert(), nlohmann::detail::lexer< BasicJsonType >::current, nlohmann::detail::lexer< BasicJsonType >::error_message, nlohmann::detail::lexer< BasicJsonType >::get(), nlohmann::detail::lexer< BasicJsonType >::get_codepoint(), JSON_HEDLEY_LIKELY, JSON_HEDLEY_UNLIKELY, nlohmann::detail::lexer< BasicJsonType >::next_byte_in_range(), nlohmann::detail::lexer< BasicJsonType >::parse_error, nlohmann::detail::lexer< BasicJsonType >::reset(), and nlohmann::detail::lexer< BasicJsonType >::value_string.
skip_bom() [1/2]
template<typename BasicJsonType > bool nlohmann::detail::lexer< BasicJsonType >::skip_bom () inline
skip the UTF-8 byte order mark
Returns
true iff there is no BOM or the correct BOM has been skipped
Definition at line 1396 of file lexer.hpp.
     {
         if (get() == 0xEF)
         {
             // check if we completely parse the BOM
             return get() == 0xBB and get() == 0xBF;
         }
         // the first character is not the beginning of the BOM; unget it to
         // process is later
         unget();
         return true;
     }
References nlohmann::detail::lexer< BasicJsonType >::get(), and nlohmann::detail::lexer< BasicJsonType >::unget().
Referenced by nlohmann::detail::lexer< BasicJsonType >::scan().
skip_bom() [2/2]
template<typename BasicJsonType > bool nlohmann::detail::lexer< BasicJsonType >::skip_bom () inline
skip the UTF-8 byte order mark
Returns
true iff there is no BOM or the correct BOM has been skipped
Definition at line 8526 of file json.hpp.
     {
         if (get() == 0xEF)
         {
             // check if we completely parse the BOM
             return get() == 0xBB and get() == 0xBF;
         }
         // the first character is not the beginning of the BOM; unget it to
         // process is later
         unget();
         return true;
     }
References nlohmann::detail::lexer< BasicJsonType >::get(), and nlohmann::detail::lexer< BasicJsonType >::unget().
strtof() [1/6]
template<typename BasicJsonType > static void nlohmann::detail::lexer< BasicJsonType >::strtof (double & f, const char * str, char ** endptr) inline static private noexcept
Definition at line 828 of file lexer.hpp.
     {
         f = std::strtod(str, endptr);
     }
strtof() [2/6]
template<typename BasicJsonType > static void nlohmann::detail::lexer< BasicJsonType >::strtof (double & f, const char * str, char ** endptr) inline static private noexcept
Definition at line 7958 of file json.hpp.
     {
         f = std::strtod(str, endptr);
     }
strtof() [3/6]
template<typename BasicJsonType > static void nlohmann::detail::lexer< BasicJsonType >::strtof (float & f, const char * str, char ** endptr) inline static private noexcept
Definition at line 822 of file lexer.hpp.
     {
         f = std::strtof(str, endptr);
     }
Referenced by nlohmann::detail::lexer< BasicJsonType >::scan_number().
strtof() [4/6]
template<typename BasicJsonType > static void nlohmann::detail::lexer< BasicJsonType >::strtof (float & f, const char * str, char ** endptr) inline static private noexcept
Definition at line 7952 of file json.hpp.
     {
         f = std::strtof(str, endptr);
     }
strtof() [5/6]
template<typename BasicJsonType > static void nlohmann::detail::lexer< BasicJsonType >::strtof (long double & f, const char * str, char ** endptr) inline static private noexcept
Definition at line 834 of file lexer.hpp.
     {
         f = std::strtold(str, endptr);
     }
strtof() [6/6]
template<typename BasicJsonType > static void nlohmann::detail::lexer< BasicJsonType >::strtof (long double & f, const char * str, char ** endptr) inline static private noexcept
Definition at line 7964 of file json.hpp.
     {
         f = std::strtold(str, endptr);
     }
token_type_name() [1/2]
template<typename BasicJsonType > JSON_HEDLEY_RETURNS_NON_NULL static const JSON_HEDLEY_CONST char* nlohmann::detail::lexer< BasicJsonType >::token_type_name (const token_type t) inline static noexcept
return name of values of type token_type (only used for errors)
Definition at line 64 of file lexer.hpp.
     {
         switch (t)
         {
             case token_type::uninitialized:
                 return "<uninitialized>";
             case token_type::literal_true:
                 return "true literal";
             case token_type::literal_false:
                 return "false literal";
             case token_type::literal_null:
                 return "null literal";
             case token_type::value_string:
                 return "string literal";
             case lexer::token_type::value_unsigned:
             case lexer::token_type::value_integer:
             case lexer::token_type::value_float:
                 return "number literal";
             case token_type::begin_array:
                 return "'['";
             case token_type::begin_object:
                 return "'{'";
             case token_type::end_array:
                 return "']'";
             case token_type::end_object:
                 return "'}'";
             case token_type::name_separator:
                 return "':'";
             case token_type::value_separator:
                 return "','";
             case token_type::parse_error:
                 return "<parse error>";
             case token_type::end_of_input:
                 return "end of input";
             case token_type::literal_or_value:
                 return "'[', '{', or a literal";
             // LCOV_EXCL_START
             default: // catch non-enum values
                 return "unknown token";
                 // LCOV_EXCL_STOP
         }
     }
References nlohmann::detail::lexer< BasicJsonType >::begin_array, nlohmann::detail::lexer< BasicJsonType >::begin_object, nlohmann::detail::lexer< BasicJsonType >::end_array, nlohmann::detail::lexer< BasicJsonType >::end_object, nlohmann::detail::lexer< BasicJsonType >::end_of_input, nlohmann::detail::lexer< BasicJsonType >::literal_false, nlohmann::detail::lexer< BasicJsonType >::literal_null, nlohmann::detail::lexer< BasicJsonType >::literal_or_value, nlohmann::detail::lexer< BasicJsonType >::literal_true, nlohmann::detail::lexer< BasicJsonType >::name_separator, nlohmann::detail::lexer< BasicJsonType >::parse_error, t, nlohmann::detail::lexer< BasicJsonType >::uninitialized, nlohmann::detail::lexer< BasicJsonType >::value_float, nlohmann::detail::lexer< BasicJsonType >::value_integer, nlohmann::detail::lexer< BasicJsonType >::value_separator, nlohmann::detail::lexer< BasicJsonType >::value_string, and nlohmann::detail::lexer< BasicJsonType >::value_unsigned.
Referenced by nlohmann::detail::parser< BasicJsonType >::exception_message(), and TEST_CASE().
token_type_name() [2/2]
template<typename BasicJsonType > static const char* nlohmann::detail::lexer< BasicJsonType >::token_type_name (const token_type t) inline static noexcept
return name of values of type token_type (only used for errors)
Definition at line 7194 of file json.hpp.
     {
         switch (t)
         {
             case token_type::uninitialized:
                 return "<uninitialized>";
             case token_type::literal_true:
                 return "true literal";
             case token_type::literal_false:
                 return "false literal";
             case token_type::literal_null:
                 return "null literal";
             case token_type::value_string:
                 return "string literal";
             case lexer::token_type::value_unsigned:
             case lexer::token_type::value_integer:
             case lexer::token_type::value_float:
                 return "number literal";
             case token_type::begin_array:
                 return "'['";
             case token_type::begin_object:
                 return "'{'";
             case token_type::end_array:
                 return "']'";
             case token_type::end_object:
                 return "'}'";
             case token_type::name_separator:
                 return "':'";
             case token_type::value_separator:
                 return "','";
             case token_type::parse_error:
                 return "<parse error>";
             case token_type::end_of_input:
                 return "end of input";
             case token_type::literal_or_value:
                 return "'[', '{', or a literal";
             // LCOV_EXCL_START
             default: // catch non-enum values
                 return "unknown token";
                 // LCOV_EXCL_STOP
         }
     }
References nlohmann::detail::lexer< BasicJsonType >::begin_array, nlohmann::detail::lexer< BasicJsonType >::begin_object, nlohmann::detail::lexer< BasicJsonType >::end_array, nlohmann::detail::lexer< BasicJsonType >::end_object, nlohmann::detail::lexer< BasicJsonType >::end_of_input, nlohmann::detail::lexer< BasicJsonType >::literal_false, nlohmann::detail::lexer< BasicJsonType >::literal_null, nlohmann::detail::lexer< BasicJsonType >::literal_or_value, nlohmann::detail::lexer< BasicJsonType >::literal_true, nlohmann::detail::lexer< BasicJsonType >::name_separator, nlohmann::detail::lexer< BasicJsonType >::parse_error, t, nlohmann::detail::lexer< BasicJsonType >::uninitialized, nlohmann::detail::lexer< BasicJsonType >::value_float, nlohmann::detail::lexer< BasicJsonType >::value_integer, nlohmann::detail::lexer< BasicJsonType >::value_separator, nlohmann::detail::lexer< BasicJsonType >::value_string, and nlohmann::detail::lexer< BasicJsonType >::value_unsigned.
unget() [1/2]
template<typename BasicJsonType > void nlohmann::detail::lexer< BasicJsonType >::unget () inline private
unget current character (read it again on next get)
We implement unget by setting variable next_unget to true. The input is not changed - we just simulate ungetting by modifying chars_read_total, chars_read_current_line, and token_string. The next call to get() will behave as if the unget character is read again.
Definition at line 1284 of file lexer.hpp.
     {
         next_unget = true;
         --position.chars_read_total;
         // in case we "unget" a newline, we have to also decrement the lines_read
         if (position.chars_read_current_line == 0)
         {
             if (position.lines_read > 0)
             {
                 --position.lines_read;
             }
         }
         else
         {
             --position.chars_read_current_line;
         }
         if (JSON_HEDLEY_LIKELY(current != std::char_traits<char>::eof()))
         {
             assert(not token_string.empty());
             token_string.pop_back();
         }
     }
References assert(), nlohmann::detail::position_t::chars_read_current_line, nlohmann::detail::position_t::chars_read_total, nlohmann::detail::lexer< BasicJsonType >::current, JSON_HEDLEY_LIKELY, nlohmann::detail::position_t::lines_read, nlohmann::detail::lexer< BasicJsonType >::next_unget, nlohmann::detail::lexer< BasicJsonType >::position, and nlohmann::detail::lexer< BasicJsonType >::token_string.
Referenced by nlohmann::detail::lexer< BasicJsonType >::scan_number(), and nlohmann::detail::lexer< BasicJsonType >::skip_bom().
unget() [2/2]
template<typename BasicJsonType > void nlohmann::detail::lexer< BasicJsonType >::unget () inline private
unget current character (read it again on next get)
We implement unget by setting variable next_unget to true. The input is not changed - we just simulate ungetting by modifying chars_read_total, chars_read_current_line, and token_string. The next call to get() will behave as if the unget character is read again.
Definition at line 8414 of file json.hpp.
     {
         next_unget = true;
         --position.chars_read_total;
         // in case we "unget" a newline, we have to also decrement the lines_read
         if (position.chars_read_current_line == 0)
         {
             if (position.lines_read > 0)
             {
                 --position.lines_read;
             }
         }
         else
         {
             --position.chars_read_current_line;
         }
         if (JSON_HEDLEY_LIKELY(current != std::char_traits<char>::eof()))
         {
             assert(not token_string.empty());
             token_string.pop_back();
         }
     }
References assert(), nlohmann::detail::position_t::chars_read_current_line, nlohmann::detail::position_t::chars_read_total, nlohmann::detail::lexer< BasicJsonType >::current, JSON_HEDLEY_LIKELY, nlohmann::detail::position_t::lines_read, nlohmann::detail::lexer< BasicJsonType >::next_unget, nlohmann::detail::lexer< BasicJsonType >::position, and nlohmann::detail::lexer< BasicJsonType >::token_string.
Member Data Documentation
current
template<typename BasicJsonType > std::char_traits< char >::int_type nlohmann::detail::lexer< BasicJsonType >::current = std::char_traits<char>::eof() private
the current character
Definition at line 1486 of file lexer.hpp.
Referenced by nlohmann::detail::lexer< BasicJsonType >::get(), nlohmann::detail::lexer< BasicJsonType >::get_codepoint(), nlohmann::detail::lexer< BasicJsonType >::next_byte_in_range(), nlohmann::detail::lexer< BasicJsonType >::reset(), nlohmann::detail::lexer< BasicJsonType >::scan(), nlohmann::detail::lexer< BasicJsonType >::scan_literal(), nlohmann::detail::lexer< BasicJsonType >::scan_number(), nlohmann::detail::lexer< BasicJsonType >::scan_string(), and nlohmann::detail::lexer< BasicJsonType >::unget().
decimal_point_char
template<typename BasicJsonType > const char nlohmann::detail::lexer< BasicJsonType >::decimal_point_char = '.' private
the decimal point
Definition at line 1509 of file lexer.hpp.
Referenced by nlohmann::detail::lexer< BasicJsonType >::scan_number().
error_message
template<typename BasicJsonType > const char * nlohmann::detail::lexer< BasicJsonType >::error_message = "" private
a description of occurred lexer errors
Definition at line 1501 of file lexer.hpp.
Referenced by nlohmann::detail::lexer< BasicJsonType >::get_error_message(), nlohmann::detail::lexer< BasicJsonType >::next_byte_in_range(), nlohmann::detail::lexer< BasicJsonType >::scan(), nlohmann::detail::lexer< BasicJsonType >::scan_literal(), nlohmann::detail::lexer< BasicJsonType >::scan_number(), and nlohmann::detail::lexer< BasicJsonType >::scan_string().
ia
template<typename BasicJsonType > detail::input_adapter_t nlohmann::detail::lexer< BasicJsonType >::ia = nullptr private
input adapter
Definition at line 1483 of file lexer.hpp.
Referenced by nlohmann::detail::lexer< BasicJsonType >::get().
next_unget
template<typename BasicJsonType > bool nlohmann::detail::lexer< BasicJsonType >::next_unget = false private
whether the next get() call should just return current
Definition at line 1489 of file lexer.hpp.
Referenced by nlohmann::detail::lexer< BasicJsonType >::get(), and nlohmann::detail::lexer< BasicJsonType >::unget().
position
template<typename BasicJsonType > position_t nlohmann::detail::lexer< BasicJsonType >::position {} private
the start position of the current token
Definition at line 1492 of file lexer.hpp.
Referenced by nlohmann::detail::lexer< BasicJsonType >::get(), nlohmann::detail::lexer< BasicJsonType >::get_position(), nlohmann::detail::lexer< BasicJsonType >::scan(), and nlohmann::detail::lexer< BasicJsonType >::unget().
token_buffer
template<typename BasicJsonType > string_t nlohmann::detail::lexer< BasicJsonType >::token_buffer {} private
buffer for variable-length tokens (numbers, strings)
Definition at line 1498 of file lexer.hpp.
Referenced by nlohmann::detail::lexer< BasicJsonType >::add(), nlohmann::detail::lexer< BasicJsonType >::get_string(), nlohmann::detail::lexer< BasicJsonType >::reset(), and nlohmann::detail::lexer< BasicJsonType >::scan_number().
token_string
template<typename BasicJsonType > std::vector< char > nlohmann::detail::lexer< BasicJsonType >::token_string {} private
raw input token string (for error messages)
Definition at line 1495 of file lexer.hpp.
Referenced by nlohmann::detail::lexer< BasicJsonType >::get(), nlohmann::detail::lexer< BasicJsonType >::get_token_string(), nlohmann::detail::lexer< BasicJsonType >::reset(), and nlohmann::detail::lexer< BasicJsonType >::unget().
value_float
template<typename BasicJsonType > number_float_t nlohmann::detail::lexer< BasicJsonType >::value_float = 0 private
Definition at line 1506 of file lexer.hpp.
Referenced by nlohmann::detail::lexer< BasicJsonType >::get_number_float(), and nlohmann::detail::lexer< BasicJsonType >::scan_number().
value_integer
template<typename BasicJsonType > number_integer_t nlohmann::detail::lexer< BasicJsonType >::value_integer = 0 private
Definition at line 1504 of file lexer.hpp.
Referenced by nlohmann::detail::lexer< BasicJsonType >::get_number_integer(), and nlohmann::detail::lexer< BasicJsonType >::scan_number().
value_unsigned
template<typename BasicJsonType > number_unsigned_t nlohmann::detail::lexer< BasicJsonType >::value_unsigned = 0 private
Definition at line 1505 of file lexer.hpp.
Referenced by nlohmann::detail::lexer< BasicJsonType >::get_number_unsigned(), and nlohmann::detail::lexer< BasicJsonType >::scan_number().
The documentation for this class was generated from the following files:
mc_orchestrator/json-3.7.3/include/nlohmann/detail/input/lexer.hpp
mc_orchestrator/json-3.7.3/single_include/nlohmann/json.hpp