Mixed Criticality Orchestrator: benchmark::internal::Benchmark Class Reference
benchmark::internal::Benchmark Class Reference abstract
#include <benchmark.h>
Classes
struct Instance
Public Member Functions
virtual ~Benchmark ()
Benchmark * Arg (int64_t x)
Benchmark * Unit (TimeUnit unit)
Benchmark * Range (int64_t start, int64_t limit)
Benchmark * DenseRange (int64_t start, int64_t limit, int step=1)
Benchmark * Args (const std::vector< int64_t > &args)
Benchmark * ArgPair (int64_t x, int64_t y)
Benchmark * Ranges (const std::vector< std::pair< int64_t, int64_t > > &ranges)
Benchmark * ArgName (const std::string &name)
Benchmark * ArgNames (const std::vector< std::string > &names)
Benchmark * RangePair (int64_t lo1, int64_t hi1, int64_t lo2, int64_t hi2)
Benchmark * Apply (void(*func)(Benchmark *benchmark))
Benchmark * RangeMultiplier (int multiplier)
Benchmark * MinTime (double t)
Benchmark * Iterations (size_t n)
Benchmark * Repetitions (int n)
Benchmark * ReportAggregatesOnly (bool value=true)
Benchmark * UseRealTime ()
Benchmark * UseManualTime ()
Benchmark * Complexity (BigO complexity=benchmark::oAuto)
Benchmark * Complexity (BigOFunc *complexity)
Benchmark * ComputeStatistics (std::string name, StatisticsFunc *statistics)
Benchmark * Threads (int t)
Benchmark * ThreadRange (int min_threads, int max_threads)
Benchmark * DenseThreadRange (int min_threads, int max_threads, int stride=1)
Benchmark * ThreadPerCpu ()
virtual void Run (State &state)=0
Protected Member Functions
Benchmark (const char *name)
Benchmark (Benchmark const &)
void SetName (const char *name)
int ArgsCnt () const
Private Member Functions
Benchmark & operator= (Benchmark const &)
Private Attributes
std::string name_
ReportMode report_mode_
std::vector< std::string > arg_names_
std::vector< std::vector< int64_t > > args_
TimeUnit time_unit_
int range_multiplier_
double min_time_
size_t iterations_
int repetitions_
bool use_real_time_
bool use_manual_time_
BigO complexity_
BigOFunc * complexity_lambda_
std::vector< Statistics > statistics_
std::vector< int > thread_counts_
Friends
class BenchmarkFamilies
Detailed Description
Definition at line 732 of file benchmark.h.
Constructor & Destructor Documentation
~Benchmark()
virtual benchmark::internal::Benchmark::~Benchmark () virtual
Benchmark() [1/2]
benchmark::internal::Benchmark::Benchmark (const char * name) explicit protected
Benchmark() [2/2]
benchmark::internal::Benchmark::Benchmark (Benchmark const &) protected
Member Function Documentation
Apply()
Benchmark* benchmark::internal::Benchmark::Apply (void(*)(Benchmark *benchmark) func)
Arg()
Benchmark* benchmark::internal::Benchmark::Arg (int64_t x)
ArgName()
Benchmark* benchmark::internal::Benchmark::ArgName (const std::string & name)
ArgNames()
Benchmark* benchmark::internal::Benchmark::ArgNames (const std::vector< std::string > & names)
ArgPair()
Benchmark* benchmark::internal::Benchmark::ArgPair (int64_t x, int64_t y) inline
Definition at line 765 of file benchmark.h.
{
     std::vector<int64_t> args;
     args.push_back(x);
     args.push_back(y);
     return Args(args);
   }
References Args().
Args()
Benchmark* benchmark::internal::Benchmark::Args (const std::vector< int64_t > & args)
Referenced by ArgPair().
ArgsCnt()
int benchmark::internal::Benchmark::ArgsCnt () const protected
Complexity() [1/2]
Benchmark* benchmark::internal::Benchmark::Complexity (BigO complexity = benchmark::oAuto)
Complexity() [2/2]
Benchmark* benchmark::internal::Benchmark::Complexity (BigOFunc * complexity)
ComputeStatistics()
Benchmark* benchmark::internal::Benchmark::ComputeStatistics (std::string name, StatisticsFunc * statistics)
DenseRange()
Benchmark* benchmark::internal::Benchmark::DenseRange (int64_t start, int64_t limit, int step = 1)
DenseThreadRange()
Benchmark* benchmark::internal::Benchmark::DenseThreadRange (int min_threads, int max_threads, int stride = 1)
Iterations()
Benchmark* benchmark::internal::Benchmark::Iterations (size_t n)
MinTime()
Benchmark* benchmark::internal::Benchmark::MinTime (double t)
operator=()
Benchmark& benchmark::internal::Benchmark::operator= (Benchmark const &) private
Range()
Benchmark* benchmark::internal::Benchmark::Range (int64_t start, int64_t limit)
RangeMultiplier()
Benchmark* benchmark::internal::Benchmark::RangeMultiplier (int multiplier)
RangePair()
Benchmark* benchmark::internal::Benchmark::RangePair (int64_t lo1, int64_t hi1, int64_t lo2, int64_t hi2) inline
Definition at line 787 of file benchmark.h.
{
     std::vector<std::pair<int64_t, int64_t> > ranges;
     ranges.push_back(std::make_pair(lo1, hi1));
     ranges.push_back(std::make_pair(lo2, hi2));
     return Ranges(ranges);
   }
References Ranges().
Ranges()
Benchmark* benchmark::internal::Benchmark::Ranges (const std::vector< std::pair< int64_t, int64_t > > & ranges)
Referenced by RangePair().
Repetitions()
Benchmark* benchmark::internal::Benchmark::Repetitions (int n)
ReportAggregatesOnly()
Benchmark* benchmark::internal::Benchmark::ReportAggregatesOnly (bool value = true)
Run()
virtual void benchmark::internal::Benchmark::Run (State & state) pure virtual
Implemented in benchmark::Fixture, and benchmark::internal::FunctionBenchmark.
SetName()
void benchmark::internal::Benchmark::SetName (const char * name) protected
ThreadPerCpu()
Benchmark* benchmark::internal::Benchmark::ThreadPerCpu ()
ThreadRange()
Benchmark* benchmark::internal::Benchmark::ThreadRange (int min_threads, int max_threads)
Threads()
Benchmark* benchmark::internal::Benchmark::Threads (int t)
Unit()
Benchmark* benchmark::internal::Benchmark::Unit (TimeUnit unit)
UseManualTime()
Benchmark* benchmark::internal::Benchmark::UseManualTime ()
UseRealTime()
Benchmark* benchmark::internal::Benchmark::UseRealTime ()
Friends And Related Function Documentation
BenchmarkFamilies
friend class BenchmarkFamilies friend
Definition at line 896 of file benchmark.h.
Member Data Documentation
arg_names_
std::vector<std::string> benchmark::internal::Benchmark::arg_names_ private
Definition at line 900 of file benchmark.h.
args_
std::vector<std::vector<int64_t> > benchmark::internal::Benchmark::args_ private
Definition at line 901 of file benchmark.h.
complexity_
BigO benchmark::internal::Benchmark::complexity_ private
Definition at line 909 of file benchmark.h.
complexity_lambda_
BigOFunc* benchmark::internal::Benchmark::complexity_lambda_ private
Definition at line 910 of file benchmark.h.
iterations_
size_t benchmark::internal::Benchmark::iterations_ private
Definition at line 905 of file benchmark.h.
min_time_
double benchmark::internal::Benchmark::min_time_ private
Definition at line 904 of file benchmark.h.
name_
std::string benchmark::internal::Benchmark::name_ private
Definition at line 898 of file benchmark.h.
range_multiplier_
int benchmark::internal::Benchmark::range_multiplier_ private
Definition at line 903 of file benchmark.h.
repetitions_
int benchmark::internal::Benchmark::repetitions_ private
Definition at line 906 of file benchmark.h.
report_mode_
ReportMode benchmark::internal::Benchmark::report_mode_ private
Definition at line 899 of file benchmark.h.
statistics_
std::vector<Statistics> benchmark::internal::Benchmark::statistics_ private
Definition at line 911 of file benchmark.h.
thread_counts_
std::vector<int> benchmark::internal::Benchmark::thread_counts_ private
Definition at line 912 of file benchmark.h.
time_unit_
TimeUnit benchmark::internal::Benchmark::time_unit_ private
Definition at line 902 of file benchmark.h.
use_manual_time_
bool benchmark::internal::Benchmark::use_manual_time_ private
Definition at line 908 of file benchmark.h.
use_real_time_
bool benchmark::internal::Benchmark::use_real_time_ private
Definition at line 907 of file benchmark.h.
The documentation for this class was generated from the following file:
mc_orchestrator/json-3.7.3/benchmarks/thirdparty/benchmark/include/benchmark/benchmark.h