Mixed Criticality Orchestrator: DeletePodObserver Class Reference
DeletePodObserver Class Reference
Public Member Functions
void Update (int avg_cpuUtilization, int avg_memoryUtilization) override
void DeleteAllPods ()
Public Member Functions inherited from Observer
virtual ~Observer ()
Private Attributes
int cpu_utilization_threshold = stoi(config_parameters["cpu_utilization_threshold"])
int memory_utilization_threshold = stoi(config_parameters["memory_utilization_threshold"])
Detailed Description
Definition at line 161 of file mco_resource_monitor_handler.cpp.
Member Function Documentation
DeleteAllPods()
void DeletePodObserver::DeleteAllPods () inline
Definition at line 193 of file mco_resource_monitor_handler.cpp.
{
         // Logic to delete a pod
         list<string> running_apps = DatabaseHandler::GetInstance().ReadListData(kRunningApps);
         string container_runtime = config_parameters["container_runtime"];
         string msg = "";
         Invoker invoker;
         for (const auto& app : running_apps) {
             invoker.SetCommand(CommandFactory::CreateCommand(container_runtime, "DeletePod", app));
             if(!invoker.Invoke()) {
                 msg = "Failed to delete pod";
                 cout << msg << endl;
                 return;
                 // LOG(ERROR) << msg;
             }
         }
         msg = "All pods deleted successfully";
         cout << msg << endl;
         // LOG(INFO) << msg;
         UpdateEvent(msg);
     }
References config_parameters, CommandFactory::CreateCommand(), DatabaseHandler::GetInstance(), Invoker::Invoke(), kRunningApps, DatabaseHandler::ReadListData(), Invoker::SetCommand(), and UpdateEvent().
Update()
void DeletePodObserver::Update (int avg_cpuUtilization, int avg_memoryUtilization) inline override virtual
Implements Observer.
Definition at line 167 of file mco_resource_monitor_handler.cpp.
{
         // Logic to check if the resource utilization is high
         if(avg_cpuUtilization >= cpu_utilization_threshold){
             cout << "CPU utilization is high" << endl;
             is_cpu_utilization_high = true;
         } else{
             cout<< "CPU utilization is low" << endl;
             is_cpu_utilization_high = false;
         }
         if(avg_memoryUtilization >= memory_utilization_threshold){
             cout << "Memory utilization is high" << endl;
             is_memory_utilization_high = true;
         } else{
             cout<< "Memory utilization is low" << endl;
             is_memory_utilization_high = false;
         }
         // Check if CPU and Memory utilization is below threshold
         if(is_cpu_utilization_high or is_memory_utilization_high){
             string msg = "Resource utilization is above threshold limit";
             cout << msg << endl;
           //  DeleteAllPods();    // Delete QM pod
         }
     }
References is_cpu_utilization_high, and is_memory_utilization_high.
Member Data Documentation
cpu_utilization_threshold
int DeletePodObserver::cpu_utilization_threshold = stoi(config_parameters["cpu_utilization_threshold"]) private
Definition at line 163 of file mco_resource_monitor_handler.cpp.
memory_utilization_threshold
int DeletePodObserver::memory_utilization_threshold = stoi(config_parameters["memory_utilization_threshold"]) private
Definition at line 164 of file mco_resource_monitor_handler.cpp.
The documentation for this class was generated from the following file:
mc_orchestrator/bl/src/mco_resource_monitor_handler.cpp