Mixed Criticality Orchestrator: AvpTriggerMonitorHandler Class Reference
AvpTriggerMonitorHandler Class Reference
AvpTriggerMonitorHandler is used to monitor triggers from AVP application.
#include <mco_avp_trigger_monitor_handler.hpp>
Public Member Functions
void Init ()
initialize LFO to check for pods status.
Static Public Member Functions
static AvpTriggerMonitorHandler & GetInstance ()
Public static method getInstance(). This function is responsible for object creation.
Private Member Functions
AvpTriggerMonitorHandler ()=default
Define constructor in the private section to make this class as singleton.
~AvpTriggerMonitorHandler ()=default
Define destructor in private section, so no one can delete the instance of this class.
AvpTriggerMonitorHandler (const AvpTriggerMonitorHandler &obj)
Define copy constructor in the private section, so that no one can voilate the singleton policy of this class.
void operator= (const AvpTriggerMonitorHandler &obj)
Define assignment operator in the private section, so that no one can voilate the singleton policy of this class.
Detailed Description
AvpTriggerMonitorHandler is used to monitor triggers from AVP application.
Definition at line 14 of file mco_avp_trigger_monitor_handler.hpp.
Constructor & Destructor Documentation
AvpTriggerMonitorHandler() [1/2]
AvpTriggerMonitorHandler::AvpTriggerMonitorHandler () private default
Define constructor in the private section to make this class as singleton.
~AvpTriggerMonitorHandler()
AvpTriggerMonitorHandler::~AvpTriggerMonitorHandler () private default
Define destructor in private section, so no one can delete the instance of this class.
AvpTriggerMonitorHandler() [2/2]
AvpTriggerMonitorHandler::AvpTriggerMonitorHandler (const AvpTriggerMonitorHandler & obj) inline private
Define copy constructor in the private section, so that no one can voilate the singleton policy of this class.
Definition at line 31 of file mco_avp_trigger_monitor_handler.hpp.
 {}
Member Function Documentation
GetInstance()
AvpTriggerMonitorHandler & AvpTriggerMonitorHandler::GetInstance () static
Public static method getInstance(). This function is responsible for object creation.
Definition at line 52 of file mco_avp_trigger_monitor_handler.cpp.
 {
     static AvpTriggerMonitorHandler self{};
     return self;
 }
Init()
void AvpTriggerMonitorHandler::Init ()
initialize LFO to check for pods status.
Definition at line 58 of file mco_avp_trigger_monitor_handler.cpp.
 {
     mosqpp::lib_init();
     Subscriber subscriber("Subscriber", "localhost", 1883);
     Invoker invoker;
     std::string container_runtime = config_parameters["container_runtime"];
     invoker.SetCommand(CommandFactory::CreateCommand(container_runtime, "RuntimeStatus"));
     if(invoker.Invoke()) {
         while(true) {
             subscriber.loop();    // Start the loop to receive messages
             std::this_thread::sleep_for(std::chrono::milliseconds(20));  // Sleep for 20ms for subscription
             if (!subscriber.payload.empty()) {
                 json receivedMessage = json::parse(subscriber.payload);
                 std::string command = receivedMessage["command"];
                 std::string app_name = receivedMessage["app_name"];
                 std::cout << "COMMAND is: " << command << std::endl;
                 std::cout << "APP_NAME IS: " << app_name<< std::endl;
                // json response;
                 string msg = "";
                 if (command == "delete") {
                     // std::this_thread::sleep_for(std::chrono::seconds(5));  // Sleep for 5 seconds
                     bool success = true;
                     list<string> running_apps = DatabaseHandler::GetInstance().ReadListData(app_name);
                     for (const auto& app : running_apps) {
                         invoker.SetCommand(CommandFactory::CreateCommand(container_runtime, "DeletePod", app));
                         if(!invoker.Invoke()) {
                             msg = "FAILED to delete pods in group";
                             success = false;
                             break;
                         }
                     }
                     if (success) {
                         msg = "Pods requested as per AVP trigger are deleted";
                      }
                 //    response["response"] = msg;
                     UpdateEvent(msg);
                     DatabaseHandler::GetInstance().AddData("avp_trigger", "true");
                 } else{}
             subscriber.payload.clear(); // Clear the payload after processing the message
             } else {
                 cout << "No message received from " << kTopicAvp << " yet." << endl;
             }
         }
     }
       /*       auto avp_it = subscriber.topic_data.find(kTopicAvp);
              if (avp_it != subscriber.topic_data.end() && !avp_it->second.empty()) {
                 cout << "Received message from " << kTopicAvp << ": " << avp_it->second << endl;
                 subscriber.topic_data.erase(avp_it);
                 mosqpp::lib_cleanup();
             } else {
                 if (avp_it == subscriber.topic_data.end()) {
                     cout << "No message received from " << kTopicAvp << " yet." << endl;
                 } else {
                     cout << "Received message from " << kTopicAvp << " is empty." << endl;
                 }
             }
         }
     }    */
     else {
         // LOG(FATAL) << "K3S is not running";
     }
  }
References DatabaseHandler::AddData(), config_parameters, CommandFactory::CreateCommand(), DatabaseHandler::GetInstance(), Invoker::Invoke(), kTopicAvp, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parse(), Subscriber::payload, DatabaseHandler::ReadListData(), Invoker::SetCommand(), and UpdateEvent().
operator=()
void AvpTriggerMonitorHandler::operator= (const AvpTriggerMonitorHandler & obj) inline private
Define assignment operator in the private section, so that no one can voilate the singleton policy of this class.
Definition at line 34 of file mco_avp_trigger_monitor_handler.hpp.
 {}
The documentation for this class was generated from the following files:
mc_orchestrator/bl/inc/mco_avp_trigger_monitor_handler.hpp
mc_orchestrator/bl/src/mco_avp_trigger_monitor_handler.cpp