Mixed Criticality Orchestrator: K3sStarvePodCommand Class Reference
K3sStarvePodCommand Class Reference
#include <mco_k3s_commands.hpp>
Public Member Functions
K3sStarvePodCommand (const std::string &app_name_)
~K3sStarvePodCommand ()=default
bool Execute () const override
Public Member Functions inherited from Command
virtual ~Command ()=default
Private Attributes
std::string app_name_
Detailed Description
Definition at line 8 of file mco_k3s_commands.hpp.
Constructor & Destructor Documentation
K3sStarvePodCommand()
K3sStarvePodCommand::K3sStarvePodCommand (const std::string & app_name_)
Definition at line 48 of file mco_k3s_commands.cpp.
{
     this->app_name_ = app_name;
 }
~K3sStarvePodCommand()
K3sStarvePodCommand::~K3sStarvePodCommand () default
Member Function Documentation
Execute()
bool K3sStarvePodCommand::Execute () const override virtual
Implements Command.
Definition at line 52 of file mco_k3s_commands.cpp.
{
     // This method should contain the logic to starve pod
     string database_app_name_value = this->app_name_;
     string database_cpu_limit_value = DatabaseHandler::GetInstance().ReadData(this->app_name_, kCpuLimit);
     string database_memory_limit_value = DatabaseHandler::GetInstance().ReadData(this->app_name_, kMemoryLimit);
     string database_cpu_request_value = DatabaseHandler::GetInstance().ReadData(this->app_name_, kCpuRequest);
     string database_memory_request_value = DatabaseHandler::GetInstance().ReadData(this->app_name_, kMemoryRequest);
     string command = "kubectl patch deployment " + database_app_name_value + " -p " + "'{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"name\":\"" + database_app_name_value + "\",\"resources\":{\"limits\":{\"cpu\":\"" + database_cpu_limit_value + "\", \"memory\":\"" + database_memory_limit_value + "\"},\"requests\":{\"cpu\":\"" + database_cpu_request_value +"\", \"memory\":\"" + database_memory_request_value + "\"}}}]}}}}'";
     system(command.c_str());
     command = kK3sGetPods + kOutputFile;
     system(command.c_str());
     ifstream file(kOutputFile);
     // Parse the file into a json object
     json response_obj;
     file >> response_obj;
     for (const auto& item : response_obj["items"]) {
         string name = item["metadata"]["name"];
         if (name.rfind(this->app_name_, 0) == 0) {
             DatabaseHandler::GetInstance().ModifyValue(this->app_name_, kPodName, name);
             DatabaseHandler::GetInstance().ModifyValue(this->app_name_, kPodRunningStatus, "true");
         }
     }
     return true;
 }
References DatabaseHandler::GetInstance(), kCpuLimit, kCpuRequest, kK3sGetPods, kMemoryLimit, kMemoryRequest, kOutputFile, kPodName, kPodRunningStatus, DatabaseHandler::ModifyValue(), and DatabaseHandler::ReadData().
Member Data Documentation
app_name_
std::string K3sStarvePodCommand::app_name_ private
Definition at line 10 of file mco_k3s_commands.hpp.
The documentation for this class was generated from the following files:
mc_orchestrator/runtime/inc/mco_k3s_commands.hpp
mc_orchestrator/runtime/src/mco_k3s_commands.cpp