Mixed Criticality Orchestrator: httplib::Stream Class Reference
httplib::Stream Class Reference abstract
#include <httplib.h>
Public Member Functions
virtual ~Stream ()=default
virtual bool is_readable () const =0
virtual bool is_writable () const =0
virtual ssize_t read (char *ptr, size_t size)=0
virtual ssize_t write (const char *ptr, size_t size)=0
virtual void get_remote_ip_and_port (std::string &ip, int &port) const =0
virtual void get_local_ip_and_port (std::string &ip, int &port) const =0
virtual socket_t socket () const =0
template<typename... Args>
ssize_t write_format (const char *fmt, const Args &...args)
ssize_t write (const char *ptr)
ssize_t write (const std::string &s)
Detailed Description
Definition at line 636 of file httplib.h.
Constructor & Destructor Documentation
~Stream()
virtual httplib::Stream::~Stream () virtual default
Member Function Documentation
get_local_ip_and_port()
virtual void httplib::Stream::get_local_ip_and_port (std::string & ip, int & port) const pure virtual
Implemented in httplib::detail::SocketStream, and httplib::detail::BufferStream.
Referenced by httplib::Server::process_request().
get_remote_ip_and_port()
virtual void httplib::Stream::get_remote_ip_and_port (std::string & ip, int & port) const pure virtual
Implemented in httplib::detail::SocketStream, and httplib::detail::BufferStream.
Referenced by httplib::Server::process_request().
is_readable()
virtual bool httplib::Stream::is_readable () const pure virtual
Implemented in httplib::detail::SocketStream, and httplib::detail::BufferStream.
is_writable()
virtual bool httplib::Stream::is_writable () const pure virtual
Implemented in httplib::detail::SocketStream, and httplib::detail::BufferStream.
Referenced by httplib::detail::write_content(), httplib::detail::write_content_chunked(), and httplib::detail::write_content_without_length().
read()
virtual ssize_t httplib::Stream::read (char * ptr, size_t size) pure virtual
Implemented in httplib::detail::SocketStream, and httplib::detail::BufferStream.
Referenced by httplib::detail::stream_line_reader::getline(), httplib::detail::read_content_with_length(), httplib::detail::read_content_without_length(), and httplib::detail::skip_content_with_length().
socket()
virtual socket_t httplib::Stream::socket () const pure virtual
Implemented in httplib::detail::SocketStream, and httplib::detail::BufferStream.
Referenced by httplib::Server::process_request().
write() [1/3]
ssize_t httplib::Stream::write (const char * ptr) inline
Definition at line 5453 of file httplib.h.
{
   return write(ptr, strlen(ptr));
 }
write() [2/3]
virtual ssize_t httplib::Stream::write (const char * ptr, size_t size) pure virtual
Implemented in httplib::detail::SocketStream, and httplib::detail::BufferStream.
Referenced by httplib::detail::write_data(), write_format(), httplib::detail::write_headers(), and httplib::detail::write_multipart_ranges_data().
write() [3/3]
ssize_t httplib::Stream::write (const std::string & s) inline
Definition at line 5457 of file httplib.h.
{
   return write(s.data(), s.size());
 }
write_format()
template<typename... Args> ssize_t httplib::Stream::write_format (const char * fmt, const Args &... args) inline
Definition at line 1836 of file httplib.h.
{
   const auto bufsiz = 2048;
   std::array<char, bufsiz> buf{};
   auto sn = snprintf(buf.data(), buf.size() - 1, fmt, args...);
   if (sn <= 0) { return sn; }
   auto n = static_cast<size_t>(sn);
   if (n >= buf.size() - 1) {
     std::vector<char> glowable_buf(buf.size());
     while (n >= glowable_buf.size() - 1) {
       glowable_buf.resize(glowable_buf.size() * 2);
       n = static_cast<size_t>(
           snprintf(&glowable_buf[0], glowable_buf.size() - 1, fmt, args...));
     }
     return write(&glowable_buf[0], n);
   } else {
     return write(buf.data(), n);
   }
 }
References n, and write().
Referenced by httplib::Server::process_request(), httplib::detail::write_headers(), httplib::ClientImpl::write_request(), and httplib::Server::write_response_core().
The documentation for this class was generated from the following file:
mc_orchestrator/httplib/httplib.h