Mixed Criticality Orchestrator: BluechiStopQmUnitCommand Class Reference
BluechiStopQmUnitCommand Class Reference
#include <mco_bluechi_commands.hpp>
Public Member Functions
BluechiStopQmUnitCommand (const std::string &app_name_)
~BluechiStopQmUnitCommand ()=default
bool Execute () const override
Public Member Functions inherited from Command
virtual ~Command ()=default
Private Attributes
std::string app_name_
Detailed Description
Definition at line 74 of file mco_bluechi_commands.hpp.
Constructor & Destructor Documentation
BluechiStopQmUnitCommand()
BluechiStopQmUnitCommand::BluechiStopQmUnitCommand (const std::string & app_name_)
Definition at line 285 of file mco_bluechi_commands.cpp.
{
     this->app_name_ = app_name;
 }
~BluechiStopQmUnitCommand()
BluechiStopQmUnitCommand::~BluechiStopQmUnitCommand () default
Member Function Documentation
Execute()
bool BluechiStopQmUnitCommand::Execute () const override virtual
Implements Command.
Definition at line 289 of file mco_bluechi_commands.cpp.
{
     // string pod_name = DatabaseHandler::GetInstance().ReadData(this->app_name_, kPodName);
     // cout << "POD IS " << pod_name << endl;
     string command = kBluechiDeletePods + kQmNodeName + " " + this->app_name_ + ".service";
     system(command.c_str());
     // if (!DatabaseHandler::GetInstance().running_apps_.empty()) {
     //   //   Updating the list of running apps and deleted apps in the database
     //     DatabaseHandler::GetInstance().running_apps_.erase(this->app_name_);
     //     DatabaseHandler::GetInstance().UpdateRunningApps(kRunningApps, DatabaseHandler::GetInstance().running_apps_);
     //     DatabaseHandler::GetInstance().deleted_apps_.emplace(this->app_name_);
     //     DatabaseHandler::GetInstance().UpdateRunningApps(kDeletedApps, DatabaseHandler::GetInstance().deleted_apps_);
     //     string app_priority = DatabaseHandler::GetInstance().ReadData(this->app_name_, kAppPriority);
     //     if(app_priority == kHighPriority){
     //         DatabaseHandler::GetInstance().priority_high_apps_.erase(this->app_name_);
     //         DatabaseHandler::GetInstance().UpdateRunningApps(kPriorityHighApps, DatabaseHandler::GetInstance().priority_high_apps_);
     //     } else if(app_priority == kMediumPriority){
     //         DatabaseHandler::GetInstance().priority_medium_apps_.erase(this->app_name_);
     //         DatabaseHandler::GetInstance().UpdateRunningApps(kPriorityMediumApps, DatabaseHandler::GetInstance().priority_medium_apps_);
     //     } else if(app_priority == kLowPriority){
     //         DatabaseHandler::GetInstance().priority_low_apps_.erase(this->app_name_);
     //         DatabaseHandler::GetInstance().UpdateRunningApps(kPriorityLowApps, DatabaseHandler::GetInstance().priority_low_apps_);
     //     } else {}
     // } else {
     //     string msg = "No running services to stop";
     //     // LOG(INFO) << msg;
     //     cout << msg << endl;
     // }
     // DatabaseHandler::GetInstance().ModifyValue(this->app_name_, kPodName, "");  // Reset the pod name
     // DatabaseHandler::GetInstance().ModifyValue(this->app_name_, kPodRunningStatus, "false");  // Reset the running status
     // string msg = "Service is successfully stopped";
     // // LOG(INFO) << msg;
     // cout << msg << endl;
     string category = DatabaseHandler::GetInstance().ReadData(infotainment, this->app_name_, kCategory);
     if(category == "games"){
     DatabaseHandler::GetInstance().qm_infotainment_games_running_apps_.erase(this->app_name_);
     DatabaseHandler::GetInstance().UpdateRunningApps(kQmInfoGamesRunningApps, DatabaseHandler::GetInstance().qm_infotainment_games_running_apps_);
     DatabaseHandler::GetInstance().qm_infotainment_games_stopped_apps_.emplace(this->app_name_);
     DatabaseHandler::GetInstance().UpdateRunningApps(kQmInfoGamesStoppedApps, DatabaseHandler::GetInstance().qm_infotainment_games_stopped_apps_);
     } else if(category == "ott"){
     DatabaseHandler::GetInstance().qm_infotainment_ott_running_apps_.erase(this->app_name_);
     DatabaseHandler::GetInstance().UpdateRunningApps(kQmInfoOttRunningApps, DatabaseHandler::GetInstance().qm_infotainment_ott_running_apps_);
     DatabaseHandler::GetInstance().qm_infotainment_ott_stopped_apps_.emplace(this->app_name_);
     DatabaseHandler::GetInstance().UpdateRunningApps(kQmInfoOttStoppedApps, DatabaseHandler::GetInstance().qm_infotainment_ott_stopped_apps_);
     } else {}
     string priority = DatabaseHandler::GetInstance().ReadData(infotainment, this->app_name_, "priority");
     if(priority == "high"){
         DatabaseHandler::GetInstance().priority_high_qm_running_apps_.erase(this->app_name_);
         DatabaseHandler::GetInstance().UpdateRunningApps(kPriorityHighQmRunningApps, DatabaseHandler::GetInstance().priority_high_qm_running_apps_);
     } else if(priority == "medium"){
         DatabaseHandler::GetInstance().priority_medium_qm_running_apps_.erase(this->app_name_);
         DatabaseHandler::GetInstance().UpdateRunningApps(kPriorityMediumQmRunningApps, DatabaseHandler::GetInstance().priority_medium_qm_running_apps_);
     } else if(priority == "low"){
         DatabaseHandler::GetInstance().priority_low_qm_running_apps_.erase(this->app_name_);
         DatabaseHandler::GetInstance().UpdateRunningApps(kPriorityLowQmRunningApps, DatabaseHandler::GetInstance().priority_low_qm_running_apps_);
     } else {}
     return true;
 }
References DatabaseHandler::GetInstance(), infotainment, kBluechiDeletePods, kCategory, kPriorityHighQmRunningApps, kPriorityLowQmRunningApps, kPriorityMediumQmRunningApps, kQmInfoGamesRunningApps, kQmInfoGamesStoppedApps, kQmInfoOttRunningApps, kQmInfoOttStoppedApps, kQmNodeName, DatabaseHandler::priority_high_qm_running_apps_, DatabaseHandler::priority_low_qm_running_apps_, DatabaseHandler::priority_medium_qm_running_apps_, DatabaseHandler::qm_infotainment_games_running_apps_, DatabaseHandler::qm_infotainment_games_stopped_apps_, DatabaseHandler::qm_infotainment_ott_running_apps_, DatabaseHandler::qm_infotainment_ott_stopped_apps_, DatabaseHandler::ReadData(), and DatabaseHandler::UpdateRunningApps().
Member Data Documentation
app_name_
std::string BluechiStopQmUnitCommand::app_name_ private
Definition at line 76 of file mco_bluechi_commands.hpp.
The documentation for this class was generated from the following files:
mc_orchestrator/runtime/inc/mco_bluechi_commands.hpp
mc_orchestrator/runtime/src/mco_bluechi_commands.cpp