Mixed Criticality Orchestrator: fuzzer::TracePC Class Reference
fuzzer::TracePC Class Reference
#include <FuzzerTracePC.h>
Classes
struct Module
Public Member Functions
void HandleTrace (uint32_t *guard, uintptr_t PC)
void HandleInit (uint32_t *start, uint32_t *stop)
void HandleCallerCallee (uintptr_t Caller, uintptr_t Callee)
void HandleValueProfile (size_t Value)
template<class T >
void HandleCmp (void *PC, T Arg1, T Arg2)
size_t GetTotalPCCoverage ()
void SetUseCounters (bool UC)
void SetUseValueProfile (bool VP)
void SetPrintNewPCs (bool P)
template<class Callback >
size_t CollectFeatures (Callback CB)
bool UpdateValueProfileMap (ValueBitMap *MaxValueProfileMap)
void ResetMaps ()
void UpdateFeatureSet (size_t CurrentElementIdx, size_t CurrentElementSize)
void PrintFeatureSet ()
void PrintModuleInfo ()
void PrintCoverage ()
void DumpCoverage ()
void AddValueForMemcmp (void *caller_pc, const void *s1, const void *s2, size_t n)
void AddValueForStrcmp (void *caller_pc, const char *s1, const char *s2, size_t n)
bool UsingTracePcGuard () const
void PrintNewPCs ()
size_t GetNumPCs () const
uintptr_t GetPC (size_t Idx)
Public Attributes
TableOfRecentCompares< uint32_t, kTORCSize > TORC4
TableOfRecentCompares< uint64_t, kTORCSize > TORC8
Static Public Attributes
static const size_t kFeatureSetSize = ValueBitMap::kNumberOfItems
static const size_t kTORCSize = 1 << 5
Private Attributes
bool UseCounters = false
bool UseValueProfile = false
bool DoPrintNewPCs = false
Module Modules [4096]
size_t NumModules
size_t NumGuards
uint8_t Counters [kNumCounters]
uintptr_t PCs [kNumPCs]
std::set< uintptr_t > * PrintedPCs
ValueBitMap ValueProfileMap
Static Private Attributes
static const size_t kNumCounters = 1 << 14
static const size_t kNumPCs = 1 << 24
Detailed Description
Definition at line 45 of file FuzzerTracePC.h.
Member Function Documentation
AddValueForMemcmp()
void fuzzer::TracePC::AddValueForMemcmp (void * caller_pc, const void * s1, const void * s2, size_t n)
Definition at line 207 of file FuzzerTracePC.cpp.
{
   if (!n) return;
   size_t Len = std::min(n, (size_t)32);
   const uint8_t *A1 = reinterpret_cast<const uint8_t *>(s1);
   const uint8_t *A2 = reinterpret_cast<const uint8_t *>(s2);
   size_t I = 0;
   for (; I < Len; I++)
     if (A1[I] != A2[I])
       break;
   size_t PC = reinterpret_cast<size_t>(caller_pc);
   size_t Idx = I;
   // if (I < Len)
   //  Idx += __builtin_popcountl((A1[I] ^ A2[I])) - 1;
   TPC.HandleValueProfile((PC & 4095) | (Idx << 12));
 }
References HandleValueProfile(), Idx, n, PC, and fuzzer::TPC.
Referenced by __sanitizer_weak_hook_memcmp().
AddValueForStrcmp()
void fuzzer::TracePC::AddValueForStrcmp (void * caller_pc, const char * s1, const char * s2, size_t n)
Definition at line 225 of file FuzzerTracePC.cpp.
{
   if (!n) return;
   size_t Len = std::min(n, (size_t)32);
   const uint8_t *A1 = reinterpret_cast<const uint8_t *>(s1);
   const uint8_t *A2 = reinterpret_cast<const uint8_t *>(s2);
   size_t I = 0;
   for (; I < Len; I++)
     if (A1[I] != A2[I] || A1[I] == 0)
       break;
   size_t PC = reinterpret_cast<size_t>(caller_pc);
   size_t Idx = I;
   // if (I < Len && A1[I])
   //  Idx += __builtin_popcountl((A1[I] ^ A2[I])) - 1;
   TPC.HandleValueProfile((PC & 4095) | (Idx << 12));
 }
References HandleValueProfile(), Idx, n, PC, and fuzzer::TPC.
Referenced by __sanitizer_weak_hook_strcmp(), and __sanitizer_weak_hook_strncmp().
CollectFeatures()
template<class Callback > size_t fuzzer::TracePC::CollectFeatures (Callback CB)
Definition at line 119 of file FuzzerTracePC.h.
{
   if (!UsingTracePcGuard()) return 0;
   size_t Res = 0;
   const size_t Step = 8;
   assert(reinterpret_cast<uintptr_t>(Counters) % Step == 0);
   size_t N = Min(kNumCounters, NumGuards + 1);
   N = (N + Step - 1) & ~(Step - 1);  // Round up.
   for (size_t Idx = 0; Idx < N; Idx += Step) {
     uint64_t Bundle = *reinterpret_cast<uint64_t*>(&Counters[Idx]);
     if (!Bundle) continue;
     for (size_t i = Idx; i < Idx + Step; i++) {
       uint8_t Counter = (Bundle >> ((i - Idx) * 8)) & 0xff;
       if (!Counter) continue;
       Counters[i] = 0;
       unsigned Bit = 0;
        if (Counter >= 128) Bit = 7;
       else if (Counter >= 32) Bit = 6;
       else if (Counter >= 16) Bit = 5;
       else if (Counter >= 8) Bit = 4;
       else if (Counter >= 4) Bit = 3;
       else if (Counter >= 3) Bit = 2;
       else if (Counter >= 2) Bit = 1;
       size_t Feature = (i * 8 + Bit);
       if (CB(Feature))
         Res++;
     }
   }
   if (UseValueProfile)
     ValueProfileMap.ForEach([&](size_t Idx) {
       if (CB(NumGuards * 8 + Idx))
         Res++;
     });
   return Res;
 }
References assert(), Counter, Counters, fuzzer::ValueBitMap::ForEach(), Idx, kNumCounters, fuzzer::Min(), N, NumGuards, UseValueProfile, UsingTracePcGuard(), and ValueProfileMap.
Referenced by fuzzer::Fuzzer::CrashResistantMergeInternalStep(), and fuzzer::Fuzzer::RunOne().
DumpCoverage()
void fuzzer::TracePC::DumpCoverage ()
Definition at line 192 of file FuzzerTracePC.cpp.
{
   __sanitizer_dump_coverage(PCs, GetNumPCs());
 }
References GetNumPCs(), and PCs.
Referenced by fuzzer::Fuzzer::PrintFinalStats().
GetNumPCs()
size_t fuzzer::TracePC::GetNumPCs () const inline
Definition at line 88 of file FuzzerTracePC.h.
 { return Min(kNumPCs, NumGuards + 1); }
References kNumPCs, fuzzer::Min(), and NumGuards.
Referenced by fuzzer::Fuzzer::CheckExitOnSrcPosOrItem(), DumpCoverage(), GetPC(), GetTotalPCCoverage(), PrintCoverage(), and PrintNewPCs().
GetPC()
uintptr_t fuzzer::TracePC::GetPC (size_t Idx) inline
Definition at line 89 of file FuzzerTracePC.h.
{
     assert(Idx < GetNumPCs());
     return PCs[Idx];
   }
References assert(), GetNumPCs(), Idx, and PCs.
Referenced by fuzzer::Fuzzer::CheckExitOnSrcPosOrItem().
GetTotalPCCoverage()
size_t fuzzer::TracePC::GetTotalPCCoverage ()
Definition at line 38 of file FuzzerTracePC.cpp.
{
   size_t Res = 0;
   for (size_t i = 1; i < GetNumPCs(); i++)
     if (PCs[i])
       Res++;
   return Res;
 }
References GetNumPCs(), and PCs.
Referenced by fuzzer::Fuzzer::PrintStats().
HandleCallerCallee()
void fuzzer::TracePC::HandleCallerCallee (uintptr_t Caller, uintptr_t Callee)
Definition at line 63 of file FuzzerTracePC.cpp.
{
   const uintptr_t kBits = 12;
   const uintptr_t kMask = (1 << kBits) - 1;
   uintptr_t Idx = (Caller & kMask) | ((Callee & kMask) << kBits);
   HandleValueProfile(Idx);
 }
References HandleValueProfile(), and Idx.
HandleCmp()
template<class T > void fuzzer::TracePC::HandleCmp (void * PC, T Arg1, T Arg2)
Definition at line 247 of file FuzzerTracePC.cpp.
{
   uintptr_t PCuint = reinterpret_cast<uintptr_t>(PC);
   uint64_t ArgXor = Arg1 ^ Arg2;
   uint64_t ArgDistance = __builtin_popcountl(ArgXor) + 1; // [1,65]
   uintptr_t Idx = ((PCuint & 4095) + 1) * ArgDistance;
   if (sizeof(T) == 4)
       TORC4.Insert(ArgXor, Arg1, Arg2);
   else if (sizeof(T) == 8)
       TORC8.Insert(ArgXor, Arg1, Arg2);
   HandleValueProfile(Idx);
 }
References Arg2, HandleValueProfile(), Idx, fuzzer::TableOfRecentCompares< T, kSizeT >::Insert(), PC, TORC4, and TORC8.
HandleInit()
void fuzzer::TracePC::HandleInit (uint32_t * start, uint32_t * stop)
Definition at line 46 of file FuzzerTracePC.cpp.
{
   if (Start == Stop || *Start) return;
   assert(NumModules < sizeof(Modules) / sizeof(Modules[0]));
   for (uint32_t *P = Start; P < Stop; P++)
     *P = ++NumGuards;
   Modules[NumModules].Start = Start;
   Modules[NumModules].Stop = Stop;
   NumModules++;
 }
References assert(), Modules, NumGuards, NumModules, fuzzer::TracePC::Module::Start, fuzzer::TracePC::Module::Stop, and Stop.
HandleTrace()
void fuzzer::TracePC::HandleTrace (uint32_t * guard, uintptr_t PC)
Definition at line 31 of file FuzzerTracePC.cpp.
{
   uint32_t Idx = *Guard;
   if (!Idx) return;
   PCs[Idx % kNumPCs] = PC;
   Counters[Idx % kNumCounters]++;
 }
References Counters, Idx, kNumCounters, kNumPCs, PC, and PCs.
Referenced by __attribute__().
HandleValueProfile()
void fuzzer::TracePC::HandleValueProfile (size_t Value) inline
Definition at line 52 of file FuzzerTracePC.h.
 { ValueProfileMap.AddValue(Value); }
References fuzzer::ValueBitMap::AddValue(), and ValueProfileMap.
Referenced by AddValueForMemcmp(), AddValueForStrcmp(), HandleCallerCallee(), and HandleCmp().
PrintCoverage()
void fuzzer::TracePC::PrintCoverage ()
Definition at line 92 of file FuzzerTracePC.cpp.
{
   if (!EF->__sanitizer_symbolize_pc ||
       !EF->__sanitizer_get_module_and_offset_for_pc) {
     Printf("INFO: __sanitizer_symbolize_pc or "
            "__sanitizer_get_module_and_offset_for_pc is not available,"
            " not printing coverage\n");
     return;
   }
   std::map<std::string, std::vector<uintptr_t>> CoveredPCsPerModule;
   std::map<std::string, uintptr_t> ModuleOffsets;
   std::set<std::string> CoveredDirs, CoveredFiles, CoveredFunctions,
       CoveredLines;
   Printf("COVERAGE:\n");
   for (size_t i = 1; i < GetNumPCs(); i++) {
     if (!PCs[i]) continue;
     std::string FileStr = DescribePC("%s", PCs[i]);
     if (!IsInterestingCoverageFile(FileStr)) continue;
     std::string FixedPCStr = DescribePC("%p", PCs[i]);
     std::string FunctionStr = DescribePC("%F", PCs[i]);
     std::string LineStr = DescribePC("%l", PCs[i]);
     char ModulePathRaw[4096] = "";  // What's PATH_MAX in portable C++?
     void *OffsetRaw = nullptr;
     if (!EF->__sanitizer_get_module_and_offset_for_pc(
             reinterpret_cast<void *>(PCs[i]), ModulePathRaw,
             sizeof(ModulePathRaw), &OffsetRaw))
       continue;
     std::string Module = ModulePathRaw;
     uintptr_t FixedPC = std::stol(FixedPCStr, 0, 16);
     uintptr_t PcOffset = reinterpret_cast<uintptr_t>(OffsetRaw);
     ModuleOffsets[Module] = FixedPC - PcOffset;
     CoveredPCsPerModule[Module].push_back(PcOffset);
     CoveredFunctions.insert(FunctionStr);
     CoveredFiles.insert(FileStr);
     CoveredDirs.insert(DirName(FileStr));
     if (!CoveredLines.insert(FileStr + ":" + LineStr).second)
       continue;
     Printf("COVERED: %s %s:%s\n", FunctionStr.c_str(),
            FileStr.c_str(), LineStr.c_str());
   }
   std::string CoveredDirsStr;
   for (auto &Dir : CoveredDirs) {
     if (!CoveredDirsStr.empty())
       CoveredDirsStr += ",";
     CoveredDirsStr += Dir;
   }
   Printf("COVERED_DIRS: %s\n", CoveredDirsStr.c_str());
   for (auto &M : CoveredPCsPerModule) {
     std::set<std::string> UncoveredFiles, UncoveredFunctions;
     std::map<std::string, std::set<int> > UncoveredLines;  // Func+File => lines
     auto &ModuleName = M.first;
     auto &CoveredOffsets = M.second;
     uintptr_t ModuleOffset = ModuleOffsets[ModuleName];
     std::sort(CoveredOffsets.begin(), CoveredOffsets.end());
     Printf("MODULE_WITH_COVERAGE: %s\n", ModuleName.c_str());
     // sancov does not yet fully support DSOs.
     // std::string Cmd = "sancov -print-coverage-pcs " + ModuleName;
     std::string Cmd = "objdump -d " + ModuleName +
         " | grep 'call.*__sanitizer_cov_trace_pc_guard' | awk -F: '{print $1}'";
     std::string SanCovOutput;
     if (!ExecuteCommandAndReadOutput(Cmd, &SanCovOutput)) {
       Printf("INFO: Command failed: %s\n", Cmd.c_str());
       continue;
     }
     std::istringstream ISS(SanCovOutput);
     std::string S;
     while (std::getline(ISS, S, '\n')) {
       uintptr_t PcOffset = std::stol(S, 0, 16);
       if (!std::binary_search(CoveredOffsets.begin(), CoveredOffsets.end(),
                               PcOffset)) {
         uintptr_t PC = ModuleOffset + PcOffset;
         auto FileStr = DescribePC("%s", PC);
         if (!IsInterestingCoverageFile(FileStr)) continue;
         if (CoveredFiles.count(FileStr) == 0) {
           UncoveredFiles.insert(FileStr);
           continue;
         }
         auto FunctionStr = DescribePC("%F", PC);
         if (CoveredFunctions.count(FunctionStr) == 0) {
           UncoveredFunctions.insert(FunctionStr);
           continue;
         }
         std::string LineStr = DescribePC("%l", PC);
         uintptr_t Line = std::stoi(LineStr);
         std::string FileLineStr = FileStr + ":" + LineStr;
         if (CoveredLines.count(FileLineStr) == 0)
           UncoveredLines[FunctionStr + " " + FileStr].insert(Line);
       }
     }
     for (auto &FileLine: UncoveredLines)
       for (int Line : FileLine.second)
         Printf("UNCOVERED_LINE: %s:%d\n", FileLine.first.c_str(), Line);
     for (auto &Func : UncoveredFunctions)
       Printf("UNCOVERED_FUNC: %s\n", Func.c_str());
     for (auto &File : UncoveredFiles)
       Printf("UNCOVERED_FILE: %s\n", File.c_str());
   }
 }
References fuzzer::DescribePC(), fuzzer::DirName(), fuzzer::EF, fuzzer::ExecuteCommandAndReadOutput(), GetNumPCs(), fuzzer::IsInterestingCoverageFile(), PC, PCs, and fuzzer::Printf().
Referenced by fuzzer::Fuzzer::PrintFinalStats().
PrintFeatureSet()
void fuzzer::TracePC::PrintFeatureSet ()
PrintModuleInfo()
void fuzzer::TracePC::PrintModuleInfo ()
Definition at line 56 of file FuzzerTracePC.cpp.
{
   Printf("INFO: Loaded %zd modules (%zd guards): ", NumModules, NumGuards);
   for (size_t i = 0; i < NumModules; i++)
     Printf("[%p, %p), ", Modules[i].Start, Modules[i].Stop);
   Printf("\n");
 }
References Modules, NumGuards, NumModules, fuzzer::Printf(), and Stop.
Referenced by fuzzer::Fuzzer::Fuzzer().
PrintNewPCs()
void fuzzer::TracePC::PrintNewPCs ()
Definition at line 82 of file FuzzerTracePC.cpp.
{
   if (DoPrintNewPCs) {
     if (!PrintedPCs)
       PrintedPCs = new std::set<uintptr_t>;
     for (size_t i = 1; i < GetNumPCs(); i++)
       if (PCs[i] && PrintedPCs->insert(PCs[i]).second)
         PrintPC("\tNEW_PC: %p %F %L\n", "\tNEW_PC: %p\n", PCs[i]);
   }
 }
References DoPrintNewPCs, GetNumPCs(), PCs, PrintedPCs, and fuzzer::PrintPC().
Referenced by fuzzer::Fuzzer::ReportNewCoverage().
ResetMaps()
void fuzzer::TracePC::ResetMaps () inline
Definition at line 63 of file FuzzerTracePC.h.
                    {
     ValueProfileMap.Reset();
     memset(Counters, 0, sizeof(Counters));
   }
References Counters, fuzzer::ValueBitMap::Reset(), and ValueProfileMap.
Referenced by fuzzer::Fuzzer::CrashResistantMergeInternalStep(), fuzzer::Fuzzer::ExecuteCallback(), fuzzer::Fuzzer::FindExtraUnits(), and fuzzer::Fuzzer::Fuzzer().
SetPrintNewPCs()
void fuzzer::TracePC::SetPrintNewPCs (bool P) inline
Definition at line 57 of file FuzzerTracePC.h.
 { DoPrintNewPCs = P; }
References DoPrintNewPCs.
Referenced by fuzzer::Fuzzer::Fuzzer().
SetUseCounters()
void fuzzer::TracePC::SetUseCounters (bool UC) inline
Definition at line 55 of file FuzzerTracePC.h.
 { UseCounters = UC; }
References UseCounters.
Referenced by fuzzer::Fuzzer::Fuzzer().
SetUseValueProfile()
void fuzzer::TracePC::SetUseValueProfile (bool VP) inline
Definition at line 56 of file FuzzerTracePC.h.
 { UseValueProfile = VP; }
References UseValueProfile.
Referenced by fuzzer::Fuzzer::Fuzzer().
UpdateFeatureSet()
void fuzzer::TracePC::UpdateFeatureSet (size_t CurrentElementIdx, size_t CurrentElementSize)
UpdateValueProfileMap()
bool fuzzer::TracePC::UpdateValueProfileMap (ValueBitMap * MaxValueProfileMap) inline
Definition at line 59 of file FuzzerTracePC.h.
{
     return UseValueProfile && MaxValueProfileMap->MergeFrom(ValueProfileMap);
   }
References fuzzer::ValueBitMap::MergeFrom(), UseValueProfile, and ValueProfileMap.
Referenced by fuzzer::Fuzzer::RunOne().
UsingTracePcGuard()
bool fuzzer::TracePC::UsingTracePcGuard () const inline
Definition at line 81 of file FuzzerTracePC.h.
 {return NumModules; }
References NumModules.
Referenced by CollectFeatures(), fuzzer::FuzzerDriver(), and fuzzer::Fuzzer::RunOne().
Member Data Documentation
Counters
uint8_t fuzzer::TracePC::Counters[kNumCounters] private
Definition at line 108 of file FuzzerTracePC.h.
Referenced by CollectFeatures(), HandleTrace(), and ResetMaps().
DoPrintNewPCs
bool fuzzer::TracePC::DoPrintNewPCs = false private
Definition at line 97 of file FuzzerTracePC.h.
Referenced by PrintNewPCs(), and SetPrintNewPCs().
kFeatureSetSize
const size_t fuzzer::TracePC::kFeatureSetSize = ValueBitMap::kNumberOfItems static
Definition at line 47 of file FuzzerTracePC.h.
kNumCounters
const size_t fuzzer::TracePC::kNumCounters = 1 << 14 static private
Definition at line 107 of file FuzzerTracePC.h.
Referenced by CollectFeatures(), and HandleTrace().
kNumPCs
const size_t fuzzer::TracePC::kNumPCs = 1 << 24 static private
Definition at line 110 of file FuzzerTracePC.h.
Referenced by GetNumPCs(), and HandleTrace().
kTORCSize
const size_t fuzzer::TracePC::kTORCSize = 1 << 5 static
Definition at line 83 of file FuzzerTracePC.h.
Modules
Module fuzzer::TracePC::Modules[4096] private
Definition at line 103 of file FuzzerTracePC.h.
Referenced by HandleInit(), and PrintModuleInfo().
NumGuards
size_t fuzzer::TracePC::NumGuards private
Definition at line 105 of file FuzzerTracePC.h.
Referenced by CollectFeatures(), GetNumPCs(), HandleInit(), and PrintModuleInfo().
NumModules
size_t fuzzer::TracePC::NumModules private
Definition at line 104 of file FuzzerTracePC.h.
Referenced by HandleInit(), PrintModuleInfo(), and UsingTracePcGuard().
PCs
uintptr_t fuzzer::TracePC::PCs[kNumPCs] private
Definition at line 111 of file FuzzerTracePC.h.
Referenced by DumpCoverage(), GetPC(), GetTotalPCCoverage(), HandleTrace(), PrintCoverage(), and PrintNewPCs().
PrintedPCs
std::set<uintptr_t>* fuzzer::TracePC::PrintedPCs private
Definition at line 113 of file FuzzerTracePC.h.
Referenced by PrintNewPCs().
TORC4
TableOfRecentCompares<uint32_t, kTORCSize> fuzzer::TracePC::TORC4
Definition at line 84 of file FuzzerTracePC.h.
Referenced by HandleCmp(), and fuzzer::MutationDispatcher::Mutate_AddWordFromTORC().
TORC8
TableOfRecentCompares<uint64_t, kTORCSize> fuzzer::TracePC::TORC8
Definition at line 85 of file FuzzerTracePC.h.
Referenced by HandleCmp(), and fuzzer::MutationDispatcher::Mutate_AddWordFromTORC().
UseCounters
bool fuzzer::TracePC::UseCounters = false private
Definition at line 95 of file FuzzerTracePC.h.
Referenced by SetUseCounters().
UseValueProfile
bool fuzzer::TracePC::UseValueProfile = false private
Definition at line 96 of file FuzzerTracePC.h.
Referenced by CollectFeatures(), SetUseValueProfile(), and UpdateValueProfileMap().
ValueProfileMap
ValueBitMap fuzzer::TracePC::ValueProfileMap private
Definition at line 115 of file FuzzerTracePC.h.
Referenced by CollectFeatures(), HandleValueProfile(), ResetMaps(), and UpdateValueProfileMap().
The documentation for this class was generated from the following files:
mc_orchestrator/json-3.7.3/test/thirdparty/Fuzzer/FuzzerTracePC.h
mc_orchestrator/json-3.7.3/test/thirdparty/Fuzzer/FuzzerTracePC.cpp