Mixed Criticality Orchestrator: fuzzer::Dictionary Class Reference
fuzzer::Dictionary Class Reference
#include <FuzzerDictionary.h>
Public Member Functions
bool ContainsWord (const Word &W) const
const DictionaryEntry * begin () const
const DictionaryEntry * end () const
DictionaryEntry & operator[] (size_t Idx)
void push_back (DictionaryEntry DE)
void clear ()
bool empty () const
size_t size () const
Static Public Attributes
static const size_t kMaxDictSize = 1 << 14
Private Attributes
DictionaryEntry DE [kMaxDictSize]
size_t Size = 0
Detailed Description
Definition at line 86 of file FuzzerDictionary.h.
Member Function Documentation
begin()
const DictionaryEntry* fuzzer::Dictionary::begin () const inline
Definition at line 95 of file FuzzerDictionary.h.
 { return &DE[0]; }
References DE.
Referenced by ContainsWord(), and end().
clear()
void fuzzer::Dictionary::clear () inline
Definition at line 105 of file FuzzerDictionary.h.
 { Size = 0; }
References Size.
ContainsWord()
bool fuzzer::Dictionary::ContainsWord (const Word & W) const inline
Definition at line 90 of file FuzzerDictionary.h.
{
     return std::any_of(begin(), end(), [&](const DictionaryEntry &DE) {
       return DE.GetW() == W;
     });
   }
References begin(), DE, end(), and fuzzer::DictionaryEntry::GetW().
empty()
bool fuzzer::Dictionary::empty () const inline
Definition at line 106 of file FuzzerDictionary.h.
 { return Size == 0; }
References Size.
Referenced by fuzzer::MutationDispatcher::AddWordFromDictionary(), and fuzzer::FuzzerDriver().
end()
const DictionaryEntry* fuzzer::Dictionary::end () const inline
Definition at line 96 of file FuzzerDictionary.h.
 { return begin() + Size; }
References begin(), and Size.
Referenced by ContainsWord().
operator[]()
DictionaryEntry& fuzzer::Dictionary::operator[] (size_t Idx) inline
Definition at line 97 of file FuzzerDictionary.h.
{
     assert(Idx < Size);
     return DE[Idx];
   }
References assert(), DE, Idx, and Size.
push_back()
void fuzzer::Dictionary::push_back (DictionaryEntry DE) inline
Definition at line 101 of file FuzzerDictionary.h.
{
     if (Size < kMaxDictSize)
       this->DE[Size++] = DE;
   }
References DE, kMaxDictSize, and Size.
size()
size_t fuzzer::Dictionary::size () const inline
Definition at line 107 of file FuzzerDictionary.h.
 { return Size; }
References Size.
Referenced by fuzzer::MutationDispatcher::AddWordFromDictionary(), and fuzzer::FuzzerDriver().
Member Data Documentation
DE
DictionaryEntry fuzzer::Dictionary::DE[kMaxDictSize] private
Definition at line 110 of file FuzzerDictionary.h.
Referenced by begin(), ContainsWord(), operator[](), and push_back().
kMaxDictSize
const size_t fuzzer::Dictionary::kMaxDictSize = 1 << 14 static
Definition at line 88 of file FuzzerDictionary.h.
Referenced by push_back().
Size
size_t fuzzer::Dictionary::Size = 0 private
Definition at line 111 of file FuzzerDictionary.h.
Referenced by clear(), empty(), end(), operator[](), push_back(), and size().
The documentation for this class was generated from the following files:
mc_orchestrator/json-3.7.3/test/thirdparty/Fuzzer/FuzzerDictionary.h
mc_orchestrator/json-3.7.3/test/thirdparty/Fuzzer/FuzzerMutate.cpp