Mixed Criticality Orchestrator: ResourceMonitorHandler Class Reference
ResourceMonitorHandler Class Reference
ResourceMonitorHandler is used to monitor resources of host machine.
#include <mco_resource_monitor_handler.hpp>
Public Member Functions
void Init ()
initialize LFO to check for pods status.
Static Public Member Functions
static ResourceMonitorHandler & GetInstance ()
Public static method getInstance(). This function is responsible for object creation.
Private Member Functions
ResourceMonitorHandler ()=default
Define constructor in the private section to make this class as singleton.
~ResourceMonitorHandler ()=default
Define destructor in private section, so no one can delete the instance of this class.
ResourceMonitorHandler (const ResourceMonitorHandler &obj)
Define copy constructor in the private section, so that no one can voilate the singleton policy of this class.
void operator= (const ResourceMonitorHandler &obj)
Define assignment operator in the private section, so that no one can voilate the singleton policy of this class.
Detailed Description
ResourceMonitorHandler is used to monitor resources of host machine.
Definition at line 14 of file mco_resource_monitor_handler.hpp.
Constructor & Destructor Documentation
ResourceMonitorHandler() [1/2]
ResourceMonitorHandler::ResourceMonitorHandler () private default
Define constructor in the private section to make this class as singleton.
~ResourceMonitorHandler()
ResourceMonitorHandler::~ResourceMonitorHandler () private default
Define destructor in private section, so no one can delete the instance of this class.
ResourceMonitorHandler() [2/2]
ResourceMonitorHandler::ResourceMonitorHandler (const ResourceMonitorHandler & obj) inline private
Define copy constructor in the private section, so that no one can voilate the singleton policy of this class.
Definition at line 31 of file mco_resource_monitor_handler.hpp.
 {}
Member Function Documentation
GetInstance()
ResourceMonitorHandler & ResourceMonitorHandler::GetInstance () static
Public static method getInstance(). This function is responsible for object creation.
Definition at line 31 of file mco_resource_monitor_handler.cpp.
 {
     static ResourceMonitorHandler self{};
     return self;
 }
Init()
void ResourceMonitorHandler::Init ()
initialize LFO to check for pods status.
Definition at line 289 of file mco_resource_monitor_handler.cpp.
{
     // Initialize the mosquitto library
     mosqpp::lib_init();
     // Remove old file
     if (remove(kAllLogsFile.c_str()) != 0) {
         perror("Error deleting file");
     } else {
         puts("File successfully deleted");
     }
     // Spawn all exisiting apps
     Invoker invoker;
     list<string> available_apps = DatabaseHandler::GetInstance().ReadListData(kRunningApps);
     string container_runtime = config_parameters["container_runtime"];
     for (const auto& app : available_apps) {
         invoker.SetCommand(CommandFactory::CreateCommand(container_runtime, "ApplyPod", app));
         if(!invoker.Invoke()) {
             string msg = "Failed to spawn pod";
             cout << msg << endl;
             // LOG(ERROR) << msg;
         }
     }
     string msg = "Spawnned all pods at start";
     cout << msg << endl;
     // LOG(INFO) << msg;
     UpdateEvent(msg);
     ResourceMonitorSubject resourceMonitorSubject;
     DeletePodObserver deletePodObserver;
     RespawnPodObserver respawnPodObserver;
     resourceMonitorSubject.AddObserver(&deletePodObserver);
     resourceMonitorSubject.AddObserver(&respawnPodObserver);
     resourceMonitorSubject.Run();
     mosqpp::lib_cleanup(); // Clean up the mosquitto library
 }
References ResourceMonitorSubject::AddObserver(), config_parameters, CommandFactory::CreateCommand(), DatabaseHandler::GetInstance(), Invoker::Invoke(), kAllLogsFile, kRunningApps, DatabaseHandler::ReadListData(), ResourceMonitorSubject::Run(), Invoker::SetCommand(), and UpdateEvent().
operator=()
void ResourceMonitorHandler::operator= (const ResourceMonitorHandler & obj) inline private
Define assignment operator in the private section, so that no one can voilate the singleton policy of this class.
Definition at line 34 of file mco_resource_monitor_handler.hpp.
 {}
The documentation for this class was generated from the following files:
mc_orchestrator/bl/inc/mco_resource_monitor_handler.hpp
mc_orchestrator/bl/src/mco_resource_monitor_handler.cpp