Mixed Criticality Orchestrator: nlohmann::detail::serializer< BasicJsonType > Class Template Reference
nlohmann::detail::serializer< BasicJsonType > Class Template Reference
#include <serializer.hpp>
Public Member Functions
serializer (output_adapter_t< char > s, const char ichar, error_handler_t error_handler_=error_handler_t::strict)
serializer (const serializer &)=delete
serializer & operator= (const serializer &)=delete
serializer (serializer &&)=delete
serializer & operator= (serializer &&)=delete
~serializer ()=default
void dump (const BasicJsonType &val, const bool pretty_print, const bool ensure_ascii, const unsigned int indent_step, const unsigned int current_indent=0)
internal implementation of the serialization function
serializer (output_adapter_t< char > s, const char ichar, error_handler_t error_handler_=error_handler_t::strict)
serializer (const serializer &)=delete
serializer & operator= (const serializer &)=delete
serializer (serializer &&)=delete
serializer & operator= (serializer &&)=delete
~serializer ()=default
void dump (const BasicJsonType &val, const bool pretty_print, const bool ensure_ascii, const unsigned int indent_step, const unsigned int current_indent=0)
internal implementation of the serialization function
Private Types
using string_t = typename BasicJsonType::string_t
using number_float_t = typename BasicJsonType::number_float_t
using number_integer_t = typename BasicJsonType::number_integer_t
using number_unsigned_t = typename BasicJsonType::number_unsigned_t
using string_t = typename BasicJsonType::string_t
using number_float_t = typename BasicJsonType::number_float_t
using number_integer_t = typename BasicJsonType::number_integer_t
using number_unsigned_t = typename BasicJsonType::number_unsigned_t
Private Member Functions
void dump_escaped (const string_t &s, const bool ensure_ascii)
dump escaped string
unsigned int count_digits (number_unsigned_t x) noexcept
count digits
template<typename NumberType , detail::enable_if_t< std::is_same< NumberType, number_unsigned_t >::value or std::is_same< NumberType, number_integer_t >::value, int > = 0>
void dump_integer (NumberType x)
dump an integer
void dump_float (number_float_t x)
dump a floating-point number
void dump_float (number_float_t x, std::true_type)
void dump_float (number_float_t x, std::false_type)
number_unsigned_t remove_sign (number_unsigned_t x)
number_unsigned_t remove_sign (number_integer_t x) noexcept
void dump_escaped (const string_t &s, const bool ensure_ascii)
dump escaped string
unsigned int count_digits (number_unsigned_t x) noexcept
count digits
template<typename NumberType , detail::enable_if_t< std::is_same< NumberType, number_unsigned_t >::value or std::is_same< NumberType, number_integer_t >::value, int > = 0>
void dump_integer (NumberType x)
dump an integer
void dump_float (number_float_t x)
dump a floating-point number
void dump_float (number_float_t x, std::true_type)
void dump_float (number_float_t x, std::false_type)
number_unsigned_t remove_sign (number_unsigned_t x)
number_unsigned_t remove_sign (number_integer_t x) noexcept
Static Private Member Functions
static std::uint8_t decode (std::uint8_t &state, std::uint32_t &codep, const std::uint8_t byte) noexcept
check whether a string is UTF-8 encoded
static std::uint8_t decode (std::uint8_t &state, std::uint32_t &codep, const std::uint8_t byte) noexcept
check whether a string is UTF-8 encoded
Private Attributes
output_adapter_t< char > o = nullptr
the output of the serializer
std::array< char, 64 > number_buffer {{}}
a (hopefully) large enough character buffer
const std::lconv * loc = nullptr
the locale
const char thousands_sep = '\0'
the locale's thousand separator character
const char decimal_point = '\0'
the locale's decimal point character
std::array< char, 512 > string_buffer {{}}
string buffer
const char indent_char
the indentation character
string_t indent_string
the indentation string
const error_handler_t error_handler
error_handler how to react on decoding errors
Static Private Attributes
static constexpr std::uint8_t UTF8_ACCEPT = 0
static constexpr std::uint8_t UTF8_REJECT = 1
Detailed Description
template<typename BasicJsonType>
class nlohmann::detail::serializer< BasicJsonType >
Definition at line 42 of file serializer.hpp.
Member Typedef Documentation
number_float_t [1/2]
template<typename BasicJsonType > using nlohmann::detail::serializer< BasicJsonType >::number_float_t = typename BasicJsonType::number_float_t private
Definition at line 45 of file serializer.hpp.
number_float_t [2/2]
template<typename BasicJsonType > using nlohmann::detail::serializer< BasicJsonType >::number_float_t = typename BasicJsonType::number_float_t private
Definition at line 13790 of file json.hpp.
number_integer_t [1/2]
template<typename BasicJsonType > using nlohmann::detail::serializer< BasicJsonType >::number_integer_t = typename BasicJsonType::number_integer_t private
Definition at line 46 of file serializer.hpp.
number_integer_t [2/2]
template<typename BasicJsonType > using nlohmann::detail::serializer< BasicJsonType >::number_integer_t = typename BasicJsonType::number_integer_t private
Definition at line 13791 of file json.hpp.
number_unsigned_t [1/2]
template<typename BasicJsonType > using nlohmann::detail::serializer< BasicJsonType >::number_unsigned_t = typename BasicJsonType::number_unsigned_t private
Definition at line 47 of file serializer.hpp.
number_unsigned_t [2/2]
template<typename BasicJsonType > using nlohmann::detail::serializer< BasicJsonType >::number_unsigned_t = typename BasicJsonType::number_unsigned_t private
Definition at line 13792 of file json.hpp.
string_t [1/2]
template<typename BasicJsonType > using nlohmann::detail::serializer< BasicJsonType >::string_t = typename BasicJsonType::string_t private
Definition at line 44 of file serializer.hpp.
string_t [2/2]
template<typename BasicJsonType > using nlohmann::detail::serializer< BasicJsonType >::string_t = typename BasicJsonType::string_t private
Definition at line 13789 of file json.hpp.
Constructor & Destructor Documentation
serializer() [1/6]
template<typename BasicJsonType > nlohmann::detail::serializer< BasicJsonType >::serializer (output_adapter_t< char > s, const char ichar, error_handler_t error_handler_ = error_handler_t::strict) inline
Parameters
[in] s output stream to serialize to
[in] ichar indentation character to use
[in] error_handler_ how to react on decoding errors
Definition at line 57 of file serializer.hpp.
         : o(std::move(s))
         , loc(std::localeconv())
         , thousands_sep(loc->thousands_sep == nullptr ? '\0' : * (loc->thousands_sep))
         , decimal_point(loc->decimal_point == nullptr ? '\0' : * (loc->decimal_point))
         , indent_char(ichar)
         , indent_string(512, indent_char)
         , error_handler(error_handler_)
     {}
serializer() [2/6]
template<typename BasicJsonType > nlohmann::detail::serializer< BasicJsonType >::serializer (const serializer< BasicJsonType > &) delete
serializer() [3/6]
template<typename BasicJsonType > nlohmann::detail::serializer< BasicJsonType >::serializer (serializer< BasicJsonType > &&) delete
~serializer() [1/2]
template<typename BasicJsonType > nlohmann::detail::serializer< BasicJsonType >::~serializer () default
serializer() [4/6]
template<typename BasicJsonType > nlohmann::detail::serializer< BasicJsonType >::serializer (output_adapter_t< char > s, const char ichar, error_handler_t error_handler_ = error_handler_t::strict) inline
Parameters
[in] s output stream to serialize to
[in] ichar indentation character to use
[in] error_handler_ how to react on decoding errors
Definition at line 13802 of file json.hpp.
         : o(std::move(s))
         , loc(std::localeconv())
         , thousands_sep(loc->thousands_sep == nullptr ? '\0' : * (loc->thousands_sep))
         , decimal_point(loc->decimal_point == nullptr ? '\0' : * (loc->decimal_point))
         , indent_char(ichar)
         , indent_string(512, indent_char)
         , error_handler(error_handler_)
     {}
serializer() [5/6]
template<typename BasicJsonType > nlohmann::detail::serializer< BasicJsonType >::serializer (const serializer< BasicJsonType > &) delete
serializer() [6/6]
template<typename BasicJsonType > nlohmann::detail::serializer< BasicJsonType >::serializer (serializer< BasicJsonType > &&) delete
~serializer() [2/2]
template<typename BasicJsonType > nlohmann::detail::serializer< BasicJsonType >::~serializer () default
Member Function Documentation
count_digits() [1/2]
template<typename BasicJsonType > unsigned int nlohmann::detail::serializer< BasicJsonType >::count_digits (number_unsigned_t x) inline private noexcept
count digits
Count the number of decimal (base 10) digits for an input unsigned integer.
Parameters
[in] x unsigned integer number to count its digits
Returns
number of decimal digits
Definition at line 558 of file serializer.hpp.
     {
         unsigned int n_digits = 1;
         for (;;)
         {
             if (x < 10)
             {
                 return n_digits;
             }
             if (x < 100)
             {
                 return n_digits + 1;
             }
             if (x < 1000)
             {
                 return n_digits + 2;
             }
             if (x < 10000)
             {
                 return n_digits + 3;
             }
             x = x / 10000u;
             n_digits += 4;
         }
     }
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump_integer().
count_digits() [2/2]
template<typename BasicJsonType > unsigned int nlohmann::detail::serializer< BasicJsonType >::count_digits (number_unsigned_t x) inline private noexcept
count digits
Count the number of decimal (base 10) digits for an input unsigned integer.
Parameters
[in] x unsigned integer number to count its digits
Returns
number of decimal digits
Definition at line 14303 of file json.hpp.
     {
         unsigned int n_digits = 1;
         for (;;)
         {
             if (x < 10)
             {
                 return n_digits;
             }
             if (x < 100)
             {
                 return n_digits + 1;
             }
             if (x < 1000)
             {
                 return n_digits + 2;
             }
             if (x < 10000)
             {
                 return n_digits + 3;
             }
             x = x / 10000u;
             n_digits += 4;
         }
     }
decode() [1/2]
template<typename BasicJsonType > static std::uint8_t nlohmann::detail::serializer< BasicJsonType >::decode (std::uint8_t & state, std::uint32_t & codep, const std::uint8_t byte) inline static private noexcept
check whether a string is UTF-8 encoded
The function checks each byte of a string whether it is UTF-8 encoded. The result of the check is stored in the state parameter. The function must be called initially with state 0 (accept). State 1 means the string must be rejected, because the current byte is not allowed. If the string is completely processed, but the state is non-zero, the string ended prematurely; that is, the last byte indicated more bytes should have followed.
Parameters
[in,out] state the state of the decoding
[in,out] codep codepoint (valid only if resulting state is UTF8_ACCEPT)
[in] byte next byte to decode
Returns
new state
Note
The function has been edited: a std::array is used.
Copyright
Copyright (c) 2008-2009 Bjoern Hoehrmann bjoer.nosp@m.n@ho.nosp@m.ehrma.nosp@m.nn.d.nosp@m.e
See also
http://bjoern.hoehrmann.de/utf-8/decoder/dfa/
Definition at line 782 of file serializer.hpp.
     {
         static const std::array<std::uint8_t, 400> utf8d =
         {
             {
                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 00..1F
                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 20..3F
                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 40..5F
                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 60..7F
                 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, // 80..9F
                 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, // A0..BF
                 8, 8, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, // C0..DF
                 0xA, 0x3, 0x3, 0x3, 0x3, 0x3, 0x3, 0x3, 0x3, 0x3, 0x3, 0x3, 0x3, 0x4, 0x3, 0x3, // E0..EF
                 0xB, 0x6, 0x6, 0x6, 0x5, 0x8, 0x8, 0x8, 0x8, 0x8, 0x8, 0x8, 0x8, 0x8, 0x8, 0x8, // F0..FF
                 0x0, 0x1, 0x2, 0x3, 0x5, 0x8, 0x7, 0x1, 0x1, 0x1, 0x4, 0x6, 0x1, 0x1, 0x1, 0x1, // s0..s0
                 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, // s1..s2
                 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, // s3..s4
                 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 3, 1, 1, 1, 1, 1, 1, // s5..s6
                 1, 3, 1, 1, 1, 1, 1, 3, 1, 3, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 // s7..s8
             }
         };
         const std::uint8_t type = utf8d[byte];
         codep = (state != UTF8_ACCEPT)
                 ? (byte & 0x3fu) | (codep << 6u)
                 : (0xFFu >> type) & (byte);
         state = utf8d[256u + state * 16u + type];
         return state;
     }
References nlohmann::detail::serializer< BasicJsonType >::UTF8_ACCEPT.
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump_escaped().
decode() [2/2]
template<typename BasicJsonType > static std::uint8_t nlohmann::detail::serializer< BasicJsonType >::decode (std::uint8_t & state, std::uint32_t & codep, const std::uint8_t byte) inline static private noexcept
check whether a string is UTF-8 encoded
The function checks each byte of a string whether it is UTF-8 encoded. The result of the check is stored in the state parameter. The function must be called initially with state 0 (accept). State 1 means the string must be rejected, because the current byte is not allowed. If the string is completely processed, but the state is non-zero, the string ended prematurely; that is, the last byte indicated more bytes should have followed.
Parameters
[in,out] state the state of the decoding
[in,out] codep codepoint (valid only if resulting state is UTF8_ACCEPT)
[in] byte next byte to decode
Returns
new state
Note
The function has been edited: a std::array is used.
Copyright
Copyright (c) 2008-2009 Bjoern Hoehrmann bjoer.nosp@m.n@ho.nosp@m.ehrma.nosp@m.nn.d.nosp@m.e
See also
http://bjoern.hoehrmann.de/utf-8/decoder/dfa/
Definition at line 14527 of file json.hpp.
     {
         static const std::array<std::uint8_t, 400> utf8d =
         {
             {
                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 00..1F
                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 20..3F
                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 40..5F
                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 60..7F
                 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, // 80..9F
                 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, // A0..BF
                 8, 8, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, // C0..DF
                 0xA, 0x3, 0x3, 0x3, 0x3, 0x3, 0x3, 0x3, 0x3, 0x3, 0x3, 0x3, 0x3, 0x4, 0x3, 0x3, // E0..EF
                 0xB, 0x6, 0x6, 0x6, 0x5, 0x8, 0x8, 0x8, 0x8, 0x8, 0x8, 0x8, 0x8, 0x8, 0x8, 0x8, // F0..FF
                 0x0, 0x1, 0x2, 0x3, 0x5, 0x8, 0x7, 0x1, 0x1, 0x1, 0x4, 0x6, 0x1, 0x1, 0x1, 0x1, // s0..s0
                 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, // s1..s2
                 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, // s3..s4
                 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 3, 1, 1, 1, 1, 1, 1, // s5..s6
                 1, 3, 1, 1, 1, 1, 1, 3, 1, 3, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 // s7..s8
             }
         };
         const std::uint8_t type = utf8d[byte];
         codep = (state != UTF8_ACCEPT)
                 ? (byte & 0x3fu) | (codep << 6u)
                 : (0xFFu >> type) & (byte);
         state = utf8d[256u + state * 16u + type];
         return state;
     }
References nlohmann::detail::serializer< BasicJsonType >::UTF8_ACCEPT.
dump() [1/2]
template<typename BasicJsonType > void nlohmann::detail::serializer< BasicJsonType >::dump (const BasicJsonType & val, const bool pretty_print, const bool ensure_ascii, const unsigned int indent_step, const unsigned int current_indent = 0) inline
internal implementation of the serialization function
This function is called by the public member function dump and organizes the serialization internally. The indentation level is propagated as additional parameter. In case of arrays and objects, the function is called recursively.
strings and object keys are escaped using escape_string()
integer numbers are converted implicitly via operator<<
floating-point numbers are converted to a string using "%g" format
Parameters
[in] val value to serialize
[in] pretty_print whether the output shall be pretty-printed
[in] indent_step the indent level
[in] current_indent the current indent level (only used internally)
Definition at line 92 of file serializer.hpp.
     {
         switch (val.m_type)
         {
             case value_t::object:
             {
                 if (val.m_value.object->empty())
                 {
                     o->write_characters("{}", 2);
                     return;
                 }
                 if (pretty_print)
                 {
                     o->write_characters("{\n", 2);
                     // variable to hold indentation for recursive calls
                     const auto new_indent = current_indent + indent_step;
                     if (JSON_HEDLEY_UNLIKELY(indent_string.size() < new_indent))
                     {
                         indent_string.resize(indent_string.size() * 2, ' ');
                     }
                     // first n-1 elements
                     auto i = val.m_value.object->cbegin();
                     for (std::size_t cnt = 0; cnt < val.m_value.object->size() - 1; ++cnt, ++i)
                     {
                         o->write_characters(indent_string.c_str(), new_indent);
                         o->write_character('\"');
                         dump_escaped(i->first, ensure_ascii);
                         o->write_characters("\": ", 3);
                         dump(i->second, true, ensure_ascii, indent_step, new_indent);
                         o->write_characters(",\n", 2);
                     }
                     // last element
                     assert(i != val.m_value.object->cend());
                     assert(std::next(i) == val.m_value.object->cend());
                     o->write_characters(indent_string.c_str(), new_indent);
                     o->write_character('\"');
                     dump_escaped(i->first, ensure_ascii);
                     o->write_characters("\": ", 3);
                     dump(i->second, true, ensure_ascii, indent_step, new_indent);
                     o->write_character('\n');
                     o->write_characters(indent_string.c_str(), current_indent);
                     o->write_character('}');
                 }
                 else
                 {
                     o->write_character('{');
                     // first n-1 elements
                     auto i = val.m_value.object->cbegin();
                     for (std::size_t cnt = 0; cnt < val.m_value.object->size() - 1; ++cnt, ++i)
                     {
                         o->write_character('\"');
                         dump_escaped(i->first, ensure_ascii);
                         o->write_characters("\":", 2);
                         dump(i->second, false, ensure_ascii, indent_step, current_indent);
                         o->write_character(',');
                     }
                     // last element
                     assert(i != val.m_value.object->cend());
                     assert(std::next(i) == val.m_value.object->cend());
                     o->write_character('\"');
                     dump_escaped(i->first, ensure_ascii);
                     o->write_characters("\":", 2);
                     dump(i->second, false, ensure_ascii, indent_step, current_indent);
                     o->write_character('}');
                 }
                 return;
             }
             case value_t::array:
             {
                 if (val.m_value.array->empty())
                 {
                     o->write_characters("[]", 2);
                     return;
                 }
                 if (pretty_print)
                 {
                     o->write_characters("[\n", 2);
                     // variable to hold indentation for recursive calls
                     const auto new_indent = current_indent + indent_step;
                     if (JSON_HEDLEY_UNLIKELY(indent_string.size() < new_indent))
                     {
                         indent_string.resize(indent_string.size() * 2, ' ');
                     }
                     // first n-1 elements
                     for (auto i = val.m_value.array->cbegin();
                             i != val.m_value.array->cend() - 1; ++i)
                     {
                         o->write_characters(indent_string.c_str(), new_indent);
                         dump(*i, true, ensure_ascii, indent_step, new_indent);
                         o->write_characters(",\n", 2);
                     }
                     // last element
                     assert(not val.m_value.array->empty());
                     o->write_characters(indent_string.c_str(), new_indent);
                     dump(val.m_value.array->back(), true, ensure_ascii, indent_step, new_indent);
                     o->write_character('\n');
                     o->write_characters(indent_string.c_str(), current_indent);
                     o->write_character(']');
                 }
                 else
                 {
                     o->write_character('[');
                     // first n-1 elements
                     for (auto i = val.m_value.array->cbegin();
                             i != val.m_value.array->cend() - 1; ++i)
                     {
                         dump(*i, false, ensure_ascii, indent_step, current_indent);
                         o->write_character(',');
                     }
                     // last element
                     assert(not val.m_value.array->empty());
                     dump(val.m_value.array->back(), false, ensure_ascii, indent_step, current_indent);
                     o->write_character(']');
                 }
                 return;
             }
             case value_t::string:
             {
                 o->write_character('\"');
                 dump_escaped(*val.m_value.string, ensure_ascii);
                 o->write_character('\"');
                 return;
             }
             case value_t::boolean:
             {
                 if (val.m_value.boolean)
                 {
                     o->write_characters("true", 4);
                 }
                 else
                 {
                     o->write_characters("false", 5);
                 }
                 return;
             }
             case value_t::number_integer:
             {
                 dump_integer(val.m_value.number_integer);
                 return;
             }
             case value_t::number_unsigned:
             {
                 dump_integer(val.m_value.number_unsigned);
                 return;
             }
             case value_t::number_float:
             {
                 dump_float(val.m_value.number_float);
                 return;
             }
             case value_t::discarded:
             {
                 o->write_characters("<discarded>", 11);
                 return;
             }
             case value_t::null:
             {
                 o->write_characters("null", 4);
                 return;
             }
             default:            // LCOV_EXCL_LINE
                 assert(false);  // LCOV_EXCL_LINE
         }
     }
References nlohmann::detail::array, assert(), nlohmann::detail::boolean, nlohmann::detail::discarded, nlohmann::detail::serializer< BasicJsonType >::dump_escaped(), nlohmann::detail::serializer< BasicJsonType >::dump_float(), nlohmann::detail::serializer< BasicJsonType >::dump_integer(), nlohmann::detail::serializer< BasicJsonType >::indent_string, JSON_HEDLEY_UNLIKELY, nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::serializer< BasicJsonType >::o, nlohmann::detail::object, and nlohmann::detail::string.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::dump(), and nlohmann::detail::serializer< BasicJsonType >::dump().
dump() [2/2]
template<typename BasicJsonType > void nlohmann::detail::serializer< BasicJsonType >::dump (const BasicJsonType & val, const bool pretty_print, const bool ensure_ascii, const unsigned int indent_step, const unsigned int current_indent = 0) inline
internal implementation of the serialization function
This function is called by the public member function dump and organizes the serialization internally. The indentation level is propagated as additional parameter. In case of arrays and objects, the function is called recursively.
strings and object keys are escaped using escape_string()
integer numbers are converted implicitly via operator<<
floating-point numbers are converted to a string using "%g" format
Parameters
[in] val value to serialize
[in] pretty_print whether the output shall be pretty-printed
[in] indent_step the indent level
[in] current_indent the current indent level (only used internally)
Definition at line 13837 of file json.hpp.
     {
         switch (val.m_type)
         {
             case value_t::object:
             {
                 if (val.m_value.object->empty())
                 {
                     o->write_characters("{}", 2);
                     return;
                 }
                 if (pretty_print)
                 {
                     o->write_characters("{\n", 2);
                     // variable to hold indentation for recursive calls
                     const auto new_indent = current_indent + indent_step;
                     if (JSON_HEDLEY_UNLIKELY(indent_string.size() < new_indent))
                     {
                         indent_string.resize(indent_string.size() * 2, ' ');
                     }
                     // first n-1 elements
                     auto i = val.m_value.object->cbegin();
                     for (std::size_t cnt = 0; cnt < val.m_value.object->size() - 1; ++cnt, ++i)
                     {
                         o->write_characters(indent_string.c_str(), new_indent);
                         o->write_character('\"');
                         dump_escaped(i->first, ensure_ascii);
                         o->write_characters("\": ", 3);
                         dump(i->second, true, ensure_ascii, indent_step, new_indent);
                         o->write_characters(",\n", 2);
                     }
                     // last element
                     assert(i != val.m_value.object->cend());
                     assert(std::next(i) == val.m_value.object->cend());
                     o->write_characters(indent_string.c_str(), new_indent);
                     o->write_character('\"');
                     dump_escaped(i->first, ensure_ascii);
                     o->write_characters("\": ", 3);
                     dump(i->second, true, ensure_ascii, indent_step, new_indent);
                     o->write_character('\n');
                     o->write_characters(indent_string.c_str(), current_indent);
                     o->write_character('}');
                 }
                 else
                 {
                     o->write_character('{');
                     // first n-1 elements
                     auto i = val.m_value.object->cbegin();
                     for (std::size_t cnt = 0; cnt < val.m_value.object->size() - 1; ++cnt, ++i)
                     {
                         o->write_character('\"');
                         dump_escaped(i->first, ensure_ascii);
                         o->write_characters("\":", 2);
                         dump(i->second, false, ensure_ascii, indent_step, current_indent);
                         o->write_character(',');
                     }
                     // last element
                     assert(i != val.m_value.object->cend());
                     assert(std::next(i) == val.m_value.object->cend());
                     o->write_character('\"');
                     dump_escaped(i->first, ensure_ascii);
                     o->write_characters("\":", 2);
                     dump(i->second, false, ensure_ascii, indent_step, current_indent);
                     o->write_character('}');
                 }
                 return;
             }
             case value_t::array:
             {
                 if (val.m_value.array->empty())
                 {
                     o->write_characters("[]", 2);
                     return;
                 }
                 if (pretty_print)
                 {
                     o->write_characters("[\n", 2);
                     // variable to hold indentation for recursive calls
                     const auto new_indent = current_indent + indent_step;
                     if (JSON_HEDLEY_UNLIKELY(indent_string.size() < new_indent))
                     {
                         indent_string.resize(indent_string.size() * 2, ' ');
                     }
                     // first n-1 elements
                     for (auto i = val.m_value.array->cbegin();
                             i != val.m_value.array->cend() - 1; ++i)
                     {
                         o->write_characters(indent_string.c_str(), new_indent);
                         dump(*i, true, ensure_ascii, indent_step, new_indent);
                         o->write_characters(",\n", 2);
                     }
                     // last element
                     assert(not val.m_value.array->empty());
                     o->write_characters(indent_string.c_str(), new_indent);
                     dump(val.m_value.array->back(), true, ensure_ascii, indent_step, new_indent);
                     o->write_character('\n');
                     o->write_characters(indent_string.c_str(), current_indent);
                     o->write_character(']');
                 }
                 else
                 {
                     o->write_character('[');
                     // first n-1 elements
                     for (auto i = val.m_value.array->cbegin();
                             i != val.m_value.array->cend() - 1; ++i)
                     {
                         dump(*i, false, ensure_ascii, indent_step, current_indent);
                         o->write_character(',');
                     }
                     // last element
                     assert(not val.m_value.array->empty());
                     dump(val.m_value.array->back(), false, ensure_ascii, indent_step, current_indent);
                     o->write_character(']');
                 }
                 return;
             }
             case value_t::string:
             {
                 o->write_character('\"');
                 dump_escaped(*val.m_value.string, ensure_ascii);
                 o->write_character('\"');
                 return;
             }
             case value_t::boolean:
             {
                 if (val.m_value.boolean)
                 {
                     o->write_characters("true", 4);
                 }
                 else
                 {
                     o->write_characters("false", 5);
                 }
                 return;
             }
             case value_t::number_integer:
             {
                 dump_integer(val.m_value.number_integer);
                 return;
             }
             case value_t::number_unsigned:
             {
                 dump_integer(val.m_value.number_unsigned);
                 return;
             }
             case value_t::number_float:
             {
                 dump_float(val.m_value.number_float);
                 return;
             }
             case value_t::discarded:
             {
                 o->write_characters("<discarded>", 11);
                 return;
             }
             case value_t::null:
             {
                 o->write_characters("null", 4);
                 return;
             }
             default:            // LCOV_EXCL_LINE
                 assert(false);  // LCOV_EXCL_LINE
         }
     }
References nlohmann::detail::array, assert(), nlohmann::detail::boolean, nlohmann::detail::discarded, nlohmann::detail::serializer< BasicJsonType >::dump(), nlohmann::detail::serializer< BasicJsonType >::dump_escaped(), nlohmann::detail::serializer< BasicJsonType >::dump_float(), nlohmann::detail::serializer< BasicJsonType >::dump_integer(), nlohmann::detail::serializer< BasicJsonType >::indent_string, JSON_HEDLEY_UNLIKELY, nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::serializer< BasicJsonType >::o, nlohmann::detail::object, and nlohmann::detail::string.
dump_escaped() [1/2]
template<typename BasicJsonType > void nlohmann::detail::serializer< BasicJsonType >::dump_escaped (const string_t & s, const bool ensure_ascii) inline private
dump escaped string
Escape a string by replacing certain special characters by a sequence of an escape character (backslash) and another character and other control characters by a sequence of "\u" followed by a four-digit hex representation. The escaped string is written to output stream o.
Parameters
[in] s the string to escape
[in] ensure_ascii whether to escape non-ASCII characters with \uXXXX sequences
@complexity Linear in the length of string s.
Definition at line 302 of file serializer.hpp.
     {
         std::uint32_t codepoint;
         std::uint8_t state = UTF8_ACCEPT;
         std::size_t bytes = 0;  // number of bytes written to string_buffer
         // number of bytes written at the point of the last valid byte
         std::size_t bytes_after_last_accept = 0;
         std::size_t undumped_chars = 0;
         for (std::size_t i = 0; i < s.size(); ++i)
         {
             const auto byte = static_cast<uint8_t>(s[i]);
             switch (decode(state, codepoint, byte))
             {
                 case UTF8_ACCEPT:  // decode found a new code point
                 {
                     switch (codepoint)
                     {
                         case 0x08: // backspace
{
                             string_buffer[bytes++] = '\\';
                             string_buffer[bytes++] = 'b';
                             break;
                         }
                         case 0x09: // horizontal tab
{
                             string_buffer[bytes++] = '\\';
                             string_buffer[bytes++] = 't';
                             break;
                         }
                         case 0x0A: // newline
{
                             string_buffer[bytes++] = '\\';
                             string_buffer[bytes++] = 'n';
                             break;
                         }
                         case 0x0C: // formfeed
{
                             string_buffer[bytes++] = '\\';
                             string_buffer[bytes++] = 'f';
                             break;
                         }
                         case 0x0D: // carriage return
{
                             string_buffer[bytes++] = '\\';
                             string_buffer[bytes++] = 'r';
                             break;
                         }
                         case 0x22: // quotation mark
{
                             string_buffer[bytes++] = '\\';
                             string_buffer[bytes++] = '\"';
                             break;
                         }
                         case 0x5C: // reverse solidus
{
                             string_buffer[bytes++] = '\\';
                             string_buffer[bytes++] = '\\';
                             break;
                         }
                         default:
{
                             // escape control characters (0x00..0x1F) or, if
                             // ensure_ascii parameter is used, non-ASCII characters
                             if ((codepoint <= 0x1F) or (ensure_ascii and (codepoint >= 0x7F)))
{
                                 if (codepoint <= 0xFFFF)
{
                                     (std::snprintf)(string_buffer.data() + bytes, 7, "\\u%04x",
                                                     static_cast<std::uint16_t>(codepoint));
                                     bytes += 6;
                                 }
                                 else
{
                                     (std::snprintf)(string_buffer.data() + bytes, 13, "\\u%04x\\u%04x",
                                                     static_cast<std::uint16_t>(0xD7C0u + (codepoint >> 10u)),
                                                     static_cast<std::uint16_t>(0xDC00u + (codepoint & 0x3FFu)));
                                     bytes += 12;
                                 }
                             }
                             else
{
                                 // copy byte to buffer (all previous bytes
                                 // been copied have in default case above)
                                 string_buffer[bytes++] = s[i];
                             }
                             break;
                         }
                     }
                     // write buffer and reset index; there must be 13 bytes
                     // left, as this is the maximal number of bytes to be
                     // written ("\uxxxx\uxxxx\0") for one code point
                     if (string_buffer.size() - bytes < 13)
                     {
                         o->write_characters(string_buffer.data(), bytes);
                         bytes = 0;
                     }
                     // remember the byte position of this accept
                     bytes_after_last_accept = bytes;
                     undumped_chars = 0;
                     break;
                 }
                 case UTF8_REJECT:  // decode found invalid UTF-8 byte
                 {
                     switch (error_handler)
                     {
                         case error_handler_t::strict:
{
                             std::string sn(3, '\0');
                             (std::snprintf)(&sn[0], sn.size(), "%.2X", byte);
                             JSON_THROW(type_error::create(316, "invalid UTF-8 byte at index " + std::to_string(i) + ": 0x" + sn));
                         }
                         case error_handler_t::ignore:
                         case error_handler_t::replace:
{
                             // in case we saw this character the first time, we
                             // would like to read it again, because the byte
                             // may be OK for itself, but just not OK for the
                             // previous sequence
                             if (undumped_chars > 0)
{
                                 --i;
                             }
                             // reset length buffer to the last accepted index;
                             // thus removing/ignoring the invalid characters
                             bytes = bytes_after_last_accept;
                             if (error_handler == error_handler_t::replace)
{
                                 // add a replacement character
                                 if (ensure_ascii)
{
                                     string_buffer[bytes++] = '\\';
                                     string_buffer[bytes++] = 'u';
                                     string_buffer[bytes++] = 'f';
                                     string_buffer[bytes++] = 'f';
                                     string_buffer[bytes++] = 'f';
                                     string_buffer[bytes++] = 'd';
                                 }
                                 else
{
                                     string_buffer[bytes++] = detail::binary_writer<BasicJsonType, char>::to_char_type('\xEF');
                                     string_buffer[bytes++] = detail::binary_writer<BasicJsonType, char>::to_char_type('\xBF');
                                     string_buffer[bytes++] = detail::binary_writer<BasicJsonType, char>::to_char_type('\xBD');
                                 }
                                 // write buffer and reset index; there must be 13 bytes
                                 // left, as this is the maximal number of bytes to be
                                 // written ("\uxxxx\uxxxx\0") for one code point
                                 if (string_buffer.size() - bytes < 13)
{
                                     o->write_characters(string_buffer.data(), bytes);
                                     bytes = 0;
                                 }
                                 bytes_after_last_accept = bytes;
                             }
                             undumped_chars = 0;
                             // continue processing the string
                             state = UTF8_ACCEPT;
                             break;
                         }
                         default:            // LCOV_EXCL_LINE
                             assert(false);  // LCOV_EXCL_LINE
                     }
                     break;
                 }
                 default:  // decode found yet incomplete multi-byte code point
                 {
                     if (not ensure_ascii)
                     {
                         // code point will not be escaped - copy byte to buffer
                         string_buffer[bytes++] = s[i];
                     }
                     ++undumped_chars;
                     break;
                 }
             }
         }
         // we finished processing the string
         if (JSON_HEDLEY_LIKELY(state == UTF8_ACCEPT))
         {
             // write buffer
             if (bytes > 0)
             {
                 o->write_characters(string_buffer.data(), bytes);
             }
         }
         else
         {
             // we finish reading, but do not accept: string was incomplete
             switch (error_handler)
             {
                 case error_handler_t::strict:
                 {
                     std::string sn(3, '\0');
                     (std::snprintf)(&sn[0], sn.size(), "%.2X", static_cast<std::uint8_t>(s.back()));
                     JSON_THROW(type_error::create(316, "incomplete UTF-8 string; last byte: 0x" + sn));
                 }
                 case error_handler_t::ignore:
                 {
                     // write all accepted bytes
                     o->write_characters(string_buffer.data(), bytes_after_last_accept);
                     break;
                 }
                 case error_handler_t::replace:
                 {
                     // write all accepted bytes
                     o->write_characters(string_buffer.data(), bytes_after_last_accept);
                     // add a replacement character
                     if (ensure_ascii)
                     {
                         o->write_characters("\\ufffd", 6);
                     }
                     else
                     {
                         o->write_characters("\xEF\xBF\xBD", 3);
                     }
                     break;
                 }
                 default:            // LCOV_EXCL_LINE
                     assert(false);  // LCOV_EXCL_LINE
             }
         }
     }
References assert(), nlohmann::detail::type_error::create(), nlohmann::detail::serializer< BasicJsonType >::decode(), nlohmann::detail::serializer< BasicJsonType >::error_handler, nlohmann::detail::ignore, JSON_HEDLEY_LIKELY, JSON_THROW, nlohmann::detail::serializer< BasicJsonType >::o, nlohmann::detail::replace, nlohmann::detail::strict, nlohmann::detail::serializer< BasicJsonType >::string_buffer, nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), httplib::to_string(), nlohmann::detail::serializer< BasicJsonType >::UTF8_ACCEPT, and nlohmann::detail::serializer< BasicJsonType >::UTF8_REJECT.
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump().
dump_escaped() [2/2]
template<typename BasicJsonType > void nlohmann::detail::serializer< BasicJsonType >::dump_escaped (const string_t & s, const bool ensure_ascii) inline private
dump escaped string
Escape a string by replacing certain special characters by a sequence of an escape character (backslash) and another character and other control characters by a sequence of "\u" followed by a four-digit hex representation. The escaped string is written to output stream o.
Parameters
[in] s the string to escape
[in] ensure_ascii whether to escape non-ASCII characters with \uXXXX sequences
@complexity Linear in the length of string s.
Definition at line 14047 of file json.hpp.
     {
         std::uint32_t codepoint;
         std::uint8_t state = UTF8_ACCEPT;
         std::size_t bytes = 0;  // number of bytes written to string_buffer
         // number of bytes written at the point of the last valid byte
         std::size_t bytes_after_last_accept = 0;
         std::size_t undumped_chars = 0;
         for (std::size_t i = 0; i < s.size(); ++i)
         {
             const auto byte = static_cast<uint8_t>(s[i]);
             switch (decode(state, codepoint, byte))
             {
                 case UTF8_ACCEPT:  // decode found a new code point
                 {
                     switch (codepoint)
                     {
                         case 0x08: // backspace
{
                             string_buffer[bytes++] = '\\';
                             string_buffer[bytes++] = 'b';
                             break;
                         }
                         case 0x09: // horizontal tab
{
                             string_buffer[bytes++] = '\\';
                             string_buffer[bytes++] = 't';
                             break;
                         }
                         case 0x0A: // newline
{
                             string_buffer[bytes++] = '\\';
                             string_buffer[bytes++] = 'n';
                             break;
                         }
                         case 0x0C: // formfeed
{
                             string_buffer[bytes++] = '\\';
                             string_buffer[bytes++] = 'f';
                             break;
                         }
                         case 0x0D: // carriage return
{
                             string_buffer[bytes++] = '\\';
                             string_buffer[bytes++] = 'r';
                             break;
                         }
                         case 0x22: // quotation mark
{
                             string_buffer[bytes++] = '\\';
                             string_buffer[bytes++] = '\"';
                             break;
                         }
                         case 0x5C: // reverse solidus
{
                             string_buffer[bytes++] = '\\';
                             string_buffer[bytes++] = '\\';
                             break;
                         }
                         default:
{
                             // escape control characters (0x00..0x1F) or, if
                             // ensure_ascii parameter is used, non-ASCII characters
                             if ((codepoint <= 0x1F) or (ensure_ascii and (codepoint >= 0x7F)))
{
                                 if (codepoint <= 0xFFFF)
{
                                     (std::snprintf)(string_buffer.data() + bytes, 7, "\\u%04x",
                                                     static_cast<std::uint16_t>(codepoint));
                                     bytes += 6;
                                 }
                                 else
{
                                     (std::snprintf)(string_buffer.data() + bytes, 13, "\\u%04x\\u%04x",
                                                     static_cast<std::uint16_t>(0xD7C0u + (codepoint >> 10u)),
                                                     static_cast<std::uint16_t>(0xDC00u + (codepoint & 0x3FFu)));
                                     bytes += 12;
                                 }
                             }
                             else
{
                                 // copy byte to buffer (all previous bytes
                                 // been copied have in default case above)
                                 string_buffer[bytes++] = s[i];
                             }
                             break;
                         }
                     }
                     // write buffer and reset index; there must be 13 bytes
                     // left, as this is the maximal number of bytes to be
                     // written ("\uxxxx\uxxxx\0") for one code point
                     if (string_buffer.size() - bytes < 13)
                     {
                         o->write_characters(string_buffer.data(), bytes);
                         bytes = 0;
                     }
                     // remember the byte position of this accept
                     bytes_after_last_accept = bytes;
                     undumped_chars = 0;
                     break;
                 }
                 case UTF8_REJECT:  // decode found invalid UTF-8 byte
                 {
                     switch (error_handler)
                     {
                         case error_handler_t::strict:
{
                             std::string sn(3, '\0');
                             (std::snprintf)(&sn[0], sn.size(), "%.2X", byte);
                             JSON_THROW(type_error::create(316, "invalid UTF-8 byte at index " + std::to_string(i) + ": 0x" + sn));
                         }
                         case error_handler_t::ignore:
                         case error_handler_t::replace:
{
                             // in case we saw this character the first time, we
                             // would like to read it again, because the byte
                             // may be OK for itself, but just not OK for the
                             // previous sequence
                             if (undumped_chars > 0)
{
                                 --i;
                             }
                             // reset length buffer to the last accepted index;
                             // thus removing/ignoring the invalid characters
                             bytes = bytes_after_last_accept;
                             if (error_handler == error_handler_t::replace)
{
                                 // add a replacement character
                                 if (ensure_ascii)
{
                                     string_buffer[bytes++] = '\\';
                                     string_buffer[bytes++] = 'u';
                                     string_buffer[bytes++] = 'f';
                                     string_buffer[bytes++] = 'f';
                                     string_buffer[bytes++] = 'f';
                                     string_buffer[bytes++] = 'd';
                                 }
                                 else
{
                                     string_buffer[bytes++] = detail::binary_writer<BasicJsonType, char>::to_char_type('\xEF');
                                     string_buffer[bytes++] = detail::binary_writer<BasicJsonType, char>::to_char_type('\xBF');
                                     string_buffer[bytes++] = detail::binary_writer<BasicJsonType, char>::to_char_type('\xBD');
                                 }
                                 // write buffer and reset index; there must be 13 bytes
                                 // left, as this is the maximal number of bytes to be
                                 // written ("\uxxxx\uxxxx\0") for one code point
                                 if (string_buffer.size() - bytes < 13)
{
                                     o->write_characters(string_buffer.data(), bytes);
                                     bytes = 0;
                                 }
                                 bytes_after_last_accept = bytes;
                             }
                             undumped_chars = 0;
                             // continue processing the string
                             state = UTF8_ACCEPT;
                             break;
                         }
                         default:            // LCOV_EXCL_LINE
                             assert(false);  // LCOV_EXCL_LINE
                     }
                     break;
                 }
                 default:  // decode found yet incomplete multi-byte code point
                 {
                     if (not ensure_ascii)
                     {
                         // code point will not be escaped - copy byte to buffer
                         string_buffer[bytes++] = s[i];
                     }
                     ++undumped_chars;
                     break;
                 }
             }
         }
         // we finished processing the string
         if (JSON_HEDLEY_LIKELY(state == UTF8_ACCEPT))
         {
             // write buffer
             if (bytes > 0)
             {
                 o->write_characters(string_buffer.data(), bytes);
             }
         }
         else
         {
             // we finish reading, but do not accept: string was incomplete
             switch (error_handler)
             {
                 case error_handler_t::strict:
                 {
                     std::string sn(3, '\0');
                     (std::snprintf)(&sn[0], sn.size(), "%.2X", static_cast<std::uint8_t>(s.back()));
                     JSON_THROW(type_error::create(316, "incomplete UTF-8 string; last byte: 0x" + sn));
                 }
                 case error_handler_t::ignore:
                 {
                     // write all accepted bytes
                     o->write_characters(string_buffer.data(), bytes_after_last_accept);
                     break;
                 }
                 case error_handler_t::replace:
                 {
                     // write all accepted bytes
                     o->write_characters(string_buffer.data(), bytes_after_last_accept);
                     // add a replacement character
                     if (ensure_ascii)
                     {
                         o->write_characters("\\ufffd", 6);
                     }
                     else
                     {
                         o->write_characters("\xEF\xBF\xBD", 3);
                     }
                     break;
                 }
                 default:            // LCOV_EXCL_LINE
                     assert(false);  // LCOV_EXCL_LINE
             }
         }
     }
References assert(), nlohmann::detail::type_error::create(), nlohmann::detail::serializer< BasicJsonType >::decode(), nlohmann::detail::serializer< BasicJsonType >::error_handler, nlohmann::detail::ignore, JSON_HEDLEY_LIKELY, JSON_THROW, nlohmann::detail::serializer< BasicJsonType >::o, nlohmann::detail::replace, nlohmann::detail::strict, nlohmann::detail::serializer< BasicJsonType >::string_buffer, nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), nlohmann::to_string(), nlohmann::detail::serializer< BasicJsonType >::UTF8_ACCEPT, and nlohmann::detail::serializer< BasicJsonType >::UTF8_REJECT.
dump_float() [1/6]
template<typename BasicJsonType > void nlohmann::detail::serializer< BasicJsonType >::dump_float (number_float_t x) inline private
dump a floating-point number
Dump a given floating-point number to output stream o. Works internally with number_buffer.
Parameters
[in] x floating-point number to dump
Definition at line 683 of file serializer.hpp.
     {
         // NaN / inf
         if (not std::isfinite(x))
         {
             o->write_characters("null", 4);
             return;
         }
         // If number_float_t is an IEEE-754 single or double precision number,
         // use the Grisu2 algorithm to produce short numbers which are
         // guaranteed to round-trip, using strtof and strtod, resp.
         //
         // NB: The test below works if <long double> == <double>.
         static constexpr bool is_ieee_single_or_double
             = (std::numeric_limits<number_float_t>::is_iec559 and std::numeric_limits<number_float_t>::digits == 24 and std::numeric_limits<number_float_t>::max_exponent == 128) or
               (std::numeric_limits<number_float_t>::is_iec559 and std::numeric_limits<number_float_t>::digits == 53 and std::numeric_limits<number_float_t>::max_exponent == 1024);
         dump_float(x, std::integral_constant<bool, is_ieee_single_or_double>());
     }
References nlohmann::detail::serializer< BasicJsonType >::o.
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump(), and nlohmann::detail::serializer< BasicJsonType >::dump_float().
dump_float() [2/6]
template<typename BasicJsonType > void nlohmann::detail::serializer< BasicJsonType >::dump_float (number_float_t x) inline private
dump a floating-point number
Dump a given floating-point number to output stream o. Works internally with number_buffer.
Parameters
[in] x floating-point number to dump
Definition at line 14428 of file json.hpp.
     {
         // NaN / inf
         if (not std::isfinite(x))
         {
             o->write_characters("null", 4);
             return;
         }
         // If number_float_t is an IEEE-754 single or double precision number,
         // use the Grisu2 algorithm to produce short numbers which are
         // guaranteed to round-trip, using strtof and strtod, resp.
         //
         // NB: The test below works if <long double> == <double>.
         static constexpr bool is_ieee_single_or_double
             = (std::numeric_limits<number_float_t>::is_iec559 and std::numeric_limits<number_float_t>::digits == 24 and std::numeric_limits<number_float_t>::max_exponent == 128) or
               (std::numeric_limits<number_float_t>::is_iec559 and std::numeric_limits<number_float_t>::digits == 53 and std::numeric_limits<number_float_t>::max_exponent == 1024);
         dump_float(x, std::integral_constant<bool, is_ieee_single_or_double>());
     }
References nlohmann::detail::serializer< BasicJsonType >::dump_float(), and nlohmann::detail::serializer< BasicJsonType >::o.
dump_float() [3/6]
template<typename BasicJsonType > void nlohmann::detail::serializer< BasicJsonType >::dump_float (number_float_t x, std::false_type) inline private
Definition at line 712 of file serializer.hpp.
     {
         // get number of digits for a float -> text -> float round-trip
         static constexpr auto d = std::numeric_limits<number_float_t>::max_digits10;
         // the actual conversion
         std::ptrdiff_t len = (std::snprintf)(number_buffer.data(), number_buffer.size(), "%.*g", d, x);
         // negative value indicates an error
         assert(len > 0);
         // check if buffer was large enough
         assert(static_cast<std::size_t>(len) < number_buffer.size());
         // erase thousands separator
         if (thousands_sep != '\0')
         {
             const auto end = std::remove(number_buffer.begin(),
                                          number_buffer.begin() + len, thousands_sep);
             std::fill(end, number_buffer.end(), '\0');
             assert((end - number_buffer.begin()) <= len);
             len = (end - number_buffer.begin());
         }
         // convert decimal point to '.'
         if (decimal_point != '\0' and decimal_point != '.')
         {
             const auto dec_pos = std::find(number_buffer.begin(), number_buffer.end(), decimal_point);
             if (dec_pos != number_buffer.end())
             {
                 *dec_pos = '.';
             }
         }
         o->write_characters(number_buffer.data(), static_cast<std::size_t>(len));
         // determine if need to append ".0"
         const bool value_is_int_like =
             std::none_of(number_buffer.begin(), number_buffer.begin() + len + 1,
                          [](char c)
         {
             return c == '.' or c == 'e';
         });
         if (value_is_int_like)
         {
             o->write_characters(".0", 2);
         }
     }
References assert(), c, nlohmann::detail::serializer< BasicJsonType >::decimal_point, nlohmann::detail::serializer< BasicJsonType >::number_buffer, nlohmann::detail::serializer< BasicJsonType >::o, and nlohmann::detail::serializer< BasicJsonType >::thousands_sep.
dump_float() [4/6]
template<typename BasicJsonType > void nlohmann::detail::serializer< BasicJsonType >::dump_float (number_float_t x, std::false_type) inline private
Definition at line 14457 of file json.hpp.
     {
         // get number of digits for a float -> text -> float round-trip
         static constexpr auto d = std::numeric_limits<number_float_t>::max_digits10;
         // the actual conversion
         std::ptrdiff_t len = (std::snprintf)(number_buffer.data(), number_buffer.size(), "%.*g", d, x);
         // negative value indicates an error
         assert(len > 0);
         // check if buffer was large enough
         assert(static_cast<std::size_t>(len) < number_buffer.size());
         // erase thousands separator
         if (thousands_sep != '\0')
         {
             const auto end = std::remove(number_buffer.begin(),
                                          number_buffer.begin() + len, thousands_sep);
             std::fill(end, number_buffer.end(), '\0');
             assert((end - number_buffer.begin()) <= len);
             len = (end - number_buffer.begin());
         }
         // convert decimal point to '.'
         if (decimal_point != '\0' and decimal_point != '.')
         {
             const auto dec_pos = std::find(number_buffer.begin(), number_buffer.end(), decimal_point);
             if (dec_pos != number_buffer.end())
             {
                 *dec_pos = '.';
             }
         }
         o->write_characters(number_buffer.data(), static_cast<std::size_t>(len));
         // determine if need to append ".0"
         const bool value_is_int_like =
             std::none_of(number_buffer.begin(), number_buffer.begin() + len + 1,
                          [](char c)
         {
             return c == '.' or c == 'e';
         });
         if (value_is_int_like)
         {
             o->write_characters(".0", 2);
         }
     }
References assert(), c, nlohmann::detail::serializer< BasicJsonType >::decimal_point, nlohmann::detail::serializer< BasicJsonType >::number_buffer, nlohmann::detail::serializer< BasicJsonType >::o, and nlohmann::detail::serializer< BasicJsonType >::thousands_sep.
dump_float() [5/6]
template<typename BasicJsonType > void nlohmann::detail::serializer< BasicJsonType >::dump_float (number_float_t x, std::true_type) inline private
Definition at line 704 of file serializer.hpp.
     {
         char* begin = number_buffer.data();
         char* end = ::nlohmann::detail::to_chars(begin, begin + number_buffer.size(), x);
         o->write_characters(begin, static_cast<size_t>(end - begin));
     }
References nlohmann::detail::serializer< BasicJsonType >::number_buffer, nlohmann::detail::serializer< BasicJsonType >::o, and nlohmann::detail::to_chars().
dump_float() [6/6]
template<typename BasicJsonType > void nlohmann::detail::serializer< BasicJsonType >::dump_float (number_float_t x, std::true_type) inline private
Definition at line 14449 of file json.hpp.
     {
         char* begin = number_buffer.data();
         char* end = ::nlohmann::detail::to_chars(begin, begin + number_buffer.size(), x);
         o->write_characters(begin, static_cast<size_t>(end - begin));
     }
References nlohmann::detail::serializer< BasicJsonType >::number_buffer, nlohmann::detail::serializer< BasicJsonType >::o, and nlohmann::detail::to_chars().
dump_integer() [1/2]
template<typename BasicJsonType > template<typename NumberType , detail::enable_if_t< std::is_same< NumberType, number_unsigned_t >::value or std::is_same< NumberType, number_integer_t >::value, int > = 0> void nlohmann::detail::serializer< BasicJsonType >::dump_integer (NumberType x) inline private
dump an integer
Dump a given integer to output stream o. Works internally with number_buffer.
Parameters
[in] x integer number (signed or unsigned) to dump
Template Parameters
NumberType either number_integer_t or number_unsigned_t
Definition at line 597 of file serializer.hpp.
     {
         static constexpr std::array<std::array<char, 2>, 100> digits_to_99
         {
             {
                 {{'0', '0'}}, {{'0', '1'}}, {{'0', '2'}}, {{'0', '3'}}, {{'0', '4'}}, {{'0', '5'}}, {{'0', '6'}}, {{'0', '7'}}, {{'0', '8'}}, {{'0', '9'}},
                 {{'1', '0'}}, {{'1', '1'}}, {{'1', '2'}}, {{'1', '3'}}, {{'1', '4'}}, {{'1', '5'}}, {{'1', '6'}}, {{'1', '7'}}, {{'1', '8'}}, {{'1', '9'}},
                 {{'2', '0'}}, {{'2', '1'}}, {{'2', '2'}}, {{'2', '3'}}, {{'2', '4'}}, {{'2', '5'}}, {{'2', '6'}}, {{'2', '7'}}, {{'2', '8'}}, {{'2', '9'}},
                 {{'3', '0'}}, {{'3', '1'}}, {{'3', '2'}}, {{'3', '3'}}, {{'3', '4'}}, {{'3', '5'}}, {{'3', '6'}}, {{'3', '7'}}, {{'3', '8'}}, {{'3', '9'}},
                 {{'4', '0'}}, {{'4', '1'}}, {{'4', '2'}}, {{'4', '3'}}, {{'4', '4'}}, {{'4', '5'}}, {{'4', '6'}}, {{'4', '7'}}, {{'4', '8'}}, {{'4', '9'}},
                 {{'5', '0'}}, {{'5', '1'}}, {{'5', '2'}}, {{'5', '3'}}, {{'5', '4'}}, {{'5', '5'}}, {{'5', '6'}}, {{'5', '7'}}, {{'5', '8'}}, {{'5', '9'}},
                 {{'6', '0'}}, {{'6', '1'}}, {{'6', '2'}}, {{'6', '3'}}, {{'6', '4'}}, {{'6', '5'}}, {{'6', '6'}}, {{'6', '7'}}, {{'6', '8'}}, {{'6', '9'}},
                 {{'7', '0'}}, {{'7', '1'}}, {{'7', '2'}}, {{'7', '3'}}, {{'7', '4'}}, {{'7', '5'}}, {{'7', '6'}}, {{'7', '7'}}, {{'7', '8'}}, {{'7', '9'}},
                 {{'8', '0'}}, {{'8', '1'}}, {{'8', '2'}}, {{'8', '3'}}, {{'8', '4'}}, {{'8', '5'}}, {{'8', '6'}}, {{'8', '7'}}, {{'8', '8'}}, {{'8', '9'}},
                 {{'9', '0'}}, {{'9', '1'}}, {{'9', '2'}}, {{'9', '3'}}, {{'9', '4'}}, {{'9', '5'}}, {{'9', '6'}}, {{'9', '7'}}, {{'9', '8'}}, {{'9', '9'}},
             }
         };
         // special case for "0"
         if (x == 0)
         {
             o->write_character('0');
             return;
         }
         // use a pointer to fill the buffer
         auto buffer_ptr = number_buffer.begin();
         const bool is_negative = std::is_same<NumberType, number_integer_t>::value and not(x >= 0); // see issue #755
         number_unsigned_t abs_value;
         unsigned int n_chars;
         if (is_negative)
         {
             *buffer_ptr = '-';
             abs_value = remove_sign(x);
             // account one more byte for the minus sign
             n_chars = 1 + count_digits(abs_value);
         }
         else
         {
             abs_value = static_cast<number_unsigned_t>(x);
             n_chars = count_digits(abs_value);
         }
         // spare 1 byte for '\0'
         assert(n_chars < number_buffer.size() - 1);
         // jump to the end to generate the string from backward
         // so we later avoid reversing the result
         buffer_ptr += n_chars;
         // Fast int2ascii implementation inspired by "Fastware" talk by Andrei Alexandrescu
         // See: https://www.youtube.com/watch?v=o4-CwDo2zpg
         while (abs_value >= 100)
         {
             const auto digits_index = static_cast<unsigned>((abs_value % 100));
             abs_value /= 100;
             *(--buffer_ptr) = digits_to_99[digits_index][1];
             *(--buffer_ptr) = digits_to_99[digits_index][0];
         }
         if (abs_value >= 10)
         {
             const auto digits_index = static_cast<unsigned>(abs_value);
             *(--buffer_ptr) = digits_to_99[digits_index][1];
             *(--buffer_ptr) = digits_to_99[digits_index][0];
         }
         else
         {
             *(--buffer_ptr) = static_cast<char>('0' + abs_value);
         }
         o->write_characters(number_buffer.data(), n_chars);
     }
References assert(), nlohmann::detail::serializer< BasicJsonType >::count_digits(), nlohmann::detail::serializer< BasicJsonType >::number_buffer, nlohmann::detail::serializer< BasicJsonType >::o, and nlohmann::detail::serializer< BasicJsonType >::remove_sign().
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump().
dump_integer() [2/2]
template<typename BasicJsonType > template<typename NumberType , detail::enable_if_t< std::is_same< NumberType, number_unsigned_t >::value or std::is_same< NumberType, number_integer_t >::value, int > = 0> void nlohmann::detail::serializer< BasicJsonType >::dump_integer (NumberType x) inline private
dump an integer
Dump a given integer to output stream o. Works internally with number_buffer.
Parameters
[in] x integer number (signed or unsigned) to dump
Template Parameters
NumberType either number_integer_t or number_unsigned_t
Definition at line 14342 of file json.hpp.
     {
         static constexpr std::array<std::array<char, 2>, 100> digits_to_99
         {
             {
                 {{'0', '0'}}, {{'0', '1'}}, {{'0', '2'}}, {{'0', '3'}}, {{'0', '4'}}, {{'0', '5'}}, {{'0', '6'}}, {{'0', '7'}}, {{'0', '8'}}, {{'0', '9'}},
                 {{'1', '0'}}, {{'1', '1'}}, {{'1', '2'}}, {{'1', '3'}}, {{'1', '4'}}, {{'1', '5'}}, {{'1', '6'}}, {{'1', '7'}}, {{'1', '8'}}, {{'1', '9'}},
                 {{'2', '0'}}, {{'2', '1'}}, {{'2', '2'}}, {{'2', '3'}}, {{'2', '4'}}, {{'2', '5'}}, {{'2', '6'}}, {{'2', '7'}}, {{'2', '8'}}, {{'2', '9'}},
                 {{'3', '0'}}, {{'3', '1'}}, {{'3', '2'}}, {{'3', '3'}}, {{'3', '4'}}, {{'3', '5'}}, {{'3', '6'}}, {{'3', '7'}}, {{'3', '8'}}, {{'3', '9'}},
                 {{'4', '0'}}, {{'4', '1'}}, {{'4', '2'}}, {{'4', '3'}}, {{'4', '4'}}, {{'4', '5'}}, {{'4', '6'}}, {{'4', '7'}}, {{'4', '8'}}, {{'4', '9'}},
                 {{'5', '0'}}, {{'5', '1'}}, {{'5', '2'}}, {{'5', '3'}}, {{'5', '4'}}, {{'5', '5'}}, {{'5', '6'}}, {{'5', '7'}}, {{'5', '8'}}, {{'5', '9'}},
                 {{'6', '0'}}, {{'6', '1'}}, {{'6', '2'}}, {{'6', '3'}}, {{'6', '4'}}, {{'6', '5'}}, {{'6', '6'}}, {{'6', '7'}}, {{'6', '8'}}, {{'6', '9'}},
                 {{'7', '0'}}, {{'7', '1'}}, {{'7', '2'}}, {{'7', '3'}}, {{'7', '4'}}, {{'7', '5'}}, {{'7', '6'}}, {{'7', '7'}}, {{'7', '8'}}, {{'7', '9'}},
                 {{'8', '0'}}, {{'8', '1'}}, {{'8', '2'}}, {{'8', '3'}}, {{'8', '4'}}, {{'8', '5'}}, {{'8', '6'}}, {{'8', '7'}}, {{'8', '8'}}, {{'8', '9'}},
                 {{'9', '0'}}, {{'9', '1'}}, {{'9', '2'}}, {{'9', '3'}}, {{'9', '4'}}, {{'9', '5'}}, {{'9', '6'}}, {{'9', '7'}}, {{'9', '8'}}, {{'9', '9'}},
             }
         };
         // special case for "0"
         if (x == 0)
         {
             o->write_character('0');
             return;
         }
         // use a pointer to fill the buffer
         auto buffer_ptr = number_buffer.begin();
         const bool is_negative = std::is_same<NumberType, number_integer_t>::value and not(x >= 0); // see issue #755
         number_unsigned_t abs_value;
         unsigned int n_chars;
         if (is_negative)
         {
             *buffer_ptr = '-';
             abs_value = remove_sign(x);
             // account one more byte for the minus sign
             n_chars = 1 + count_digits(abs_value);
         }
         else
         {
             abs_value = static_cast<number_unsigned_t>(x);
             n_chars = count_digits(abs_value);
         }
         // spare 1 byte for '\0'
         assert(n_chars < number_buffer.size() - 1);
         // jump to the end to generate the string from backward
         // so we later avoid reversing the result
         buffer_ptr += n_chars;
         // Fast int2ascii implementation inspired by "Fastware" talk by Andrei Alexandrescu
         // See: https://www.youtube.com/watch?v=o4-CwDo2zpg
         while (abs_value >= 100)
         {
             const auto digits_index = static_cast<unsigned>((abs_value % 100));
             abs_value /= 100;
             *(--buffer_ptr) = digits_to_99[digits_index][1];
             *(--buffer_ptr) = digits_to_99[digits_index][0];
         }
         if (abs_value >= 10)
         {
             const auto digits_index = static_cast<unsigned>(abs_value);
             *(--buffer_ptr) = digits_to_99[digits_index][1];
             *(--buffer_ptr) = digits_to_99[digits_index][0];
         }
         else
         {
             *(--buffer_ptr) = static_cast<char>('0' + abs_value);
         }
         o->write_characters(number_buffer.data(), n_chars);
     }
References assert(), nlohmann::detail::serializer< BasicJsonType >::count_digits(), nlohmann::detail::serializer< BasicJsonType >::number_buffer, nlohmann::detail::serializer< BasicJsonType >::o, and nlohmann::detail::serializer< BasicJsonType >::remove_sign().
operator=() [1/4]
template<typename BasicJsonType > serializer& nlohmann::detail::serializer< BasicJsonType >::operator= (const serializer< BasicJsonType > &) delete
operator=() [2/4]
template<typename BasicJsonType > serializer& nlohmann::detail::serializer< BasicJsonType >::operator= (const serializer< BasicJsonType > &) delete
operator=() [3/4]
template<typename BasicJsonType > serializer& nlohmann::detail::serializer< BasicJsonType >::operator= (serializer< BasicJsonType > &&) delete
operator=() [4/4]
template<typename BasicJsonType > serializer& nlohmann::detail::serializer< BasicJsonType >::operator= (serializer< BasicJsonType > &&) delete
remove_sign() [1/4]
template<typename BasicJsonType > number_unsigned_t nlohmann::detail::serializer< BasicJsonType >::remove_sign (number_integer_t x) inline private noexcept
Definition at line 834 of file serializer.hpp.
     {
         assert(x < 0 and x < (std::numeric_limits<number_integer_t>::max)());
         return static_cast<number_unsigned_t>(-(x + 1)) + 1;
     }
References assert().
remove_sign() [2/4]
template<typename BasicJsonType > number_unsigned_t nlohmann::detail::serializer< BasicJsonType >::remove_sign (number_integer_t x) inline private noexcept
Definition at line 14579 of file json.hpp.
     {
         assert(x < 0 and x < (std::numeric_limits<number_integer_t>::max)());
         return static_cast<number_unsigned_t>(-(x + 1)) + 1;
     }
References assert().
remove_sign() [3/4]
template<typename BasicJsonType > number_unsigned_t nlohmann::detail::serializer< BasicJsonType >::remove_sign (number_unsigned_t x) inline private
Definition at line 819 of file serializer.hpp.
     {
         assert(false); // LCOV_EXCL_LINE
         return x; // LCOV_EXCL_LINE
     }
References assert().
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump_integer().
remove_sign() [4/4]
template<typename BasicJsonType > number_unsigned_t nlohmann::detail::serializer< BasicJsonType >::remove_sign (number_unsigned_t x) inline private
Definition at line 14564 of file json.hpp.
     {
         assert(false); // LCOV_EXCL_LINE
         return x; // LCOV_EXCL_LINE
     }
References assert().
Member Data Documentation
decimal_point
template<typename BasicJsonType > const char nlohmann::detail::serializer< BasicJsonType >::decimal_point = '\0' private
the locale's decimal point character
Definition at line 852 of file serializer.hpp.
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump_float().
error_handler
template<typename BasicJsonType > const error_handler_t nlohmann::detail::serializer< BasicJsonType >::error_handler private
error_handler how to react on decoding errors
Definition at line 863 of file serializer.hpp.
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump_escaped().
indent_char
template<typename BasicJsonType > const char nlohmann::detail::serializer< BasicJsonType >::indent_char private
the indentation character
Definition at line 858 of file serializer.hpp.
indent_string
template<typename BasicJsonType > string_t nlohmann::detail::serializer< BasicJsonType >::indent_string private
the indentation string
Definition at line 860 of file serializer.hpp.
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump().
loc
template<typename BasicJsonType > const std::lconv * nlohmann::detail::serializer< BasicJsonType >::loc = nullptr private
the locale
Definition at line 848 of file serializer.hpp.
number_buffer
template<typename BasicJsonType > std::array< char, 64 > nlohmann::detail::serializer< BasicJsonType >::number_buffer {{}} private
a (hopefully) large enough character buffer
Definition at line 845 of file serializer.hpp.
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump_float(), and nlohmann::detail::serializer< BasicJsonType >::dump_integer().
o
template<typename BasicJsonType > output_adapter_t< char > nlohmann::detail::serializer< BasicJsonType >::o = nullptr private
the output of the serializer
Definition at line 842 of file serializer.hpp.
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump(), nlohmann::detail::serializer< BasicJsonType >::dump_escaped(), nlohmann::detail::serializer< BasicJsonType >::dump_float(), and nlohmann::detail::serializer< BasicJsonType >::dump_integer().
string_buffer
template<typename BasicJsonType > std::array< char, 512 > nlohmann::detail::serializer< BasicJsonType >::string_buffer {{}} private
string buffer
Definition at line 855 of file serializer.hpp.
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump_escaped().
thousands_sep
template<typename BasicJsonType > const char nlohmann::detail::serializer< BasicJsonType >::thousands_sep = '\0' private
the locale's thousand separator character
Definition at line 850 of file serializer.hpp.
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump_float().
UTF8_ACCEPT
template<typename BasicJsonType > static constexpr std::uint8_t nlohmann::detail::serializer< BasicJsonType >::UTF8_ACCEPT = 0 static constexpr private
Definition at line 48 of file serializer.hpp.
Referenced by nlohmann::detail::serializer< BasicJsonType >::decode(), and nlohmann::detail::serializer< BasicJsonType >::dump_escaped().
UTF8_REJECT
template<typename BasicJsonType > static constexpr std::uint8_t nlohmann::detail::serializer< BasicJsonType >::UTF8_REJECT = 1 static constexpr private
Definition at line 49 of file serializer.hpp.
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump_escaped().
The documentation for this class was generated from the following files:
mc_orchestrator/json-3.7.3/include/nlohmann/detail/output/serializer.hpp
mc_orchestrator/json-3.7.3/single_include/nlohmann/json.hpp