Mixed Criticality Orchestrator: fuzzer::Fuzzer Class Reference
fuzzer::Fuzzer Class Reference
#include <FuzzerInternal.h>
Classes
struct Coverage
Public Member Functions
Fuzzer (UserCallback CB, InputCorpus &Corpus, MutationDispatcher &MD, FuzzingOptions Options)
~Fuzzer ()
void Loop ()
void MinimizeCrashLoop (const Unit &U)
void ShuffleAndMinimize (UnitVector *V)
void InitializeTraceState ()
void RereadOutputCorpus (size_t MaxSize)
size_t secondsSinceProcessStartUp ()
bool TimedOut ()
size_t execPerSec ()
size_t getTotalNumberOfRuns ()
void ExecuteCallback (const uint8_t *Data, size_t Size)
size_t RunOne (const uint8_t *Data, size_t Size)
void Merge (const std::vector< std::string > &Corpora)
void CrashResistantMerge (const std::vector< std::string > &Args, const std::vector< std::string > &Corpora)
void CrashResistantMergeInternalStep (const std::string &ControlFilePath)
UnitVector FindExtraUnits (const UnitVector &Initial, const UnitVector &Extra)
MutationDispatcher & GetMD ()
void PrintFinalStats ()
void SetMaxInputLen (size_t MaxInputLen)
void SetMaxMutationLen (size_t MaxMutationLen)
void RssLimitCallback ()
void ResetCoverage ()
bool InFuzzingThread () const
size_t GetCurrentUnitInFuzzingThead (const uint8_t **Data) const
void TryDetectingAMemoryLeak (const uint8_t *Data, size_t Size, bool DuringInitialCorpusExecution)
void HandleMalloc (size_t Size)
Static Public Member Functions
static void StaticAlarmCallback ()
static void StaticCrashSignalCallback ()
static void StaticInterruptCallback ()
Private Member Functions
void AlarmCallback ()
void CrashCallback ()
void InterruptCallback ()
void MutateAndTestOne ()
void ReportNewCoverage (InputInfo *II, const Unit &U)
size_t RunOne (const Unit &U)
void WriteToOutputCorpus (const Unit &U)
void WriteUnitToFileWithPrefix (const Unit &U, const char *Prefix)
void PrintStats (const char *Where, const char *End="\n", size_t Units=0)
void PrintStatusForNewUnit (const Unit &U)
void ShuffleCorpus (UnitVector *V)
void AddToCorpus (const Unit &U)
void CheckExitOnSrcPosOrItem ()
void StartTraceRecording ()
void StopTraceRecording ()
void SetDeathCallback ()
void DumpCurrentUnit (const char *Prefix)
void DeathCallback ()
void ResetEdgeCoverage ()
void ResetCounters ()
void PrepareCounters (Fuzzer::Coverage *C)
bool RecordMaxCoverage (Fuzzer::Coverage *C)
void AllocateCurrentUnitData ()
Static Private Member Functions
static void StaticDeathCallback ()
Private Attributes
uint8_t * CurrentUnitData = nullptr
std::atomic< size_t > CurrentUnitSize
uint8_t BaseSha1 [kSHA1NumBytes]
bool RunningCB = false
size_t TotalNumberOfRuns = 0
size_t NumberOfNewUnitsAdded = 0
bool HasMoreMallocsThanFrees = false
size_t NumberOfLeakDetectionAttempts = 0
UserCallback CB
InputCorpus & Corpus
MutationDispatcher & MD
FuzzingOptions Options
system_clock::time_point ProcessStartTime = system_clock::now()
system_clock::time_point UnitStartTime
system_clock::time_point UnitStopTime
long TimeOfLongestUnitInSeconds = 0
long EpochOfLastReadOfOutputCorpus = 0
Coverage MaxCoverage
size_t MaxInputLen = 0
size_t MaxMutationLen = 0
bool InMergeMode = false
Static Private Attributes
static thread_local bool IsMyThread
Detailed Description
Definition at line 32 of file FuzzerInternal.h.
Constructor & Destructor Documentation
Fuzzer()
fuzzer::Fuzzer::Fuzzer (UserCallback CB, InputCorpus & Corpus, MutationDispatcher & MD, FuzzingOptions Options)
Definition at line 176 of file FuzzerLoop.cpp.
     : CB(CB), Corpus(Corpus), MD(MD), Options(Options) {
   SetDeathCallback();
   InitializeTraceState();
   assert(!F);
   F = this;
   TPC.ResetMaps();
   ResetCoverage();
   IsMyThread = true;
   if (Options.DetectLeaks && EF->__sanitizer_install_malloc_and_free_hooks)
     EF->__sanitizer_install_malloc_and_free_hooks(MallocHook, FreeHook);
   TPC.SetUseCounters(Options.UseCounters);
   TPC.SetUseValueProfile(Options.UseValueProfile);
   TPC.SetPrintNewPCs(Options.PrintNewCovPcs);
   if (Options.Verbosity)
     TPC.PrintModuleInfo();
   if (!Options.OutputCorpus.empty() && Options.ReloadIntervalSec)
     EpochOfLastReadOfOutputCorpus = GetEpoch(Options.OutputCorpus);
   MaxInputLen = MaxMutationLen = Options.MaxLen;
   AllocateCurrentUnitData();
   CurrentUnitSize = 0;
   memset(BaseSha1, 0, sizeof(BaseSha1));
 }
References AllocateCurrentUnitData(), assert(), BaseSha1, CurrentUnitSize, fuzzer::FuzzingOptions::DetectLeaks, fuzzer::EF, EpochOfLastReadOfOutputCorpus, fuzzer::F, fuzzer::FreeHook(), fuzzer::GetEpoch(), InitializeTraceState(), IsMyThread, fuzzer::MallocHook(), MaxInputLen, fuzzer::FuzzingOptions::MaxLen, MaxMutationLen, Options, fuzzer::FuzzingOptions::OutputCorpus, fuzzer::TracePC::PrintModuleInfo(), fuzzer::FuzzingOptions::PrintNewCovPcs, fuzzer::FuzzingOptions::ReloadIntervalSec, ResetCoverage(), fuzzer::TracePC::ResetMaps(), SetDeathCallback(), fuzzer::TracePC::SetPrintNewPCs(), fuzzer::TracePC::SetUseCounters(), fuzzer::TracePC::SetUseValueProfile(), fuzzer::TPC, fuzzer::FuzzingOptions::UseCounters, fuzzer::FuzzingOptions::UseValueProfile, and fuzzer::FuzzingOptions::Verbosity.
~Fuzzer()
fuzzer::Fuzzer::~Fuzzer ()
Definition at line 202 of file FuzzerLoop.cpp.
 { }
Member Function Documentation
AddToCorpus()
void fuzzer::Fuzzer::AddToCorpus (const Unit & U) private
AlarmCallback()
void fuzzer::Fuzzer::AlarmCallback () private
Definition at line 289 of file FuzzerLoop.cpp.
{
   assert(Options.UnitTimeoutSec > 0);
   if (!InFuzzingThread()) return;
   if (!RunningCB)
     return; // We have not started running units yet.
   size_t Seconds =
       duration_cast<seconds>(system_clock::now() - UnitStartTime).count();
   if (Seconds == 0)
     return;
   if (Options.Verbosity >= 2)
     Printf("AlarmCallback %zd\n", Seconds);
   if (Seconds >= (size_t)Options.UnitTimeoutSec) {
     Printf("ALARM: working on the last Unit for %zd seconds\n", Seconds);
     Printf("       and the timeout value is %d (use -timeout=N to change)\n",
            Options.UnitTimeoutSec);
     DumpCurrentUnit("timeout-");
     Printf("==%lu== ERROR: libFuzzer: timeout after %d seconds\n", GetPid(),
            Seconds);
     if (EF->__sanitizer_print_stack_trace)
       EF->__sanitizer_print_stack_trace();
     Printf("SUMMARY: libFuzzer: timeout\n");
     PrintFinalStats();
     _Exit(Options.TimeoutExitCode); // Stop right now.
   }
 }
References assert(), DumpCurrentUnit(), fuzzer::EF, fuzzer::GetPid(), InFuzzingThread(), Options, fuzzer::Printf(), PrintFinalStats(), RunningCB, fuzzer::FuzzingOptions::TimeoutExitCode, UnitStartTime, fuzzer::FuzzingOptions::UnitTimeoutSec, and fuzzer::FuzzingOptions::Verbosity.
Referenced by StaticAlarmCallback().
AllocateCurrentUnitData()
void fuzzer::Fuzzer::AllocateCurrentUnitData () private
Definition at line 204 of file FuzzerLoop.cpp.
{
   if (CurrentUnitData || MaxInputLen == 0) return;
   CurrentUnitData = new uint8_t[MaxInputLen];
 }
References CurrentUnitData, and MaxInputLen.
Referenced by Fuzzer(), and SetMaxInputLen().
CheckExitOnSrcPosOrItem()
void fuzzer::Fuzzer::CheckExitOnSrcPosOrItem () private
Definition at line 405 of file FuzzerLoop.cpp.
{
   if (!Options.ExitOnSrcPos.empty()) {
     static auto *PCsSet = new std::set<uintptr_t>;
     for (size_t i = 1, N = TPC.GetNumPCs(); i < N; i++) {
       uintptr_t PC = TPC.GetPC(i);
       if (!PC) continue;
       if (!PCsSet->insert(PC).second) continue;
       std::string Descr = DescribePC("%L", PC);
       if (Descr.find(Options.ExitOnSrcPos) != std::string::npos) {
         Printf("INFO: found line matching '%s', exiting.\n",
                Options.ExitOnSrcPos.c_str());
         _Exit(0);
       }
     }
   }
   if (!Options.ExitOnItem.empty()) {
     if (Corpus.HasUnit(Options.ExitOnItem)) {
       Printf("INFO: found item with checksum '%s', exiting.\n",
              Options.ExitOnItem.c_str());
       _Exit(0);
     }
   }
 }
References Corpus, fuzzer::DescribePC(), fuzzer::FuzzingOptions::ExitOnItem, fuzzer::FuzzingOptions::ExitOnSrcPos, fuzzer::TracePC::GetNumPCs(), fuzzer::TracePC::GetPC(), fuzzer::InputCorpus::HasUnit(), N, Options, PC, fuzzer::Printf(), and fuzzer::TPC.
Referenced by MutateAndTestOne(), RereadOutputCorpus(), and ShuffleAndMinimize().
CrashCallback()
void fuzzer::Fuzzer::CrashCallback () private
Definition at line 269 of file FuzzerLoop.cpp.
{
   Printf("==%lu== ERROR: libFuzzer: deadly signal\n", GetPid());
   if (EF->__sanitizer_print_stack_trace)
     EF->__sanitizer_print_stack_trace();
   Printf("NOTE: libFuzzer has rudimentary signal handlers.\n"
          "      Combine libFuzzer with AddressSanitizer or similar for better "
          "crash reports.\n");
   Printf("SUMMARY: libFuzzer: deadly signal\n");
   DumpCurrentUnit("crash-");
   PrintFinalStats();
   exit(Options.ErrorExitCode);
 }
References DumpCurrentUnit(), fuzzer::EF, fuzzer::FuzzingOptions::ErrorExitCode, fuzzer::GetPid(), Options, fuzzer::Printf(), and PrintFinalStats().
Referenced by StaticCrashSignalCallback().
CrashResistantMerge()
void fuzzer::Fuzzer::CrashResistantMerge (const std::vector< std::string > & Args, const std::vector< std::string > & Corpora)
Definition at line 210 of file FuzzerMerge.cpp.
{
   if (Corpora.size() <= 1) {
     Printf("Merge requires two or more corpus dirs\n");
     return;
   }
   std::vector<std::string> AllFiles;
   ListFilesInDirRecursive(Corpora[0], nullptr, &AllFiles, /*TopDir*/true);
   size_t NumFilesInFirstCorpus = AllFiles.size();
   for (size_t i = 1; i < Corpora.size(); i++)
     ListFilesInDirRecursive(Corpora[i], nullptr, &AllFiles, /*TopDir*/true);
   Printf("MERGE-OUTER: %zd files, %zd in the initial corpus\n",
          AllFiles.size(), NumFilesInFirstCorpus);
   std::string CFPath =
       "libFuzzerTemp." + std::to_string(GetPid()) + ".txt";
   // Write the control file.
   RemoveFile(CFPath);
   std::ofstream ControlFile(CFPath);
   ControlFile << AllFiles.size() << "\n";
   ControlFile << NumFilesInFirstCorpus << "\n";
   for (auto &Path: AllFiles)
     ControlFile << Path << "\n";
   ControlFile.close();
   // Execute the inner process untill it passes.
   // Every inner process should execute at least one input.
   std::string BaseCmd = CloneArgsWithoutX(Args, "keep-all-flags");
   for (size_t i = 1; i <= AllFiles.size(); i++) {
     Printf("MERGE-OUTER: attempt %zd\n", i);
     auto ExitCode =
         ExecuteCommand(BaseCmd + " -merge_control_file=" + CFPath);
     if (!ExitCode) {
       Printf("MERGE-OUTER: succesfull in %zd attempt(s)\n", i);
       break;
     }
   }
   // Read the control file and do the merge.
   Merger M;
   std::ifstream IF(CFPath);
   M.ParseOrExit(IF, true);
   IF.close();
   std::vector<std::string> NewFiles;
   size_t NumNewFeatures = M.Merge(&NewFiles);
   Printf("MERGE-OUTER: %zd new files with %zd new features added\n",
          NewFiles.size(), NumNewFeatures);
   for (auto &F: NewFiles)
     WriteToOutputCorpus(FileToVector(F));
   // We are done, delete the control file.
   RemoveFile(CFPath);
 }
References fuzzer::CloneArgsWithoutX(), fuzzer::ExecuteCommand(), fuzzer::F, fuzzer::FileToVector(), fuzzer::GetPid(), fuzzer::ListFilesInDirRecursive(), fuzzer::Merger::Merge(), fuzzer::Merger::ParseOrExit(), fuzzer::Printf(), fuzzer::RemoveFile(), httplib::to_string(), and WriteToOutputCorpus().
Referenced by fuzzer::FuzzerDriver().
CrashResistantMergeInternalStep()
void fuzzer::Fuzzer::CrashResistantMergeInternalStep (const std::string & ControlFilePath)
Definition at line 162 of file FuzzerMerge.cpp.
{
   Printf("MERGE-INNER: using the control file '%s'\n", CFPath.c_str());
   Merger M;
   std::ifstream IF(CFPath);
   M.ParseOrExit(IF, false);
   IF.close();
   if (!M.LastFailure.empty())
     Printf("MERGE-INNER: '%s' caused a failure at the previous merge step\n",
            M.LastFailure.c_str());
   Printf("MERGE-INNER: %zd total files;"
          " %zd processed earlier; will process %zd files now\n",
          M.Files.size(), M.FirstNotProcessedFile,
          M.Files.size() - M.FirstNotProcessedFile);
   std::ofstream OF(CFPath, std::ofstream::out | std::ofstream::app);
   for (size_t i = M.FirstNotProcessedFile; i < M.Files.size(); i++) {
     auto U = FileToVector(M.Files[i].Name);
     if (U.size() > MaxInputLen) {
       U.resize(MaxInputLen);
       U.shrink_to_fit();
     }
     std::ostringstream StartedLine;
     // Write the pre-run marker.
     OF << "STARTED " << std::dec << i << " " << U.size() << "\n";
     OF.flush();  // Flush is important since ExecuteCommand may crash.
     // Run.
     TPC.ResetMaps();
     ExecuteCallback(U.data(), U.size());
     // Collect coverage.
     std::set<size_t> Features;
     TPC.CollectFeatures([&](size_t Feature) -> bool {
       Features.insert(Feature);
       return true;
     });
     // Show stats.
     TotalNumberOfRuns++;
     if (!(TotalNumberOfRuns & (TotalNumberOfRuns - 1)))
       PrintStats("pulse ");
     // Write the post-run marker and the coverage.
     OF << "DONE " << i;
     for (size_t F : Features)
       OF << " " << std::hex << F;
     OF << "\n";
   }
 }
References fuzzer::TracePC::CollectFeatures(), ExecuteCallback(), fuzzer::F, fuzzer::Merger::Files, fuzzer::FileToVector(), fuzzer::Merger::FirstNotProcessedFile, fuzzer::Merger::LastFailure, MaxInputLen, fuzzer::Merger::ParseOrExit(), fuzzer::Printf(), PrintStats(), fuzzer::TracePC::ResetMaps(), TotalNumberOfRuns, and fuzzer::TPC.
Referenced by fuzzer::FuzzerDriver().
DeathCallback()
void fuzzer::Fuzzer::DeathCallback () private
Definition at line 249 of file FuzzerLoop.cpp.
{
   DumpCurrentUnit("crash-");
   PrintFinalStats();
 }
References DumpCurrentUnit(), and PrintFinalStats().
Referenced by StaticDeathCallback().
DumpCurrentUnit()
void fuzzer::Fuzzer::DumpCurrentUnit (const char * Prefix) private
Definition at line 234 of file FuzzerLoop.cpp.
{
   WarnOnUnsuccessfullMerge(InMergeMode);
   if (!CurrentUnitData) return;  // Happens when running individual inputs.
   MD.PrintMutationSequence();
   Printf("; base unit: %s\n", Sha1ToString(BaseSha1).c_str());
   size_t UnitSize = CurrentUnitSize;
   if (UnitSize <= kMaxUnitSizeToPrint) {
     PrintHexArray(CurrentUnitData, UnitSize, "\n");
     PrintASCII(CurrentUnitData, UnitSize, "\n");
   }
   WriteUnitToFileWithPrefix({CurrentUnitData, CurrentUnitData + UnitSize},
                             Prefix);
 }
References BaseSha1, CurrentUnitData, CurrentUnitSize, InMergeMode, fuzzer::kMaxUnitSizeToPrint, MD, fuzzer::PrintASCII(), fuzzer::Printf(), fuzzer::PrintHexArray(), fuzzer::MutationDispatcher::PrintMutationSequence(), fuzzer::Sha1ToString(), fuzzer::WarnOnUnsuccessfullMerge(), and WriteUnitToFileWithPrefix().
Referenced by AlarmCallback(), CrashCallback(), DeathCallback(), HandleMalloc(), RssLimitCallback(), and TryDetectingAMemoryLeak().
execPerSec()
size_t fuzzer::Fuzzer::execPerSec () inline
Definition at line 75 of file FuzzerInternal.h.
                       {
     size_t Seconds = secondsSinceProcessStartUp();
     return Seconds ? TotalNumberOfRuns / Seconds : 0;
   }
Referenced by PrintFinalStats(), and PrintStats().
ExecuteCallback()
void fuzzer::Fuzzer::ExecuteCallback (const uint8_t * Data, size_t Size)
Definition at line 527 of file FuzzerLoop.cpp.
{
   assert(InFuzzingThread());
   // We copy the contents of Unit into a separate heap buffer
   // so that we reliably find buffer overflows in it.
   uint8_t *DataCopy = new uint8_t[Size];
   memcpy(DataCopy, Data, Size);
   if (CurrentUnitData && CurrentUnitData != Data)
     memcpy(CurrentUnitData, Data, Size);
   CurrentUnitSize = Size;
   AllocTracer.Start(Options.TraceMalloc);
   UnitStartTime = system_clock::now();
   ResetCounters();  // Reset coverage right before the callback.
   TPC.ResetMaps();
   RunningCB = true;
   int Res = CB(DataCopy, Size);
   RunningCB = false;
   UnitStopTime = system_clock::now();
   (void)Res;
   assert(Res == 0);
   HasMoreMallocsThanFrees = AllocTracer.Stop();
   CurrentUnitSize = 0;
   delete[] DataCopy;
 }
References fuzzer::AllocTracer, assert(), CB, CurrentUnitData, CurrentUnitSize, HasMoreMallocsThanFrees, InFuzzingThread(), Options, ResetCounters(), fuzzer::TracePC::ResetMaps(), RunningCB, fuzzer::MallocFreeTracer::Start(), fuzzer::MallocFreeTracer::Stop(), fuzzer::TPC, fuzzer::FuzzingOptions::TraceMalloc, UnitStartTime, UnitStopTime, and nlohmann::detail::void().
Referenced by CrashResistantMergeInternalStep(), RunOne(), ShuffleAndMinimize(), and TryDetectingAMemoryLeak().
FindExtraUnits()
UnitVector fuzzer::Fuzzer::FindExtraUnits (const UnitVector & Initial, const UnitVector & Extra)
Definition at line 599 of file FuzzerLoop.cpp.
{
   UnitVector Res = Extra;
   UnitVector Tmp;
   size_t OldSize = Res.size();
   for (int Iter = 0; Iter < 10; Iter++) {
     ShuffleCorpus(&Res);
     TPC.ResetMaps();
     Corpus.ResetFeatureSet();
     ResetCoverage();
     for (auto &U : Initial) {
       TPC.ResetMaps();
       RunOne(U);
     }
     Tmp.clear();
     for (auto &U : Res) {
       TPC.ResetMaps();
       if (RunOne(U))
         Tmp.push_back(U);
     }
     char Stat[7] = "MIN   ";
     Stat[3] = '0' + Iter;
     PrintStats(Stat, "\n", Tmp.size());
     size_t NewSize = Tmp.size();
     assert(NewSize <= OldSize);
     Res.swap(Tmp);
     if (NewSize + 5 >= OldSize)
       break;
     OldSize = NewSize;
   }
   return Res;
 }
References assert(), Corpus, PrintStats(), ResetCoverage(), fuzzer::InputCorpus::ResetFeatureSet(), fuzzer::TracePC::ResetMaps(), RunOne(), ShuffleCorpus(), and fuzzer::TPC.
Referenced by Merge().
GetCurrentUnitInFuzzingThead()
size_t fuzzer::Fuzzer::GetCurrentUnitInFuzzingThead (const uint8_t ** Data) const
Definition at line 521 of file FuzzerLoop.cpp.
{
   assert(InFuzzingThread());
   *Data = CurrentUnitData;
   return CurrentUnitSize;
 }
References assert(), CurrentUnitData, CurrentUnitSize, and InFuzzingThread().
Referenced by fuzzer::TraceState::TryToAddDesiredData().
GetMD()
MutationDispatcher& fuzzer::Fuzzer::GetMD () inline
Definition at line 96 of file FuzzerInternal.h.
 { return MD; }
Referenced by LLVMFuzzerMutate().
getTotalNumberOfRuns()
size_t fuzzer::Fuzzer::getTotalNumberOfRuns () inline
Definition at line 80 of file FuzzerInternal.h.
 { return TotalNumberOfRuns; }
Referenced by fuzzer::FuzzerDriver().
HandleMalloc()
void fuzzer::Fuzzer::HandleMalloc (size_t Size)
Definition at line 162 of file FuzzerLoop.cpp.
{
   if (!Options.RssLimitMb || (Size >> 20) < (size_t)Options.RssLimitMb)
     return;
   Printf("==%d== ERROR: libFuzzer: out-of-memory (malloc(%zd))\n", GetPid(),
          Size);
   Printf("   To change the out-of-memory limit use -rss_limit_mb=<N>\n\n");
   if (EF->__sanitizer_print_stack_trace)
     EF->__sanitizer_print_stack_trace();
   DumpCurrentUnit("oom-");
   Printf("SUMMARY: libFuzzer: out-of-memory\n");
   PrintFinalStats();
   _Exit(Options.ErrorExitCode); // Stop right now.
 }
References DumpCurrentUnit(), fuzzer::EF, fuzzer::FuzzingOptions::ErrorExitCode, fuzzer::GetPid(), Options, fuzzer::Printf(), PrintFinalStats(), and fuzzer::FuzzingOptions::RssLimitMb.
Referenced by fuzzer::MallocHook().
InFuzzingThread()
bool fuzzer::Fuzzer::InFuzzingThread () const inline
Definition at line 105 of file FuzzerInternal.h.
 { return IsMyThread; }
Referenced by fuzzer::TraceState::AddInterestingWord(), AlarmCallback(), ExecuteCallback(), GetCurrentUnitInFuzzingThead(), fuzzer::TraceState::TraceMemcmpCallback(), and fuzzer::TraceState::TraceSwitchCallback().
InitializeTraceState()
void fuzzer::Fuzzer::InitializeTraceState ()
Definition at line 241 of file FuzzerTraceState.cpp.
{
   if (!Options.UseMemcmp) return;
   TS = new TraceState(MD, Options, this);
 }
References MD, Options, fuzzer::TS, and fuzzer::FuzzingOptions::UseMemcmp.
Referenced by Fuzzer().
InterruptCallback()
void fuzzer::Fuzzer::InterruptCallback () private
Definition at line 282 of file FuzzerLoop.cpp.
{
   Printf("==%lu== libFuzzer: run interrupted; exiting\n", GetPid());
   PrintFinalStats();
   _Exit(0);  // Stop right now, don't perform any at-exit actions.
 }
References fuzzer::GetPid(), fuzzer::Printf(), and PrintFinalStats().
Referenced by StaticInterruptCallback().
Loop()
void fuzzer::Fuzzer::Loop ()
Definition at line 747 of file FuzzerLoop.cpp.
                   {
   system_clock::time_point LastCorpusReload = system_clock::now();
   if (Options.DoCrossOver)
     MD.SetCorpus(&Corpus);
   while (true) {
     auto Now = system_clock::now();
     if (duration_cast<seconds>(Now - LastCorpusReload).count() >=
         Options.ReloadIntervalSec) {
       RereadOutputCorpus(MaxInputLen);
       LastCorpusReload = system_clock::now();
     }
     if (TotalNumberOfRuns >= Options.MaxNumberOfRuns)
       break;
     if (TimedOut()) break;
     // Perform several mutations and runs.
     MutateAndTestOne();
   }
   PrintStats("DONE  ", "\n");
   MD.PrintRecommendedDictionary();
 }
References Corpus, fuzzer::FuzzingOptions::DoCrossOver, MaxInputLen, fuzzer::FuzzingOptions::MaxNumberOfRuns, MD, MutateAndTestOne(), benchmark::cycleclock::Now(), Options, fuzzer::MutationDispatcher::PrintRecommendedDictionary(), PrintStats(), fuzzer::FuzzingOptions::ReloadIntervalSec, RereadOutputCorpus(), fuzzer::MutationDispatcher::SetCorpus(), TimedOut(), and TotalNumberOfRuns.
Referenced by fuzzer::FuzzerDriver().
Merge()
void fuzzer::Fuzzer::Merge (const std::vector< std::string > & Corpora)
Definition at line 637 of file FuzzerLoop.cpp.
{
   if (Corpora.size() <= 1) {
     Printf("Merge requires two or more corpus dirs\n");
     return;
   }
   InMergeMode = true;
   std::vector<std::string> ExtraCorpora(Corpora.begin() + 1, Corpora.end());
   assert(MaxInputLen > 0);
   UnitVector Initial, Extra;
   ReadDirToVectorOfUnits(Corpora[0].c_str(), &Initial, nullptr, MaxInputLen,
                          true);
   for (auto &C : ExtraCorpora)
     ReadDirToVectorOfUnits(C.c_str(), &Extra, nullptr, MaxInputLen, true);
   if (!Initial.empty()) {
     Printf("=== Minimizing the initial corpus of %zd units\n", Initial.size());
     Initial = FindExtraUnits({}, Initial);
   }
   Printf("=== Merging extra %zd units\n", Extra.size());
   auto Res = FindExtraUnits(Initial, Extra);
   for (auto &U: Res)
     WriteToOutputCorpus(U);
   Printf("=== Merge: written %zd units\n", Res.size());
 }
References assert(), FindExtraUnits(), InMergeMode, MaxInputLen, fuzzer::Printf(), fuzzer::ReadDirToVectorOfUnits(), and WriteToOutputCorpus().
Referenced by fuzzer::FuzzerDriver().
MinimizeCrashLoop()
void fuzzer::Fuzzer::MinimizeCrashLoop (const Unit & U)
Definition at line 769 of file FuzzerLoop.cpp.
{
   if (U.size() <= 2) return;
   while (!TimedOut() && TotalNumberOfRuns < Options.MaxNumberOfRuns) {
     MD.StartMutationSequence();
     memcpy(CurrentUnitData, U.data(), U.size());
     for (int i = 0; i < Options.MutateDepth; i++) {
       size_t NewSize = MD.Mutate(CurrentUnitData, U.size(), MaxMutationLen);
       assert(NewSize > 0 && NewSize <= MaxMutationLen);
       RunOne(CurrentUnitData, NewSize);
       TryDetectingAMemoryLeak(CurrentUnitData, NewSize,
                               /*DuringInitialCorpusExecution*/ false);
     }
   }
 }
References assert(), CurrentUnitData, MaxMutationLen, fuzzer::FuzzingOptions::MaxNumberOfRuns, MD, fuzzer::MutationDispatcher::Mutate(), fuzzer::FuzzingOptions::MutateDepth, Options, RunOne(), fuzzer::MutationDispatcher::StartMutationSequence(), TimedOut(), TotalNumberOfRuns, and TryDetectingAMemoryLeak().
Referenced by fuzzer::MinimizeCrashInputInternalStep().
MutateAndTestOne()
void fuzzer::Fuzzer::MutateAndTestOne () private
Definition at line 705 of file FuzzerLoop.cpp.
{
   MD.StartMutationSequence();
   auto &II = Corpus.ChooseUnitToMutate(MD.GetRand());
   const auto &U = II.U;
   memcpy(BaseSha1, II.Sha1, sizeof(BaseSha1));
   assert(CurrentUnitData);
   size_t Size = U.size();
   assert(Size <= MaxInputLen && "Oversized Unit");
   memcpy(CurrentUnitData, U.data(), Size);
   assert(MaxMutationLen > 0);
   for (int i = 0; i < Options.MutateDepth; i++) {
     if (TotalNumberOfRuns >= Options.MaxNumberOfRuns)
       break;
     size_t NewSize = 0;
     NewSize = MD.Mutate(CurrentUnitData, Size, MaxMutationLen);
     assert(NewSize > 0 && "Mutator returned empty unit");
     assert(NewSize <= MaxMutationLen && "Mutator return overisized unit");
     Size = NewSize;
     if (i == 0)
       StartTraceRecording();
     II.NumExecutedMutations++;
     if (size_t NumFeatures = RunOne(CurrentUnitData, Size)) {
       Corpus.AddToCorpus({CurrentUnitData, CurrentUnitData + Size}, NumFeatures,
                          /*MayDeleteFile=*/true);
       ReportNewCoverage(&II, {CurrentUnitData, CurrentUnitData + Size});
       CheckExitOnSrcPosOrItem();
     }
     StopTraceRecording();
     TryDetectingAMemoryLeak(CurrentUnitData, Size,
                             /*DuringInitialCorpusExecution*/ false);
   }
 }
References fuzzer::InputCorpus::AddToCorpus(), assert(), BaseSha1, CheckExitOnSrcPosOrItem(), fuzzer::InputCorpus::ChooseUnitToMutate(), Corpus, CurrentUnitData, fuzzer::MutationDispatcher::GetRand(), MaxInputLen, MaxMutationLen, fuzzer::FuzzingOptions::MaxNumberOfRuns, MD, fuzzer::MutationDispatcher::Mutate(), fuzzer::FuzzingOptions::MutateDepth, Options, ReportNewCoverage(), RunOne(), fuzzer::MutationDispatcher::StartMutationSequence(), StartTraceRecording(), StopTraceRecording(), TotalNumberOfRuns, TryDetectingAMemoryLeak(), and fuzzer::InputInfo::U.
Referenced by Loop().
PrepareCounters()
void fuzzer::Fuzzer::PrepareCounters (Fuzzer::Coverage * C) private
Definition at line 71 of file FuzzerLoop.cpp.
{
   if (Options.UseCounters) {
     size_t NumCounters = EF->__sanitizer_get_number_of_counters();
     C->CounterBitmap.resize(NumCounters);
   }
 }
References fuzzer::Fuzzer::Coverage::CounterBitmap, fuzzer::EF, Options, and fuzzer::FuzzingOptions::UseCounters.
Referenced by ResetCoverage().
PrintFinalStats()
void fuzzer::Fuzzer::PrintFinalStats ()
Definition at line 375 of file FuzzerLoop.cpp.
{
   if (Options.PrintCoverage)
     TPC.PrintCoverage();
   if (Options.DumpCoverage)
     TPC.DumpCoverage();
   if (Options.PrintCorpusStats)
     Corpus.PrintStats();
   if (!Options.PrintFinalStats) return;
   size_t ExecPerSec = execPerSec();
   Printf("stat::number_of_executed_units: %zd\n", TotalNumberOfRuns);
   Printf("stat::average_exec_per_sec:     %zd\n", ExecPerSec);
   Printf("stat::new_units_added:          %zd\n", NumberOfNewUnitsAdded);
   Printf("stat::slowest_unit_time_sec:    %zd\n", TimeOfLongestUnitInSeconds);
   Printf("stat::peak_rss_mb:              %zd\n", GetPeakRSSMb());
 }
References Corpus, fuzzer::FuzzingOptions::DumpCoverage, fuzzer::TracePC::DumpCoverage(), execPerSec(), fuzzer::GetPeakRSSMb(), NumberOfNewUnitsAdded, Options, fuzzer::FuzzingOptions::PrintCorpusStats, fuzzer::FuzzingOptions::PrintCoverage, fuzzer::TracePC::PrintCoverage(), fuzzer::Printf(), fuzzer::FuzzingOptions::PrintFinalStats, fuzzer::InputCorpus::PrintStats(), TimeOfLongestUnitInSeconds, TotalNumberOfRuns, and fuzzer::TPC.
Referenced by AlarmCallback(), CrashCallback(), DeathCallback(), fuzzer::FuzzerDriver(), HandleMalloc(), InterruptCallback(), RssLimitCallback(), and TryDetectingAMemoryLeak().
PrintStats()
void fuzzer::Fuzzer::PrintStats (const char * Where, const char * End = "\n", size_t Units = 0) private
Definition at line 328 of file FuzzerLoop.cpp.
{
   size_t ExecPerSec = execPerSec();
   if (Options.OutputCSV) {
     static bool csvHeaderPrinted = false;
     if (!csvHeaderPrinted) {
       csvHeaderPrinted = true;
       Printf("runs,block_cov,bits,cc_cov,corpus,execs_per_sec,tbms,reason\n");
     }
     Printf("%zd,%zd,%zd,%zd,%zd,%zd,%s\n", TotalNumberOfRuns,
            MaxCoverage.BlockCoverage, MaxCoverage.CounterBitmapBits,
            MaxCoverage.CallerCalleeCoverage, Corpus.size(), ExecPerSec, Where);
   }
   if (!Options.Verbosity)
     return;
   Printf("#%zd\t%s", TotalNumberOfRuns, Where);
   if (MaxCoverage.BlockCoverage)
     Printf(" cov: %zd", MaxCoverage.BlockCoverage);
   if (size_t N = MaxCoverage.VPMap.GetNumBitsSinceLastMerge())
     Printf(" vp: %zd", N);
   if (size_t N = TPC.GetTotalPCCoverage())
     Printf(" cov: %zd", N);
   if (auto TB = MaxCoverage.CounterBitmapBits)
     Printf(" bits: %zd", TB);
   if (size_t N = Corpus.NumFeatures())
     Printf( " ft: %zd", N);
   if (MaxCoverage.CallerCalleeCoverage)
     Printf(" indir: %zd", MaxCoverage.CallerCalleeCoverage);
   if (!Corpus.empty()) {
     Printf(" corp: %zd", Corpus.NumActiveUnits());
     if (size_t N = Corpus.SizeInBytes()) {
       if (N < (1<<14))
         Printf("/%zdb", N);
       else if (N < (1 << 24))
         Printf("/%zdKb", N >> 10);
       else
         Printf("/%zdMb", N >> 20);
     }
   }
   if (Units)
     Printf(" units: %zd", Units);
   Printf(" exec/s: %zd", ExecPerSec);
   Printf(" rss: %zdMb", GetPeakRSSMb());
   Printf("%s", End);
 }
References fuzzer::Fuzzer::Coverage::BlockCoverage, fuzzer::Fuzzer::Coverage::CallerCalleeCoverage, Corpus, fuzzer::Fuzzer::Coverage::CounterBitmapBits, fuzzer::InputCorpus::empty(), execPerSec(), fuzzer::ValueBitMap::GetNumBitsSinceLastMerge(), fuzzer::GetPeakRSSMb(), fuzzer::TracePC::GetTotalPCCoverage(), MaxCoverage, N, fuzzer::InputCorpus::NumActiveUnits(), fuzzer::InputCorpus::NumFeatures(), Options, fuzzer::FuzzingOptions::OutputCSV, fuzzer::Printf(), fuzzer::InputCorpus::size(), fuzzer::InputCorpus::SizeInBytes(), TotalNumberOfRuns, fuzzer::TPC, fuzzer::FuzzingOptions::Verbosity, and fuzzer::Fuzzer::Coverage::VPMap.
Referenced by CrashResistantMergeInternalStep(), FindExtraUnits(), Loop(), PrintStatusForNewUnit(), RereadOutputCorpus(), RunOne(), and ShuffleAndMinimize().
PrintStatusForNewUnit()
void fuzzer::Fuzzer::PrintStatusForNewUnit (const Unit & U) private
Definition at line 575 of file FuzzerLoop.cpp.
{
   if (!Options.PrintNEW)
     return;
   PrintStats("NEW   ", "");
   if (Options.Verbosity) {
     Printf(" L: %zd ", U.size());
     MD.PrintMutationSequence();
     Printf("\n");
   }
 }
References MD, Options, fuzzer::Printf(), fuzzer::MutationDispatcher::PrintMutationSequence(), fuzzer::FuzzingOptions::PrintNEW, PrintStats(), and fuzzer::FuzzingOptions::Verbosity.
Referenced by ReportNewCoverage().
RecordMaxCoverage()
bool fuzzer::Fuzzer::RecordMaxCoverage (Fuzzer::Coverage * C) private
Definition at line 80 of file FuzzerLoop.cpp.
{
   bool Res = false;
   uint64_t NewBlockCoverage = EF->__sanitizer_get_total_unique_coverage();
   if (NewBlockCoverage > C->BlockCoverage) {
     Res = true;
     C->BlockCoverage = NewBlockCoverage;
   }
   if (Options.UseIndirCalls &&
       EF->__sanitizer_get_total_unique_caller_callee_pairs) {
     uint64_t NewCallerCalleeCoverage =
         EF->__sanitizer_get_total_unique_caller_callee_pairs();
     if (NewCallerCalleeCoverage > C->CallerCalleeCoverage) {
       Res = true;
       C->CallerCalleeCoverage = NewCallerCalleeCoverage;
     }
   }
   if (Options.UseCounters) {
     uint64_t CounterDelta =
         EF->__sanitizer_update_counter_bitset_and_clear_counters(
             C->CounterBitmap.data());
     if (CounterDelta > 0) {
       Res = true;
       C->CounterBitmapBits += CounterDelta;
     }
   }
   return Res;
 }
References fuzzer::Fuzzer::Coverage::BlockCoverage, fuzzer::Fuzzer::Coverage::CallerCalleeCoverage, fuzzer::Fuzzer::Coverage::CounterBitmap, fuzzer::Fuzzer::Coverage::CounterBitmapBits, fuzzer::EF, Options, fuzzer::FuzzingOptions::UseCounters, and fuzzer::FuzzingOptions::UseIndirCalls.
Referenced by RunOne().
ReportNewCoverage()
void fuzzer::Fuzzer::ReportNewCoverage (InputInfo * II, const Unit & U) private
Definition at line 586 of file FuzzerLoop.cpp.
{
   II->NumSuccessfullMutations++;
   MD.RecordSuccessfulMutationSequence();
   PrintStatusForNewUnit(U);
   WriteToOutputCorpus(U);
   NumberOfNewUnitsAdded++;
   TPC.PrintNewPCs();
 }
References MD, NumberOfNewUnitsAdded, fuzzer::InputInfo::NumSuccessfullMutations, fuzzer::TracePC::PrintNewPCs(), PrintStatusForNewUnit(), fuzzer::MutationDispatcher::RecordSuccessfulMutationSequence(), fuzzer::TPC, and WriteToOutputCorpus().
Referenced by MutateAndTestOne().
RereadOutputCorpus()
void fuzzer::Fuzzer::RereadOutputCorpus (size_t MaxSize)
Definition at line 429 of file FuzzerLoop.cpp.
{
   if (Options.OutputCorpus.empty() || !Options.ReloadIntervalSec) return;
   std::vector<Unit> AdditionalCorpus;
   ReadDirToVectorOfUnits(Options.OutputCorpus.c_str(), &AdditionalCorpus,
                          &EpochOfLastReadOfOutputCorpus, MaxSize,
                          /*ExitOnError*/ false);
   if (Options.Verbosity >= 2)
     Printf("Reload: read %zd new units.\n", AdditionalCorpus.size());
   bool Reloaded = false;
   for (auto &U : AdditionalCorpus) {
     if (U.size() > MaxSize)
       U.resize(MaxSize);
     if (!Corpus.HasUnit(U)) {
       if (size_t NumFeatures = RunOne(U)) {
         CheckExitOnSrcPosOrItem();
         Corpus.AddToCorpus(U, NumFeatures);
         Reloaded = true;
       }
     }
   }
   if (Reloaded)
     PrintStats("RELOAD");
 }
References fuzzer::InputCorpus::AddToCorpus(), CheckExitOnSrcPosOrItem(), Corpus, EpochOfLastReadOfOutputCorpus, fuzzer::InputCorpus::HasUnit(), Options, fuzzer::FuzzingOptions::OutputCorpus, fuzzer::Printf(), PrintStats(), fuzzer::ReadDirToVectorOfUnits(), fuzzer::FuzzingOptions::ReloadIntervalSec, RunOne(), and fuzzer::FuzzingOptions::Verbosity.
Referenced by Loop().
ResetCounters()
void fuzzer::Fuzzer::ResetCounters () private
Definition at line 66 of file FuzzerLoop.cpp.
{
   if (Options.UseCounters)
     EF->__sanitizer_update_counter_bitset_and_clear_counters(0);
 }
References fuzzer::EF, Options, and fuzzer::FuzzingOptions::UseCounters.
Referenced by ExecuteCallback().
ResetCoverage()
void fuzzer::Fuzzer::ResetCoverage ()
Definition at line 741 of file FuzzerLoop.cpp.
{
   ResetEdgeCoverage();
   MaxCoverage.Reset();
   PrepareCounters(&MaxCoverage);
 }
References MaxCoverage, PrepareCounters(), fuzzer::Fuzzer::Coverage::Reset(), and ResetEdgeCoverage().
Referenced by FindExtraUnits(), and Fuzzer().
ResetEdgeCoverage()
void fuzzer::Fuzzer::ResetEdgeCoverage () private
Definition at line 61 of file FuzzerLoop.cpp.
{
   CHECK_EXTERNAL_FUNCTION(__sanitizer_reset_coverage);
   EF->__sanitizer_reset_coverage();
 }
References CHECK_EXTERNAL_FUNCTION, and fuzzer::EF.
Referenced by ResetCoverage().
RssLimitCallback()
void fuzzer::Fuzzer::RssLimitCallback ()
Definition at line 315 of file FuzzerLoop.cpp.
{
   Printf(
       "==%lu== ERROR: libFuzzer: out-of-memory (used: %zdMb; limit: %zdMb)\n",
       GetPid(), GetPeakRSSMb(), Options.RssLimitMb);
   Printf("   To change the out-of-memory limit use -rss_limit_mb=<N>\n\n");
   if (EF->__sanitizer_print_memory_profile)
     EF->__sanitizer_print_memory_profile(95);
   DumpCurrentUnit("oom-");
   Printf("SUMMARY: libFuzzer: out-of-memory\n");
   PrintFinalStats();
   _Exit(Options.ErrorExitCode); // Stop right now.
 }
References DumpCurrentUnit(), fuzzer::EF, fuzzer::FuzzingOptions::ErrorExitCode, fuzzer::GetPeakRSSMb(), fuzzer::GetPid(), Options, fuzzer::Printf(), PrintFinalStats(), and fuzzer::FuzzingOptions::RssLimitMb.
Referenced by fuzzer::RssThread().
RunOne() [1/2]
size_t fuzzer::Fuzzer::RunOne (const uint8_t * Data, size_t Size)
Definition at line 488 of file FuzzerLoop.cpp.
{
   if (!Size) return 0;
   TotalNumberOfRuns++;
   ExecuteCallback(Data, Size);
   size_t Res = 0;
   if (size_t NumFeatures = TPC.CollectFeatures([&](size_t Feature) -> bool {
         return Corpus.AddFeature(Feature, Size, Options.Shrink);
       }))
     Res = NumFeatures;
   if (!TPC.UsingTracePcGuard()) {
     if (TPC.UpdateValueProfileMap(&MaxCoverage.VPMap))
       Res = 1;
     if (!Res && RecordMaxCoverage(&MaxCoverage))
       Res = 1;
   }
   auto TimeOfUnit =
       duration_cast<seconds>(UnitStopTime - UnitStartTime).count();
   if (!(TotalNumberOfRuns & (TotalNumberOfRuns - 1)) &&
       secondsSinceProcessStartUp() >= 2)
     PrintStats("pulse ");
   if (TimeOfUnit > TimeOfLongestUnitInSeconds * 1.1 &&
       TimeOfUnit >= Options.ReportSlowUnits) {
     TimeOfLongestUnitInSeconds = TimeOfUnit;
     Printf("Slowest unit: %zd s:\n", TimeOfLongestUnitInSeconds);
     WriteUnitToFileWithPrefix({Data, Data + Size}, "slow-unit-");
   }
   return Res;
 }
References fuzzer::TracePC::CollectFeatures(), ExecuteCallback(), MaxCoverage, Options, fuzzer::Printf(), PrintStats(), RecordMaxCoverage(), fuzzer::FuzzingOptions::ReportSlowUnits, secondsSinceProcessStartUp(), TimeOfLongestUnitInSeconds, TotalNumberOfRuns, fuzzer::TPC, UnitStartTime, UnitStopTime, fuzzer::TracePC::UpdateValueProfileMap(), fuzzer::TracePC::UsingTracePcGuard(), fuzzer::Fuzzer::Coverage::VPMap, and WriteUnitToFileWithPrefix().
Referenced by FindExtraUnits(), MinimizeCrashLoop(), MutateAndTestOne(), RereadOutputCorpus(), fuzzer::RunOneTest(), and ShuffleAndMinimize().
RunOne() [2/2]
size_t fuzzer::Fuzzer::RunOne (const Unit & U) inline private
Definition at line 118 of file FuzzerInternal.h.
 { return RunOne(U.data(), U.size()); }
References RunOne().
Referenced by RunOne().
secondsSinceProcessStartUp()
size_t fuzzer::Fuzzer::secondsSinceProcessStartUp () inline
Definition at line 64 of file FuzzerInternal.h.
{
     return duration_cast<seconds>(system_clock::now() - ProcessStartTime)
         .count();
   }
Referenced by fuzzer::FuzzerDriver(), and RunOne().
SetDeathCallback()
void fuzzer::Fuzzer::SetDeathCallback () private
Definition at line 209 of file FuzzerLoop.cpp.
{
   CHECK_EXTERNAL_FUNCTION(__sanitizer_set_death_callback);
   EF->__sanitizer_set_death_callback(StaticDeathCallback);
 }
References CHECK_EXTERNAL_FUNCTION, fuzzer::EF, and StaticDeathCallback().
Referenced by Fuzzer().
SetMaxInputLen()
void fuzzer::Fuzzer::SetMaxInputLen (size_t MaxInputLen)
Definition at line 391 of file FuzzerLoop.cpp.
{
   assert(this->MaxInputLen == 0); // Can only reset MaxInputLen from 0 to non-0.
   assert(MaxInputLen);
   this->MaxInputLen = MaxInputLen;
   this->MaxMutationLen = MaxInputLen;
   AllocateCurrentUnitData();
   Printf("INFO: -max_len is not provided, using %zd\n", MaxInputLen);
 }
References AllocateCurrentUnitData(), assert(), MaxInputLen, MaxMutationLen, and fuzzer::Printf().
Referenced by fuzzer::FuzzerDriver(), and fuzzer::MinimizeCrashInputInternalStep().
SetMaxMutationLen()
void fuzzer::Fuzzer::SetMaxMutationLen (size_t MaxMutationLen)
Definition at line 400 of file FuzzerLoop.cpp.
{
   assert(MaxMutationLen && MaxMutationLen <= MaxInputLen);
   this->MaxMutationLen = MaxMutationLen;
 }
References assert(), MaxInputLen, and MaxMutationLen.
Referenced by fuzzer::MinimizeCrashInputInternalStep().
ShuffleAndMinimize()
void fuzzer::Fuzzer::ShuffleAndMinimize (UnitVector * V)
Definition at line 461 of file FuzzerLoop.cpp.
{
   Printf("#0\tREAD units: %zd\n", InitialCorpus->size());
   if (Options.ShuffleAtStartUp)
     ShuffleCorpus(InitialCorpus);
   // Test the callback with empty input and never try it again.
   uint8_t dummy;
   ExecuteCallback(&dummy, 0);
   for (const auto &U : *InitialCorpus) {
     if (size_t NumFeatures = RunOne(U)) {
       CheckExitOnSrcPosOrItem();
       Corpus.AddToCorpus(U, NumFeatures);
       if (Options.Verbosity >= 2)
         Printf("NEW0: %zd L %zd\n", MaxCoverage.BlockCoverage, U.size());
     }
     TryDetectingAMemoryLeak(U.data(), U.size(),
                             /*DuringInitialCorpusExecution*/ true);
   }
   PrintStats("INITED");
   if (Corpus.empty()) {
     Printf("ERROR: no interesting inputs were found. "
            "Is the code instrumented for coverage? Exiting.\n");
     exit(1);
   }
 }
References fuzzer::InputCorpus::AddToCorpus(), fuzzer::Fuzzer::Coverage::BlockCoverage, CheckExitOnSrcPosOrItem(), Corpus, fuzzer::InputCorpus::empty(), ExecuteCallback(), MaxCoverage, Options, fuzzer::Printf(), PrintStats(), RunOne(), fuzzer::FuzzingOptions::ShuffleAtStartUp, ShuffleCorpus(), TryDetectingAMemoryLeak(), and fuzzer::FuzzingOptions::Verbosity.
Referenced by fuzzer::FuzzerDriver().
ShuffleCorpus()
void fuzzer::Fuzzer::ShuffleCorpus (UnitVector * V) private
Definition at line 453 of file FuzzerLoop.cpp.
{
   std::random_shuffle(V->begin(), V->end(), MD.GetRand());
   if (Options.PreferSmall)
     std::stable_sort(V->begin(), V->end(), [](const Unit &A, const Unit &B) {
       return A.size() < B.size();
     });
 }
References fuzzer::MutationDispatcher::GetRand(), MD, Options, and fuzzer::FuzzingOptions::PreferSmall.
Referenced by FindExtraUnits(), and ShuffleAndMinimize().
StartTraceRecording()
void fuzzer::Fuzzer::StartTraceRecording () private
Definition at line 231 of file FuzzerTraceState.cpp.
{
   if (!TS) return;
   TS->StartTraceRecording();
 }
References fuzzer::TraceState::StartTraceRecording(), and fuzzer::TS.
Referenced by MutateAndTestOne().
StaticAlarmCallback()
void fuzzer::Fuzzer::StaticAlarmCallback () static
Definition at line 254 of file FuzzerLoop.cpp.
{
   assert(F);
   F->AlarmCallback();
 }
References AlarmCallback(), assert(), and fuzzer::F.
StaticCrashSignalCallback()
void fuzzer::Fuzzer::StaticCrashSignalCallback () static
Definition at line 259 of file FuzzerLoop.cpp.
{
   assert(F);
   F->CrashCallback();
 }
References assert(), CrashCallback(), and fuzzer::F.
StaticDeathCallback()
void fuzzer::Fuzzer::StaticDeathCallback () static private
Definition at line 214 of file FuzzerLoop.cpp.
{
   assert(F);
   F->DeathCallback();
 }
References assert(), DeathCallback(), and fuzzer::F.
Referenced by SetDeathCallback().
StaticInterruptCallback()
void fuzzer::Fuzzer::StaticInterruptCallback () static
Definition at line 264 of file FuzzerLoop.cpp.
{
   assert(F);
   F->InterruptCallback();
 }
References assert(), fuzzer::F, and InterruptCallback().
StopTraceRecording()
void fuzzer::Fuzzer::StopTraceRecording () private
Definition at line 236 of file FuzzerTraceState.cpp.
{
   if (!TS) return;
   TS->StopTraceRecording();
 }
References fuzzer::TraceState::StopTraceRecording(), and fuzzer::TS.
Referenced by MutateAndTestOne().
TimedOut()
bool fuzzer::Fuzzer::TimedOut () inline
Definition at line 69 of file FuzzerInternal.h.
                   {
     return Options.MaxTotalTimeSec > 0 &&
            secondsSinceProcessStartUp() >
                static_cast<size_t>(Options.MaxTotalTimeSec);
   }
Referenced by Loop(), and MinimizeCrashLoop().
TryDetectingAMemoryLeak()
void fuzzer::Fuzzer::TryDetectingAMemoryLeak (const uint8_t * Data, size_t Size, bool DuringInitialCorpusExecution)
Definition at line 668 of file FuzzerLoop.cpp.
{
   if (!HasMoreMallocsThanFrees) return;  // mallocs==frees, a leak is unlikely.
   if (!Options.DetectLeaks) return;
   if (!&(EF->__lsan_enable) || !&(EF->__lsan_disable) ||
       !(EF->__lsan_do_recoverable_leak_check))
     return;  // No lsan.
   // Run the target once again, but with lsan disabled so that if there is
   // a real leak we do not report it twice.
   EF->__lsan_disable();
   ExecuteCallback(Data, Size);
   EF->__lsan_enable();
   if (!HasMoreMallocsThanFrees) return;  // a leak is unlikely.
   if (NumberOfLeakDetectionAttempts++ > 1000) {
     Options.DetectLeaks = false;
     Printf("INFO: libFuzzer disabled leak detection after every mutation.\n"
            "      Most likely the target function accumulates allocated\n"
            "      memory in a global state w/o actually leaking it.\n"
            "      You may try running this binary with -trace_malloc=[12]"
            "      to get a trace of mallocs and frees.\n"
            "      If LeakSanitizer is enabled in this process it will still\n"
            "      run on the process shutdown.\n");
     return;
   }
   // Now perform the actual lsan pass. This is expensive and we must ensure
   // we don't call it too often.
   if (EF->__lsan_do_recoverable_leak_check()) { // Leak is found, report it.
     if (DuringInitialCorpusExecution)
       Printf("\nINFO: a leak has been found in the initial corpus.\n\n");
     Printf("INFO: to ignore leaks on libFuzzer side use -detect_leaks=0.\n\n");
     CurrentUnitSize = Size;
     DumpCurrentUnit("leak-");
     PrintFinalStats();
     _Exit(Options.ErrorExitCode);  // not exit() to disable lsan further on.
   }
 }
References CurrentUnitSize, fuzzer::FuzzingOptions::DetectLeaks, DumpCurrentUnit(), fuzzer::EF, fuzzer::FuzzingOptions::ErrorExitCode, ExecuteCallback(), HasMoreMallocsThanFrees, NumberOfLeakDetectionAttempts, Options, fuzzer::Printf(), and PrintFinalStats().
Referenced by MinimizeCrashLoop(), MutateAndTestOne(), fuzzer::RunOneTest(), and ShuffleAndMinimize().
WriteToOutputCorpus()
void fuzzer::Fuzzer::WriteToOutputCorpus (const Unit & U) private
Definition at line 551 of file FuzzerLoop.cpp.
{
   if (Options.OnlyASCII)
     assert(IsASCII(U));
   if (Options.OutputCorpus.empty())
     return;
   std::string Path = DirPlusFile(Options.OutputCorpus, Hash(U));
   WriteToFile(U, Path);
   if (Options.Verbosity >= 2)
     Printf("Written to %s\n", Path.c_str());
 }
References assert(), fuzzer::DirPlusFile(), fuzzer::Hash(), fuzzer::IsASCII(), fuzzer::FuzzingOptions::OnlyASCII, Options, fuzzer::FuzzingOptions::OutputCorpus, fuzzer::Printf(), fuzzer::FuzzingOptions::Verbosity, and fuzzer::WriteToFile().
Referenced by CrashResistantMerge(), Merge(), and ReportNewCoverage().
WriteUnitToFileWithPrefix()
void fuzzer::Fuzzer::WriteUnitToFileWithPrefix (const Unit & U, const char * Prefix) private
Definition at line 562 of file FuzzerLoop.cpp.
{
   if (!Options.SaveArtifacts)
     return;
   std::string Path = Options.ArtifactPrefix + Prefix + Hash(U);
   if (!Options.ExactArtifactPath.empty())
     Path = Options.ExactArtifactPath; // Overrides ArtifactPrefix.
   WriteToFile(U, Path);
   Printf("artifact_prefix='%s'; Test unit written to %s\n",
          Options.ArtifactPrefix.c_str(), Path.c_str());
   if (U.size() <= kMaxUnitSizeToPrint)
     Printf("Base64: %s\n", Base64(U).c_str());
 }
References fuzzer::FuzzingOptions::ArtifactPrefix, fuzzer::Base64(), fuzzer::FuzzingOptions::ExactArtifactPath, fuzzer::Hash(), fuzzer::kMaxUnitSizeToPrint, Options, fuzzer::Printf(), fuzzer::FuzzingOptions::SaveArtifacts, and fuzzer::WriteToFile().
Referenced by DumpCurrentUnit(), and RunOne().
Member Data Documentation
BaseSha1
uint8_t fuzzer::Fuzzer::BaseSha1[kSHA1NumBytes] private
Definition at line 149 of file FuzzerInternal.h.
Referenced by DumpCurrentUnit(), Fuzzer(), and MutateAndTestOne().
CB
UserCallback fuzzer::Fuzzer::CB private
Definition at line 158 of file FuzzerInternal.h.
Referenced by ExecuteCallback().
Corpus
InputCorpus& fuzzer::Fuzzer::Corpus private
Definition at line 159 of file FuzzerInternal.h.
Referenced by CheckExitOnSrcPosOrItem(), FindExtraUnits(), Loop(), MutateAndTestOne(), PrintFinalStats(), PrintStats(), RereadOutputCorpus(), and ShuffleAndMinimize().
CurrentUnitData
uint8_t* fuzzer::Fuzzer::CurrentUnitData = nullptr private
Definition at line 147 of file FuzzerInternal.h.
Referenced by AllocateCurrentUnitData(), DumpCurrentUnit(), ExecuteCallback(), GetCurrentUnitInFuzzingThead(), MinimizeCrashLoop(), and MutateAndTestOne().
CurrentUnitSize
std::atomic<size_t> fuzzer::Fuzzer::CurrentUnitSize private
Definition at line 148 of file FuzzerInternal.h.
Referenced by DumpCurrentUnit(), ExecuteCallback(), Fuzzer(), GetCurrentUnitInFuzzingThead(), and TryDetectingAMemoryLeak().
EpochOfLastReadOfOutputCorpus
long fuzzer::Fuzzer::EpochOfLastReadOfOutputCorpus = 0 private
Definition at line 166 of file FuzzerInternal.h.
Referenced by Fuzzer(), and RereadOutputCorpus().
HasMoreMallocsThanFrees
bool fuzzer::Fuzzer::HasMoreMallocsThanFrees = false private
Definition at line 155 of file FuzzerInternal.h.
Referenced by ExecuteCallback(), and TryDetectingAMemoryLeak().
InMergeMode
bool fuzzer::Fuzzer::InMergeMode = false private
Definition at line 177 of file FuzzerInternal.h.
Referenced by DumpCurrentUnit(), and Merge().
IsMyThread
thread_local bool fuzzer::Fuzzer::IsMyThread static private
Definition at line 175 of file FuzzerInternal.h.
Referenced by Fuzzer().
MaxCoverage
Coverage fuzzer::Fuzzer::MaxCoverage private
Definition at line 169 of file FuzzerInternal.h.
Referenced by PrintStats(), ResetCoverage(), RunOne(), and ShuffleAndMinimize().
MaxInputLen
size_t fuzzer::Fuzzer::MaxInputLen = 0 private
Definition at line 171 of file FuzzerInternal.h.
Referenced by AllocateCurrentUnitData(), CrashResistantMergeInternalStep(), Fuzzer(), Loop(), Merge(), MutateAndTestOne(), SetMaxInputLen(), and SetMaxMutationLen().
MaxMutationLen
size_t fuzzer::Fuzzer::MaxMutationLen = 0 private
Definition at line 172 of file FuzzerInternal.h.
Referenced by Fuzzer(), MinimizeCrashLoop(), MutateAndTestOne(), SetMaxInputLen(), and SetMaxMutationLen().
MD
MutationDispatcher& fuzzer::Fuzzer::MD private
Definition at line 160 of file FuzzerInternal.h.
Referenced by DumpCurrentUnit(), InitializeTraceState(), Loop(), MinimizeCrashLoop(), MutateAndTestOne(), PrintStatusForNewUnit(), ReportNewCoverage(), and ShuffleCorpus().
NumberOfLeakDetectionAttempts
size_t fuzzer::Fuzzer::NumberOfLeakDetectionAttempts = 0 private
Definition at line 156 of file FuzzerInternal.h.
Referenced by TryDetectingAMemoryLeak().
NumberOfNewUnitsAdded
size_t fuzzer::Fuzzer::NumberOfNewUnitsAdded = 0 private
Definition at line 153 of file FuzzerInternal.h.
Referenced by PrintFinalStats(), and ReportNewCoverage().
Options
FuzzingOptions fuzzer::Fuzzer::Options private
Definition at line 161 of file FuzzerInternal.h.
Referenced by AlarmCallback(), CheckExitOnSrcPosOrItem(), CrashCallback(), ExecuteCallback(), Fuzzer(), HandleMalloc(), InitializeTraceState(), Loop(), MinimizeCrashLoop(), MutateAndTestOne(), PrepareCounters(), PrintFinalStats(), PrintStats(), PrintStatusForNewUnit(), RecordMaxCoverage(), RereadOutputCorpus(), ResetCounters(), RssLimitCallback(), RunOne(), ShuffleAndMinimize(), ShuffleCorpus(), TryDetectingAMemoryLeak(), WriteToOutputCorpus(), and WriteUnitToFileWithPrefix().
ProcessStartTime
system_clock::time_point fuzzer::Fuzzer::ProcessStartTime = system_clock::now() private
Definition at line 163 of file FuzzerInternal.h.
RunningCB
bool fuzzer::Fuzzer::RunningCB = false private
Definition at line 150 of file FuzzerInternal.h.
Referenced by AlarmCallback(), and ExecuteCallback().
TimeOfLongestUnitInSeconds
long fuzzer::Fuzzer::TimeOfLongestUnitInSeconds = 0 private
Definition at line 165 of file FuzzerInternal.h.
Referenced by PrintFinalStats(), and RunOne().
TotalNumberOfRuns
size_t fuzzer::Fuzzer::TotalNumberOfRuns = 0 private
Definition at line 152 of file FuzzerInternal.h.
Referenced by CrashResistantMergeInternalStep(), Loop(), MinimizeCrashLoop(), MutateAndTestOne(), PrintFinalStats(), PrintStats(), and RunOne().
UnitStartTime
system_clock::time_point fuzzer::Fuzzer::UnitStartTime private
Definition at line 164 of file FuzzerInternal.h.
Referenced by AlarmCallback(), ExecuteCallback(), and RunOne().
UnitStopTime
system_clock::time_point fuzzer::Fuzzer::UnitStopTime private
Definition at line 164 of file FuzzerInternal.h.
Referenced by ExecuteCallback(), and RunOne().
The documentation for this class was generated from the following files:
mc_orchestrator/json-3.7.3/test/thirdparty/Fuzzer/FuzzerInternal.h
mc_orchestrator/json-3.7.3/test/thirdparty/Fuzzer/FuzzerLoop.cpp
mc_orchestrator/json-3.7.3/test/thirdparty/Fuzzer/FuzzerMerge.cpp
mc_orchestrator/json-3.7.3/test/thirdparty/Fuzzer/FuzzerTraceState.cpp