Mixed Criticality Orchestrator: fuzzer::InputCorpus Class Reference
fuzzer::InputCorpus Class Reference
#include <FuzzerCorpus.h>
Public Member Functions
InputCorpus (const std::string &OutputCorpus)
~InputCorpus ()
size_t size () const
size_t SizeInBytes () const
size_t NumActiveUnits () const
bool empty () const
const Unit & operator[] (size_t Idx) const
void AddToCorpus (const Unit &U, size_t NumFeatures, bool MayDeleteFile=false)
bool HasUnit (const Unit &U)
bool HasUnit (const std::string &H)
InputInfo & ChooseUnitToMutate (Random &Rand)
size_t ChooseUnitIdxToMutate (Random &Rand)
void PrintStats ()
void PrintFeatureSet ()
void DeleteInput (size_t Idx)
bool AddFeature (size_t Idx, uint32_t NewSize, bool Shrink)
size_t NumFeatures () const
void ResetFeatureSet ()
Static Public Attributes
static const size_t kFeatureSetSize = 1 << 16
Private Member Functions
size_t GetFeature (size_t Idx) const
void ValidateFeatureSet ()
void UpdateCorpusDistribution ()
Private Attributes
std::piecewise_constant_distribution< double > CorpusDistribution
std::vector< double > Intervals
std::vector< double > Weights
std::unordered_set< std::string > Hashes
std::vector< InputInfo * > Inputs
bool CountingFeatures = false
uint32_t InputSizesPerFeature [kFeatureSetSize]
uint32_t SmallestElementPerFeature [kFeatureSetSize]
std::string OutputCorpus
Static Private Attributes
static const bool FeatureDebug = false
Detailed Description
Definition at line 38 of file FuzzerCorpus.h.
Constructor & Destructor Documentation
InputCorpus()
fuzzer::InputCorpus::InputCorpus (const std::string & OutputCorpus) inline
Definition at line 41 of file FuzzerCorpus.h.
                                              : OutputCorpus(OutputCorpus) {
     memset(InputSizesPerFeature, 0, sizeof(InputSizesPerFeature));
     memset(SmallestElementPerFeature, 0, sizeof(SmallestElementPerFeature));
   }
References InputSizesPerFeature, and SmallestElementPerFeature.
~InputCorpus()
fuzzer::InputCorpus::~InputCorpus () inline
Definition at line 45 of file FuzzerCorpus.h.
                  {
     for (auto II : Inputs)
       delete II;
   }
References Inputs.
Member Function Documentation
AddFeature()
bool fuzzer::InputCorpus::AddFeature (size_t Idx, uint32_t NewSize, bool Shrink) inline
Definition at line 128 of file FuzzerCorpus.h.
{
     assert(NewSize);
     Idx = Idx % kFeatureSetSize;
     uint32_t OldSize = GetFeature(Idx);
     if (OldSize == 0 || (Shrink && OldSize > NewSize)) {
       if (OldSize > 0) {
         size_t OldIdx = SmallestElementPerFeature[Idx];
         InputInfo &II = *Inputs[OldIdx];
         assert(II.NumFeatures > 0);
         II.NumFeatures--;
         if (II.NumFeatures == 0)
           DeleteInput(OldIdx);
       }
       if (FeatureDebug)
         Printf("ADD FEATURE %zd sz %d\n", Idx, NewSize);
       SmallestElementPerFeature[Idx] = Inputs.size();
       InputSizesPerFeature[Idx] = NewSize;
       CountingFeatures = true;
       return true;
     }
     return false;
   }
References assert(), CountingFeatures, DeleteInput(), FeatureDebug, GetFeature(), Idx, Inputs, InputSizesPerFeature, kFeatureSetSize, fuzzer::InputInfo::NumFeatures, fuzzer::Printf(), and SmallestElementPerFeature.
AddToCorpus()
void fuzzer::InputCorpus::AddToCorpus (const Unit & U, size_t NumFeatures, bool MayDeleteFile = false) inline
Definition at line 64 of file FuzzerCorpus.h.
{
     assert(!U.empty());
     uint8_t Hash[kSHA1NumBytes];
     if (FeatureDebug)
       Printf("ADD_TO_CORPUS %zd NF %zd\n", Inputs.size(), NumFeatures);
     ComputeSHA1(U.data(), U.size(), Hash);
     Hashes.insert(Sha1ToString(Hash));
     Inputs.push_back(new InputInfo());
     InputInfo &II = *Inputs.back();
     II.U = U;
     II.NumFeatures = NumFeatures;
     II.MayDeleteFile = MayDeleteFile;
     memcpy(II.Sha1, Hash, kSHA1NumBytes);
     UpdateCorpusDistribution();
     ValidateFeatureSet();
   }
References assert(), fuzzer::ComputeSHA1(), FeatureDebug, fuzzer::Hash(), Hashes, Inputs, fuzzer::kSHA1NumBytes, fuzzer::InputInfo::MayDeleteFile, fuzzer::InputInfo::NumFeatures, NumFeatures(), fuzzer::Printf(), fuzzer::InputInfo::Sha1, fuzzer::Sha1ToString(), fuzzer::InputInfo::U, UpdateCorpusDistribution(), and ValidateFeatureSet().
Referenced by fuzzer::MinimizeCrashInputInternalStep(), fuzzer::Fuzzer::MutateAndTestOne(), fuzzer::Fuzzer::RereadOutputCorpus(), fuzzer::Fuzzer::ShuffleAndMinimize(), and TEST().
ChooseUnitIdxToMutate()
size_t fuzzer::InputCorpus::ChooseUnitIdxToMutate (Random & Rand) inline
Definition at line 92 of file FuzzerCorpus.h.
{
     size_t Idx = static_cast<size_t>(CorpusDistribution(Rand.Get_mt19937()));
     assert(Idx < Inputs.size());
     return Idx;
   }
References assert(), CorpusDistribution, fuzzer::Random::Get_mt19937(), Idx, and Inputs.
Referenced by ChooseUnitToMutate(), and TEST().
ChooseUnitToMutate()
InputInfo& fuzzer::InputCorpus::ChooseUnitToMutate (Random & Rand) inline
Definition at line 83 of file FuzzerCorpus.h.
{
     InputInfo &II = *Inputs[ChooseUnitIdxToMutate(Rand)];
     assert(!II.U.empty());
     return II;
   };
References assert(), ChooseUnitIdxToMutate(), Inputs, and fuzzer::InputInfo::U.
Referenced by fuzzer::Fuzzer::MutateAndTestOne().
DeleteInput()
void fuzzer::InputCorpus::DeleteInput (size_t Idx) inline
Definition at line 119 of file FuzzerCorpus.h.
{
     InputInfo &II = *Inputs[Idx];
     if (!OutputCorpus.empty() && II.MayDeleteFile)
       RemoveFile(DirPlusFile(OutputCorpus, Sha1ToString(II.Sha1)));
     Unit().swap(II.U);
     if (FeatureDebug)
       Printf("EVICTED %zd\n", Idx);
   }
References fuzzer::DirPlusFile(), FeatureDebug, Idx, Inputs, fuzzer::InputInfo::MayDeleteFile, OutputCorpus, fuzzer::Printf(), fuzzer::RemoveFile(), fuzzer::InputInfo::Sha1, fuzzer::Sha1ToString(), and fuzzer::InputInfo::U.
Referenced by AddFeature().
empty()
bool fuzzer::InputCorpus::empty () const inline
Definition at line 62 of file FuzzerCorpus.h.
 { return Inputs.empty(); }
References Inputs.
Referenced by fuzzer::Fuzzer::PrintStats(), and fuzzer::Fuzzer::ShuffleAndMinimize().
GetFeature()
size_t fuzzer::InputCorpus::GetFeature (size_t Idx) const inline private
Definition at line 168 of file FuzzerCorpus.h.
 { return InputSizesPerFeature[Idx]; }
References Idx, and InputSizesPerFeature.
Referenced by AddFeature(), NumFeatures(), PrintFeatureSet(), and ValidateFeatureSet().
HasUnit() [1/2]
bool fuzzer::InputCorpus::HasUnit (const std::string & H) inline
Definition at line 82 of file FuzzerCorpus.h.
 { return Hashes.count(H); }
References Hashes.
HasUnit() [2/2]
bool fuzzer::InputCorpus::HasUnit (const Unit & U) inline
Definition at line 81 of file FuzzerCorpus.h.
 { return Hashes.count(Hash(U)); }
References fuzzer::Hash(), and Hashes.
Referenced by fuzzer::Fuzzer::CheckExitOnSrcPosOrItem(), and fuzzer::Fuzzer::RereadOutputCorpus().
NumActiveUnits()
size_t fuzzer::InputCorpus::NumActiveUnits () const inline
Definition at line 56 of file FuzzerCorpus.h.
{
     size_t Res = 0;
     for (auto II : Inputs)
       Res += !II->U.empty();
     return Res;
   }
References Inputs.
Referenced by fuzzer::Fuzzer::PrintStats().
NumFeatures()
size_t fuzzer::InputCorpus::NumFeatures () const inline
Definition at line 151 of file FuzzerCorpus.h.
{
     size_t Res = 0;
     for (size_t i = 0; i < kFeatureSetSize; i++)
       Res += GetFeature(i) != 0;
     return Res;
   }
References GetFeature(), and kFeatureSetSize.
Referenced by AddToCorpus(), PrintFeatureSet(), fuzzer::Fuzzer::PrintStats(), and UpdateCorpusDistribution().
operator[]()
const Unit& fuzzer::InputCorpus::operator[] (size_t Idx) const inline
Definition at line 63 of file FuzzerCorpus.h.
 { return Inputs[Idx]->U; }
References Idx, and Inputs.
PrintFeatureSet()
void fuzzer::InputCorpus::PrintFeatureSet () inline
Definition at line 107 of file FuzzerCorpus.h.
{
     for (size_t i = 0; i < kFeatureSetSize; i++) {
       if(size_t Sz = GetFeature(i))
         Printf("[%zd: id %zd sz%zd] ", i, SmallestElementPerFeature[i], Sz);
     }
     Printf("\n\t");
     for (size_t i = 0; i < Inputs.size(); i++)
       if (size_t N = Inputs[i]->NumFeatures)
         Printf(" %zd=>%zd ", i, N);
     Printf("\n");
   }
References GetFeature(), Inputs, kFeatureSetSize, N, NumFeatures(), fuzzer::Printf(), and SmallestElementPerFeature.
Referenced by ValidateFeatureSet().
PrintStats()
void fuzzer::InputCorpus::PrintStats () inline
Definition at line 98 of file FuzzerCorpus.h.
                     {
     for (size_t i = 0; i < Inputs.size(); i++) {
       const auto &II = *Inputs[i];
       Printf("  [%zd %s]\tsz: %zd\truns: %zd\tsucc: %zd\n", i,
              Sha1ToString(II.Sha1).c_str(), II.U.size(),
              II.NumExecutedMutations, II.NumSuccessfullMutations);
     }
   }
References Inputs, fuzzer::Printf(), and fuzzer::Sha1ToString().
Referenced by fuzzer::Fuzzer::PrintFinalStats().
ResetFeatureSet()
void fuzzer::InputCorpus::ResetFeatureSet () inline
Definition at line 158 of file FuzzerCorpus.h.
{
     assert(Inputs.empty());
     memset(InputSizesPerFeature, 0, sizeof(InputSizesPerFeature));
     memset(SmallestElementPerFeature, 0, sizeof(SmallestElementPerFeature));
   }
References assert(), Inputs, InputSizesPerFeature, and SmallestElementPerFeature.
Referenced by fuzzer::Fuzzer::FindExtraUnits().
size()
size_t fuzzer::InputCorpus::size () const inline
Definition at line 49 of file FuzzerCorpus.h.
 { return Inputs.size(); }
References Inputs.
Referenced by fuzzer::Fuzzer::PrintStats().
SizeInBytes()
size_t fuzzer::InputCorpus::SizeInBytes () const inline
Definition at line 50 of file FuzzerCorpus.h.
{
     size_t Res = 0;
     for (auto II : Inputs)
       Res += II->U.size();
     return Res;
   }
References Inputs.
Referenced by fuzzer::Fuzzer::PrintStats().
UpdateCorpusDistribution()
void fuzzer::InputCorpus::UpdateCorpusDistribution () inline private
Definition at line 187 of file FuzzerCorpus.h.
{
     size_t N = Inputs.size();
     Intervals.resize(N + 1);
     Weights.resize(N);
     std::iota(Intervals.begin(), Intervals.end(), 0);
     if (CountingFeatures)
       for (size_t i = 0; i < N; i++)
         Weights[i] = Inputs[i]->NumFeatures * (i + 1);
     else
       std::iota(Weights.begin(), Weights.end(), 1);
     CorpusDistribution = std::piecewise_constant_distribution<double>(
         Intervals.begin(), Intervals.end(), Weights.begin());
   }
References CorpusDistribution, CountingFeatures, Inputs, Intervals, N, NumFeatures(), and Weights.
Referenced by AddToCorpus().
ValidateFeatureSet()
void fuzzer::InputCorpus::ValidateFeatureSet () inline private
Definition at line 170 of file FuzzerCorpus.h.
{
     if (!CountingFeatures) return;
     if (FeatureDebug)
       PrintFeatureSet();
     for (size_t Idx = 0; Idx < kFeatureSetSize; Idx++)
       if (GetFeature(Idx))
         Inputs[SmallestElementPerFeature[Idx]]->Tmp++;
     for (auto II: Inputs) {
       if (II->Tmp != II->NumFeatures)
         Printf("ZZZ %zd %zd\n", II->Tmp, II->NumFeatures);
       assert(II->Tmp == II->NumFeatures);
       II->Tmp = 0;
     }
   }
References assert(), CountingFeatures, FeatureDebug, GetFeature(), Idx, Inputs, kFeatureSetSize, fuzzer::Printf(), PrintFeatureSet(), and SmallestElementPerFeature.
Referenced by AddToCorpus().
Member Data Documentation
CorpusDistribution
std::piecewise_constant_distribution<double> fuzzer::InputCorpus::CorpusDistribution private
Definition at line 200 of file FuzzerCorpus.h.
Referenced by ChooseUnitIdxToMutate(), and UpdateCorpusDistribution().
CountingFeatures
bool fuzzer::InputCorpus::CountingFeatures = false private
Definition at line 208 of file FuzzerCorpus.h.
Referenced by AddFeature(), UpdateCorpusDistribution(), and ValidateFeatureSet().
FeatureDebug
const bool fuzzer::InputCorpus::FeatureDebug = false static private
Definition at line 166 of file FuzzerCorpus.h.
Referenced by AddFeature(), AddToCorpus(), DeleteInput(), and ValidateFeatureSet().
Hashes
std::unordered_set<std::string> fuzzer::InputCorpus::Hashes private
Definition at line 205 of file FuzzerCorpus.h.
Referenced by AddToCorpus(), and HasUnit().
Inputs
std::vector<InputInfo*> fuzzer::InputCorpus::Inputs private
Definition at line 206 of file FuzzerCorpus.h.
Referenced by AddFeature(), AddToCorpus(), ChooseUnitIdxToMutate(), ChooseUnitToMutate(), DeleteInput(), empty(), NumActiveUnits(), operator[](), PrintFeatureSet(), PrintStats(), ResetFeatureSet(), size(), SizeInBytes(), UpdateCorpusDistribution(), ValidateFeatureSet(), and ~InputCorpus().
InputSizesPerFeature
uint32_t fuzzer::InputCorpus::InputSizesPerFeature[kFeatureSetSize] private
Definition at line 209 of file FuzzerCorpus.h.
Referenced by AddFeature(), GetFeature(), InputCorpus(), and ResetFeatureSet().
Intervals
std::vector<double> fuzzer::InputCorpus::Intervals private
Definition at line 202 of file FuzzerCorpus.h.
Referenced by UpdateCorpusDistribution().
kFeatureSetSize
const size_t fuzzer::InputCorpus::kFeatureSetSize = 1 << 16 static
Definition at line 40 of file FuzzerCorpus.h.
Referenced by AddFeature(), NumFeatures(), PrintFeatureSet(), and ValidateFeatureSet().
OutputCorpus
std::string fuzzer::InputCorpus::OutputCorpus private
Definition at line 212 of file FuzzerCorpus.h.
Referenced by DeleteInput().
SmallestElementPerFeature
uint32_t fuzzer::InputCorpus::SmallestElementPerFeature[kFeatureSetSize] private
Definition at line 210 of file FuzzerCorpus.h.
Referenced by AddFeature(), InputCorpus(), PrintFeatureSet(), ResetFeatureSet(), and ValidateFeatureSet().
Weights
std::vector<double> fuzzer::InputCorpus::Weights private
Definition at line 203 of file FuzzerCorpus.h.
Referenced by UpdateCorpusDistribution().
The documentation for this class was generated from the following file:
mc_orchestrator/json-3.7.3/test/thirdparty/Fuzzer/FuzzerCorpus.h