Mixed Criticality Orchestrator: httplib::Server Class Reference
httplib::Server Class Reference
#include <httplib.h>
Classes
struct MountPointEntry
Public Types
enum HandlerResponse { HandlerResponse::Handled, HandlerResponse::Unhandled }
using Handler = std::function< void(const Request &, Response &)>
using ExceptionHandler = std::function< void(const Request &, Response &, std::exception_ptr ep)>
using HandlerWithResponse = std::function< HandlerResponse(const Request &, Response &)>
using HandlerWithContentReader = std::function< void(const Request &, Response &, const ContentReader &content_reader)>
using Expect100ContinueHandler = std::function< int(const Request &, Response &)>
Public Member Functions
Server ()
virtual ~Server ()
virtual bool is_valid () const
Server & Get (const std::string &pattern, Handler handler)
Server & Post (const std::string &pattern, Handler handler)
Server & Post (const std::string &pattern, HandlerWithContentReader handler)
Server & Put (const std::string &pattern, Handler handler)
Server & Put (const std::string &pattern, HandlerWithContentReader handler)
Server & Patch (const std::string &pattern, Handler handler)
Server & Patch (const std::string &pattern, HandlerWithContentReader handler)
Server & Delete (const std::string &pattern, Handler handler)
Server & Delete (const std::string &pattern, HandlerWithContentReader handler)
Server & Options (const std::string &pattern, Handler handler)
bool set_base_dir (const std::string &dir, const std::string &mount_point=std::string())
bool set_mount_point (const std::string &mount_point, const std::string &dir, Headers headers=Headers())
bool remove_mount_point (const std::string &mount_point)
Server & set_file_extension_and_mimetype_mapping (const std::string &ext, const std::string &mime)
Server & set_default_file_mimetype (const std::string &mime)
Server & set_file_request_handler (Handler handler)
Server & set_error_handler (HandlerWithResponse handler)
Server & set_error_handler (Handler handler)
Server & set_exception_handler (ExceptionHandler handler)
Server & set_pre_routing_handler (HandlerWithResponse handler)
Server & set_post_routing_handler (Handler handler)
Server & set_expect_100_continue_handler (Expect100ContinueHandler handler)
Server & set_logger (Logger logger)
Server & set_address_family (int family)
Server & set_tcp_nodelay (bool on)
Server & set_socket_options (SocketOptions socket_options)
Server & set_default_headers (Headers headers)
Server & set_header_writer (std::function< ssize_t(Stream &, Headers &)> const &writer)
Server & set_keep_alive_max_count (size_t count)
Server & set_keep_alive_timeout (time_t sec)
Server & set_read_timeout (time_t sec, time_t usec=0)
template<class Rep , class Period >
Server & set_read_timeout (const std::chrono::duration< Rep, Period > &duration)
Server & set_write_timeout (time_t sec, time_t usec=0)
template<class Rep , class Period >
Server & set_write_timeout (const std::chrono::duration< Rep, Period > &duration)
Server & set_idle_interval (time_t sec, time_t usec=0)
template<class Rep , class Period >
Server & set_idle_interval (const std::chrono::duration< Rep, Period > &duration)
Server & set_payload_max_length (size_t length)
bool bind_to_port (const std::string &host, int port, int socket_flags=0)
int bind_to_any_port (const std::string &host, int socket_flags=0)
bool listen_after_bind ()
bool listen (const std::string &host, int port, int socket_flags=0)
bool is_running () const
void wait_until_ready () const
void stop ()
Public Attributes
std::function< TaskQueue *(void)> new_task_queue
Protected Member Functions
bool process_request (Stream &strm, bool close_connection, bool &connection_closed, const std::function< void(Request &)> &setup_request)
Protected Attributes
std::atomic< socket_t > svr_sock_ { (-1) }
size_t keep_alive_max_count_ = 5
time_t keep_alive_timeout_sec_ = 5
time_t read_timeout_sec_ = 5
time_t read_timeout_usec_ = 0
time_t write_timeout_sec_ = 5
time_t write_timeout_usec_ = 0
time_t idle_interval_sec_ = 0
time_t idle_interval_usec_ = 0
size_t payload_max_length_ = ((std::numeric_limits<size_t>::max)())
Private Types
using Handlers = std::vector< std::pair< std::unique_ptr< detail::MatcherBase >, Handler > >
using HandlersForContentReader = std::vector< std::pair< std::unique_ptr< detail::MatcherBase >, HandlerWithContentReader > >
Private Member Functions
socket_t create_server_socket (const std::string &host, int port, int socket_flags, SocketOptions socket_options) const
int bind_internal (const std::string &host, int port, int socket_flags)
bool listen_internal ()
bool routing (Request &req, Response &res, Stream &strm)
bool handle_file_request (const Request &req, Response &res, bool head=false)
bool dispatch_request (Request &req, Response &res, const Handlers &handlers) const
bool dispatch_request_for_content_reader (Request &req, Response &res, ContentReader content_reader, const HandlersForContentReader &handlers) const
bool parse_request_line (const char *s, Request &req) const
void apply_ranges (const Request &req, Response &res, std::string &content_type, std::string &boundary) const
bool write_response (Stream &strm, bool close_connection, Request &req, Response &res)
bool write_response_with_content (Stream &strm, bool close_connection, const Request &req, Response &res)
bool write_response_core (Stream &strm, bool close_connection, const Request &req, Response &res, bool need_apply_ranges)
bool write_content_with_provider (Stream &strm, const Request &req, Response &res, const std::string &boundary, const std::string &content_type)
bool read_content (Stream &strm, Request &req, Response &res)
bool read_content_with_content_receiver (Stream &strm, Request &req, Response &res, ContentReceiver receiver, MultipartContentHeader multipart_header, ContentReceiver multipart_receiver)
bool read_content_core (Stream &strm, Request &req, Response &res, ContentReceiver receiver, MultipartContentHeader multipart_header, ContentReceiver multipart_receiver) const
virtual bool process_and_close_socket (socket_t sock)
Static Private Member Functions
static std::unique_ptr< detail::MatcherBase > make_matcher (const std::string &pattern)
Private Attributes
std::atomic< bool > is_running_ {false}
std::atomic< bool > done_ {false}
std::vector< MountPointEntry > base_dirs_
std::map< std::string, std::string > file_extension_and_mimetype_map_
std::string default_file_mimetype_ = "application/octet-stream"
Handler file_request_handler_
Handlers get_handlers_
Handlers post_handlers_
HandlersForContentReader post_handlers_for_content_reader_
Handlers put_handlers_
HandlersForContentReader put_handlers_for_content_reader_
Handlers patch_handlers_
HandlersForContentReader patch_handlers_for_content_reader_
Handlers delete_handlers_
HandlersForContentReader delete_handlers_for_content_reader_
Handlers options_handlers_
HandlerWithResponse error_handler_
ExceptionHandler exception_handler_
HandlerWithResponse pre_routing_handler_
Handler post_routing_handler_
Expect100ContinueHandler expect_100_continue_handler_
Logger logger_
int address_family_ = AF_UNSPEC
bool tcp_nodelay_ = false
SocketOptions socket_options_ = default_socket_options
Headers default_headers_
std::function< ssize_t(Stream &, Headers &)> header_writer_
Detailed Description
Definition at line 827 of file httplib.h.
Member Typedef Documentation
ExceptionHandler
using httplib::Server::ExceptionHandler = std::function<void(const Request &, Response &, std::exception_ptr ep)>
Definition at line 832 of file httplib.h.
Expect100ContinueHandler
using httplib::Server::Expect100ContinueHandler = std::function<int(const Request &, Response &)>
Definition at line 845 of file httplib.h.
Handler
using httplib::Server::Handler = std::function<void(const Request &, Response &)>
Definition at line 829 of file httplib.h.
Handlers
using httplib::Server::Handlers = std::vector<std::pair<std::unique_ptr<detail::MatcherBase>, Handler> > private
Definition at line 938 of file httplib.h.
HandlersForContentReader
using httplib::Server::HandlersForContentReader = std::vector<std::pair<std::unique_ptr<detail::MatcherBase>, HandlerWithContentReader> > private
Definition at line 941 of file httplib.h.
HandlerWithContentReader
using httplib::Server::HandlerWithContentReader = std::function<void(const Request &, Response &, const ContentReader &content_reader)>
Definition at line 842 of file httplib.h.
HandlerWithResponse
using httplib::Server::HandlerWithResponse = std::function<HandlerResponse(const Request &, Response &)>
Definition at line 839 of file httplib.h.
Member Enumeration Documentation
HandlerResponse
enum httplib::Server::HandlerResponse strong
Enumerator
Handled
Unhandled
Definition at line 834 of file httplib.h.
{
     Handled,
     Unhandled,
   };
Constructor & Destructor Documentation
Server()
httplib::Server::Server () inline
Definition at line 5679 of file httplib.h.
     : new_task_queue(
           [] { return new ThreadPool(CPPHTTPLIB_THREAD_POOL_COUNT); }) {
 #ifndef _WIN32
   signal(SIGPIPE, SIG_IGN);
 #endif
 }
References CPPHTTPLIB_THREAD_POOL_COUNT.
~Server()
httplib::Server::~Server () inline virtual default
Member Function Documentation
apply_ranges()
void httplib::Server::apply_ranges (const Request & req, Response & res, std::string & content_type, std::string & boundary) const inline private
Definition at line 6500 of file httplib.h.
{
   if (req.ranges.size() > 1) {
     auto it = res.headers.find("Content-Type");
     if (it != res.headers.end()) {
       content_type = it->second;
       res.headers.erase(it);
     }
     boundary = detail::make_multipart_data_boundary();
     res.set_header("Content-Type",
                    "multipart/byteranges; boundary=" + boundary);
   }
   auto type = detail::encoding_type(req, res);
   if (res.body.empty()) {
     if (res.content_length_ > 0) {
       size_t length = 0;
       if (req.ranges.empty()) {
         length = res.content_length_;
       } else if (req.ranges.size() == 1) {
         auto offset_and_length = detail::get_range_offset_and_length(
             req.ranges[0], res.content_length_);
         length = offset_and_length.second;
         auto content_range = detail::make_content_range_header_field(
             offset_and_length, res.content_length_);
         res.set_header("Content-Range", content_range);
       } else {
         length = detail::get_multipart_ranges_data_length(
             req, boundary, content_type, res.content_length_);
       }
       res.set_header("Content-Length", std::to_string(length));
     } else {
       if (res.content_provider_) {
         if (res.is_chunked_content_provider_) {
           res.set_header("Transfer-Encoding", "chunked");
           if (type == detail::EncodingType::Gzip) {
             res.set_header("Content-Encoding", "gzip");
           } else if (type == detail::EncodingType::Brotli) {
             res.set_header("Content-Encoding", "br");
           }
         }
       }
     }
   } else {
     if (req.ranges.empty()) {
       ;
     } else if (req.ranges.size() == 1) {
       auto offset_and_length =
           detail::get_range_offset_and_length(req.ranges[0], res.body.size());
       auto offset = offset_and_length.first;
       auto length = offset_and_length.second;
       auto content_range = detail::make_content_range_header_field(
           offset_and_length, res.body.size());
       res.set_header("Content-Range", content_range);
       assert(offset + length <= res.body.size());
       res.body = res.body.substr(offset, length);
     } else {
       std::string data;
       detail::make_multipart_ranges_data(req, res, boundary, content_type,
                                          res.body.size(), data);
       res.body.swap(data);
     }
     if (type != detail::EncodingType::None) {
       std::unique_ptr<detail::compressor> compressor;
       std::string content_encoding;
       if (type == detail::EncodingType::Gzip) {
 #ifdef CPPHTTPLIB_ZLIB_SUPPORT
         compressor = detail::make_unique<detail::gzip_compressor>();
         content_encoding = "gzip";
 #endif
       } else if (type == detail::EncodingType::Brotli) {
 #ifdef CPPHTTPLIB_BROTLI_SUPPORT
         compressor = detail::make_unique<detail::brotli_compressor>();
         content_encoding = "br";
 #endif
       }
       if (compressor) {
         std::string compressed;
         if (compressor->compress(res.body.data(), res.body.size(), true,
                                  [&](const char *data, size_t data_len) {
                                    compressed.append(data, data_len);
                                    return true;
                                  })) {
           res.body.swap(compressed);
           res.set_header("Content-Encoding", content_encoding);
         }
       }
     }
     auto length = std::to_string(res.body.size());
     res.set_header("Content-Length", length);
   }
 }
References assert(), httplib::Response::body, httplib::detail::Brotli, httplib::Response::content_length_, httplib::Response::content_provider_, httplib::detail::encoding_type(), httplib::detail::get_multipart_ranges_data_length(), httplib::detail::get_range_offset_and_length(), httplib::detail::Gzip, httplib::Response::headers, httplib::Response::is_chunked_content_provider_, httplib::detail::make_content_range_header_field(), httplib::detail::make_multipart_data_boundary(), httplib::detail::make_multipart_ranges_data(), httplib::detail::None, httplib::Request::ranges, httplib::Response::set_header(), and httplib::to_string().
Referenced by write_response_core().
bind_internal()
int httplib::Server::bind_internal (const std::string & host, int port, int socket_flags) inline private
Definition at line 6299 of file httplib.h.
{
   if (!is_valid()) { return -1; }
   svr_sock_ = create_server_socket(host, port, socket_flags, socket_options_);
   if (svr_sock_ == INVALID_SOCKET) { return -1; }
   if (port == 0) {
     struct sockaddr_storage addr;
     socklen_t addr_len = sizeof(addr);
     if (getsockname(svr_sock_, reinterpret_cast<struct sockaddr *>(&addr),
                     &addr_len) == -1) {
       return -1;
     }
     if (addr.ss_family == AF_INET) {
       return ntohs(reinterpret_cast<struct sockaddr_in *>(&addr)->sin_port);
     } else if (addr.ss_family == AF_INET6) {
       return ntohs(reinterpret_cast<struct sockaddr_in6 *>(&addr)->sin6_port);
     } else {
       return -1;
     }
   } else {
     return port;
   }
 }
References addr, create_server_socket(), INVALID_SOCKET, is_valid(), socket_options_, and svr_sock_.
Referenced by bind_to_any_port(), and bind_to_port().
bind_to_any_port()
int httplib::Server::bind_to_any_port (const std::string & host, int socket_flags = 0) inline
Definition at line 5902 of file httplib.h.
{
   return bind_internal(host, 0, socket_flags);
 }
References bind_internal().
bind_to_port()
bool httplib::Server::bind_to_port (const std::string & host, int port, int socket_flags = 0) inline
Definition at line 5898 of file httplib.h.
{
   return bind_internal(host, port, socket_flags) >= 0;
 }
References bind_internal().
Referenced by listen().
create_server_socket()
socket_t httplib::Server::create_server_socket (const std::string & host, int port, int socket_flags, SocketOptions socket_options) const inline private
Definition at line 6284 of file httplib.h.
{
   return detail::create_socket(
       host, std::string(), port, address_family_, socket_flags, tcp_nodelay_,
       std::move(socket_options),
       [](socket_t sock, struct addrinfo &ai) -> bool {
         if (::bind(sock, ai.ai_addr, static_cast<socklen_t>(ai.ai_addrlen))) {
           return false;
         }
         if (::listen(sock, CPPHTTPLIB_LISTEN_BACKLOG)) { return false; }
         return true;
       });
 }
References address_family_, CPPHTTPLIB_LISTEN_BACKLOG, httplib::detail::create_socket(), if(), listen(), and tcp_nodelay_.
Referenced by bind_internal().
Delete() [1/2]
Server & httplib::Server::Delete (const std::string & pattern, Handler handler) inline
Definition at line 5739 of file httplib.h.
{
   delete_handlers_.emplace_back(make_matcher(pattern), std::move(handler));
   return *this;
 }
References delete_handlers_, and make_matcher().
Delete() [2/2]
Server & httplib::Server::Delete (const std::string & pattern, HandlerWithContentReader handler) inline
Definition at line 5744 of file httplib.h.
{
   delete_handlers_for_content_reader_.emplace_back(make_matcher(pattern),
                                                    std::move(handler));
   return *this;
 }
References delete_handlers_for_content_reader_, and make_matcher().
dispatch_request()
bool httplib::Server::dispatch_request (Request & req, Response & res, const Handlers & handlers) const inline private
Definition at line 6486 of file httplib.h.
{
   for (const auto &x : handlers) {
     const auto &matcher = x.first;
     const auto &handler = x.second;
     if (matcher->match(req)) {
       handler(req, res);
       return true;
     }
   }
   return false;
 }
Referenced by routing().
dispatch_request_for_content_reader()
bool httplib::Server::dispatch_request_for_content_reader (Request & req, Response & res, ContentReader content_reader, const HandlersForContentReader & handlers) const inline private
Definition at line 6605 of file httplib.h.
{
   for (const auto &x : handlers) {
     const auto &matcher = x.first;
     const auto &handler = x.second;
     if (matcher->match(req)) {
       handler(req, res, content_reader);
       return true;
     }
   }
   return false;
 }
Referenced by routing().
Get()
Server & httplib::Server::Get (const std::string & pattern, Handler handler) inline
Definition at line 5698 of file httplib.h.
{
   get_handlers_.emplace_back(make_matcher(pattern), std::move(handler));
   return *this;
 }
References get_handlers_, and make_matcher().
handle_file_request()
bool httplib::Server::handle_file_request (const Request & req, Response & res, bool head = false) inline private
Definition at line 6244 of file httplib.h.
{
   for (const auto &entry : base_dirs_) {
     // Prefix match
     if (!req.path.compare(0, entry.mount_point.size(), entry.mount_point)) {
       std::string sub_path = "/" + req.path.substr(entry.mount_point.size());
       if (detail::is_valid_path(sub_path)) {
         auto path = entry.base_dir + sub_path;
         if (path.back() == '/') { path += "index.html"; }
         if (detail::is_file(path)) {
           for (const auto &kv : entry.headers) {
             res.set_header(kv.first, kv.second);
           }
           auto mm = std::make_shared<detail::mmap>(path.c_str());
           if (!mm->is_open()) { return false; }
           res.set_content_provider(
               mm->size(),
               detail::find_content_type(path, file_extension_and_mimetype_map_,
                                         default_file_mimetype_),
               [mm](size_t offset, size_t length, DataSink &sink) -> bool {
                 sink.write(mm->data() + offset, length);
                 return true;
               });
           if (!head && file_request_handler_) {
             file_request_handler_(req, res);
           }
           return true;
         }
       }
     }
   }
   return false;
 }
References base_dirs_, default_file_mimetype_, file_extension_and_mimetype_map_, file_request_handler_, httplib::detail::find_content_type(), httplib::detail::is_file(), httplib::detail::is_valid_path(), httplib::Request::path, httplib::Response::set_content_provider(), httplib::Response::set_header(), and sink.
Referenced by routing().
is_running()
bool httplib::Server::is_running () const inline
Definition at line 5917 of file httplib.h.
 { return is_running_; }
References is_running_.
Referenced by wait_until_ready().
is_valid()
bool httplib::Server::is_valid () const inline virtual
Definition at line 6766 of file httplib.h.
 { return true; }
Referenced by bind_internal().
listen()
bool httplib::Server::listen (const std::string & host, int port, int socket_flags = 0) inline
Definition at line 5911 of file httplib.h.
{
   auto se = detail::scope_exit([&]() { done_ = true; });
   return bind_to_port(host, port, socket_flags) && listen_internal();
 }
References bind_to_port(), done_, and listen_internal().
Referenced by create_server_socket(), and ServerHandler::StartMcOrchestratorServer().
listen_after_bind()
bool httplib::Server::listen_after_bind () inline
Definition at line 5906 of file httplib.h.
{
   auto se = detail::scope_exit([&]() { done_ = true; });
   return listen_internal();
 }
References done_, and listen_internal().
listen_internal()
bool httplib::Server::listen_internal () inline private
Definition at line 6325 of file httplib.h.
{
   auto ret = true;
   is_running_ = true;
   auto se = detail::scope_exit([&]() { is_running_ = false; });
   {
     std::unique_ptr<TaskQueue> task_queue(new_task_queue());
     while (svr_sock_ != INVALID_SOCKET) {
 #ifndef _WIN32
       if (idle_interval_sec_ > 0 || idle_interval_usec_ > 0) {
 #endif
         auto val = detail::select_read(svr_sock_, idle_interval_sec_,
                                        idle_interval_usec_);
         if (val == 0) { // Timeout
           task_queue->on_idle();
           continue;
         }
 #ifndef _WIN32
       }
 #endif
       socket_t sock = accept(svr_sock_, nullptr, nullptr);
       if (sock == INVALID_SOCKET) {
         if (errno == EMFILE) {
           // The per-process limit of open file descriptors has been reached.
           // Try to accept new connections after a short sleep.
           std::this_thread::sleep_for(std::chrono::milliseconds(1));
           continue;
         } else if (errno == EINTR || errno == EAGAIN) {
           continue;
         }
         if (svr_sock_ != INVALID_SOCKET) {
           detail::close_socket(svr_sock_);
           ret = false;
         } else {
           ; // The server socket was closed by user.
         }
         break;
       }
       {
 #ifdef _WIN32
         auto timeout = static_cast<uint32_t>(read_timeout_sec_ * 1000 +
                                              read_timeout_usec_ / 1000);
         setsockopt(sock, SOL_SOCKET, SO_RCVTIMEO,
                    reinterpret_cast<const char *>(&timeout), sizeof(timeout));
 #else
         timeval tv;
         tv.tv_sec = static_cast<long>(read_timeout_sec_);
         tv.tv_usec = static_cast<decltype(tv.tv_usec)>(read_timeout_usec_);
         setsockopt(sock, SOL_SOCKET, SO_RCVTIMEO,
                    reinterpret_cast<const void *>(&tv), sizeof(tv));
 #endif
       }
       {
 #ifdef _WIN32
         auto timeout = static_cast<uint32_t>(write_timeout_sec_ * 1000 +
                                              write_timeout_usec_ / 1000);
         setsockopt(sock, SOL_SOCKET, SO_SNDTIMEO,
                    reinterpret_cast<const char *>(&timeout), sizeof(timeout));
 #else
         timeval tv;
         tv.tv_sec = static_cast<long>(write_timeout_sec_);
         tv.tv_usec = static_cast<decltype(tv.tv_usec)>(write_timeout_usec_);
         setsockopt(sock, SOL_SOCKET, SO_SNDTIMEO,
                    reinterpret_cast<const void *>(&tv), sizeof(tv));
 #endif
       }
       if (!task_queue->enqueue(
               [this, sock]() { process_and_close_socket(sock); })) {
         detail::shutdown_socket(sock);
         detail::close_socket(sock);
       }
     }
     task_queue->shutdown();
   }
   return ret;
 }
References httplib::detail::close_socket(), idle_interval_sec_, idle_interval_usec_, INVALID_SOCKET, is_running_, new_task_queue, read_timeout_sec_, read_timeout_usec_, httplib::detail::select_read(), httplib::detail::shutdown_socket(), svr_sock_, write_timeout_sec_, and write_timeout_usec_.
Referenced by listen(), and listen_after_bind().
make_matcher()
std::unique_ptr< detail::MatcherBase > httplib::Server::make_matcher (const std::string & pattern) inline static private
Definition at line 5690 of file httplib.h.
{
   if (pattern.find("/:") != std::string::npos) {
     return detail::make_unique<detail::PathParamsMatcher>(pattern);
   } else {
     return detail::make_unique<detail::RegexMatcher>(pattern);
   }
 }
Referenced by Delete(), Get(), Options(), Patch(), Post(), and Put().
Options()
Server & httplib::Server::Options (const std::string & pattern, Handler handler) inline
Definition at line 5751 of file httplib.h.
{
   options_handlers_.emplace_back(make_matcher(pattern), std::move(handler));
   return *this;
 }
References make_matcher(), and options_handlers_.
parse_request_line()
bool httplib::Server::parse_request_line (const char * s, Request & req) const inline private
Definition at line 5934 of file httplib.h.
{
   auto len = strlen(s);
   if (len < 2 || s[len - 2] != '\r' || s[len - 1] != '\n') { return false; }
   len -= 2;
   {
     size_t count = 0;
     detail::split(s, s + len, ' ', [&](const char *b, const char *e) {
       switch (count) {
       case 0: req.method = std::string(b, e); break;
       case 1: req.target = std::string(b, e); break;
       case 2: req.version = std::string(b, e); break;
       default: break;
       }
       count++;
     });
     if (count != 3) { return false; }
   }
   static const std::set<std::string> methods{
       "GET",     "HEAD",    "POST",  "PUT",   "DELETE",
       "CONNECT", "OPTIONS", "TRACE", "PATCH", "PRI"};
   if (methods.find(req.method) == methods.end()) { return false; }
   if (req.version != "HTTP/1.1" && req.version != "HTTP/1.0") { return false; }
   {
     // Skip URL fragment
     for (size_t i = 0; i < req.target.size(); i++) {
       if (req.target[i] == '#') {
         req.target.erase(i);
         break;
       }
     }
     size_t count = 0;
     detail::split(req.target.data(), req.target.data() + req.target.size(), '?',
                   2, [&](const char *b, const char *e) {
                     switch (count) {
                     case 0:
                       req.path = detail::decode_url(std::string(b, e), false);
                       break;
                     case 1: {
                       if (e - b > 0) {
                         detail::parse_query_text(std::string(b, e), req.params);
                       }
                       break;
                     }
                     default: break;
                     }
                     count++;
                   });
     if (count > 2) { return false; }
   }
   return true;
 }
References httplib::Request::method, httplib::detail::split(), httplib::Request::target, and httplib::Request::version.
Referenced by process_request().
Patch() [1/2]
Server & httplib::Server::Patch (const std::string & pattern, Handler handler) inline
Definition at line 5727 of file httplib.h.
{
   patch_handlers_.emplace_back(make_matcher(pattern), std::move(handler));
   return *this;
 }
References make_matcher(), and patch_handlers_.
Patch() [2/2]
Server & httplib::Server::Patch (const std::string & pattern, HandlerWithContentReader handler) inline
Definition at line 5732 of file httplib.h.
{
   patch_handlers_for_content_reader_.emplace_back(make_matcher(pattern),
                                                   std::move(handler));
   return *this;
 }
References make_matcher(), and patch_handlers_for_content_reader_.
Post() [1/2]
Server & httplib::Server::Post (const std::string & pattern, Handler handler) inline
Definition at line 5703 of file httplib.h.
{
   post_handlers_.emplace_back(make_matcher(pattern), std::move(handler));
   return *this;
 }
References make_matcher(), and post_handlers_.
Referenced by ServerHandler::StartMcOrchestratorServer().
Post() [2/2]
Server & httplib::Server::Post (const std::string & pattern, HandlerWithContentReader handler) inline
Definition at line 5708 of file httplib.h.
{
   post_handlers_for_content_reader_.emplace_back(make_matcher(pattern),
                                                  std::move(handler));
   return *this;
 }
References make_matcher(), and post_handlers_for_content_reader_.
process_and_close_socket()
bool httplib::Server::process_and_close_socket (socket_t sock) inline private virtual
Definition at line 6768 of file httplib.h.
{
   auto ret = detail::process_server_socket(
       svr_sock_, sock, keep_alive_max_count_, keep_alive_timeout_sec_,
       read_timeout_sec_, read_timeout_usec_, write_timeout_sec_,
       write_timeout_usec_,
       [this](Stream &strm, bool close_connection, bool &connection_closed) {
         return process_request(strm, close_connection, connection_closed,
                                nullptr);
       });
   detail::shutdown_socket(sock);
   detail::close_socket(sock);
   return ret;
 }
References httplib::detail::close_socket(), keep_alive_max_count_, keep_alive_timeout_sec_, process_request(), httplib::detail::process_server_socket(), read_timeout_sec_, read_timeout_usec_, httplib::detail::shutdown_socket(), svr_sock_, write_timeout_sec_, and write_timeout_usec_.
process_request()
bool httplib::Server::process_request (Stream & strm, bool close_connection, bool & connection_closed, const std::function< void(Request &)> & setup_request) inline protected
Definition at line 6621 of file httplib.h.
{
   std::array<char, 2048> buf{};
   detail::stream_line_reader line_reader(strm, buf.data(), buf.size());
   // Connection has been closed on client
   if (!line_reader.getline()) { return false; }
   Request req;
   Response res;
   res.version = "HTTP/1.1";
   res.headers = default_headers_;
 #ifdef _WIN32
   // TODO: Increase FD_SETSIZE statically (libzmq), dynamically (MySQL).
 #else
 #ifndef CPPHTTPLIB_USE_POLL
   // Socket file descriptor exceeded FD_SETSIZE...
   if (strm.socket() >= FD_SETSIZE) {
     Headers dummy;
     detail::read_headers(strm, dummy);
     res.status = StatusCode::InternalServerError_500;
     return write_response(strm, close_connection, req, res);
   }
 #endif
 #endif
   // Check if the request URI doesn't exceed the limit
   if (line_reader.size() > CPPHTTPLIB_REQUEST_URI_MAX_LENGTH) {
     Headers dummy;
     detail::read_headers(strm, dummy);
     res.status = StatusCode::UriTooLong_414;
     return write_response(strm, close_connection, req, res);
   }
   // Request line and headers
   if (!parse_request_line(line_reader.ptr(), req) ||
       !detail::read_headers(strm, req.headers)) {
     res.status = StatusCode::BadRequest_400;
     return write_response(strm, close_connection, req, res);
   }
   if (req.get_header_value("Connection") == "close") {
     connection_closed = true;
   }
   if (req.version == "HTTP/1.0" &&
       req.get_header_value("Connection") != "Keep-Alive") {
     connection_closed = true;
   }
   strm.get_remote_ip_and_port(req.remote_addr, req.remote_port);
   req.set_header("REMOTE_ADDR", req.remote_addr);
   req.set_header("REMOTE_PORT", std::to_string(req.remote_port));
   strm.get_local_ip_and_port(req.local_addr, req.local_port);
   req.set_header("LOCAL_ADDR", req.local_addr);
   req.set_header("LOCAL_PORT", std::to_string(req.local_port));
   if (req.has_header("Range")) {
     const auto &range_header_value = req.get_header_value("Range");
     if (!detail::parse_range_header(range_header_value, req.ranges)) {
       res.status = StatusCode::RangeNotSatisfiable_416;
       return write_response(strm, close_connection, req, res);
     }
   }
   if (setup_request) { setup_request(req); }
   if (req.get_header_value("Expect") == "100-continue") {
     int status = StatusCode::Continue_100;
     if (expect_100_continue_handler_) {
       status = expect_100_continue_handler_(req, res);
     }
     switch (status) {
     case StatusCode::Continue_100:
     case StatusCode::ExpectationFailed_417:
       strm.write_format("HTTP/1.1 %d %s\r\n\r\n", status,
                         status_message(status));
       break;
     default: return write_response(strm, close_connection, req, res);
     }
   }
   // Routing
   auto routed = false;
 #ifdef CPPHTTPLIB_NO_EXCEPTIONS
   routed = routing(req, res, strm);
 #else
   try {
     routed = routing(req, res, strm);
   } catch (std::exception &e) {
     if (exception_handler_) {
       auto ep = std::current_exception();
       exception_handler_(req, res, ep);
       routed = true;
     } else {
       res.status = StatusCode::InternalServerError_500;
       std::string val;
       auto s = e.what();
       for (size_t i = 0; s[i]; i++) {
         switch (s[i]) {
         case '\r': val += "\\r"; break;
         case '\n': val += "\\n"; break;
         default: val += s[i]; break;
         }
       }
       res.set_header("EXCEPTION_WHAT", val);
     }
   } catch (...) {
     if (exception_handler_) {
       auto ep = std::current_exception();
       exception_handler_(req, res, ep);
       routed = true;
     } else {
       res.status = StatusCode::InternalServerError_500;
       res.set_header("EXCEPTION_WHAT", "UNKNOWN");
     }
   }
 #endif
   if (routed) {
     if (res.status == -1) {
       res.status = req.ranges.empty() ? StatusCode::OK_200
                                       : StatusCode::PartialContent_206;
     }
     if (detail::range_error(req, res)) {
       res.body.clear();
       res.content_length_ = 0;
       res.content_provider_ = nullptr;
       res.status = StatusCode::RangeNotSatisfiable_416;
       return write_response(strm, close_connection, req, res);
     }
     return write_response_with_content(strm, close_connection, req, res);
   } else {
     if (res.status == -1) { res.status = StatusCode::NotFound_404; }
     return write_response(strm, close_connection, req, res);
   }
 }
References httplib::BadRequest_400, httplib::Response::body, httplib::Response::content_length_, httplib::Response::content_provider_, httplib::Continue_100, CPPHTTPLIB_REQUEST_URI_MAX_LENGTH, default_headers_, exception_handler_, expect_100_continue_handler_, httplib::ExpectationFailed_417, httplib::Request::get_header_value(), httplib::Stream::get_local_ip_and_port(), httplib::Stream::get_remote_ip_and_port(), httplib::detail::stream_line_reader::getline(), httplib::Request::has_header(), httplib::Request::headers, httplib::Response::headers, httplib::InternalServerError_500, httplib::Request::local_addr, httplib::Request::local_port, httplib::NotFound_404, httplib::OK_200, httplib::detail::parse_range_header(), parse_request_line(), httplib::PartialContent_206, httplib::detail::stream_line_reader::ptr(), httplib::detail::range_error(), httplib::RangeNotSatisfiable_416, httplib::Request::ranges, httplib::detail::read_headers(), httplib::Request::remote_addr, httplib::Request::remote_port, routing(), httplib::Request::set_header(), httplib::Response::set_header(), httplib::detail::stream_line_reader::size(), httplib::Stream::socket(), httplib::Response::status, httplib::status_message(), httplib::to_string(), httplib::UriTooLong_414, httplib::Request::version, httplib::Response::version, httplib::Stream::write_format(), write_response(), and write_response_with_content().
Referenced by process_and_close_socket().
Put() [1/2]
Server & httplib::Server::Put (const std::string & pattern, Handler handler) inline
Definition at line 5715 of file httplib.h.
{
   put_handlers_.emplace_back(make_matcher(pattern), std::move(handler));
   return *this;
 }
References make_matcher(), and put_handlers_.
Put() [2/2]
Server & httplib::Server::Put (const std::string & pattern, HandlerWithContentReader handler) inline
Definition at line 5720 of file httplib.h.
{
   put_handlers_for_content_reader_.emplace_back(make_matcher(pattern),
                                                 std::move(handler));
   return *this;
 }
References make_matcher(), and put_handlers_for_content_reader_.
read_content()
bool httplib::Server::read_content (Stream & strm, Request & req, Response & res) inline private
Definition at line 6141 of file httplib.h.
{
   MultipartFormDataMap::iterator cur;
   auto file_count = 0;
   if (read_content_core(
           strm, req, res,
           // Regular
           [&](const char *buf, size_t n) {
             if (req.body.size() + n > req.body.max_size()) { return false; }
             req.body.append(buf, n);
             return true;
           },
           // Multipart
           [&](const MultipartFormData &file) {
             if (file_count++ == CPPHTTPLIB_MULTIPART_FORM_DATA_FILE_MAX_COUNT) {
               return false;
             }
             cur = req.files.emplace(file.name, file);
             return true;
           },
           [&](const char *buf, size_t n) {
             auto &content = cur->second.content;
             if (content.size() + n > content.max_size()) { return false; }
             content.append(buf, n);
             return true;
           })) {
     const auto &content_type = req.get_header_value("Content-Type");
     if (!content_type.find("application/x-www-form-urlencoded")) {
       if (req.body.size() > CPPHTTPLIB_FORM_URL_ENCODED_PAYLOAD_MAX_LENGTH) {
         res.status = StatusCode::PayloadTooLarge_413; // NOTE: should be 414?
         return false;
       }
       detail::parse_query_text(req.body, req.params);
     }
     return true;
   }
   return false;
 }
References httplib::Request::body, CPPHTTPLIB_FORM_URL_ENCODED_PAYLOAD_MAX_LENGTH, CPPHTTPLIB_MULTIPART_FORM_DATA_FILE_MAX_COUNT, httplib::Request::files, httplib::Request::get_header_value(), n, httplib::Request::params, httplib::detail::parse_query_text(), httplib::PayloadTooLarge_413, read_content_core(), and httplib::Response::status.
Referenced by routing().
read_content_core()
bool httplib::Server::read_content_core (Stream & strm, Request & req, Response & res, ContentReceiver receiver, MultipartContentHeader multipart_header, ContentReceiver multipart_receiver) const inline private
Definition at line 6189 of file httplib.h.
{
   detail::MultipartFormDataParser multipart_form_data_parser;
   ContentReceiverWithProgress out;
   if (req.is_multipart_form_data()) {
     const auto &content_type = req.get_header_value("Content-Type");
     std::string boundary;
     if (!detail::parse_multipart_boundary(content_type, boundary)) {
       res.status = StatusCode::BadRequest_400;
       return false;
     }
     multipart_form_data_parser.set_boundary(std::move(boundary));
     out = [&](const char *buf, size_t n, uint64_t /*off*/, uint64_t /*len*/) {
       /* For debug
       size_t pos = 0;
       while (pos < n) {
         auto read_size = (std::min)<size_t>(1, n - pos);
         auto ret = multipart_form_data_parser.parse(
             buf + pos, read_size, multipart_receiver, multipart_header);
         if (!ret) { return false; }
         pos += read_size;
       }
       return true;
       */
       return multipart_form_data_parser.parse(buf, n, multipart_receiver,
                                               multipart_header);
     };
   } else {
     out = [receiver](const char *buf, size_t n, uint64_t /*off*/,
                      uint64_t /*len*/) { return receiver(buf, n); };
   }
   if (req.method == "DELETE" && !req.has_header("Content-Length")) {
     return true;
   }
   if (!detail::read_content(strm, req, payload_max_length_, res.status, nullptr,
                             out, true)) {
     return false;
   }
   if (req.is_multipart_form_data()) {
     if (!multipart_form_data_parser.is_valid()) {
       res.status = StatusCode::BadRequest_400;
       return false;
     }
   }
   return true;
 }
References httplib::BadRequest_400, httplib::Request::get_header_value(), httplib::Request::has_header(), httplib::Request::is_multipart_form_data(), httplib::detail::MultipartFormDataParser::is_valid(), httplib::Request::method, n, httplib::detail::MultipartFormDataParser::parse(), httplib::detail::parse_multipart_boundary(), payload_max_length_, httplib::detail::read_content(), httplib::detail::MultipartFormDataParser::set_boundary(), and httplib::Response::status.
Referenced by read_content(), and read_content_with_content_receiver().
read_content_with_content_receiver()
bool httplib::Server::read_content_with_content_receiver (Stream & strm, Request & req, Response & res, ContentReceiver receiver, MultipartContentHeader multipart_header, ContentReceiver multipart_receiver) inline private
Definition at line 6179 of file httplib.h.
{
   return read_content_core(strm, req, res, std::move(receiver),
                            std::move(multipart_header),
                            std::move(multipart_receiver));
 }
References read_content_core().
Referenced by routing().
remove_mount_point()
bool httplib::Server::remove_mount_point (const std::string & mount_point) inline
Definition at line 5773 of file httplib.h.
{
   for (auto it = base_dirs_.begin(); it != base_dirs_.end(); ++it) {
     if (it->mount_point == mount_point) {
       base_dirs_.erase(it);
       return true;
     }
   }
   return false;
 }
References base_dirs_.
routing()
bool httplib::Server::routing (Request & req, Response & res, Stream & strm) inline private
Definition at line 6409 of file httplib.h.
{
   if (pre_routing_handler_ &&
       pre_routing_handler_(req, res) == HandlerResponse::Handled) {
     return true;
   }
   // File handler
   auto is_head_request = req.method == "HEAD";
   if ((req.method == "GET" || is_head_request) &&
       handle_file_request(req, res, is_head_request)) {
     return true;
   }
   if (detail::expect_content(req)) {
     // Content reader handler
     {
       ContentReader reader(
           [&](ContentReceiver receiver) {
             return read_content_with_content_receiver(
                 strm, req, res, std::move(receiver), nullptr, nullptr);
           },
           [&](MultipartContentHeader header, ContentReceiver receiver) {
             return read_content_with_content_receiver(strm, req, res, nullptr,
                                                       std::move(header),
                                                       std::move(receiver));
           });
       if (req.method == "POST") {
         if (dispatch_request_for_content_reader(
                 req, res, std::move(reader),
                 post_handlers_for_content_reader_)) {
           return true;
         }
       } else if (req.method == "PUT") {
         if (dispatch_request_for_content_reader(
                 req, res, std::move(reader),
                 put_handlers_for_content_reader_)) {
           return true;
         }
       } else if (req.method == "PATCH") {
         if (dispatch_request_for_content_reader(
                 req, res, std::move(reader),
                 patch_handlers_for_content_reader_)) {
           return true;
         }
       } else if (req.method == "DELETE") {
         if (dispatch_request_for_content_reader(
                 req, res, std::move(reader),
                 delete_handlers_for_content_reader_)) {
           return true;
         }
       }
     }
     // Read content into `req.body`
     if (!read_content(strm, req, res)) { return false; }
   }
   // Regular handler
   if (req.method == "GET" || req.method == "HEAD") {
     return dispatch_request(req, res, get_handlers_);
   } else if (req.method == "POST") {
     return dispatch_request(req, res, post_handlers_);
   } else if (req.method == "PUT") {
     return dispatch_request(req, res, put_handlers_);
   } else if (req.method == "DELETE") {
     return dispatch_request(req, res, delete_handlers_);
   } else if (req.method == "OPTIONS") {
     return dispatch_request(req, res, options_handlers_);
   } else if (req.method == "PATCH") {
     return dispatch_request(req, res, patch_handlers_);
   }
   res.status = StatusCode::BadRequest_400;
   return false;
 }
References httplib::BadRequest_400, delete_handlers_, delete_handlers_for_content_reader_, dispatch_request(), dispatch_request_for_content_reader(), httplib::detail::expect_content(), get_handlers_, handle_file_request(), Handled, httplib::Request::method, options_handlers_, patch_handlers_, patch_handlers_for_content_reader_, post_handlers_, post_handlers_for_content_reader_, pre_routing_handler_, put_handlers_, put_handlers_for_content_reader_, read_content(), read_content_with_content_receiver(), and httplib::Response::status.
Referenced by process_request().
set_address_family()
Server & httplib::Server::set_address_family (int family) inline
Definition at line 5839 of file httplib.h.
{
   address_family_ = family;
   return *this;
 }
References address_family_.
set_base_dir()
bool httplib::Server::set_base_dir (const std::string & dir, const std::string & mount_point = std::string()) inline
Definition at line 5756 of file httplib.h.
{
   return set_mount_point(mount_point, dir);
 }
References set_mount_point().
set_default_file_mimetype()
Server & httplib::Server::set_default_file_mimetype (const std::string & mime) inline
Definition at line 5790 of file httplib.h.
{
   default_file_mimetype_ = mime;
   return *this;
 }
References default_file_mimetype_.
set_default_headers()
Server & httplib::Server::set_default_headers (Headers headers) inline
Definition at line 5854 of file httplib.h.
{
   default_headers_ = std::move(headers);
   return *this;
 }
References default_headers_.
set_error_handler() [1/2]
Server & httplib::Server::set_error_handler (Handler handler) inline
Definition at line 5805 of file httplib.h.
{
   error_handler_ = [handler](const Request &req, Response &res) {
     handler(req, res);
     return HandlerResponse::Handled;
   };
   return *this;
 }
References error_handler_, and Handled.
set_error_handler() [2/2]
Server & httplib::Server::set_error_handler (HandlerWithResponse handler) inline
Definition at line 5800 of file httplib.h.
{
   error_handler_ = std::move(handler);
   return *this;
 }
References error_handler_.
set_exception_handler()
Server & httplib::Server::set_exception_handler (ExceptionHandler handler) inline
Definition at line 5813 of file httplib.h.
{
   exception_handler_ = std::move(handler);
   return *this;
 }
References exception_handler_.
set_expect_100_continue_handler()
Server & httplib::Server::set_expect_100_continue_handler (Expect100ContinueHandler handler) inline
Definition at line 5834 of file httplib.h.
{
   expect_100_continue_handler_ = std::move(handler);
   return *this;
 }
References expect_100_continue_handler_.
set_file_extension_and_mimetype_mapping()
Server & httplib::Server::set_file_extension_and_mimetype_mapping (const std::string & ext, const std::string & mime) inline
Definition at line 5784 of file httplib.h.
{
   file_extension_and_mimetype_map_[ext] = mime;
   return *this;
 }
References file_extension_and_mimetype_map_.
set_file_request_handler()
Server & httplib::Server::set_file_request_handler (Handler handler) inline
Definition at line 5795 of file httplib.h.
{
   file_request_handler_ = std::move(handler);
   return *this;
 }
References file_request_handler_.
set_header_writer()
Server & httplib::Server::set_header_writer (std::function< ssize_t(Stream &, Headers &)> const & writer) inline
Definition at line 5859 of file httplib.h.
{
   header_writer_ = writer;
   return *this;
 }
References header_writer_.
set_idle_interval() [1/2]
template<class Rep , class Period > Server & httplib::Server::set_idle_interval (const std::chrono::duration< Rep, Period > & duration) inline
Definition at line 1980 of file httplib.h.
{
   detail::duration_to_sec_and_usec(
       duration, [&](time_t sec, time_t usec) { set_idle_interval(sec, usec); });
   return *this;
 }
References httplib::detail::duration_to_sec_and_usec(), sec, and set_idle_interval().
set_idle_interval() [2/2]
Server & httplib::Server::set_idle_interval (time_t sec, time_t usec = 0) inline
Definition at line 5887 of file httplib.h.
{
   idle_interval_sec_ = sec;
   idle_interval_usec_ = usec;
   return *this;
 }
References idle_interval_sec_, idle_interval_usec_, and sec.
Referenced by set_idle_interval().
set_keep_alive_max_count()
Server & httplib::Server::set_keep_alive_max_count (size_t count) inline
Definition at line 5865 of file httplib.h.
{
   keep_alive_max_count_ = count;
   return *this;
 }
References keep_alive_max_count_.
set_keep_alive_timeout()
Server & httplib::Server::set_keep_alive_timeout (time_t sec) inline
Definition at line 5870 of file httplib.h.
{
   keep_alive_timeout_sec_ = sec;
   return *this;
 }
References keep_alive_timeout_sec_, and sec.
set_logger()
Server & httplib::Server::set_logger (Logger logger) inline
Definition at line 5828 of file httplib.h.
{
   logger_ = std::move(logger);
   return *this;
 }
References logger_.
set_mount_point()
bool httplib::Server::set_mount_point (const std::string & mount_point, const std::string & dir, Headers headers = Headers()) inline
Definition at line 5761 of file httplib.h.
{
   if (detail::is_dir(dir)) {
     std::string mnt = !mount_point.empty() ? mount_point : "/";
     if (!mnt.empty() && mnt[0] == '/') {
       base_dirs_.push_back({mnt, dir, std::move(headers)});
       return true;
     }
   }
   return false;
 }
References base_dirs_, and httplib::detail::is_dir().
Referenced by set_base_dir().
set_payload_max_length()
Server & httplib::Server::set_payload_max_length (size_t length) inline
Definition at line 5893 of file httplib.h.
{
   payload_max_length_ = length;
   return *this;
 }
References payload_max_length_.
set_post_routing_handler()
Server & httplib::Server::set_post_routing_handler (Handler handler) inline
Definition at line 5823 of file httplib.h.
{
   post_routing_handler_ = std::move(handler);
   return *this;
 }
References post_routing_handler_.
set_pre_routing_handler()
Server & httplib::Server::set_pre_routing_handler (HandlerWithResponse handler) inline
Definition at line 5818 of file httplib.h.
{
   pre_routing_handler_ = std::move(handler);
   return *this;
 }
References pre_routing_handler_.
set_read_timeout() [1/2]
template<class Rep , class Period > Server & httplib::Server::set_read_timeout (const std::chrono::duration< Rep, Period > & duration) inline
Definition at line 1964 of file httplib.h.
{
   detail::duration_to_sec_and_usec(
       duration, [&](time_t sec, time_t usec) { set_read_timeout(sec, usec); });
   return *this;
 }
References httplib::detail::duration_to_sec_and_usec(), sec, and set_read_timeout().
set_read_timeout() [2/2]
Server & httplib::Server::set_read_timeout (time_t sec, time_t usec = 0) inline
Definition at line 5875 of file httplib.h.
{
   read_timeout_sec_ = sec;
   read_timeout_usec_ = usec;
   return *this;
 }
References read_timeout_sec_, read_timeout_usec_, and sec.
Referenced by set_read_timeout().
set_socket_options()
Server & httplib::Server::set_socket_options (SocketOptions socket_options) inline
Definition at line 5849 of file httplib.h.
{
   socket_options_ = std::move(socket_options);
   return *this;
 }
References socket_options_.
set_tcp_nodelay()
Server & httplib::Server::set_tcp_nodelay (bool on) inline
Definition at line 5844 of file httplib.h.
{
   tcp_nodelay_ = on;
   return *this;
 }
References tcp_nodelay_.
set_write_timeout() [1/2]
template<class Rep , class Period > Server & httplib::Server::set_write_timeout (const std::chrono::duration< Rep, Period > & duration) inline
Definition at line 1972 of file httplib.h.
{
   detail::duration_to_sec_and_usec(
       duration, [&](time_t sec, time_t usec) { set_write_timeout(sec, usec); });
   return *this;
 }
References httplib::detail::duration_to_sec_and_usec(), sec, and set_write_timeout().
set_write_timeout() [2/2]
Server & httplib::Server::set_write_timeout (time_t sec, time_t usec = 0) inline
Definition at line 5881 of file httplib.h.
{
   write_timeout_sec_ = sec;
   write_timeout_usec_ = usec;
   return *this;
 }
References sec, write_timeout_sec_, and write_timeout_usec_.
Referenced by set_write_timeout().
stop()
void httplib::Server::stop () inline
Definition at line 5925 of file httplib.h.
{
   if (is_running_) {
     assert(svr_sock_ != INVALID_SOCKET);
     std::atomic<socket_t> sock(svr_sock_.exchange(INVALID_SOCKET));
     detail::shutdown_socket(sock);
     detail::close_socket(sock);
   }
 }
References assert(), httplib::detail::close_socket(), INVALID_SOCKET, is_running_, httplib::detail::shutdown_socket(), and svr_sock_.
wait_until_ready()
void httplib::Server::wait_until_ready () const inline
Definition at line 5919 of file httplib.h.
{
   while (!is_running() && !done_) {
     std::this_thread::sleep_for(std::chrono::milliseconds{1});
   }
 }
References done_, and is_running().
write_content_with_provider()
bool httplib::Server::write_content_with_provider (Stream & strm, const Request & req, Response & res, const std::string & boundary, const std::string & content_type) inline private
Definition at line 6091 of file httplib.h.
{
   auto is_shutting_down = [this]() {
     return this->svr_sock_ == INVALID_SOCKET;
   };
   if (res.content_length_ > 0) {
     if (req.ranges.empty()) {
       return detail::write_content(strm, res.content_provider_, 0,
                                    res.content_length_, is_shutting_down);
     } else if (req.ranges.size() == 1) {
       auto offset_and_length = detail::get_range_offset_and_length(
           req.ranges[0], res.content_length_);
       return detail::write_content(strm, res.content_provider_,
                                    offset_and_length.first,
                                    offset_and_length.second, is_shutting_down);
     } else {
       return detail::write_multipart_ranges_data(
           strm, req, res, boundary, content_type, res.content_length_,
           is_shutting_down);
     }
   } else {
     if (res.is_chunked_content_provider_) {
       auto type = detail::encoding_type(req, res);
       std::unique_ptr<detail::compressor> compressor;
       if (type == detail::EncodingType::Gzip) {
 #ifdef CPPHTTPLIB_ZLIB_SUPPORT
         compressor = detail::make_unique<detail::gzip_compressor>();
 #endif
       } else if (type == detail::EncodingType::Brotli) {
 #ifdef CPPHTTPLIB_BROTLI_SUPPORT
         compressor = detail::make_unique<detail::brotli_compressor>();
 #endif
       } else {
         compressor = detail::make_unique<detail::nocompressor>();
       }
       assert(compressor != nullptr);
       return detail::write_content_chunked(strm, res.content_provider_,
                                            is_shutting_down, *compressor);
     } else {
       return detail::write_content_without_length(strm, res.content_provider_,
                                                   is_shutting_down);
     }
   }
 }
References assert(), httplib::detail::Brotli, httplib::Response::content_length_, httplib::Response::content_provider_, httplib::detail::encoding_type(), httplib::detail::get_range_offset_and_length(), httplib::detail::Gzip, INVALID_SOCKET, httplib::Response::is_chunked_content_provider_, httplib::Request::ranges, svr_sock_, httplib::detail::write_content(), httplib::detail::write_content_chunked(), httplib::detail::write_content_without_length(), and httplib::detail::write_multipart_ranges_data().
Referenced by write_response_core().
write_response()
bool httplib::Server::write_response (Stream & strm, bool close_connection, Request & req, Response & res) inline private
Definition at line 5997 of file httplib.h.
{
   // NOTE: `req.ranges` should be empty, otherwise it will be applied
   // incorrectly to the error content.
   req.ranges.clear();
   return write_response_core(strm, close_connection, req, res, false);
 }
References httplib::Request::ranges, and write_response_core().
Referenced by process_request().
write_response_core()
bool httplib::Server::write_response_core (Stream & strm, bool close_connection, const Request & req, Response & res, bool need_apply_ranges) inline private
Definition at line 6012 of file httplib.h.
{
   assert(res.status != -1);
   if (400 <= res.status && error_handler_ &&
       error_handler_(req, res) == HandlerResponse::Handled) {
     need_apply_ranges = true;
   }
   std::string content_type;
   std::string boundary;
   if (need_apply_ranges) { apply_ranges(req, res, content_type, boundary); }
   // Prepare additional headers
   if (close_connection || req.get_header_value("Connection") == "close") {
     res.set_header("Connection", "close");
   } else {
     std::stringstream ss;
     ss << "timeout=" << keep_alive_timeout_sec_
        << ", max=" << keep_alive_max_count_;
     res.set_header("Keep-Alive", ss.str());
   }
   if (!res.has_header("Content-Type") &&
       (!res.body.empty() || res.content_length_ > 0 || res.content_provider_)) {
     res.set_header("Content-Type", "text/plain");
   }
   if (!res.has_header("Content-Length") && res.body.empty() &&
       !res.content_length_ && !res.content_provider_) {
     res.set_header("Content-Length", "0");
   }
   if (!res.has_header("Accept-Ranges") && req.method == "HEAD") {
     res.set_header("Accept-Ranges", "bytes");
   }
   if (post_routing_handler_) { post_routing_handler_(req, res); }
   // Response line and headers
   {
     detail::BufferStream bstrm;
     if (!bstrm.write_format("HTTP/1.1 %d %s\r\n", res.status,
                             status_message(res.status))) {
       return false;
     }
     if (!header_writer_(bstrm, res.headers)) { return false; }
     // Flush buffer
     auto &data = bstrm.get_buffer();
     detail::write_data(strm, data.data(), data.size());
   }
   // Body
   auto ret = true;
   if (req.method != "HEAD") {
     if (!res.body.empty()) {
       if (!detail::write_data(strm, res.body.data(), res.body.size())) {
         ret = false;
       }
     } else if (res.content_provider_) {
       if (write_content_with_provider(strm, req, res, boundary, content_type)) {
         res.content_provider_success_ = true;
       } else {
         ret = false;
       }
     }
   }
   // Log
   if (logger_) { logger_(req, res); }
   return ret;
 }
References apply_ranges(), assert(), httplib::Response::body, httplib::Response::content_length_, httplib::Response::content_provider_, httplib::Response::content_provider_success_, error_handler_, httplib::detail::BufferStream::get_buffer(), httplib::Request::get_header_value(), Handled, httplib::Response::has_header(), header_writer_, httplib::Response::headers, keep_alive_max_count_, keep_alive_timeout_sec_, logger_, httplib::Request::method, post_routing_handler_, httplib::Response::set_header(), ss, httplib::Response::status, httplib::status_message(), write_content_with_provider(), httplib::detail::write_data(), and httplib::Stream::write_format().
Referenced by write_response(), and write_response_with_content().
write_response_with_content()
bool httplib::Server::write_response_with_content (Stream & strm, bool close_connection, const Request & req, Response & res) inline private
Definition at line 6005 of file httplib.h.
{
   return write_response_core(strm, close_connection, req, res, true);
 }
References write_response_core().
Referenced by process_request().
Member Data Documentation
address_family_
int httplib::Server::address_family_ = AF_UNSPEC private
Definition at line 1019 of file httplib.h.
Referenced by create_server_socket(), and set_address_family().
base_dirs_
std::vector<MountPointEntry> httplib::Server::base_dirs_ private
Definition at line 995 of file httplib.h.
Referenced by handle_file_request(), remove_mount_point(), and set_mount_point().
default_file_mimetype_
std::string httplib::Server::default_file_mimetype_ = "application/octet-stream" private
Definition at line 997 of file httplib.h.
Referenced by handle_file_request(), and set_default_file_mimetype().
default_headers_
Headers httplib::Server::default_headers_ private
Definition at line 1023 of file httplib.h.
Referenced by process_request(), and set_default_headers().
delete_handlers_
Handlers httplib::Server::delete_handlers_ private
Definition at line 1007 of file httplib.h.
Referenced by Delete(), and routing().
delete_handlers_for_content_reader_
HandlersForContentReader httplib::Server::delete_handlers_for_content_reader_ private
Definition at line 1008 of file httplib.h.
Referenced by Delete(), and routing().
done_
std::atomic<bool> httplib::Server::done_ {false} private
Definition at line 988 of file httplib.h.
Referenced by listen(), listen_after_bind(), and wait_until_ready().
error_handler_
HandlerWithResponse httplib::Server::error_handler_ private
Definition at line 1011 of file httplib.h.
Referenced by set_error_handler(), and write_response_core().
exception_handler_
ExceptionHandler httplib::Server::exception_handler_ private
Definition at line 1012 of file httplib.h.
Referenced by process_request(), and set_exception_handler().
expect_100_continue_handler_
Expect100ContinueHandler httplib::Server::expect_100_continue_handler_ private
Definition at line 1015 of file httplib.h.
Referenced by process_request(), and set_expect_100_continue_handler().
file_extension_and_mimetype_map_
std::map<std::string, std::string> httplib::Server::file_extension_and_mimetype_map_ private
Definition at line 996 of file httplib.h.
Referenced by handle_file_request(), and set_file_extension_and_mimetype_mapping().
file_request_handler_
Handler httplib::Server::file_request_handler_ private
Definition at line 998 of file httplib.h.
Referenced by handle_file_request(), and set_file_request_handler().
get_handlers_
Handlers httplib::Server::get_handlers_ private
Definition at line 1000 of file httplib.h.
Referenced by Get(), and routing().
header_writer_
std::function<ssize_t(Stream &, Headers &)> httplib::Server::header_writer_ private
Initial value:
=
      detail::write_headers
Definition at line 1024 of file httplib.h.
Referenced by set_header_writer(), and write_response_core().
idle_interval_sec_
time_t httplib::Server::idle_interval_sec_ = 0 protected
Definition at line 932 of file httplib.h.
Referenced by listen_internal(), and set_idle_interval().
idle_interval_usec_
time_t httplib::Server::idle_interval_usec_ = 0 protected
Definition at line 933 of file httplib.h.
Referenced by listen_internal(), and set_idle_interval().
is_running_
std::atomic<bool> httplib::Server::is_running_ {false} private
Definition at line 987 of file httplib.h.
Referenced by is_running(), listen_internal(), and stop().
keep_alive_max_count_
size_t httplib::Server::keep_alive_max_count_ = 5 protected
Definition at line 926 of file httplib.h.
Referenced by process_and_close_socket(), set_keep_alive_max_count(), and write_response_core().
keep_alive_timeout_sec_
time_t httplib::Server::keep_alive_timeout_sec_ = 5 protected
Definition at line 927 of file httplib.h.
Referenced by process_and_close_socket(), set_keep_alive_timeout(), and write_response_core().
logger_
Logger httplib::Server::logger_ private
Definition at line 1017 of file httplib.h.
Referenced by set_logger(), and write_response_core().
new_task_queue
std::function<TaskQueue *(void)> httplib::Server::new_task_queue
Definition at line 918 of file httplib.h.
Referenced by listen_internal().
options_handlers_
Handlers httplib::Server::options_handlers_ private
Definition at line 1009 of file httplib.h.
Referenced by Options(), and routing().
patch_handlers_
Handlers httplib::Server::patch_handlers_ private
Definition at line 1005 of file httplib.h.
Referenced by Patch(), and routing().
patch_handlers_for_content_reader_
HandlersForContentReader httplib::Server::patch_handlers_for_content_reader_ private
Definition at line 1006 of file httplib.h.
Referenced by Patch(), and routing().
payload_max_length_
size_t httplib::Server::payload_max_length_ = ((std::numeric_limits<size_t>::max)()) protected
Definition at line 934 of file httplib.h.
Referenced by read_content_core(), and set_payload_max_length().
post_handlers_
Handlers httplib::Server::post_handlers_ private
Definition at line 1001 of file httplib.h.
Referenced by Post(), and routing().
post_handlers_for_content_reader_
HandlersForContentReader httplib::Server::post_handlers_for_content_reader_ private
Definition at line 1002 of file httplib.h.
Referenced by Post(), and routing().
post_routing_handler_
Handler httplib::Server::post_routing_handler_ private
Definition at line 1014 of file httplib.h.
Referenced by set_post_routing_handler(), and write_response_core().
pre_routing_handler_
HandlerWithResponse httplib::Server::pre_routing_handler_ private
Definition at line 1013 of file httplib.h.
Referenced by routing(), and set_pre_routing_handler().
put_handlers_
Handlers httplib::Server::put_handlers_ private
Definition at line 1003 of file httplib.h.
Referenced by Put(), and routing().
put_handlers_for_content_reader_
HandlersForContentReader httplib::Server::put_handlers_for_content_reader_ private
Definition at line 1004 of file httplib.h.
Referenced by Put(), and routing().
read_timeout_sec_
time_t httplib::Server::read_timeout_sec_ = 5 protected
Definition at line 928 of file httplib.h.
Referenced by listen_internal(), process_and_close_socket(), and set_read_timeout().
read_timeout_usec_
time_t httplib::Server::read_timeout_usec_ = 0 protected
Definition at line 929 of file httplib.h.
Referenced by listen_internal(), process_and_close_socket(), and set_read_timeout().
socket_options_
SocketOptions httplib::Server::socket_options_ = default_socket_options private
Definition at line 1021 of file httplib.h.
Referenced by bind_internal(), and set_socket_options().
svr_sock_
std::atomic<socket_t> httplib::Server::svr_sock_ { (-1) } protected
Definition at line 925 of file httplib.h.
Referenced by bind_internal(), listen_internal(), process_and_close_socket(), stop(), and write_content_with_provider().
tcp_nodelay_
bool httplib::Server::tcp_nodelay_ = false private
Definition at line 1020 of file httplib.h.
Referenced by create_server_socket(), and set_tcp_nodelay().
write_timeout_sec_
time_t httplib::Server::write_timeout_sec_ = 5 protected
Definition at line 930 of file httplib.h.
Referenced by listen_internal(), process_and_close_socket(), and set_write_timeout().
write_timeout_usec_
time_t httplib::Server::write_timeout_usec_ = 0 protected
Definition at line 931 of file httplib.h.
Referenced by listen_internal(), process_and_close_socket(), and set_write_timeout().
The documentation for this class was generated from the following file:
mc_orchestrator/httplib/httplib.h