Mixed Criticality Orchestrator: httplib::DataSink Class Reference
httplib::DataSink Class Reference
#include <httplib.h>
Classes
class data_sink_streambuf
Public Member Functions
DataSink ()
DataSink (const DataSink &)=delete
DataSink & operator= (const DataSink &)=delete
DataSink (DataSink &&)=delete
DataSink & operator= (DataSink &&)=delete
Public Attributes
std::function< bool(const char *data, size_t data_len)> write
std::function< bool()> is_writable
std::function< void()> done
std::function< void(const Headers &trailer)> done_with_trailer
std::ostream os
Private Attributes
data_sink_streambuf sb_
Detailed Description
Definition at line 449 of file httplib.h.
Constructor & Destructor Documentation
DataSink() [1/3]
httplib::DataSink::DataSink () inline
Definition at line 451 of file httplib.h.
 : os(&sb_), sb_(*this) {}
DataSink() [2/3]
httplib::DataSink::DataSink (const DataSink &) delete
DataSink() [3/3]
httplib::DataSink::DataSink (DataSink &&) delete
Member Function Documentation
operator=() [1/2]
DataSink& httplib::DataSink::operator= (const DataSink &) delete
operator=() [2/2]
DataSink& httplib::DataSink::operator= (DataSink &&) delete
Member Data Documentation
done
std::function<void()> httplib::DataSink::done
Definition at line 460 of file httplib.h.
Referenced by httplib::ClientImpl::get_multipart_content_provider(), httplib::detail::write_content_chunked(), and httplib::detail::write_content_without_length().
done_with_trailer
std::function<void(const Headers &trailer)> httplib::DataSink::done_with_trailer
Definition at line 461 of file httplib.h.
Referenced by httplib::detail::write_content_chunked().
is_writable
std::function<bool()> httplib::DataSink::is_writable
Definition at line 459 of file httplib.h.
Referenced by httplib::detail::write_content(), httplib::detail::write_content_chunked(), and httplib::detail::write_content_without_length().
os
std::ostream httplib::DataSink::os
Definition at line 462 of file httplib.h.
sb_
data_sink_streambuf httplib::DataSink::sb_ private
Definition at line 479 of file httplib.h.
write
std::function<bool(const char *data, size_t data_len)> httplib::DataSink::write
Definition at line 458 of file httplib.h.
Referenced by httplib::ClientImpl::get_multipart_content_provider(), httplib::ClientImpl::send_with_content_provider(), httplib::detail::write_content(), httplib::detail::write_content_chunked(), httplib::detail::write_content_without_length(), and httplib::DataSink::data_sink_streambuf::xsputn().
The documentation for this class was generated from the following file:
mc_orchestrator/httplib/httplib.h