Mixed Criticality Orchestrator: httplib::ClientImpl Class Reference
httplib::ClientImpl Class Reference
#include <httplib.h>
Classes
struct Socket
Public Member Functions
ClientImpl (const std::string &host)
ClientImpl (const std::string &host, int port)
ClientImpl (const std::string &host, int port, const std::string &client_cert_path, const std::string &client_key_path)
virtual ~ClientImpl ()
virtual bool is_valid () const
Result Get (const std::string &path)
Result Get (const std::string &path, const Headers &headers)
Result Get (const std::string &path, Progress progress)
Result Get (const std::string &path, const Headers &headers, Progress progress)
Result Get (const std::string &path, ContentReceiver content_receiver)
Result Get (const std::string &path, const Headers &headers, ContentReceiver content_receiver)
Result Get (const std::string &path, ContentReceiver content_receiver, Progress progress)
Result Get (const std::string &path, const Headers &headers, ContentReceiver content_receiver, Progress progress)
Result Get (const std::string &path, ResponseHandler response_handler, ContentReceiver content_receiver)
Result Get (const std::string &path, const Headers &headers, ResponseHandler response_handler, ContentReceiver content_receiver)
Result Get (const std::string &path, ResponseHandler response_handler, ContentReceiver content_receiver, Progress progress)
Result Get (const std::string &path, const Headers &headers, ResponseHandler response_handler, ContentReceiver content_receiver, Progress progress)
Result Get (const std::string &path, const Params &params, const Headers &headers, Progress progress=nullptr)
Result Get (const std::string &path, const Params &params, const Headers &headers, ContentReceiver content_receiver, Progress progress=nullptr)
Result Get (const std::string &path, const Params &params, const Headers &headers, ResponseHandler response_handler, ContentReceiver content_receiver, Progress progress=nullptr)
Result Head (const std::string &path)
Result Head (const std::string &path, const Headers &headers)
Result Post (const std::string &path)
Result Post (const std::string &path, const Headers &headers)
Result Post (const std::string &path, const char *body, size_t content_length, const std::string &content_type)
Result Post (const std::string &path, const Headers &headers, const char *body, size_t content_length, const std::string &content_type)
Result Post (const std::string &path, const std::string &body, const std::string &content_type)
Result Post (const std::string &path, const Headers &headers, const std::string &body, const std::string &content_type)
Result Post (const std::string &path, size_t content_length, ContentProvider content_provider, const std::string &content_type)
Result Post (const std::string &path, ContentProviderWithoutLength content_provider, const std::string &content_type)
Result Post (const std::string &path, const Headers &headers, size_t content_length, ContentProvider content_provider, const std::string &content_type)
Result Post (const std::string &path, const Headers &headers, ContentProviderWithoutLength content_provider, const std::string &content_type)
Result Post (const std::string &path, const Params &params)
Result Post (const std::string &path, const Headers &headers, const Params &params)
Result Post (const std::string &path, const MultipartFormDataItems &items)
Result Post (const std::string &path, const Headers &headers, const MultipartFormDataItems &items)
Result Post (const std::string &path, const Headers &headers, const MultipartFormDataItems &items, const std::string &boundary)
Result Post (const std::string &path, const Headers &headers, const MultipartFormDataItems &items, const MultipartFormDataProviderItems &provider_items)
Result Put (const std::string &path)
Result Put (const std::string &path, const char *body, size_t content_length, const std::string &content_type)
Result Put (const std::string &path, const Headers &headers, const char *body, size_t content_length, const std::string &content_type)
Result Put (const std::string &path, const std::string &body, const std::string &content_type)
Result Put (const std::string &path, const Headers &headers, const std::string &body, const std::string &content_type)
Result Put (const std::string &path, size_t content_length, ContentProvider content_provider, const std::string &content_type)
Result Put (const std::string &path, ContentProviderWithoutLength content_provider, const std::string &content_type)
Result Put (const std::string &path, const Headers &headers, size_t content_length, ContentProvider content_provider, const std::string &content_type)
Result Put (const std::string &path, const Headers &headers, ContentProviderWithoutLength content_provider, const std::string &content_type)
Result Put (const std::string &path, const Params &params)
Result Put (const std::string &path, const Headers &headers, const Params &params)
Result Put (const std::string &path, const MultipartFormDataItems &items)
Result Put (const std::string &path, const Headers &headers, const MultipartFormDataItems &items)
Result Put (const std::string &path, const Headers &headers, const MultipartFormDataItems &items, const std::string &boundary)
Result Put (const std::string &path, const Headers &headers, const MultipartFormDataItems &items, const MultipartFormDataProviderItems &provider_items)
Result Patch (const std::string &path)
Result Patch (const std::string &path, const char *body, size_t content_length, const std::string &content_type)
Result Patch (const std::string &path, const Headers &headers, const char *body, size_t content_length, const std::string &content_type)
Result Patch (const std::string &path, const std::string &body, const std::string &content_type)
Result Patch (const std::string &path, const Headers &headers, const std::string &body, const std::string &content_type)
Result Patch (const std::string &path, size_t content_length, ContentProvider content_provider, const std::string &content_type)
Result Patch (const std::string &path, ContentProviderWithoutLength content_provider, const std::string &content_type)
Result Patch (const std::string &path, const Headers &headers, size_t content_length, ContentProvider content_provider, const std::string &content_type)
Result Patch (const std::string &path, const Headers &headers, ContentProviderWithoutLength content_provider, const std::string &content_type)
Result Delete (const std::string &path)
Result Delete (const std::string &path, const Headers &headers)
Result Delete (const std::string &path, const char *body, size_t content_length, const std::string &content_type)
Result Delete (const std::string &path, const Headers &headers, const char *body, size_t content_length, const std::string &content_type)
Result Delete (const std::string &path, const std::string &body, const std::string &content_type)
Result Delete (const std::string &path, const Headers &headers, const std::string &body, const std::string &content_type)
Result Options (const std::string &path)
Result Options (const std::string &path, const Headers &headers)
bool send (Request &req, Response &res, Error &error)
Result send (const Request &req)
void stop ()
std::string host () const
int port () const
size_t is_socket_open () const
socket_t socket () const
void set_hostname_addr_map (std::map< std::string, std::string > addr_map)
void set_default_headers (Headers headers)
void set_header_writer (std::function< ssize_t(Stream &, Headers &)> const &writer)
void set_address_family (int family)
void set_tcp_nodelay (bool on)
void set_socket_options (SocketOptions socket_options)
void set_connection_timeout (time_t sec, time_t usec=0)
template<class Rep , class Period >
void set_connection_timeout (const std::chrono::duration< Rep, Period > &duration)
void set_read_timeout (time_t sec, time_t usec=0)
template<class Rep , class Period >
void set_read_timeout (const std::chrono::duration< Rep, Period > &duration)
void set_write_timeout (time_t sec, time_t usec=0)
template<class Rep , class Period >
void set_write_timeout (const std::chrono::duration< Rep, Period > &duration)
void set_basic_auth (const std::string &username, const std::string &password)
void set_bearer_token_auth (const std::string &token)
void set_keep_alive (bool on)
void set_follow_location (bool on)
void set_url_encode (bool on)
void set_compress (bool on)
void set_decompress (bool on)
void set_interface (const std::string &intf)
void set_proxy (const std::string &host, int port)
void set_proxy_basic_auth (const std::string &username, const std::string &password)
void set_proxy_bearer_token_auth (const std::string &token)
void set_logger (Logger logger)
Protected Member Functions
virtual bool create_and_connect_socket (Socket &socket, Error &error)
virtual void shutdown_ssl (Socket &socket, bool shutdown_gracefully)
void shutdown_socket (Socket &socket) const
void close_socket (Socket &socket)
bool process_request (Stream &strm, Request &req, Response &res, bool close_connection, Error &error)
bool write_content_with_provider (Stream &strm, const Request &req, Error &error) const
void copy_settings (const ClientImpl &rhs)
Protected Attributes
const std::string host_
const int port_
const std::string host_and_port_
Socket socket_
std::mutex socket_mutex_
std::recursive_mutex request_mutex_
size_t socket_requests_in_flight_ = 0
std::thread::id socket_requests_are_from_thread_ = std::thread::id()
bool socket_should_be_closed_when_request_is_done_ = false
std::map< std::string, std::string > addr_map_
Headers default_headers_
std::function< ssize_t(Stream &, Headers &)> header_writer_
std::string client_cert_path_
std::string client_key_path_
time_t connection_timeout_sec_ = 300
time_t connection_timeout_usec_ = 0
time_t read_timeout_sec_ = 5
time_t read_timeout_usec_ = 0
time_t write_timeout_sec_ = 5
time_t write_timeout_usec_ = 0
std::string basic_auth_username_
std::string basic_auth_password_
std::string bearer_token_auth_token_
bool keep_alive_ = false
bool follow_location_ = false
bool url_encode_ = true
int address_family_ = AF_UNSPEC
bool tcp_nodelay_ = false
SocketOptions socket_options_ = nullptr
bool compress_ = false
bool decompress_ = true
std::string interface_
std::string proxy_host_
int proxy_port_ = -1
std::string proxy_basic_auth_username_
std::string proxy_basic_auth_password_
std::string proxy_bearer_token_auth_token_
Logger logger_
Private Member Functions
bool send_ (Request &req, Response &res, Error &error)
Result send_ (Request &&req)
socket_t create_client_socket (Error &error) const
bool read_response_line (Stream &strm, const Request &req, Response &res) const
bool write_request (Stream &strm, Request &req, bool close_connection, Error &error)
bool redirect (Request &req, Response &res, Error &error)
bool handle_request (Stream &strm, Request &req, Response &res, bool close_connection, Error &error)
std::unique_ptr< Response > send_with_content_provider (Request &req, const char *body, size_t content_length, ContentProvider content_provider, ContentProviderWithoutLength content_provider_without_length, const std::string &content_type, Error &error)
Result send_with_content_provider (const std::string &method, const std::string &path, const Headers &headers, const char *body, size_t content_length, ContentProvider content_provider, ContentProviderWithoutLength content_provider_without_length, const std::string &content_type)
ContentProviderWithoutLength get_multipart_content_provider (const std::string &boundary, const MultipartFormDataItems &items, const MultipartFormDataProviderItems &provider_items) const
std::string adjust_host_string (const std::string &host) const
virtual bool process_socket (const Socket &socket, std::function< bool(Stream &strm)> callback)
virtual bool is_ssl () const
Detailed Description
Definition at line 1088 of file httplib.h.
Constructor & Destructor Documentation
ClientImpl() [1/3]
httplib::ClientImpl::ClientImpl (const std::string & host) inline explicit
Definition at line 6784 of file httplib.h.
     : ClientImpl(host, 80, std::string(), std::string()) {}
ClientImpl() [2/3]
httplib::ClientImpl::ClientImpl (const std::string & host, int port) inline explicit
Definition at line 6787 of file httplib.h.
     : ClientImpl(host, port, std::string(), std::string()) {}
ClientImpl() [3/3]
httplib::ClientImpl::ClientImpl (const std::string & host, int port, const std::string & client_cert_path, const std::string & client_key_path) inline explicit
Definition at line 6790 of file httplib.h.
     : host_(host), port_(port),
       host_and_port_(adjust_host_string(host) + ":" + std::to_string(port)),
       client_cert_path_(client_cert_path), client_key_path_(client_key_path) {}
~ClientImpl()
httplib::ClientImpl::~ClientImpl () inline virtual
Definition at line 6797 of file httplib.h.
{
   std::lock_guard<std::mutex> guard(socket_mutex_);
   shutdown_socket(socket_);
   close_socket(socket_);
 }
References close_socket(), shutdown_socket(), socket_, and socket_mutex_.
Member Function Documentation
adjust_host_string()
std::string httplib::ClientImpl::adjust_host_string (const std::string & host) const inline private
Definition at line 7433 of file httplib.h.
{
   if (host.find(':') != std::string::npos) { return "[" + host + "]"; }
   return host;
 }
References host().
close_socket()
void httplib::ClientImpl::close_socket (Socket & socket) inline protected
Definition at line 6891 of file httplib.h.
{
   // If there are requests in flight in another thread, usually closing
   // the socket will be fine and they will simply receive an error when
   // using the closed socket, but it is still a bug since rarely the OS
   // may reassign the socket id to be used for a new socket, and then
   // suddenly they will be operating on a live socket that is different
   // than the one they intended!
   assert(socket_requests_in_flight_ == 0 ||
          socket_requests_are_from_thread_ == std::this_thread::get_id());
   // It is also a bug if this happens while SSL is still active
 #ifdef CPPHTTPLIB_OPENSSL_SUPPORT
   assert(socket.ssl == nullptr);
 #endif
   if (socket.sock == INVALID_SOCKET) { return; }
   detail::close_socket(socket.sock);
   socket.sock = INVALID_SOCKET;
 }
References assert(), httplib::detail::close_socket(), INVALID_SOCKET, socket(), socket_requests_are_from_thread_, and socket_requests_in_flight_.
Referenced by handle_request(), send_(), stop(), and ~ClientImpl().
copy_settings()
void httplib::ClientImpl::copy_settings (const ClientImpl & rhs) inline protected
Definition at line 6805 of file httplib.h.
{
   client_cert_path_ = rhs.client_cert_path_;
   client_key_path_ = rhs.client_key_path_;
   connection_timeout_sec_ = rhs.connection_timeout_sec_;
   read_timeout_sec_ = rhs.read_timeout_sec_;
   read_timeout_usec_ = rhs.read_timeout_usec_;
   write_timeout_sec_ = rhs.write_timeout_sec_;
   write_timeout_usec_ = rhs.write_timeout_usec_;
   basic_auth_username_ = rhs.basic_auth_username_;
   basic_auth_password_ = rhs.basic_auth_password_;
   bearer_token_auth_token_ = rhs.bearer_token_auth_token_;
 #ifdef CPPHTTPLIB_OPENSSL_SUPPORT
   digest_auth_username_ = rhs.digest_auth_username_;
   digest_auth_password_ = rhs.digest_auth_password_;
 #endif
   keep_alive_ = rhs.keep_alive_;
   follow_location_ = rhs.follow_location_;
   url_encode_ = rhs.url_encode_;
   address_family_ = rhs.address_family_;
   tcp_nodelay_ = rhs.tcp_nodelay_;
   socket_options_ = rhs.socket_options_;
   compress_ = rhs.compress_;
   decompress_ = rhs.decompress_;
   interface_ = rhs.interface_;
   proxy_host_ = rhs.proxy_host_;
   proxy_port_ = rhs.proxy_port_;
   proxy_basic_auth_username_ = rhs.proxy_basic_auth_username_;
   proxy_basic_auth_password_ = rhs.proxy_basic_auth_password_;
   proxy_bearer_token_auth_token_ = rhs.proxy_bearer_token_auth_token_;
 #ifdef CPPHTTPLIB_OPENSSL_SUPPORT
   proxy_digest_auth_username_ = rhs.proxy_digest_auth_username_;
   proxy_digest_auth_password_ = rhs.proxy_digest_auth_password_;
 #endif
 #ifdef CPPHTTPLIB_OPENSSL_SUPPORT
   ca_cert_file_path_ = rhs.ca_cert_file_path_;
   ca_cert_dir_path_ = rhs.ca_cert_dir_path_;
   ca_cert_store_ = rhs.ca_cert_store_;
 #endif
 #ifdef CPPHTTPLIB_OPENSSL_SUPPORT
   server_certificate_verification_ = rhs.server_certificate_verification_;
 #endif
   logger_ = rhs.logger_;
 }
References address_family_, basic_auth_password_, basic_auth_username_, bearer_token_auth_token_, client_cert_path_, client_key_path_, compress_, connection_timeout_sec_, decompress_, follow_location_, interface_, keep_alive_, logger_, proxy_basic_auth_password_, proxy_basic_auth_username_, proxy_bearer_token_auth_token_, proxy_host_, proxy_port_, read_timeout_sec_, read_timeout_usec_, socket_options_, tcp_nodelay_, url_encode_, write_timeout_sec_, and write_timeout_usec_.
Referenced by redirect().
create_and_connect_socket()
bool httplib::ClientImpl::create_and_connect_socket (Socket & socket, Error & error) inline protected virtual
Definition at line 6870 of file httplib.h.
{
   auto sock = create_client_socket(error);
   if (sock == INVALID_SOCKET) { return false; }
   socket.sock = sock;
   return true;
 }
References create_client_socket(), INVALID_SOCKET, and socket().
Referenced by send_().
create_client_socket()
socket_t httplib::ClientImpl::create_client_socket (Error & error) const inline private
Definition at line 6849 of file httplib.h.
{
   if (!proxy_host_.empty() && proxy_port_ != -1) {
     return detail::create_client_socket(
         proxy_host_, std::string(), proxy_port_, address_family_, tcp_nodelay_,
         socket_options_, connection_timeout_sec_, connection_timeout_usec_,
         read_timeout_sec_, read_timeout_usec_, write_timeout_sec_,
         write_timeout_usec_, interface_, error);
   }
   // Check is custom IP specified for host_
   std::string ip;
   auto it = addr_map_.find(host_);
   if (it != addr_map_.end()) { ip = it->second; }
   return detail::create_client_socket(
       host_, ip, port_, address_family_, tcp_nodelay_, socket_options_,
       connection_timeout_sec_, connection_timeout_usec_, read_timeout_sec_,
       read_timeout_usec_, write_timeout_sec_, write_timeout_usec_, interface_,
       error);
 }
References addr_map_, address_family_, connection_timeout_sec_, connection_timeout_usec_, httplib::detail::create_client_socket(), host_, interface_, port_, proxy_host_, proxy_port_, read_timeout_sec_, read_timeout_usec_, socket_options_, tcp_nodelay_, write_timeout_sec_, and write_timeout_usec_.
Referenced by create_and_connect_socket().
Delete() [1/6]
Result httplib::ClientImpl::Delete (const std::string & path) inline
Definition at line 7988 of file httplib.h.
{
   return Delete(path, Headers(), std::string(), std::string());
 }
Referenced by Delete().
Delete() [2/6]
Result httplib::ClientImpl::Delete (const std::string & path, const char * body, size_t content_length, const std::string & content_type) inline
Definition at line 7997 of file httplib.h.
{
   return Delete(path, Headers(), body, content_length, content_type);
 }
References Delete().
Delete() [3/6]
Result httplib::ClientImpl::Delete (const std::string & path, const Headers & headers) inline
Definition at line 7992 of file httplib.h.
{
   return Delete(path, headers, std::string(), std::string());
 }
References Delete().
Delete() [4/6]
Result httplib::ClientImpl::Delete (const std::string & path, const Headers & headers, const char * body, size_t content_length, const std::string & content_type) inline
Definition at line 8003 of file httplib.h.
{
   Request req;
   req.method = "DELETE";
   req.headers = headers;
   req.path = path;
   if (!content_type.empty()) { req.set_header("Content-Type", content_type); }
   req.body.assign(body, content_length);
   return send_(std::move(req));
 }
References httplib::Request::body, httplib::Request::headers, httplib::Request::method, httplib::Request::path, send_(), and httplib::Request::set_header().
Delete() [5/6]
Result httplib::ClientImpl::Delete (const std::string & path, const Headers & headers, const std::string & body, const std::string & content_type) inline
Definition at line 8024 of file httplib.h.
{
   return Delete(path, headers, body.data(), body.size(), content_type);
 }
References Delete().
Delete() [6/6]
Result httplib::ClientImpl::Delete (const std::string & path, const std::string & body, const std::string & content_type) inline
Definition at line 8018 of file httplib.h.
{
   return Delete(path, Headers(), body.data(), body.size(), content_type);
 }
References Delete().
Get() [1/15]
Result httplib::ClientImpl::Get (const std::string & path) inline
Definition at line 7572 of file httplib.h.
{
   return Get(path, Headers(), Progress());
 }
Referenced by Get().
Get() [2/15]
Result httplib::ClientImpl::Get (const std::string & path, const Headers & headers) inline
Definition at line 7580 of file httplib.h.
{
   return Get(path, headers, Progress());
 }
References Get().
Get() [3/15]
Result httplib::ClientImpl::Get (const std::string & path, const Headers & headers, ContentReceiver content_receiver) inline
Definition at line 7607 of file httplib.h.
{
   return Get(path, headers, nullptr, std::move(content_receiver), nullptr);
 }
References Get().
Get() [4/15]
Result httplib::ClientImpl::Get (const std::string & path, const Headers & headers, ContentReceiver content_receiver, Progress progress) inline
Definition at line 7612 of file httplib.h.
{
   return Get(path, headers, nullptr, std::move(content_receiver),
              std::move(progress));
 }
References Get().
Get() [5/15]
Result httplib::ClientImpl::Get (const std::string & path, const Headers & headers, Progress progress) inline
Definition at line 7584 of file httplib.h.
{
   Request req;
   req.method = "GET";
   req.path = path;
   req.headers = headers;
   req.progress = std::move(progress);
   return send_(std::move(req));
 }
References httplib::Request::headers, httplib::Request::method, httplib::Request::path, httplib::Request::progress, and send_().
Get() [6/15]
Result httplib::ClientImpl::Get (const std::string & path, const Headers & headers, ResponseHandler response_handler, ContentReceiver content_receiver) inline
Definition at line 7626 of file httplib.h.
{
   return Get(path, headers, std::move(response_handler),
              std::move(content_receiver), nullptr);
 }
References Get().
Get() [7/15]
Result httplib::ClientImpl::Get (const std::string & path, const Headers & headers, ResponseHandler response_handler, ContentReceiver content_receiver, Progress progress) inline
Definition at line 7641 of file httplib.h.
{
   Request req;
   req.method = "GET";
   req.path = path;
   req.headers = headers;
   req.response_handler = std::move(response_handler);
   req.content_receiver =
       [content_receiver](const char *data, size_t data_length,
                          uint64_t /*offset*/, uint64_t /*total_length*/) {
         return content_receiver(data, data_length);
       };
   req.progress = std::move(progress);
   return send_(std::move(req));
 }
References httplib::Request::content_receiver, httplib::Request::headers, httplib::Request::method, httplib::Request::path, httplib::Request::progress, httplib::Request::response_handler, and send_().
Get() [8/15]
Result httplib::ClientImpl::Get (const std::string & path, const Params & params, const Headers & headers, ContentReceiver content_receiver, Progress progress = nullptr) inline
Definition at line 7668 of file httplib.h.
{
   return Get(path, params, headers, nullptr, std::move(content_receiver),
              std::move(progress));
 }
References Get().
Get() [9/15]
Result httplib::ClientImpl::Get (const std::string & path, const Params & params, const Headers & headers, Progress progress = nullptr) inline
Definition at line 7660 of file httplib.h.
{
   if (params.empty()) { return Get(path, headers); }
   std::string path_with_query = append_query_params(path, params);
   return Get(path_with_query, headers, std::move(progress));
 }
References httplib::append_query_params(), and Get().
Get() [10/15]
Result httplib::ClientImpl::Get (const std::string & path, const Params & params, const Headers & headers, ResponseHandler response_handler, ContentReceiver content_receiver, Progress progress = nullptr) inline
Definition at line 7676 of file httplib.h.
{
   if (params.empty()) {
     return Get(path, headers, std::move(response_handler),
                std::move(content_receiver), std::move(progress));
   }
   std::string path_with_query = append_query_params(path, params);
   return Get(path_with_query, headers, std::move(response_handler),
              std::move(content_receiver), std::move(progress));
 }
References httplib::append_query_params(), and Get().
Get() [11/15]
Result httplib::ClientImpl::Get (const std::string & path, ContentReceiver content_receiver) inline
Definition at line 7595 of file httplib.h.
{
   return Get(path, Headers(), nullptr, std::move(content_receiver), nullptr);
 }
References Get().
Get() [12/15]
Result httplib::ClientImpl::Get (const std::string & path, ContentReceiver content_receiver, Progress progress) inline
Definition at line 7600 of file httplib.h.
{
   return Get(path, Headers(), nullptr, std::move(content_receiver),
              std::move(progress));
 }
References Get().
Get() [13/15]
Result httplib::ClientImpl::Get (const std::string & path, Progress progress) inline
Definition at line 7576 of file httplib.h.
{
   return Get(path, Headers(), std::move(progress));
 }
References Get().
Get() [14/15]
Result httplib::ClientImpl::Get (const std::string & path, ResponseHandler response_handler, ContentReceiver content_receiver) inline
Definition at line 7619 of file httplib.h.
{
   return Get(path, Headers(), std::move(response_handler),
              std::move(content_receiver), nullptr);
 }
References Get().
Get() [15/15]
Result httplib::ClientImpl::Get (const std::string & path, ResponseHandler response_handler, ContentReceiver content_receiver, Progress progress) inline
Definition at line 7633 of file httplib.h.
{
   return Get(path, Headers(), std::move(response_handler),
              std::move(content_receiver), std::move(progress));
 }
References Get().
get_multipart_content_provider()
ContentProviderWithoutLength httplib::ClientImpl::get_multipart_content_provider (const std::string & boundary, const MultipartFormDataItems & items, const MultipartFormDataProviderItems & provider_items) const inline private
Definition at line 7518 of file httplib.h.
{
   size_t cur_item = 0;
   size_t cur_start = 0;
   // cur_item and cur_start are copied to within the std::function and maintain
   // state between successive calls
   return [&, cur_item, cur_start](size_t offset,
                                   DataSink &sink) mutable -> bool {
     if (!offset && !items.empty()) {
       sink.os << detail::serialize_multipart_formdata(items, boundary, false);
       return true;
     } else if (cur_item < provider_items.size()) {
       if (!cur_start) {
         const auto &begin = detail::serialize_multipart_formdata_item_begin(
             provider_items[cur_item], boundary);
         offset += begin.size();
         cur_start = offset;
         sink.os << begin;
       }
       DataSink cur_sink;
       auto has_data = true;
       cur_sink.write = sink.write;
       cur_sink.done = [&]() { has_data = false; };
       if (!provider_items[cur_item].provider(offset - cur_start, cur_sink)) {
         return false;
       }
       if (!has_data) {
         sink.os << detail::serialize_multipart_formdata_item_end();
         cur_item++;
         cur_start = 0;
       }
       return true;
     } else {
       sink.os << detail::serialize_multipart_formdata_finish(boundary);
       sink.done();
       return true;
     }
   };
 }
References httplib::DataSink::done, httplib::detail::serialize_multipart_formdata(), httplib::detail::serialize_multipart_formdata_finish(), httplib::detail::serialize_multipart_formdata_item_begin(), httplib::detail::serialize_multipart_formdata_item_end(), sink, and httplib::DataSink::write.
Referenced by Post(), and Put().
handle_request()
bool httplib::ClientImpl::handle_request (Stream & strm, Request & req, Response & res, bool close_connection, Error & error) inline private
Definition at line 7057 of file httplib.h.
{
   if (req.path.empty()) {
     error = Error::Connection;
     return false;
   }
   auto req_save = req;
   bool ret;
   if (!is_ssl() && !proxy_host_.empty() && proxy_port_ != -1) {
     auto req2 = req;
     req2.path = "http://" + host_and_port_ + req.path;
     ret = process_request(strm, req2, res, close_connection, error);
     req = req2;
     req.path = req_save.path;
   } else {
     ret = process_request(strm, req, res, close_connection, error);
   }
   if (!ret) { return false; }
   if (res.get_header_value("Connection") == "close" ||
       (res.version == "HTTP/1.0" && res.reason != "Connection established")) {
     // TODO this requires a not-entirely-obvious chain of calls to be correct
     // for this to be safe.
     // This is safe to call because handle_request is only called by send_
     // which locks the request mutex during the process. It would be a bug
     // to call it from a different thread since it's a thread-safety issue
     // to do these things to the socket if another thread is using the socket.
     std::lock_guard<std::mutex> guard(socket_mutex_);
     shutdown_ssl(socket_, true);
     shutdown_socket(socket_);
     close_socket(socket_);
   }
   if (300 < res.status && res.status < 400 && follow_location_) {
     req = req_save;
     ret = redirect(req, res, error);
   }
 #ifdef CPPHTTPLIB_OPENSSL_SUPPORT
   if ((res.status == StatusCode::Unauthorized_401 ||
        res.status == StatusCode::ProxyAuthenticationRequired_407) &&
       req.authorization_count_ < 5) {
     auto is_proxy = res.status == StatusCode::ProxyAuthenticationRequired_407;
     const auto &username =
         is_proxy ? proxy_digest_auth_username_ : digest_auth_username_;
     const auto &password =
         is_proxy ? proxy_digest_auth_password_ : digest_auth_password_;
     if (!username.empty() && !password.empty()) {
       std::map<std::string, std::string> auth;
       if (detail::parse_www_authenticate(res, auth, is_proxy)) {
         Request new_req = req;
         new_req.authorization_count_ += 1;
         new_req.headers.erase(is_proxy ? "Proxy-Authorization"
                                        : "Authorization");
         new_req.headers.insert(detail::make_digest_authentication_header(
             req, auth, new_req.authorization_count_, detail::random_string(10),
             username, password, is_proxy));
         Response new_res;
         ret = send(new_req, new_res, error);
         if (ret) { res = new_res; }
       }
     }
   }
 #endif
   return ret;
 }
References httplib::Request::authorization_count_, close_socket(), httplib::Connection, follow_location_, httplib::Response::get_header_value(), httplib::Request::headers, host_and_port_, is_ssl(), httplib::detail::parse_www_authenticate(), httplib::Request::path, process_request(), proxy_host_, proxy_port_, httplib::ProxyAuthenticationRequired_407, httplib::detail::random_string(), httplib::Response::reason, redirect(), send(), shutdown_socket(), shutdown_ssl(), socket_, socket_mutex_, httplib::Response::status, httplib::Unauthorized_401, and httplib::Response::version.
Referenced by send_().
Head() [1/2]
Result httplib::ClientImpl::Head (const std::string & path) inline
Definition at line 7691 of file httplib.h.
{
   return Head(path, Headers());
 }
Head() [2/2]
Result httplib::ClientImpl::Head (const std::string & path, const Headers & headers) inline
Definition at line 7695 of file httplib.h.
{
   Request req;
   req.method = "HEAD";
   req.headers = headers;
   req.path = path;
   return send_(std::move(req));
 }
References httplib::Request::headers, httplib::Request::method, httplib::Request::path, and send_().
host()
std::string httplib::ClientImpl::host () const inline
Definition at line 8068 of file httplib.h.
 { return host_; }
References host_.
Referenced by adjust_host_string(), and set_proxy().
is_socket_open()
size_t httplib::ClientImpl::is_socket_open () const inline
Definition at line 8072 of file httplib.h.
{
   std::lock_guard<std::mutex> guard(socket_mutex_);
   return socket_.is_open();
 }
References httplib::ClientImpl::Socket::is_open(), socket_, and socket_mutex_.
is_ssl()
bool httplib::ClientImpl::is_ssl () const inline private virtual
Definition at line 7570 of file httplib.h.
 { return false; }
Referenced by handle_request(), process_request(), redirect(), send_(), and write_request().
is_valid()
bool httplib::ClientImpl::is_valid () const inline virtual
Definition at line 6803 of file httplib.h.
 { return true; }
Options() [1/2]
Result httplib::ClientImpl::Options (const std::string & path) inline
Definition at line 8031 of file httplib.h.
{
   return Options(path, Headers());
 }
Options() [2/2]
Result httplib::ClientImpl::Options (const std::string & path, const Headers & headers) inline
Definition at line 8035 of file httplib.h.
{
   Request req;
   req.method = "OPTIONS";
   req.headers = headers;
   req.path = path;
   return send_(std::move(req));
 }
References httplib::Request::headers, httplib::Request::method, httplib::Request::path, and send_().
Patch() [1/9]
Result httplib::ClientImpl::Patch (const std::string & path) inline
Definition at line 7927 of file httplib.h.
{
   return Patch(path, std::string(), std::string());
 }
Referenced by Patch().
Patch() [2/9]
Result httplib::ClientImpl::Patch (const std::string & path, const char * body, size_t content_length, const std::string & content_type) inline
Definition at line 7931 of file httplib.h.
{
   return Patch(path, Headers(), body, content_length, content_type);
 }
References Patch().
Patch() [3/9]
Result httplib::ClientImpl::Patch (const std::string & path, const Headers & headers, const char * body, size_t content_length, const std::string & content_type) inline
Definition at line 7937 of file httplib.h.
{
   return send_with_content_provider("PATCH", path, headers, body,
                                     content_length, nullptr, nullptr,
                                     content_type);
 }
References send_with_content_provider().
Patch() [4/9]
Result httplib::ClientImpl::Patch (const std::string & path, const Headers & headers, const std::string & body, const std::string & content_type) inline
Definition at line 7951 of file httplib.h.
{
   return send_with_content_provider("PATCH", path, headers, body.data(),
                                     body.size(), nullptr, nullptr,
                                     content_type);
 }
References send_with_content_provider().
Patch() [5/9]
Result httplib::ClientImpl::Patch (const std::string & path, const Headers & headers, ContentProviderWithoutLength content_provider, const std::string & content_type) inline
Definition at line 7981 of file httplib.h.
{
   return send_with_content_provider("PATCH", path, headers, nullptr, 0, nullptr,
                                     std::move(content_provider), content_type);
 }
References send_with_content_provider().
Patch() [6/9]
Result httplib::ClientImpl::Patch (const std::string & path, const Headers & headers, size_t content_length, ContentProvider content_provider, const std::string & content_type) inline
Definition at line 7972 of file httplib.h.
{
   return send_with_content_provider("PATCH", path, headers, nullptr,
                                     content_length, std::move(content_provider),
                                     nullptr, content_type);
 }
References send_with_content_provider().
Patch() [7/9]
Result httplib::ClientImpl::Patch (const std::string & path, const std::string & body, const std::string & content_type) inline
Definition at line 7945 of file httplib.h.
{
   return Patch(path, Headers(), body, content_type);
 }
References Patch().
Patch() [8/9]
Result httplib::ClientImpl::Patch (const std::string & path, ContentProviderWithoutLength content_provider, const std::string & content_type) inline
Definition at line 7966 of file httplib.h.
{
   return Patch(path, Headers(), std::move(content_provider), content_type);
 }
References Patch().
Patch() [9/9]
Result httplib::ClientImpl::Patch (const std::string & path, size_t content_length, ContentProvider content_provider, const std::string & content_type) inline
Definition at line 7959 of file httplib.h.
{
   return Patch(path, Headers(), content_length, std::move(content_provider),
                content_type);
 }
References Patch().
port()
int httplib::ClientImpl::port () const inline
Definition at line 8070 of file httplib.h.
 { return port_; }
References port_.
Referenced by set_proxy().
Post() [1/16]
Result httplib::ClientImpl::Post (const std::string & path) inline
Definition at line 7705 of file httplib.h.
{
   return Post(path, std::string(), std::string());
 }
Referenced by Post().
Post() [2/16]
Result httplib::ClientImpl::Post (const std::string & path, const char * body, size_t content_length, const std::string & content_type) inline
Definition at line 7714 of file httplib.h.
{
   return Post(path, Headers(), body, content_length, content_type);
 }
References Post().
Post() [3/16]
Result httplib::ClientImpl::Post (const std::string & path, const Headers & headers) inline
Definition at line 7709 of file httplib.h.
{
   return Post(path, headers, nullptr, 0, std::string());
 }
References Post().
Post() [4/16]
Result httplib::ClientImpl::Post (const std::string & path, const Headers & headers, const char * body, size_t content_length, const std::string & content_type) inline
Definition at line 7720 of file httplib.h.
{
   return send_with_content_provider("POST", path, headers, body, content_length,
                                     nullptr, nullptr, content_type);
 }
References send_with_content_provider().
Post() [5/16]
Result httplib::ClientImpl::Post (const std::string & path, const Headers & headers, const MultipartFormDataItems & items) inline
Definition at line 7784 of file httplib.h.
{
   const auto &boundary = detail::make_multipart_data_boundary();
   const auto &content_type =
       detail::serialize_multipart_formdata_get_content_type(boundary);
   const auto &body = detail::serialize_multipart_formdata(items, boundary);
   return Post(path, headers, body, content_type);
 }
References httplib::detail::make_multipart_data_boundary(), Post(), httplib::detail::serialize_multipart_formdata(), and httplib::detail::serialize_multipart_formdata_get_content_type().
Post() [6/16]
Result httplib::ClientImpl::Post (const std::string & path, const Headers & headers, const MultipartFormDataItems & items, const MultipartFormDataProviderItems & provider_items) inline
Definition at line 7807 of file httplib.h.
{
   const auto &boundary = detail::make_multipart_data_boundary();
   const auto &content_type =
       detail::serialize_multipart_formdata_get_content_type(boundary);
   return send_with_content_provider(
       "POST", path, headers, nullptr, 0, nullptr,
       get_multipart_content_provider(boundary, items, provider_items),
       content_type);
 }
References get_multipart_content_provider(), httplib::detail::make_multipart_data_boundary(), send_with_content_provider(), and httplib::detail::serialize_multipart_formdata_get_content_type().
Post() [7/16]
Result httplib::ClientImpl::Post (const std::string & path, const Headers & headers, const MultipartFormDataItems & items, const std::string & boundary) inline
Definition at line 7793 of file httplib.h.
{
   if (!detail::is_multipart_boundary_chars_valid(boundary)) {
     return Result{nullptr, Error::UnsupportedMultipartBoundaryChars};
   }
   const auto &content_type =
       detail::serialize_multipart_formdata_get_content_type(boundary);
   const auto &body = detail::serialize_multipart_formdata(items, boundary);
   return Post(path, headers, body, content_type);
 }
References httplib::detail::is_multipart_boundary_chars_valid(), Post(), httplib::detail::serialize_multipart_formdata(), httplib::detail::serialize_multipart_formdata_get_content_type(), and httplib::UnsupportedMultipartBoundaryChars.
Post() [8/16]
Result httplib::ClientImpl::Post (const std::string & path, const Headers & headers, const Params & params) inline
Definition at line 7773 of file httplib.h.
{
   auto query = detail::params_to_query_str(params);
   return Post(path, headers, query, "application/x-www-form-urlencoded");
 }
References httplib::detail::params_to_query_str(), and Post().
Post() [9/16]
Result httplib::ClientImpl::Post (const std::string & path, const Headers & headers, const std::string & body, const std::string & content_type) inline
Definition at line 7732 of file httplib.h.
{
   return send_with_content_provider("POST", path, headers, body.data(),
                                     body.size(), nullptr, nullptr,
                                     content_type);
 }
References send_with_content_provider().
Post() [10/16]
Result httplib::ClientImpl::Post (const std::string & path, const Headers & headers, ContentProviderWithoutLength content_provider, const std::string & content_type) inline
Definition at line 7766 of file httplib.h.
{
   return send_with_content_provider("POST", path, headers, nullptr, 0, nullptr,
                                     std::move(content_provider), content_type);
 }
References send_with_content_provider().
Post() [11/16]
Result httplib::ClientImpl::Post (const std::string & path, const Headers & headers, size_t content_length, ContentProvider content_provider, const std::string & content_type) inline
Definition at line 7757 of file httplib.h.
{
   return send_with_content_provider("POST", path, headers, nullptr,
                                     content_length, std::move(content_provider),
                                     nullptr, content_type);
 }
References send_with_content_provider().
Post() [12/16]
Result httplib::ClientImpl::Post (const std::string & path, const MultipartFormDataItems & items) inline
Definition at line 7779 of file httplib.h.
{
   return Post(path, Headers(), items);
 }
References Post().
Post() [13/16]
Result httplib::ClientImpl::Post (const std::string & path, const Params & params) inline
Definition at line 7740 of file httplib.h.
{
   return Post(path, Headers(), params);
 }
References Post().
Post() [14/16]
Result httplib::ClientImpl::Post (const std::string & path, const std::string & body, const std::string & content_type) inline
Definition at line 7727 of file httplib.h.
{
   return Post(path, Headers(), body, content_type);
 }
References Post().
Post() [15/16]
Result httplib::ClientImpl::Post (const std::string & path, ContentProviderWithoutLength content_provider, const std::string & content_type) inline
Definition at line 7751 of file httplib.h.
{
   return Post(path, Headers(), std::move(content_provider), content_type);
 }
References Post().
Post() [16/16]
Result httplib::ClientImpl::Post (const std::string & path, size_t content_length, ContentProvider content_provider, const std::string & content_type) inline
Definition at line 7744 of file httplib.h.
{
   return Post(path, Headers(), content_length, std::move(content_provider),
               content_type);
 }
References Post().
process_request()
bool httplib::ClientImpl::process_request (Stream & strm, Request & req, Response & res, bool close_connection, Error & error) inline protected
Definition at line 7438 of file httplib.h.
{
   // Send request
   if (!write_request(strm, req, close_connection, error)) { return false; }
 #ifdef CPPHTTPLIB_OPENSSL_SUPPORT
   if (is_ssl()) {
     auto is_proxy_enabled = !proxy_host_.empty() && proxy_port_ != -1;
     if (!is_proxy_enabled) {
       char buf[1];
       if (SSL_peek(socket_.ssl, buf, 1) == 0 &&
           SSL_get_error(socket_.ssl, 0) == SSL_ERROR_ZERO_RETURN) {
         error = Error::SSLPeerCouldBeClosed_;
         return false;
       }
     }
   }
 #endif
   // Receive response and headers
   if (!read_response_line(strm, req, res) ||
       !detail::read_headers(strm, res.headers)) {
     error = Error::Read;
     return false;
   }
   // Body
   if ((res.status != StatusCode::NoContent_204) && req.method != "HEAD" &&
       req.method != "CONNECT") {
     auto redirect = 300 < res.status && res.status < 400 && follow_location_;
     if (req.response_handler && !redirect) {
       if (!req.response_handler(res)) {
         error = Error::Canceled;
         return false;
       }
     }
     auto out =
         req.content_receiver
             ? static_cast<ContentReceiverWithProgress>(
                   [&](const char *buf, size_t n, uint64_t off, uint64_t len) {
                     if (redirect) { return true; }
                     auto ret = req.content_receiver(buf, n, off, len);
                     if (!ret) { error = Error::Canceled; }
                     return ret;
                   })
             : static_cast<ContentReceiverWithProgress>(
                   [&](const char *buf, size_t n, uint64_t /*off*/,
                       uint64_t /*len*/) {
                     if (res.body.size() + n > res.body.max_size()) {
                       return false;
                     }
                     res.body.append(buf, n);
                     return true;
                   });
     auto progress = [&](uint64_t current, uint64_t total) {
       if (!req.progress || redirect) { return true; }
       auto ret = req.progress(current, total);
       if (!ret) { error = Error::Canceled; }
       return ret;
     };
     int dummy_status;
     if (!detail::read_content(strm, res, (std::numeric_limits<size_t>::max)(),
                               dummy_status, std::move(progress), std::move(out),
                               decompress_)) {
       if (error != Error::Canceled) { error = Error::Read; }
       return false;
     }
   }
   // Log
   if (logger_) { logger_(req, res); }
   return true;
 }
References httplib::Response::body, httplib::Canceled, httplib::Request::content_receiver, decompress_, follow_location_, httplib::Response::headers, is_ssl(), logger_, httplib::Request::method, n, httplib::NoContent_204, httplib::Request::progress, proxy_host_, proxy_port_, httplib::Read, httplib::detail::read_content(), httplib::detail::read_headers(), read_response_line(), redirect(), httplib::Request::response_handler, socket_, httplib::SSLPeerCouldBeClosed_, httplib::Response::status, and write_request().
Referenced by handle_request().
process_socket()
bool httplib::ClientImpl::process_socket (const Socket & socket, std::function< bool(Stream &strm)> callback) inline private virtual
Definition at line 7563 of file httplib.h.
{
   return detail::process_client_socket(
       socket.sock, read_timeout_sec_, read_timeout_usec_, write_timeout_sec_,
       write_timeout_usec_, std::move(callback));
 }
References httplib::detail::process_client_socket(), read_timeout_sec_, read_timeout_usec_, socket(), write_timeout_sec_, and write_timeout_usec_.
Referenced by send_().
Put() [1/15]
Result httplib::ClientImpl::Put (const std::string & path) inline
Definition at line 7819 of file httplib.h.
{
   return Put(path, std::string(), std::string());
 }
Referenced by Put().
Put() [2/15]
Result httplib::ClientImpl::Put (const std::string & path, const char * body, size_t content_length, const std::string & content_type) inline
Definition at line 7823 of file httplib.h.
{
   return Put(path, Headers(), body, content_length, content_type);
 }
References Put().
Put() [3/15]
Result httplib::ClientImpl::Put (const std::string & path, const Headers & headers, const char * body, size_t content_length, const std::string & content_type) inline
Definition at line 7829 of file httplib.h.
{
   return send_with_content_provider("PUT", path, headers, body, content_length,
                                     nullptr, nullptr, content_type);
 }
References send_with_content_provider().
Put() [4/15]
Result httplib::ClientImpl::Put (const std::string & path, const Headers & headers, const MultipartFormDataItems & items) inline
Definition at line 7893 of file httplib.h.
{
   const auto &boundary = detail::make_multipart_data_boundary();
   const auto &content_type =
       detail::serialize_multipart_formdata_get_content_type(boundary);
   const auto &body = detail::serialize_multipart_formdata(items, boundary);
   return Put(path, headers, body, content_type);
 }
References httplib::detail::make_multipart_data_boundary(), Put(), httplib::detail::serialize_multipart_formdata(), and httplib::detail::serialize_multipart_formdata_get_content_type().
Put() [5/15]
Result httplib::ClientImpl::Put (const std::string & path, const Headers & headers, const MultipartFormDataItems & items, const MultipartFormDataProviderItems & provider_items) inline
Definition at line 7916 of file httplib.h.
{
   const auto &boundary = detail::make_multipart_data_boundary();
   const auto &content_type =
       detail::serialize_multipart_formdata_get_content_type(boundary);
   return send_with_content_provider(
       "PUT", path, headers, nullptr, 0, nullptr,
       get_multipart_content_provider(boundary, items, provider_items),
       content_type);
 }
References get_multipart_content_provider(), httplib::detail::make_multipart_data_boundary(), send_with_content_provider(), and httplib::detail::serialize_multipart_formdata_get_content_type().
Put() [6/15]
Result httplib::ClientImpl::Put (const std::string & path, const Headers & headers, const MultipartFormDataItems & items, const std::string & boundary) inline
Definition at line 7902 of file httplib.h.
{
   if (!detail::is_multipart_boundary_chars_valid(boundary)) {
     return Result{nullptr, Error::UnsupportedMultipartBoundaryChars};
   }
   const auto &content_type =
       detail::serialize_multipart_formdata_get_content_type(boundary);
   const auto &body = detail::serialize_multipart_formdata(items, boundary);
   return Put(path, headers, body, content_type);
 }
References httplib::detail::is_multipart_boundary_chars_valid(), Put(), httplib::detail::serialize_multipart_formdata(), httplib::detail::serialize_multipart_formdata_get_content_type(), and httplib::UnsupportedMultipartBoundaryChars.
Put() [7/15]
Result httplib::ClientImpl::Put (const std::string & path, const Headers & headers, const Params & params) inline
Definition at line 7882 of file httplib.h.
{
   auto query = detail::params_to_query_str(params);
   return Put(path, headers, query, "application/x-www-form-urlencoded");
 }
References httplib::detail::params_to_query_str(), and Put().
Put() [8/15]
Result httplib::ClientImpl::Put (const std::string & path, const Headers & headers, const std::string & body, const std::string & content_type) inline
Definition at line 7841 of file httplib.h.
{
   return send_with_content_provider("PUT", path, headers, body.data(),
                                     body.size(), nullptr, nullptr,
                                     content_type);
 }
References send_with_content_provider().
Put() [9/15]
Result httplib::ClientImpl::Put (const std::string & path, const Headers & headers, ContentProviderWithoutLength content_provider, const std::string & content_type) inline
Definition at line 7871 of file httplib.h.
{
   return send_with_content_provider("PUT", path, headers, nullptr, 0, nullptr,
                                     std::move(content_provider), content_type);
 }
References send_with_content_provider().
Put() [10/15]
Result httplib::ClientImpl::Put (const std::string & path, const Headers & headers, size_t content_length, ContentProvider content_provider, const std::string & content_type) inline
Definition at line 7862 of file httplib.h.
{
   return send_with_content_provider("PUT", path, headers, nullptr,
                                     content_length, std::move(content_provider),
                                     nullptr, content_type);
 }
References send_with_content_provider().
Put() [11/15]
Result httplib::ClientImpl::Put (const std::string & path, const MultipartFormDataItems & items) inline
Definition at line 7888 of file httplib.h.
{
   return Put(path, Headers(), items);
 }
References Put().
Put() [12/15]
Result httplib::ClientImpl::Put (const std::string & path, const Params & params) inline
Definition at line 7878 of file httplib.h.
{
   return Put(path, Headers(), params);
 }
References Put().
Put() [13/15]
Result httplib::ClientImpl::Put (const std::string & path, const std::string & body, const std::string & content_type) inline
Definition at line 7836 of file httplib.h.
{
   return Put(path, Headers(), body, content_type);
 }
References Put().
Put() [14/15]
Result httplib::ClientImpl::Put (const std::string & path, ContentProviderWithoutLength content_provider, const std::string & content_type) inline
Definition at line 7856 of file httplib.h.
{
   return Put(path, Headers(), std::move(content_provider), content_type);
 }
References Put().
Put() [15/15]
Result httplib::ClientImpl::Put (const std::string & path, size_t content_length, ContentProvider content_provider, const std::string & content_type) inline
Definition at line 7849 of file httplib.h.
{
   return Put(path, Headers(), content_length, std::move(content_provider),
              content_type);
 }
References Put().
read_response_line()
bool httplib::ClientImpl::read_response_line (Stream & strm, const Request & req, Response & res) const inline private
Definition at line 6910 of file httplib.h.
{
   std::array<char, 2048> buf{};
   detail::stream_line_reader line_reader(strm, buf.data(), buf.size());
   if (!line_reader.getline()) { return false; }
 #ifdef CPPHTTPLIB_ALLOW_LF_AS_LINE_TERMINATOR
   const static std::regex re("(HTTP/1\\.[01]) (\\d{3})(?: (.*?))?\r?\n");
 #else
   const static std::regex re("(HTTP/1\\.[01]) (\\d{3})(?: (.*?))?\r\n");
 #endif
   std::cmatch m;
   if (!std::regex_match(line_reader.ptr(), m, re)) {
     return req.method == "CONNECT";
   }
   res.version = std::string(m[1]);
   res.status = std::stoi(std::string(m[2]));
   res.reason = std::string(m[3]);
   // Ignore '100 Continue'
   while (res.status == StatusCode::Continue_100) {
     if (!line_reader.getline()) { return false; } // CRLF
     if (!line_reader.getline()) { return false; } // next response line
     if (!std::regex_match(line_reader.ptr(), m, re)) { return false; }
     res.version = std::string(m[1]);
     res.status = std::stoi(std::string(m[2]));
     res.reason = std::string(m[3]);
   }
   return true;
 }
References httplib::Continue_100, httplib::detail::stream_line_reader::getline(), httplib::Request::method, httplib::detail::stream_line_reader::ptr(), httplib::Response::reason, httplib::Response::status, and httplib::Response::version.
Referenced by process_request().
redirect()
bool httplib::ClientImpl::redirect (Request & req, Response & res, Error & error) inline private
Definition at line 7134 of file httplib.h.
{
   if (req.redirect_count_ == 0) {
     error = Error::ExceedRedirectCount;
     return false;
   }
   auto location = res.get_header_value("location");
   if (location.empty()) { return false; }
   const static std::regex re(
       R"((?:(https?):)?(?://(?:\[([\d:]+)\]|([^:/?#]+))(?::(\d+))?)?([^?#]*)(\?[^#]*)?(?:#.*)?)");
   std::smatch m;
   if (!std::regex_match(location, m, re)) { return false; }
   auto scheme = is_ssl() ? "https" : "http";
   auto next_scheme = m[1].str();
   auto next_host = m[2].str();
   if (next_host.empty()) { next_host = m[3].str(); }
   auto port_str = m[4].str();
   auto next_path = m[5].str();
   auto next_query = m[6].str();
   auto next_port = port_;
   if (!port_str.empty()) {
     next_port = std::stoi(port_str);
   } else if (!next_scheme.empty()) {
     next_port = next_scheme == "https" ? 443 : 80;
   }
   if (next_scheme.empty()) { next_scheme = scheme; }
   if (next_host.empty()) { next_host = host_; }
   if (next_path.empty()) { next_path = "/"; }
   auto path = detail::decode_url(next_path, true) + next_query;
   if (next_scheme == scheme && next_host == host_ && next_port == port_) {
     return detail::redirect(*this, req, res, path, location, error);
   } else {
     if (next_scheme == "https") {
 #ifdef CPPHTTPLIB_OPENSSL_SUPPORT
       SSLClient cli(next_host, next_port);
       cli.copy_settings(*this);
       if (ca_cert_store_) { cli.set_ca_cert_store(ca_cert_store_); }
       return detail::redirect(cli, req, res, path, location, error);
 #else
       return false;
 #endif
     } else {
       ClientImpl cli(next_host, next_port);
       cli.copy_settings(*this);
       return detail::redirect(cli, req, res, path, location, error);
     }
   }
 }
References copy_settings(), httplib::detail::decode_url(), httplib::ExceedRedirectCount, httplib::Response::get_header_value(), host_, is_ssl(), port_, httplib::detail::redirect(), and httplib::Request::redirect_count_.
Referenced by handle_request(), and process_request().
send() [1/2]
Result httplib::ClientImpl::send (const Request & req) inline
Definition at line 7045 of file httplib.h.
{
   auto req2 = req;
   return send_(std::move(req2));
 }
References send_().
send() [2/2]
bool httplib::ClientImpl::send (Request & req, Response & res, Error & error) inline
Definition at line 6946 of file httplib.h.
{
   std::lock_guard<std::recursive_mutex> request_mutex_guard(request_mutex_);
   auto ret = send_(req, res, error);
   if (error == Error::SSLPeerCouldBeClosed_) {
     assert(!ret);
     ret = send_(req, res, error);
   }
   return ret;
 }
References assert(), request_mutex_, send_(), and httplib::SSLPeerCouldBeClosed_.
Referenced by handle_request(), send_(), and send_with_content_provider().
send_() [1/2]
Result httplib::ClientImpl::send_ (Request && req) inline private
Definition at line 7050 of file httplib.h.
{
   auto res = detail::make_unique<Response>();
   auto error = Error::Success;
   auto ret = send(req, *res, error);
   return Result{ret ? std::move(res) : nullptr, error, std::move(req.headers)};
 }
References send(), and httplib::Success.
send_() [2/2]
bool httplib::ClientImpl::send_ (Request & req, Response & res, Error & error) inline private
Definition at line 6956 of file httplib.h.
{
   {
     std::lock_guard<std::mutex> guard(socket_mutex_);
     // Set this to false immediately - if it ever gets set to true by the end of
     // the request, we know another thread instructed us to close the socket.
     socket_should_be_closed_when_request_is_done_ = false;
     auto is_alive = false;
     if (socket_.is_open()) {
       is_alive = detail::is_socket_alive(socket_.sock);
       if (!is_alive) {
         // Attempt to avoid sigpipe by shutting down nongracefully if it seems
         // like the other side has already closed the connection Also, there
         // cannot be any requests in flight from other threads since we locked
         // request_mutex_, so safe to close everything immediately
         const bool shutdown_gracefully = false;
         shutdown_ssl(socket_, shutdown_gracefully);
         shutdown_socket(socket_);
         close_socket(socket_);
       }
     }
     if (!is_alive) {
       if (!create_and_connect_socket(socket_, error)) { return false; }
 #ifdef CPPHTTPLIB_OPENSSL_SUPPORT
       // TODO: refactoring
       if (is_ssl()) {
         auto &scli = static_cast<SSLClient &>(*this);
         if (!proxy_host_.empty() && proxy_port_ != -1) {
           auto success = false;
           if (!scli.connect_with_proxy(socket_, res, success, error)) {
             return success;
           }
         }
         if (!scli.initialize_ssl(socket_, error)) { return false; }
       }
 #endif
     }
     // Mark the current socket as being in use so that it cannot be closed by
     // anyone else while this request is ongoing, even though we will be
     // releasing the mutex.
     if (socket_requests_in_flight_ > 1) {
       assert(socket_requests_are_from_thread_ == std::this_thread::get_id());
     }
     socket_requests_in_flight_ += 1;
     socket_requests_are_from_thread_ = std::this_thread::get_id();
   }
   for (const auto &header : default_headers_) {
     if (req.headers.find(header.first) == req.headers.end()) {
       req.headers.insert(header);
     }
   }
   auto ret = false;
   auto close_connection = !keep_alive_;
   auto se = detail::scope_exit([&]() {
     // Briefly lock mutex in order to mark that a request is no longer ongoing
     std::lock_guard<std::mutex> guard(socket_mutex_);
     socket_requests_in_flight_ -= 1;
     if (socket_requests_in_flight_ <= 0) {
       assert(socket_requests_in_flight_ == 0);
       socket_requests_are_from_thread_ = std::thread::id();
     }
     if (socket_should_be_closed_when_request_is_done_ || close_connection ||
         !ret) {
       shutdown_ssl(socket_, true);
       shutdown_socket(socket_);
       close_socket(socket_);
     }
   });
   ret = process_socket(socket_, [&](Stream &strm) {
     return handle_request(strm, req, res, close_connection, error);
   });
   if (!ret) {
     if (error == Error::Success) { error = Error::Unknown; }
   }
   return ret;
 }
References assert(), close_socket(), create_and_connect_socket(), default_headers_, handle_request(), httplib::Request::headers, httplib::ClientImpl::Socket::is_open(), httplib::detail::is_socket_alive(), is_ssl(), keep_alive_, process_socket(), proxy_host_, proxy_port_, shutdown_socket(), shutdown_ssl(), httplib::ClientImpl::Socket::sock, socket_, socket_mutex_, socket_requests_are_from_thread_, socket_requests_in_flight_, socket_should_be_closed_when_request_is_done_, httplib::Success, and httplib::Unknown.
Referenced by Delete(), Get(), Head(), Options(), and send().
send_with_content_provider() [1/2]
Result httplib::ClientImpl::send_with_content_provider (const std::string & method, const std::string & path, const Headers & headers, const char * body, size_t content_length, ContentProvider content_provider, ContentProviderWithoutLength content_provider_without_length, const std::string & content_type) inline private
Definition at line 7413 of file httplib.h.
{
   Request req;
   req.method = method;
   req.headers = headers;
   req.path = path;
   auto error = Error::Success;
   auto res = send_with_content_provider(
       req, body, content_length, std::move(content_provider),
       std::move(content_provider_without_length), content_type, error);
   return Result{std::move(res), error, std::move(req.headers)};
 }
References httplib::Request::headers, httplib::Request::method, httplib::Request::path, send_with_content_provider(), and httplib::Success.
send_with_content_provider() [2/2]
std::unique_ptr< Response > httplib::ClientImpl::send_with_content_provider (Request & req, const char * body, size_t content_length, ContentProvider content_provider, ContentProviderWithoutLength content_provider_without_length, const std::string & content_type, Error & error) inline private
Definition at line 7334 of file httplib.h.
{
   if (!content_type.empty()) { req.set_header("Content-Type", content_type); }
 #ifdef CPPHTTPLIB_ZLIB_SUPPORT
   if (compress_) { req.set_header("Content-Encoding", "gzip"); }
 #endif
 #ifdef CPPHTTPLIB_ZLIB_SUPPORT
   if (compress_ && !content_provider_without_length) {
     // TODO: Brotli support
     detail::gzip_compressor compressor;
     if (content_provider) {
       auto ok = true;
       size_t offset = 0;
       DataSink data_sink;
       data_sink.write = [&](const char *data, size_t data_len) -> bool {
         if (ok) {
           auto last = offset + data_len == content_length;
           auto ret = compressor.compress(
               data, data_len, last,
               [&](const char *compressed_data, size_t compressed_data_len) {
                 req.body.append(compressed_data, compressed_data_len);
                 return true;
               });
           if (ret) {
             offset += data_len;
           } else {
             ok = false;
           }
         }
         return ok;
       };
       while (ok && offset < content_length) {
         if (!content_provider(offset, content_length - offset, data_sink)) {
           error = Error::Canceled;
           return nullptr;
         }
       }
     } else {
       if (!compressor.compress(body, content_length, true,
                                [&](const char *data, size_t data_len) {
                                  req.body.append(data, data_len);
                                  return true;
                                })) {
         error = Error::Compression;
         return nullptr;
       }
     }
   } else
 #endif
   {
     if (content_provider) {
       req.content_length_ = content_length;
       req.content_provider_ = std::move(content_provider);
       req.is_chunked_content_provider_ = false;
     } else if (content_provider_without_length) {
       req.content_length_ = 0;
       req.content_provider_ = detail::ContentProviderAdapter(
           std::move(content_provider_without_length));
       req.is_chunked_content_provider_ = true;
       req.set_header("Transfer-Encoding", "chunked");
     } else {
       req.body.assign(body, content_length);
     }
   }
   auto res = detail::make_unique<Response>();
   return send(req, *res, error) ? std::move(res) : nullptr;
 }
References httplib::Request::body, httplib::Canceled, compress_, httplib::Compression, httplib::Request::content_length_, httplib::Request::content_provider_, httplib::Request::is_chunked_content_provider_, send(), httplib::Request::set_header(), and httplib::DataSink::write.
Referenced by Patch(), Post(), Put(), and send_with_content_provider().
set_address_family()
void httplib::ClientImpl::set_address_family (int family) inline
Definition at line 8132 of file httplib.h.
{
   address_family_ = family;
 }
References address_family_.
set_basic_auth()
void httplib::ClientImpl::set_basic_auth (const std::string & username, const std::string & password) inline
Definition at line 8094 of file httplib.h.
{
   basic_auth_username_ = username;
   basic_auth_password_ = password;
 }
References basic_auth_password_, and basic_auth_username_.
set_bearer_token_auth()
void httplib::ClientImpl::set_bearer_token_auth (const std::string & token) inline
Definition at line 8100 of file httplib.h.
{
   bearer_token_auth_token_ = token;
 }
References bearer_token_auth_token_.
set_compress()
void httplib::ClientImpl::set_compress (bool on) inline
Definition at line 8142 of file httplib.h.
 { compress_ = on; }
References compress_.
set_connection_timeout() [1/2]
template<class Rep , class Period > void httplib::ClientImpl::set_connection_timeout (const std::chrono::duration< Rep, Period > & duration) inline
Definition at line 2022 of file httplib.h.
{
   detail::duration_to_sec_and_usec(duration, [&](time_t sec, time_t usec) {
     set_connection_timeout(sec, usec);
   });
 }
References httplib::detail::duration_to_sec_and_usec(), sec, and set_connection_timeout().
set_connection_timeout() [2/2]
void httplib::ClientImpl::set_connection_timeout (time_t sec, time_t usec = 0) inline
Definition at line 8079 of file httplib.h.
{
   connection_timeout_sec_ = sec;
   connection_timeout_usec_ = usec;
 }
References connection_timeout_sec_, connection_timeout_usec_, and sec.
Referenced by set_connection_timeout().
set_decompress()
void httplib::ClientImpl::set_decompress (bool on) inline
Definition at line 8144 of file httplib.h.
 { decompress_ = on; }
References decompress_.
set_default_headers()
void httplib::ClientImpl::set_default_headers (Headers headers) inline
Definition at line 8123 of file httplib.h.
{
   default_headers_ = std::move(headers);
 }
References default_headers_.
set_follow_location()
void httplib::ClientImpl::set_follow_location (bool on) inline
Definition at line 8114 of file httplib.h.
 { follow_location_ = on; }
References follow_location_.
set_header_writer()
void httplib::ClientImpl::set_header_writer (std::function< ssize_t(Stream &, Headers &)> const & writer) inline
Definition at line 8127 of file httplib.h.
{
   header_writer_ = writer;
 }
References header_writer_.
set_hostname_addr_map()
void httplib::ClientImpl::set_hostname_addr_map (std::map< std::string, std::string > addr_map) inline
Definition at line 8119 of file httplib.h.
{
   addr_map_ = std::move(addr_map);
 }
References addr_map_.
set_interface()
void httplib::ClientImpl::set_interface (const std::string & intf) inline
Definition at line 8146 of file httplib.h.
{
   interface_ = intf;
 }
References interface_.
set_keep_alive()
void httplib::ClientImpl::set_keep_alive (bool on) inline
Definition at line 8112 of file httplib.h.
 { keep_alive_ = on; }
References keep_alive_.
set_logger()
void httplib::ClientImpl::set_logger (Logger logger) inline
Definition at line 8216 of file httplib.h.
{
   logger_ = std::move(logger);
 }
References logger_.
set_proxy()
void httplib::ClientImpl::set_proxy (const std::string & host, int port) inline
Definition at line 8150 of file httplib.h.
{
   proxy_host_ = host;
   proxy_port_ = port;
 }
References host(), port(), proxy_host_, and proxy_port_.
set_proxy_basic_auth()
void httplib::ClientImpl::set_proxy_basic_auth (const std::string & username, const std::string & password) inline
Definition at line 8155 of file httplib.h.
{
   proxy_basic_auth_username_ = username;
   proxy_basic_auth_password_ = password;
 }
References proxy_basic_auth_password_, and proxy_basic_auth_username_.
set_proxy_bearer_token_auth()
void httplib::ClientImpl::set_proxy_bearer_token_auth (const std::string & token) inline
Definition at line 8161 of file httplib.h.
{
   proxy_bearer_token_auth_token_ = token;
 }
References proxy_bearer_token_auth_token_.
set_read_timeout() [1/2]
template<class Rep , class Period > void httplib::ClientImpl::set_read_timeout (const std::chrono::duration< Rep, Period > & duration) inline
Definition at line 2030 of file httplib.h.
{
   detail::duration_to_sec_and_usec(
       duration, [&](time_t sec, time_t usec) { set_read_timeout(sec, usec); });
 }
References httplib::detail::duration_to_sec_and_usec(), sec, and set_read_timeout().
set_read_timeout() [2/2]
void httplib::ClientImpl::set_read_timeout (time_t sec, time_t usec = 0) inline
Definition at line 8084 of file httplib.h.
{
   read_timeout_sec_ = sec;
   read_timeout_usec_ = usec;
 }
References read_timeout_sec_, read_timeout_usec_, and sec.
Referenced by set_read_timeout().
set_socket_options()
void httplib::ClientImpl::set_socket_options (SocketOptions socket_options) inline
Definition at line 8138 of file httplib.h.
{
   socket_options_ = std::move(socket_options);
 }
References socket_options_.
set_tcp_nodelay()
void httplib::ClientImpl::set_tcp_nodelay (bool on) inline
Definition at line 8136 of file httplib.h.
 { tcp_nodelay_ = on; }
References tcp_nodelay_.
set_url_encode()
void httplib::ClientImpl::set_url_encode (bool on) inline
Definition at line 8116 of file httplib.h.
 { url_encode_ = on; }
References url_encode_.
set_write_timeout() [1/2]
template<class Rep , class Period > void httplib::ClientImpl::set_write_timeout (const std::chrono::duration< Rep, Period > & duration) inline
Definition at line 2037 of file httplib.h.
{
   detail::duration_to_sec_and_usec(
       duration, [&](time_t sec, time_t usec) { set_write_timeout(sec, usec); });
 }
References httplib::detail::duration_to_sec_and_usec(), sec, and set_write_timeout().
set_write_timeout() [2/2]
void httplib::ClientImpl::set_write_timeout (time_t sec, time_t usec = 0) inline
Definition at line 8089 of file httplib.h.
{
   write_timeout_sec_ = sec;
   write_timeout_usec_ = usec;
 }
References sec, write_timeout_sec_, and write_timeout_usec_.
Referenced by set_write_timeout().
shutdown_socket()
void httplib::ClientImpl::shutdown_socket (Socket & socket) const inline protected
Definition at line 6886 of file httplib.h.
{
   if (socket.sock == INVALID_SOCKET) { return; }
   detail::shutdown_socket(socket.sock);
 }
References INVALID_SOCKET, httplib::detail::shutdown_socket(), and socket().
Referenced by handle_request(), send_(), stop(), and ~ClientImpl().
shutdown_ssl()
void httplib::ClientImpl::shutdown_ssl (Socket & socket, bool shutdown_gracefully) inline protected virtual
Definition at line 6878 of file httplib.h.
{
   // If there are any requests in flight from threads other than us, then it's
   // a thread-unsafe race because individual ssl* objects are not thread-safe.
   assert(socket_requests_in_flight_ == 0 ||
          socket_requests_are_from_thread_ == std::this_thread::get_id());
 }
References assert(), socket_requests_are_from_thread_, and socket_requests_in_flight_.
Referenced by handle_request(), send_(), and stop().
socket()
socket_t httplib::ClientImpl::socket () const inline
Definition at line 8077 of file httplib.h.
 { return socket_.sock; }
References httplib::ClientImpl::Socket::sock, and socket_.
Referenced by close_socket(), create_and_connect_socket(), process_socket(), and shutdown_socket().
stop()
void httplib::ClientImpl::stop () inline
Definition at line 8045 of file httplib.h.
{
   std::lock_guard<std::mutex> guard(socket_mutex_);
   // If there is anything ongoing right now, the ONLY thread-safe thing we can
   // do is to shutdown_socket, so that threads using this socket suddenly
   // discover they can't read/write any more and error out. Everything else
   // (closing the socket, shutting ssl down) is unsafe because these actions are
   // not thread-safe.
   if (socket_requests_in_flight_ > 0) {
     shutdown_socket(socket_);
     // Aside from that, we set a flag for the socket to be closed when we're
     // done.
     socket_should_be_closed_when_request_is_done_ = true;
     return;
   }
   // Otherwise, still holding the mutex, we can shut everything down ourselves
   shutdown_ssl(socket_, true);
   shutdown_socket(socket_);
   close_socket(socket_);
 }
References close_socket(), shutdown_socket(), shutdown_ssl(), socket_, socket_mutex_, socket_requests_in_flight_, and socket_should_be_closed_when_request_is_done_.
write_content_with_provider()
bool httplib::ClientImpl::write_content_with_provider (Stream & strm, const Request & req, Error & error) const inline protected
Definition at line 7191 of file httplib.h.
{
   auto is_shutting_down = []() { return false; };
   if (req.is_chunked_content_provider_) {
     // TODO: Brotli support
     std::unique_ptr<detail::compressor> compressor;
 #ifdef CPPHTTPLIB_ZLIB_SUPPORT
     if (compress_) {
       compressor = detail::make_unique<detail::gzip_compressor>();
     } else
 #endif
     {
       compressor = detail::make_unique<detail::nocompressor>();
     }
     return detail::write_content_chunked(strm, req.content_provider_,
                                          is_shutting_down, *compressor, error);
   } else {
     return detail::write_content(strm, req.content_provider_, 0,
                                  req.content_length_, is_shutting_down, error);
   }
 }
References compress_, httplib::Request::content_length_, httplib::Request::content_provider_, httplib::Request::is_chunked_content_provider_, httplib::detail::write_content(), and httplib::detail::write_content_chunked().
Referenced by write_request().
write_request()
bool httplib::ClientImpl::write_request (Stream & strm, Request & req, bool close_connection, Error & error) inline private
Definition at line 7216 of file httplib.h.
{
   // Prepare additional headers
   if (close_connection) {
     if (!req.has_header("Connection")) {
       req.set_header("Connection", "close");
     }
   }
   if (!req.has_header("Host")) {
     if (is_ssl()) {
       if (port_ == 443) {
         req.set_header("Host", host_);
       } else {
         req.set_header("Host", host_and_port_);
       }
     } else {
       if (port_ == 80) {
         req.set_header("Host", host_);
       } else {
         req.set_header("Host", host_and_port_);
       }
     }
   }
   if (!req.has_header("Accept")) { req.set_header("Accept", "*/*"); }
 #ifndef CPPHTTPLIB_NO_DEFAULT_USER_AGENT
   if (!req.has_header("User-Agent")) {
     auto agent = std::string("cpp-httplib/") + CPPHTTPLIB_VERSION;
     req.set_header("User-Agent", agent);
   }
 #endif
   if (req.body.empty()) {
     if (req.content_provider_) {
       if (!req.is_chunked_content_provider_) {
         if (!req.has_header("Content-Length")) {
           auto length = std::to_string(req.content_length_);
           req.set_header("Content-Length", length);
         }
       }
     } else {
       if (req.method == "POST" || req.method == "PUT" ||
           req.method == "PATCH") {
         req.set_header("Content-Length", "0");
       }
     }
   } else {
     if (!req.has_header("Content-Type")) {
       req.set_header("Content-Type", "text/plain");
     }
     if (!req.has_header("Content-Length")) {
       auto length = std::to_string(req.body.size());
       req.set_header("Content-Length", length);
     }
   }
   if (!basic_auth_password_.empty() || !basic_auth_username_.empty()) {
     if (!req.has_header("Authorization")) {
       req.headers.insert(make_basic_authentication_header(
           basic_auth_username_, basic_auth_password_, false));
     }
   }
   if (!proxy_basic_auth_username_.empty() &&
       !proxy_basic_auth_password_.empty()) {
     if (!req.has_header("Proxy-Authorization")) {
       req.headers.insert(make_basic_authentication_header(
           proxy_basic_auth_username_, proxy_basic_auth_password_, true));
     }
   }
   if (!bearer_token_auth_token_.empty()) {
     if (!req.has_header("Authorization")) {
       req.headers.insert(make_bearer_token_authentication_header(
           bearer_token_auth_token_, false));
     }
   }
   if (!proxy_bearer_token_auth_token_.empty()) {
     if (!req.has_header("Proxy-Authorization")) {
       req.headers.insert(make_bearer_token_authentication_header(
           proxy_bearer_token_auth_token_, true));
     }
   }
   // Request line and headers
   {
     detail::BufferStream bstrm;
     const auto &path = url_encode_ ? detail::encode_url(req.path) : req.path;
     bstrm.write_format("%s %s HTTP/1.1\r\n", req.method.c_str(), path.c_str());
     header_writer_(bstrm, req.headers);
     // Flush buffer
     auto &data = bstrm.get_buffer();
     if (!detail::write_data(strm, data.data(), data.size())) {
       error = Error::Write;
       return false;
     }
   }
   // Body
   if (req.body.empty()) {
     return write_content_with_provider(strm, req, error);
   }
   if (!detail::write_data(strm, req.body.data(), req.body.size())) {
     error = Error::Write;
     return false;
   }
   return true;
 }
References basic_auth_password_, basic_auth_username_, bearer_token_auth_token_, httplib::Request::body, httplib::Request::content_length_, httplib::Request::content_provider_, CPPHTTPLIB_VERSION, httplib::detail::encode_url(), httplib::detail::BufferStream::get_buffer(), httplib::Request::has_header(), header_writer_, httplib::Request::headers, host_, host_and_port_, httplib::Request::is_chunked_content_provider_, is_ssl(), httplib::make_basic_authentication_header(), httplib::make_bearer_token_authentication_header(), httplib::Request::method, httplib::Request::path, port_, proxy_basic_auth_password_, proxy_basic_auth_username_, proxy_bearer_token_auth_token_, httplib::Request::set_header(), httplib::to_string(), url_encode_, httplib::Write, write_content_with_provider(), httplib::detail::write_data(), and httplib::Stream::write_format().
Referenced by process_request().
Member Data Documentation
addr_map_
std::map<std::string, std::string> httplib::ClientImpl::addr_map_ protected
Definition at line 1363 of file httplib.h.
Referenced by create_client_socket(), and set_hostname_addr_map().
address_family_
int httplib::ClientImpl::address_family_ = AF_UNSPEC protected
Definition at line 1396 of file httplib.h.
Referenced by copy_settings(), create_client_socket(), and set_address_family().
basic_auth_password_
std::string httplib::ClientImpl::basic_auth_password_ protected
Definition at line 1384 of file httplib.h.
Referenced by copy_settings(), set_basic_auth(), and write_request().
basic_auth_username_
std::string httplib::ClientImpl::basic_auth_username_ protected
Definition at line 1383 of file httplib.h.
Referenced by copy_settings(), set_basic_auth(), and write_request().
bearer_token_auth_token_
std::string httplib::ClientImpl::bearer_token_auth_token_ protected
Definition at line 1385 of file httplib.h.
Referenced by copy_settings(), set_bearer_token_auth(), and write_request().
client_cert_path_
std::string httplib::ClientImpl::client_cert_path_ protected
Definition at line 1373 of file httplib.h.
Referenced by copy_settings().
client_key_path_
std::string httplib::ClientImpl::client_key_path_ protected
Definition at line 1374 of file httplib.h.
Referenced by copy_settings().
compress_
bool httplib::ClientImpl::compress_ = false protected
Definition at line 1400 of file httplib.h.
Referenced by copy_settings(), send_with_content_provider(), set_compress(), and write_content_with_provider().
connection_timeout_sec_
time_t httplib::ClientImpl::connection_timeout_sec_ = 300 protected
Definition at line 1376 of file httplib.h.
Referenced by copy_settings(), create_client_socket(), and set_connection_timeout().
connection_timeout_usec_
time_t httplib::ClientImpl::connection_timeout_usec_ = 0 protected
Definition at line 1377 of file httplib.h.
Referenced by create_client_socket(), and set_connection_timeout().
decompress_
bool httplib::ClientImpl::decompress_ = true protected
Definition at line 1401 of file httplib.h.
Referenced by copy_settings(), process_request(), and set_decompress().
default_headers_
Headers httplib::ClientImpl::default_headers_ protected
Definition at line 1366 of file httplib.h.
Referenced by send_(), and set_default_headers().
follow_location_
bool httplib::ClientImpl::follow_location_ = false protected
Definition at line 1392 of file httplib.h.
Referenced by copy_settings(), handle_request(), process_request(), and set_follow_location().
header_writer_
std::function<ssize_t(Stream &, Headers &)> httplib::ClientImpl::header_writer_ protected
Initial value:
=
      detail::write_headers
Definition at line 1369 of file httplib.h.
Referenced by set_header_writer(), and write_request().
host_
const std::string httplib::ClientImpl::host_ protected
Definition at line 1348 of file httplib.h.
Referenced by create_client_socket(), host(), redirect(), and write_request().
host_and_port_
const std::string httplib::ClientImpl::host_and_port_ protected
Definition at line 1350 of file httplib.h.
Referenced by handle_request(), and write_request().
interface_
std::string httplib::ClientImpl::interface_ protected
Definition at line 1403 of file httplib.h.
Referenced by copy_settings(), create_client_socket(), and set_interface().
keep_alive_
bool httplib::ClientImpl::keep_alive_ = false protected
Definition at line 1391 of file httplib.h.
Referenced by copy_settings(), send_(), and set_keep_alive().
logger_
Logger httplib::ClientImpl::logger_ protected
Definition at line 1427 of file httplib.h.
Referenced by copy_settings(), process_request(), and set_logger().
port_
const int httplib::ClientImpl::port_ protected
Definition at line 1349 of file httplib.h.
Referenced by create_client_socket(), port(), redirect(), and write_request().
proxy_basic_auth_password_
std::string httplib::ClientImpl::proxy_basic_auth_password_ protected
Definition at line 1409 of file httplib.h.
Referenced by copy_settings(), set_proxy_basic_auth(), and write_request().
proxy_basic_auth_username_
std::string httplib::ClientImpl::proxy_basic_auth_username_ protected
Definition at line 1408 of file httplib.h.
Referenced by copy_settings(), set_proxy_basic_auth(), and write_request().
proxy_bearer_token_auth_token_
std::string httplib::ClientImpl::proxy_bearer_token_auth_token_ protected
Definition at line 1410 of file httplib.h.
Referenced by copy_settings(), set_proxy_bearer_token_auth(), and write_request().
proxy_host_
std::string httplib::ClientImpl::proxy_host_ protected
Definition at line 1405 of file httplib.h.
Referenced by copy_settings(), create_client_socket(), handle_request(), process_request(), send_(), and set_proxy().
proxy_port_
int httplib::ClientImpl::proxy_port_ = -1 protected
Definition at line 1406 of file httplib.h.
Referenced by copy_settings(), create_client_socket(), handle_request(), process_request(), send_(), and set_proxy().
read_timeout_sec_
time_t httplib::ClientImpl::read_timeout_sec_ = 5 protected
Definition at line 1378 of file httplib.h.
Referenced by copy_settings(), create_client_socket(), process_socket(), and set_read_timeout().
read_timeout_usec_
time_t httplib::ClientImpl::read_timeout_usec_ = 0 protected
Definition at line 1379 of file httplib.h.
Referenced by copy_settings(), create_client_socket(), process_socket(), and set_read_timeout().
request_mutex_
std::recursive_mutex httplib::ClientImpl::request_mutex_ protected
Definition at line 1355 of file httplib.h.
Referenced by send().
socket_
Socket httplib::ClientImpl::socket_ protected
Definition at line 1353 of file httplib.h.
Referenced by handle_request(), is_socket_open(), process_request(), send_(), socket(), stop(), and ~ClientImpl().
socket_mutex_
std::mutex httplib::ClientImpl::socket_mutex_ mutable protected
Definition at line 1354 of file httplib.h.
Referenced by handle_request(), is_socket_open(), send_(), stop(), and ~ClientImpl().
socket_options_
SocketOptions httplib::ClientImpl::socket_options_ = nullptr protected
Definition at line 1398 of file httplib.h.
Referenced by copy_settings(), create_client_socket(), and set_socket_options().
socket_requests_are_from_thread_
std::thread::id httplib::ClientImpl::socket_requests_are_from_thread_ = std::thread::id() protected
Definition at line 1359 of file httplib.h.
Referenced by close_socket(), send_(), and shutdown_ssl().
socket_requests_in_flight_
size_t httplib::ClientImpl::socket_requests_in_flight_ = 0 protected
Definition at line 1358 of file httplib.h.
Referenced by close_socket(), send_(), shutdown_ssl(), and stop().
socket_should_be_closed_when_request_is_done_
bool httplib::ClientImpl::socket_should_be_closed_when_request_is_done_ = false protected
Definition at line 1360 of file httplib.h.
Referenced by send_(), and stop().
tcp_nodelay_
bool httplib::ClientImpl::tcp_nodelay_ = false protected
Definition at line 1397 of file httplib.h.
Referenced by copy_settings(), create_client_socket(), and set_tcp_nodelay().
url_encode_
bool httplib::ClientImpl::url_encode_ = true protected
Definition at line 1394 of file httplib.h.
Referenced by copy_settings(), set_url_encode(), and write_request().
write_timeout_sec_
time_t httplib::ClientImpl::write_timeout_sec_ = 5 protected
Definition at line 1380 of file httplib.h.
Referenced by copy_settings(), create_client_socket(), process_socket(), and set_write_timeout().
write_timeout_usec_
time_t httplib::ClientImpl::write_timeout_usec_ = 0 protected
Definition at line 1381 of file httplib.h.
Referenced by copy_settings(), create_client_socket(), process_socket(), and set_write_timeout().
The documentation for this class was generated from the following file:
mc_orchestrator/httplib/httplib.h