Mixed Criticality Orchestrator: nlohmann::detail::iter_impl< BasicJsonType > Class Template Reference
nlohmann::detail::iter_impl< BasicJsonType > Class Template Reference
a template for a bidirectional iterator for the basic_json class This class implements a both iterators (iterator and const_iterator) for the basic_json class.
#include <iter_impl.hpp>
Public Types
using iterator_category = std::bidirectional_iterator_tag
using value_type = typename BasicJsonType::value_type
the type of the values when the iterator is dereferenced
using difference_type = typename BasicJsonType::difference_type
a type to represent differences between iterators
using pointer = typename std::conditional< std::is_const< BasicJsonType >::value, typename BasicJsonType::const_pointer, typename BasicJsonType::pointer >::type
defines a pointer to the type iterated over (value_type)
using reference = typename std::conditional< std::is_const< BasicJsonType >::value, typename BasicJsonType::const_reference, typename BasicJsonType::reference >::type
defines a reference to the type iterated over (value_type)
using iterator_category = std::bidirectional_iterator_tag
using value_type = typename BasicJsonType::value_type
the type of the values when the iterator is dereferenced
using difference_type = typename BasicJsonType::difference_type
a type to represent differences between iterators
using pointer = typename std::conditional< std::is_const< BasicJsonType >::value, typename BasicJsonType::const_pointer, typename BasicJsonType::pointer >::type
defines a pointer to the type iterated over (value_type)
using reference = typename std::conditional< std::is_const< BasicJsonType >::value, typename BasicJsonType::const_reference, typename BasicJsonType::reference >::type
defines a reference to the type iterated over (value_type)
Public Member Functions
iter_impl ()=default
default constructor
iter_impl (pointer object) noexcept
constructor for a given JSON instance
iter_impl (const iter_impl< const BasicJsonType > &other) noexcept
const copy constructor
iter_impl & operator= (const iter_impl< const BasicJsonType > &other) noexcept
converting assignment
iter_impl (const iter_impl< typename std::remove_const< BasicJsonType >::type > &other) noexcept
converting constructor
iter_impl & operator= (const iter_impl< typename std::remove_const< BasicJsonType >::type > &other) noexcept
converting assignment
reference operator* () const
return a reference to the value pointed to by the iterator
pointer operator-> () const
dereference the iterator
const iter_impl operator++ (int)
post-increment (it++)
iter_impl & operator++ ()
pre-increment (++it)
const iter_impl operator-- (int)
post-decrement (it–)
iter_impl & operator-- ()
pre-decrement (–it)
bool operator== (const iter_impl &other) const
comparison: equal
bool operator!= (const iter_impl &other) const
comparison: not equal
bool operator< (const iter_impl &other) const
comparison: smaller
bool operator<= (const iter_impl &other) const
comparison: less than or equal
bool operator> (const iter_impl &other) const
comparison: greater than
bool operator>= (const iter_impl &other) const
comparison: greater than or equal
iter_impl & operator+= (difference_type i)
add to iterator
iter_impl & operator-= (difference_type i)
subtract from iterator
iter_impl operator+ (difference_type i) const
add to iterator
iter_impl operator- (difference_type i) const
subtract from iterator
difference_type operator- (const iter_impl &other) const
return difference
reference operator[] (difference_type n) const
access to successor
const object_t::key_type & key () const
return the key of an object iterator
reference value () const
return the value of an iterator
iter_impl ()=default
default constructor
iter_impl (pointer object) noexcept
constructor for a given JSON instance
iter_impl (const iter_impl< const BasicJsonType > &other) noexcept
const copy constructor
iter_impl & operator= (const iter_impl< const BasicJsonType > &other) noexcept
converting assignment
iter_impl (const iter_impl< typename std::remove_const< BasicJsonType >::type > &other) noexcept
converting constructor
iter_impl & operator= (const iter_impl< typename std::remove_const< BasicJsonType >::type > &other) noexcept
converting assignment
reference operator* () const
return a reference to the value pointed to by the iterator
pointer operator-> () const
dereference the iterator
const iter_impl operator++ (int)
post-increment (it++)
iter_impl & operator++ ()
pre-increment (++it)
const iter_impl operator-- (int)
post-decrement (it–)
iter_impl & operator-- ()
pre-decrement (–it)
bool operator== (const iter_impl &other) const
comparison: equal
bool operator!= (const iter_impl &other) const
comparison: not equal
bool operator< (const iter_impl &other) const
comparison: smaller
bool operator<= (const iter_impl &other) const
comparison: less than or equal
bool operator> (const iter_impl &other) const
comparison: greater than
bool operator>= (const iter_impl &other) const
comparison: greater than or equal
iter_impl & operator+= (difference_type i)
add to iterator
iter_impl & operator-= (difference_type i)
subtract from iterator
iter_impl operator+ (difference_type i) const
add to iterator
iter_impl operator- (difference_type i) const
subtract from iterator
difference_type operator- (const iter_impl &other) const
return difference
reference operator[] (difference_type n) const
access to successor
const object_t::key_type & key () const
return the key of an object iterator
reference value () const
return the value of an iterator
Private Types
using object_t = typename BasicJsonType::object_t
using array_t = typename BasicJsonType::array_t
using object_t = typename BasicJsonType::object_t
using array_t = typename BasicJsonType::array_t
Private Member Functions
void set_begin () noexcept
set the iterator to the first value
void set_end () noexcept
set the iterator past the last value
void set_begin () noexcept
set the iterator to the first value
void set_end () noexcept
set the iterator past the last value
Private Attributes
friend BasicJsonType
friend iteration_proxy< iter_impl >
friend iteration_proxy_value< iter_impl >
pointer m_object = nullptr
associated JSON instance
internal_iterator< typename std::remove_const< BasicJsonType >::type > m_it {}
the actual iterator of the associated instance
Friends
iter_impl operator+ (difference_type i, const iter_impl &it)
addition of distance and iterator
iter_impl operator+ (difference_type i, const iter_impl &it)
addition of distance and iterator
Detailed Description
template<typename BasicJsonType>
class nlohmann::detail::iter_impl< BasicJsonType >
a template for a bidirectional iterator for the basic_json class This class implements a both iterators (iterator and const_iterator) for the basic_json class.
Note
An iterator is called initialized when a pointer to a JSON value has been set (e.g., by a constructor or a copy assignment). If the iterator is default-constructed, it is uninitialized and most methods are undefined. The library uses assertions to detect calls on uninitialized iterators.** @requirement The class satisfies the following concept requirements:
BidirectionalIterator: The iterator that can be moved can be moved in both directions (i.e. incremented and decremented).
Since
version 1.0.0, simplified in version 2.0.9, change to bidirectional iterators in version 3.0.0 (see https://github.com/nlohmann/json/issues/593)
Definition at line 40 of file iter_impl.hpp.
Member Typedef Documentation
array_t [1/2]
template<typename BasicJsonType > using nlohmann::detail::iter_impl< BasicJsonType >::array_t = typename BasicJsonType::array_t private
Definition at line 49 of file iter_impl.hpp.
array_t [2/2]
template<typename BasicJsonType > using nlohmann::detail::iter_impl< BasicJsonType >::array_t = typename BasicJsonType::array_t private
Definition at line 9355 of file json.hpp.
difference_type [1/2]
template<typename BasicJsonType > using nlohmann::detail::iter_impl< BasicJsonType >::difference_type = typename BasicJsonType::difference_type
a type to represent differences between iterators
Definition at line 66 of file iter_impl.hpp.
difference_type [2/2]
template<typename BasicJsonType > using nlohmann::detail::iter_impl< BasicJsonType >::difference_type = typename BasicJsonType::difference_type
a type to represent differences between iterators
Definition at line 9372 of file json.hpp.
iterator_category [1/2]
template<typename BasicJsonType > using nlohmann::detail::iter_impl< BasicJsonType >::iterator_category = std::bidirectional_iterator_tag
The std::iterator class template (used as a base class to provide typedefs) is deprecated in C++17. The C++ Standard has never required user-defined iterators to derive from std::iterator. A user-defined iterator should provide publicly accessible typedefs named iterator_category, value_type, difference_type, pointer, and reference. Note that value_type is required to be non-const, even for constant iterators.
Definition at line 61 of file iter_impl.hpp.
iterator_category [2/2]
template<typename BasicJsonType > using nlohmann::detail::iter_impl< BasicJsonType >::iterator_category = std::bidirectional_iterator_tag
The std::iterator class template (used as a base class to provide typedefs) is deprecated in C++17. The C++ Standard has never required user-defined iterators to derive from std::iterator. A user-defined iterator should provide publicly accessible typedefs named iterator_category, value_type, difference_type, pointer, and reference. Note that value_type is required to be non-const, even for constant iterators.
Definition at line 9367 of file json.hpp.
object_t [1/2]
template<typename BasicJsonType > using nlohmann::detail::iter_impl< BasicJsonType >::object_t = typename BasicJsonType::object_t private
Definition at line 48 of file iter_impl.hpp.
object_t [2/2]
template<typename BasicJsonType > using nlohmann::detail::iter_impl< BasicJsonType >::object_t = typename BasicJsonType::object_t private
Definition at line 9354 of file json.hpp.
pointer [1/2]
template<typename BasicJsonType > using nlohmann::detail::iter_impl< BasicJsonType >::pointer = typename std::conditional<std::is_const<BasicJsonType>::value, typename BasicJsonType::const_pointer, typename BasicJsonType::pointer>::type
defines a pointer to the type iterated over (value_type)
Definition at line 70 of file iter_impl.hpp.
pointer [2/2]
template<typename BasicJsonType > using nlohmann::detail::iter_impl< BasicJsonType >::pointer = typename std::conditional<std::is_const<BasicJsonType>::value, typename BasicJsonType::const_pointer, typename BasicJsonType::pointer>::type
defines a pointer to the type iterated over (value_type)
Definition at line 9376 of file json.hpp.
reference [1/2]
template<typename BasicJsonType > using nlohmann::detail::iter_impl< BasicJsonType >::reference = typename std::conditional<std::is_const<BasicJsonType>::value, typename BasicJsonType::const_reference, typename BasicJsonType::reference>::type
defines a reference to the type iterated over (value_type)
Definition at line 75 of file iter_impl.hpp.
reference [2/2]
template<typename BasicJsonType > using nlohmann::detail::iter_impl< BasicJsonType >::reference = typename std::conditional<std::is_const<BasicJsonType>::value, typename BasicJsonType::const_reference, typename BasicJsonType::reference>::type
defines a reference to the type iterated over (value_type)
Definition at line 9381 of file json.hpp.
value_type [1/2]
template<typename BasicJsonType > using nlohmann::detail::iter_impl< BasicJsonType >::value_type = typename BasicJsonType::value_type
the type of the values when the iterator is dereferenced
Definition at line 64 of file iter_impl.hpp.
value_type [2/2]
template<typename BasicJsonType > using nlohmann::detail::iter_impl< BasicJsonType >::value_type = typename BasicJsonType::value_type
the type of the values when the iterator is dereferenced
Definition at line 9370 of file json.hpp.
Constructor & Destructor Documentation
iter_impl() [1/8]
template<typename BasicJsonType > iter_impl< typename std::conditional< std::is_const< BasicJsonType >::value, typename std::remove_const< BasicJsonType >::type, const BasicJsonType >::type > () default
default constructor
allow basic_json to access private members
Definition at line 43 of file iter_impl.hpp.
iter_impl() [2/8]
template<typename BasicJsonType > nlohmann::detail::iter_impl< BasicJsonType >::iter_impl (pointer object) inline explicit noexcept
constructor for a given JSON instance
Parameters
[in] object pointer to a JSON object for this iterator
Precondition
object != nullptr
Postcondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 86 of file iter_impl.hpp.
                                                 : m_object(object)
     {
         assert(m_object != nullptr);
         switch (m_object->m_type)
         {
             case value_t::object:
             {
                 m_it.object_iterator = typename object_t::iterator();
                 break;
             }
             case value_t::array:
             {
                 m_it.array_iterator = typename array_t::iterator();
                 break;
             }
             default:
             {
                 m_it.primitive_iterator = primitive_iterator_t();
                 break;
             }
         }
     }
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, assert(), nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
iter_impl() [3/8]
template<typename BasicJsonType > nlohmann::detail::iter_impl< BasicJsonType >::iter_impl (const iter_impl< const BasicJsonType > & other) inline noexcept
const copy constructor
Note
The conventional copy constructor and copy assignment are implicitly defined. Combined with the following converting constructor and assignment, they support: (1) copy from iterator to iterator, (2) copy from const iterator to const iterator, and (3) conversion from iterator to const iterator. However conversion from const iterator to iterator is not defined.
Parameters
[in] other const iterator to copy from
Note
This copy constructor had to be defined explicitly to circumvent a bug occurring on msvc v19.0 compiler (VS 2015) debug build. For more information refer to: https://github.com/nlohmann/json/issues/1608
Definition at line 128 of file iter_impl.hpp.
         : m_object(other.m_object), m_it(other.m_it)
     {}
iter_impl() [4/8]
template<typename BasicJsonType > nlohmann::detail::iter_impl< BasicJsonType >::iter_impl (const iter_impl< typename std::remove_const< BasicJsonType >::type > & other) inline noexcept
converting constructor
Parameters
[in] other non-const iterator to copy from
Note
It is not checked whether other is initialized.
Definition at line 150 of file iter_impl.hpp.
         : m_object(other.m_object), m_it(other.m_it)
     {}
iter_impl() [5/8]
template<typename BasicJsonType > nlohmann::detail::iter_impl< BasicJsonType >::iter_impl () default
default constructor
iter_impl() [6/8]
template<typename BasicJsonType > nlohmann::detail::iter_impl< BasicJsonType >::iter_impl (pointer object) inline explicit noexcept
constructor for a given JSON instance
Parameters
[in] object pointer to a JSON object for this iterator
Precondition
object != nullptr
Postcondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9392 of file json.hpp.
                                                 : m_object(object)
     {
         assert(m_object != nullptr);
         switch (m_object->m_type)
         {
             case value_t::object:
             {
                 m_it.object_iterator = typename object_t::iterator();
                 break;
             }
             case value_t::array:
             {
                 m_it.array_iterator = typename array_t::iterator();
                 break;
             }
             default:
             {
                 m_it.primitive_iterator = primitive_iterator_t();
                 break;
             }
         }
     }
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, assert(), nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
iter_impl() [7/8]
template<typename BasicJsonType > nlohmann::detail::iter_impl< BasicJsonType >::iter_impl (const iter_impl< const BasicJsonType > & other) inline noexcept
const copy constructor
Note
The conventional copy constructor and copy assignment are implicitly defined. Combined with the following converting constructor and assignment, they support: (1) copy from iterator to iterator, (2) copy from const iterator to const iterator, and (3) conversion from iterator to const iterator. However conversion from const iterator to iterator is not defined.
Parameters
[in] other const iterator to copy from
Note
This copy constructor had to be defined explicitly to circumvent a bug occurring on msvc v19.0 compiler (VS 2015) debug build. For more information refer to: https://github.com/nlohmann/json/issues/1608
Definition at line 9434 of file json.hpp.
         : m_object(other.m_object), m_it(other.m_it)
     {}
iter_impl() [8/8]
template<typename BasicJsonType > nlohmann::detail::iter_impl< BasicJsonType >::iter_impl (const iter_impl< typename std::remove_const< BasicJsonType >::type > & other) inline noexcept
converting constructor
Parameters
[in] other non-const iterator to copy from
Note
It is not checked whether other is initialized.
Definition at line 9456 of file json.hpp.
         : m_object(other.m_object), m_it(other.m_it)
     {}
Member Function Documentation
key() [1/2]
template<typename BasicJsonType > const object_t::key_type& nlohmann::detail::iter_impl< BasicJsonType >::key () const inline
return the key of an object iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 610 of file iter_impl.hpp.
     {
         assert(m_object != nullptr);
         if (JSON_HEDLEY_LIKELY(m_object->is_object()))
         {
             return m_it.object_iterator->first;
         }
         JSON_THROW(invalid_iterator::create(207, "cannot use key() for non-object iterators"));
     }
References assert(), nlohmann::detail::invalid_iterator::create(), JSON_HEDLEY_LIKELY, JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, and nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator.
Referenced by main().
key() [2/2]
template<typename BasicJsonType > const object_t::key_type& nlohmann::detail::iter_impl< BasicJsonType >::key () const inline
return the key of an object iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9916 of file json.hpp.
     {
         assert(m_object != nullptr);
         if (JSON_HEDLEY_LIKELY(m_object->is_object()))
         {
             return m_it.object_iterator->first;
         }
         JSON_THROW(invalid_iterator::create(207, "cannot use key() for non-object iterators"));
     }
References assert(), nlohmann::detail::invalid_iterator::create(), JSON_HEDLEY_LIKELY, JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, and nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator.
operator!=() [1/2]
template<typename BasicJsonType > bool nlohmann::detail::iter_impl< BasicJsonType >::operator!= (const iter_impl< BasicJsonType > & other) const inline
comparison: not equal
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 424 of file iter_impl.hpp.
     {
         return not operator==(other);
     }
References nlohmann::detail::iter_impl< BasicJsonType >::operator==().
operator!=() [2/2]
template<typename BasicJsonType > bool nlohmann::detail::iter_impl< BasicJsonType >::operator!= (const iter_impl< BasicJsonType > & other) const inline
comparison: not equal
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9730 of file json.hpp.
     {
         return not operator==(other);
     }
References nlohmann::detail::iter_impl< BasicJsonType >::operator==().
operator*() [1/2]
template<typename BasicJsonType > reference nlohmann::detail::iter_impl< BasicJsonType >::operator* () const inline
return a reference to the value pointed to by the iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 240 of file iter_impl.hpp.
     {
         assert(m_object != nullptr);
         switch (m_object->m_type)
         {
             case value_t::object:
             {
                 assert(m_it.object_iterator != m_object->m_value.object->end());
                 return m_it.object_iterator->second;
             }
             case value_t::array:
             {
                 assert(m_it.array_iterator != m_object->m_value.array->end());
                 return *m_it.array_iterator;
             }
             case value_t::null:
                 JSON_THROW(invalid_iterator::create(214, "cannot get value"));
             default:
             {
                 if (JSON_HEDLEY_LIKELY(m_it.primitive_iterator.is_begin()))
                 {
                     return *m_object;
                 }
                 JSON_THROW(invalid_iterator::create(214, "cannot get value"));
             }
         }
     }
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, assert(), nlohmann::detail::invalid_iterator::create(), nlohmann::detail::primitive_iterator_t::is_begin(), JSON_HEDLEY_LIKELY, JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::null, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
Referenced by nlohmann::detail::iter_impl< BasicJsonType >::value().
operator*() [2/2]
template<typename BasicJsonType > reference nlohmann::detail::iter_impl< BasicJsonType >::operator* () const inline
return a reference to the value pointed to by the iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9546 of file json.hpp.
     {
         assert(m_object != nullptr);
         switch (m_object->m_type)
         {
             case value_t::object:
             {
                 assert(m_it.object_iterator != m_object->m_value.object->end());
                 return m_it.object_iterator->second;
             }
             case value_t::array:
             {
                 assert(m_it.array_iterator != m_object->m_value.array->end());
                 return *m_it.array_iterator;
             }
             case value_t::null:
                 JSON_THROW(invalid_iterator::create(214, "cannot get value"));
             default:
             {
                 if (JSON_HEDLEY_LIKELY(m_it.primitive_iterator.is_begin()))
                 {
                     return *m_object;
                 }
                 JSON_THROW(invalid_iterator::create(214, "cannot get value"));
             }
         }
     }
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, assert(), nlohmann::detail::invalid_iterator::create(), nlohmann::detail::primitive_iterator_t::is_begin(), JSON_HEDLEY_LIKELY, JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::null, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
operator+() [1/2]
template<typename BasicJsonType > iter_impl nlohmann::detail::iter_impl< BasicJsonType >::operator+ (difference_type i) const inline
add to iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 525 of file iter_impl.hpp.
     {
         auto result = *this;
         result += i;
         return result;
     }
References result.
operator+() [2/2]
template<typename BasicJsonType > iter_impl nlohmann::detail::iter_impl< BasicJsonType >::operator+ (difference_type i) const inline
add to iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9831 of file json.hpp.
     {
         auto result = *this;
         result += i;
         return result;
     }
References result.
operator++() [1/4]
template<typename BasicJsonType > iter_impl& nlohmann::detail::iter_impl< BasicJsonType >::operator++ () inline
pre-increment (++it)
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 322 of file iter_impl.hpp.
     {
         assert(m_object != nullptr);
         switch (m_object->m_type)
         {
             case value_t::object:
             {
                 std::advance(m_it.object_iterator, 1);
                 break;
             }
             case value_t::array:
             {
                 std::advance(m_it.array_iterator, 1);
                 break;
             }
             default:
             {
                 ++m_it.primitive_iterator;
                 break;
             }
         }
         return *this;
     }
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, assert(), nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
operator++() [2/4]
template<typename BasicJsonType > iter_impl& nlohmann::detail::iter_impl< BasicJsonType >::operator++ () inline
pre-increment (++it)
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9628 of file json.hpp.
     {
         assert(m_object != nullptr);
         switch (m_object->m_type)
         {
             case value_t::object:
             {
                 std::advance(m_it.object_iterator, 1);
                 break;
             }
             case value_t::array:
             {
                 std::advance(m_it.array_iterator, 1);
                 break;
             }
             default:
             {
                 ++m_it.primitive_iterator;
                 break;
             }
         }
         return *this;
     }
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, assert(), nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
operator++() [3/4]
template<typename BasicJsonType > const iter_impl nlohmann::detail::iter_impl< BasicJsonType >::operator++ (int) inline
post-increment (it++)
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 311 of file iter_impl.hpp.
     {
         auto result = *this;
         ++(*this);
         return result;
     }
References result.
operator++() [4/4]
template<typename BasicJsonType > const iter_impl nlohmann::detail::iter_impl< BasicJsonType >::operator++ (int) inline
post-increment (it++)
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9617 of file json.hpp.
     {
         auto result = *this;
         ++(*this);
         return result;
     }
References result.
operator+=() [1/2]
template<typename BasicJsonType > iter_impl& nlohmann::detail::iter_impl< BasicJsonType >::operator+= (difference_type i) inline
add to iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 487 of file iter_impl.hpp.
     {
         assert(m_object != nullptr);
         switch (m_object->m_type)
         {
             case value_t::object:
                 JSON_THROW(invalid_iterator::create(209, "cannot use offsets with object iterators"));
             case value_t::array:
             {
                 std::advance(m_it.array_iterator, i);
                 break;
             }
             default:
             {
                 m_it.primitive_iterator += i;
                 break;
             }
         }
         return *this;
     }
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, assert(), nlohmann::detail::invalid_iterator::create(), JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
Referenced by nlohmann::detail::iter_impl< BasicJsonType >::operator-=().
operator+=() [2/2]
template<typename BasicJsonType > iter_impl& nlohmann::detail::iter_impl< BasicJsonType >::operator+= (difference_type i) inline
add to iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9793 of file json.hpp.
     {
         assert(m_object != nullptr);
         switch (m_object->m_type)
         {
             case value_t::object:
                 JSON_THROW(invalid_iterator::create(209, "cannot use offsets with object iterators"));
             case value_t::array:
             {
                 std::advance(m_it.array_iterator, i);
                 break;
             }
             default:
             {
                 m_it.primitive_iterator += i;
                 break;
             }
         }
         return *this;
     }
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, assert(), nlohmann::detail::invalid_iterator::create(), JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
operator-() [1/4]
template<typename BasicJsonType > difference_type nlohmann::detail::iter_impl< BasicJsonType >::operator- (const iter_impl< BasicJsonType > & other) const inline
return difference
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 558 of file iter_impl.hpp.
     {
         assert(m_object != nullptr);
         switch (m_object->m_type)
         {
             case value_t::object:
                 JSON_THROW(invalid_iterator::create(209, "cannot use offsets with object iterators"));
             case value_t::array:
                 return m_it.array_iterator - other.m_it.array_iterator;
             default:
                 return m_it.primitive_iterator - other.m_it.primitive_iterator;
         }
     }
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, assert(), nlohmann::detail::invalid_iterator::create(), JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
operator-() [2/4]
template<typename BasicJsonType > difference_type nlohmann::detail::iter_impl< BasicJsonType >::operator- (const iter_impl< BasicJsonType > & other) const inline
return difference
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9864 of file json.hpp.
     {
         assert(m_object != nullptr);
         switch (m_object->m_type)
         {
             case value_t::object:
                 JSON_THROW(invalid_iterator::create(209, "cannot use offsets with object iterators"));
             case value_t::array:
                 return m_it.array_iterator - other.m_it.array_iterator;
             default:
                 return m_it.primitive_iterator - other.m_it.primitive_iterator;
         }
     }
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, assert(), nlohmann::detail::invalid_iterator::create(), JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
operator-() [3/4]
template<typename BasicJsonType > iter_impl nlohmann::detail::iter_impl< BasicJsonType >::operator- (difference_type i) const inline
subtract from iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 547 of file iter_impl.hpp.
     {
         auto result = *this;
         result -= i;
         return result;
     }
References result.
operator-() [4/4]
template<typename BasicJsonType > iter_impl nlohmann::detail::iter_impl< BasicJsonType >::operator- (difference_type i) const inline
subtract from iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9853 of file json.hpp.
     {
         auto result = *this;
         result -= i;
         return result;
     }
References result.
operator--() [1/4]
template<typename BasicJsonType > iter_impl& nlohmann::detail::iter_impl< BasicJsonType >::operator-- () inline
pre-decrement (–it)
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 365 of file iter_impl.hpp.
     {
         assert(m_object != nullptr);
         switch (m_object->m_type)
         {
             case value_t::object:
             {
                 std::advance(m_it.object_iterator, -1);
                 break;
             }
             case value_t::array:
             {
                 std::advance(m_it.array_iterator, -1);
                 break;
             }
             default:
             {
                 --m_it.primitive_iterator;
                 break;
             }
         }
         return *this;
     }
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, assert(), nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
operator--() [2/4]
template<typename BasicJsonType > iter_impl& nlohmann::detail::iter_impl< BasicJsonType >::operator-- () inline
pre-decrement (–it)
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9671 of file json.hpp.
     {
         assert(m_object != nullptr);
         switch (m_object->m_type)
         {
             case value_t::object:
             {
                 std::advance(m_it.object_iterator, -1);
                 break;
             }
             case value_t::array:
             {
                 std::advance(m_it.array_iterator, -1);
                 break;
             }
             default:
             {
                 --m_it.primitive_iterator;
                 break;
             }
         }
         return *this;
     }
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, assert(), nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
operator--() [3/4]
template<typename BasicJsonType > const iter_impl nlohmann::detail::iter_impl< BasicJsonType >::operator-- (int) inline
post-decrement (it–)
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 354 of file iter_impl.hpp.
     {
         auto result = *this;
         --(*this);
         return result;
     }
References result.
operator--() [4/4]
template<typename BasicJsonType > const iter_impl nlohmann::detail::iter_impl< BasicJsonType >::operator-- (int) inline
post-decrement (it–)
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9660 of file json.hpp.
     {
         auto result = *this;
         --(*this);
         return result;
     }
References result.
operator-=() [1/2]
template<typename BasicJsonType > iter_impl& nlohmann::detail::iter_impl< BasicJsonType >::operator-= (difference_type i) inline
subtract from iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 516 of file iter_impl.hpp.
     {
         return operator+=(-i);
     }
References nlohmann::detail::iter_impl< BasicJsonType >::operator+=().
operator-=() [2/2]
template<typename BasicJsonType > iter_impl& nlohmann::detail::iter_impl< BasicJsonType >::operator-= (difference_type i) inline
subtract from iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9822 of file json.hpp.
     {
         return operator+=(-i);
     }
References nlohmann::detail::iter_impl< BasicJsonType >::operator+=().
operator->() [1/2]
template<typename BasicJsonType > pointer nlohmann::detail::iter_impl< BasicJsonType >::operator-> () const inline
dereference the iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 277 of file iter_impl.hpp.
     {
         assert(m_object != nullptr);
         switch (m_object->m_type)
         {
             case value_t::object:
             {
                 assert(m_it.object_iterator != m_object->m_value.object->end());
                 return &(m_it.object_iterator->second);
             }
             case value_t::array:
             {
                 assert(m_it.array_iterator != m_object->m_value.array->end());
                 return &*m_it.array_iterator;
             }
             default:
             {
                 if (JSON_HEDLEY_LIKELY(m_it.primitive_iterator.is_begin()))
                 {
                     return m_object;
                 }
                 JSON_THROW(invalid_iterator::create(214, "cannot get value"));
             }
         }
     }
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, assert(), nlohmann::detail::invalid_iterator::create(), nlohmann::detail::primitive_iterator_t::is_begin(), JSON_HEDLEY_LIKELY, JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
operator->() [2/2]
template<typename BasicJsonType > pointer nlohmann::detail::iter_impl< BasicJsonType >::operator-> () const inline
dereference the iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9583 of file json.hpp.
     {
         assert(m_object != nullptr);
         switch (m_object->m_type)
         {
             case value_t::object:
             {
                 assert(m_it.object_iterator != m_object->m_value.object->end());
                 return &(m_it.object_iterator->second);
             }
             case value_t::array:
             {
                 assert(m_it.array_iterator != m_object->m_value.array->end());
                 return &*m_it.array_iterator;
             }
             default:
             {
                 if (JSON_HEDLEY_LIKELY(m_it.primitive_iterator.is_begin()))
                 {
                     return m_object;
                 }
                 JSON_THROW(invalid_iterator::create(214, "cannot get value"));
             }
         }
     }
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, assert(), nlohmann::detail::invalid_iterator::create(), nlohmann::detail::primitive_iterator_t::is_begin(), JSON_HEDLEY_LIKELY, JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
operator<() [1/2]
template<typename BasicJsonType > bool nlohmann::detail::iter_impl< BasicJsonType >::operator< (const iter_impl< BasicJsonType > & other) const inline
comparison: smaller
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 433 of file iter_impl.hpp.
     {
         // if objects are not the same, the comparison is undefined
         if (JSON_HEDLEY_UNLIKELY(m_object != other.m_object))
         {
             JSON_THROW(invalid_iterator::create(212, "cannot compare iterators of different containers"));
         }
         assert(m_object != nullptr);
         switch (m_object->m_type)
         {
             case value_t::object:
                 JSON_THROW(invalid_iterator::create(213, "cannot compare order of object iterators"));
             case value_t::array:
                 return (m_it.array_iterator < other.m_it.array_iterator);
             default:
                 return (m_it.primitive_iterator < other.m_it.primitive_iterator);
         }
     }
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, assert(), nlohmann::detail::invalid_iterator::create(), JSON_HEDLEY_UNLIKELY, JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
Referenced by nlohmann::detail::iter_impl< BasicJsonType >::operator>=().
operator<() [2/2]
template<typename BasicJsonType > bool nlohmann::detail::iter_impl< BasicJsonType >::operator< (const iter_impl< BasicJsonType > & other) const inline
comparison: smaller
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9739 of file json.hpp.
     {
         // if objects are not the same, the comparison is undefined
         if (JSON_HEDLEY_UNLIKELY(m_object != other.m_object))
         {
             JSON_THROW(invalid_iterator::create(212, "cannot compare iterators of different containers"));
         }
         assert(m_object != nullptr);
         switch (m_object->m_type)
         {
             case value_t::object:
                 JSON_THROW(invalid_iterator::create(213, "cannot compare order of object iterators"));
             case value_t::array:
                 return (m_it.array_iterator < other.m_it.array_iterator);
             default:
                 return (m_it.primitive_iterator < other.m_it.primitive_iterator);
         }
     }
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, assert(), nlohmann::detail::invalid_iterator::create(), JSON_HEDLEY_UNLIKELY, JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
operator<=() [1/2]
template<typename BasicJsonType > bool nlohmann::detail::iter_impl< BasicJsonType >::operator<= (const iter_impl< BasicJsonType > & other) const inline
comparison: less than or equal
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 460 of file iter_impl.hpp.
     {
         return not other.operator < (*this);
     }
Referenced by nlohmann::detail::iter_impl< BasicJsonType >::operator>().
operator<=() [2/2]
template<typename BasicJsonType > bool nlohmann::detail::iter_impl< BasicJsonType >::operator<= (const iter_impl< BasicJsonType > & other) const inline
comparison: less than or equal
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9766 of file json.hpp.
     {
         return not other.operator < (*this);
     }
operator=() [1/4]
template<typename BasicJsonType > iter_impl& nlohmann::detail::iter_impl< BasicJsonType >::operator= (const iter_impl< const BasicJsonType > & other) inline noexcept
converting assignment
Parameters
[in] other const iterator to copy from
Returns
const/non-const iterator
Note
It is not checked whether other is initialized.
Definition at line 138 of file iter_impl.hpp.
     {
         m_object = other.m_object;
         m_it = other.m_it;
         return *this;
     }
References nlohmann::detail::iter_impl< BasicJsonType >::m_it, and nlohmann::detail::iter_impl< BasicJsonType >::m_object.
operator=() [2/4]
template<typename BasicJsonType > iter_impl& nlohmann::detail::iter_impl< BasicJsonType >::operator= (const iter_impl< const BasicJsonType > & other) inline noexcept
converting assignment
Parameters
[in] other const iterator to copy from
Returns
const/non-const iterator
Note
It is not checked whether other is initialized.
Definition at line 9444 of file json.hpp.
     {
         m_object = other.m_object;
         m_it = other.m_it;
         return *this;
     }
References nlohmann::detail::iter_impl< BasicJsonType >::m_it, and nlohmann::detail::iter_impl< BasicJsonType >::m_object.
operator=() [3/4]
template<typename BasicJsonType > iter_impl& nlohmann::detail::iter_impl< BasicJsonType >::operator= (const iter_impl< typename std::remove_const< BasicJsonType >::type > & other) inline noexcept
converting assignment
Parameters
[in] other non-const iterator to copy from
Returns
const/non-const iterator
Note
It is not checked whether other is initialized.
Definition at line 160 of file iter_impl.hpp.
     {
         m_object = other.m_object;
         m_it = other.m_it;
         return *this;
     }
References nlohmann::detail::iter_impl< BasicJsonType >::m_it, and nlohmann::detail::iter_impl< BasicJsonType >::m_object.
operator=() [4/4]
template<typename BasicJsonType > iter_impl& nlohmann::detail::iter_impl< BasicJsonType >::operator= (const iter_impl< typename std::remove_const< BasicJsonType >::type > & other) inline noexcept
converting assignment
Parameters
[in] other non-const iterator to copy from
Returns
const/non-const iterator
Note
It is not checked whether other is initialized.
Definition at line 9466 of file json.hpp.
     {
         m_object = other.m_object;
         m_it = other.m_it;
         return *this;
     }
References nlohmann::detail::iter_impl< BasicJsonType >::m_it, and nlohmann::detail::iter_impl< BasicJsonType >::m_object.
operator==() [1/2]
template<typename BasicJsonType > bool nlohmann::detail::iter_impl< BasicJsonType >::operator== (const iter_impl< BasicJsonType > & other) const inline
comparison: equal
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 397 of file iter_impl.hpp.
     {
         // if objects are not the same, the comparison is undefined
         if (JSON_HEDLEY_UNLIKELY(m_object != other.m_object))
         {
             JSON_THROW(invalid_iterator::create(212, "cannot compare iterators of different containers"));
         }
         assert(m_object != nullptr);
         switch (m_object->m_type)
         {
             case value_t::object:
                 return (m_it.object_iterator == other.m_it.object_iterator);
             case value_t::array:
                 return (m_it.array_iterator == other.m_it.array_iterator);
             default:
                 return (m_it.primitive_iterator == other.m_it.primitive_iterator);
         }
     }
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, assert(), nlohmann::detail::invalid_iterator::create(), JSON_HEDLEY_UNLIKELY, JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
Referenced by nlohmann::detail::iter_impl< BasicJsonType >::operator!=().
operator==() [2/2]
template<typename BasicJsonType > bool nlohmann::detail::iter_impl< BasicJsonType >::operator== (const iter_impl< BasicJsonType > & other) const inline
comparison: equal
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9703 of file json.hpp.
     {
         // if objects are not the same, the comparison is undefined
         if (JSON_HEDLEY_UNLIKELY(m_object != other.m_object))
         {
             JSON_THROW(invalid_iterator::create(212, "cannot compare iterators of different containers"));
         }
         assert(m_object != nullptr);
         switch (m_object->m_type)
         {
             case value_t::object:
                 return (m_it.object_iterator == other.m_it.object_iterator);
             case value_t::array:
                 return (m_it.array_iterator == other.m_it.array_iterator);
             default:
                 return (m_it.primitive_iterator == other.m_it.primitive_iterator);
         }
     }
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, assert(), nlohmann::detail::invalid_iterator::create(), JSON_HEDLEY_UNLIKELY, JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
operator>() [1/2]
template<typename BasicJsonType > bool nlohmann::detail::iter_impl< BasicJsonType >::operator> (const iter_impl< BasicJsonType > & other) const inline
comparison: greater than
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 469 of file iter_impl.hpp.
     {
         return not operator<=(other);
     }
References nlohmann::detail::iter_impl< BasicJsonType >::operator<=().
operator>() [2/2]
template<typename BasicJsonType > bool nlohmann::detail::iter_impl< BasicJsonType >::operator> (const iter_impl< BasicJsonType > & other) const inline
comparison: greater than
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9775 of file json.hpp.
     {
         return not operator<=(other);
     }
References nlohmann::detail::iter_impl< BasicJsonType >::operator<=().
operator>=() [1/2]
template<typename BasicJsonType > bool nlohmann::detail::iter_impl< BasicJsonType >::operator>= (const iter_impl< BasicJsonType > & other) const inline
comparison: greater than or equal
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 478 of file iter_impl.hpp.
     {
         return not operator<(other);
     }
References nlohmann::detail::iter_impl< BasicJsonType >::operator<().
operator>=() [2/2]
template<typename BasicJsonType > bool nlohmann::detail::iter_impl< BasicJsonType >::operator>= (const iter_impl< BasicJsonType > & other) const inline
comparison: greater than or equal
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9784 of file json.hpp.
     {
         return not operator<(other);
     }
References nlohmann::detail::iter_impl< BasicJsonType >::operator<().
operator[]() [1/2]
template<typename BasicJsonType > reference nlohmann::detail::iter_impl< BasicJsonType >::operator[] (difference_type n) const inline
access to successor
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 579 of file iter_impl.hpp.
     {
         assert(m_object != nullptr);
         switch (m_object->m_type)
         {
             case value_t::object:
                 JSON_THROW(invalid_iterator::create(208, "cannot use operator[] for object iterators"));
             case value_t::array:
                 return *std::next(m_it.array_iterator, n);
             case value_t::null:
                 JSON_THROW(invalid_iterator::create(214, "cannot get value"));
             default:
             {
                 if (JSON_HEDLEY_LIKELY(m_it.primitive_iterator.get_value() == -n))
                 {
                     return *m_object;
                 }
                 JSON_THROW(invalid_iterator::create(214, "cannot get value"));
             }
         }
     }
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, assert(), nlohmann::detail::invalid_iterator::create(), nlohmann::detail::primitive_iterator_t::get_value(), JSON_HEDLEY_LIKELY, JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, n, nlohmann::detail::null, nlohmann::detail::object, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
operator[]() [2/2]
template<typename BasicJsonType > reference nlohmann::detail::iter_impl< BasicJsonType >::operator[] (difference_type n) const inline
access to successor
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9885 of file json.hpp.
     {
         assert(m_object != nullptr);
         switch (m_object->m_type)
         {
             case value_t::object:
                 JSON_THROW(invalid_iterator::create(208, "cannot use operator[] for object iterators"));
             case value_t::array:
                 return *std::next(m_it.array_iterator, n);
             case value_t::null:
                 JSON_THROW(invalid_iterator::create(214, "cannot get value"));
             default:
             {
                 if (JSON_HEDLEY_LIKELY(m_it.primitive_iterator.get_value() == -n))
                 {
                     return *m_object;
                 }
                 JSON_THROW(invalid_iterator::create(214, "cannot get value"));
             }
         }
     }
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, assert(), nlohmann::detail::invalid_iterator::create(), nlohmann::detail::primitive_iterator_t::get_value(), JSON_HEDLEY_LIKELY, JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, n, nlohmann::detail::null, nlohmann::detail::object, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
set_begin() [1/2]
template<typename BasicJsonType > void nlohmann::detail::iter_impl< BasicJsonType >::set_begin () inline private noexcept
set the iterator to the first value
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 172 of file iter_impl.hpp.
     {
         assert(m_object != nullptr);
         switch (m_object->m_type)
         {
             case value_t::object:
             {
                 m_it.object_iterator = m_object->m_value.object->begin();
                 break;
             }
             case value_t::array:
             {
                 m_it.array_iterator = m_object->m_value.array->begin();
                 break;
             }
             case value_t::null:
             {
                 // set to end so begin()==end() is true: null is empty
                 m_it.primitive_iterator.set_end();
                 break;
             }
             default:
             {
                 m_it.primitive_iterator.set_begin();
                 break;
             }
         }
     }
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, assert(), nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::null, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator, nlohmann::detail::primitive_iterator_t::set_begin(), and nlohmann::detail::primitive_iterator_t::set_end().
Referenced by TEST_CASE().
set_begin() [2/2]
template<typename BasicJsonType > void nlohmann::detail::iter_impl< BasicJsonType >::set_begin () inline private noexcept
set the iterator to the first value
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9478 of file json.hpp.
     {
         assert(m_object != nullptr);
         switch (m_object->m_type)
         {
             case value_t::object:
             {
                 m_it.object_iterator = m_object->m_value.object->begin();
                 break;
             }
             case value_t::array:
             {
                 m_it.array_iterator = m_object->m_value.array->begin();
                 break;
             }
             case value_t::null:
             {
                 // set to end so begin()==end() is true: null is empty
                 m_it.primitive_iterator.set_end();
                 break;
             }
             default:
             {
                 m_it.primitive_iterator.set_begin();
                 break;
             }
         }
     }
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, assert(), nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::null, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator, nlohmann::detail::primitive_iterator_t::set_begin(), and nlohmann::detail::primitive_iterator_t::set_end().
set_end() [1/2]
template<typename BasicJsonType > void nlohmann::detail::iter_impl< BasicJsonType >::set_end () inline private noexcept
set the iterator past the last value
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 209 of file iter_impl.hpp.
     {
         assert(m_object != nullptr);
         switch (m_object->m_type)
         {
             case value_t::object:
             {
                 m_it.object_iterator = m_object->m_value.object->end();
                 break;
             }
             case value_t::array:
             {
                 m_it.array_iterator = m_object->m_value.array->end();
                 break;
             }
             default:
             {
                 m_it.primitive_iterator.set_end();
                 break;
             }
         }
     }
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, assert(), nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator, and nlohmann::detail::primitive_iterator_t::set_end().
Referenced by TEST_CASE().
set_end() [2/2]
template<typename BasicJsonType > void nlohmann::detail::iter_impl< BasicJsonType >::set_end () inline private noexcept
set the iterator past the last value
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9515 of file json.hpp.
     {
         assert(m_object != nullptr);
         switch (m_object->m_type)
         {
             case value_t::object:
             {
                 m_it.object_iterator = m_object->m_value.object->end();
                 break;
             }
             case value_t::array:
             {
                 m_it.array_iterator = m_object->m_value.array->end();
                 break;
             }
             default:
             {
                 m_it.primitive_iterator.set_end();
                 break;
             }
         }
     }
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, assert(), nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator, and nlohmann::detail::primitive_iterator_t::set_end().
value() [1/2]
template<typename BasicJsonType > reference nlohmann::detail::iter_impl< BasicJsonType >::value () const inline
return the value of an iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 626 of file iter_impl.hpp.
     {
         return operator*();
     }
References nlohmann::detail::iter_impl< BasicJsonType >::operator*().
value() [2/2]
template<typename BasicJsonType > reference nlohmann::detail::iter_impl< BasicJsonType >::value () const inline
return the value of an iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9932 of file json.hpp.
     {
         return operator*();
     }
References nlohmann::detail::iter_impl< BasicJsonType >::operator*().
Friends And Related Function Documentation
operator+ [1/2]
template<typename BasicJsonType > iter_impl operator+ (difference_type i, const iter_impl< BasicJsonType > & it) friend
addition of distance and iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 536 of file iter_impl.hpp.
     {
         auto result = it;
         result += i;
         return result;
     }
operator+ [2/2]
template<typename BasicJsonType > iter_impl operator+ (difference_type i, const iter_impl< BasicJsonType > & it) friend
addition of distance and iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9842 of file json.hpp.
     {
         auto result = it;
         result += i;
         return result;
     }
Member Data Documentation
BasicJsonType
template<typename BasicJsonType > BasicJsonType private
Definition at line 44 of file iter_impl.hpp.
iteration_proxy< iter_impl >
template<typename BasicJsonType > iteration_proxy< iter_impl > private
Definition at line 45 of file iter_impl.hpp.
iteration_proxy_value< iter_impl >
template<typename BasicJsonType > iteration_proxy_value< iter_impl > private
Definition at line 46 of file iter_impl.hpp.
m_it
template<typename BasicJsonType > internal_iterator< typename std::remove_const< BasicJsonType >::type > nlohmann::detail::iter_impl< BasicJsonType >::m_it {} private
the actual iterator of the associated instance
Definition at line 635 of file iter_impl.hpp.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::insert(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::insert_iterator(), nlohmann::detail::iter_impl< BasicJsonType >::iter_impl(), nlohmann::detail::iter_impl< BasicJsonType >::key(), nlohmann::detail::iter_impl< BasicJsonType >::operator*(), nlohmann::detail::iter_impl< BasicJsonType >::operator++(), nlohmann::detail::iter_impl< BasicJsonType >::operator+=(), nlohmann::detail::iter_impl< BasicJsonType >::operator-(), nlohmann::detail::iter_impl< BasicJsonType >::operator--(), nlohmann::detail::iter_impl< BasicJsonType >::operator->(), nlohmann::detail::iter_impl< BasicJsonType >::operator<(), nlohmann::detail::iter_impl< BasicJsonType >::operator=(), nlohmann::detail::iter_impl< BasicJsonType >::operator==(), nlohmann::detail::iter_impl< BasicJsonType >::operator[](), nlohmann::detail::iter_impl< BasicJsonType >::set_begin(), nlohmann::detail::iter_impl< BasicJsonType >::set_end(), and TEST_CASE().
m_object
template<typename BasicJsonType > pointer nlohmann::detail::iter_impl< BasicJsonType >::m_object = nullptr private
associated JSON instance
Definition at line 633 of file iter_impl.hpp.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::insert(), nlohmann::detail::iter_impl< BasicJsonType >::iter_impl(), nlohmann::detail::iter_impl< BasicJsonType >::key(), nlohmann::detail::iter_impl< BasicJsonType >::operator*(), nlohmann::detail::iter_impl< BasicJsonType >::operator++(), nlohmann::detail::iter_impl< BasicJsonType >::operator+=(), nlohmann::detail::iter_impl< BasicJsonType >::operator-(), nlohmann::detail::iter_impl< BasicJsonType >::operator--(), nlohmann::detail::iter_impl< BasicJsonType >::operator->(), nlohmann::detail::iter_impl< BasicJsonType >::operator<(), nlohmann::detail::iter_impl< BasicJsonType >::operator=(), nlohmann::detail::iter_impl< BasicJsonType >::operator==(), nlohmann::detail::iter_impl< BasicJsonType >::operator[](), nlohmann::detail::iter_impl< BasicJsonType >::set_begin(), nlohmann::detail::iter_impl< BasicJsonType >::set_end(), TEST_CASE(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::update().
The documentation for this class was generated from the following files:
mc_orchestrator/json-3.7.3/include/nlohmann/detail/iterators/iter_impl.hpp
mc_orchestrator/json-3.7.3/single_include/nlohmann/json.hpp