Mixed Criticality Orchestrator: nlohmann::detail::binary_reader< BasicJsonType, SAX > Class Template Reference
nlohmann::detail::binary_reader< BasicJsonType, SAX > Class Template Reference
deserialization of CBOR, MessagePack, and UBJSON values
#include <binary_reader.hpp>
Public Member Functions
binary_reader (input_adapter_t adapter)
create a binary reader
binary_reader (const binary_reader &)=delete
binary_reader (binary_reader &&)=default
binary_reader & operator= (const binary_reader &)=delete
binary_reader & operator= (binary_reader &&)=default
~binary_reader ()=default
bool sax_parse (const input_format_t format, json_sax_t *sax_, const bool strict=true)
binary_reader (input_adapter_t adapter)
create a binary reader
binary_reader (const binary_reader &)=delete
binary_reader (binary_reader &&)=default
binary_reader & operator= (const binary_reader &)=delete
binary_reader & operator= (binary_reader &&)=default
~binary_reader ()=default
bool sax_parse (const input_format_t format, json_sax_t *sax_, const bool strict=true)
Static Public Member Functions
static constexpr bool little_endianess (int num=1) noexcept
determine system byte order
static constexpr bool little_endianess (int num=1) noexcept
determine system byte order
Private Types
using number_integer_t = typename BasicJsonType::number_integer_t
using number_unsigned_t = typename BasicJsonType::number_unsigned_t
using number_float_t = typename BasicJsonType::number_float_t
using string_t = typename BasicJsonType::string_t
using json_sax_t = SAX
using number_integer_t = typename BasicJsonType::number_integer_t
using number_unsigned_t = typename BasicJsonType::number_unsigned_t
using number_float_t = typename BasicJsonType::number_float_t
using string_t = typename BasicJsonType::string_t
using json_sax_t = SAX
Private Member Functions
bool parse_bson_internal ()
Reads in a BSON-object and passes it to the SAX-parser.
bool get_bson_cstr (string_t &result)
Parses a C-style string from the BSON input.
template<typename NumberType >
bool get_bson_string (const NumberType len, string_t &result)
Parses a zero-terminated string of length len from the BSON input.
bool parse_bson_element_internal (const int element_type, const std::size_t element_type_parse_position)
Read a BSON document element of the given element_type.
bool parse_bson_element_list (const bool is_array)
Read a BSON element list (as specified in the BSON-spec)
bool parse_bson_array ()
Reads an array from the BSON input and passes it to the SAX-parser.
bool parse_cbor_internal (const bool get_char=true)
bool get_cbor_string (string_t &result)
reads a CBOR string
bool get_cbor_array (const std::size_t len)
bool get_cbor_object (const std::size_t len)
bool parse_msgpack_internal ()
bool get_msgpack_string (string_t &result)
reads a MessagePack string
bool get_msgpack_array (const std::size_t len)
bool get_msgpack_object (const std::size_t len)
bool parse_ubjson_internal (const bool get_char=true)
bool get_ubjson_string (string_t &result, const bool get_char=true)
reads a UBJSON string
bool get_ubjson_size_value (std::size_t &result)
bool get_ubjson_size_type (std::pair< std::size_t, int > &result)
determine the type and size for a container
bool get_ubjson_value (const int prefix)
bool get_ubjson_array ()
bool get_ubjson_object ()
int get ()
get next character from the input
int get_ignore_noop ()
template<typename NumberType , bool InputIsLittleEndian = false>
bool get_number (const input_format_t format, NumberType &result)
template<typename NumberType >
bool get_string (const input_format_t format, const NumberType len, string_t &result)
create a string by reading characters from the input
bool unexpect_eof (const input_format_t format, const char *context) const
std::string get_token_string () const
std::string exception_message (const input_format_t format, const std::string &detail, const std::string &context) const
bool parse_bson_internal ()
Reads in a BSON-object and passes it to the SAX-parser.
bool get_bson_cstr (string_t &result)
Parses a C-style string from the BSON input.
template<typename NumberType >
bool get_bson_string (const NumberType len, string_t &result)
Parses a zero-terminated string of length len from the BSON input.
bool parse_bson_element_internal (const int element_type, const std::size_t element_type_parse_position)
Read a BSON document element of the given element_type.
bool parse_bson_element_list (const bool is_array)
Read a BSON element list (as specified in the BSON-spec)
bool parse_bson_array ()
Reads an array from the BSON input and passes it to the SAX-parser.
bool parse_cbor_internal (const bool get_char=true)
bool get_cbor_string (string_t &result)
reads a CBOR string
bool get_cbor_array (const std::size_t len)
bool get_cbor_object (const std::size_t len)
bool parse_msgpack_internal ()
bool get_msgpack_string (string_t &result)
reads a MessagePack string
bool get_msgpack_array (const std::size_t len)
bool get_msgpack_object (const std::size_t len)
bool parse_ubjson_internal (const bool get_char=true)
bool get_ubjson_string (string_t &result, const bool get_char=true)
reads a UBJSON string
bool get_ubjson_size_value (std::size_t &result)
bool get_ubjson_size_type (std::pair< std::size_t, int > &result)
determine the type and size for a container
bool get_ubjson_value (const int prefix)
bool get_ubjson_array ()
bool get_ubjson_object ()
int get ()
get next character from the input
int get_ignore_noop ()
template<typename NumberType , bool InputIsLittleEndian = false>
bool get_number (const input_format_t format, NumberType &result)
template<typename NumberType >
bool get_string (const input_format_t format, const NumberType len, string_t &result)
create a string by reading characters from the input
bool unexpect_eof (const input_format_t format, const char *context) const
std::string get_token_string () const
std::string exception_message (const input_format_t format, const std::string &detail, const std::string &context) const
Private Attributes
input_adapter_t ia = nullptr
input adapter
int current = std::char_traits<char>::eof()
the current character
std::size_t chars_read = 0
the number of characters read
const bool is_little_endian = little_endianess()
whether we can assume little endianess
json_sax_t * sax = nullptr
the SAX parser
Detailed Description
template<typename BasicJsonType, typename SAX = json_sax_dom_parser<BasicJsonType>>
class nlohmann::detail::binary_reader< BasicJsonType, SAX >
deserialization of CBOR, MessagePack, and UBJSON values
Definition at line 35 of file binary_reader.hpp.
Member Typedef Documentation
json_sax_t [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> using nlohmann::detail::binary_reader< BasicJsonType, SAX >::json_sax_t = SAX private
Definition at line 41 of file binary_reader.hpp.
json_sax_t [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> using nlohmann::detail::binary_reader< BasicJsonType, SAX >::json_sax_t = SAX private
Definition at line 5181 of file json.hpp.
number_float_t [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> using nlohmann::detail::binary_reader< BasicJsonType, SAX >::number_float_t = typename BasicJsonType::number_float_t private
Definition at line 39 of file binary_reader.hpp.
number_float_t [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> using nlohmann::detail::binary_reader< BasicJsonType, SAX >::number_float_t = typename BasicJsonType::number_float_t private
Definition at line 5179 of file json.hpp.
number_integer_t [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> using nlohmann::detail::binary_reader< BasicJsonType, SAX >::number_integer_t = typename BasicJsonType::number_integer_t private
Definition at line 37 of file binary_reader.hpp.
number_integer_t [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> using nlohmann::detail::binary_reader< BasicJsonType, SAX >::number_integer_t = typename BasicJsonType::number_integer_t private
Definition at line 5177 of file json.hpp.
number_unsigned_t [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> using nlohmann::detail::binary_reader< BasicJsonType, SAX >::number_unsigned_t = typename BasicJsonType::number_unsigned_t private
Definition at line 38 of file binary_reader.hpp.
number_unsigned_t [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> using nlohmann::detail::binary_reader< BasicJsonType, SAX >::number_unsigned_t = typename BasicJsonType::number_unsigned_t private
Definition at line 5178 of file json.hpp.
string_t [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> using nlohmann::detail::binary_reader< BasicJsonType, SAX >::string_t = typename BasicJsonType::string_t private
Definition at line 40 of file binary_reader.hpp.
string_t [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> using nlohmann::detail::binary_reader< BasicJsonType, SAX >::string_t = typename BasicJsonType::string_t private
Definition at line 5180 of file json.hpp.
Constructor & Destructor Documentation
binary_reader() [1/6]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> nlohmann::detail::binary_reader< BasicJsonType, SAX >::binary_reader (input_adapter_t adapter) inline explicit
create a binary reader
Parameters
[in] adapter input adapter to read from
Definition at line 49 of file binary_reader.hpp.
                                                     : ia(std::move(adapter))
     {
         (void)detail::is_sax_static_asserts<SAX, BasicJsonType> {};
         assert(ia);
     }
References assert(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::ia, and nlohmann::detail::void().
binary_reader() [2/6]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> nlohmann::detail::binary_reader< BasicJsonType, SAX >::binary_reader (const binary_reader< BasicJsonType, SAX > &) delete
binary_reader() [3/6]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> nlohmann::detail::binary_reader< BasicJsonType, SAX >::binary_reader (binary_reader< BasicJsonType, SAX > &&) default
~binary_reader() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> nlohmann::detail::binary_reader< BasicJsonType, SAX >::~binary_reader () default
binary_reader() [4/6]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> nlohmann::detail::binary_reader< BasicJsonType, SAX >::binary_reader (input_adapter_t adapter) inline explicit
create a binary reader
Parameters
[in] adapter input adapter to read from
Definition at line 5189 of file json.hpp.
                                                     : ia(std::move(adapter))
     {
         (void)detail::is_sax_static_asserts<SAX, BasicJsonType> {};
         assert(ia);
     }
References assert(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::ia, and nlohmann::detail::void().
binary_reader() [5/6]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> nlohmann::detail::binary_reader< BasicJsonType, SAX >::binary_reader (const binary_reader< BasicJsonType, SAX > &) delete
binary_reader() [6/6]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> nlohmann::detail::binary_reader< BasicJsonType, SAX >::binary_reader (binary_reader< BasicJsonType, SAX > &&) default
~binary_reader() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> nlohmann::detail::binary_reader< BasicJsonType, SAX >::~binary_reader () default
Member Function Documentation
exception_message() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> std::string nlohmann::detail::binary_reader< BasicJsonType, SAX >::exception_message (const input_format_t format, const std::string & detail, const std::string & context) const inline private
Parameters
[in] format the current format
[in] detail a detailed error message
[in] context further context information
Returns
a message string to use in the parse_error exceptions
Definition at line 1935 of file binary_reader.hpp.
     {
         std::string error_msg = "syntax error while parsing ";
         switch (format)
         {
             case input_format_t::cbor:
                 error_msg += "CBOR";
                 break;
             case input_format_t::msgpack:
                 error_msg += "MessagePack";
                 break;
             case input_format_t::ubjson:
                 error_msg += "UBJSON";
                 break;
             case input_format_t::bson:
                 error_msg += "BSON";
                 break;
             default:            // LCOV_EXCL_LINE
                 assert(false);  // LCOV_EXCL_LINE
         }
         return error_msg + " " + context + ": " + detail;
     }
References assert(), nlohmann::detail::bson, nlohmann::detail::cbor, nlohmann::detail::msgpack, and nlohmann::detail::ubjson.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_bson_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_size_type(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_size_value(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_value(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_cbor_internal(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_msgpack_internal(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax_parse(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof().
exception_message() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> std::string nlohmann::detail::binary_reader< BasicJsonType, SAX >::exception_message (const input_format_t format, const std::string & detail, const std::string & context) const inline private
Parameters
[in] format the current format
[in] detail a detailed error message
[in] context further context information
Returns
a message string to use in the parse_error exceptions
Definition at line 7075 of file json.hpp.
     {
         std::string error_msg = "syntax error while parsing ";
         switch (format)
         {
             case input_format_t::cbor:
                 error_msg += "CBOR";
                 break;
             case input_format_t::msgpack:
                 error_msg += "MessagePack";
                 break;
             case input_format_t::ubjson:
                 error_msg += "UBJSON";
                 break;
             case input_format_t::bson:
                 error_msg += "BSON";
                 break;
             default:            // LCOV_EXCL_LINE
                 assert(false);  // LCOV_EXCL_LINE
         }
         return error_msg + " " + context + ": " + detail;
     }
References assert(), nlohmann::detail::bson, nlohmann::detail::cbor, nlohmann::detail::msgpack, and nlohmann::detail::ubjson.
get() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> int nlohmann::detail::binary_reader< BasicJsonType, SAX >::get () inline private
get next character from the input
This function provides the interface to the used input adapter. It does not throw in case the input reached EOF, but returns a -'ve valued std::char_traits<char>::eof() in that case.
Returns
character read from the input
Definition at line 1809 of file binary_reader.hpp.
     {
         ++chars_read;
         return current = ia->get_character();
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read, nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::ia.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_bson_cstr(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_bson_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_array(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_object(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ignore_noop(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_object(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_size_type(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_value(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_element_internal(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_element_list(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_cbor_internal(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_msgpack_internal(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax_parse().
get() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> int nlohmann::detail::binary_reader< BasicJsonType, SAX >::get () inline private
get next character from the input
This function provides the interface to the used input adapter. It does not throw in case the input reached EOF, but returns a -'ve valued std::char_traits<char>::eof() in that case.
Returns
character read from the input
Definition at line 6949 of file json.hpp.
     {
         ++chars_read;
         return current = ia->get_character();
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read, nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::ia.
get_bson_cstr() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_bson_cstr (string_t & result) inline private
Parses a C-style string from the BSON input.
Parameters
[in,out] result A reference to the string variable where the read string is to be stored.
Returns
true if the \x00-byte indicating the end of the string was encountered before the EOF; false` indicates an unexpected EOF.
Definition at line 167 of file binary_reader.hpp.
     {
         auto out = std::back_inserter(result);
         while (true)
         {
             get();
             if (JSON_HEDLEY_UNLIKELY(not unexpect_eof(input_format_t::bson, "cstring")))
             {
                 return false;
             }
             if (current == 0x00)
             {
                 return true;
             }
             *out++ = static_cast<char>(current);
         }
         return true;
     }
References nlohmann::detail::bson, nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), JSON_HEDLEY_UNLIKELY, result, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_element_list().
get_bson_cstr() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_bson_cstr (string_t & result) inline private
Parses a C-style string from the BSON input.
Parameters
[in,out] result A reference to the string variable where the read string is to be stored.
Returns
true if the \x00-byte indicating the end of the string was encountered before the EOF; false` indicates an unexpected EOF.
Definition at line 5307 of file json.hpp.
     {
         auto out = std::back_inserter(result);
         while (true)
         {
             get();
             if (JSON_HEDLEY_UNLIKELY(not unexpect_eof(input_format_t::bson, "cstring")))
             {
                 return false;
             }
             if (current == 0x00)
             {
                 return true;
             }
             *out++ = static_cast<char>(current);
         }
         return true;
     }
References nlohmann::detail::bson, nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), JSON_HEDLEY_UNLIKELY, result, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof().
get_bson_string() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> template<typename NumberType > bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_bson_string (const NumberType len, string_t & result) inline private
Parses a zero-terminated string of length len from the BSON input.
Parameters
[in] len The length (including the zero-byte at the end) of the string to be read.
[in,out] result A reference to the string variable where the read string is to be stored.
Template Parameters
NumberType The type of the length len
Precondition
len >= 1
Returns
true if the string was successfully parsed
Definition at line 199 of file binary_reader.hpp.
     {
         if (JSON_HEDLEY_UNLIKELY(len < 1))
         {
             auto last_token = get_token_string();
             return sax->parse_error(chars_read, last_token, parse_error::create(112, chars_read, exception_message(input_format_t::bson, "string length must be at least 1, is " + std::to_string(len), "string")));
         }
         return get_string(input_format_t::bson, len - static_cast<NumberType>(1), result) and get() != std::char_traits<char>::eof();
     }
References nlohmann::detail::bson, nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_token_string(), JSON_HEDLEY_UNLIKELY, result, nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax, and httplib::to_string().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_element_internal().
get_bson_string() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> template<typename NumberType > bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_bson_string (const NumberType len, string_t & result) inline private
Parses a zero-terminated string of length len from the BSON input.
Parameters
[in] len The length (including the zero-byte at the end) of the string to be read.
[in,out] result A reference to the string variable where the read string is to be stored.
Template Parameters
NumberType The type of the length len
Precondition
len >= 1
Returns
true if the string was successfully parsed
Definition at line 5339 of file json.hpp.
     {
         if (JSON_HEDLEY_UNLIKELY(len < 1))
         {
             auto last_token = get_token_string();
             return sax->parse_error(chars_read, last_token, parse_error::create(112, chars_read, exception_message(input_format_t::bson, "string length must be at least 1, is " + std::to_string(len), "string")));
         }
         return get_string(input_format_t::bson, len - static_cast<NumberType>(1), result) and get() != std::char_traits<char>::eof();
     }
References nlohmann::detail::bson, nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_token_string(), JSON_HEDLEY_UNLIKELY, result, nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax, and nlohmann::to_string().
get_cbor_array() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_array (const std::size_t len) inline private
Parameters
[in] len the length of the array or std::size_t(-1) for an array of indefinite size
Returns
whether array creation completed
Definition at line 788 of file binary_reader.hpp.
     {
         if (JSON_HEDLEY_UNLIKELY(not sax->start_array(len)))
         {
             return false;
         }
         if (len != std::size_t(-1))
         {
             for (std::size_t i = 0; i < len; ++i)
             {
                 if (JSON_HEDLEY_UNLIKELY(not parse_cbor_internal()))
                 {
                     return false;
                 }
             }
         }
         else
         {
             while (get() != 0xFF)
             {
                 if (JSON_HEDLEY_UNLIKELY(not parse_cbor_internal(false)))
                 {
                     return false;
                 }
             }
         }
         return sax->end_array();
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_cbor_internal(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_cbor_internal().
get_cbor_array() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_array (const std::size_t len) inline private
Parameters
[in] len the length of the array or std::size_t(-1) for an array of indefinite size
Returns
whether array creation completed
Definition at line 5928 of file json.hpp.
     {
         if (JSON_HEDLEY_UNLIKELY(not sax->start_array(len)))
         {
             return false;
         }
         if (len != std::size_t(-1))
         {
             for (std::size_t i = 0; i < len; ++i)
             {
                 if (JSON_HEDLEY_UNLIKELY(not parse_cbor_internal()))
                 {
                     return false;
                 }
             }
         }
         else
         {
             while (get() != 0xFF)
             {
                 if (JSON_HEDLEY_UNLIKELY(not parse_cbor_internal(false)))
                 {
                     return false;
                 }
             }
         }
         return sax->end_array();
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_cbor_internal(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax.
get_cbor_object() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_object (const std::size_t len) inline private
Parameters
[in] len the length of the object or std::size_t(-1) for an object of indefinite size
Returns
whether object creation completed
Definition at line 824 of file binary_reader.hpp.
     {
         if (JSON_HEDLEY_UNLIKELY(not sax->start_object(len)))
         {
             return false;
         }
         string_t key;
         if (len != std::size_t(-1))
         {
             for (std::size_t i = 0; i < len; ++i)
             {
                 get();
                 if (JSON_HEDLEY_UNLIKELY(not get_cbor_string(key) or not sax->key(key)))
                 {
                     return false;
                 }
                 if (JSON_HEDLEY_UNLIKELY(not parse_cbor_internal()))
                 {
                     return false;
                 }
                 key.clear();
             }
         }
         else
         {
             while (get() != 0xFF)
             {
                 if (JSON_HEDLEY_UNLIKELY(not get_cbor_string(key) or not sax->key(key)))
                 {
                     return false;
                 }
                 if (JSON_HEDLEY_UNLIKELY(not parse_cbor_internal()))
                 {
                     return false;
                 }
                 key.clear();
             }
         }
         return sax->end_object();
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_string(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_cbor_internal(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_cbor_internal().
get_cbor_object() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_object (const std::size_t len) inline private
Parameters
[in] len the length of the object or std::size_t(-1) for an object of indefinite size
Returns
whether object creation completed
Definition at line 5964 of file json.hpp.
     {
         if (JSON_HEDLEY_UNLIKELY(not sax->start_object(len)))
         {
             return false;
         }
         string_t key;
         if (len != std::size_t(-1))
         {
             for (std::size_t i = 0; i < len; ++i)
             {
                 get();
                 if (JSON_HEDLEY_UNLIKELY(not get_cbor_string(key) or not sax->key(key)))
                 {
                     return false;
                 }
                 if (JSON_HEDLEY_UNLIKELY(not parse_cbor_internal()))
                 {
                     return false;
                 }
                 key.clear();
             }
         }
         else
         {
             while (get() != 0xFF)
             {
                 if (JSON_HEDLEY_UNLIKELY(not get_cbor_string(key) or not sax->key(key)))
                 {
                     return false;
                 }
                 if (JSON_HEDLEY_UNLIKELY(not parse_cbor_internal()))
                 {
                     return false;
                 }
                 key.clear();
             }
         }
         return sax->end_object();
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_string(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_cbor_internal(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax.
get_cbor_string() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_string (string_t & result) inline private
reads a CBOR string
This function first reads starting bytes to determine the expected string length and then copies this number of bytes into a string. Additionally, CBOR's strings with indefinite lengths are supported.
Parameters
[out] result created string
Returns
whether string creation completed
Definition at line 699 of file binary_reader.hpp.
     {
         if (JSON_HEDLEY_UNLIKELY(not unexpect_eof(input_format_t::cbor, "string")))
         {
             return false;
         }
         switch (current)
         {
             // UTF-8 string (0x00..0x17 bytes follow)
             case 0x60:
             case 0x61:
             case 0x62:
             case 0x63:
             case 0x64:
             case 0x65:
             case 0x66:
             case 0x67:
             case 0x68:
             case 0x69:
             case 0x6A:
             case 0x6B:
             case 0x6C:
             case 0x6D:
             case 0x6E:
             case 0x6F:
             case 0x70:
             case 0x71:
             case 0x72:
             case 0x73:
             case 0x74:
             case 0x75:
             case 0x76:
             case 0x77:
             {
                 return get_string(input_format_t::cbor, static_cast<unsigned int>(current) & 0x1Fu, result);
             }
             case 0x78: // UTF-8 string (one-byte uint8_t for n follows)
             {
                 std::uint8_t len;
                 return get_number(input_format_t::cbor, len) and get_string(input_format_t::cbor, len, result);
             }
             case 0x79: // UTF-8 string (two-byte uint16_t for n follow)
             {
                 std::uint16_t len;
                 return get_number(input_format_t::cbor, len) and get_string(input_format_t::cbor, len, result);
             }
             case 0x7A: // UTF-8 string (four-byte uint32_t for n follow)
             {
                 std::uint32_t len;
                 return get_number(input_format_t::cbor, len) and get_string(input_format_t::cbor, len, result);
             }
             case 0x7B: // UTF-8 string (eight-byte uint64_t for n follow)
             {
                 std::uint64_t len;
                 return get_number(input_format_t::cbor, len) and get_string(input_format_t::cbor, len, result);
             }
             case 0x7F: // UTF-8 string (indefinite length)
             {
                 while (get() != 0xFF)
                 {
                     string_t chunk;
                     if (not get_cbor_string(chunk))
                     {
                         return false;
                     }
                     result.append(chunk);
                 }
                 return true;
             }
             default:
             {
                 auto last_token = get_token_string();
                 return sax->parse_error(chars_read, last_token, parse_error::create(113, chars_read, exception_message(input_format_t::cbor, "expected length specification (0x60-0x7B) or indefinite string type (0x7F); last byte: 0x" + last_token, "string")));
             }
         }
     }
References nlohmann::detail::cbor, nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_token_string(), JSON_HEDLEY_UNLIKELY, result, nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_object(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_string(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_cbor_internal().
get_cbor_string() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_string (string_t & result) inline private
reads a CBOR string
This function first reads starting bytes to determine the expected string length and then copies this number of bytes into a string. Additionally, CBOR's strings with indefinite lengths are supported.
Parameters
[out] result created string
Returns
whether string creation completed
Definition at line 5839 of file json.hpp.
     {
         if (JSON_HEDLEY_UNLIKELY(not unexpect_eof(input_format_t::cbor, "string")))
         {
             return false;
         }
         switch (current)
         {
             // UTF-8 string (0x00..0x17 bytes follow)
             case 0x60:
             case 0x61:
             case 0x62:
             case 0x63:
             case 0x64:
             case 0x65:
             case 0x66:
             case 0x67:
             case 0x68:
             case 0x69:
             case 0x6A:
             case 0x6B:
             case 0x6C:
             case 0x6D:
             case 0x6E:
             case 0x6F:
             case 0x70:
             case 0x71:
             case 0x72:
             case 0x73:
             case 0x74:
             case 0x75:
             case 0x76:
             case 0x77:
             {
                 return get_string(input_format_t::cbor, static_cast<unsigned int>(current) & 0x1Fu, result);
             }
             case 0x78: // UTF-8 string (one-byte uint8_t for n follows)
             {
                 std::uint8_t len;
                 return get_number(input_format_t::cbor, len) and get_string(input_format_t::cbor, len, result);
             }
             case 0x79: // UTF-8 string (two-byte uint16_t for n follow)
             {
                 std::uint16_t len;
                 return get_number(input_format_t::cbor, len) and get_string(input_format_t::cbor, len, result);
             }
             case 0x7A: // UTF-8 string (four-byte uint32_t for n follow)
             {
                 std::uint32_t len;
                 return get_number(input_format_t::cbor, len) and get_string(input_format_t::cbor, len, result);
             }
             case 0x7B: // UTF-8 string (eight-byte uint64_t for n follow)
             {
                 std::uint64_t len;
                 return get_number(input_format_t::cbor, len) and get_string(input_format_t::cbor, len, result);
             }
             case 0x7F: // UTF-8 string (indefinite length)
             {
                 while (get() != 0xFF)
                 {
                     string_t chunk;
                     if (not get_cbor_string(chunk))
                     {
                         return false;
                     }
                     result.append(chunk);
                 }
                 return true;
             }
             default:
             {
                 auto last_token = get_token_string();
                 return sax->parse_error(chars_read, last_token, parse_error::create(113, chars_read, exception_message(input_format_t::cbor, "expected length specification (0x60-0x7B) or indefinite string type (0x7F); last byte: 0x" + last_token, "string")));
             }
         }
     }
References nlohmann::detail::cbor, nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_token_string(), JSON_HEDLEY_UNLIKELY, result, nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof().
get_ignore_noop() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> int nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ignore_noop () inline private
Returns
character read from the input after ignoring all 'N' entries
Definition at line 1818 of file binary_reader.hpp.
     {
         do
         {
             get();
         }
         while (current == 'N');
         return current;
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::get().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_array(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_object(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_size_type(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_size_value(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_ubjson_internal(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax_parse().
get_ignore_noop() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> int nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ignore_noop () inline private
Returns
character read from the input after ignoring all 'N' entries
Definition at line 6958 of file json.hpp.
     {
         do
         {
             get();
         }
         while (current == 'N');
         return current;
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::get().
get_msgpack_array() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_array (const std::size_t len) inline private
Parameters
[in] len the length of the array
Returns
whether array creation completed
Definition at line 1316 of file binary_reader.hpp.
     {
         if (JSON_HEDLEY_UNLIKELY(not sax->start_array(len)))
         {
             return false;
         }
         for (std::size_t i = 0; i < len; ++i)
         {
             if (JSON_HEDLEY_UNLIKELY(not parse_msgpack_internal()))
             {
                 return false;
             }
         }
         return sax->end_array();
     }
References JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_msgpack_internal(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_msgpack_internal().
get_msgpack_array() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_array (const std::size_t len) inline private
Parameters
[in] len the length of the array
Returns
whether array creation completed
Definition at line 6456 of file json.hpp.
     {
         if (JSON_HEDLEY_UNLIKELY(not sax->start_array(len)))
         {
             return false;
         }
         for (std::size_t i = 0; i < len; ++i)
         {
             if (JSON_HEDLEY_UNLIKELY(not parse_msgpack_internal()))
             {
                 return false;
             }
         }
         return sax->end_array();
     }
References JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_msgpack_internal(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax.
get_msgpack_object() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_object (const std::size_t len) inline private
Parameters
[in] len the length of the object
Returns
whether object creation completed
Definition at line 1338 of file binary_reader.hpp.
     {
         if (JSON_HEDLEY_UNLIKELY(not sax->start_object(len)))
         {
             return false;
         }
         string_t key;
         for (std::size_t i = 0; i < len; ++i)
         {
             get();
             if (JSON_HEDLEY_UNLIKELY(not get_msgpack_string(key) or not sax->key(key)))
             {
                 return false;
             }
             if (JSON_HEDLEY_UNLIKELY(not parse_msgpack_internal()))
             {
                 return false;
             }
             key.clear();
         }
         return sax->end_object();
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_string(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_msgpack_internal(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_msgpack_internal().
get_msgpack_object() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_object (const std::size_t len) inline private
Parameters
[in] len the length of the object
Returns
whether object creation completed
Definition at line 6478 of file json.hpp.
     {
         if (JSON_HEDLEY_UNLIKELY(not sax->start_object(len)))
         {
             return false;
         }
         string_t key;
         for (std::size_t i = 0; i < len; ++i)
         {
             get();
             if (JSON_HEDLEY_UNLIKELY(not get_msgpack_string(key) or not sax->key(key)))
             {
                 return false;
             }
             if (JSON_HEDLEY_UNLIKELY(not parse_msgpack_internal()))
             {
                 return false;
             }
             key.clear();
         }
         return sax->end_object();
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_string(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_msgpack_internal(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax.
get_msgpack_string() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_string (string_t & result) inline private
reads a MessagePack string
This function first reads starting bytes to determine the expected string length and then copies this number of bytes into a string.
Parameters
[out] result created string
Returns
whether string creation completed
Definition at line 1240 of file binary_reader.hpp.
     {
         if (JSON_HEDLEY_UNLIKELY(not unexpect_eof(input_format_t::msgpack, "string")))
         {
             return false;
         }
         switch (current)
         {
             // fixstr
             case 0xA0:
             case 0xA1:
             case 0xA2:
             case 0xA3:
             case 0xA4:
             case 0xA5:
             case 0xA6:
             case 0xA7:
             case 0xA8:
             case 0xA9:
             case 0xAA:
             case 0xAB:
             case 0xAC:
             case 0xAD:
             case 0xAE:
             case 0xAF:
             case 0xB0:
             case 0xB1:
             case 0xB2:
             case 0xB3:
             case 0xB4:
             case 0xB5:
             case 0xB6:
             case 0xB7:
             case 0xB8:
             case 0xB9:
             case 0xBA:
             case 0xBB:
             case 0xBC:
             case 0xBD:
             case 0xBE:
             case 0xBF:
             {
                 return get_string(input_format_t::msgpack, static_cast<unsigned int>(current) & 0x1Fu, result);
             }
             case 0xD9: // str 8
             {
                 std::uint8_t len;
                 return get_number(input_format_t::msgpack, len) and get_string(input_format_t::msgpack, len, result);
             }
             case 0xDA: // str 16
             {
                 std::uint16_t len;
                 return get_number(input_format_t::msgpack, len) and get_string(input_format_t::msgpack, len, result);
             }
             case 0xDB: // str 32
             {
                 std::uint32_t len;
                 return get_number(input_format_t::msgpack, len) and get_string(input_format_t::msgpack, len, result);
             }
             default:
             {
                 auto last_token = get_token_string();
                 return sax->parse_error(chars_read, last_token, parse_error::create(113, chars_read, exception_message(input_format_t::msgpack, "expected length specification (0xA0-0xBF, 0xD9-0xDB); last byte: 0x" + last_token, "string")));
             }
         }
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_token_string(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::msgpack, result, nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_object(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_msgpack_internal().
get_msgpack_string() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_string (string_t & result) inline private
reads a MessagePack string
This function first reads starting bytes to determine the expected string length and then copies this number of bytes into a string.
Parameters
[out] result created string
Returns
whether string creation completed
Definition at line 6380 of file json.hpp.
     {
         if (JSON_HEDLEY_UNLIKELY(not unexpect_eof(input_format_t::msgpack, "string")))
         {
             return false;
         }
         switch (current)
         {
             // fixstr
             case 0xA0:
             case 0xA1:
             case 0xA2:
             case 0xA3:
             case 0xA4:
             case 0xA5:
             case 0xA6:
             case 0xA7:
             case 0xA8:
             case 0xA9:
             case 0xAA:
             case 0xAB:
             case 0xAC:
             case 0xAD:
             case 0xAE:
             case 0xAF:
             case 0xB0:
             case 0xB1:
             case 0xB2:
             case 0xB3:
             case 0xB4:
             case 0xB5:
             case 0xB6:
             case 0xB7:
             case 0xB8:
             case 0xB9:
             case 0xBA:
             case 0xBB:
             case 0xBC:
             case 0xBD:
             case 0xBE:
             case 0xBF:
             {
                 return get_string(input_format_t::msgpack, static_cast<unsigned int>(current) & 0x1Fu, result);
             }
             case 0xD9: // str 8
             {
                 std::uint8_t len;
                 return get_number(input_format_t::msgpack, len) and get_string(input_format_t::msgpack, len, result);
             }
             case 0xDA: // str 16
             {
                 std::uint16_t len;
                 return get_number(input_format_t::msgpack, len) and get_string(input_format_t::msgpack, len, result);
             }
             case 0xDB: // str 32
             {
                 std::uint32_t len;
                 return get_number(input_format_t::msgpack, len) and get_string(input_format_t::msgpack, len, result);
             }
             default:
             {
                 auto last_token = get_token_string();
                 return sax->parse_error(chars_read, last_token, parse_error::create(113, chars_read, exception_message(input_format_t::msgpack, "expected length specification (0xA0-0xBF, 0xD9-0xDB); last byte: 0x" + last_token, "string")));
             }
         }
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_token_string(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::msgpack, result, nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof().
get_number() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> template<typename NumberType , bool InputIsLittleEndian = false> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_number (const input_format_t format, NumberType & result) inline private
Definition at line 1843 of file binary_reader.hpp.
     {
         // step 1: read input into array with system's byte order
         std::array<std::uint8_t, sizeof(NumberType)> vec;
         for (std::size_t i = 0; i < sizeof(NumberType); ++i)
         {
             get();
             if (JSON_HEDLEY_UNLIKELY(not unexpect_eof(format, "number")))
             {
                 return false;
             }
             // reverse byte order prior to conversion if necessary
             if (is_little_endian != InputIsLittleEndian)
             {
                 vec[sizeof(NumberType) - i - 1] = static_cast<std::uint8_t>(current);
             }
             else
             {
                 vec[i] = static_cast<std::uint8_t>(current); // LCOV_EXCL_LINE
             }
         }
         // step 2: convert array into number of type T and return
         std::memcpy(&result, vec.data(), sizeof(NumberType));
         return true;
     }
References array, nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::is_little_endian, JSON_HEDLEY_UNLIKELY, result, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_size_value(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_value(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_cbor_internal(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_msgpack_internal().
get_number() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> template<typename NumberType , bool InputIsLittleEndian = false> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_number (const input_format_t format, NumberType & result) inline private
Definition at line 6983 of file json.hpp.
     {
         // step 1: read input into array with system's byte order
         std::array<std::uint8_t, sizeof(NumberType)> vec;
         for (std::size_t i = 0; i < sizeof(NumberType); ++i)
         {
             get();
             if (JSON_HEDLEY_UNLIKELY(not unexpect_eof(format, "number")))
             {
                 return false;
             }
             // reverse byte order prior to conversion if necessary
             if (is_little_endian != InputIsLittleEndian)
             {
                 vec[sizeof(NumberType) - i - 1] = static_cast<std::uint8_t>(current);
             }
             else
             {
                 vec[i] = static_cast<std::uint8_t>(current); // LCOV_EXCL_LINE
             }
         }
         // step 2: convert array into number of type T and return
         std::memcpy(&result, vec.data(), sizeof(NumberType));
         return true;
     }
References array, nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::is_little_endian, JSON_HEDLEY_UNLIKELY, result, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof().
get_string() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> template<typename NumberType > bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_string (const input_format_t format, const NumberType len, string_t & result) inline private
create a string by reading characters from the input
Template Parameters
NumberType the type of the number
Parameters
[in] format the current format (for diagnostics)
[in] len number of characters to read
[out] result string created by reading len bytes
Returns
whether string creation completed
Note
We can not reserve len bytes for the result, because len may be too large. Usually, unexpect_eof() detects the end of the input before we run out of string memory.
Definition at line 1886 of file binary_reader.hpp.
     {
         bool success = true;
         std::generate_n(std::back_inserter(result), len, [this, &success, &format]()
         {
             get();
             if (JSON_HEDLEY_UNLIKELY(not unexpect_eof(format, "string")))
             {
                 success = false;
             }
             return static_cast<char>(current);
         });
         return success;
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), JSON_HEDLEY_UNLIKELY, result, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_bson_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_string(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_string().
get_string() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> template<typename NumberType > bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_string (const input_format_t format, const NumberType len, string_t & result) inline private
create a string by reading characters from the input
Template Parameters
NumberType the type of the number
Parameters
[in] format the current format (for diagnostics)
[in] len number of characters to read
[out] result string created by reading len bytes
Returns
whether string creation completed
Note
We can not reserve len bytes for the result, because len may be too large. Usually, unexpect_eof() detects the end of the input before we run out of string memory.
Definition at line 7026 of file json.hpp.
     {
         bool success = true;
         std::generate_n(std::back_inserter(result), len, [this, &success, &format]()
         {
             get();
             if (JSON_HEDLEY_UNLIKELY(not unexpect_eof(format, "string")))
             {
                 success = false;
             }
             return static_cast<char>(current);
         });
         return success;
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), JSON_HEDLEY_UNLIKELY, result, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof().
get_token_string() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> std::string nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_token_string () const inline private
Returns
a string representation of the last read byte
Definition at line 1922 of file binary_reader.hpp.
     {
         std::array<char, 3> cr{{}};
         (std::snprintf)(cr.data(), cr.size(), "%.2hhX", static_cast<unsigned char>(current));
         return std::string{cr.data()};
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::current.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_bson_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_size_type(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_size_value(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_value(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_cbor_internal(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_msgpack_internal(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax_parse().
get_token_string() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> std::string nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_token_string () const inline private
Returns
a string representation of the last read byte
Definition at line 7062 of file json.hpp.
     {
         std::array<char, 3> cr{{}};
         (std::snprintf)(cr.data(), cr.size(), "%.2hhX", static_cast<unsigned char>(current));
         return std::string{cr.data()};
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::current.
get_ubjson_array() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_array () inline private
Returns
whether array creation completed
Definition at line 1662 of file binary_reader.hpp.
     {
         std::pair<std::size_t, int> size_and_type;
         if (JSON_HEDLEY_UNLIKELY(not get_ubjson_size_type(size_and_type)))
         {
             return false;
         }
         if (size_and_type.first != string_t::npos)
         {
             if (JSON_HEDLEY_UNLIKELY(not sax->start_array(size_and_type.first)))
             {
                 return false;
             }
             if (size_and_type.second != 0)
             {
                 if (size_and_type.second != 'N')
                 {
                     for (std::size_t i = 0; i < size_and_type.first; ++i)
                     {
                         if (JSON_HEDLEY_UNLIKELY(not get_ubjson_value(size_and_type.second)))
{
                             return false;
                         }
                     }
                 }
             }
             else
             {
                 for (std::size_t i = 0; i < size_and_type.first; ++i)
                 {
                     if (JSON_HEDLEY_UNLIKELY(not parse_ubjson_internal()))
                     {
                         return false;
                     }
                 }
             }
         }
         else
         {
             if (JSON_HEDLEY_UNLIKELY(not sax->start_array(std::size_t(-1))))
             {
                 return false;
             }
             while (current != ']')
             {
                 if (JSON_HEDLEY_UNLIKELY(not parse_ubjson_internal(false)))
                 {
                     return false;
                 }
                 get_ignore_noop();
             }
         }
         return sax->end_array();
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ignore_noop(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_size_type(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_value(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_ubjson_internal(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_value().
get_ubjson_array() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_array () inline private
Returns
whether array creation completed
Definition at line 6802 of file json.hpp.
     {
         std::pair<std::size_t, int> size_and_type;
         if (JSON_HEDLEY_UNLIKELY(not get_ubjson_size_type(size_and_type)))
         {
             return false;
         }
         if (size_and_type.first != string_t::npos)
         {
             if (JSON_HEDLEY_UNLIKELY(not sax->start_array(size_and_type.first)))
             {
                 return false;
             }
             if (size_and_type.second != 0)
             {
                 if (size_and_type.second != 'N')
                 {
                     for (std::size_t i = 0; i < size_and_type.first; ++i)
                     {
                         if (JSON_HEDLEY_UNLIKELY(not get_ubjson_value(size_and_type.second)))
{
                             return false;
                         }
                     }
                 }
             }
             else
             {
                 for (std::size_t i = 0; i < size_and_type.first; ++i)
                 {
                     if (JSON_HEDLEY_UNLIKELY(not parse_ubjson_internal()))
                     {
                         return false;
                     }
                 }
             }
         }
         else
         {
             if (JSON_HEDLEY_UNLIKELY(not sax->start_array(std::size_t(-1))))
             {
                 return false;
             }
             while (current != ']')
             {
                 if (JSON_HEDLEY_UNLIKELY(not parse_ubjson_internal(false)))
                 {
                     return false;
                 }
                 get_ignore_noop();
             }
         }
         return sax->end_array();
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ignore_noop(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_size_type(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_value(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_ubjson_internal(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax.
get_ubjson_object() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_object () inline private
Returns
whether object creation completed
Definition at line 1724 of file binary_reader.hpp.
     {
         std::pair<std::size_t, int> size_and_type;
         if (JSON_HEDLEY_UNLIKELY(not get_ubjson_size_type(size_and_type)))
         {
             return false;
         }
         string_t key;
         if (size_and_type.first != string_t::npos)
         {
             if (JSON_HEDLEY_UNLIKELY(not sax->start_object(size_and_type.first)))
             {
                 return false;
             }
             if (size_and_type.second != 0)
             {
                 for (std::size_t i = 0; i < size_and_type.first; ++i)
                 {
                     if (JSON_HEDLEY_UNLIKELY(not get_ubjson_string(key) or not sax->key(key)))
                     {
                         return false;
                     }
                     if (JSON_HEDLEY_UNLIKELY(not get_ubjson_value(size_and_type.second)))
                     {
                         return false;
                     }
                     key.clear();
                 }
             }
             else
             {
                 for (std::size_t i = 0; i < size_and_type.first; ++i)
                 {
                     if (JSON_HEDLEY_UNLIKELY(not get_ubjson_string(key) or not sax->key(key)))
                     {
                         return false;
                     }
                     if (JSON_HEDLEY_UNLIKELY(not parse_ubjson_internal()))
                     {
                         return false;
                     }
                     key.clear();
                 }
             }
         }
         else
         {
             if (JSON_HEDLEY_UNLIKELY(not sax->start_object(std::size_t(-1))))
             {
                 return false;
             }
             while (current != '}')
             {
                 if (JSON_HEDLEY_UNLIKELY(not get_ubjson_string(key, false) or not sax->key(key)))
                 {
                     return false;
                 }
                 if (JSON_HEDLEY_UNLIKELY(not parse_ubjson_internal()))
                 {
                     return false;
                 }
                 get_ignore_noop();
                 key.clear();
             }
         }
         return sax->end_object();
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ignore_noop(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_size_type(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_value(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_ubjson_internal(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_value().
get_ubjson_object() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_object () inline private
Returns
whether object creation completed
Definition at line 6864 of file json.hpp.
     {
         std::pair<std::size_t, int> size_and_type;
         if (JSON_HEDLEY_UNLIKELY(not get_ubjson_size_type(size_and_type)))
         {
             return false;
         }
         string_t key;
         if (size_and_type.first != string_t::npos)
         {
             if (JSON_HEDLEY_UNLIKELY(not sax->start_object(size_and_type.first)))
             {
                 return false;
             }
             if (size_and_type.second != 0)
             {
                 for (std::size_t i = 0; i < size_and_type.first; ++i)
                 {
                     if (JSON_HEDLEY_UNLIKELY(not get_ubjson_string(key) or not sax->key(key)))
                     {
                         return false;
                     }
                     if (JSON_HEDLEY_UNLIKELY(not get_ubjson_value(size_and_type.second)))
                     {
                         return false;
                     }
                     key.clear();
                 }
             }
             else
             {
                 for (std::size_t i = 0; i < size_and_type.first; ++i)
                 {
                     if (JSON_HEDLEY_UNLIKELY(not get_ubjson_string(key) or not sax->key(key)))
                     {
                         return false;
                     }
                     if (JSON_HEDLEY_UNLIKELY(not parse_ubjson_internal()))
                     {
                         return false;
                     }
                     key.clear();
                 }
             }
         }
         else
         {
             if (JSON_HEDLEY_UNLIKELY(not sax->start_object(std::size_t(-1))))
             {
                 return false;
             }
             while (current != '}')
             {
                 if (JSON_HEDLEY_UNLIKELY(not get_ubjson_string(key, false) or not sax->key(key)))
                 {
                     return false;
                 }
                 if (JSON_HEDLEY_UNLIKELY(not parse_ubjson_internal()))
                 {
                     return false;
                 }
                 get_ignore_noop();
                 key.clear();
             }
         }
         return sax->end_object();
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ignore_noop(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_size_type(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_value(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_ubjson_internal(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax.
get_ubjson_size_type() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_size_type (std::pair< std::size_t, int > & result) inline private
determine the type and size for a container
In the optimized UBJSON format, a type and a size can be provided to allow for a more compact representation.
Parameters
[out] result pair of the size and the type
Returns
whether pair creation completed
Definition at line 1525 of file binary_reader.hpp.
     {
         result.first = string_t::npos; // size
         result.second = 0; // type
         get_ignore_noop();
         if (current == '$')
         {
             result.second = get();  // must not ignore 'N', because 'N' maybe the type
             if (JSON_HEDLEY_UNLIKELY(not unexpect_eof(input_format_t::ubjson, "type")))
             {
                 return false;
             }
             get_ignore_noop();
             if (JSON_HEDLEY_UNLIKELY(current != '#'))
             {
                 if (JSON_HEDLEY_UNLIKELY(not unexpect_eof(input_format_t::ubjson, "value")))
                 {
                     return false;
                 }
                 auto last_token = get_token_string();
                 return sax->parse_error(chars_read, last_token, parse_error::create(112, chars_read, exception_message(input_format_t::ubjson, "expected '#' after type information; last byte: 0x" + last_token, "size")));
             }
             return get_ubjson_size_value(result.first);
         }
         if (current == '#')
         {
             return get_ubjson_size_value(result.first);
         }
         return true;
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ignore_noop(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_token_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_size_value(), JSON_HEDLEY_UNLIKELY, result, nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax, nlohmann::detail::ubjson, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_array(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_object().
get_ubjson_size_type() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_size_type (std::pair< std::size_t, int > & result) inline private
determine the type and size for a container
In the optimized UBJSON format, a type and a size can be provided to allow for a more compact representation.
Parameters
[out] result pair of the size and the type
Returns
whether pair creation completed
Definition at line 6665 of file json.hpp.
     {
         result.first = string_t::npos; // size
         result.second = 0; // type
         get_ignore_noop();
         if (current == '$')
         {
             result.second = get();  // must not ignore 'N', because 'N' maybe the type
             if (JSON_HEDLEY_UNLIKELY(not unexpect_eof(input_format_t::ubjson, "type")))
             {
                 return false;
             }
             get_ignore_noop();
             if (JSON_HEDLEY_UNLIKELY(current != '#'))
             {
                 if (JSON_HEDLEY_UNLIKELY(not unexpect_eof(input_format_t::ubjson, "value")))
                 {
                     return false;
                 }
                 auto last_token = get_token_string();
                 return sax->parse_error(chars_read, last_token, parse_error::create(112, chars_read, exception_message(input_format_t::ubjson, "expected '#' after type information; last byte: 0x" + last_token, "size")));
             }
             return get_ubjson_size_value(result.first);
         }
         if (current == '#')
         {
             return get_ubjson_size_value(result.first);
         }
         return true;
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ignore_noop(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_token_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_size_value(), JSON_HEDLEY_UNLIKELY, result, nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax, nlohmann::detail::ubjson, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof().
get_ubjson_size_value() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_size_value (std::size_t & result) inline private
Parameters
[out] result determined size
Returns
whether size determination completed
Definition at line 1448 of file binary_reader.hpp.
     {
         switch (get_ignore_noop())
         {
             case 'U':
             {
                 std::uint8_t number;
                 if (JSON_HEDLEY_UNLIKELY(not get_number(input_format_t::ubjson, number)))
                 {
                     return false;
                 }
                 result = static_cast<std::size_t>(number);
                 return true;
             }
             case 'i':
             {
                 std::int8_t number;
                 if (JSON_HEDLEY_UNLIKELY(not get_number(input_format_t::ubjson, number)))
                 {
                     return false;
                 }
                 result = static_cast<std::size_t>(number);
                 return true;
             }
             case 'I':
             {
                 std::int16_t number;
                 if (JSON_HEDLEY_UNLIKELY(not get_number(input_format_t::ubjson, number)))
                 {
                     return false;
                 }
                 result = static_cast<std::size_t>(number);
                 return true;
             }
             case 'l':
             {
                 std::int32_t number;
                 if (JSON_HEDLEY_UNLIKELY(not get_number(input_format_t::ubjson, number)))
                 {
                     return false;
                 }
                 result = static_cast<std::size_t>(number);
                 return true;
             }
             case 'L':
             {
                 std::int64_t number;
                 if (JSON_HEDLEY_UNLIKELY(not get_number(input_format_t::ubjson, number)))
                 {
                     return false;
                 }
                 result = static_cast<std::size_t>(number);
                 return true;
             }
             default:
             {
                 auto last_token = get_token_string();
                 return sax->parse_error(chars_read, last_token, parse_error::create(113, chars_read, exception_message(input_format_t::ubjson, "expected length type specification (U, i, I, l, L) after '#'; last byte: 0x" + last_token, "size")));
             }
         }
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ignore_noop(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_token_string(), JSON_HEDLEY_UNLIKELY, result, nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax, and nlohmann::detail::ubjson.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_size_type().
get_ubjson_size_value() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_size_value (std::size_t & result) inline private
Parameters
[out] result determined size
Returns
whether size determination completed
Definition at line 6588 of file json.hpp.
     {
         switch (get_ignore_noop())
         {
             case 'U':
             {
                 std::uint8_t number;
                 if (JSON_HEDLEY_UNLIKELY(not get_number(input_format_t::ubjson, number)))
                 {
                     return false;
                 }
                 result = static_cast<std::size_t>(number);
                 return true;
             }
             case 'i':
             {
                 std::int8_t number;
                 if (JSON_HEDLEY_UNLIKELY(not get_number(input_format_t::ubjson, number)))
                 {
                     return false;
                 }
                 result = static_cast<std::size_t>(number);
                 return true;
             }
             case 'I':
             {
                 std::int16_t number;
                 if (JSON_HEDLEY_UNLIKELY(not get_number(input_format_t::ubjson, number)))
                 {
                     return false;
                 }
                 result = static_cast<std::size_t>(number);
                 return true;
             }
             case 'l':
             {
                 std::int32_t number;
                 if (JSON_HEDLEY_UNLIKELY(not get_number(input_format_t::ubjson, number)))
                 {
                     return false;
                 }
                 result = static_cast<std::size_t>(number);
                 return true;
             }
             case 'L':
             {
                 std::int64_t number;
                 if (JSON_HEDLEY_UNLIKELY(not get_number(input_format_t::ubjson, number)))
                 {
                     return false;
                 }
                 result = static_cast<std::size_t>(number);
                 return true;
             }
             default:
             {
                 auto last_token = get_token_string();
                 return sax->parse_error(chars_read, last_token, parse_error::create(113, chars_read, exception_message(input_format_t::ubjson, "expected length type specification (U, i, I, l, L) after '#'; last byte: 0x" + last_token, "size")));
             }
         }
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ignore_noop(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_token_string(), JSON_HEDLEY_UNLIKELY, result, nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax, and nlohmann::detail::ubjson.
get_ubjson_string() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_string (string_t & result, const bool get_char = true) inline private
reads a UBJSON string
This function is either called after reading the 'S' byte explicitly indicating a string, or in case of an object key where the 'S' byte can be left out.
Parameters
[out] result created string
[in] get_char whether a new character should be retrieved from the input (true, default) or whether the last read character should be considered instead
Returns
whether string creation completed
Definition at line 1394 of file binary_reader.hpp.
     {
         if (get_char)
         {
             get();  // TODO(niels): may we ignore N here?
         }
         if (JSON_HEDLEY_UNLIKELY(not unexpect_eof(input_format_t::ubjson, "value")))
         {
             return false;
         }
         switch (current)
         {
             case 'U':
             {
                 std::uint8_t len;
                 return get_number(input_format_t::ubjson, len) and get_string(input_format_t::ubjson, len, result);
             }
             case 'i':
             {
                 std::int8_t len;
                 return get_number(input_format_t::ubjson, len) and get_string(input_format_t::ubjson, len, result);
             }
             case 'I':
             {
                 std::int16_t len;
                 return get_number(input_format_t::ubjson, len) and get_string(input_format_t::ubjson, len, result);
             }
             case 'l':
             {
                 std::int32_t len;
                 return get_number(input_format_t::ubjson, len) and get_string(input_format_t::ubjson, len, result);
             }
             case 'L':
             {
                 std::int64_t len;
                 return get_number(input_format_t::ubjson, len) and get_string(input_format_t::ubjson, len, result);
             }
             default:
                 auto last_token = get_token_string();
                 return sax->parse_error(chars_read, last_token, parse_error::create(113, chars_read, exception_message(input_format_t::ubjson, "expected length type specification (U, i, I, l, L); last byte: 0x" + last_token, "string")));
         }
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_token_string(), JSON_HEDLEY_UNLIKELY, result, nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax, nlohmann::detail::ubjson, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_object(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_value().
get_ubjson_string() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_string (string_t & result, const bool get_char = true) inline private
reads a UBJSON string
This function is either called after reading the 'S' byte explicitly indicating a string, or in case of an object key where the 'S' byte can be left out.
Parameters
[out] result created string
[in] get_char whether a new character should be retrieved from the input (true, default) or whether the last read character should be considered instead
Returns
whether string creation completed
Definition at line 6534 of file json.hpp.
     {
         if (get_char)
         {
             get();  // TODO(niels): may we ignore N here?
         }
         if (JSON_HEDLEY_UNLIKELY(not unexpect_eof(input_format_t::ubjson, "value")))
         {
             return false;
         }
         switch (current)
         {
             case 'U':
             {
                 std::uint8_t len;
                 return get_number(input_format_t::ubjson, len) and get_string(input_format_t::ubjson, len, result);
             }
             case 'i':
             {
                 std::int8_t len;
                 return get_number(input_format_t::ubjson, len) and get_string(input_format_t::ubjson, len, result);
             }
             case 'I':
             {
                 std::int16_t len;
                 return get_number(input_format_t::ubjson, len) and get_string(input_format_t::ubjson, len, result);
             }
             case 'l':
             {
                 std::int32_t len;
                 return get_number(input_format_t::ubjson, len) and get_string(input_format_t::ubjson, len, result);
             }
             case 'L':
             {
                 std::int64_t len;
                 return get_number(input_format_t::ubjson, len) and get_string(input_format_t::ubjson, len, result);
             }
             default:
                 auto last_token = get_token_string();
                 return sax->parse_error(chars_read, last_token, parse_error::create(113, chars_read, exception_message(input_format_t::ubjson, "expected length type specification (U, i, I, l, L); last byte: 0x" + last_token, "string")));
         }
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_token_string(), JSON_HEDLEY_UNLIKELY, result, nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax, nlohmann::detail::ubjson, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof().
get_ubjson_value() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_value (const int prefix) inline private
Parameters
prefix the previously read or set type prefix
Returns
whether value creation completed
Definition at line 1566 of file binary_reader.hpp.
     {
         switch (prefix)
         {
             case std::char_traits<char>::eof():  // EOF
                 return unexpect_eof(input_format_t::ubjson, "value");
             case 'T':  // true
                 return sax->boolean(true);
             case 'F':  // false
                 return sax->boolean(false);
             case 'Z':  // null
                 return sax->null();
             case 'U':
             {
                 std::uint8_t number;
                 return get_number(input_format_t::ubjson, number) and sax->number_unsigned(number);
             }
             case 'i':
             {
                 std::int8_t number;
                 return get_number(input_format_t::ubjson, number) and sax->number_integer(number);
             }
             case 'I':
             {
                 std::int16_t number;
                 return get_number(input_format_t::ubjson, number) and sax->number_integer(number);
             }
             case 'l':
             {
                 std::int32_t number;
                 return get_number(input_format_t::ubjson, number) and sax->number_integer(number);
             }
             case 'L':
             {
                 std::int64_t number;
                 return get_number(input_format_t::ubjson, number) and sax->number_integer(number);
             }
             case 'd':
             {
                 float number;
                 return get_number(input_format_t::ubjson, number) and sax->number_float(static_cast<number_float_t>(number), "");
             }
             case 'D':
             {
                 double number;
                 return get_number(input_format_t::ubjson, number) and sax->number_float(static_cast<number_float_t>(number), "");
             }
             case 'C':  // char
             {
                 get();
                 if (JSON_HEDLEY_UNLIKELY(not unexpect_eof(input_format_t::ubjson, "char")))
                 {
                     return false;
                 }
                 if (JSON_HEDLEY_UNLIKELY(current > 127))
                 {
                     auto last_token = get_token_string();
                     return sax->parse_error(chars_read, last_token, parse_error::create(113, chars_read, exception_message(input_format_t::ubjson, "byte after 'C' must be in range 0x00..0x7F; last byte: 0x" + last_token, "char")));
                 }
                 string_t s(1, static_cast<char>(current));
                 return sax->string(s);
             }
             case 'S':  // string
             {
                 string_t s;
                 return get_ubjson_string(s) and sax->string(s);
             }
             case '[':  // array
                 return get_ubjson_array();
             case '{':  // object
                 return get_ubjson_object();
             default: // anything else
             {
                 auto last_token = get_token_string();
                 return sax->parse_error(chars_read, last_token, parse_error::create(112, chars_read, exception_message(input_format_t::ubjson, "invalid byte: 0x" + last_token, "value")));
             }
         }
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_token_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_array(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_object(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_string(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax, nlohmann::detail::ubjson, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_array(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_object(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_ubjson_internal().
get_ubjson_value() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_value (const int prefix) inline private
Parameters
prefix the previously read or set type prefix
Returns
whether value creation completed
Definition at line 6706 of file json.hpp.
     {
         switch (prefix)
         {
             case std::char_traits<char>::eof():  // EOF
                 return unexpect_eof(input_format_t::ubjson, "value");
             case 'T':  // true
                 return sax->boolean(true);
             case 'F':  // false
                 return sax->boolean(false);
             case 'Z':  // null
                 return sax->null();
             case 'U':
             {
                 std::uint8_t number;
                 return get_number(input_format_t::ubjson, number) and sax->number_unsigned(number);
             }
             case 'i':
             {
                 std::int8_t number;
                 return get_number(input_format_t::ubjson, number) and sax->number_integer(number);
             }
             case 'I':
             {
                 std::int16_t number;
                 return get_number(input_format_t::ubjson, number) and sax->number_integer(number);
             }
             case 'l':
             {
                 std::int32_t number;
                 return get_number(input_format_t::ubjson, number) and sax->number_integer(number);
             }
             case 'L':
             {
                 std::int64_t number;
                 return get_number(input_format_t::ubjson, number) and sax->number_integer(number);
             }
             case 'd':
             {
                 float number;
                 return get_number(input_format_t::ubjson, number) and sax->number_float(static_cast<number_float_t>(number), "");
             }
             case 'D':
             {
                 double number;
                 return get_number(input_format_t::ubjson, number) and sax->number_float(static_cast<number_float_t>(number), "");
             }
             case 'C':  // char
             {
                 get();
                 if (JSON_HEDLEY_UNLIKELY(not unexpect_eof(input_format_t::ubjson, "char")))
                 {
                     return false;
                 }
                 if (JSON_HEDLEY_UNLIKELY(current > 127))
                 {
                     auto last_token = get_token_string();
                     return sax->parse_error(chars_read, last_token, parse_error::create(113, chars_read, exception_message(input_format_t::ubjson, "byte after 'C' must be in range 0x00..0x7F; last byte: 0x" + last_token, "char")));
                 }
                 string_t s(1, static_cast<char>(current));
                 return sax->string(s);
             }
             case 'S':  // string
             {
                 string_t s;
                 return get_ubjson_string(s) and sax->string(s);
             }
             case '[':  // array
                 return get_ubjson_array();
             case '{':  // object
                 return get_ubjson_object();
             default: // anything else
             {
                 auto last_token = get_token_string();
                 return sax->parse_error(chars_read, last_token, parse_error::create(112, chars_read, exception_message(input_format_t::ubjson, "invalid byte: 0x" + last_token, "value")));
             }
         }
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_token_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_array(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_object(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_string(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax, nlohmann::detail::ubjson, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof().
little_endianess() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> static constexpr bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::little_endianess (int num = 1) inline static constexpr noexcept
determine system byte order
Returns
true if and only if system's byte order is little endian
Note
from http://stackoverflow.com/a/1001328/266378
Definition at line 128 of file binary_reader.hpp.
     {
         return *reinterpret_cast<char*>(&num) == 1;
     }
little_endianess() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> static constexpr bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::little_endianess (int num = 1) inline static constexpr noexcept
determine system byte order
Returns
true if and only if system's byte order is little endian
Note
from http://stackoverflow.com/a/1001328/266378
Definition at line 5268 of file json.hpp.
     {
         return *reinterpret_cast<char*>(&num) == 1;
     }
operator=() [1/4]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> binary_reader& nlohmann::detail::binary_reader< BasicJsonType, SAX >::operator= (binary_reader< BasicJsonType, SAX > &&) default
operator=() [2/4]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> binary_reader& nlohmann::detail::binary_reader< BasicJsonType, SAX >::operator= (binary_reader< BasicJsonType, SAX > &&) default
operator=() [3/4]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> binary_reader& nlohmann::detail::binary_reader< BasicJsonType, SAX >::operator= (const binary_reader< BasicJsonType, SAX > &) delete
operator=() [4/4]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> binary_reader& nlohmann::detail::binary_reader< BasicJsonType, SAX >::operator= (const binary_reader< BasicJsonType, SAX > &) delete
parse_bson_array() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_array () inline private
Reads an array from the BSON input and passes it to the SAX-parser.
Returns
whether a valid BSON-array was passed to the SAX parser
Definition at line 328 of file binary_reader.hpp.
     {
         std::int32_t document_size;
         get_number<std::int32_t, true>(input_format_t::bson, document_size);
         if (JSON_HEDLEY_UNLIKELY(not sax->start_array(std::size_t(-1))))
         {
             return false;
         }
         if (JSON_HEDLEY_UNLIKELY(not parse_bson_element_list(/*is_array*/true)))
         {
             return false;
         }
         return sax->end_array();
     }
References nlohmann::detail::bson, JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_element_list(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_element_internal().
parse_bson_array() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_array () inline private
Reads an array from the BSON input and passes it to the SAX-parser.
Returns
whether a valid BSON-array was passed to the SAX parser
Definition at line 5468 of file json.hpp.
     {
         std::int32_t document_size;
         get_number<std::int32_t, true>(input_format_t::bson, document_size);
         if (JSON_HEDLEY_UNLIKELY(not sax->start_array(std::size_t(-1))))
         {
             return false;
         }
         if (JSON_HEDLEY_UNLIKELY(not parse_bson_element_list(/*is_array*/true)))
         {
             return false;
         }
         return sax->end_array();
     }
References nlohmann::detail::bson, JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_element_list(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax.
parse_bson_element_internal() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_element_internal (const int element_type, const std::size_t element_type_parse_position) inline private
Read a BSON document element of the given element_type.
Parameters
[in] element_type The BSON element type, c.f. http://bsonspec.org/spec.html
[in] element_type_parse_position The position in the input stream, where the element_type was read.
Warning
Not all BSON element types are supported yet. An unsupported element_type will give rise to a parse_error.114: Unsupported BSON record type 0x...
Returns
whether a valid BSON-object/array was passed to the SAX parser
Definition at line 220 of file binary_reader.hpp.
     {
         switch (element_type)
         {
             case 0x01: // double
             {
                 double number;
                 return get_number<double, true>(input_format_t::bson, number) and sax->number_float(static_cast<number_float_t>(number), "");
             }
             case 0x02: // string
             {
                 std::int32_t len;
                 string_t value;
                 return get_number<std::int32_t, true>(input_format_t::bson, len) and get_bson_string(len, value) and sax->string(value);
             }
             case 0x03: // object
             {
                 return parse_bson_internal();
             }
             case 0x04: // array
             {
                 return parse_bson_array();
             }
             case 0x08: // boolean
             {
                 return sax->boolean(get() != 0);
             }
             case 0x0A: // null
             {
                 return sax->null();
             }
             case 0x10: // int32
             {
                 std::int32_t value;
                 return get_number<std::int32_t, true>(input_format_t::bson, value) and sax->number_integer(value);
             }
             case 0x12: // int64
             {
                 std::int64_t value;
                 return get_number<std::int64_t, true>(input_format_t::bson, value) and sax->number_integer(value);
             }
             default: // anything else not supported (yet)
             {
                 std::array<char, 3> cr{{}};
                 (std::snprintf)(cr.data(), cr.size(), "%.2hhX", static_cast<unsigned char>(element_type));
                 return sax->parse_error(element_type_parse_position, std::string(cr.data()), parse_error::create(114, element_type_parse_position, "Unsupported BSON record type 0x" + std::string(cr.data())));
             }
         }
     }
References nlohmann::detail::bson, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_bson_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_array(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_internal(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_element_list().
parse_bson_element_internal() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_element_internal (const int element_type, const std::size_t element_type_parse_position) inline private
Read a BSON document element of the given element_type.
Parameters
[in] element_type The BSON element type, c.f. http://bsonspec.org/spec.html
[in] element_type_parse_position The position in the input stream, where the element_type was read.
Warning
Not all BSON element types are supported yet. An unsupported element_type will give rise to a parse_error.114: Unsupported BSON record type 0x...
Returns
whether a valid BSON-object/array was passed to the SAX parser
Definition at line 5360 of file json.hpp.
     {
         switch (element_type)
         {
             case 0x01: // double
             {
                 double number;
                 return get_number<double, true>(input_format_t::bson, number) and sax->number_float(static_cast<number_float_t>(number), "");
             }
             case 0x02: // string
             {
                 std::int32_t len;
                 string_t value;
                 return get_number<std::int32_t, true>(input_format_t::bson, len) and get_bson_string(len, value) and sax->string(value);
             }
             case 0x03: // object
             {
                 return parse_bson_internal();
             }
             case 0x04: // array
             {
                 return parse_bson_array();
             }
             case 0x08: // boolean
             {
                 return sax->boolean(get() != 0);
             }
             case 0x0A: // null
             {
                 return sax->null();
             }
             case 0x10: // int32
             {
                 std::int32_t value;
                 return get_number<std::int32_t, true>(input_format_t::bson, value) and sax->number_integer(value);
             }
             case 0x12: // int64
             {
                 std::int64_t value;
                 return get_number<std::int64_t, true>(input_format_t::bson, value) and sax->number_integer(value);
             }
             default: // anything else not supported (yet)
             {
                 std::array<char, 3> cr{{}};
                 (std::snprintf)(cr.data(), cr.size(), "%.2hhX", static_cast<unsigned char>(element_type));
                 return sax->parse_error(element_type_parse_position, std::string(cr.data()), parse_error::create(114, element_type_parse_position, "Unsupported BSON record type 0x" + std::string(cr.data())));
             }
         }
     }
References nlohmann::detail::bson, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_bson_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_array(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_internal(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax.
parse_bson_element_list() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_element_list (const bool is_array) inline private
Read a BSON element list (as specified in the BSON-spec)
The same binary layout is used for objects and arrays, hence it must be indicated with the argument is_array which one is expected (true --> array, false --> object).
Parameters
[in] is_array Determines if the element list being read is to be treated as an object (is_array == false), or as an array (is_array == true).
Returns
whether a valid BSON-object/array was passed to the SAX parser
Definition at line 291 of file binary_reader.hpp.
     {
         string_t key;
         while (int element_type = get())
         {
             if (JSON_HEDLEY_UNLIKELY(not unexpect_eof(input_format_t::bson, "element list")))
             {
                 return false;
             }
             const std::size_t element_type_parse_position = chars_read;
             if (JSON_HEDLEY_UNLIKELY(not get_bson_cstr(key)))
             {
                 return false;
             }
             if (not is_array and not sax->key(key))
             {
                 return false;
             }
             if (JSON_HEDLEY_UNLIKELY(not parse_bson_element_internal(element_type, element_type_parse_position)))
             {
                 return false;
             }
             // get_bson_cstr only appends
             key.clear();
         }
         return true;
     }
References nlohmann::detail::bson, nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read, nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_bson_cstr(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_element_internal(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_array(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_internal().
parse_bson_element_list() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_element_list (const bool is_array) inline private
Read a BSON element list (as specified in the BSON-spec)
The same binary layout is used for objects and arrays, hence it must be indicated with the argument is_array which one is expected (true --> array, false --> object).
Parameters
[in] is_array Determines if the element list being read is to be treated as an object (is_array == false), or as an array (is_array == true).
Returns
whether a valid BSON-object/array was passed to the SAX parser
Definition at line 5431 of file json.hpp.
     {
         string_t key;
         while (int element_type = get())
         {
             if (JSON_HEDLEY_UNLIKELY(not unexpect_eof(input_format_t::bson, "element list")))
             {
                 return false;
             }
             const std::size_t element_type_parse_position = chars_read;
             if (JSON_HEDLEY_UNLIKELY(not get_bson_cstr(key)))
             {
                 return false;
             }
             if (not is_array and not sax->key(key))
             {
                 return false;
             }
             if (JSON_HEDLEY_UNLIKELY(not parse_bson_element_internal(element_type, element_type_parse_position)))
             {
                 return false;
             }
             // get_bson_cstr only appends
             key.clear();
         }
         return true;
     }
References nlohmann::detail::bson, nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read, nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_bson_cstr(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_element_internal(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof().
parse_bson_internal() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_internal () inline private
Reads in a BSON-object and passes it to the SAX-parser.
Returns
whether a valid BSON-value was passed to the SAX parser
Definition at line 142 of file binary_reader.hpp.
     {
         std::int32_t document_size;
         get_number<std::int32_t, true>(input_format_t::bson, document_size);
         if (JSON_HEDLEY_UNLIKELY(not sax->start_object(std::size_t(-1))))
         {
             return false;
         }
         if (JSON_HEDLEY_UNLIKELY(not parse_bson_element_list(/*is_array*/false)))
         {
             return false;
         }
         return sax->end_object();
     }
References nlohmann::detail::bson, JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_element_list(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_element_internal(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax_parse().
parse_bson_internal() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_internal () inline private
Reads in a BSON-object and passes it to the SAX-parser.
Returns
whether a valid BSON-value was passed to the SAX parser
Definition at line 5282 of file json.hpp.
     {
         std::int32_t document_size;
         get_number<std::int32_t, true>(input_format_t::bson, document_size);
         if (JSON_HEDLEY_UNLIKELY(not sax->start_object(std::size_t(-1))))
         {
             return false;
         }
         if (JSON_HEDLEY_UNLIKELY(not parse_bson_element_list(/*is_array*/false)))
         {
             return false;
         }
         return sax->end_object();
     }
References nlohmann::detail::bson, JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_element_list(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax.
parse_cbor_internal() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_cbor_internal (const bool get_char = true) inline private
Parameters
[in] get_char whether a new character should be retrieved from the input (true, default) or whether the last read character should be considered instead
Returns
whether a valid CBOR value was passed to the SAX parser
Definition at line 357 of file binary_reader.hpp.
     {
         switch (get_char ? get() : current)
         {
             // EOF
             case std::char_traits<char>::eof():
                 return unexpect_eof(input_format_t::cbor, "value");
             // Integer 0x00..0x17 (0..23)
             case 0x00:
             case 0x01:
             case 0x02:
             case 0x03:
             case 0x04:
             case 0x05:
             case 0x06:
             case 0x07:
             case 0x08:
             case 0x09:
             case 0x0A:
             case 0x0B:
             case 0x0C:
             case 0x0D:
             case 0x0E:
             case 0x0F:
             case 0x10:
             case 0x11:
             case 0x12:
             case 0x13:
             case 0x14:
             case 0x15:
             case 0x16:
             case 0x17:
                 return sax->number_unsigned(static_cast<number_unsigned_t>(current));
             case 0x18: // Unsigned integer (one-byte uint8_t follows)
             {
                 std::uint8_t number;
                 return get_number(input_format_t::cbor, number) and sax->number_unsigned(number);
             }
             case 0x19: // Unsigned integer (two-byte uint16_t follows)
             {
                 std::uint16_t number;
                 return get_number(input_format_t::cbor, number) and sax->number_unsigned(number);
             }
             case 0x1A: // Unsigned integer (four-byte uint32_t follows)
             {
                 std::uint32_t number;
                 return get_number(input_format_t::cbor, number) and sax->number_unsigned(number);
             }
             case 0x1B: // Unsigned integer (eight-byte uint64_t follows)
             {
                 std::uint64_t number;
                 return get_number(input_format_t::cbor, number) and sax->number_unsigned(number);
             }
             // Negative integer -1-0x00..-1-0x17 (-1..-24)
             case 0x20:
             case 0x21:
             case 0x22:
             case 0x23:
             case 0x24:
             case 0x25:
             case 0x26:
             case 0x27:
             case 0x28:
             case 0x29:
             case 0x2A:
             case 0x2B:
             case 0x2C:
             case 0x2D:
             case 0x2E:
             case 0x2F:
             case 0x30:
             case 0x31:
             case 0x32:
             case 0x33:
             case 0x34:
             case 0x35:
             case 0x36:
             case 0x37:
                 return sax->number_integer(static_cast<std::int8_t>(0x20 - 1 - current));
             case 0x38: // Negative integer (one-byte uint8_t follows)
             {
                 std::uint8_t number;
                 return get_number(input_format_t::cbor, number) and sax->number_integer(static_cast<number_integer_t>(-1) - number);
             }
             case 0x39: // Negative integer -1-n (two-byte uint16_t follows)
             {
                 std::uint16_t number;
                 return get_number(input_format_t::cbor, number) and sax->number_integer(static_cast<number_integer_t>(-1) - number);
             }
             case 0x3A: // Negative integer -1-n (four-byte uint32_t follows)
             {
                 std::uint32_t number;
                 return get_number(input_format_t::cbor, number) and sax->number_integer(static_cast<number_integer_t>(-1) - number);
             }
             case 0x3B: // Negative integer -1-n (eight-byte uint64_t follows)
             {
                 std::uint64_t number;
                 return get_number(input_format_t::cbor, number) and sax->number_integer(static_cast<number_integer_t>(-1)
                         - static_cast<number_integer_t>(number));
             }
             // UTF-8 string (0x00..0x17 bytes follow)
             case 0x60:
             case 0x61:
             case 0x62:
             case 0x63:
             case 0x64:
             case 0x65:
             case 0x66:
             case 0x67:
             case 0x68:
             case 0x69:
             case 0x6A:
             case 0x6B:
             case 0x6C:
             case 0x6D:
             case 0x6E:
             case 0x6F:
             case 0x70:
             case 0x71:
             case 0x72:
             case 0x73:
             case 0x74:
             case 0x75:
             case 0x76:
             case 0x77:
             case 0x78: // UTF-8 string (one-byte uint8_t for n follows)
             case 0x79: // UTF-8 string (two-byte uint16_t for n follow)
             case 0x7A: // UTF-8 string (four-byte uint32_t for n follow)
             case 0x7B: // UTF-8 string (eight-byte uint64_t for n follow)
             case 0x7F: // UTF-8 string (indefinite length)
             {
                 string_t s;
                 return get_cbor_string(s) and sax->string(s);
             }
             // array (0x00..0x17 data items follow)
             case 0x80:
             case 0x81:
             case 0x82:
             case 0x83:
             case 0x84:
             case 0x85:
             case 0x86:
             case 0x87:
             case 0x88:
             case 0x89:
             case 0x8A:
             case 0x8B:
             case 0x8C:
             case 0x8D:
             case 0x8E:
             case 0x8F:
             case 0x90:
             case 0x91:
             case 0x92:
             case 0x93:
             case 0x94:
             case 0x95:
             case 0x96:
             case 0x97:
                 return get_cbor_array(static_cast<std::size_t>(static_cast<unsigned int>(current) & 0x1Fu));
             case 0x98: // array (one-byte uint8_t for n follows)
             {
                 std::uint8_t len;
                 return get_number(input_format_t::cbor, len) and get_cbor_array(static_cast<std::size_t>(len));
             }
             case 0x99: // array (two-byte uint16_t for n follow)
             {
                 std::uint16_t len;
                 return get_number(input_format_t::cbor, len) and get_cbor_array(static_cast<std::size_t>(len));
             }
             case 0x9A: // array (four-byte uint32_t for n follow)
             {
                 std::uint32_t len;
                 return get_number(input_format_t::cbor, len) and get_cbor_array(static_cast<std::size_t>(len));
             }
             case 0x9B: // array (eight-byte uint64_t for n follow)
             {
                 std::uint64_t len;
                 return get_number(input_format_t::cbor, len) and get_cbor_array(static_cast<std::size_t>(len));
             }
             case 0x9F: // array (indefinite length)
                 return get_cbor_array(std::size_t(-1));
             // map (0x00..0x17 pairs of data items follow)
             case 0xA0:
             case 0xA1:
             case 0xA2:
             case 0xA3:
             case 0xA4:
             case 0xA5:
             case 0xA6:
             case 0xA7:
             case 0xA8:
             case 0xA9:
             case 0xAA:
             case 0xAB:
             case 0xAC:
             case 0xAD:
             case 0xAE:
             case 0xAF:
             case 0xB0:
             case 0xB1:
             case 0xB2:
             case 0xB3:
             case 0xB4:
             case 0xB5:
             case 0xB6:
             case 0xB7:
                 return get_cbor_object(static_cast<std::size_t>(static_cast<unsigned int>(current) & 0x1Fu));
             case 0xB8: // map (one-byte uint8_t for n follows)
             {
                 std::uint8_t len;
                 return get_number(input_format_t::cbor, len) and get_cbor_object(static_cast<std::size_t>(len));
             }
             case 0xB9: // map (two-byte uint16_t for n follow)
             {
                 std::uint16_t len;
                 return get_number(input_format_t::cbor, len) and get_cbor_object(static_cast<std::size_t>(len));
             }
             case 0xBA: // map (four-byte uint32_t for n follow)
             {
                 std::uint32_t len;
                 return get_number(input_format_t::cbor, len) and get_cbor_object(static_cast<std::size_t>(len));
             }
             case 0xBB: // map (eight-byte uint64_t for n follow)
             {
                 std::uint64_t len;
                 return get_number(input_format_t::cbor, len) and get_cbor_object(static_cast<std::size_t>(len));
             }
             case 0xBF: // map (indefinite length)
                 return get_cbor_object(std::size_t(-1));
             case 0xF4: // false
                 return sax->boolean(false);
             case 0xF5: // true
                 return sax->boolean(true);
             case 0xF6: // null
                 return sax->null();
             case 0xF9: // Half-Precision Float (two-byte IEEE 754)
             {
                 const int byte1_raw = get();
                 if (JSON_HEDLEY_UNLIKELY(not unexpect_eof(input_format_t::cbor, "number")))
                 {
                     return false;
                 }
                 const int byte2_raw = get();
                 if (JSON_HEDLEY_UNLIKELY(not unexpect_eof(input_format_t::cbor, "number")))
                 {
                     return false;
                 }
                 const auto byte1 = static_cast<unsigned char>(byte1_raw);
                 const auto byte2 = static_cast<unsigned char>(byte2_raw);
                 // code from RFC 7049, Appendix D, Figure 3:
                 // As half-precision floating-point numbers were only added
                 // to IEEE 754 in 2008, today's programming platforms often
                 // still only have limited support for them. It is very
                 // easy to include at least decoding support for them even
                 // without such support. An example of a small decoder for
                 // half-precision floating-point numbers in the C language
                 // is shown in Fig. 3.
                 const auto half = static_cast<unsigned int>((byte1 << 8u) + byte2);
                 const double val = [&half]
                 {
                     const int exp = (half >> 10u) & 0x1Fu;
                     const unsigned int mant = half & 0x3FFu;
                     assert(0 <= exp and exp <= 32);
                     assert(mant <= 1024);
                     switch (exp)
                     {
                         case 0:
                             return std::ldexp(mant, -24);
                         case 31:
                             return (mant == 0)
                             ? std::numeric_limits<double>::infinity()
                             : std::numeric_limits<double>::quiet_NaN();
                         default:
                             return std::ldexp(mant + 1024, exp - 25);
                     }
                 }();
                 return sax->number_float((half & 0x8000u) != 0
                                          ? static_cast<number_float_t>(-val)
                                          : static_cast<number_float_t>(val), "");
             }
             case 0xFA: // Single-Precision Float (four-byte IEEE 754)
             {
                 float number;
                 return get_number(input_format_t::cbor, number) and sax->number_float(static_cast<number_float_t>(number), "");
             }
             case 0xFB: // Double-Precision Float (eight-byte IEEE 754)
             {
                 double number;
                 return get_number(input_format_t::cbor, number) and sax->number_float(static_cast<number_float_t>(number), "");
             }
             default: // anything else (0xFF is handled inside the other types)
             {
                 auto last_token = get_token_string();
                 return sax->parse_error(chars_read, last_token, parse_error::create(112, chars_read, exception_message(input_format_t::cbor, "invalid byte: 0x" + last_token, "value")));
             }
         }
     }
References assert(), nlohmann::detail::cbor, nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_array(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_object(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_token_string(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_array(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_object(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax_parse().
parse_cbor_internal() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_cbor_internal (const bool get_char = true) inline private
Parameters
[in] get_char whether a new character should be retrieved from the input (true, default) or whether the last read character should be considered instead
Returns
whether a valid CBOR value was passed to the SAX parser
Definition at line 5497 of file json.hpp.
     {
         switch (get_char ? get() : current)
         {
             // EOF
             case std::char_traits<char>::eof():
                 return unexpect_eof(input_format_t::cbor, "value");
             // Integer 0x00..0x17 (0..23)
             case 0x00:
             case 0x01:
             case 0x02:
             case 0x03:
             case 0x04:
             case 0x05:
             case 0x06:
             case 0x07:
             case 0x08:
             case 0x09:
             case 0x0A:
             case 0x0B:
             case 0x0C:
             case 0x0D:
             case 0x0E:
             case 0x0F:
             case 0x10:
             case 0x11:
             case 0x12:
             case 0x13:
             case 0x14:
             case 0x15:
             case 0x16:
             case 0x17:
                 return sax->number_unsigned(static_cast<number_unsigned_t>(current));
             case 0x18: // Unsigned integer (one-byte uint8_t follows)
             {
                 std::uint8_t number;
                 return get_number(input_format_t::cbor, number) and sax->number_unsigned(number);
             }
             case 0x19: // Unsigned integer (two-byte uint16_t follows)
             {
                 std::uint16_t number;
                 return get_number(input_format_t::cbor, number) and sax->number_unsigned(number);
             }
             case 0x1A: // Unsigned integer (four-byte uint32_t follows)
             {
                 std::uint32_t number;
                 return get_number(input_format_t::cbor, number) and sax->number_unsigned(number);
             }
             case 0x1B: // Unsigned integer (eight-byte uint64_t follows)
             {
                 std::uint64_t number;
                 return get_number(input_format_t::cbor, number) and sax->number_unsigned(number);
             }
             // Negative integer -1-0x00..-1-0x17 (-1..-24)
             case 0x20:
             case 0x21:
             case 0x22:
             case 0x23:
             case 0x24:
             case 0x25:
             case 0x26:
             case 0x27:
             case 0x28:
             case 0x29:
             case 0x2A:
             case 0x2B:
             case 0x2C:
             case 0x2D:
             case 0x2E:
             case 0x2F:
             case 0x30:
             case 0x31:
             case 0x32:
             case 0x33:
             case 0x34:
             case 0x35:
             case 0x36:
             case 0x37:
                 return sax->number_integer(static_cast<std::int8_t>(0x20 - 1 - current));
             case 0x38: // Negative integer (one-byte uint8_t follows)
             {
                 std::uint8_t number;
                 return get_number(input_format_t::cbor, number) and sax->number_integer(static_cast<number_integer_t>(-1) - number);
             }
             case 0x39: // Negative integer -1-n (two-byte uint16_t follows)
             {
                 std::uint16_t number;
                 return get_number(input_format_t::cbor, number) and sax->number_integer(static_cast<number_integer_t>(-1) - number);
             }
             case 0x3A: // Negative integer -1-n (four-byte uint32_t follows)
             {
                 std::uint32_t number;
                 return get_number(input_format_t::cbor, number) and sax->number_integer(static_cast<number_integer_t>(-1) - number);
             }
             case 0x3B: // Negative integer -1-n (eight-byte uint64_t follows)
             {
                 std::uint64_t number;
                 return get_number(input_format_t::cbor, number) and sax->number_integer(static_cast<number_integer_t>(-1)
                         - static_cast<number_integer_t>(number));
             }
             // UTF-8 string (0x00..0x17 bytes follow)
             case 0x60:
             case 0x61:
             case 0x62:
             case 0x63:
             case 0x64:
             case 0x65:
             case 0x66:
             case 0x67:
             case 0x68:
             case 0x69:
             case 0x6A:
             case 0x6B:
             case 0x6C:
             case 0x6D:
             case 0x6E:
             case 0x6F:
             case 0x70:
             case 0x71:
             case 0x72:
             case 0x73:
             case 0x74:
             case 0x75:
             case 0x76:
             case 0x77:
             case 0x78: // UTF-8 string (one-byte uint8_t for n follows)
             case 0x79: // UTF-8 string (two-byte uint16_t for n follow)
             case 0x7A: // UTF-8 string (four-byte uint32_t for n follow)
             case 0x7B: // UTF-8 string (eight-byte uint64_t for n follow)
             case 0x7F: // UTF-8 string (indefinite length)
             {
                 string_t s;
                 return get_cbor_string(s) and sax->string(s);
             }
             // array (0x00..0x17 data items follow)
             case 0x80:
             case 0x81:
             case 0x82:
             case 0x83:
             case 0x84:
             case 0x85:
             case 0x86:
             case 0x87:
             case 0x88:
             case 0x89:
             case 0x8A:
             case 0x8B:
             case 0x8C:
             case 0x8D:
             case 0x8E:
             case 0x8F:
             case 0x90:
             case 0x91:
             case 0x92:
             case 0x93:
             case 0x94:
             case 0x95:
             case 0x96:
             case 0x97:
                 return get_cbor_array(static_cast<std::size_t>(static_cast<unsigned int>(current) & 0x1Fu));
             case 0x98: // array (one-byte uint8_t for n follows)
             {
                 std::uint8_t len;
                 return get_number(input_format_t::cbor, len) and get_cbor_array(static_cast<std::size_t>(len));
             }
             case 0x99: // array (two-byte uint16_t for n follow)
             {
                 std::uint16_t len;
                 return get_number(input_format_t::cbor, len) and get_cbor_array(static_cast<std::size_t>(len));
             }
             case 0x9A: // array (four-byte uint32_t for n follow)
             {
                 std::uint32_t len;
                 return get_number(input_format_t::cbor, len) and get_cbor_array(static_cast<std::size_t>(len));
             }
             case 0x9B: // array (eight-byte uint64_t for n follow)
             {
                 std::uint64_t len;
                 return get_number(input_format_t::cbor, len) and get_cbor_array(static_cast<std::size_t>(len));
             }
             case 0x9F: // array (indefinite length)
                 return get_cbor_array(std::size_t(-1));
             // map (0x00..0x17 pairs of data items follow)
             case 0xA0:
             case 0xA1:
             case 0xA2:
             case 0xA3:
             case 0xA4:
             case 0xA5:
             case 0xA6:
             case 0xA7:
             case 0xA8:
             case 0xA9:
             case 0xAA:
             case 0xAB:
             case 0xAC:
             case 0xAD:
             case 0xAE:
             case 0xAF:
             case 0xB0:
             case 0xB1:
             case 0xB2:
             case 0xB3:
             case 0xB4:
             case 0xB5:
             case 0xB6:
             case 0xB7:
                 return get_cbor_object(static_cast<std::size_t>(static_cast<unsigned int>(current) & 0x1Fu));
             case 0xB8: // map (one-byte uint8_t for n follows)
             {
                 std::uint8_t len;
                 return get_number(input_format_t::cbor, len) and get_cbor_object(static_cast<std::size_t>(len));
             }
             case 0xB9: // map (two-byte uint16_t for n follow)
             {
                 std::uint16_t len;
                 return get_number(input_format_t::cbor, len) and get_cbor_object(static_cast<std::size_t>(len));
             }
             case 0xBA: // map (four-byte uint32_t for n follow)
             {
                 std::uint32_t len;
                 return get_number(input_format_t::cbor, len) and get_cbor_object(static_cast<std::size_t>(len));
             }
             case 0xBB: // map (eight-byte uint64_t for n follow)
             {
                 std::uint64_t len;
                 return get_number(input_format_t::cbor, len) and get_cbor_object(static_cast<std::size_t>(len));
             }
             case 0xBF: // map (indefinite length)
                 return get_cbor_object(std::size_t(-1));
             case 0xF4: // false
                 return sax->boolean(false);
             case 0xF5: // true
                 return sax->boolean(true);
             case 0xF6: // null
                 return sax->null();
             case 0xF9: // Half-Precision Float (two-byte IEEE 754)
             {
                 const int byte1_raw = get();
                 if (JSON_HEDLEY_UNLIKELY(not unexpect_eof(input_format_t::cbor, "number")))
                 {
                     return false;
                 }
                 const int byte2_raw = get();
                 if (JSON_HEDLEY_UNLIKELY(not unexpect_eof(input_format_t::cbor, "number")))
                 {
                     return false;
                 }
                 const auto byte1 = static_cast<unsigned char>(byte1_raw);
                 const auto byte2 = static_cast<unsigned char>(byte2_raw);
                 // code from RFC 7049, Appendix D, Figure 3:
                 // As half-precision floating-point numbers were only added
                 // to IEEE 754 in 2008, today's programming platforms often
                 // still only have limited support for them. It is very
                 // easy to include at least decoding support for them even
                 // without such support. An example of a small decoder for
                 // half-precision floating-point numbers in the C language
                 // is shown in Fig. 3.
                 const auto half = static_cast<unsigned int>((byte1 << 8u) + byte2);
                 const double val = [&half]
                 {
                     const int exp = (half >> 10u) & 0x1Fu;
                     const unsigned int mant = half & 0x3FFu;
                     assert(0 <= exp and exp <= 32);
                     assert(mant <= 1024);
                     switch (exp)
                     {
                         case 0:
                             return std::ldexp(mant, -24);
                         case 31:
                             return (mant == 0)
                             ? std::numeric_limits<double>::infinity()
                             : std::numeric_limits<double>::quiet_NaN();
                         default:
                             return std::ldexp(mant + 1024, exp - 25);
                     }
                 }();
                 return sax->number_float((half & 0x8000u) != 0
                                          ? static_cast<number_float_t>(-val)
                                          : static_cast<number_float_t>(val), "");
             }
             case 0xFA: // Single-Precision Float (four-byte IEEE 754)
             {
                 float number;
                 return get_number(input_format_t::cbor, number) and sax->number_float(static_cast<number_float_t>(number), "");
             }
             case 0xFB: // Double-Precision Float (eight-byte IEEE 754)
             {
                 double number;
                 return get_number(input_format_t::cbor, number) and sax->number_float(static_cast<number_float_t>(number), "");
             }
             default: // anything else (0xFF is handled inside the other types)
             {
                 auto last_token = get_token_string();
                 return sax->parse_error(chars_read, last_token, parse_error::create(112, chars_read, exception_message(input_format_t::cbor, "invalid byte: 0x" + last_token, "value")));
             }
         }
     }
References assert(), nlohmann::detail::cbor, nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_array(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_object(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_token_string(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof().
parse_msgpack_internal() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_msgpack_internal () inline private
Returns
whether a valid MessagePack value was passed to the SAX parser
Definition at line 876 of file binary_reader.hpp.
     {
         switch (get())
         {
             // EOF
             case std::char_traits<char>::eof():
                 return unexpect_eof(input_format_t::msgpack, "value");
             // positive fixint
             case 0x00:
             case 0x01:
             case 0x02:
             case 0x03:
             case 0x04:
             case 0x05:
             case 0x06:
             case 0x07:
             case 0x08:
             case 0x09:
             case 0x0A:
             case 0x0B:
             case 0x0C:
             case 0x0D:
             case 0x0E:
             case 0x0F:
             case 0x10:
             case 0x11:
             case 0x12:
             case 0x13:
             case 0x14:
             case 0x15:
             case 0x16:
             case 0x17:
             case 0x18:
             case 0x19:
             case 0x1A:
             case 0x1B:
             case 0x1C:
             case 0x1D:
             case 0x1E:
             case 0x1F:
             case 0x20:
             case 0x21:
             case 0x22:
             case 0x23:
             case 0x24:
             case 0x25:
             case 0x26:
             case 0x27:
             case 0x28:
             case 0x29:
             case 0x2A:
             case 0x2B:
             case 0x2C:
             case 0x2D:
             case 0x2E:
             case 0x2F:
             case 0x30:
             case 0x31:
             case 0x32:
             case 0x33:
             case 0x34:
             case 0x35:
             case 0x36:
             case 0x37:
             case 0x38:
             case 0x39:
             case 0x3A:
             case 0x3B:
             case 0x3C:
             case 0x3D:
             case 0x3E:
             case 0x3F:
             case 0x40:
             case 0x41:
             case 0x42:
             case 0x43:
             case 0x44:
             case 0x45:
             case 0x46:
             case 0x47:
             case 0x48:
             case 0x49:
             case 0x4A:
             case 0x4B:
             case 0x4C:
             case 0x4D:
             case 0x4E:
             case 0x4F:
             case 0x50:
             case 0x51:
             case 0x52:
             case 0x53:
             case 0x54:
             case 0x55:
             case 0x56:
             case 0x57:
             case 0x58:
             case 0x59:
             case 0x5A:
             case 0x5B:
             case 0x5C:
             case 0x5D:
             case 0x5E:
             case 0x5F:
             case 0x60:
             case 0x61:
             case 0x62:
             case 0x63:
             case 0x64:
             case 0x65:
             case 0x66:
             case 0x67:
             case 0x68:
             case 0x69:
             case 0x6A:
             case 0x6B:
             case 0x6C:
             case 0x6D:
             case 0x6E:
             case 0x6F:
             case 0x70:
             case 0x71:
             case 0x72:
             case 0x73:
             case 0x74:
             case 0x75:
             case 0x76:
             case 0x77:
             case 0x78:
             case 0x79:
             case 0x7A:
             case 0x7B:
             case 0x7C:
             case 0x7D:
             case 0x7E:
             case 0x7F:
                 return sax->number_unsigned(static_cast<number_unsigned_t>(current));
             // fixmap
             case 0x80:
             case 0x81:
             case 0x82:
             case 0x83:
             case 0x84:
             case 0x85:
             case 0x86:
             case 0x87:
             case 0x88:
             case 0x89:
             case 0x8A:
             case 0x8B:
             case 0x8C:
             case 0x8D:
             case 0x8E:
             case 0x8F:
                 return get_msgpack_object(static_cast<std::size_t>(static_cast<unsigned int>(current) & 0x0Fu));
             // fixarray
             case 0x90:
             case 0x91:
             case 0x92:
             case 0x93:
             case 0x94:
             case 0x95:
             case 0x96:
             case 0x97:
             case 0x98:
             case 0x99:
             case 0x9A:
             case 0x9B:
             case 0x9C:
             case 0x9D:
             case 0x9E:
             case 0x9F:
                 return get_msgpack_array(static_cast<std::size_t>(static_cast<unsigned int>(current) & 0x0Fu));
             // fixstr
             case 0xA0:
             case 0xA1:
             case 0xA2:
             case 0xA3:
             case 0xA4:
             case 0xA5:
             case 0xA6:
             case 0xA7:
             case 0xA8:
             case 0xA9:
             case 0xAA:
             case 0xAB:
             case 0xAC:
             case 0xAD:
             case 0xAE:
             case 0xAF:
             case 0xB0:
             case 0xB1:
             case 0xB2:
             case 0xB3:
             case 0xB4:
             case 0xB5:
             case 0xB6:
             case 0xB7:
             case 0xB8:
             case 0xB9:
             case 0xBA:
             case 0xBB:
             case 0xBC:
             case 0xBD:
             case 0xBE:
             case 0xBF:
             case 0xD9: // str 8
             case 0xDA: // str 16
             case 0xDB: // str 32
             {
                 string_t s;
                 return get_msgpack_string(s) and sax->string(s);
             }
             case 0xC0: // nil
                 return sax->null();
             case 0xC2: // false
                 return sax->boolean(false);
             case 0xC3: // true
                 return sax->boolean(true);
             case 0xCA: // float 32
             {
                 float number;
                 return get_number(input_format_t::msgpack, number) and sax->number_float(static_cast<number_float_t>(number), "");
             }
             case 0xCB: // float 64
             {
                 double number;
                 return get_number(input_format_t::msgpack, number) and sax->number_float(static_cast<number_float_t>(number), "");
             }
             case 0xCC: // uint 8
             {
                 std::uint8_t number;
                 return get_number(input_format_t::msgpack, number) and sax->number_unsigned(number);
             }
             case 0xCD: // uint 16
             {
                 std::uint16_t number;
                 return get_number(input_format_t::msgpack, number) and sax->number_unsigned(number);
             }
             case 0xCE: // uint 32
             {
                 std::uint32_t number;
                 return get_number(input_format_t::msgpack, number) and sax->number_unsigned(number);
             }
             case 0xCF: // uint 64
             {
                 std::uint64_t number;
                 return get_number(input_format_t::msgpack, number) and sax->number_unsigned(number);
             }
             case 0xD0: // int 8
             {
                 std::int8_t number;
                 return get_number(input_format_t::msgpack, number) and sax->number_integer(number);
             }
             case 0xD1: // int 16
             {
                 std::int16_t number;
                 return get_number(input_format_t::msgpack, number) and sax->number_integer(number);
             }
             case 0xD2: // int 32
             {
                 std::int32_t number;
                 return get_number(input_format_t::msgpack, number) and sax->number_integer(number);
             }
             case 0xD3: // int 64
             {
                 std::int64_t number;
                 return get_number(input_format_t::msgpack, number) and sax->number_integer(number);
             }
             case 0xDC: // array 16
             {
                 std::uint16_t len;
                 return get_number(input_format_t::msgpack, len) and get_msgpack_array(static_cast<std::size_t>(len));
             }
             case 0xDD: // array 32
             {
                 std::uint32_t len;
                 return get_number(input_format_t::msgpack, len) and get_msgpack_array(static_cast<std::size_t>(len));
             }
             case 0xDE: // map 16
             {
                 std::uint16_t len;
                 return get_number(input_format_t::msgpack, len) and get_msgpack_object(static_cast<std::size_t>(len));
             }
             case 0xDF: // map 32
             {
                 std::uint32_t len;
                 return get_number(input_format_t::msgpack, len) and get_msgpack_object(static_cast<std::size_t>(len));
             }
             // negative fixint
             case 0xE0:
             case 0xE1:
             case 0xE2:
             case 0xE3:
             case 0xE4:
             case 0xE5:
             case 0xE6:
             case 0xE7:
             case 0xE8:
             case 0xE9:
             case 0xEA:
             case 0xEB:
             case 0xEC:
             case 0xED:
             case 0xEE:
             case 0xEF:
             case 0xF0:
             case 0xF1:
             case 0xF2:
             case 0xF3:
             case 0xF4:
             case 0xF5:
             case 0xF6:
             case 0xF7:
             case 0xF8:
             case 0xF9:
             case 0xFA:
             case 0xFB:
             case 0xFC:
             case 0xFD:
             case 0xFE:
             case 0xFF:
                 return sax->number_integer(static_cast<std::int8_t>(current));
             default: // anything else
             {
                 auto last_token = get_token_string();
                 return sax->parse_error(chars_read, last_token, parse_error::create(112, chars_read, exception_message(input_format_t::msgpack, "invalid byte: 0x" + last_token, "value")));
             }
         }
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_array(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_object(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_token_string(), nlohmann::detail::msgpack, nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_array(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_object(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax_parse().
parse_msgpack_internal() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_msgpack_internal () inline private
Returns
whether a valid MessagePack value was passed to the SAX parser
Definition at line 6016 of file json.hpp.
     {
         switch (get())
         {
             // EOF
             case std::char_traits<char>::eof():
                 return unexpect_eof(input_format_t::msgpack, "value");
             // positive fixint
             case 0x00:
             case 0x01:
             case 0x02:
             case 0x03:
             case 0x04:
             case 0x05:
             case 0x06:
             case 0x07:
             case 0x08:
             case 0x09:
             case 0x0A:
             case 0x0B:
             case 0x0C:
             case 0x0D:
             case 0x0E:
             case 0x0F:
             case 0x10:
             case 0x11:
             case 0x12:
             case 0x13:
             case 0x14:
             case 0x15:
             case 0x16:
             case 0x17:
             case 0x18:
             case 0x19:
             case 0x1A:
             case 0x1B:
             case 0x1C:
             case 0x1D:
             case 0x1E:
             case 0x1F:
             case 0x20:
             case 0x21:
             case 0x22:
             case 0x23:
             case 0x24:
             case 0x25:
             case 0x26:
             case 0x27:
             case 0x28:
             case 0x29:
             case 0x2A:
             case 0x2B:
             case 0x2C:
             case 0x2D:
             case 0x2E:
             case 0x2F:
             case 0x30:
             case 0x31:
             case 0x32:
             case 0x33:
             case 0x34:
             case 0x35:
             case 0x36:
             case 0x37:
             case 0x38:
             case 0x39:
             case 0x3A:
             case 0x3B:
             case 0x3C:
             case 0x3D:
             case 0x3E:
             case 0x3F:
             case 0x40:
             case 0x41:
             case 0x42:
             case 0x43:
             case 0x44:
             case 0x45:
             case 0x46:
             case 0x47:
             case 0x48:
             case 0x49:
             case 0x4A:
             case 0x4B:
             case 0x4C:
             case 0x4D:
             case 0x4E:
             case 0x4F:
             case 0x50:
             case 0x51:
             case 0x52:
             case 0x53:
             case 0x54:
             case 0x55:
             case 0x56:
             case 0x57:
             case 0x58:
             case 0x59:
             case 0x5A:
             case 0x5B:
             case 0x5C:
             case 0x5D:
             case 0x5E:
             case 0x5F:
             case 0x60:
             case 0x61:
             case 0x62:
             case 0x63:
             case 0x64:
             case 0x65:
             case 0x66:
             case 0x67:
             case 0x68:
             case 0x69:
             case 0x6A:
             case 0x6B:
             case 0x6C:
             case 0x6D:
             case 0x6E:
             case 0x6F:
             case 0x70:
             case 0x71:
             case 0x72:
             case 0x73:
             case 0x74:
             case 0x75:
             case 0x76:
             case 0x77:
             case 0x78:
             case 0x79:
             case 0x7A:
             case 0x7B:
             case 0x7C:
             case 0x7D:
             case 0x7E:
             case 0x7F:
                 return sax->number_unsigned(static_cast<number_unsigned_t>(current));
             // fixmap
             case 0x80:
             case 0x81:
             case 0x82:
             case 0x83:
             case 0x84:
             case 0x85:
             case 0x86:
             case 0x87:
             case 0x88:
             case 0x89:
             case 0x8A:
             case 0x8B:
             case 0x8C:
             case 0x8D:
             case 0x8E:
             case 0x8F:
                 return get_msgpack_object(static_cast<std::size_t>(static_cast<unsigned int>(current) & 0x0Fu));
             // fixarray
             case 0x90:
             case 0x91:
             case 0x92:
             case 0x93:
             case 0x94:
             case 0x95:
             case 0x96:
             case 0x97:
             case 0x98:
             case 0x99:
             case 0x9A:
             case 0x9B:
             case 0x9C:
             case 0x9D:
             case 0x9E:
             case 0x9F:
                 return get_msgpack_array(static_cast<std::size_t>(static_cast<unsigned int>(current) & 0x0Fu));
             // fixstr
             case 0xA0:
             case 0xA1:
             case 0xA2:
             case 0xA3:
             case 0xA4:
             case 0xA5:
             case 0xA6:
             case 0xA7:
             case 0xA8:
             case 0xA9:
             case 0xAA:
             case 0xAB:
             case 0xAC:
             case 0xAD:
             case 0xAE:
             case 0xAF:
             case 0xB0:
             case 0xB1:
             case 0xB2:
             case 0xB3:
             case 0xB4:
             case 0xB5:
             case 0xB6:
             case 0xB7:
             case 0xB8:
             case 0xB9:
             case 0xBA:
             case 0xBB:
             case 0xBC:
             case 0xBD:
             case 0xBE:
             case 0xBF:
             case 0xD9: // str 8
             case 0xDA: // str 16
             case 0xDB: // str 32
             {
                 string_t s;
                 return get_msgpack_string(s) and sax->string(s);
             }
             case 0xC0: // nil
                 return sax->null();
             case 0xC2: // false
                 return sax->boolean(false);
             case 0xC3: // true
                 return sax->boolean(true);
             case 0xCA: // float 32
             {
                 float number;
                 return get_number(input_format_t::msgpack, number) and sax->number_float(static_cast<number_float_t>(number), "");
             }
             case 0xCB: // float 64
             {
                 double number;
                 return get_number(input_format_t::msgpack, number) and sax->number_float(static_cast<number_float_t>(number), "");
             }
             case 0xCC: // uint 8
             {
                 std::uint8_t number;
                 return get_number(input_format_t::msgpack, number) and sax->number_unsigned(number);
             }
             case 0xCD: // uint 16
             {
                 std::uint16_t number;
                 return get_number(input_format_t::msgpack, number) and sax->number_unsigned(number);
             }
             case 0xCE: // uint 32
             {
                 std::uint32_t number;
                 return get_number(input_format_t::msgpack, number) and sax->number_unsigned(number);
             }
             case 0xCF: // uint 64
             {
                 std::uint64_t number;
                 return get_number(input_format_t::msgpack, number) and sax->number_unsigned(number);
             }
             case 0xD0: // int 8
             {
                 std::int8_t number;
                 return get_number(input_format_t::msgpack, number) and sax->number_integer(number);
             }
             case 0xD1: // int 16
             {
                 std::int16_t number;
                 return get_number(input_format_t::msgpack, number) and sax->number_integer(number);
             }
             case 0xD2: // int 32
             {
                 std::int32_t number;
                 return get_number(input_format_t::msgpack, number) and sax->number_integer(number);
             }
             case 0xD3: // int 64
             {
                 std::int64_t number;
                 return get_number(input_format_t::msgpack, number) and sax->number_integer(number);
             }
             case 0xDC: // array 16
             {
                 std::uint16_t len;
                 return get_number(input_format_t::msgpack, len) and get_msgpack_array(static_cast<std::size_t>(len));
             }
             case 0xDD: // array 32
             {
                 std::uint32_t len;
                 return get_number(input_format_t::msgpack, len) and get_msgpack_array(static_cast<std::size_t>(len));
             }
             case 0xDE: // map 16
             {
                 std::uint16_t len;
                 return get_number(input_format_t::msgpack, len) and get_msgpack_object(static_cast<std::size_t>(len));
             }
             case 0xDF: // map 32
             {
                 std::uint32_t len;
                 return get_number(input_format_t::msgpack, len) and get_msgpack_object(static_cast<std::size_t>(len));
             }
             // negative fixint
             case 0xE0:
             case 0xE1:
             case 0xE2:
             case 0xE3:
             case 0xE4:
             case 0xE5:
             case 0xE6:
             case 0xE7:
             case 0xE8:
             case 0xE9:
             case 0xEA:
             case 0xEB:
             case 0xEC:
             case 0xED:
             case 0xEE:
             case 0xEF:
             case 0xF0:
             case 0xF1:
             case 0xF2:
             case 0xF3:
             case 0xF4:
             case 0xF5:
             case 0xF6:
             case 0xF7:
             case 0xF8:
             case 0xF9:
             case 0xFA:
             case 0xFB:
             case 0xFC:
             case 0xFD:
             case 0xFE:
             case 0xFF:
                 return sax->number_integer(static_cast<std::int8_t>(current));
             default: // anything else
             {
                 auto last_token = get_token_string();
                 return sax->parse_error(chars_read, last_token, parse_error::create(112, chars_read, exception_message(input_format_t::msgpack, "invalid byte: 0x" + last_token, "value")));
             }
         }
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_array(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_object(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_token_string(), nlohmann::detail::msgpack, nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof().
parse_ubjson_internal() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_ubjson_internal (const bool get_char = true) inline private
Parameters
[in] get_char whether a new character should be retrieved from the input (true, default) or whether the last read character should be considered instead
Returns
whether a valid UBJSON value was passed to the SAX parser
Definition at line 1375 of file binary_reader.hpp.
     {
         return get_ubjson_value(get_char ? get_ignore_noop() : current);
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ignore_noop(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_value().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_array(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_object(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax_parse().
parse_ubjson_internal() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_ubjson_internal (const bool get_char = true) inline private
Parameters
[in] get_char whether a new character should be retrieved from the input (true, default) or whether the last read character should be considered instead
Returns
whether a valid UBJSON value was passed to the SAX parser
Definition at line 6515 of file json.hpp.
     {
         return get_ubjson_value(get_char ? get_ignore_noop() : current);
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ignore_noop(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_value().
sax_parse() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax_parse (const input_format_t format, json_sax_t * sax_, const bool strict = true) inline
Parameters
[in] format the binary format to parse
[in] sax_ a SAX event processor
[in] strict whether to expect the input to be consumed completed
Returns
Definition at line 70 of file binary_reader.hpp.
     {
         sax = sax_;
         bool result = false;
         switch (format)
         {
             case input_format_t::bson:
                 result = parse_bson_internal();
                 break;
             case input_format_t::cbor:
                 result = parse_cbor_internal();
                 break;
             case input_format_t::msgpack:
                 result = parse_msgpack_internal();
                 break;
             case input_format_t::ubjson:
                 result = parse_ubjson_internal();
                 break;
             default:            // LCOV_EXCL_LINE
                 assert(false);  // LCOV_EXCL_LINE
         }
         // strict mode: next byte must be EOF
         if (result and strict)
         {
             if (format == input_format_t::ubjson)
             {
                 get_ignore_noop();
             }
             else
             {
                 get();
             }
             if (JSON_HEDLEY_UNLIKELY(current != std::char_traits<char>::eof()))
             {
                 return sax->parse_error(chars_read, get_token_string(),
                                         parse_error::create(110, chars_read, exception_message(format, "expected end of input; last byte: 0x" + get_token_string(), "value")));
             }
         }
         return result;
     }
References assert(), nlohmann::detail::bson, nlohmann::detail::cbor, nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ignore_noop(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_token_string(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::msgpack, nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_internal(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_cbor_internal(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_msgpack_internal(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_ubjson_internal(), result, nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax, nlohmann::detail::strict, and nlohmann::detail::ubjson.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::sax_parse().
sax_parse() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax_parse (const input_format_t format, json_sax_t * sax_, const bool strict = true) inline
Parameters
[in] format the binary format to parse
[in] sax_ a SAX event processor
[in] strict whether to expect the input to be consumed completed
Returns
Definition at line 5210 of file json.hpp.
     {
         sax = sax_;
         bool result = false;
         switch (format)
         {
             case input_format_t::bson:
                 result = parse_bson_internal();
                 break;
             case input_format_t::cbor:
                 result = parse_cbor_internal();
                 break;
             case input_format_t::msgpack:
                 result = parse_msgpack_internal();
                 break;
             case input_format_t::ubjson:
                 result = parse_ubjson_internal();
                 break;
             default:            // LCOV_EXCL_LINE
                 assert(false);  // LCOV_EXCL_LINE
         }
         // strict mode: next byte must be EOF
         if (result and strict)
         {
             if (format == input_format_t::ubjson)
             {
                 get_ignore_noop();
             }
             else
             {
                 get();
             }
             if (JSON_HEDLEY_UNLIKELY(current != std::char_traits<char>::eof()))
             {
                 return sax->parse_error(chars_read, get_token_string(),
                                         parse_error::create(110, chars_read, exception_message(format, "expected end of input; last byte: 0x" + get_token_string(), "value")));
             }
         }
         return result;
     }
References assert(), nlohmann::detail::bson, nlohmann::detail::cbor, nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ignore_noop(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_token_string(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::msgpack, nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_internal(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_cbor_internal(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_msgpack_internal(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_ubjson_internal(), result, nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax, nlohmann::detail::strict, and nlohmann::detail::ubjson.
unexpect_eof() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof (const input_format_t format, const char * context) const inline private
Parameters
[in] format the current format (for diagnostics)
[in] context further context information (for diagnostics)
Returns
whether the last read character is not EOF
Definition at line 1909 of file binary_reader.hpp.
     {
         if (JSON_HEDLEY_UNLIKELY(current == std::char_traits<char>::eof()))
         {
             return sax->parse_error(chars_read, "<end of file>",
                                     parse_error::create(110, chars_read, exception_message(format, "unexpected end of input", context)));
         }
         return true;
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::exception_message(), JSON_HEDLEY_UNLIKELY, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_bson_cstr(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_size_type(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_value(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_element_list(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_cbor_internal(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_msgpack_internal().
unexpect_eof() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof (const input_format_t format, const char * context) const inline private
Parameters
[in] format the current format (for diagnostics)
[in] context further context information (for diagnostics)
Returns
whether the last read character is not EOF
Definition at line 7049 of file json.hpp.
     {
         if (JSON_HEDLEY_UNLIKELY(current == std::char_traits<char>::eof()))
         {
             return sax->parse_error(chars_read, "<end of file>",
                                     parse_error::create(110, chars_read, exception_message(format, "unexpected end of input", context)));
         }
         return true;
     }
References nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, SAX >::exception_message(), JSON_HEDLEY_UNLIKELY, and nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax.
Member Data Documentation
chars_read
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> std::size_t nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read = 0 private
the number of characters read
Definition at line 1974 of file binary_reader.hpp.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_bson_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_size_type(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_size_value(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_value(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_element_list(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_cbor_internal(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_msgpack_internal(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax_parse(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof().
current
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> int nlohmann::detail::binary_reader< BasicJsonType, SAX >::current = std::char_traits<char>::eof() private
the current character
Definition at line 1971 of file binary_reader.hpp.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_bson_cstr(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ignore_noop(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_token_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_array(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_object(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_size_type(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_value(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_cbor_internal(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_msgpack_internal(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_ubjson_internal(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax_parse(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof().
ia
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> input_adapter_t nlohmann::detail::binary_reader< BasicJsonType, SAX >::ia = nullptr private
input adapter
Definition at line 1968 of file binary_reader.hpp.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::binary_reader(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::get().
is_little_endian
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> const bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::is_little_endian = little_endianess() private
whether we can assume little endianess
Definition at line 1977 of file binary_reader.hpp.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_number().
sax
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> json_sax_t * nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax = nullptr private
the SAX parser
Definition at line 1980 of file binary_reader.hpp.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_bson_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_array(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_object(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_array(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_object(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_array(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_object(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_size_type(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_size_value(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_value(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_array(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_element_internal(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_element_list(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_bson_internal(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_cbor_internal(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_msgpack_internal(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax_parse(), and nlohmann::detail::binary_reader< BasicJsonType, SAX >::unexpect_eof().
The documentation for this class was generated from the following files:
mc_orchestrator/json-3.7.3/include/nlohmann/detail/input/binary_reader.hpp
mc_orchestrator/json-3.7.3/single_include/nlohmann/json.hpp