Mixed Criticality Orchestrator: httplib::detail::MultipartFormDataParser Class Reference
httplib::detail::MultipartFormDataParser Class Reference
#include <httplib.h>
Public Member Functions
MultipartFormDataParser ()=default
void set_boundary (std::string &&boundary)
bool is_valid () const
bool parse (const char *buf, size_t n, const ContentReceiver &content_callback, const MultipartContentHeader &header_callback)
Private Member Functions
void clear_file_info ()
bool start_with_case_ignore (const std::string &a, const std::string &b) const
bool start_with (const std::string &a, size_t spos, size_t epos, const std::string &b) const
size_t buf_size () const
const char * buf_data () const
std::string buf_head (size_t l) const
bool buf_start_with (const std::string &s) const
size_t buf_find (const std::string &s) const
void buf_append (const char *data, size_t n)
void buf_erase (size_t size)
Private Attributes
const std::string dash_ = "--"
const std::string crlf_ = "\r\n"
std::string boundary_
std::string dash_boundary_crlf_
std::string crlf_dash_boundary_
size_t state_ = 0
bool is_valid_ = false
MultipartFormData file_
std::string buf_
size_t buf_spos_ = 0
size_t buf_epos_ = 0
Detailed Description
Definition at line 4403 of file httplib.h.
Constructor & Destructor Documentation
MultipartFormDataParser()
httplib::detail::MultipartFormDataParser::MultipartFormDataParser () default
Member Function Documentation
buf_append()
void httplib::detail::MultipartFormDataParser::buf_append (const char * data, size_t n) inline private
Definition at line 4621 of file httplib.h.
{
     auto remaining_size = buf_size();
     if (remaining_size > 0 && buf_spos_ > 0) {
       for (size_t i = 0; i < remaining_size; i++) {
         buf_[i] = buf_[buf_spos_ + i];
       }
     }
     buf_spos_ = 0;
     buf_epos_ = remaining_size;
     if (remaining_size + n > buf_.size()) { buf_.resize(remaining_size + n); }
     for (size_t i = 0; i < n; i++) {
       buf_[buf_epos_ + i] = data[i];
     }
     buf_epos_ += n;
   }
References n.
buf_data()
const char* httplib::detail::MultipartFormDataParser::buf_data () const inline private
Definition at line 4590 of file httplib.h.
 { return &buf_[buf_spos_]; }
buf_erase()
void httplib::detail::MultipartFormDataParser::buf_erase (size_t size) inline private
Definition at line 4639 of file httplib.h.
 { buf_spos_ += size; }
buf_find()
size_t httplib::detail::MultipartFormDataParser::buf_find (const std::string & s) const inline private
Definition at line 4598 of file httplib.h.
{
     auto c = s.front();
     size_t off = buf_spos_;
     while (off < buf_epos_) {
       auto pos = off;
       while (true) {
         if (pos == buf_epos_) { return buf_size(); }
         if (buf_[pos] == c) { break; }
         pos++;
       }
       auto remaining_size = buf_epos_ - pos;
       if (s.size() > remaining_size) { return buf_size(); }
       if (start_with(buf_, pos, buf_epos_, s)) { return pos - buf_spos_; }
       off = pos + 1;
     }
     return buf_size();
   }
References c.
buf_head()
std::string httplib::detail::MultipartFormDataParser::buf_head (size_t l) const inline private
Definition at line 4592 of file httplib.h.
 { return buf_.substr(buf_spos_, l); }
buf_size()
size_t httplib::detail::MultipartFormDataParser::buf_size () const inline private
Definition at line 4588 of file httplib.h.
 { return buf_epos_ - buf_spos_; }
buf_start_with()
bool httplib::detail::MultipartFormDataParser::buf_start_with (const std::string & s) const inline private
Definition at line 4594 of file httplib.h.
{
     return start_with(buf_, buf_spos_, buf_epos_, s);
   }
clear_file_info()
void httplib::detail::MultipartFormDataParser::clear_file_info () inline private
Definition at line 4553 of file httplib.h.
{
     file_.name.clear();
     file_.filename.clear();
     file_.content_type.clear();
   }
is_valid()
bool httplib::detail::MultipartFormDataParser::is_valid () const inline
Definition at line 4413 of file httplib.h.
 { return is_valid_; }
Referenced by httplib::Server::read_content_core().
parse()
bool httplib::detail::MultipartFormDataParser::parse (const char * buf, size_t n, const ContentReceiver & content_callback, const MultipartContentHeader & header_callback) inline
Definition at line 4415 of file httplib.h.
{
     buf_append(buf, n);
     while (buf_size() > 0) {
       switch (state_) {
       case 0: { // Initial boundary
         buf_erase(buf_find(dash_boundary_crlf_));
         if (dash_boundary_crlf_.size() > buf_size()) { return true; }
         if (!buf_start_with(dash_boundary_crlf_)) { return false; }
         buf_erase(dash_boundary_crlf_.size());
         state_ = 1;
         break;
       }
       case 1: { // New entry
         clear_file_info();
         state_ = 2;
         break;
       }
       case 2: { // Headers
         auto pos = buf_find(crlf_);
         if (pos > CPPHTTPLIB_HEADER_MAX_LENGTH) { return false; }
         while (pos < buf_size()) {
           // Empty line
           if (pos == 0) {
             if (!header_callback(file_)) {
               is_valid_ = false;
               return false;
             }
             buf_erase(crlf_.size());
             state_ = 3;
             break;
           }
           const auto header = buf_head(pos);
           if (!parse_header(header.data(), header.data() + header.size(),
                             [&](std::string &&, std::string &&) {})) {
             is_valid_ = false;
             return false;
           }
           static const std::string header_content_type = "Content-Type:";
           if (start_with_case_ignore(header, header_content_type)) {
             file_.content_type =
                 trim_copy(header.substr(header_content_type.size()));
           } else {
             static const std::regex re_content_disposition(
                 R"~(^Content-Disposition:\s*form-data;\s*(.*)$)~",
                 std::regex_constants::icase);
             std::smatch m;
             if (std::regex_match(header, m, re_content_disposition)) {
               Params params;
               parse_disposition_params(m[1], params);
               auto it = params.find("name");
               if (it != params.end()) {
                 file_.name = it->second;
               } else {
                 is_valid_ = false;
                 return false;
               }
               it = params.find("filename");
               if (it != params.end()) { file_.filename = it->second; }
               it = params.find("filename*");
               if (it != params.end()) {
                 // Only allow UTF-8 enconnding...
                 static const std::regex re_rfc5987_encoding(
                     R"~(^UTF-8''(.+?)$)~", std::regex_constants::icase);
                 std::smatch m2;
                 if (std::regex_match(it->second, m2, re_rfc5987_encoding)) {
                   file_.filename = decode_url(m2[1], false); // override...
                 } else {
                   is_valid_ = false;
                   return false;
                 }
               }
             }
           }
           buf_erase(pos + crlf_.size());
           pos = buf_find(crlf_);
         }
         if (state_ != 3) { return true; }
         break;
       }
       case 3: { // Body
         if (crlf_dash_boundary_.size() > buf_size()) { return true; }
         auto pos = buf_find(crlf_dash_boundary_);
         if (pos < buf_size()) {
           if (!content_callback(buf_data(), pos)) {
             is_valid_ = false;
             return false;
           }
           buf_erase(pos + crlf_dash_boundary_.size());
           state_ = 4;
         } else {
           auto len = buf_size() - crlf_dash_boundary_.size();
           if (len > 0) {
             if (!content_callback(buf_data(), len)) {
               is_valid_ = false;
               return false;
             }
             buf_erase(len);
           }
           return true;
         }
         break;
       }
       case 4: { // Boundary
         if (crlf_.size() > buf_size()) { return true; }
         if (buf_start_with(crlf_)) {
           buf_erase(crlf_.size());
           state_ = 1;
         } else {
           if (dash_.size() > buf_size()) { return true; }
           if (buf_start_with(dash_)) {
             buf_erase(dash_.size());
             is_valid_ = true;
             buf_erase(buf_size()); // Remove epilogue
           } else {
             return true;
           }
         }
         break;
       }
       }
     }
     return true;
   }
References CPPHTTPLIB_HEADER_MAX_LENGTH, httplib::detail::decode_url(), n, httplib::detail::parse_disposition_params(), httplib::detail::parse_header(), and httplib::detail::trim_copy().
Referenced by httplib::Server::read_content_core().
set_boundary()
void httplib::detail::MultipartFormDataParser::set_boundary (std::string && boundary) inline
Definition at line 4407 of file httplib.h.
{
     boundary_ = boundary;
     dash_boundary_crlf_ = dash_ + boundary_ + crlf_;
     crlf_dash_boundary_ = crlf_ + dash_ + boundary_;
   }
Referenced by httplib::Server::read_content_core().
start_with()
bool httplib::detail::MultipartFormDataParser::start_with (const std::string & a, size_t spos, size_t epos, const std::string & b) const inline private
Definition at line 4579 of file httplib.h.
{
     if (epos - spos < b.size()) { return false; }
     for (size_t i = 0; i < b.size(); i++) {
       if (a[i + spos] != b[i]) { return false; }
     }
     return true;
   }
start_with_case_ignore()
bool httplib::detail::MultipartFormDataParser::start_with_case_ignore (const std::string & a, const std::string & b) const inline private
Definition at line 4559 of file httplib.h.
{
     if (a.size() < b.size()) { return false; }
     for (size_t i = 0; i < b.size(); i++) {
       if (::tolower(a[i]) != ::tolower(b[i])) { return false; }
     }
     return true;
   }
Member Data Documentation
boundary_
std::string httplib::detail::MultipartFormDataParser::boundary_ private
Definition at line 4570 of file httplib.h.
buf_
std::string httplib::detail::MultipartFormDataParser::buf_ private
Definition at line 4641 of file httplib.h.
buf_epos_
size_t httplib::detail::MultipartFormDataParser::buf_epos_ = 0 private
Definition at line 4643 of file httplib.h.
buf_spos_
size_t httplib::detail::MultipartFormDataParser::buf_spos_ = 0 private
Definition at line 4642 of file httplib.h.
crlf_
const std::string httplib::detail::MultipartFormDataParser::crlf_ = "\r\n" private
Definition at line 4569 of file httplib.h.
crlf_dash_boundary_
std::string httplib::detail::MultipartFormDataParser::crlf_dash_boundary_ private
Definition at line 4572 of file httplib.h.
dash_
const std::string httplib::detail::MultipartFormDataParser::dash_ = "--" private
Definition at line 4568 of file httplib.h.
dash_boundary_crlf_
std::string httplib::detail::MultipartFormDataParser::dash_boundary_crlf_ private
Definition at line 4571 of file httplib.h.
file_
MultipartFormData httplib::detail::MultipartFormDataParser::file_ private
Definition at line 4576 of file httplib.h.
is_valid_
bool httplib::detail::MultipartFormDataParser::is_valid_ = false private
Definition at line 4575 of file httplib.h.
state_
size_t httplib::detail::MultipartFormDataParser::state_ = 0 private
Definition at line 4574 of file httplib.h.
The documentation for this class was generated from the following file:
mc_orchestrator/httplib/httplib.h