Mixed Criticality Orchestrator: UserAppControlHandler Class Reference
UserAppControlHandler Class Reference
UserAppControlHandler is to handle User App control requests from Infotainment and Vehicle State UI.
#include <mco_user_app_control_handler.hpp>
Public Member Functions
void Init ()
Initialize User App Control Handler.
bool PlayQmApp (const std::string &app)
Play QM App selected by User from Infotainment UI.
bool StopQmApp (const std::string &app)
Stop QM App selected by User from Infotainment UI.
bool PlayAsilApp (const std::string &app)
Unpause ASIL App selected by User from Vehicle State UI.
bool StopAsilApp (const std::string &app)
Pause ASIL App selected by User from Vehicle State UI.
Static Public Member Functions
static UserAppControlHandler & GetInstance ()
Public static method getInstance(). This function is.
Private Member Functions
UserAppControlHandler ()=default
Define constructor in the private section to make this class as singleton.
~UserAppControlHandler ()=default
Define destructor in private section, so no one can delete the instance of this class.
UserAppControlHandler (const UserAppControlHandler &obj)
Define copy constructor in the private section, so that no one can voilate the singleton policy of this class.
void operator= (const UserAppControlHandler &obj)
Define assignment operator in the private section, so that no one can voilate the singleton policy of this class.
Detailed Description
UserAppControlHandler is to handle User App control requests from Infotainment and Vehicle State UI.
Definition at line 10 of file mco_user_app_control_handler.hpp.
Constructor & Destructor Documentation
UserAppControlHandler() [1/2]
UserAppControlHandler::UserAppControlHandler () private default
Define constructor in the private section to make this class as singleton.
~UserAppControlHandler()
UserAppControlHandler::~UserAppControlHandler () private default
Define destructor in private section, so no one can delete the instance of this class.
UserAppControlHandler() [2/2]
UserAppControlHandler::UserAppControlHandler (const UserAppControlHandler & obj) inline private
Define copy constructor in the private section, so that no one can voilate the singleton policy of this class.
Definition at line 20 of file mco_user_app_control_handler.hpp.
 {}
Member Function Documentation
GetInstance()
UserAppControlHandler & UserAppControlHandler::GetInstance () static
Public static method getInstance(). This function is.
Definition at line 26 of file mco_user_app_control_handler.cpp.
 {
     static UserAppControlHandler self{};
     return self;
 }
Referenced by main(), and update_qm_available_resource().
Init()
void UserAppControlHandler::Init ()
Initialize User App Control Handler.
Definition at line 32 of file mco_user_app_control_handler.cpp.
 {
     while (true){
         string data = DatabaseHandler::GetInstance().ReadStringData(infotainment_selection);
         if(!data.empty()){
             try {
                 json jsonObject = json::parse(data);
                 std::string action = jsonObject.value("action", "");
                 std::string app = jsonObject.value("app", "");
                 if(action == "play"){
                         if (PlayQmApp(app)) {
                             cout << "Successfully played QM App: " << app << endl;
                         } else {
                             cout << "Failed to play QM App: " << app << endl;
                         }
                 } else if(action == "stop"){
                     if (StopQmApp(app)) {
                         cout << "Successfully stopped QM App: " << app << endl;
                     } else {
                         cout << "Failed to stop QM App: " << app << endl;
                     }
                 }
             } catch (const json::parse_error& e) {
                 cout << "JSON parse error: " << e.what() << endl;
             } catch (const json::type_error& e) {
                 cout << "JSON type error: " << e.what() << endl;
             } catch (const std::exception& e) {
                 cout << "Error: " << e.what() << endl;
             }
         }
         std::this_thread::sleep_for(std::chrono::seconds(1));
         data = DatabaseHandler::GetInstance().ReadStringData(vehiclestate_selection);
         if(!data.empty()){
             try {
                 json jsonObject = json::parse(data);
                 std::string action = jsonObject.value("action", "");
                 std::string app = jsonObject.value("app", "");
                 if(action == "play"){
                     if (PlayAsilApp(app)) {
                         cout << "Successfully started ASIL App: " << app << endl;
                     } else {
                         cout << "Failed to start ASIL App: " << app << endl;
                     }
                 } else if(action == "stop"){
                     if (StopAsilApp(app)) {
                         cout << "Successfully stopped ASIL App: " << app << endl;
                     } else {
                         cout << "Failed to stop ASIL App: " << app << endl;
                     }
                 }
             } catch (const json::parse_error& e) {
                 cout << "JSON parse error: " << e.what() << endl;
             } catch (const json::type_error& e) {
                 cout << "JSON type error: " << e.what() << endl;
             } catch (const std::exception& e) {
                 cout << "Error: " << e.what() << endl;
             }
         }
         // Monitor vehicle mode
         data = DatabaseHandler::GetInstance().ReadStringData(vehicle_drive_mode);
         if(data == "drive"){
                 cout << "Vehicle mode is : " << data << endl;
                 allocateQmResources(QM_ALLOCATION_DRIVE_STATE);
                 update_qm_available_resource(data);
                 //stop all running asil apps to stop rear camera
                 list<string> running_apps = DatabaseHandler::GetInstance().ReadListData(kAsilRunningApps);
                 for (const auto& app : running_apps) {
                     if(StopAsilApp(app)){
                         cout << "Successfully stopped ASIL App" << endl;
                     } else {
                         cout << "Failed to stop ASIL Apps" << endl;
                     }
                 }
                 //play driving asil apps
                 list<string> available_apps = DatabaseHandler::GetInstance().ReadListData(kAsilBAvailableApps);
                 for (const auto& app : available_apps) {
                     if (app == "rearcamera") {
                         continue; // Skip the rearcamera app
                     }
                     if(PlayAsilApp(app)){
                         cout << "Successfully started ASIL App" << endl;
                     } else {
                         cout << "Failed to start ASIL Apps" << endl;
                     }
                 }
                 // DatabaseHandler::GetInstance().AddData(resource_management_log, global_log_message);
                 // usleep(2000000);
                 // DatabaseHandler::GetInstance().AddData(resource_management_log, "");
                 json jsonObject= json::object();
                 DatabaseHandler::GetInstance().SaveData(vehicle_drive_mode, jsonObject);
         } else if(data == "park"){
                 cout << "Vehicle mode is : " << data << endl;
                 allocateQmResources(QM_ALLOCATION_PARK_STATE);
                 update_qm_available_resource(data) ;
                 list<string> running_apps = DatabaseHandler::GetInstance().ReadListData(kAsilRunningApps);
                 for (const auto& app : running_apps) {
                     if(StopAsilApp(app)){
                         cout << "Successfully stopped ASIL App" << endl;
                     } else {
                         cout << "Failed to stop ASIL Apps" << endl;
                     }
                 }
                 json jsonObject= json::object();
                 DatabaseHandler::GetInstance().SaveData(vehicle_drive_mode, jsonObject);
         } else if(data == "reverse"){
             cout << "Vehicle mode is : " << data << endl;
             allocateQmResources(QM_ALLOCATION_DRIVE_STATE);
             update_qm_available_resource(data);
             //Stop all running apps
             list<string> running_apps = DatabaseHandler::GetInstance().ReadListData(kAsilRunningApps);
             for (const auto& app : running_apps) {
                 if(StopAsilApp(app)){
                     cout << "Successfully stopped ASIL App" << endl;
                 } else {
                     cout << "Failed to stop ASIL Apps" << endl;
                 }
             }
              // Start the rearcamera app
             string rearcamera_app = "rearcamera";
             if (PlayAsilApp(rearcamera_app) ) {
                 cout << "Successfully started Rear Camera App" << endl;
             } else {
                 cout << "Failed to start Rear Camera App" << endl;
             }
             json jsonObject= json::object();
             DatabaseHandler::GetInstance().SaveData(vehicle_drive_mode, jsonObject);
     }
     }
 }
References allocateQmResources(), DatabaseHandler::GetInstance(), infotainment_selection, kAsilBAvailableApps, kAsilRunningApps, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::object(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parse(), QM_ALLOCATION_DRIVE_STATE, QM_ALLOCATION_PARK_STATE, DatabaseHandler::ReadListData(), DatabaseHandler::ReadStringData(), DatabaseHandler::SaveData(), update_qm_available_resource(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::value(), vehicle_drive_mode, vehiclestate_selection, and nlohmann::detail::exception::what().
operator=()
void UserAppControlHandler::operator= (const UserAppControlHandler & obj) inline private
Define assignment operator in the private section, so that no one can voilate the singleton policy of this class.
Definition at line 23 of file mco_user_app_control_handler.hpp.
 {}
PlayAsilApp()
bool UserAppControlHandler::PlayAsilApp (const std::string & app)
Unpause ASIL App selected by User from Vehicle State UI.
Parameters
app The ASIL app name to be played
Definition at line 239 of file mco_user_app_control_handler.cpp.
 {
     if(checkResourceAvailability("asil", app)){
         Invoker invoker;
         string container_runtime = config_parameters["container_runtime"];
         invoker.SetCommand(CommandFactory::CreateCommand(container_runtime, "ApplyAsilPod", app));
         // Invoke the command and check if it was successful
         if (!invoker.Invoke()) {
             string msg = "Failed to create pod for app: " + app;
             cout << msg << endl;
             // LOG(ERROR) << msg;
             return false;
         }
         cout << "ASIL Pod started successfully for app: " << app << endl;
         json jsonObject= json::object();
         DatabaseHandler::GetInstance().SaveData(vehiclestate_selection, jsonObject);
         // Deduct the required resources from the available resources
         updateResources("asil", app, false);
         return true;
     }
     cout << "Insufficient resources to run the app: " << app << endl;
     // List of priority levels (low -> medium -> high)
     vector<string> priorityLevels = {kPriorityLowQmRunningApps, kPriorityMediumQmRunningApps, kPriorityHighQmRunningApps};
     // Freeing up resources by stopping lower-priority apps
     for (const auto& priority : priorityLevels) {
         while (!(checkResourceAvailability("asil", app))) {
             cout << "Checking priority level: " << priority << endl;
             list<string> running_apps = DatabaseHandler::GetInstance().ReadListData(priority);
             cout<< "Running apps are "<< running_apps.size()<<endl;
             if (running_apps.empty()) break;
             string app_to_delete = running_apps.front();
             string log_message = "Stopping app: " + app_to_delete + " to free up resources for app: " + app;
             cout<< log_message << endl ;
             DatabaseHandler::GetInstance().AddData(resource_management_log, log_message);
             StopQmApp(app_to_delete);
             usleep(1000000);
             // if (global_log_message == "null") {
             //     global_log_message = log_message;  // Remove "null" and set the message
             // } else {
             //     global_log_message +=log_message + "\n" ;  // Append normally
             // }
         }
     }
     DatabaseHandler::GetInstance().AddData(resource_management_log, "");
     // Retry if resources are now available
     if (checkResourceAvailability("asil", app)) {
         return PlayAsilApp(app);
     }
     cout << "Still insufficient resources even after deleting all qm apps!" << endl;
     json jsonObject = json::object();
     DatabaseHandler::GetInstance().SaveData(vehiclestate_selection, jsonObject);
     return false;
 }
References DatabaseHandler::AddData(), checkResourceAvailability(), config_parameters, CommandFactory::CreateCommand(), DatabaseHandler::GetInstance(), Invoker::Invoke(), kPriorityHighQmRunningApps, kPriorityLowQmRunningApps, kPriorityMediumQmRunningApps, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::object(), DatabaseHandler::ReadListData(), resource_management_log, DatabaseHandler::SaveData(), Invoker::SetCommand(), updateResources(), and vehiclestate_selection.
PlayQmApp()
bool UserAppControlHandler::PlayQmApp (const std::string & app)
Play QM App selected by User from Infotainment UI.
Parameters
app The QM app name to be played
Definition at line 177 of file mco_user_app_control_handler.cpp.
 {
     if(checkResourceAvailability("infotainment", app)){
         Invoker invoker;
         string container_runtime = config_parameters["container_runtime"];
         invoker.SetCommand(CommandFactory::CreateCommand(container_runtime, "ApplyQmPod", app));
         // Invoke the command and check if it was successful
         if (!invoker.Invoke()) {
             string msg = "Failed to create pod for app: " + app;
             cout << msg << endl;
             // LOG(ERROR) << msg;
             return false;
         }
         cout << "QM Pod created successfully for app: " << app << endl;
         json jsonObject= json::object();
         DatabaseHandler::GetInstance().SaveData(infotainment_selection, jsonObject);
         // Deduct the required resources from the available resources
         updateResources("infotainment", app, false);
         // DatabaseHandler::GetInstance().qm_infotainment_games_running_apps_.emplace(app);
         // DatabaseHandler::GetInstance().UpdateRunningApps(kQmInfoGamesRunningApps, DatabaseHandler::GetInstance().qm_infotainment_games_running_apps_);
         return true;
     } else {
         cout << "Insufficient resources to run the app: " << app << endl;
         //DatabaseHandler::GetInstance().AddData(lack_of_resources, app);
         json jsonObject= json::object();
         DatabaseHandler::GetInstance().SaveData(infotainment_selection, jsonObject);
         return false;
     }
 }
References checkResourceAvailability(), config_parameters, CommandFactory::CreateCommand(), DatabaseHandler::GetInstance(), infotainment_selection, Invoker::Invoke(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::object(), DatabaseHandler::SaveData(), Invoker::SetCommand(), and updateResources().
StopAsilApp()
bool UserAppControlHandler::StopAsilApp (const std::string & app)
Pause ASIL App selected by User from Vehicle State UI.
Parameters
app The ASIL app name to be stopped
Definition at line 307 of file mco_user_app_control_handler.cpp.
 {
     Invoker invoker;
     string container_runtime = config_parameters["container_runtime"];
     invoker.SetCommand(CommandFactory::CreateCommand(container_runtime, "DeleteAsilPod", app));
     // Invoke the command and check if it was successful
     if (!invoker.Invoke()) {
         string msg = "Failed to create pod for app: " + app;
         cout << msg << endl;
         // LOG(ERROR) << msg;
         return false;
     }
     cout << "ASIL Pod stopped successfully for app: " << app << endl;
     json jsonObject= json::object();
     DatabaseHandler::GetInstance().SaveData(vehiclestate_selection, jsonObject);
     //Add the stopped resources in the available resources
     updateResources("asil", app, true);
     return true;
 }
References config_parameters, CommandFactory::CreateCommand(), DatabaseHandler::GetInstance(), Invoker::Invoke(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::object(), DatabaseHandler::SaveData(), Invoker::SetCommand(), updateResources(), and vehiclestate_selection.
StopQmApp()
bool UserAppControlHandler::StopQmApp (const std::string & app)
Stop QM App selected by User from Infotainment UI.
Parameters
app The QM app name to be stopped
Definition at line 214 of file mco_user_app_control_handler.cpp.
 {
     Invoker invoker;
     string container_runtime = config_parameters["container_runtime"];
     invoker.SetCommand(CommandFactory::CreateCommand(container_runtime, "DeleteQmPod", app));
     // Invoke the command and check if it was successful
     if (!invoker.Invoke()) {
         string msg = "Failed to create pod for app: " + app;
         cout << msg << endl;
         // LOG(ERROR) << msg;
         return false;
     }
     cout << "QM Pod successfully deleted: " << app << endl;
     json jsonObject= json::object();
     DatabaseHandler::GetInstance().SaveData(infotainment_selection, jsonObject);
     //Add the stopped resources in the available resources
     updateResources("infotainment", app, true);
     return true;
 }
References config_parameters, CommandFactory::CreateCommand(), DatabaseHandler::GetInstance(), infotainment_selection, Invoker::Invoke(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::object(), DatabaseHandler::SaveData(), Invoker::SetCommand(), and updateResources().
Referenced by update_qm_available_resource().
The documentation for this class was generated from the following files:
mc_orchestrator/bl/inc/mco_user_app_control_handler.hpp
mc_orchestrator/bl/src/mco_user_app_control_handler.cpp