Mixed Criticality Orchestrator: httplib::detail::SocketStream Class Reference
httplib::detail::SocketStream Class Reference
#include <httplib.h>
Public Member Functions
SocketStream (socket_t sock, time_t read_timeout_sec, time_t read_timeout_usec, time_t write_timeout_sec, time_t write_timeout_usec)
~SocketStream () override
bool is_readable () const override
bool is_writable () const override
ssize_t read (char *ptr, size_t size) override
ssize_t write (const char *ptr, size_t size) override
void get_remote_ip_and_port (std::string &ip, int &port) const override
void get_local_ip_and_port (std::string &ip, int &port) const override
socket_t socket () const override
Public Member Functions inherited from httplib::Stream
virtual ~Stream ()=default
template<typename... Args>
ssize_t write_format (const char *fmt, const Args &...args)
ssize_t write (const char *ptr)
ssize_t write (const std::string &s)
Private Attributes
socket_t sock_
time_t read_timeout_sec_
time_t read_timeout_usec_
time_t write_timeout_sec_
time_t write_timeout_usec_
std::vector< char > read_buff_
size_t read_buff_off_ = 0
size_t read_buff_content_size_ = 0
Static Private Attributes
static const size_t read_buff_size_ = 1024l * 4
Detailed Description
Definition at line 2938 of file httplib.h.
Constructor & Destructor Documentation
SocketStream()
httplib::detail::SocketStream::SocketStream (socket_t sock, time_t read_timeout_sec, time_t read_timeout_usec, time_t write_timeout_sec, time_t write_timeout_usec) inline
Definition at line 5464 of file httplib.h.
     : sock_(sock), read_timeout_sec_(read_timeout_sec),
       read_timeout_usec_(read_timeout_usec),
       write_timeout_sec_(write_timeout_sec),
       write_timeout_usec_(write_timeout_usec), read_buff_(read_buff_size_, 0) {}
~SocketStream()
httplib::detail::SocketStream::~SocketStream () inline override default
Member Function Documentation
get_local_ip_and_port()
void httplib::detail::SocketStream::get_local_ip_and_port (std::string & ip, int & port) const inline override virtual
Implements httplib::Stream.
Definition at line 5546 of file httplib.h.
{
   return detail::get_local_ip_and_port(sock_, ip, port);
 }
References httplib::detail::get_local_ip_and_port(), and sock_.
get_remote_ip_and_port()
void httplib::detail::SocketStream::get_remote_ip_and_port (std::string & ip, int & port) const inline override virtual
Implements httplib::Stream.
Definition at line 5541 of file httplib.h.
{
   return detail::get_remote_ip_and_port(sock_, ip, port);
 }
References httplib::detail::get_remote_ip_and_port(), and sock_.
is_readable()
bool httplib::detail::SocketStream::is_readable () const inline override virtual
Implements httplib::Stream.
Definition at line 5475 of file httplib.h.
{
   return select_read(sock_, read_timeout_sec_, read_timeout_usec_) > 0;
 }
References read_timeout_sec_, read_timeout_usec_, httplib::detail::select_read(), and sock_.
Referenced by read().
is_writable()
bool httplib::detail::SocketStream::is_writable () const inline override virtual
Implements httplib::Stream.
Definition at line 5479 of file httplib.h.
{
   return select_write(sock_, write_timeout_sec_, write_timeout_usec_) > 0 &&
          is_socket_alive(sock_);
 }
References httplib::detail::is_socket_alive(), httplib::detail::select_write(), sock_, write_timeout_sec_, and write_timeout_usec_.
Referenced by write().
read()
ssize_t httplib::detail::SocketStream::read (char * ptr, size_t size) inline override virtual
Implements httplib::Stream.
Definition at line 5484 of file httplib.h.
{
 #ifdef _WIN32
   size =
       (std::min)(size, static_cast<size_t>((std::numeric_limits<int>::max)()));
 #else
   size = (std::min)(size,
                     static_cast<size_t>((std::numeric_limits<ssize_t>::max)()));
 #endif
   if (read_buff_off_ < read_buff_content_size_) {
     auto remaining_size = read_buff_content_size_ - read_buff_off_;
     if (size <= remaining_size) {
       memcpy(ptr, read_buff_.data() + read_buff_off_, size);
       read_buff_off_ += size;
       return static_cast<ssize_t>(size);
     } else {
       memcpy(ptr, read_buff_.data() + read_buff_off_, remaining_size);
       read_buff_off_ += remaining_size;
       return static_cast<ssize_t>(remaining_size);
     }
   }
   if (!is_readable()) { return -1; }
   read_buff_off_ = 0;
   read_buff_content_size_ = 0;
   if (size < read_buff_size_) {
     auto n = read_socket(sock_, read_buff_.data(), read_buff_size_,
                          CPPHTTPLIB_RECV_FLAGS);
     if (n <= 0) {
       return n;
     } else if (n <= static_cast<ssize_t>(size)) {
       memcpy(ptr, read_buff_.data(), static_cast<size_t>(n));
       return n;
     } else {
       memcpy(ptr, read_buff_.data(), size);
       read_buff_off_ = size;
       read_buff_content_size_ = static_cast<size_t>(n);
       return static_cast<ssize_t>(size);
     }
   } else {
     return read_socket(sock_, ptr, size, CPPHTTPLIB_RECV_FLAGS);
   }
 }
References CPPHTTPLIB_RECV_FLAGS, is_readable(), n, read_buff_, read_buff_content_size_, read_buff_off_, read_buff_size_, httplib::detail::read_socket(), and sock_.
socket()
socket_t httplib::detail::SocketStream::socket () const inline override virtual
Implements httplib::Stream.
Definition at line 5551 of file httplib.h.
 { return sock_; }
References sock_.
write()
ssize_t httplib::detail::SocketStream::write (const char * ptr, size_t size) inline override virtual
Implements httplib::Stream.
Definition at line 5530 of file httplib.h.
{
   if (!is_writable()) { return -1; }
 #if defined(_WIN32) && !defined(_WIN64)
   size =
       (std::min)(size, static_cast<size_t>((std::numeric_limits<int>::max)()));
 #endif
   return send_socket(sock_, ptr, size, CPPHTTPLIB_SEND_FLAGS);
 }
References CPPHTTPLIB_SEND_FLAGS, is_writable(), httplib::detail::send_socket(), and sock_.
Member Data Documentation
read_buff_
std::vector<char> httplib::detail::SocketStream::read_buff_ private
Definition at line 2959 of file httplib.h.
Referenced by read().
read_buff_content_size_
size_t httplib::detail::SocketStream::read_buff_content_size_ = 0 private
Definition at line 2961 of file httplib.h.
Referenced by read().
read_buff_off_
size_t httplib::detail::SocketStream::read_buff_off_ = 0 private
Definition at line 2960 of file httplib.h.
Referenced by read().
read_buff_size_
const size_t httplib::detail::SocketStream::read_buff_size_ = 1024l * 4 static private
Definition at line 2963 of file httplib.h.
Referenced by read().
read_timeout_sec_
time_t httplib::detail::SocketStream::read_timeout_sec_ private
Definition at line 2954 of file httplib.h.
Referenced by is_readable().
read_timeout_usec_
time_t httplib::detail::SocketStream::read_timeout_usec_ private
Definition at line 2955 of file httplib.h.
Referenced by is_readable().
sock_
socket_t httplib::detail::SocketStream::sock_ private
Definition at line 2953 of file httplib.h.
Referenced by get_local_ip_and_port(), get_remote_ip_and_port(), is_readable(), is_writable(), read(), socket(), and write().
write_timeout_sec_
time_t httplib::detail::SocketStream::write_timeout_sec_ private
Definition at line 2956 of file httplib.h.
Referenced by is_writable().
write_timeout_usec_
time_t httplib::detail::SocketStream::write_timeout_usec_ private
Definition at line 2957 of file httplib.h.
Referenced by is_writable().
The documentation for this class was generated from the following file:
mc_orchestrator/httplib/httplib.h