Mixed Criticality Orchestrator: fuzzer::FixedWord< kMaxSize > Class Template Reference
fuzzer::FixedWord< kMaxSize > Class Template Reference
#include <FuzzerDictionary.h>
Public Member Functions
FixedWord ()
FixedWord (const uint8_t *B, uint8_t S)
void Set (const uint8_t *B, uint8_t S)
bool operator== (const FixedWord< kMaxSize > &w) const
bool operator< (const FixedWord< kMaxSize > &w) const
const uint8_t * data () const
uint8_t size () const
Static Public Member Functions
static size_t GetMaxSize ()
Private Attributes
uint8_t Size = 0
uint8_t Data [kMaxSize]
Detailed Description
template<size_t kMaxSize>
class fuzzer::FixedWord< kMaxSize >
Definition at line 23 of file FuzzerDictionary.h.
Constructor & Destructor Documentation
FixedWord() [1/2]
template<size_t kMaxSize> fuzzer::FixedWord< kMaxSize >::FixedWord () inline
Definition at line 25 of file FuzzerDictionary.h.
 {}
FixedWord() [2/2]
template<size_t kMaxSize> fuzzer::FixedWord< kMaxSize >::FixedWord (const uint8_t * B, uint8_t S) inline
Definition at line 26 of file FuzzerDictionary.h.
 { Set(B, S); }
Member Function Documentation
data()
template<size_t kMaxSize> const uint8_t* fuzzer::FixedWord< kMaxSize >::data () const inline
Definition at line 45 of file FuzzerDictionary.h.
 { return Data; }
Referenced by fuzzer::MutationDispatcher::ApplyDictionaryEntry(), fuzzer::DictionaryEntry::Print(), and fuzzer::PrintASCII().
GetMaxSize()
template<size_t kMaxSize> static size_t fuzzer::FixedWord< kMaxSize >::GetMaxSize () inline static
Definition at line 44 of file FuzzerDictionary.h.
 { return kMaxSize; }
operator<()
template<size_t kMaxSize> bool fuzzer::FixedWord< kMaxSize >::operator< (const FixedWord< kMaxSize > & w) const inline
Definition at line 38 of file FuzzerDictionary.h.
{
     if (Size != w.Size)
       return Size < w.Size;
     return memcmp(Data, w.Data, Size) < 0;
   }
operator==()
template<size_t kMaxSize> bool fuzzer::FixedWord< kMaxSize >::operator== (const FixedWord< kMaxSize > & w) const inline
Definition at line 34 of file FuzzerDictionary.h.
{
     return Size == w.Size && 0 == memcmp(Data, w.Data, Size);
   }
Set()
template<size_t kMaxSize> void fuzzer::FixedWord< kMaxSize >::Set (const uint8_t * B, uint8_t S) inline
Definition at line 28 of file FuzzerDictionary.h.
{
     assert(S <= kMaxSize);
     memcpy(Data, B, S);
     Size = S;
   }
Referenced by fuzzer::FixedWord< 27 >::FixedWord(), and fuzzer::MutationDispatcher::MakeDictionaryEntryFromCMP().
size()
template<size_t kMaxSize> uint8_t fuzzer::FixedWord< kMaxSize >::size () const inline
Definition at line 46 of file FuzzerDictionary.h.
 { return Size; }
Referenced by fuzzer::MutationDispatcher::ApplyDictionaryEntry(), fuzzer::DictionaryEntry::Print(), and fuzzer::PrintASCII().
Member Data Documentation
Data
template<size_t kMaxSize> uint8_t fuzzer::FixedWord< kMaxSize >::Data[kMaxSize] private
Definition at line 50 of file FuzzerDictionary.h.
Referenced by fuzzer::FixedWord< 27 >::data(), fuzzer::FixedWord< 27 >::operator<(), fuzzer::FixedWord< 27 >::operator==(), and fuzzer::FixedWord< 27 >::Set().
Size
template<size_t kMaxSize> uint8_t fuzzer::FixedWord< kMaxSize >::Size = 0 private
Definition at line 49 of file FuzzerDictionary.h.
Referenced by fuzzer::FixedWord< 27 >::operator<(), fuzzer::FixedWord< 27 >::operator==(), fuzzer::FixedWord< 27 >::Set(), and fuzzer::FixedWord< 27 >::size().
The documentation for this class was generated from the following file:
mc_orchestrator/json-3.7.3/test/thirdparty/Fuzzer/FuzzerDictionary.h