Mixed Criticality Orchestrator: ResourceMonitorSubject Class Reference
ResourceMonitorSubject Class Reference
Public Member Functions
ResourceMonitorSubject ()
void AddObserver (Observer *o) override
void RemoveObserver (Observer *o) override
void NotifyObservers () override
void GetResourceUtilization (vector< pair< float, float >> &resource_utilization)
void AverageResourceUtilization ()
void Run ()
Public Member Functions inherited from Subject
virtual ~Subject ()
Private Attributes
vector< Observer * > observers
int avg_cpuUtilization
int avg_memoryUtilization
bool is_cpu_utilization_high
bool is_memory_utilization_high
bool is_cpu_utilization_below_pod_respawn_threshold
bool is_memory_utilization_below_pod_respawn_threshold
std::vector< std::string > topics = {kTopicCpuUtilization, kTopicMemoryUtilization}
MqttHandler subscriber
Detailed Description
Definition at line 54 of file mco_resource_monitor_handler.cpp.
Constructor & Destructor Documentation
ResourceMonitorSubject()
ResourceMonitorSubject::ResourceMonitorSubject () inline
Definition at line 68 of file mco_resource_monitor_handler.cpp.
 : subscriber("subscriber", this->topics) {}
Member Function Documentation
AddObserver()
void ResourceMonitorSubject::AddObserver (Observer * o) inline override virtual
Implements Subject.
Definition at line 70 of file mco_resource_monitor_handler.cpp.
{
         observers.push_back(o);
     }
Referenced by ResourceMonitorHandler::Init().
AverageResourceUtilization()
void ResourceMonitorSubject::AverageResourceUtilization () inline
Definition at line 102 of file mco_resource_monitor_handler.cpp.
{
         // Get resource monitor time interval and sample size from config file
         int sample_size = stoi(config_parameters["resource_monitor_sample_size"]);
         vector<float> cpu_utilization;
         vector<float> memory_utilization;
         vector<pair<float, float>> resource_utilization;
         while (resource_utilization.size() < sample_size+1) {
             GetResourceUtilization(resource_utilization);
             for (auto& utilization : resource_utilization) {
                 cpu_utilization.push_back(utilization.first);
                 memory_utilization.push_back(utilization.second);
             }
             // Calculate average resource utilization over a sample size
             if(sample_size == resource_utilization.size()){
                 avg_cpuUtilization = 0;
                 avg_memoryUtilization = 0;
                 // Average CPU and memory utilization
                 avg_cpuUtilization = accumulate(cpu_utilization.begin(), cpu_utilization.end(), 0.0)/cpu_utilization.size();
                 avg_memoryUtilization = accumulate(memory_utilization.begin(), memory_utilization.end(), 0.0)/memory_utilization.size();
                 // Store timestamp in database
                 string time = GetCurrentTime();
                 DatabaseHandler::GetInstance().AddData("timestamp", time);
                 // Store average CPU and memory utilization in database
                 DatabaseHandler::GetInstance().AddData("avg_cpu_utilization", to_string(avg_cpuUtilization));
                 DatabaseHandler::GetInstance().AddData("avg_memory_utilization", to_string(avg_memoryUtilization));
                 // // Save data to file
                 // std::ofstream file;
                 // file.open(kAllLogsFile.c_str(), std::ios_base::app);
                 // // If the file was just created, write the header
                 // if (file.tellp() == 0) {
                 //     file << "time, avg_cpuUtilization, avg_memoryUtilization\n";
                 // }
                 // file << time << "," << avg_cpuUtilization << "," << avg_memoryUtilization << "\n";
                 // file.close();
                cout << "Average CPU Utilization: " << avg_cpuUtilization << "%" << endl;
                cout << "Average Memory Utilization: " << avg_memoryUtilization << "%" << endl;
                cout << "Time: " << time << "millisec" << endl;
             }
         }
     }
References DatabaseHandler::AddData(), config_parameters, GetCurrentTime(), DatabaseHandler::GetInstance(), and httplib::to_string().
GetResourceUtilization()
void ResourceMonitorSubject::GetResourceUtilization (vector< pair< float, float >> & resource_utilization) inline
Definition at line 84 of file mco_resource_monitor_handler.cpp.
{
         // Call the mosquitto loop function to process incoming messages
         for (int j = 0; j < kMqttCommLoop; ++j) {
             subscriber.loop();
             std::this_thread::sleep_for(std::chrono::milliseconds(1));  // Sleep for 1ms for sunscription
             // Check if the subscriber has received the CPU and Memory utilization data
             auto cpu_it = subscriber.topic_data.find(kTopicCpuUtilization.c_str());
             auto mem_it = subscriber.topic_data.find(kTopicMemoryUtilization.c_str());
             if (cpu_it != subscriber.topic_data.end() && !cpu_it->second.empty() &&
                 mem_it != subscriber.topic_data.end() && !mem_it->second.empty()) {
                 resource_utilization.push_back(std::make_pair(std::stof(cpu_it->second), std::stof(mem_it->second)));
                 break;
             }
         }
     }
References kMqttCommLoop, kTopicCpuUtilization, kTopicMemoryUtilization, and MqttHandler::topic_data.
NotifyObservers()
void ResourceMonitorSubject::NotifyObservers () inline override virtual
Implements Subject.
Definition at line 78 of file mco_resource_monitor_handler.cpp.
{
         for (Observer* o : observers) {
             o->Update(avg_cpuUtilization, avg_memoryUtilization);
         }
     }
RemoveObserver()
void ResourceMonitorSubject::RemoveObserver (Observer * o) inline override virtual
Implements Subject.
Definition at line 74 of file mco_resource_monitor_handler.cpp.
{
         observers.erase(remove(observers.begin(), observers.end(), o), observers.end());
     }
Run()
void ResourceMonitorSubject::Run () inline
Definition at line 152 of file mco_resource_monitor_handler.cpp.
                {
         while (true) {
             AverageResourceUtilization();
             NotifyObservers();
         }
     }
Referenced by ResourceMonitorHandler::Init().
Member Data Documentation
avg_cpuUtilization
int ResourceMonitorSubject::avg_cpuUtilization private
Definition at line 57 of file mco_resource_monitor_handler.cpp.
avg_memoryUtilization
int ResourceMonitorSubject::avg_memoryUtilization private
Definition at line 58 of file mco_resource_monitor_handler.cpp.
is_cpu_utilization_below_pod_respawn_threshold
bool ResourceMonitorSubject::is_cpu_utilization_below_pod_respawn_threshold private
Definition at line 61 of file mco_resource_monitor_handler.cpp.
is_cpu_utilization_high
bool ResourceMonitorSubject::is_cpu_utilization_high private
Definition at line 59 of file mco_resource_monitor_handler.cpp.
is_memory_utilization_below_pod_respawn_threshold
bool ResourceMonitorSubject::is_memory_utilization_below_pod_respawn_threshold private
Definition at line 62 of file mco_resource_monitor_handler.cpp.
is_memory_utilization_high
bool ResourceMonitorSubject::is_memory_utilization_high private
Definition at line 60 of file mco_resource_monitor_handler.cpp.
observers
vector<Observer*> ResourceMonitorSubject::observers private
Definition at line 56 of file mco_resource_monitor_handler.cpp.
subscriber
MqttHandler ResourceMonitorSubject::subscriber private
Definition at line 65 of file mco_resource_monitor_handler.cpp.
topics
std::vector<std::string> ResourceMonitorSubject::topics = {kTopicCpuUtilization, kTopicMemoryUtilization} private
Definition at line 64 of file mco_resource_monitor_handler.cpp.
The documentation for this class was generated from the following file:
mc_orchestrator/bl/src/mco_resource_monitor_handler.cpp