Mixed Criticality Orchestrator: nlohmann::detail::json_sax_dom_parser< BasicJsonType > Class Template Reference
nlohmann::detail::json_sax_dom_parser< BasicJsonType > Class Template Reference
SAX implementation to create a JSON value from SAX events.
#include <json_sax.hpp>
Public Types
using number_integer_t = typename BasicJsonType::number_integer_t
using number_unsigned_t = typename BasicJsonType::number_unsigned_t
using number_float_t = typename BasicJsonType::number_float_t
using string_t = typename BasicJsonType::string_t
using number_integer_t = typename BasicJsonType::number_integer_t
using number_unsigned_t = typename BasicJsonType::number_unsigned_t
using number_float_t = typename BasicJsonType::number_float_t
using string_t = typename BasicJsonType::string_t
Public Member Functions
json_sax_dom_parser (BasicJsonType &r, const bool allow_exceptions_=true)
json_sax_dom_parser (const json_sax_dom_parser &)=delete
json_sax_dom_parser (json_sax_dom_parser &&)=default
json_sax_dom_parser & operator= (const json_sax_dom_parser &)=delete
json_sax_dom_parser & operator= (json_sax_dom_parser &&)=default
~json_sax_dom_parser ()=default
bool null ()
bool boolean (bool val)
bool number_integer (number_integer_t val)
bool number_unsigned (number_unsigned_t val)
bool number_float (number_float_t val, const string_t &)
bool string (string_t &val)
bool start_object (std::size_t len)
bool key (string_t &val)
bool end_object ()
bool start_array (std::size_t len)
bool end_array ()
bool parse_error (std::size_t, const std::string &, const detail::exception &ex)
constexpr bool is_errored () const
json_sax_dom_parser (BasicJsonType &r, const bool allow_exceptions_=true)
json_sax_dom_parser (const json_sax_dom_parser &)=delete
json_sax_dom_parser (json_sax_dom_parser &&)=default
json_sax_dom_parser & operator= (const json_sax_dom_parser &)=delete
json_sax_dom_parser & operator= (json_sax_dom_parser &&)=default
~json_sax_dom_parser ()=default
bool null ()
bool boolean (bool val)
bool number_integer (number_integer_t val)
bool number_unsigned (number_unsigned_t val)
bool number_float (number_float_t val, const string_t &)
bool string (string_t &val)
bool start_object (std::size_t len)
bool key (string_t &val)
bool end_object ()
bool start_array (std::size_t len)
bool end_array ()
bool parse_error (std::size_t, const std::string &, const detail::exception &ex)
constexpr bool is_errored () const
Private Member Functions
template<typename Value >
JSON_HEDLEY_RETURNS_NON_NULL BasicJsonType * handle_value (Value &&v)
template<typename Value >
BasicJsonType * handle_value (Value &&v)
Private Attributes
BasicJsonType & root
the parsed JSON value
std::vector< BasicJsonType * > ref_stack {}
stack to model hierarchy of values
BasicJsonType * object_element = nullptr
helper to hold the reference for the next object element
bool errored = false
whether a syntax error occurred
const bool allow_exceptions = true
whether to throw exceptions in case of errors
Detailed Description
template<typename BasicJsonType>
class nlohmann::detail::json_sax_dom_parser< BasicJsonType >
SAX implementation to create a JSON value from SAX events.
This class implements the json_sax interface and processes the SAX events to create a JSON value which makes it basically a DOM parser. The structure or hierarchy of the JSON value is managed by the stack ref_stack which contains a pointer to the respective array or object for each recursion depth.
After successful parsing, the value that is passed by reference to the constructor contains the parsed value.
Template Parameters
BasicJsonType the JSON type
Definition at line 145 of file json_sax.hpp.
Member Typedef Documentation
number_float_t [1/2]
template<typename BasicJsonType > using nlohmann::detail::json_sax_dom_parser< BasicJsonType >::number_float_t = typename BasicJsonType::number_float_t
Definition at line 150 of file json_sax.hpp.
number_float_t [2/2]
template<typename BasicJsonType > using nlohmann::detail::json_sax_dom_parser< BasicJsonType >::number_float_t = typename BasicJsonType::number_float_t
Definition at line 4459 of file json.hpp.
number_integer_t [1/2]
template<typename BasicJsonType > using nlohmann::detail::json_sax_dom_parser< BasicJsonType >::number_integer_t = typename BasicJsonType::number_integer_t
Definition at line 148 of file json_sax.hpp.
number_integer_t [2/2]
template<typename BasicJsonType > using nlohmann::detail::json_sax_dom_parser< BasicJsonType >::number_integer_t = typename BasicJsonType::number_integer_t
Definition at line 4457 of file json.hpp.
number_unsigned_t [1/2]
template<typename BasicJsonType > using nlohmann::detail::json_sax_dom_parser< BasicJsonType >::number_unsigned_t = typename BasicJsonType::number_unsigned_t
Definition at line 149 of file json_sax.hpp.
number_unsigned_t [2/2]
template<typename BasicJsonType > using nlohmann::detail::json_sax_dom_parser< BasicJsonType >::number_unsigned_t = typename BasicJsonType::number_unsigned_t
Definition at line 4458 of file json.hpp.
string_t [1/2]
template<typename BasicJsonType > using nlohmann::detail::json_sax_dom_parser< BasicJsonType >::string_t = typename BasicJsonType::string_t
Definition at line 151 of file json_sax.hpp.
string_t [2/2]
template<typename BasicJsonType > using nlohmann::detail::json_sax_dom_parser< BasicJsonType >::string_t = typename BasicJsonType::string_t
Definition at line 4460 of file json.hpp.
Constructor & Destructor Documentation
json_sax_dom_parser() [1/6]
template<typename BasicJsonType > nlohmann::detail::json_sax_dom_parser< BasicJsonType >::json_sax_dom_parser (BasicJsonType & r, const bool allow_exceptions_ = true) inline explicit
Parameters
[in,out] r reference to a JSON value that is manipulated while parsing
[in] allow_exceptions_ whether parse errors yield exceptions
Definition at line 158 of file json_sax.hpp.
         : root(r), allow_exceptions(allow_exceptions_)
     {}
json_sax_dom_parser() [2/6]
template<typename BasicJsonType > nlohmann::detail::json_sax_dom_parser< BasicJsonType >::json_sax_dom_parser (const json_sax_dom_parser< BasicJsonType > &) delete
json_sax_dom_parser() [3/6]
template<typename BasicJsonType > nlohmann::detail::json_sax_dom_parser< BasicJsonType >::json_sax_dom_parser (json_sax_dom_parser< BasicJsonType > &&) default
~json_sax_dom_parser() [1/2]
template<typename BasicJsonType > nlohmann::detail::json_sax_dom_parser< BasicJsonType >::~json_sax_dom_parser () default
json_sax_dom_parser() [4/6]
template<typename BasicJsonType > nlohmann::detail::json_sax_dom_parser< BasicJsonType >::json_sax_dom_parser (BasicJsonType & r, const bool allow_exceptions_ = true) inline explicit
Parameters
[in,out] r reference to a JSON value that is manipulated while parsing
[in] allow_exceptions_ whether parse errors yield exceptions
Definition at line 4467 of file json.hpp.
         : root(r), allow_exceptions(allow_exceptions_)
     {}
json_sax_dom_parser() [5/6]
template<typename BasicJsonType > nlohmann::detail::json_sax_dom_parser< BasicJsonType >::json_sax_dom_parser (const json_sax_dom_parser< BasicJsonType > &) delete
json_sax_dom_parser() [6/6]
template<typename BasicJsonType > nlohmann::detail::json_sax_dom_parser< BasicJsonType >::json_sax_dom_parser (json_sax_dom_parser< BasicJsonType > &&) default
~json_sax_dom_parser() [2/2]
template<typename BasicJsonType > nlohmann::detail::json_sax_dom_parser< BasicJsonType >::~json_sax_dom_parser () default
Member Function Documentation
boolean() [1/2]
template<typename BasicJsonType > bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::boolean (bool val) inline
Definition at line 175 of file json_sax.hpp.
     {
         handle_value(val);
         return true;
     }
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value().
boolean() [2/2]
template<typename BasicJsonType > bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::boolean (bool val) inline
Definition at line 4484 of file json.hpp.
     {
         handle_value(val);
         return true;
     }
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value().
end_array() [1/2]
template<typename BasicJsonType > bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::end_array () inline
Definition at line 244 of file json_sax.hpp.
     {
         ref_stack.pop_back();
         return true;
     }
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::ref_stack.
end_array() [2/2]
template<typename BasicJsonType > bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::end_array () inline
Definition at line 4553 of file json.hpp.
     {
         ref_stack.pop_back();
         return true;
     }
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::ref_stack.
end_object() [1/2]
template<typename BasicJsonType > bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::end_object () inline
Definition at line 225 of file json_sax.hpp.
     {
         ref_stack.pop_back();
         return true;
     }
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::ref_stack.
end_object() [2/2]
template<typename BasicJsonType > bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::end_object () inline
Definition at line 4534 of file json.hpp.
     {
         ref_stack.pop_back();
         return true;
     }
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::ref_stack.
handle_value() [1/2]
template<typename BasicJsonType > template<typename Value > JSON_HEDLEY_RETURNS_NON_NULL BasicJsonType* nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value (Value && v) inline private
Invariant
If the ref stack is empty, then the passed value will be the new root.
If the ref stack contains a value, then it is an array or an object to which we can add elements
Definition at line 292 of file json_sax.hpp.
     {
         if (ref_stack.empty())
         {
             root = BasicJsonType(std::forward<Value>(v));
             return &root;
         }
         assert(ref_stack.back()->is_array() or ref_stack.back()->is_object());
         if (ref_stack.back()->is_array())
         {
             ref_stack.back()->m_value.array->emplace_back(std::forward<Value>(v));
             return &(ref_stack.back()->m_value.array->back());
         }
         assert(ref_stack.back()->is_object());
         assert(object_element);
         *object_element = BasicJsonType(std::forward<Value>(v));
         return object_element;
     }
References assert(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::object_element, nlohmann::detail::json_sax_dom_parser< BasicJsonType >::ref_stack, and nlohmann::detail::json_sax_dom_parser< BasicJsonType >::root.
Referenced by nlohmann::detail::json_sax_dom_parser< BasicJsonType >::boolean(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::null(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::number_float(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::number_integer(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::number_unsigned(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::start_array(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::start_object(), and nlohmann::detail::json_sax_dom_parser< BasicJsonType >::string().
handle_value() [2/2]
template<typename BasicJsonType > template<typename Value > BasicJsonType* nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value (Value && v) inline private
Invariant
If the ref stack is empty, then the passed value will be the new root.
If the ref stack contains a value, then it is an array or an object to which we can add elements
Definition at line 4601 of file json.hpp.
     {
         if (ref_stack.empty())
         {
             root = BasicJsonType(std::forward<Value>(v));
             return &root;
         }
         assert(ref_stack.back()->is_array() or ref_stack.back()->is_object());
         if (ref_stack.back()->is_array())
         {
             ref_stack.back()->m_value.array->emplace_back(std::forward<Value>(v));
             return &(ref_stack.back()->m_value.array->back());
         }
         assert(ref_stack.back()->is_object());
         assert(object_element);
         *object_element = BasicJsonType(std::forward<Value>(v));
         return object_element;
     }
References assert(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::object_element, nlohmann::detail::json_sax_dom_parser< BasicJsonType >::ref_stack, and nlohmann::detail::json_sax_dom_parser< BasicJsonType >::root.
is_errored() [1/2]
template<typename BasicJsonType > constexpr bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::is_errored () const inline constexpr
Definition at line 278 of file json_sax.hpp.
     {
         return errored;
     }
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::errored.
Referenced by nlohmann::detail::parser< BasicJsonType >::parse().
is_errored() [2/2]
template<typename BasicJsonType > constexpr bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::is_errored () const inline constexpr
Definition at line 4587 of file json.hpp.
     {
         return errored;
     }
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::errored.
key() [1/2]
template<typename BasicJsonType > bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::key (string_t & val) inline
Definition at line 218 of file json_sax.hpp.
     {
         // add null at given key and store the reference for later
         object_element = &(ref_stack.back()->m_value.object->operator[](val));
         return true;
     }
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::object_element, and nlohmann::detail::json_sax_dom_parser< BasicJsonType >::ref_stack.
key() [2/2]
template<typename BasicJsonType > bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::key (string_t & val) inline
Definition at line 4527 of file json.hpp.
     {
         // add null at given key and store the reference for later
         object_element = &(ref_stack.back()->m_value.object->operator[](val));
         return true;
     }
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::object_element, and nlohmann::detail::json_sax_dom_parser< BasicJsonType >::ref_stack.
null() [1/2]
template<typename BasicJsonType > bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::null () inline
Definition at line 169 of file json_sax.hpp.
     {
         handle_value(nullptr);
         return true;
     }
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value().
null() [2/2]
template<typename BasicJsonType > bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::null () inline
Definition at line 4478 of file json.hpp.
     {
         handle_value(nullptr);
         return true;
     }
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value().
number_float() [1/2]
template<typename BasicJsonType > bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::number_float (number_float_t val, const string_t &) inline
Definition at line 193 of file json_sax.hpp.
     {
         handle_value(val);
         return true;
     }
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value().
number_float() [2/2]
template<typename BasicJsonType > bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::number_float (number_float_t val, const string_t &) inline
Definition at line 4502 of file json.hpp.
     {
         handle_value(val);
         return true;
     }
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value().
number_integer() [1/2]
template<typename BasicJsonType > bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::number_integer (number_integer_t val) inline
Definition at line 181 of file json_sax.hpp.
     {
         handle_value(val);
         return true;
     }
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value().
number_integer() [2/2]
template<typename BasicJsonType > bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::number_integer (number_integer_t val) inline
Definition at line 4490 of file json.hpp.
     {
         handle_value(val);
         return true;
     }
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value().
number_unsigned() [1/2]
template<typename BasicJsonType > bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::number_unsigned (number_unsigned_t val) inline
Definition at line 187 of file json_sax.hpp.
     {
         handle_value(val);
         return true;
     }
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value().
number_unsigned() [2/2]
template<typename BasicJsonType > bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::number_unsigned (number_unsigned_t val) inline
Definition at line 4496 of file json.hpp.
     {
         handle_value(val);
         return true;
     }
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value().
operator=() [1/4]
template<typename BasicJsonType > json_sax_dom_parser& nlohmann::detail::json_sax_dom_parser< BasicJsonType >::operator= (const json_sax_dom_parser< BasicJsonType > &) delete
operator=() [2/4]
template<typename BasicJsonType > json_sax_dom_parser& nlohmann::detail::json_sax_dom_parser< BasicJsonType >::operator= (const json_sax_dom_parser< BasicJsonType > &) delete
operator=() [3/4]
template<typename BasicJsonType > json_sax_dom_parser& nlohmann::detail::json_sax_dom_parser< BasicJsonType >::operator= (json_sax_dom_parser< BasicJsonType > &&) default
operator=() [4/4]
template<typename BasicJsonType > json_sax_dom_parser& nlohmann::detail::json_sax_dom_parser< BasicJsonType >::operator= (json_sax_dom_parser< BasicJsonType > &&) default
parse_error() [1/2]
template<typename BasicJsonType > bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::parse_error (std::size_t , const std::string & , const detail::exception & ex) inline
Definition at line 250 of file json_sax.hpp.
     {
         errored = true;
         if (allow_exceptions)
         {
             // determine the proper exception type from the id
             switch ((ex.id / 100) % 100)
             {
                 case 1:
                     JSON_THROW(*static_cast<const detail::parse_error*>(&ex));
                 case 4:
                     JSON_THROW(*static_cast<const detail::out_of_range*>(&ex));
                 // LCOV_EXCL_START
                 case 2:
                     JSON_THROW(*static_cast<const detail::invalid_iterator*>(&ex));
                 case 3:
                     JSON_THROW(*static_cast<const detail::type_error*>(&ex));
                 case 5:
                     JSON_THROW(*static_cast<const detail::other_error*>(&ex));
                 default:
                     assert(false);
                     // LCOV_EXCL_STOP
             }
         }
         return false;
     }
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::allow_exceptions, assert(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::errored, nlohmann::detail::exception::id, and JSON_THROW.
Referenced by nlohmann::detail::parser< BasicJsonType >::parse().
parse_error() [2/2]
template<typename BasicJsonType > bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::parse_error (std::size_t , const std::string & , const detail::exception & ex) inline
Definition at line 4559 of file json.hpp.
     {
         errored = true;
         if (allow_exceptions)
         {
             // determine the proper exception type from the id
             switch ((ex.id / 100) % 100)
             {
                 case 1:
                     JSON_THROW(*static_cast<const detail::parse_error*>(&ex));
                 case 4:
                     JSON_THROW(*static_cast<const detail::out_of_range*>(&ex));
                 // LCOV_EXCL_START
                 case 2:
                     JSON_THROW(*static_cast<const detail::invalid_iterator*>(&ex));
                 case 3:
                     JSON_THROW(*static_cast<const detail::type_error*>(&ex));
                 case 5:
                     JSON_THROW(*static_cast<const detail::other_error*>(&ex));
                 default:
                     assert(false);
                     // LCOV_EXCL_STOP
             }
         }
         return false;
     }
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::allow_exceptions, assert(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::errored, nlohmann::detail::exception::id, and JSON_THROW.
start_array() [1/2]
template<typename BasicJsonType > bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::start_array (std::size_t len) inline
Definition at line 231 of file json_sax.hpp.
     {
         ref_stack.push_back(handle_value(BasicJsonType::value_t::array));
         if (JSON_HEDLEY_UNLIKELY(len != std::size_t(-1) and len > ref_stack.back()->max_size()))
         {
             JSON_THROW(out_of_range::create(408,
                                             "excessive array size: " + std::to_string(len)));
         }
         return true;
     }
References array, nlohmann::detail::out_of_range::create(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value(), JSON_HEDLEY_UNLIKELY, JSON_THROW, nlohmann::detail::json_sax_dom_parser< BasicJsonType >::ref_stack, and httplib::to_string().
start_array() [2/2]
template<typename BasicJsonType > bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::start_array (std::size_t len) inline
Definition at line 4540 of file json.hpp.
     {
         ref_stack.push_back(handle_value(BasicJsonType::value_t::array));
         if (JSON_HEDLEY_UNLIKELY(len != std::size_t(-1) and len > ref_stack.back()->max_size()))
         {
             JSON_THROW(out_of_range::create(408,
                                             "excessive array size: " + std::to_string(len)));
         }
         return true;
     }
References array, nlohmann::detail::out_of_range::create(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value(), JSON_HEDLEY_UNLIKELY, JSON_THROW, nlohmann::detail::json_sax_dom_parser< BasicJsonType >::ref_stack, and nlohmann::to_string().
start_object() [1/2]
template<typename BasicJsonType > bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::start_object (std::size_t len) inline
Definition at line 205 of file json_sax.hpp.
     {
         ref_stack.push_back(handle_value(BasicJsonType::value_t::object));
         if (JSON_HEDLEY_UNLIKELY(len != std::size_t(-1) and len > ref_stack.back()->max_size()))
         {
             JSON_THROW(out_of_range::create(408,
                                             "excessive object size: " + std::to_string(len)));
         }
         return true;
     }
References nlohmann::detail::out_of_range::create(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value(), JSON_HEDLEY_UNLIKELY, JSON_THROW, nlohmann::detail::json_sax_dom_parser< BasicJsonType >::ref_stack, and httplib::to_string().
start_object() [2/2]
template<typename BasicJsonType > bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::start_object (std::size_t len) inline
Definition at line 4514 of file json.hpp.
     {
         ref_stack.push_back(handle_value(BasicJsonType::value_t::object));
         if (JSON_HEDLEY_UNLIKELY(len != std::size_t(-1) and len > ref_stack.back()->max_size()))
         {
             JSON_THROW(out_of_range::create(408,
                                             "excessive object size: " + std::to_string(len)));
         }
         return true;
     }
References nlohmann::detail::out_of_range::create(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value(), JSON_HEDLEY_UNLIKELY, JSON_THROW, nlohmann::detail::json_sax_dom_parser< BasicJsonType >::ref_stack, and nlohmann::to_string().
string() [1/2]
template<typename BasicJsonType > bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::string (string_t & val) inline
Definition at line 199 of file json_sax.hpp.
     {
         handle_value(val);
         return true;
     }
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value().
string() [2/2]
template<typename BasicJsonType > bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::string (string_t & val) inline
Definition at line 4508 of file json.hpp.
     {
         handle_value(val);
         return true;
     }
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value().
Member Data Documentation
allow_exceptions
template<typename BasicJsonType > const bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::allow_exceptions = true private
whether to throw exceptions in case of errors
Definition at line 323 of file json_sax.hpp.
Referenced by nlohmann::detail::json_sax_dom_parser< BasicJsonType >::parse_error().
errored
template<typename BasicJsonType > bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::errored = false private
whether a syntax error occurred
Definition at line 321 of file json_sax.hpp.
Referenced by nlohmann::detail::json_sax_dom_parser< BasicJsonType >::is_errored(), and nlohmann::detail::json_sax_dom_parser< BasicJsonType >::parse_error().
object_element
template<typename BasicJsonType > BasicJsonType * nlohmann::detail::json_sax_dom_parser< BasicJsonType >::object_element = nullptr private
helper to hold the reference for the next object element
Definition at line 319 of file json_sax.hpp.
Referenced by nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value(), and nlohmann::detail::json_sax_dom_parser< BasicJsonType >::key().
ref_stack
template<typename BasicJsonType > std::vector< BasicJsonType * > nlohmann::detail::json_sax_dom_parser< BasicJsonType >::ref_stack {} private
stack to model hierarchy of values
Definition at line 317 of file json_sax.hpp.
Referenced by nlohmann::detail::json_sax_dom_parser< BasicJsonType >::end_array(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::end_object(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::key(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::start_array(), and nlohmann::detail::json_sax_dom_parser< BasicJsonType >::start_object().
root
template<typename BasicJsonType > BasicJsonType & nlohmann::detail::json_sax_dom_parser< BasicJsonType >::root private
the parsed JSON value
Definition at line 315 of file json_sax.hpp.
Referenced by nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value().
The documentation for this class was generated from the following files:
mc_orchestrator/json-3.7.3/include/nlohmann/detail/input/json_sax.hpp
mc_orchestrator/json-3.7.3/single_include/nlohmann/json.hpp