Mixed Criticality Orchestrator: nlohmann::detail::json_reverse_iterator< Base > Class Template Reference
nlohmann::detail::json_reverse_iterator< Base > Class Template Reference
a template for a reverse iterator class
#include <json_reverse_iterator.hpp>
Public Types
using difference_type = std::ptrdiff_t
using base_iterator = std::reverse_iterator< Base >
shortcut to the reverse iterator adapter
using reference = typename Base::reference
the reference type for the pointed-to element
using difference_type = std::ptrdiff_t
using base_iterator = std::reverse_iterator< Base >
shortcut to the reverse iterator adapter
using reference = typename Base::reference
the reference type for the pointed-to element
Public Member Functions
json_reverse_iterator (const typename base_iterator::iterator_type &it) noexcept
create reverse iterator from iterator
json_reverse_iterator (const base_iterator &it) noexcept
create reverse iterator from base class
const json_reverse_iterator operator++ (int)
post-increment (it++)
json_reverse_iterator & operator++ ()
pre-increment (++it)
const json_reverse_iterator operator-- (int)
post-decrement (it–)
json_reverse_iterator & operator-- ()
pre-decrement (–it)
json_reverse_iterator & operator+= (difference_type i)
add to iterator
json_reverse_iterator operator+ (difference_type i) const
add to iterator
json_reverse_iterator operator- (difference_type i) const
subtract from iterator
difference_type operator- (const json_reverse_iterator &other) const
return difference
reference operator[] (difference_type n) const
access to successor
auto key () const -> decltype(std::declval< Base >().key())
return the key of an object iterator
reference value () const
return the value of an iterator
json_reverse_iterator (const typename base_iterator::iterator_type &it) noexcept
create reverse iterator from iterator
json_reverse_iterator (const base_iterator &it) noexcept
create reverse iterator from base class
const json_reverse_iterator operator++ (int)
post-increment (it++)
json_reverse_iterator & operator++ ()
pre-increment (++it)
const json_reverse_iterator operator-- (int)
post-decrement (it–)
json_reverse_iterator & operator-- ()
pre-decrement (–it)
json_reverse_iterator & operator+= (difference_type i)
add to iterator
json_reverse_iterator operator+ (difference_type i) const
add to iterator
json_reverse_iterator operator- (difference_type i) const
subtract from iterator
difference_type operator- (const json_reverse_iterator &other) const
return difference
reference operator[] (difference_type n) const
access to successor
auto key () const -> decltype(std::declval< Base >().key())
return the key of an object iterator
reference value () const
return the value of an iterator
Detailed Description
template<typename Base>
class nlohmann::detail::json_reverse_iterator< Base >
a template for a reverse iterator class
Template Parameters
Base the base iterator type to reverse. Valid types are iterator (to create reverse_iterator) and const_iterator (to create const_reverse_iterator).
@requirement The class satisfies the following concept requirements:
BidirectionalIterator: The iterator that can be moved can be moved in both directions (i.e. incremented and decremented).
OutputIterator: It is possible to write to the pointed-to element (only if Base is iterator).
Since
version 1.0.0
Definition at line 34 of file json_reverse_iterator.hpp.
Member Typedef Documentation
base_iterator [1/2]
template<typename Base > using nlohmann::detail::json_reverse_iterator< Base >::base_iterator = std::reverse_iterator<Base>
shortcut to the reverse iterator adapter
Definition at line 39 of file json_reverse_iterator.hpp.
base_iterator [2/2]
template<typename Base > using nlohmann::detail::json_reverse_iterator< Base >::base_iterator = std::reverse_iterator<Base>
shortcut to the reverse iterator adapter
Definition at line 9987 of file json.hpp.
difference_type [1/2]
template<typename Base > using nlohmann::detail::json_reverse_iterator< Base >::difference_type = std::ptrdiff_t
Definition at line 37 of file json_reverse_iterator.hpp.
difference_type [2/2]
template<typename Base > using nlohmann::detail::json_reverse_iterator< Base >::difference_type = std::ptrdiff_t
Definition at line 9985 of file json.hpp.
reference [1/2]
template<typename Base > using nlohmann::detail::json_reverse_iterator< Base >::reference = typename Base::reference
the reference type for the pointed-to element
Definition at line 41 of file json_reverse_iterator.hpp.
reference [2/2]
template<typename Base > using nlohmann::detail::json_reverse_iterator< Base >::reference = typename Base::reference
the reference type for the pointed-to element
Definition at line 9989 of file json.hpp.
Constructor & Destructor Documentation
json_reverse_iterator() [1/4]
template<typename Base > nlohmann::detail::json_reverse_iterator< Base >::json_reverse_iterator (const typename base_iterator::iterator_type & it) inline explicit noexcept
create reverse iterator from iterator
Definition at line 44 of file json_reverse_iterator.hpp.
         : base_iterator(it) {}
json_reverse_iterator() [2/4]
template<typename Base > nlohmann::detail::json_reverse_iterator< Base >::json_reverse_iterator (const base_iterator & it) inline explicit noexcept
create reverse iterator from base class
Definition at line 48 of file json_reverse_iterator.hpp.
 : base_iterator(it) {}
json_reverse_iterator() [3/4]
template<typename Base > nlohmann::detail::json_reverse_iterator< Base >::json_reverse_iterator (const typename base_iterator::iterator_type & it) inline explicit noexcept
create reverse iterator from iterator
Definition at line 9992 of file json.hpp.
         : base_iterator(it) {}
json_reverse_iterator() [4/4]
template<typename Base > nlohmann::detail::json_reverse_iterator< Base >::json_reverse_iterator (const base_iterator & it) inline explicit noexcept
create reverse iterator from base class
Definition at line 9996 of file json.hpp.
 : base_iterator(it) {}
Member Function Documentation
key() [1/2]
template<typename Base > auto nlohmann::detail::json_reverse_iterator< Base >::key () const -> decltype(std::declval<Base>().key()) inline
return the key of an object iterator
Definition at line 105 of file json_reverse_iterator.hpp.
     {
         auto it = --this->base();
         return it.key();
     }
key() [2/2]
template<typename Base > auto nlohmann::detail::json_reverse_iterator< Base >::key () const -> decltype(std::declval<Base>().key()) inline
return the key of an object iterator
Definition at line 10053 of file json.hpp.
     {
         auto it = --this->base();
         return it.key();
     }
operator+() [1/2]
template<typename Base > json_reverse_iterator nlohmann::detail::json_reverse_iterator< Base >::operator+ (difference_type i) const inline
add to iterator
Definition at line 81 of file json_reverse_iterator.hpp.
     {
         return static_cast<json_reverse_iterator>(base_iterator::operator+(i));
     }
Referenced by nlohmann::detail::json_reverse_iterator< Base >::operator[]().
operator+() [2/2]
template<typename Base > json_reverse_iterator nlohmann::detail::json_reverse_iterator< Base >::operator+ (difference_type i) const inline
add to iterator
Definition at line 10029 of file json.hpp.
     {
         return static_cast<json_reverse_iterator>(base_iterator::operator+(i));
     }
operator++() [1/4]
template<typename Base > json_reverse_iterator& nlohmann::detail::json_reverse_iterator< Base >::operator++ () inline
pre-increment (++it)
Definition at line 57 of file json_reverse_iterator.hpp.
     {
         return static_cast<json_reverse_iterator&>(base_iterator::operator++());
     }
operator++() [2/4]
template<typename Base > json_reverse_iterator& nlohmann::detail::json_reverse_iterator< Base >::operator++ () inline
pre-increment (++it)
Definition at line 10005 of file json.hpp.
     {
         return static_cast<json_reverse_iterator&>(base_iterator::operator++());
     }
operator++() [3/4]
template<typename Base > const json_reverse_iterator nlohmann::detail::json_reverse_iterator< Base >::operator++ (int) inline
post-increment (it++)
Definition at line 51 of file json_reverse_iterator.hpp.
     {
         return static_cast<json_reverse_iterator>(base_iterator::operator++(1));
     }
operator++() [4/4]
template<typename Base > const json_reverse_iterator nlohmann::detail::json_reverse_iterator< Base >::operator++ (int) inline
post-increment (it++)
Definition at line 9999 of file json.hpp.
     {
         return static_cast<json_reverse_iterator>(base_iterator::operator++(1));
     }
operator+=() [1/2]
template<typename Base > json_reverse_iterator& nlohmann::detail::json_reverse_iterator< Base >::operator+= (difference_type i) inline
add to iterator
Definition at line 75 of file json_reverse_iterator.hpp.
     {
         return static_cast<json_reverse_iterator&>(base_iterator::operator+=(i));
     }
operator+=() [2/2]
template<typename Base > json_reverse_iterator& nlohmann::detail::json_reverse_iterator< Base >::operator+= (difference_type i) inline
add to iterator
Definition at line 10023 of file json.hpp.
     {
         return static_cast<json_reverse_iterator&>(base_iterator::operator+=(i));
     }
operator-() [1/4]
template<typename Base > difference_type nlohmann::detail::json_reverse_iterator< Base >::operator- (const json_reverse_iterator< Base > & other) const inline
return difference
Definition at line 93 of file json_reverse_iterator.hpp.
     {
         return base_iterator(*this) - base_iterator(other);
     }
operator-() [2/4]
template<typename Base > difference_type nlohmann::detail::json_reverse_iterator< Base >::operator- (const json_reverse_iterator< Base > & other) const inline
return difference
Definition at line 10041 of file json.hpp.
     {
         return base_iterator(*this) - base_iterator(other);
     }
operator-() [3/4]
template<typename Base > json_reverse_iterator nlohmann::detail::json_reverse_iterator< Base >::operator- (difference_type i) const inline
subtract from iterator
Definition at line 87 of file json_reverse_iterator.hpp.
     {
         return static_cast<json_reverse_iterator>(base_iterator::operator-(i));
     }
operator-() [4/4]
template<typename Base > json_reverse_iterator nlohmann::detail::json_reverse_iterator< Base >::operator- (difference_type i) const inline
subtract from iterator
Definition at line 10035 of file json.hpp.
     {
         return static_cast<json_reverse_iterator>(base_iterator::operator-(i));
     }
operator--() [1/4]
template<typename Base > json_reverse_iterator& nlohmann::detail::json_reverse_iterator< Base >::operator-- () inline
pre-decrement (–it)
Definition at line 69 of file json_reverse_iterator.hpp.
     {
         return static_cast<json_reverse_iterator&>(base_iterator::operator--());
     }
operator--() [2/4]
template<typename Base > json_reverse_iterator& nlohmann::detail::json_reverse_iterator< Base >::operator-- () inline
pre-decrement (–it)
Definition at line 10017 of file json.hpp.
     {
         return static_cast<json_reverse_iterator&>(base_iterator::operator--());
     }
operator--() [3/4]
template<typename Base > const json_reverse_iterator nlohmann::detail::json_reverse_iterator< Base >::operator-- (int) inline
post-decrement (it–)
Definition at line 63 of file json_reverse_iterator.hpp.
     {
         return static_cast<json_reverse_iterator>(base_iterator::operator--(1));
     }
operator--() [4/4]
template<typename Base > const json_reverse_iterator nlohmann::detail::json_reverse_iterator< Base >::operator-- (int) inline
post-decrement (it–)
Definition at line 10011 of file json.hpp.
     {
         return static_cast<json_reverse_iterator>(base_iterator::operator--(1));
     }
operator[]() [1/2]
template<typename Base > reference nlohmann::detail::json_reverse_iterator< Base >::operator[] (difference_type n) const inline
access to successor
Definition at line 99 of file json_reverse_iterator.hpp.
     {
         return *(this->operator+(n));
     }
References nlohmann::detail::json_reverse_iterator< Base >::operator+().
operator[]() [2/2]
template<typename Base > reference nlohmann::detail::json_reverse_iterator< Base >::operator[] (difference_type n) const inline
access to successor
Definition at line 10047 of file json.hpp.
     {
         return *(this->operator+(n));
     }
References nlohmann::detail::json_reverse_iterator< Base >::operator+().
value() [1/2]
template<typename Base > reference nlohmann::detail::json_reverse_iterator< Base >::value () const inline
return the value of an iterator
Definition at line 112 of file json_reverse_iterator.hpp.
     {
         auto it = --this->base();
         return it.operator * ();
     }
Referenced by TEST_CASE().
value() [2/2]
template<typename Base > reference nlohmann::detail::json_reverse_iterator< Base >::value () const inline
return the value of an iterator
Definition at line 10060 of file json.hpp.
     {
         auto it = --this->base();
         return it.operator * ();
     }
The documentation for this class was generated from the following files:
mc_orchestrator/json-3.7.3/include/nlohmann/detail/iterators/json_reverse_iterator.hpp
mc_orchestrator/json-3.7.3/single_include/nlohmann/json.hpp