Mixed Criticality Orchestrator: ConfigHandler Class Reference
ConfigHandler Class Reference
ConfigHandler updates all the config paramneters from config.json file.
#include <mco_config_handler.hpp>
Public Member Functions
bool GetValue ()
get the value from containerManagement.conf file based on key
bool SaveAppNameToDatabase ()
Save the app name to the database.
bool SaveAppNameToDatabase (const std::string &, std::unordered_set< std::string > &, const std::string &)
Save the app name to the database.
bool SaveFileContentToDatabase (const std::string &)
Save app JSON file content to database.
bool UpdateDatabase (const std::string &)
Save the initial JSON file content to the database.
bool UpdateDatabase (const std::string &, const std::string &, const std::string &, const std::string &)
Save the initial JSON file content to the database.
ConfigHandler ()=default
Default constructor.
~ConfigHandler ()=default
Default destructor.
Detailed Description
ConfigHandler updates all the config paramneters from config.json file.
Definition at line 14 of file mco_config_handler.hpp.
Constructor & Destructor Documentation
ConfigHandler()
ConfigHandler::ConfigHandler () default
Default constructor.
~ConfigHandler()
ConfigHandler::~ConfigHandler () default
Default destructor.
Member Function Documentation
GetValue()
bool ConfigHandler::GetValue ()
get the value from containerManagement.conf file based on key
Returns
flag status
Definition at line 105 of file mco_config_handler.cpp.
 {
     std::ifstream file("../data/config.json");
     if (!file.is_open()) {
         string msg = "Failed to open config file";
         // LOG(ERROR) << msg;
         return false;
     }
     nlohmann::json jsonObj;
     file >> jsonObj;
     // Reading the json file and storing the values in a map
     for (auto it = jsonObj.begin(); it != jsonObj.end(); ++it) {
         std::string key = it.key();
         std::string value = it.value();
         config_parameters[key] = value;
     }
     file.close();
     if(config_parameters["container_runtime"] == "k3s") {
         kAppFileDownloadPath = kYamlFilePath;
     } else if(config_parameters["container_runtime"] == "podman") {
         kAppFileDownloadPath = kYamlFilePath;
     } else if(config_parameters["container_runtime"] == "bluechi") {
         std::cout << "Bluechi is selected" << std::endl;
     } else {
         // LOG(FATAL) << "Invalid container runtime";
     }
     // Update the database with the ASIL apps template
     kPath = kAsilAllAppsPath;
     UpdateDatabase(kPath);
     // // Save the JSON parameters to the database
     // for (const auto& entry : std::filesystem::directory_iterator(kAsilBAppsPath)) {
     //     if (entry.path().extension() == ".json") {
     //         // Save the content of the file to the database
     //         SaveFileContentToDatabase(entry.path());
     //     }
     // }
     // Update the database with the QM Infotainment apps based on OEM cloud
     kPath = kQmInfoAllApps;
     UpdateDatabase(kPath);
     // // Save the JSON parameters to the database
     // for (const auto& entry : std::filesystem::directory_iterator(kQmInfoGames)) {
     //     if (entry.path().extension() == ".json") {
     //         // Save the content of the file to the database
     //         SaveFileContentToDatabase(entry.path());
     //     }
     // }
     // Update the database with vehicle_info details
     kPath = kVehicleInfoPath;
     UpdateDatabase(kPath);
     // Update the database with ASIL B apps
     kPath = kAsilBAppsPath;
     UpdateDatabase(asil, "b", "downloaded", kPath);
     SaveAppNameToDatabase(kAsilBAvailableApps, DatabaseHandler::GetInstance().asil_b_available_, kPath);
      // Update the database with QM Games apps
      kPath = kQmInfoGames;
      UpdateDatabase(infotainment, "games", "downloaded", kPath);
      SaveAppNameToDatabase(kQmInfoGamesAvailableApps, DatabaseHandler::GetInstance().qm_infotainment_games_available_, kPath);
     // Update the database with QM Ott apps
     kPath = kQmInfoOtt;
     UpdateDatabase(infotainment, "ott", "downloaded", kPath);
     SaveAppNameToDatabase(kQmInfoOttAvailableApps, DatabaseHandler::GetInstance().qm_infotainment_ott_available_, kPath);
     DatabaseHandler::GetInstance().AddData(available_qm_app, "");
     DatabaseHandler::GetInstance().AddData(ota_downloaded_qm_app, "");
     DatabaseHandler::GetInstance().AddData(infotainment_selection, "");
     DatabaseHandler::GetInstance().AddData(vehiclestate_selection, "");
     DatabaseHandler::GetInstance().AddData(lack_of_resources, "");
     DatabaseHandler::GetInstance().AddData(vehicle_drive_mode, "");
     DatabaseHandler::GetInstance().AddData(resource_management_log, "null");
     // Delete any exisiting ASIL apps
     Invoker invoker;
     list<string> available_apps = DatabaseHandler::GetInstance().ReadListData(kAsilBAvailableApps);
     string container_runtime = config_parameters["container_runtime"];
     for (const auto& app : available_apps) {
         invoker.SetCommand(CommandFactory::CreateCommand(container_runtime, "DeleteAsilPod", app));
         if(!invoker.Invoke()) {
             string msg = "Failed to spawn pod";
             cout << msg << endl;
             // LOG(ERROR) << msg;
         }
     }
     // for (const auto& app : available_apps) {
     //     invoker.SetCommand(CommandFactory::CreateCommand(container_runtime, "ApplyAsilPod", app));
     //     if(!invoker.Invoke()) {
     //         string msg = "Failed to spawn pod";
     //         cout << msg << endl;
     //         // LOG(ERROR) << msg;
     //     }
     // }
     // for (const auto& app : available_apps) {
     //     string command = "sudo podman pause " + app;
     //     int ret = system(command.c_str());
     //     if (ret != 0) {
     //         cout << "Failed to pause pod: " << app << endl;
     //     }
         // invoker.SetCommand(CommandFactory::CreateCommand(container_runtime, "AsilPodUsage", app));
         // if(!invoker.Invoke()) {
         //     string msg = "Failed to get pod usage";
         //     cout << msg << endl;
         //     // LOG(ERROR) << msg;
         // }
         // updateResources("asil", app, false);
     //     DatabaseHandler::GetInstance().asil_b_paused_apps_.emplace(app);
     //     DatabaseHandler::GetInstance().UpdateRunningApps(kAsilPausedApps, DatabaseHandler::GetInstance().asil_b_paused_apps_);
     //     DatabaseHandler::GetInstance().asil_b_running_apps_.erase(app);
     //     DatabaseHandler::GetInstance().UpdateRunningApps(kAsilRunningApps, DatabaseHandler::GetInstance().asil_b_running_apps_);
     // }
     //asil_initial_memory_updated = true;
     // // Save the JSON parameters to the database
     // for (const auto& entry : std::filesystem::directory_iterator(kAppFileDownloadPath)) {
     //     if (entry.path().extension() == ".json") {
     //         // Save the content of the file to the database
     //         SaveFileContentToDatabase(entry.path());
     //     }
     // }
     // // Add the app name to the list of running apps
     // SaveAppNameToDatabase();
     //Update database with system resources and available resources
     updateInitialSystemResources();
     allocateQmResources(QM_ALLOCATION_PARK_STATE);
     return true;
 }
References DatabaseHandler::AddData(), allocateQmResources(), asil, available_qm_app, config_parameters, CommandFactory::CreateCommand(), DatabaseHandler::GetInstance(), infotainment, infotainment_selection, Invoker::Invoke(), kAppFileDownloadPath, kAsilAllAppsPath, kAsilBAppsPath, kAsilBAvailableApps, kPath, kQmInfoAllApps, kQmInfoGames, kQmInfoGamesAvailableApps, kQmInfoOtt, kQmInfoOttAvailableApps, kVehicleInfoPath, kYamlFilePath, lack_of_resources, ota_downloaded_qm_app, QM_ALLOCATION_PARK_STATE, DatabaseHandler::ReadListData(), resource_management_log, Invoker::SetCommand(), updateInitialSystemResources(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::value(), vehicle_drive_mode, and vehiclestate_selection.
Referenced by main().
SaveAppNameToDatabase() [1/2]
bool ConfigHandler::SaveAppNameToDatabase ()
Save the app name to the database.
Returns
flag status
Definition at line 39 of file mco_config_handler.cpp.
{
     string app_name = "";
     for (const auto& entry : std::filesystem::directory_iterator(kAppFileDownloadPath)) {
         if (entry.path().extension() == ".json") {
             // Add the app name to the list of running apps
             app_name = entry.path().filename().string();
             app_name = app_name.substr(0, app_name.find_last_of("."));
             DatabaseHandler::GetInstance().running_apps_.emplace(app_name);
         }
     }
     DatabaseHandler::GetInstance().UpdateRunningApps(kRunningApps, DatabaseHandler::GetInstance().running_apps_);
     return true;
 }
References DatabaseHandler::GetInstance(), kAppFileDownloadPath, kRunningApps, DatabaseHandler::running_apps_, and DatabaseHandler::UpdateRunningApps().
Referenced by QmOtaHandler::OtaDownloadSuccessful(), and RespawnPodObserver::RespawnAllPods().
SaveAppNameToDatabase() [2/2]
bool ConfigHandler::SaveAppNameToDatabase (const std::string & apps_key, std::unordered_set< std::string > & apps_set, const std::string & path)
Save the app name to the database.
Parameters
app key, app set in datahandler, folder path
Returns
flag status
Definition at line 53 of file mco_config_handler.cpp.
{
     string app_name = "";
     for (const auto& entry : std::filesystem::directory_iterator(path)) {
         if (entry.path().extension() == ".json") {
             // Add the app name to the list of running apps
             app_name = entry.path().filename().string();
             app_name = app_name.substr(0, app_name.find_last_of("."));
             apps_set.emplace(app_name);
         }
     }
     DatabaseHandler::GetInstance().UpdateRunningApps(apps_key, apps_set);
     return true;
 }
References DatabaseHandler::GetInstance(), and DatabaseHandler::UpdateRunningApps().
SaveFileContentToDatabase()
bool ConfigHandler::SaveFileContentToDatabase (const std::string & filePath)
Save app JSON file content to database.
Parameters
location of the app JSON file
Returns
flag status
Definition at line 19 of file mco_config_handler.cpp.
{
     std::ifstream file(filePath);
     if (!file.is_open()) {
         std::cerr << "Failed to open file: " << filePath << '\n';
         return false;
     }
     std::string jsonString((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
     // Parse the JSON string and save in database
     nlohmann::json data = nlohmann::json::parse(jsonString);
     string app_name = "";
     for (auto& element : data.items()) {
         app_name = element.key();
     }
     DatabaseHandler::GetInstance().SaveData( app_name, data[app_name]);
     file.close();
     return true;
 }
References DatabaseHandler::GetInstance(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::items(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parse(), and DatabaseHandler::SaveData().
Referenced by ServerHandler::StartMcOrchestratorServer().
UpdateDatabase() [1/2]
bool ConfigHandler::UpdateDatabase (const std::string & path)
Save the initial JSON file content to the database.
Parameters
location of the JSON file
Returns
flag status
Definition at line 67 of file mco_config_handler.cpp.
{
     for (const auto& entry : std::filesystem::directory_iterator(path)) {
         if (entry.path().extension() == ".json") {
             std::ifstream file(entry.path());
             if (!file.is_open()) {
                 std::cerr << "Could not open file: " << entry.path() << std::endl;
                 continue;
             }
             nlohmann::json jsonData;
             try {
                 file >> jsonData;
             } catch (const nlohmann::json::parse_error& e) {
                 std::cerr << "JSON parse error in file " << entry.path() << ": " << e.what() << std::endl;
                 continue;
             }
             // Create a key in Redis with the name of the file (without extension)
             std::string key = entry.path().stem().string();
             // Save the JSON data to the database
             DatabaseHandler::GetInstance().SaveData(key, jsonData);
         }
     }
     return true;
 }
References DatabaseHandler::GetInstance(), DatabaseHandler::SaveData(), and nlohmann::detail::exception::what().
UpdateDatabase() [2/2]
bool ConfigHandler::UpdateDatabase (const std::string & app_type, const std::string & app_category, const std::string & app_key, const std::string & path)
Save the initial JSON file content to the database.
Parameters
location of the JSON file
Returns
flag status
Definition at line 94 of file mco_config_handler.cpp.
{
     std::string asil_data_str = DatabaseHandler::GetInstance().AppendData(app_type, app_category, app_key, path);
     if(asil_data_str.empty()) {
         std::cerr << "Failed to append data to the database" << std::endl;
         return false;
     }
     return true;
 }
References DatabaseHandler::AppendData(), and DatabaseHandler::GetInstance().
The documentation for this class was generated from the following files:
mc_orchestrator/common/inc/mco_config_handler.hpp
mc_orchestrator/common/src/mco_config_handler.cpp