Mixed Criticality Orchestrator: nlohmann::detail::parser< BasicJsonType > Class Template Reference
nlohmann::detail::parser< BasicJsonType > Class Template Reference
syntax analysis
#include <parser.hpp>
Public Types
enum parse_event_t : uint8_t {
parse_event_t::object_start, parse_event_t::object_end, parse_event_t::array_start, parse_event_t::array_end,
parse_event_t::key, parse_event_t::value, parse_event_t::object_start, parse_event_t::object_end,
parse_event_t::array_start, parse_event_t::array_end, parse_event_t::key, parse_event_t::value
}
enum parse_event_t : uint8_t {
parse_event_t::object_start, parse_event_t::object_end, parse_event_t::array_start, parse_event_t::array_end,
parse_event_t::key, parse_event_t::value, parse_event_t::object_start, parse_event_t::object_end,
parse_event_t::array_start, parse_event_t::array_end, parse_event_t::key, parse_event_t::value
}
using parser_callback_t = std::function< bool(int depth, parse_event_t event, BasicJsonType &parsed)>
using parser_callback_t = std::function< bool(int depth, parse_event_t event, BasicJsonType &parsed)>
Public Member Functions
parser (detail::input_adapter_t &&adapter, const parser_callback_t cb=nullptr, const bool allow_exceptions_=true)
a parser reading from an input adapter
void parse (const bool strict, BasicJsonType &result)
public parser interface
bool accept (const bool strict=true)
public accept interface
template<typename SAX >
bool sax_parse (SAX *sax, const bool strict=true)
parser (detail::input_adapter_t &&adapter, const parser_callback_t cb=nullptr, const bool allow_exceptions_=true)
a parser reading from an input adapter
void parse (const bool strict, BasicJsonType &result)
public parser interface
bool accept (const bool strict=true)
public accept interface
template<typename SAX >
bool sax_parse (SAX *sax, const bool strict=true)
Private Types
using number_integer_t = typename BasicJsonType::number_integer_t
using number_unsigned_t = typename BasicJsonType::number_unsigned_t
using number_float_t = typename BasicJsonType::number_float_t
using string_t = typename BasicJsonType::string_t
using lexer_t = lexer< BasicJsonType >
using token_type = typename lexer_t::token_type
using number_integer_t = typename BasicJsonType::number_integer_t
using number_unsigned_t = typename BasicJsonType::number_unsigned_t
using number_float_t = typename BasicJsonType::number_float_t
using string_t = typename BasicJsonType::string_t
using lexer_t = lexer< BasicJsonType >
using token_type = typename lexer_t::token_type
Private Member Functions
template<typename SAX >
bool sax_parse_internal (SAX *sax)
token_type get_token ()
get next token from lexer
std::string exception_message (const token_type expected, const std::string &context)
template<typename SAX >
bool sax_parse_internal (SAX *sax)
token_type get_token ()
get next token from lexer
std::string exception_message (const token_type expected, const std::string &context)
Private Attributes
const parser_callback_t callback = nullptr
callback function
token_type last_token = token_type::uninitialized
the type of the last read token
lexer_t m_lexer
the lexer
const bool allow_exceptions = true
whether to throw exceptions in case of errors
Detailed Description
template<typename BasicJsonType>
class nlohmann::detail::parser< BasicJsonType >
syntax analysis
This class implements a recursive decent parser.
Definition at line 33 of file parser.hpp.
Member Typedef Documentation
lexer_t [1/2]
template<typename BasicJsonType > using nlohmann::detail::parser< BasicJsonType >::lexer_t = lexer<BasicJsonType> private
Definition at line 39 of file parser.hpp.
lexer_t [2/2]
template<typename BasicJsonType > using nlohmann::detail::parser< BasicJsonType >::lexer_t = lexer<BasicJsonType> private
Definition at line 8690 of file json.hpp.
number_float_t [1/2]
template<typename BasicJsonType > using nlohmann::detail::parser< BasicJsonType >::number_float_t = typename BasicJsonType::number_float_t private
Definition at line 37 of file parser.hpp.
number_float_t [2/2]
template<typename BasicJsonType > using nlohmann::detail::parser< BasicJsonType >::number_float_t = typename BasicJsonType::number_float_t private
Definition at line 8688 of file json.hpp.
number_integer_t [1/2]
template<typename BasicJsonType > using nlohmann::detail::parser< BasicJsonType >::number_integer_t = typename BasicJsonType::number_integer_t private
Definition at line 35 of file parser.hpp.
number_integer_t [2/2]
template<typename BasicJsonType > using nlohmann::detail::parser< BasicJsonType >::number_integer_t = typename BasicJsonType::number_integer_t private
Definition at line 8686 of file json.hpp.
number_unsigned_t [1/2]
template<typename BasicJsonType > using nlohmann::detail::parser< BasicJsonType >::number_unsigned_t = typename BasicJsonType::number_unsigned_t private
Definition at line 36 of file parser.hpp.
number_unsigned_t [2/2]
template<typename BasicJsonType > using nlohmann::detail::parser< BasicJsonType >::number_unsigned_t = typename BasicJsonType::number_unsigned_t private
Definition at line 8687 of file json.hpp.
parser_callback_t [1/2]
template<typename BasicJsonType > using nlohmann::detail::parser< BasicJsonType >::parser_callback_t = std::function<bool(int depth, parse_event_t event, BasicJsonType& parsed)>
Definition at line 60 of file parser.hpp.
parser_callback_t [2/2]
template<typename BasicJsonType > using nlohmann::detail::parser< BasicJsonType >::parser_callback_t = std::function<bool(int depth, parse_event_t event, BasicJsonType& parsed)>
Definition at line 8711 of file json.hpp.
string_t [1/2]
template<typename BasicJsonType > using nlohmann::detail::parser< BasicJsonType >::string_t = typename BasicJsonType::string_t private
Definition at line 38 of file parser.hpp.
string_t [2/2]
template<typename BasicJsonType > using nlohmann::detail::parser< BasicJsonType >::string_t = typename BasicJsonType::string_t private
Definition at line 8689 of file json.hpp.
token_type [1/2]
template<typename BasicJsonType > using nlohmann::detail::parser< BasicJsonType >::token_type = typename lexer_t::token_type private
Definition at line 40 of file parser.hpp.
token_type [2/2]
template<typename BasicJsonType > using nlohmann::detail::parser< BasicJsonType >::token_type = typename lexer_t::token_type private
Definition at line 8691 of file json.hpp.
Member Enumeration Documentation
parse_event_t [1/2]
template<typename BasicJsonType > enum nlohmann::detail::parser::parse_event_t : uint8_t strong
Enumerator
object_start
the parser read { and started to process a JSON object
object_end
the parser read } and finished processing a JSON object
array_start
the parser read [ and started to process a JSON array
array_end
the parser read ] and finished processing a JSON array
key
the parser read a key of a value in an object
value
the parser finished reading a JSON value
object_start
the parser read { and started to process a JSON object
object_end
the parser read } and finished processing a JSON object
array_start
the parser read [ and started to process a JSON array
array_end
the parser read ] and finished processing a JSON array
key
the parser read a key of a value in an object
value
the parser finished reading a JSON value
Definition at line 43 of file parser.hpp.
                              : uint8_t
     {
         object_start,
         object_end,
         array_start,
         array_end,
         key,
         value
     };
parse_event_t [2/2]
template<typename BasicJsonType > enum nlohmann::detail::parser::parse_event_t : uint8_t strong
Enumerator
object_start
the parser read { and started to process a JSON object
object_end
the parser read } and finished processing a JSON object
array_start
the parser read [ and started to process a JSON array
array_end
the parser read ] and finished processing a JSON array
key
the parser read a key of a value in an object
value
the parser finished reading a JSON value
object_start
the parser read { and started to process a JSON object
object_end
the parser read } and finished processing a JSON object
array_start
the parser read [ and started to process a JSON array
array_end
the parser read ] and finished processing a JSON array
key
the parser read a key of a value in an object
value
the parser finished reading a JSON value
Definition at line 8694 of file json.hpp.
                              : uint8_t
     {
         object_start,
         object_end,
         array_start,
         array_end,
         key,
         value
     };
Constructor & Destructor Documentation
parser() [1/2]
template<typename BasicJsonType > nlohmann::detail::parser< BasicJsonType >::parser (detail::input_adapter_t && adapter, const parser_callback_t cb = nullptr, const bool allow_exceptions_ = true) inline explicit
a parser reading from an input adapter
Definition at line 63 of file parser.hpp.
         : callback(cb), m_lexer(std::move(adapter)), allow_exceptions(allow_exceptions_)
     {
         // read first token
         get_token();
     }
References nlohmann::detail::parser< BasicJsonType >::get_token().
parser() [2/2]
template<typename BasicJsonType > nlohmann::detail::parser< BasicJsonType >::parser (detail::input_adapter_t && adapter, const parser_callback_t cb = nullptr, const bool allow_exceptions_ = true) inline explicit
a parser reading from an input adapter
Definition at line 8714 of file json.hpp.
         : callback(cb), m_lexer(std::move(adapter)), allow_exceptions(allow_exceptions_)
     {
         // read first token
         get_token();
     }
References nlohmann::detail::parser< BasicJsonType >::get_token().
Member Function Documentation
accept() [1/2]
template<typename BasicJsonType > bool nlohmann::detail::parser< BasicJsonType >::accept (const bool strict = true) inline
public accept interface
Parameters
[in] strict whether to expect the last token to be EOF
Returns
whether the input is a proper JSON text
Definition at line 143 of file parser.hpp.
     {
         json_sax_acceptor<BasicJsonType> sax_acceptor;
         return sax_parse(&sax_acceptor, strict);
     }
References nlohmann::detail::parser< BasicJsonType >::sax_parse(), and nlohmann::detail::strict.
Referenced by TEST_CASE().
accept() [2/2]
template<typename BasicJsonType > bool nlohmann::detail::parser< BasicJsonType >::accept (const bool strict = true) inline
public accept interface
Parameters
[in] strict whether to expect the last token to be EOF
Returns
whether the input is a proper JSON text
Definition at line 8794 of file json.hpp.
     {
         json_sax_acceptor<BasicJsonType> sax_acceptor;
         return sax_parse(&sax_acceptor, strict);
     }
References nlohmann::detail::parser< BasicJsonType >::sax_parse(), and nlohmann::detail::strict.
exception_message() [1/2]
template<typename BasicJsonType > std::string nlohmann::detail::parser< BasicJsonType >::exception_message (const token_type expected, const std::string & context) inline private
Definition at line 458 of file parser.hpp.
     {
         std::string error_msg = "syntax error ";
         if (not context.empty())
         {
             error_msg += "while parsing " + context + " ";
         }
         error_msg += "- ";
         if (last_token == token_type::parse_error)
         {
             error_msg += std::string(m_lexer.get_error_message()) + "; last read: '" +
                          m_lexer.get_token_string() + "'";
         }
         else
         {
             error_msg += "unexpected " + std::string(lexer_t::token_type_name(last_token));
         }
         if (expected != token_type::uninitialized)
         {
             error_msg += "; expected " + std::string(lexer_t::token_type_name(expected));
         }
         return error_msg;
     }
References nlohmann::detail::lexer< BasicJsonType >::get_error_message(), nlohmann::detail::lexer< BasicJsonType >::get_token_string(), nlohmann::detail::parser< BasicJsonType >::last_token, nlohmann::detail::parser< BasicJsonType >::m_lexer, and nlohmann::detail::lexer< BasicJsonType >::token_type_name().
Referenced by nlohmann::detail::parser< BasicJsonType >::parse(), nlohmann::detail::parser< BasicJsonType >::sax_parse(), and nlohmann::detail::parser< BasicJsonType >::sax_parse_internal().
exception_message() [2/2]
template<typename BasicJsonType > std::string nlohmann::detail::parser< BasicJsonType >::exception_message (const token_type expected, const std::string & context) inline private
Definition at line 9109 of file json.hpp.
     {
         std::string error_msg = "syntax error ";
         if (not context.empty())
         {
             error_msg += "while parsing " + context + " ";
         }
         error_msg += "- ";
         if (last_token == token_type::parse_error)
         {
             error_msg += std::string(m_lexer.get_error_message()) + "; last read: '" +
                          m_lexer.get_token_string() + "'";
         }
         else
         {
             error_msg += "unexpected " + std::string(lexer_t::token_type_name(last_token));
         }
         if (expected != token_type::uninitialized)
         {
             error_msg += "; expected " + std::string(lexer_t::token_type_name(expected));
         }
         return error_msg;
     }
References nlohmann::detail::lexer< BasicJsonType >::get_error_message(), nlohmann::detail::lexer< BasicJsonType >::get_token_string(), nlohmann::detail::parser< BasicJsonType >::last_token, nlohmann::detail::parser< BasicJsonType >::m_lexer, and nlohmann::detail::lexer< BasicJsonType >::token_type_name().
get_token() [1/2]
template<typename BasicJsonType > token_type nlohmann::detail::parser< BasicJsonType >::get_token () inline private
get next token from lexer
Definition at line 453 of file parser.hpp.
     {
         return last_token = m_lexer.scan();
     }
References nlohmann::detail::parser< BasicJsonType >::last_token, nlohmann::detail::parser< BasicJsonType >::m_lexer, and nlohmann::detail::lexer< BasicJsonType >::scan().
Referenced by nlohmann::detail::parser< BasicJsonType >::parse(), nlohmann::detail::parser< BasicJsonType >::parser(), nlohmann::detail::parser< BasicJsonType >::sax_parse(), and nlohmann::detail::parser< BasicJsonType >::sax_parse_internal().
get_token() [2/2]
template<typename BasicJsonType > token_type nlohmann::detail::parser< BasicJsonType >::get_token () inline private
get next token from lexer
Definition at line 9104 of file json.hpp.
     {
         return last_token = m_lexer.scan();
     }
References nlohmann::detail::parser< BasicJsonType >::last_token, nlohmann::detail::parser< BasicJsonType >::m_lexer, and nlohmann::detail::lexer< BasicJsonType >::scan().
parse() [1/2]
template<typename BasicJsonType > void nlohmann::detail::parser< BasicJsonType >::parse (const bool strict, BasicJsonType & result) inline
public parser interface
Parameters
[in] strict whether to expect the last token to be EOF
[in,out] result parsed JSON value
Exceptions
parse_error.101 in case of an unexpected token
parse_error.102 if to_unicode fails or surrogate error
parse_error.103 if to_unicode fails
Definition at line 82 of file parser.hpp.
     {
         if (callback)
         {
             json_sax_dom_callback_parser<BasicJsonType> sdp(result, callback, allow_exceptions);
             sax_parse_internal(&sdp);
             result.assert_invariant();
             // in strict mode, input must be completely read
             if (strict and (get_token() != token_type::end_of_input))
             {
                 sdp.parse_error(m_lexer.get_position(),
                                 m_lexer.get_token_string(),
                                 parse_error::create(101, m_lexer.get_position(),
                                                     exception_message(token_type::end_of_input, "value")));
             }
             // in case of an error, return discarded value
             if (sdp.is_errored())
             {
                 result = value_t::discarded;
                 return;
             }
             // set top-level value to null if it was discarded by the callback
             // function
             if (result.is_discarded())
             {
                 result = nullptr;
             }
         }
         else
         {
             json_sax_dom_parser<BasicJsonType> sdp(result, allow_exceptions);
             sax_parse_internal(&sdp);
             result.assert_invariant();
             // in strict mode, input must be completely read
             if (strict and (get_token() != token_type::end_of_input))
             {
                 sdp.parse_error(m_lexer.get_position(),
                                 m_lexer.get_token_string(),
                                 parse_error::create(101, m_lexer.get_position(),
                                                     exception_message(token_type::end_of_input, "value")));
             }
             // in case of an error, return discarded value
             if (sdp.is_errored())
             {
                 result = value_t::discarded;
                 return;
             }
         }
     }
References nlohmann::detail::parser< BasicJsonType >::allow_exceptions, nlohmann::detail::parser< BasicJsonType >::callback, nlohmann::detail::parse_error::create(), nlohmann::detail::discarded, nlohmann::detail::parser< BasicJsonType >::exception_message(), nlohmann::detail::lexer< BasicJsonType >::get_position(), nlohmann::detail::parser< BasicJsonType >::get_token(), nlohmann::detail::lexer< BasicJsonType >::get_token_string(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::is_errored(), nlohmann::detail::json_sax_dom_callback_parser< BasicJsonType >::is_errored(), nlohmann::detail::parser< BasicJsonType >::m_lexer, nlohmann::detail::json_sax_dom_parser< BasicJsonType >::parse_error(), nlohmann::detail::json_sax_dom_callback_parser< BasicJsonType >::parse_error(), result, nlohmann::detail::parser< BasicJsonType >::sax_parse_internal(), and nlohmann::detail::strict.
parse() [2/2]
template<typename BasicJsonType > void nlohmann::detail::parser< BasicJsonType >::parse (const bool strict, BasicJsonType & result) inline
public parser interface
Parameters
[in] strict whether to expect the last token to be EOF
[in,out] result parsed JSON value
Exceptions
parse_error.101 in case of an unexpected token
parse_error.102 if to_unicode fails or surrogate error
parse_error.103 if to_unicode fails
Definition at line 8733 of file json.hpp.
     {
         if (callback)
         {
             json_sax_dom_callback_parser<BasicJsonType> sdp(result, callback, allow_exceptions);
             sax_parse_internal(&sdp);
             result.assert_invariant();
             // in strict mode, input must be completely read
             if (strict and (get_token() != token_type::end_of_input))
             {
                 sdp.parse_error(m_lexer.get_position(),
                                 m_lexer.get_token_string(),
                                 parse_error::create(101, m_lexer.get_position(),
                                                     exception_message(token_type::end_of_input, "value")));
             }
             // in case of an error, return discarded value
             if (sdp.is_errored())
             {
                 result = value_t::discarded;
                 return;
             }
             // set top-level value to null if it was discarded by the callback
             // function
             if (result.is_discarded())
             {
                 result = nullptr;
             }
         }
         else
         {
             json_sax_dom_parser<BasicJsonType> sdp(result, allow_exceptions);
             sax_parse_internal(&sdp);
             result.assert_invariant();
             // in strict mode, input must be completely read
             if (strict and (get_token() != token_type::end_of_input))
             {
                 sdp.parse_error(m_lexer.get_position(),
                                 m_lexer.get_token_string(),
                                 parse_error::create(101, m_lexer.get_position(),
                                                     exception_message(token_type::end_of_input, "value")));
             }
             // in case of an error, return discarded value
             if (sdp.is_errored())
             {
                 result = value_t::discarded;
                 return;
             }
         }
     }
References nlohmann::detail::parser< BasicJsonType >::allow_exceptions, nlohmann::detail::parser< BasicJsonType >::callback, nlohmann::detail::parse_error::create(), nlohmann::detail::discarded, nlohmann::detail::parser< BasicJsonType >::exception_message(), nlohmann::detail::lexer< BasicJsonType >::get_position(), nlohmann::detail::parser< BasicJsonType >::get_token(), nlohmann::detail::lexer< BasicJsonType >::get_token_string(), nlohmann::detail::parser< BasicJsonType >::m_lexer, result, nlohmann::detail::parser< BasicJsonType >::sax_parse_internal(), and nlohmann::detail::strict.
sax_parse() [1/2]
template<typename BasicJsonType > template<typename SAX > bool nlohmann::detail::parser< BasicJsonType >::sax_parse (SAX * sax, const bool strict = true) inline
Definition at line 151 of file parser.hpp.
     {
         (void)detail::is_sax_static_asserts<SAX, BasicJsonType> {};
         const bool result = sax_parse_internal(sax);
         // strict mode: next byte must be EOF
         if (result and strict and (get_token() != token_type::end_of_input))
         {
             return sax->parse_error(m_lexer.get_position(),
                                     m_lexer.get_token_string(),
                                     parse_error::create(101, m_lexer.get_position(),
                                             exception_message(token_type::end_of_input, "value")));
         }
         return result;
     }
References nlohmann::detail::parse_error::create(), nlohmann::detail::parser< BasicJsonType >::exception_message(), nlohmann::detail::lexer< BasicJsonType >::get_position(), nlohmann::detail::parser< BasicJsonType >::get_token(), nlohmann::detail::lexer< BasicJsonType >::get_token_string(), nlohmann::detail::parser< BasicJsonType >::m_lexer, result, nlohmann::detail::parser< BasicJsonType >::sax_parse_internal(), nlohmann::detail::strict, and nlohmann::detail::void().
Referenced by nlohmann::detail::parser< BasicJsonType >::accept().
sax_parse() [2/2]
template<typename BasicJsonType > template<typename SAX > bool nlohmann::detail::parser< BasicJsonType >::sax_parse (SAX * sax, const bool strict = true) inline
Definition at line 8802 of file json.hpp.
     {
         (void)detail::is_sax_static_asserts<SAX, BasicJsonType> {};
         const bool result = sax_parse_internal(sax);
         // strict mode: next byte must be EOF
         if (result and strict and (get_token() != token_type::end_of_input))
         {
             return sax->parse_error(m_lexer.get_position(),
                                     m_lexer.get_token_string(),
                                     parse_error::create(101, m_lexer.get_position(),
                                             exception_message(token_type::end_of_input, "value")));
         }
         return result;
     }
References nlohmann::detail::parse_error::create(), nlohmann::detail::parser< BasicJsonType >::exception_message(), nlohmann::detail::lexer< BasicJsonType >::get_position(), nlohmann::detail::parser< BasicJsonType >::get_token(), nlohmann::detail::lexer< BasicJsonType >::get_token_string(), nlohmann::detail::parser< BasicJsonType >::m_lexer, result, nlohmann::detail::parser< BasicJsonType >::sax_parse_internal(), nlohmann::detail::strict, and nlohmann::detail::void().
sax_parse_internal() [1/2]
template<typename BasicJsonType > template<typename SAX > bool nlohmann::detail::parser< BasicJsonType >::sax_parse_internal (SAX * sax) inline private
Definition at line 171 of file parser.hpp.
     {
         // stack to remember the hierarchy of structured values we are parsing
         // true = array; false = object
         std::vector<bool> states;
         // value to avoid a goto (see comment where set to true)
         bool skip_to_state_evaluation = false;
         while (true)
         {
             if (not skip_to_state_evaluation)
             {
                 // invariant: get_token() was called before each iteration
                 switch (last_token)
                 {
                     case token_type::begin_object:
                     {
                         if (JSON_HEDLEY_UNLIKELY(not sax->start_object(std::size_t(-1))))
{
                             return false;
                         }
                         // closing } -> we are done
                         if (get_token() == token_type::end_object)
{
                             if (JSON_HEDLEY_UNLIKELY(not sax->end_object()))
{
                                 return false;
                             }
                             break;
                         }
                         // parse key
                         if (JSON_HEDLEY_UNLIKELY(last_token != token_type::value_string))
{
                             return sax->parse_error(m_lexer.get_position(),
                                                     m_lexer.get_token_string(),
                                                     parse_error::create(101, m_lexer.get_position(),
                                                             exception_message(token_type::value_string, "object key")));
                         }
                         if (JSON_HEDLEY_UNLIKELY(not sax->key(m_lexer.get_string())))
{
                             return false;
                         }
                         // parse separator (:)
                         if (JSON_HEDLEY_UNLIKELY(get_token() != token_type::name_separator))
{
                             return sax->parse_error(m_lexer.get_position(),
                                                     m_lexer.get_token_string(),
                                                     parse_error::create(101, m_lexer.get_position(),
                                                             exception_message(token_type::name_separator, "object separator")));
                         }
                         // remember we are now inside an object
                         states.push_back(false);
                         // parse values
                         get_token();
                         continue;
                     }
                     case token_type::begin_array:
                     {
                         if (JSON_HEDLEY_UNLIKELY(not sax->start_array(std::size_t(-1))))
{
                             return false;
                         }
                         // closing ] -> we are done
                         if (get_token() == token_type::end_array)
{
                             if (JSON_HEDLEY_UNLIKELY(not sax->end_array()))
{
                                 return false;
                             }
                             break;
                         }
                         // remember we are now inside an array
                         states.push_back(true);
                         // parse values (no need to call get_token)
                         continue;
                     }
                     case token_type::value_float:
                     {
                         const auto res = m_lexer.get_number_float();
                         if (JSON_HEDLEY_UNLIKELY(not std::isfinite(res)))
{
                             return sax->parse_error(m_lexer.get_position(),
                                                     m_lexer.get_token_string(),
                                                     out_of_range::create(406, "number overflow parsing '" + m_lexer.get_token_string() + "'"));
                         }
                         if (JSON_HEDLEY_UNLIKELY(not sax->number_float(res, m_lexer.get_string())))
{
                             return false;
                         }
                         break;
                     }
                     case token_type::literal_false:
                     {
                         if (JSON_HEDLEY_UNLIKELY(not sax->boolean(false)))
{
                             return false;
                         }
                         break;
                     }
                     case token_type::literal_null:
                     {
                         if (JSON_HEDLEY_UNLIKELY(not sax->null()))
{
                             return false;
                         }
                         break;
                     }
                     case token_type::literal_true:
                     {
                         if (JSON_HEDLEY_UNLIKELY(not sax->boolean(true)))
{
                             return false;
                         }
                         break;
                     }
                     case token_type::value_integer:
                     {
                         if (JSON_HEDLEY_UNLIKELY(not sax->number_integer(m_lexer.get_number_integer())))
{
                             return false;
                         }
                         break;
                     }
                     case token_type::value_string:
                     {
                         if (JSON_HEDLEY_UNLIKELY(not sax->string(m_lexer.get_string())))
{
                             return false;
                         }
                         break;
                     }
                     case token_type::value_unsigned:
                     {
                         if (JSON_HEDLEY_UNLIKELY(not sax->number_unsigned(m_lexer.get_number_unsigned())))
{
                             return false;
                         }
                         break;
                     }
                     case token_type::parse_error:
                     {
                         // using "uninitialized" to avoid "expected" message
                         return sax->parse_error(m_lexer.get_position(),
                                                 m_lexer.get_token_string(),
                                                 parse_error::create(101, m_lexer.get_position(),
                                                         exception_message(token_type::uninitialized, "value")));
                     }
                     default: // the last token was unexpected
                     {
                         return sax->parse_error(m_lexer.get_position(),
                                                 m_lexer.get_token_string(),
                                                 parse_error::create(101, m_lexer.get_position(),
                                                         exception_message(token_type::literal_or_value, "value")));
                     }
                 }
             }
             else
             {
                 skip_to_state_evaluation = false;
             }
             // we reached this line after we successfully parsed a value
             if (states.empty())
             {
                 // empty stack: we reached the end of the hierarchy: done
                 return true;
             }
             if (states.back())  // array
             {
                 // comma -> next value
                 if (get_token() == token_type::value_separator)
                 {
                     // parse a new value
                     get_token();
                     continue;
                 }
                 // closing ]
                 if (JSON_HEDLEY_LIKELY(last_token == token_type::end_array))
                 {
                     if (JSON_HEDLEY_UNLIKELY(not sax->end_array()))
                     {
                         return false;
                     }
                     // We are done with this array. Before we can parse a
                     // new value, we need to evaluate the new state first.
                     // By setting skip_to_state_evaluation to false, we
                     // are effectively jumping to the beginning of this if.
                     assert(not states.empty());
                     states.pop_back();
                     skip_to_state_evaluation = true;
                     continue;
                 }
                 return sax->parse_error(m_lexer.get_position(),
                                         m_lexer.get_token_string(),
                                         parse_error::create(101, m_lexer.get_position(),
                                                 exception_message(token_type::end_array, "array")));
             }
             else  // object
             {
                 // comma -> next value
                 if (get_token() == token_type::value_separator)
                 {
                     // parse key
                     if (JSON_HEDLEY_UNLIKELY(get_token() != token_type::value_string))
                     {
                         return sax->parse_error(m_lexer.get_position(),
                                                 m_lexer.get_token_string(),
                                                 parse_error::create(101, m_lexer.get_position(),
                                                         exception_message(token_type::value_string, "object key")));
                     }
                     if (JSON_HEDLEY_UNLIKELY(not sax->key(m_lexer.get_string())))
                     {
                         return false;
                     }
                     // parse separator (:)
                     if (JSON_HEDLEY_UNLIKELY(get_token() != token_type::name_separator))
                     {
                         return sax->parse_error(m_lexer.get_position(),
                                                 m_lexer.get_token_string(),
                                                 parse_error::create(101, m_lexer.get_position(),
                                                         exception_message(token_type::name_separator, "object separator")));
                     }
                     // parse values
                     get_token();
                     continue;
                 }
                 // closing }
                 if (JSON_HEDLEY_LIKELY(last_token == token_type::end_object))
                 {
                     if (JSON_HEDLEY_UNLIKELY(not sax->end_object()))
                     {
                         return false;
                     }
                     // We are done with this object. Before we can parse a
                     // new value, we need to evaluate the new state first.
                     // By setting skip_to_state_evaluation to false, we
                     // are effectively jumping to the beginning of this if.
                     assert(not states.empty());
                     states.pop_back();
                     skip_to_state_evaluation = true;
                     continue;
                 }
                 return sax->parse_error(m_lexer.get_position(),
                                         m_lexer.get_token_string(),
                                         parse_error::create(101, m_lexer.get_position(),
                                                 exception_message(token_type::end_object, "object")));
             }
         }
     }
References assert(), nlohmann::detail::parse_error::create(), nlohmann::detail::out_of_range::create(), nlohmann::detail::parser< BasicJsonType >::exception_message(), nlohmann::detail::lexer< BasicJsonType >::get_number_float(), nlohmann::detail::lexer< BasicJsonType >::get_number_integer(), nlohmann::detail::lexer< BasicJsonType >::get_number_unsigned(), nlohmann::detail::lexer< BasicJsonType >::get_position(), nlohmann::detail::lexer< BasicJsonType >::get_string(), nlohmann::detail::parser< BasicJsonType >::get_token(), nlohmann::detail::lexer< BasicJsonType >::get_token_string(), JSON_HEDLEY_LIKELY, JSON_HEDLEY_UNLIKELY, nlohmann::detail::parser< BasicJsonType >::last_token, and nlohmann::detail::parser< BasicJsonType >::m_lexer.
Referenced by nlohmann::detail::parser< BasicJsonType >::parse(), and nlohmann::detail::parser< BasicJsonType >::sax_parse().
sax_parse_internal() [2/2]
template<typename BasicJsonType > template<typename SAX > bool nlohmann::detail::parser< BasicJsonType >::sax_parse_internal (SAX * sax) inline private
Definition at line 8822 of file json.hpp.
     {
         // stack to remember the hierarchy of structured values we are parsing
         // true = array; false = object
         std::vector<bool> states;
         // value to avoid a goto (see comment where set to true)
         bool skip_to_state_evaluation = false;
         while (true)
         {
             if (not skip_to_state_evaluation)
             {
                 // invariant: get_token() was called before each iteration
                 switch (last_token)
                 {
                     case token_type::begin_object:
                     {
                         if (JSON_HEDLEY_UNLIKELY(not sax->start_object(std::size_t(-1))))
{
                             return false;
                         }
                         // closing } -> we are done
                         if (get_token() == token_type::end_object)
{
                             if (JSON_HEDLEY_UNLIKELY(not sax->end_object()))
{
                                 return false;
                             }
                             break;
                         }
                         // parse key
                         if (JSON_HEDLEY_UNLIKELY(last_token != token_type::value_string))
{
                             return sax->parse_error(m_lexer.get_position(),
                                                     m_lexer.get_token_string(),
                                                     parse_error::create(101, m_lexer.get_position(),
                                                             exception_message(token_type::value_string, "object key")));
                         }
                         if (JSON_HEDLEY_UNLIKELY(not sax->key(m_lexer.get_string())))
{
                             return false;
                         }
                         // parse separator (:)
                         if (JSON_HEDLEY_UNLIKELY(get_token() != token_type::name_separator))
{
                             return sax->parse_error(m_lexer.get_position(),
                                                     m_lexer.get_token_string(),
                                                     parse_error::create(101, m_lexer.get_position(),
                                                             exception_message(token_type::name_separator, "object separator")));
                         }
                         // remember we are now inside an object
                         states.push_back(false);
                         // parse values
                         get_token();
                         continue;
                     }
                     case token_type::begin_array:
                     {
                         if (JSON_HEDLEY_UNLIKELY(not sax->start_array(std::size_t(-1))))
{
                             return false;
                         }
                         // closing ] -> we are done
                         if (get_token() == token_type::end_array)
{
                             if (JSON_HEDLEY_UNLIKELY(not sax->end_array()))
{
                                 return false;
                             }
                             break;
                         }
                         // remember we are now inside an array
                         states.push_back(true);
                         // parse values (no need to call get_token)
                         continue;
                     }
                     case token_type::value_float:
                     {
                         const auto res = m_lexer.get_number_float();
                         if (JSON_HEDLEY_UNLIKELY(not std::isfinite(res)))
{
                             return sax->parse_error(m_lexer.get_position(),
                                                     m_lexer.get_token_string(),
                                                     out_of_range::create(406, "number overflow parsing '" + m_lexer.get_token_string() + "'"));
                         }
                         if (JSON_HEDLEY_UNLIKELY(not sax->number_float(res, m_lexer.get_string())))
{
                             return false;
                         }
                         break;
                     }
                     case token_type::literal_false:
                     {
                         if (JSON_HEDLEY_UNLIKELY(not sax->boolean(false)))
{
                             return false;
                         }
                         break;
                     }
                     case token_type::literal_null:
                     {
                         if (JSON_HEDLEY_UNLIKELY(not sax->null()))
{
                             return false;
                         }
                         break;
                     }
                     case token_type::literal_true:
                     {
                         if (JSON_HEDLEY_UNLIKELY(not sax->boolean(true)))
{
                             return false;
                         }
                         break;
                     }
                     case token_type::value_integer:
                     {
                         if (JSON_HEDLEY_UNLIKELY(not sax->number_integer(m_lexer.get_number_integer())))
{
                             return false;
                         }
                         break;
                     }
                     case token_type::value_string:
                     {
                         if (JSON_HEDLEY_UNLIKELY(not sax->string(m_lexer.get_string())))
{
                             return false;
                         }
                         break;
                     }
                     case token_type::value_unsigned:
                     {
                         if (JSON_HEDLEY_UNLIKELY(not sax->number_unsigned(m_lexer.get_number_unsigned())))
{
                             return false;
                         }
                         break;
                     }
                     case token_type::parse_error:
                     {
                         // using "uninitialized" to avoid "expected" message
                         return sax->parse_error(m_lexer.get_position(),
                                                 m_lexer.get_token_string(),
                                                 parse_error::create(101, m_lexer.get_position(),
                                                         exception_message(token_type::uninitialized, "value")));
                     }
                     default: // the last token was unexpected
                     {
                         return sax->parse_error(m_lexer.get_position(),
                                                 m_lexer.get_token_string(),
                                                 parse_error::create(101, m_lexer.get_position(),
                                                         exception_message(token_type::literal_or_value, "value")));
                     }
                 }
             }
             else
             {
                 skip_to_state_evaluation = false;
             }
             // we reached this line after we successfully parsed a value
             if (states.empty())
             {
                 // empty stack: we reached the end of the hierarchy: done
                 return true;
             }
             if (states.back())  // array
             {
                 // comma -> next value
                 if (get_token() == token_type::value_separator)
                 {
                     // parse a new value
                     get_token();
                     continue;
                 }
                 // closing ]
                 if (JSON_HEDLEY_LIKELY(last_token == token_type::end_array))
                 {
                     if (JSON_HEDLEY_UNLIKELY(not sax->end_array()))
                     {
                         return false;
                     }
                     // We are done with this array. Before we can parse a
                     // new value, we need to evaluate the new state first.
                     // By setting skip_to_state_evaluation to false, we
                     // are effectively jumping to the beginning of this if.
                     assert(not states.empty());
                     states.pop_back();
                     skip_to_state_evaluation = true;
                     continue;
                 }
                 return sax->parse_error(m_lexer.get_position(),
                                         m_lexer.get_token_string(),
                                         parse_error::create(101, m_lexer.get_position(),
                                                 exception_message(token_type::end_array, "array")));
             }
             else  // object
             {
                 // comma -> next value
                 if (get_token() == token_type::value_separator)
                 {
                     // parse key
                     if (JSON_HEDLEY_UNLIKELY(get_token() != token_type::value_string))
                     {
                         return sax->parse_error(m_lexer.get_position(),
                                                 m_lexer.get_token_string(),
                                                 parse_error::create(101, m_lexer.get_position(),
                                                         exception_message(token_type::value_string, "object key")));
                     }
                     if (JSON_HEDLEY_UNLIKELY(not sax->key(m_lexer.get_string())))
                     {
                         return false;
                     }
                     // parse separator (:)
                     if (JSON_HEDLEY_UNLIKELY(get_token() != token_type::name_separator))
                     {
                         return sax->parse_error(m_lexer.get_position(),
                                                 m_lexer.get_token_string(),
                                                 parse_error::create(101, m_lexer.get_position(),
                                                         exception_message(token_type::name_separator, "object separator")));
                     }
                     // parse values
                     get_token();
                     continue;
                 }
                 // closing }
                 if (JSON_HEDLEY_LIKELY(last_token == token_type::end_object))
                 {
                     if (JSON_HEDLEY_UNLIKELY(not sax->end_object()))
                     {
                         return false;
                     }
                     // We are done with this object. Before we can parse a
                     // new value, we need to evaluate the new state first.
                     // By setting skip_to_state_evaluation to false, we
                     // are effectively jumping to the beginning of this if.
                     assert(not states.empty());
                     states.pop_back();
                     skip_to_state_evaluation = true;
                     continue;
                 }
                 return sax->parse_error(m_lexer.get_position(),
                                         m_lexer.get_token_string(),
                                         parse_error::create(101, m_lexer.get_position(),
                                                 exception_message(token_type::end_object, "object")));
             }
         }
     }
References assert(), nlohmann::detail::parse_error::create(), nlohmann::detail::out_of_range::create(), nlohmann::detail::parser< BasicJsonType >::exception_message(), nlohmann::detail::lexer< BasicJsonType >::get_number_float(), nlohmann::detail::lexer< BasicJsonType >::get_number_integer(), nlohmann::detail::lexer< BasicJsonType >::get_number_unsigned(), nlohmann::detail::lexer< BasicJsonType >::get_position(), nlohmann::detail::lexer< BasicJsonType >::get_string(), nlohmann::detail::parser< BasicJsonType >::get_token(), nlohmann::detail::lexer< BasicJsonType >::get_token_string(), JSON_HEDLEY_LIKELY, JSON_HEDLEY_UNLIKELY, nlohmann::detail::parser< BasicJsonType >::last_token, and nlohmann::detail::parser< BasicJsonType >::m_lexer.
Member Data Documentation
allow_exceptions
template<typename BasicJsonType > const bool nlohmann::detail::parser< BasicJsonType >::allow_exceptions = true private
whether to throw exceptions in case of errors
Definition at line 495 of file parser.hpp.
Referenced by nlohmann::detail::parser< BasicJsonType >::parse().
callback
template<typename BasicJsonType > const parser_callback_t nlohmann::detail::parser< BasicJsonType >::callback = nullptr private
callback function
Definition at line 489 of file parser.hpp.
Referenced by nlohmann::detail::parser< BasicJsonType >::parse().
last_token
template<typename BasicJsonType > token_type nlohmann::detail::parser< BasicJsonType >::last_token = token_type::uninitialized private
the type of the last read token
Definition at line 491 of file parser.hpp.
Referenced by nlohmann::detail::parser< BasicJsonType >::exception_message(), nlohmann::detail::parser< BasicJsonType >::get_token(), and nlohmann::detail::parser< BasicJsonType >::sax_parse_internal().
m_lexer
template<typename BasicJsonType > lexer_t nlohmann::detail::parser< BasicJsonType >::m_lexer private
the lexer
Definition at line 493 of file parser.hpp.
Referenced by nlohmann::detail::parser< BasicJsonType >::exception_message(), nlohmann::detail::parser< BasicJsonType >::get_token(), nlohmann::detail::parser< BasicJsonType >::parse(), nlohmann::detail::parser< BasicJsonType >::sax_parse(), and nlohmann::detail::parser< BasicJsonType >::sax_parse_internal().
The documentation for this class was generated from the following files:
mc_orchestrator/json-3.7.3/include/nlohmann/detail/input/parser.hpp
mc_orchestrator/json-3.7.3/single_include/nlohmann/json.hpp