Mixed Criticality Orchestrator: nlohmann::detail::exception Class Reference
nlohmann::detail::exception Class Reference
general exception of the basic_json class
#include <exceptions.hpp>
Public Member Functions
const JSON_HEDLEY_RETURNS_NON_NULL char * what () const noexcept override
returns the explanatory string
const char * what () const noexcept override
returns the explanatory string
Public Attributes
const int id
the id of the exception
Protected Member Functions
exception (int id_, const char *what_arg)
exception (int id_, const char *what_arg)
Static Protected Member Functions
static std::string name (const std::string &ename, int id_)
static std::string name (const std::string &ename, int id_)
Private Attributes
std::runtime_error m
an exception object as storage for error messages
Detailed Description
general exception of the basic_json class
This class is an extension of std::exception objects with a member id for exception ids. It is used as the base class for all exceptions thrown by the basic_json class. This class can hence be used as "wildcard" to catch exceptions.
Subclasses:
parse_error for exceptions indicating a parse error
invalid_iterator for exceptions indicating errors with iterators
type_error for exceptions indicating executing a member function with a wrong type
out_of_range for exceptions indicating access out of the defined range
other_error for exceptions indicating other library errors
@liveexample{The following code shows how arbitrary library exceptions can be caught.,exception}
Since
version 3.0.0
Definition at line 46 of file exceptions.hpp.
Constructor & Destructor Documentation
exception() [1/2]
nlohmann::detail::exception::exception (int id_, const char * what_arg) inline protected
Definition at line 61 of file exceptions.hpp.
 : id(id_), m(what_arg) {}
exception() [2/2]
nlohmann::detail::exception::exception (int id_, const char * what_arg) inline protected
Definition at line 1879 of file json.hpp.
 : id(id_), m(what_arg) {}
Member Function Documentation
name() [1/2]
static std::string nlohmann::detail::exception::name (const std::string & ename, int id_) inline static protected
Definition at line 63 of file exceptions.hpp.
     {
         return "[json.exception." + ename + "." + std::to_string(id_) + "] ";
     }
References httplib::to_string().
Referenced by nlohmann::detail::parse_error::create(), nlohmann::detail::invalid_iterator::create(), nlohmann::detail::type_error::create(), nlohmann::detail::out_of_range::create(), and nlohmann::detail::other_error::create().
name() [2/2]
static std::string nlohmann::detail::exception::name (const std::string & ename, int id_) inline static protected
Definition at line 1881 of file json.hpp.
     {
         return "[json.exception." + ename + "." + std::to_string(id_) + "] ";
     }
References nlohmann::to_string().
what() [1/2]
const JSON_HEDLEY_RETURNS_NON_NULL char* nlohmann::detail::exception::what () const inline override noexcept
returns the explanatory string
Definition at line 51 of file exceptions.hpp.
     {
         return m.what();
     }
References m.
Referenced by DatabaseHandler::AppendData(), PodmanPodUsageCommand::Execute(), UserAppControlHandler::Init(), main(), sax_event_consumer::parse_error(), DatabaseHandler::ReadData(), and ConfigHandler::UpdateDatabase().
what() [2/2]
const char* nlohmann::detail::exception::what () const inline override noexcept
returns the explanatory string
Definition at line 1869 of file json.hpp.
     {
         return m.what();
     }
References m.
Member Data Documentation
id
const int nlohmann::detail::exception::id
the id of the exception
Definition at line 57 of file exceptions.hpp.
Referenced by main(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::parse_error(), and nlohmann::detail::json_sax_dom_callback_parser< BasicJsonType >::parse_error().
m
std::runtime_error nlohmann::detail::exception::m private
an exception object as storage for error messages
Definition at line 70 of file exceptions.hpp.
Referenced by what().
The documentation for this class was generated from the following files:
mc_orchestrator/json-3.7.3/include/nlohmann/detail/exceptions.hpp
mc_orchestrator/json-3.7.3/single_include/nlohmann/json.hpp