Mixed Criticality Orchestrator: nlohmann::json_pointer< BasicJsonType > Class Template Reference
nlohmann::json_pointer< BasicJsonType > Class Template Reference
JSON Pointer.
#include <json_pointer.hpp>
Public Member Functions
json_pointer (const std::string &s="")
create JSON pointer
std::string to_string () const
return a string representation of the JSON pointer
operator std::string () const
return a string representation of the JSON pointer
json_pointer & operator/= (const json_pointer &ptr)
append another JSON pointer at the end of this JSON pointer
json_pointer & operator/= (std::string token)
append an unescaped reference token at the end of this JSON pointer
json_pointer & operator/= (std::size_t array_index)
append an array index at the end of this JSON pointer
json_pointer parent_pointer () const
returns the parent of this JSON pointer
void pop_back ()
remove last reference token
const std::string & back () const
return last reference token
void push_back (const std::string &token)
append an unescaped token at the end of the reference pointer
void push_back (std::string &&token)
append an unescaped token at the end of the reference pointer
bool empty () const noexcept
return whether pointer points to the root document
json_pointer (const std::string &s="")
create JSON pointer
std::string to_string () const
return a string representation of the JSON pointer
operator std::string () const
return a string representation of the JSON pointer
json_pointer & operator/= (const json_pointer &ptr)
append another JSON pointer at the end of this JSON pointer
json_pointer & operator/= (std::string token)
append an unescaped reference token at the end of this JSON pointer
json_pointer & operator/= (std::size_t array_index)
append an array index at the end of this JSON pointer
json_pointer parent_pointer () const
returns the parent of this JSON pointer
void pop_back ()
remove last reference token
const std::string & back () const
return last reference token
void push_back (const std::string &token)
append an unescaped token at the end of the reference pointer
void push_back (std::string &&token)
append an unescaped token at the end of the reference pointer
bool empty () const noexcept
return whether pointer points to the root document
Private Member Functions
json_pointer top () const
BasicJsonType & get_and_create (BasicJsonType &j) const
create and return a reference to the pointed to value
BasicJsonType & get_unchecked (BasicJsonType *ptr) const
return a reference to the pointed to value
BasicJsonType & get_checked (BasicJsonType *ptr) const
const BasicJsonType & get_unchecked (const BasicJsonType *ptr) const
return a const reference to the pointed to value
const BasicJsonType & get_checked (const BasicJsonType *ptr) const
bool contains (const BasicJsonType *ptr) const
json_pointer top () const
BasicJsonType & get_and_create (BasicJsonType &j) const
create and return a reference to the pointed to value
BasicJsonType & get_unchecked (BasicJsonType *ptr) const
return a reference to the pointed to value
BasicJsonType & get_checked (BasicJsonType *ptr) const
const BasicJsonType & get_unchecked (const BasicJsonType *ptr) const
return a const reference to the pointed to value
const BasicJsonType & get_checked (const BasicJsonType *ptr) const
bool contains (const BasicJsonType *ptr) const
Static Private Member Functions
static int array_index (const std::string &s)
static std::vector< std::string > split (const std::string &reference_string)
split the string input to reference tokens
static void replace_substring (std::string &s, const std::string &f, const std::string &t)
replace all occurrences of a substring by another string
static std::string escape (std::string s)
escape "~" to "~0" and "/" to "~1"
static void unescape (std::string &s)
unescape "~1" to tilde and "~0" to slash (order is important!)
static void flatten (const std::string &reference_string, const BasicJsonType &value, BasicJsonType &result)
static BasicJsonType unflatten (const BasicJsonType &value)
static int array_index (const std::string &s)
static std::vector< std::string > split (const std::string &reference_string)
split the string input to reference tokens
static void replace_substring (std::string &s, const std::string &f, const std::string &t)
replace all occurrences of a substring by another string
static std::string escape (std::string s)
escape "~" to "~0" and "/" to "~1"
static void unescape (std::string &s)
unescape "~1" to tilde and "~0" to slash (order is important!)
static void flatten (const std::string &reference_string, const BasicJsonType &value, BasicJsonType &result)
static BasicJsonType unflatten (const BasicJsonType &value)
Private Attributes
std::vector< std::string > reference_tokens
the reference tokens
Friends
class basic_json
json_pointer operator/ (const json_pointer &lhs, const json_pointer &rhs)
create a new JSON pointer by appending the right JSON pointer at the end of the left JSON pointer
json_pointer operator/ (const json_pointer &ptr, std::string token)
create a new JSON pointer by appending the unescaped token at the end of the JSON pointer
json_pointer operator/ (const json_pointer &ptr, std::size_t array_index)
create a new JSON pointer by appending the array-index-token at the end of the JSON pointer
bool operator== (json_pointer const &lhs, json_pointer const &rhs) noexcept
compares two JSON pointers for equality
bool operator!= (json_pointer const &lhs, json_pointer const &rhs) noexcept
compares two JSON pointers for inequality
json_pointer operator/ (const json_pointer &lhs, const json_pointer &rhs)
create a new JSON pointer by appending the right JSON pointer at the end of the left JSON pointer
json_pointer operator/ (const json_pointer &ptr, std::string token)
create a new JSON pointer by appending the unescaped token at the end of the JSON pointer
json_pointer operator/ (const json_pointer &ptr, std::size_t array_index)
create a new JSON pointer by appending the array-index-token at the end of the JSON pointer
bool operator== (json_pointer const &lhs, json_pointer const &rhs) noexcept
compares two JSON pointers for equality
bool operator!= (json_pointer const &lhs, json_pointer const &rhs) noexcept
compares two JSON pointers for inequality
Detailed Description
template<typename BasicJsonType>
class nlohmann::json_pointer< BasicJsonType >
JSON Pointer.
A JSON pointer defines a string syntax for identifying a specific value within a JSON document. It can be used with functions at and operator[]. Furthermore, JSON pointers are the base for JSON patches.
See also
RFC 6901
Since
version 2.0.0
Definition at line 18 of file json_pointer.hpp.
Constructor & Destructor Documentation
json_pointer() [1/2]
template<typename BasicJsonType > nlohmann::json_pointer< BasicJsonType >::json_pointer (const std::string & s = "") inline explicit
create JSON pointer
Create a JSON pointer according to the syntax described in Section 3 of RFC6901.
Parameters
[in] s string representing the JSON pointer; if omitted, the empty string is assumed which references the whole JSON value
Exceptions
parse_error.107 if the given JSON pointer s is nonempty and does not begin with a slash (/); see example below
parse_error.108 if a tilde (~) in the given JSON pointer s is not followed by 0 (representing ~) or 1 (representing /); see example below
@liveexample{The example shows the construction several valid JSON pointers as well as the exceptional behavior.,json_pointer}
Since
version 2.0.0
Definition at line 46 of file json_pointer.hpp.
         : reference_tokens(split(s))
     {}
Referenced by nlohmann::json_pointer< BasicJsonType >::unflatten().
json_pointer() [2/2]
template<typename BasicJsonType > nlohmann::json_pointer< BasicJsonType >::json_pointer (const std::string & s = "") inline explicit
create JSON pointer
Create a JSON pointer according to the syntax described in Section 3 of RFC6901.
Parameters
[in] s string representing the JSON pointer; if omitted, the empty string is assumed which references the whole JSON value
Exceptions
parse_error.107 if the given JSON pointer s is nonempty and does not begin with a slash (/); see example below
parse_error.108 if a tilde (~) in the given JSON pointer s is not followed by 0 (representing ~) or 1 (representing /); see example below
@liveexample{The example shows the construction several valid JSON pointers as well as the exceptional behavior.,json_pointer}
Since
version 2.0.0
Definition at line 10120 of file json.hpp.
         : reference_tokens(split(s))
     {}
Member Function Documentation
array_index() [1/2]
template<typename BasicJsonType > static int nlohmann::json_pointer< BasicJsonType >::array_index (const std::string & s) inline static private
Parameters
[in] s reference token to be converted into an array index
Returns
integer representation of s
Exceptions
out_of_range.404 if string s could not be converted to an integer
Definition at line 330 of file json_pointer.hpp.
     {
         std::size_t processed_chars = 0;
         const int res = std::stoi(s, &processed_chars);
         // check if the string was completely read
         if (JSON_HEDLEY_UNLIKELY(processed_chars != s.size()))
         {
             JSON_THROW(detail::out_of_range::create(404, "unresolved reference token '" + s + "'"));
         }
         return res;
     }
References nlohmann::detail::out_of_range::create(), JSON_HEDLEY_UNLIKELY, and JSON_THROW.
Referenced by nlohmann::json_pointer< BasicJsonType >::contains(), nlohmann::json_pointer< BasicJsonType >::get_and_create(), nlohmann::json_pointer< BasicJsonType >::get_checked(), nlohmann::json_pointer< BasicJsonType >::get_unchecked(), nlohmann::json_pointer< BasicJsonType >::operator/=(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::patch().
array_index() [2/2]
template<typename BasicJsonType > static int nlohmann::json_pointer< BasicJsonType >::array_index (const std::string & s) inline static private
Parameters
[in] s reference token to be converted into an array index
Returns
integer representation of s
Exceptions
out_of_range.404 if string s could not be converted to an integer
Definition at line 10404 of file json.hpp.
     {
         std::size_t processed_chars = 0;
         const int res = std::stoi(s, &processed_chars);
         // check if the string was completely read
         if (JSON_HEDLEY_UNLIKELY(processed_chars != s.size()))
         {
             JSON_THROW(detail::out_of_range::create(404, "unresolved reference token '" + s + "'"));
         }
         return res;
     }
References nlohmann::detail::out_of_range::create(), JSON_HEDLEY_UNLIKELY, and JSON_THROW.
back() [1/2]
template<typename BasicJsonType > const std::string& nlohmann::json_pointer< BasicJsonType >::back () const inline
return last reference token
Precondition
not empty()
Returns
last reference token
@liveexample{The example shows the usage of back.,json_pointer__back}
@complexity Constant.
Exceptions
out_of_range.405 if JSON pointer has no parent
Since
version 3.6.0
Definition at line 270 of file json_pointer.hpp.
     {
         if (JSON_HEDLEY_UNLIKELY(empty()))
         {
             JSON_THROW(detail::out_of_range::create(405, "JSON pointer has no parent"));
         }
         return reference_tokens.back();
     }
References nlohmann::detail::out_of_range::create(), nlohmann::json_pointer< BasicJsonType >::empty(), JSON_HEDLEY_UNLIKELY, JSON_THROW, and nlohmann::json_pointer< BasicJsonType >::reference_tokens.
Referenced by main(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::patch().
back() [2/2]
template<typename BasicJsonType > const std::string& nlohmann::json_pointer< BasicJsonType >::back () const inline
return last reference token
Precondition
not empty()
Returns
last reference token
@liveexample{The example shows the usage of back.,json_pointer__back}
@complexity Constant.
Exceptions
out_of_range.405 if JSON pointer has no parent
Since
version 3.6.0
Definition at line 10344 of file json.hpp.
     {
         if (JSON_HEDLEY_UNLIKELY(empty()))
         {
             JSON_THROW(detail::out_of_range::create(405, "JSON pointer has no parent"));
         }
         return reference_tokens.back();
     }
References nlohmann::detail::out_of_range::create(), nlohmann::json_pointer< BasicJsonType >::empty(), JSON_HEDLEY_UNLIKELY, JSON_THROW, and nlohmann::json_pointer< BasicJsonType >::reference_tokens.
contains() [1/2]
template<typename BasicJsonType > bool nlohmann::json_pointer< BasicJsonType >::contains (const BasicJsonType * ptr) const inline private
Exceptions
parse_error.106 if an array index begins with '0'
parse_error.109 if an array index was not a number
Definition at line 700 of file json_pointer.hpp.
     {
         using size_type = typename BasicJsonType::size_type;
         for (const auto& reference_token : reference_tokens)
         {
             switch (ptr->type())
             {
                 case detail::value_t::object:
                 {
                     if (not ptr->contains(reference_token))
                     {
                         // we did not find the key in the object
                         return false;
                     }
                     ptr = &ptr->operator[](reference_token);
                     break;
                 }
                 case detail::value_t::array:
                 {
                     if (JSON_HEDLEY_UNLIKELY(reference_token == "-"))
                     {
                         // "-" always fails the range check
                         return false;
                     }
                     // error condition (cf. RFC 6901, Sect. 4)
                     if (JSON_HEDLEY_UNLIKELY(reference_token.size() > 1 and reference_token[0] == '0'))
                     {
                         JSON_THROW(detail::parse_error::create(106, 0,
                                                                "array index '" + reference_token +
                                                                "' must not begin with '0'"));
                     }
                     JSON_TRY
                     {
                         const auto idx = static_cast<size_type>(array_index(reference_token));
                         if (idx >= ptr->size())
{
                             // index out of range
                             return false;
                         }
                         ptr = &ptr->operator[](idx);
                         break;
                     }
                     JSON_CATCH(std::invalid_argument&)
                     {
                         JSON_THROW(detail::parse_error::create(109, 0, "array index '" + reference_token + "' is not a number"));
                     }
                     break;
                 }
                 default:
                 {
                     // we do not expect primitive values if there is still a
                     // reference token to process
                     return false;
                 }
             }
         }
         // no reference token left means we found a primitive value
         return true;
     }
References nlohmann::detail::array, nlohmann::json_pointer< BasicJsonType >::array_index(), nlohmann::detail::parse_error::create(), JSON_CATCH, JSON_HEDLEY_UNLIKELY, JSON_THROW, JSON_TRY, nlohmann::detail::object, and nlohmann::json_pointer< BasicJsonType >::reference_tokens.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::contains().
contains() [2/2]
template<typename BasicJsonType > bool nlohmann::json_pointer< BasicJsonType >::contains (const BasicJsonType * ptr) const inline private
Exceptions
parse_error.106 if an array index begins with '0'
parse_error.109 if an array index was not a number
Definition at line 10774 of file json.hpp.
     {
         using size_type = typename BasicJsonType::size_type;
         for (const auto& reference_token : reference_tokens)
         {
             switch (ptr->type())
             {
                 case detail::value_t::object:
                 {
                     if (not ptr->contains(reference_token))
                     {
                         // we did not find the key in the object
                         return false;
                     }
                     ptr = &ptr->operator[](reference_token);
                     break;
                 }
                 case detail::value_t::array:
                 {
                     if (JSON_HEDLEY_UNLIKELY(reference_token == "-"))
                     {
                         // "-" always fails the range check
                         return false;
                     }
                     // error condition (cf. RFC 6901, Sect. 4)
                     if (JSON_HEDLEY_UNLIKELY(reference_token.size() > 1 and reference_token[0] == '0'))
                     {
                         JSON_THROW(detail::parse_error::create(106, 0,
                                                                "array index '" + reference_token +
                                                                "' must not begin with '0'"));
                     }
                     JSON_TRY
                     {
                         const auto idx = static_cast<size_type>(array_index(reference_token));
                         if (idx >= ptr->size())
{
                             // index out of range
                             return false;
                         }
                         ptr = &ptr->operator[](idx);
                         break;
                     }
                     JSON_CATCH(std::invalid_argument&)
                     {
                         JSON_THROW(detail::parse_error::create(109, 0, "array index '" + reference_token + "' is not a number"));
                     }
                     break;
                 }
                 default:
                 {
                     // we do not expect primitive values if there is still a
                     // reference token to process
                     return false;
                 }
             }
         }
         // no reference token left means we found a primitive value
         return true;
     }
References nlohmann::detail::array, nlohmann::json_pointer< BasicJsonType >::array_index(), nlohmann::detail::parse_error::create(), JSON_CATCH, JSON_HEDLEY_UNLIKELY, JSON_THROW, JSON_TRY, nlohmann::detail::object, and nlohmann::json_pointer< BasicJsonType >::reference_tokens.
empty() [1/2]
template<typename BasicJsonType > bool nlohmann::json_pointer< BasicJsonType >::empty () const inline noexcept
return whether pointer points to the root document
Returns
true iff the JSON pointer points to the root document
@complexity Constant.
@exceptionsafety No-throw guarantee: this function never throws exceptions.
@liveexample{The example shows the result of empty for different JSON Pointers.,json_pointer__empty}
Since
version 3.6.0
Definition at line 317 of file json_pointer.hpp.
     {
         return reference_tokens.empty();
     }
References nlohmann::json_pointer< BasicJsonType >::reference_tokens.
Referenced by nlohmann::json_pointer< BasicJsonType >::back(), main(), nlohmann::json_pointer< BasicJsonType >::parent_pointer(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::patch(), nlohmann::json_pointer< BasicJsonType >::pop_back(), and nlohmann::json_pointer< BasicJsonType >::top().
empty() [2/2]
template<typename BasicJsonType > bool nlohmann::json_pointer< BasicJsonType >::empty () const inline noexcept
return whether pointer points to the root document
Returns
true iff the JSON pointer points to the root document
@complexity Constant.
@exceptionsafety No-throw guarantee: this function never throws exceptions.
@liveexample{The example shows the result of empty for different JSON Pointers.,json_pointer__empty}
Since
version 3.6.0
Definition at line 10391 of file json.hpp.
     {
         return reference_tokens.empty();
     }
References nlohmann::json_pointer< BasicJsonType >::reference_tokens.
escape() [1/2]
template<typename BasicJsonType > static std::string nlohmann::json_pointer< BasicJsonType >::escape (std::string s) inline static private
escape "~" to "~0" and "/" to "~1"
Definition at line 863 of file json_pointer.hpp.
     {
         replace_substring(s, "~", "~0");
         replace_substring(s, "/", "~1");
         return s;
     }
References nlohmann::json_pointer< BasicJsonType >::replace_substring().
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::diff(), and nlohmann::json_pointer< BasicJsonType >::flatten().
escape() [2/2]
template<typename BasicJsonType > static std::string nlohmann::json_pointer< BasicJsonType >::escape (std::string s) inline static private
escape "~" to "~0" and "/" to "~1"
Definition at line 10937 of file json.hpp.
     {
         replace_substring(s, "~", "~0");
         replace_substring(s, "/", "~1");
         return s;
     }
References nlohmann::json_pointer< BasicJsonType >::replace_substring().
flatten() [1/2]
template<typename BasicJsonType > static void nlohmann::json_pointer< BasicJsonType >::flatten (const std::string & reference_string, const BasicJsonType & value, BasicJsonType & result) inline static private
Parameters
[in] reference_string the reference string to the current value
[in] value the value to consider
[in,out] result the result object to insert values to
Note
Empty objects or arrays are flattened to null.
Definition at line 884 of file json_pointer.hpp.
     {
         switch (value.type())
         {
             case detail::value_t::array:
             {
                 if (value.m_value.array->empty())
                 {
                     // flatten empty array as null
                     result[reference_string] = nullptr;
                 }
                 else
                 {
                     // iterate array and use index as reference string
                     for (std::size_t i = 0; i < value.m_value.array->size(); ++i)
                     {
                         flatten(reference_string + "/" + std::to_string(i),
                                 value.m_value.array->operator[](i), result);
                     }
                 }
                 break;
             }
             case detail::value_t::object:
             {
                 if (value.m_value.object->empty())
                 {
                     // flatten empty object as null
                     result[reference_string] = nullptr;
                 }
                 else
                 {
                     // iterate object and use keys as reference string
                     for (const auto& element : *value.m_value.object)
                     {
                         flatten(reference_string + "/" + escape(element.first), element.second, result);
                     }
                 }
                 break;
             }
             default:
             {
                 // add primitive value with its reference string
                 result[reference_string] = value;
                 break;
             }
         }
     }
References nlohmann::detail::array, nlohmann::json_pointer< BasicJsonType >::escape(), nlohmann::detail::object, result, and httplib::to_string().
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::flatten(), and nlohmann::json_pointer< BasicJsonType >::flatten().
flatten() [2/2]
template<typename BasicJsonType > static void nlohmann::json_pointer< BasicJsonType >::flatten (const std::string & reference_string, const BasicJsonType & value, BasicJsonType & result) inline static private
Parameters
[in] reference_string the reference string to the current value
[in] value the value to consider
[in,out] result the result object to insert values to
Note
Empty objects or arrays are flattened to null.
Definition at line 10958 of file json.hpp.
     {
         switch (value.type())
         {
             case detail::value_t::array:
             {
                 if (value.m_value.array->empty())
                 {
                     // flatten empty array as null
                     result[reference_string] = nullptr;
                 }
                 else
                 {
                     // iterate array and use index as reference string
                     for (std::size_t i = 0; i < value.m_value.array->size(); ++i)
                     {
                         flatten(reference_string + "/" + std::to_string(i),
                                 value.m_value.array->operator[](i), result);
                     }
                 }
                 break;
             }
             case detail::value_t::object:
             {
                 if (value.m_value.object->empty())
                 {
                     // flatten empty object as null
                     result[reference_string] = nullptr;
                 }
                 else
                 {
                     // iterate object and use keys as reference string
                     for (const auto& element : *value.m_value.object)
                     {
                         flatten(reference_string + "/" + escape(element.first), element.second, result);
                     }
                 }
                 break;
             }
             default:
             {
                 // add primitive value with its reference string
                 result[reference_string] = value;
                 break;
             }
         }
     }
References nlohmann::detail::array, nlohmann::json_pointer< BasicJsonType >::escape(), nlohmann::json_pointer< BasicJsonType >::flatten(), nlohmann::detail::object, result, and nlohmann::to_string().
get_and_create() [1/2]
template<typename BasicJsonType > BasicJsonType& nlohmann::json_pointer< BasicJsonType >::get_and_create (BasicJsonType & j) const inline private
create and return a reference to the pointed to value
@complexity Linear in the number of reference tokens.
Exceptions
parse_error.109 if array index is not a number
type_error.313 if value cannot be unflattened
Definition at line 364 of file json_pointer.hpp.
     {
         using size_type = typename BasicJsonType::size_type;
         auto result = &j;
         // in case no reference tokens exist, return a reference to the JSON value
         // j which will be overwritten by a primitive value
         for (const auto& reference_token : reference_tokens)
         {
             switch (result->type())
             {
                 case detail::value_t::null:
                 {
                     if (reference_token == "0")
                     {
                         // start a new array if reference token is 0
                         result = &result->operator[](0);
                     }
                     else
                     {
                         // start a new object otherwise
                         result = &result->operator[](reference_token);
                     }
                     break;
                 }
                 case detail::value_t::object:
                 {
                     // create an entry in the object
                     result = &result->operator[](reference_token);
                     break;
                 }
                 case detail::value_t::array:
                 {
                     // create an entry in the array
                     JSON_TRY
                     {
                         result = &result->operator[](static_cast<size_type>(array_index(reference_token)));
                     }
                     JSON_CATCH(std::invalid_argument&)
                     {
                         JSON_THROW(detail::parse_error::create(109, 0, "array index '" + reference_token + "' is not a number"));
                     }
                     break;
                 }
                 /*
                 The following code is only reached if there exists a reference
                 token _and_ the current value is primitive. In this case, we have
                 an error situation, because primitive values may only occur as
                 single value; that is, with an empty list of reference tokens.
                 */
                 default:
                     JSON_THROW(detail::type_error::create(313, "invalid value to unflatten"));
             }
         }
         return *result;
     }
References nlohmann::detail::array, nlohmann::json_pointer< BasicJsonType >::array_index(), nlohmann::detail::parse_error::create(), nlohmann::detail::type_error::create(), JSON_CATCH, JSON_THROW, JSON_TRY, nlohmann::detail::null, nlohmann::detail::object, nlohmann::json_pointer< BasicJsonType >::reference_tokens, and result.
get_and_create() [2/2]
template<typename BasicJsonType > BasicJsonType& nlohmann::json_pointer< BasicJsonType >::get_and_create (BasicJsonType & j) const inline private
create and return a reference to the pointed to value
@complexity Linear in the number of reference tokens.
Exceptions
parse_error.109 if array index is not a number
type_error.313 if value cannot be unflattened
Definition at line 10438 of file json.hpp.
     {
         using size_type = typename BasicJsonType::size_type;
         auto result = &j;
         // in case no reference tokens exist, return a reference to the JSON value
         // j which will be overwritten by a primitive value
         for (const auto& reference_token : reference_tokens)
         {
             switch (result->type())
             {
                 case detail::value_t::null:
                 {
                     if (reference_token == "0")
                     {
                         // start a new array if reference token is 0
                         result = &result->operator[](0);
                     }
                     else
                     {
                         // start a new object otherwise
                         result = &result->operator[](reference_token);
                     }
                     break;
                 }
                 case detail::value_t::object:
                 {
                     // create an entry in the object
                     result = &result->operator[](reference_token);
                     break;
                 }
                 case detail::value_t::array:
                 {
                     // create an entry in the array
                     JSON_TRY
                     {
                         result = &result->operator[](static_cast<size_type>(array_index(reference_token)));
                     }
                     JSON_CATCH(std::invalid_argument&)
                     {
                         JSON_THROW(detail::parse_error::create(109, 0, "array index '" + reference_token + "' is not a number"));
                     }
                     break;
                 }
                 /*
                 The following code is only reached if there exists a reference
                 token _and_ the current value is primitive. In this case, we have
                 an error situation, because primitive values may only occur as
                 single value; that is, with an empty list of reference tokens.
                 */
                 default:
                     JSON_THROW(detail::type_error::create(313, "invalid value to unflatten"));
             }
         }
         return *result;
     }
References nlohmann::detail::array, nlohmann::json_pointer< BasicJsonType >::array_index(), nlohmann::detail::parse_error::create(), nlohmann::detail::type_error::create(), JSON_CATCH, JSON_THROW, JSON_TRY, nlohmann::detail::null, nlohmann::detail::object, nlohmann::json_pointer< BasicJsonType >::reference_tokens, and result.
get_checked() [1/4]
template<typename BasicJsonType > BasicJsonType& nlohmann::json_pointer< BasicJsonType >::get_checked (BasicJsonType * ptr) const inline private
Exceptions
parse_error.106 if an array index begins with '0'
parse_error.109 if an array index was not a number
out_of_range.402 if the array index '-' is used
out_of_range.404 if the JSON pointer can not be resolved
Definition at line 520 of file json_pointer.hpp.
     {
         using size_type = typename BasicJsonType::size_type;
         for (const auto& reference_token : reference_tokens)
         {
             switch (ptr->type())
             {
                 case detail::value_t::object:
                 {
                     // note: at performs range check
                     ptr = &ptr->at(reference_token);
                     break;
                 }
                 case detail::value_t::array:
                 {
                     if (JSON_HEDLEY_UNLIKELY(reference_token == "-"))
                     {
                         // "-" always fails the range check
                         JSON_THROW(detail::out_of_range::create(402,
                                                                 "array index '-' (" + std::to_string(ptr->m_value.array->size()) +
                                                                 ") is out of range"));
                     }
                     // error condition (cf. RFC 6901, Sect. 4)
                     if (JSON_HEDLEY_UNLIKELY(reference_token.size() > 1 and reference_token[0] == '0'))
                     {
                         JSON_THROW(detail::parse_error::create(106, 0,
                                                                "array index '" + reference_token +
                                                                "' must not begin with '0'"));
                     }
                     // note: at performs range check
                     JSON_TRY
                     {
                         ptr = &ptr->at(static_cast<size_type>(array_index(reference_token)));
                     }
                     JSON_CATCH(std::invalid_argument&)
                     {
                         JSON_THROW(detail::parse_error::create(109, 0, "array index '" + reference_token + "' is not a number"));
                     }
                     break;
                 }
                 default:
                     JSON_THROW(detail::out_of_range::create(404, "unresolved reference token '" + reference_token + "'"));
             }
         }
         return *ptr;
     }
References nlohmann::detail::array, nlohmann::json_pointer< BasicJsonType >::array_index(), nlohmann::detail::parse_error::create(), nlohmann::detail::out_of_range::create(), JSON_CATCH, JSON_HEDLEY_UNLIKELY, JSON_THROW, JSON_TRY, nlohmann::detail::object, nlohmann::json_pointer< BasicJsonType >::reference_tokens, and httplib::to_string().
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::at(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::value().
get_checked() [2/4]
template<typename BasicJsonType > BasicJsonType& nlohmann::json_pointer< BasicJsonType >::get_checked (BasicJsonType * ptr) const inline private
Exceptions
parse_error.106 if an array index begins with '0'
parse_error.109 if an array index was not a number
out_of_range.402 if the array index '-' is used
out_of_range.404 if the JSON pointer can not be resolved
Definition at line 10594 of file json.hpp.
     {
         using size_type = typename BasicJsonType::size_type;
         for (const auto& reference_token : reference_tokens)
         {
             switch (ptr->type())
             {
                 case detail::value_t::object:
                 {
                     // note: at performs range check
                     ptr = &ptr->at(reference_token);
                     break;
                 }
                 case detail::value_t::array:
                 {
                     if (JSON_HEDLEY_UNLIKELY(reference_token == "-"))
                     {
                         // "-" always fails the range check
                         JSON_THROW(detail::out_of_range::create(402,
                                                                 "array index '-' (" + std::to_string(ptr->m_value.array->size()) +
                                                                 ") is out of range"));
                     }
                     // error condition (cf. RFC 6901, Sect. 4)
                     if (JSON_HEDLEY_UNLIKELY(reference_token.size() > 1 and reference_token[0] == '0'))
                     {
                         JSON_THROW(detail::parse_error::create(106, 0,
                                                                "array index '" + reference_token +
                                                                "' must not begin with '0'"));
                     }
                     // note: at performs range check
                     JSON_TRY
                     {
                         ptr = &ptr->at(static_cast<size_type>(array_index(reference_token)));
                     }
                     JSON_CATCH(std::invalid_argument&)
                     {
                         JSON_THROW(detail::parse_error::create(109, 0, "array index '" + reference_token + "' is not a number"));
                     }
                     break;
                 }
                 default:
                     JSON_THROW(detail::out_of_range::create(404, "unresolved reference token '" + reference_token + "'"));
             }
         }
         return *ptr;
     }
References nlohmann::detail::array, nlohmann::json_pointer< BasicJsonType >::array_index(), nlohmann::detail::parse_error::create(), nlohmann::detail::out_of_range::create(), JSON_CATCH, JSON_HEDLEY_UNLIKELY, JSON_THROW, JSON_TRY, nlohmann::detail::object, nlohmann::json_pointer< BasicJsonType >::reference_tokens, and nlohmann::to_string().
get_checked() [3/4]
template<typename BasicJsonType > const BasicJsonType& nlohmann::json_pointer< BasicJsonType >::get_checked (const BasicJsonType * ptr) const inline private
Exceptions
parse_error.106 if an array index begins with '0'
parse_error.109 if an array index was not a number
out_of_range.402 if the array index '-' is used
out_of_range.404 if the JSON pointer can not be resolved
Definition at line 644 of file json_pointer.hpp.
     {
         using size_type = typename BasicJsonType::size_type;
         for (const auto& reference_token : reference_tokens)
         {
             switch (ptr->type())
             {
                 case detail::value_t::object:
                 {
                     // note: at performs range check
                     ptr = &ptr->at(reference_token);
                     break;
                 }
                 case detail::value_t::array:
                 {
                     if (JSON_HEDLEY_UNLIKELY(reference_token == "-"))
                     {
                         // "-" always fails the range check
                         JSON_THROW(detail::out_of_range::create(402,
                                                                 "array index '-' (" + std::to_string(ptr->m_value.array->size()) +
                                                                 ") is out of range"));
                     }
                     // error condition (cf. RFC 6901, Sect. 4)
                     if (JSON_HEDLEY_UNLIKELY(reference_token.size() > 1 and reference_token[0] == '0'))
                     {
                         JSON_THROW(detail::parse_error::create(106, 0,
                                                                "array index '" + reference_token +
                                                                "' must not begin with '0'"));
                     }
                     // note: at performs range check
                     JSON_TRY
                     {
                         ptr = &ptr->at(static_cast<size_type>(array_index(reference_token)));
                     }
                     JSON_CATCH(std::invalid_argument&)
                     {
                         JSON_THROW(detail::parse_error::create(109, 0, "array index '" + reference_token + "' is not a number"));
                     }
                     break;
                 }
                 default:
                     JSON_THROW(detail::out_of_range::create(404, "unresolved reference token '" + reference_token + "'"));
             }
         }
         return *ptr;
     }
References nlohmann::detail::array, nlohmann::json_pointer< BasicJsonType >::array_index(), nlohmann::detail::parse_error::create(), nlohmann::detail::out_of_range::create(), JSON_CATCH, JSON_HEDLEY_UNLIKELY, JSON_THROW, JSON_TRY, nlohmann::detail::object, nlohmann::json_pointer< BasicJsonType >::reference_tokens, and httplib::to_string().
get_checked() [4/4]
template<typename BasicJsonType > const BasicJsonType& nlohmann::json_pointer< BasicJsonType >::get_checked (const BasicJsonType * ptr) const inline private
Exceptions
parse_error.106 if an array index begins with '0'
parse_error.109 if an array index was not a number
out_of_range.402 if the array index '-' is used
out_of_range.404 if the JSON pointer can not be resolved
Definition at line 10718 of file json.hpp.
     {
         using size_type = typename BasicJsonType::size_type;
         for (const auto& reference_token : reference_tokens)
         {
             switch (ptr->type())
             {
                 case detail::value_t::object:
                 {
                     // note: at performs range check
                     ptr = &ptr->at(reference_token);
                     break;
                 }
                 case detail::value_t::array:
                 {
                     if (JSON_HEDLEY_UNLIKELY(reference_token == "-"))
                     {
                         // "-" always fails the range check
                         JSON_THROW(detail::out_of_range::create(402,
                                                                 "array index '-' (" + std::to_string(ptr->m_value.array->size()) +
                                                                 ") is out of range"));
                     }
                     // error condition (cf. RFC 6901, Sect. 4)
                     if (JSON_HEDLEY_UNLIKELY(reference_token.size() > 1 and reference_token[0] == '0'))
                     {
                         JSON_THROW(detail::parse_error::create(106, 0,
                                                                "array index '" + reference_token +
                                                                "' must not begin with '0'"));
                     }
                     // note: at performs range check
                     JSON_TRY
                     {
                         ptr = &ptr->at(static_cast<size_type>(array_index(reference_token)));
                     }
                     JSON_CATCH(std::invalid_argument&)
                     {
                         JSON_THROW(detail::parse_error::create(109, 0, "array index '" + reference_token + "' is not a number"));
                     }
                     break;
                 }
                 default:
                     JSON_THROW(detail::out_of_range::create(404, "unresolved reference token '" + reference_token + "'"));
             }
         }
         return *ptr;
     }
References nlohmann::detail::array, nlohmann::json_pointer< BasicJsonType >::array_index(), nlohmann::detail::parse_error::create(), nlohmann::detail::out_of_range::create(), JSON_CATCH, JSON_HEDLEY_UNLIKELY, JSON_THROW, JSON_TRY, nlohmann::detail::object, nlohmann::json_pointer< BasicJsonType >::reference_tokens, and nlohmann::to_string().
get_unchecked() [1/4]
template<typename BasicJsonType > BasicJsonType& nlohmann::json_pointer< BasicJsonType >::get_unchecked (BasicJsonType * ptr) const inline private
return a reference to the pointed to value
Note
This version does not throw if a value is not present, but tries to create nested values instead. For instance, calling this function with pointer "/this/that" on a null value is equivalent to calling operator[]("this").operator[]("that") on that value, effectively changing the null value to an object.
Parameters
[in] ptr a JSON value
Returns
reference to the JSON value pointed to by the JSON pointer
@complexity Linear in the length of the JSON pointer.
Exceptions
parse_error.106 if an array index begins with '0'
parse_error.109 if an array index was not a number
out_of_range.404 if the JSON pointer can not be resolved
Definition at line 444 of file json_pointer.hpp.
     {
         using size_type = typename BasicJsonType::size_type;
         for (const auto& reference_token : reference_tokens)
         {
             // convert null values to arrays or objects before continuing
             if (ptr->is_null())
             {
                 // check if reference token is a number
                 const bool nums =
                     std::all_of(reference_token.begin(), reference_token.end(),
                                 [](const unsigned char x)
                 {
                     return std::isdigit(x);
                 });
                 // change value to array for numbers or "-" or to object otherwise
                 *ptr = (nums or reference_token == "-")
                        ? detail::value_t::array
                        : detail::value_t::object;
             }
             switch (ptr->type())
             {
                 case detail::value_t::object:
                 {
                     // use unchecked object access
                     ptr = &ptr->operator[](reference_token);
                     break;
                 }
                 case detail::value_t::array:
                 {
                     // error condition (cf. RFC 6901, Sect. 4)
                     if (JSON_HEDLEY_UNLIKELY(reference_token.size() > 1 and reference_token[0] == '0'))
                     {
                         JSON_THROW(detail::parse_error::create(106, 0,
                                                                "array index '" + reference_token +
                                                                "' must not begin with '0'"));
                     }
                     if (reference_token == "-")
                     {
                         // explicitly treat "-" as index beyond the end
                         ptr = &ptr->operator[](ptr->m_value.array->size());
                     }
                     else
                     {
                         // convert array index to number; unchecked access
                         JSON_TRY
{
                             ptr = &ptr->operator[](
                                 static_cast<size_type>(array_index(reference_token)));
                         }
                         JSON_CATCH(std::invalid_argument&)
{
                             JSON_THROW(detail::parse_error::create(109, 0, "array index '" + reference_token + "' is not a number"));
                         }
                     }
                     break;
                 }
                 default:
                     JSON_THROW(detail::out_of_range::create(404, "unresolved reference token '" + reference_token + "'"));
             }
         }
         return *ptr;
     }
References nlohmann::detail::array, nlohmann::json_pointer< BasicJsonType >::array_index(), nlohmann::detail::parse_error::create(), nlohmann::detail::out_of_range::create(), JSON_CATCH, JSON_HEDLEY_UNLIKELY, JSON_THROW, JSON_TRY, nlohmann::detail::object, and nlohmann::json_pointer< BasicJsonType >::reference_tokens.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::operator[]().
get_unchecked() [2/4]
template<typename BasicJsonType > BasicJsonType& nlohmann::json_pointer< BasicJsonType >::get_unchecked (BasicJsonType * ptr) const inline private
return a reference to the pointed to value
Note
This version does not throw if a value is not present, but tries to create nested values instead. For instance, calling this function with pointer "/this/that" on a null value is equivalent to calling operator[]("this").operator[]("that") on that value, effectively changing the null value to an object.
Parameters
[in] ptr a JSON value
Returns
reference to the JSON value pointed to by the JSON pointer
@complexity Linear in the length of the JSON pointer.
Exceptions
parse_error.106 if an array index begins with '0'
parse_error.109 if an array index was not a number
out_of_range.404 if the JSON pointer can not be resolved
Definition at line 10518 of file json.hpp.
     {
         using size_type = typename BasicJsonType::size_type;
         for (const auto& reference_token : reference_tokens)
         {
             // convert null values to arrays or objects before continuing
             if (ptr->is_null())
             {
                 // check if reference token is a number
                 const bool nums =
                     std::all_of(reference_token.begin(), reference_token.end(),
                                 [](const unsigned char x)
                 {
                     return std::isdigit(x);
                 });
                 // change value to array for numbers or "-" or to object otherwise
                 *ptr = (nums or reference_token == "-")
                        ? detail::value_t::array
                        : detail::value_t::object;
             }
             switch (ptr->type())
             {
                 case detail::value_t::object:
                 {
                     // use unchecked object access
                     ptr = &ptr->operator[](reference_token);
                     break;
                 }
                 case detail::value_t::array:
                 {
                     // error condition (cf. RFC 6901, Sect. 4)
                     if (JSON_HEDLEY_UNLIKELY(reference_token.size() > 1 and reference_token[0] == '0'))
                     {
                         JSON_THROW(detail::parse_error::create(106, 0,
                                                                "array index '" + reference_token +
                                                                "' must not begin with '0'"));
                     }
                     if (reference_token == "-")
                     {
                         // explicitly treat "-" as index beyond the end
                         ptr = &ptr->operator[](ptr->m_value.array->size());
                     }
                     else
                     {
                         // convert array index to number; unchecked access
                         JSON_TRY
{
                             ptr = &ptr->operator[](
                                 static_cast<size_type>(array_index(reference_token)));
                         }
                         JSON_CATCH(std::invalid_argument&)
{
                             JSON_THROW(detail::parse_error::create(109, 0, "array index '" + reference_token + "' is not a number"));
                         }
                     }
                     break;
                 }
                 default:
                     JSON_THROW(detail::out_of_range::create(404, "unresolved reference token '" + reference_token + "'"));
             }
         }
         return *ptr;
     }
References nlohmann::detail::array, nlohmann::json_pointer< BasicJsonType >::array_index(), nlohmann::detail::parse_error::create(), nlohmann::detail::out_of_range::create(), JSON_CATCH, JSON_HEDLEY_UNLIKELY, JSON_THROW, JSON_TRY, nlohmann::detail::object, and nlohmann::json_pointer< BasicJsonType >::reference_tokens.
get_unchecked() [3/4]
template<typename BasicJsonType > const BasicJsonType& nlohmann::json_pointer< BasicJsonType >::get_unchecked (const BasicJsonType * ptr) const inline private
return a const reference to the pointed to value
Parameters
[in] ptr a JSON value
Returns
const reference to the JSON value pointed to by the JSON pointer
Exceptions
parse_error.106 if an array index begins with '0'
parse_error.109 if an array index was not a number
out_of_range.402 if the array index '-' is used
out_of_range.404 if the JSON pointer can not be resolved
Definition at line 585 of file json_pointer.hpp.
     {
         using size_type = typename BasicJsonType::size_type;
         for (const auto& reference_token : reference_tokens)
         {
             switch (ptr->type())
             {
                 case detail::value_t::object:
                 {
                     // use unchecked object access
                     ptr = &ptr->operator[](reference_token);
                     break;
                 }
                 case detail::value_t::array:
                 {
                     if (JSON_HEDLEY_UNLIKELY(reference_token == "-"))
                     {
                         // "-" cannot be used for const access
                         JSON_THROW(detail::out_of_range::create(402,
                                                                 "array index '-' (" + std::to_string(ptr->m_value.array->size()) +
                                                                 ") is out of range"));
                     }
                     // error condition (cf. RFC 6901, Sect. 4)
                     if (JSON_HEDLEY_UNLIKELY(reference_token.size() > 1 and reference_token[0] == '0'))
                     {
                         JSON_THROW(detail::parse_error::create(106, 0,
                                                                "array index '" + reference_token +
                                                                "' must not begin with '0'"));
                     }
                     // use unchecked array access
                     JSON_TRY
                     {
                         ptr = &ptr->operator[](
                             static_cast<size_type>(array_index(reference_token)));
                     }
                     JSON_CATCH(std::invalid_argument&)
                     {
                         JSON_THROW(detail::parse_error::create(109, 0, "array index '" + reference_token + "' is not a number"));
                     }
                     break;
                 }
                 default:
                     JSON_THROW(detail::out_of_range::create(404, "unresolved reference token '" + reference_token + "'"));
             }
         }
         return *ptr;
     }
References nlohmann::detail::array, nlohmann::json_pointer< BasicJsonType >::array_index(), nlohmann::detail::parse_error::create(), nlohmann::detail::out_of_range::create(), JSON_CATCH, JSON_HEDLEY_UNLIKELY, JSON_THROW, JSON_TRY, nlohmann::detail::object, nlohmann::json_pointer< BasicJsonType >::reference_tokens, and httplib::to_string().
get_unchecked() [4/4]
template<typename BasicJsonType > const BasicJsonType& nlohmann::json_pointer< BasicJsonType >::get_unchecked (const BasicJsonType * ptr) const inline private
return a const reference to the pointed to value
Parameters
[in] ptr a JSON value
Returns
const reference to the JSON value pointed to by the JSON pointer
Exceptions
parse_error.106 if an array index begins with '0'
parse_error.109 if an array index was not a number
out_of_range.402 if the array index '-' is used
out_of_range.404 if the JSON pointer can not be resolved
Definition at line 10659 of file json.hpp.
     {
         using size_type = typename BasicJsonType::size_type;
         for (const auto& reference_token : reference_tokens)
         {
             switch (ptr->type())
             {
                 case detail::value_t::object:
                 {
                     // use unchecked object access
                     ptr = &ptr->operator[](reference_token);
                     break;
                 }
                 case detail::value_t::array:
                 {
                     if (JSON_HEDLEY_UNLIKELY(reference_token == "-"))
                     {
                         // "-" cannot be used for const access
                         JSON_THROW(detail::out_of_range::create(402,
                                                                 "array index '-' (" + std::to_string(ptr->m_value.array->size()) +
                                                                 ") is out of range"));
                     }
                     // error condition (cf. RFC 6901, Sect. 4)
                     if (JSON_HEDLEY_UNLIKELY(reference_token.size() > 1 and reference_token[0] == '0'))
                     {
                         JSON_THROW(detail::parse_error::create(106, 0,
                                                                "array index '" + reference_token +
                                                                "' must not begin with '0'"));
                     }
                     // use unchecked array access
                     JSON_TRY
                     {
                         ptr = &ptr->operator[](
                             static_cast<size_type>(array_index(reference_token)));
                     }
                     JSON_CATCH(std::invalid_argument&)
                     {
                         JSON_THROW(detail::parse_error::create(109, 0, "array index '" + reference_token + "' is not a number"));
                     }
                     break;
                 }
                 default:
                     JSON_THROW(detail::out_of_range::create(404, "unresolved reference token '" + reference_token + "'"));
             }
         }
         return *ptr;
     }
References nlohmann::detail::array, nlohmann::json_pointer< BasicJsonType >::array_index(), nlohmann::detail::parse_error::create(), nlohmann::detail::out_of_range::create(), JSON_CATCH, JSON_HEDLEY_UNLIKELY, JSON_THROW, JSON_TRY, nlohmann::detail::object, nlohmann::json_pointer< BasicJsonType >::reference_tokens, and nlohmann::to_string().
operator std::string() [1/2]
template<typename BasicJsonType > nlohmann::json_pointer< BasicJsonType >::operator std::string () const inline
return a string representation of the JSON pointer
Invariant
For each JSON pointer ptr, it holds:
ptr == json_pointer(ptr.to_string());
Returns
a string representation of the JSON pointer
@liveexample{The example shows the result of to_string.,json_pointer__to_string}
Since
version 2.0.0
Definition at line 75 of file json_pointer.hpp.
     {
         return to_string();
     }
References nlohmann::json_pointer< BasicJsonType >::to_string().
operator std::string() [2/2]
template<typename BasicJsonType > nlohmann::json_pointer< BasicJsonType >::operator std::string () const inline
return a string representation of the JSON pointer
Invariant
For each JSON pointer ptr, it holds:
ptr == json_pointer(ptr.to_string());
Returns
a string representation of the JSON pointer
@liveexample{The example shows the result of to_string.,json_pointer__to_string}
Since
version 2.0.0
Definition at line 10149 of file json.hpp.
     {
         return to_string();
     }
References nlohmann::json_pointer< BasicJsonType >::to_string().
operator/=() [1/6]
template<typename BasicJsonType > json_pointer& nlohmann::json_pointer< BasicJsonType >::operator/= (const json_pointer< BasicJsonType > & ptr) inline
append another JSON pointer at the end of this JSON pointer
Parameters
[in] ptr JSON pointer to append
Returns
JSON pointer with ptr appended
@liveexample{The example shows the usage of operator/=.,json_pointer__operator_add}
@complexity Linear in the length of ptr.
See also
operator/=(std::string) to append a reference token
operator/=(std::size_t) to append an array index
operator/(const json_pointer&, const json_pointer&) for a binary operator
Since
version 3.6.0
Definition at line 96 of file json_pointer.hpp.
     {
         reference_tokens.insert(reference_tokens.end(),
                                 ptr.reference_tokens.begin(),
                                 ptr.reference_tokens.end());
         return *this;
     }
References nlohmann::json_pointer< BasicJsonType >::reference_tokens.
operator/=() [2/6]
template<typename BasicJsonType > json_pointer& nlohmann::json_pointer< BasicJsonType >::operator/= (const json_pointer< BasicJsonType > & ptr) inline
append another JSON pointer at the end of this JSON pointer
Parameters
[in] ptr JSON pointer to append
Returns
JSON pointer with ptr appended
@liveexample{The example shows the usage of operator/=.,json_pointer__operator_add}
@complexity Linear in the length of ptr.
See also
operator/=(std::string) to append a reference token
operator/=(std::size_t) to append an array index
operator/(const json_pointer&, const json_pointer&) for a binary operator
Since
version 3.6.0
Definition at line 10170 of file json.hpp.
     {
         reference_tokens.insert(reference_tokens.end(),
                                 ptr.reference_tokens.begin(),
                                 ptr.reference_tokens.end());
         return *this;
     }
References nlohmann::json_pointer< BasicJsonType >::reference_tokens.
operator/=() [3/6]
template<typename BasicJsonType > json_pointer& nlohmann::json_pointer< BasicJsonType >::operator/= (std::size_t array_index) inline
append an array index at the end of this JSON pointer
Parameters
[in] array_index array index to append
Returns
JSON pointer with array_index appended
@liveexample{The example shows the usage of operator/=.,json_pointer__operator_add}
@complexity Amortized constant.
See also
operator/=(const json_pointer&) to append a JSON pointer
operator/=(std::string) to append a reference token
operator/(const json_pointer&, std::string) for a binary operator
Since
version 3.6.0
Definition at line 142 of file json_pointer.hpp.
     {
         return *this /= std::to_string(array_index);
     }
References nlohmann::json_pointer< BasicJsonType >::array_index(), and httplib::to_string().
operator/=() [4/6]
template<typename BasicJsonType > json_pointer& nlohmann::json_pointer< BasicJsonType >::operator/= (std::size_t array_index) inline
append an array index at the end of this JSON pointer
Parameters
[in] array_index array index to append
Returns
JSON pointer with array_index appended
@liveexample{The example shows the usage of operator/=.,json_pointer__operator_add}
@complexity Amortized constant.
See also
operator/=(const json_pointer&) to append a JSON pointer
operator/=(std::string) to append a reference token
operator/(const json_pointer&, std::string) for a binary operator
Since
version 3.6.0
Definition at line 10216 of file json.hpp.
     {
         return *this /= std::to_string(array_index);
     }
References nlohmann::json_pointer< BasicJsonType >::array_index(), and nlohmann::to_string().
operator/=() [5/6]
template<typename BasicJsonType > json_pointer& nlohmann::json_pointer< BasicJsonType >::operator/= (std::string token) inline
append an unescaped reference token at the end of this JSON pointer
Parameters
[in] token reference token to append
Returns
JSON pointer with token appended without escaping token
@liveexample{The example shows the usage of operator/=.,json_pointer__operator_add}
@complexity Amortized constant.
See also
operator/=(const json_pointer&) to append a JSON pointer
operator/=(std::size_t) to append an array index
operator/(const json_pointer&, std::size_t) for a binary operator
Since
version 3.6.0
Definition at line 120 of file json_pointer.hpp.
     {
         push_back(std::move(token));
         return *this;
     }
References nlohmann::json_pointer< BasicJsonType >::push_back().
operator/=() [6/6]
template<typename BasicJsonType > json_pointer& nlohmann::json_pointer< BasicJsonType >::operator/= (std::string token) inline
append an unescaped reference token at the end of this JSON pointer
Parameters
[in] token reference token to append
Returns
JSON pointer with token appended without escaping token
@liveexample{The example shows the usage of operator/=.,json_pointer__operator_add}
@complexity Amortized constant.
See also
operator/=(const json_pointer&) to append a JSON pointer
operator/=(std::size_t) to append an array index
operator/(const json_pointer&, std::size_t) for a binary operator
Since
version 3.6.0
Definition at line 10194 of file json.hpp.
     {
         push_back(std::move(token));
         return *this;
     }
References nlohmann::json_pointer< BasicJsonType >::push_back().
parent_pointer() [1/2]
template<typename BasicJsonType > json_pointer nlohmann::json_pointer< BasicJsonType >::parent_pointer () const inline
returns the parent of this JSON pointer
Returns
parent of this JSON pointer; in case this JSON pointer is the root, the root itself is returned
@complexity Linear in the length of the JSON pointer.
@liveexample{The example shows the result of parent_pointer for different JSON Pointers.,json_pointer__parent_pointer}
Since
version 3.6.0
Definition at line 221 of file json_pointer.hpp.
     {
         if (empty())
         {
             return *this;
         }
         json_pointer res = *this;
         res.pop_back();
         return res;
     }
References nlohmann::json_pointer< BasicJsonType >::empty(), and nlohmann::json_pointer< BasicJsonType >::pop_back().
Referenced by main().
parent_pointer() [2/2]
template<typename BasicJsonType > json_pointer nlohmann::json_pointer< BasicJsonType >::parent_pointer () const inline
returns the parent of this JSON pointer
Returns
parent of this JSON pointer; in case this JSON pointer is the root, the root itself is returned
@complexity Linear in the length of the JSON pointer.
@liveexample{The example shows the result of parent_pointer for different JSON Pointers.,json_pointer__parent_pointer}
Since
version 3.6.0
Definition at line 10295 of file json.hpp.
     {
         if (empty())
         {
             return *this;
         }
         json_pointer res = *this;
         res.pop_back();
         return res;
     }
References nlohmann::json_pointer< BasicJsonType >::empty().
pop_back() [1/2]
template<typename BasicJsonType > void nlohmann::json_pointer< BasicJsonType >::pop_back () inline
remove last reference token
Precondition
not empty()
@liveexample{The example shows the usage of pop_back.,json_pointer__pop_back}
@complexity Constant.
Exceptions
out_of_range.405 if JSON pointer has no parent
Since
version 3.6.0
Definition at line 246 of file json_pointer.hpp.
     {
         if (JSON_HEDLEY_UNLIKELY(empty()))
         {
             JSON_THROW(detail::out_of_range::create(405, "JSON pointer has no parent"));
         }
         reference_tokens.pop_back();
     }
References nlohmann::detail::out_of_range::create(), nlohmann::json_pointer< BasicJsonType >::empty(), JSON_HEDLEY_UNLIKELY, JSON_THROW, and nlohmann::json_pointer< BasicJsonType >::reference_tokens.
Referenced by main(), nlohmann::json_pointer< BasicJsonType >::parent_pointer(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::patch(), and TEST_CASE().
pop_back() [2/2]
template<typename BasicJsonType > void nlohmann::json_pointer< BasicJsonType >::pop_back () inline
remove last reference token
Precondition
not empty()
@liveexample{The example shows the usage of pop_back.,json_pointer__pop_back}
@complexity Constant.
Exceptions
out_of_range.405 if JSON pointer has no parent
Since
version 3.6.0
Definition at line 10320 of file json.hpp.
     {
         if (JSON_HEDLEY_UNLIKELY(empty()))
         {
             JSON_THROW(detail::out_of_range::create(405, "JSON pointer has no parent"));
         }
         reference_tokens.pop_back();
     }
References nlohmann::detail::out_of_range::create(), nlohmann::json_pointer< BasicJsonType >::empty(), JSON_HEDLEY_UNLIKELY, JSON_THROW, and nlohmann::json_pointer< BasicJsonType >::reference_tokens.
push_back() [1/4]
template<typename BasicJsonType > void nlohmann::json_pointer< BasicJsonType >::push_back (const std::string & token) inline
append an unescaped token at the end of the reference pointer
Parameters
[in] token token to add
@complexity Amortized constant.
@liveexample{The example shows the result of push_back for different JSON Pointers.,json_pointer__push_back}
Since
version 3.6.0
Definition at line 292 of file json_pointer.hpp.
     {
         reference_tokens.push_back(token);
     }
References nlohmann::json_pointer< BasicJsonType >::reference_tokens.
Referenced by main(), and nlohmann::json_pointer< BasicJsonType >::operator/=().
push_back() [2/4]
template<typename BasicJsonType > void nlohmann::json_pointer< BasicJsonType >::push_back (const std::string & token) inline
append an unescaped token at the end of the reference pointer
Parameters
[in] token token to add
@complexity Amortized constant.
@liveexample{The example shows the result of push_back for different JSON Pointers.,json_pointer__push_back}
Since
version 3.6.0
Definition at line 10366 of file json.hpp.
     {
         reference_tokens.push_back(token);
     }
References nlohmann::json_pointer< BasicJsonType >::reference_tokens.
push_back() [3/4]
template<typename BasicJsonType > void nlohmann::json_pointer< BasicJsonType >::push_back (std::string && token) inline
append an unescaped token at the end of the reference pointer
Parameters
[in] token token to add
@complexity Amortized constant.
@liveexample{The example shows the result of push_back for different JSON Pointers.,json_pointer__push_back}
Since
version 3.6.0
Definition at line 298 of file json_pointer.hpp.
     {
         reference_tokens.push_back(std::move(token));
     }
References nlohmann::json_pointer< BasicJsonType >::reference_tokens.
push_back() [4/4]
template<typename BasicJsonType > void nlohmann::json_pointer< BasicJsonType >::push_back (std::string && token) inline
append an unescaped token at the end of the reference pointer
Parameters
[in] token token to add
@complexity Amortized constant.
@liveexample{The example shows the result of push_back for different JSON Pointers.,json_pointer__push_back}
Since
version 3.6.0
Definition at line 10372 of file json.hpp.
     {
         reference_tokens.push_back(std::move(token));
     }
References nlohmann::json_pointer< BasicJsonType >::reference_tokens.
replace_substring() [1/2]
template<typename BasicJsonType > static void nlohmann::json_pointer< BasicJsonType >::replace_substring (std::string & s, const std::string & f, const std::string & t) inline static private
replace all occurrences of a substring by another string
Parameters
[in,out] s the string to manipulate; changed so that all occurrences of f are replaced with t
[in] f the substring to replace with t
[in] t the string to replace f
Precondition
The search string f must not be empty. This precondition is enforced with an assertion.
Since
version 2.0.0
Definition at line 851 of file json_pointer.hpp.
     {
         assert(not f.empty());
         for (auto pos = s.find(f);                // find first occurrence of f
                 pos != std::string::npos;         // make sure f was found
                 s.replace(pos, f.size(), t),      // replace with t, and
                 pos = s.find(f, pos + t.size()))  // find next occurrence of f
         {}
     }
References assert(), and t.
Referenced by nlohmann::json_pointer< BasicJsonType >::escape(), and nlohmann::json_pointer< BasicJsonType >::unescape().
replace_substring() [2/2]
template<typename BasicJsonType > static void nlohmann::json_pointer< BasicJsonType >::replace_substring (std::string & s, const std::string & f, const std::string & t) inline static private
replace all occurrences of a substring by another string
Parameters
[in,out] s the string to manipulate; changed so that all occurrences of f are replaced with t
[in] f the substring to replace with t
[in] t the string to replace f
Precondition
The search string f must not be empty. This precondition is enforced with an assertion.
Since
version 2.0.0
Definition at line 10925 of file json.hpp.
     {
         assert(not f.empty());
         for (auto pos = s.find(f);                // find first occurrence of f
                 pos != std::string::npos;         // make sure f was found
                 s.replace(pos, f.size(), t),      // replace with t, and
                 pos = s.find(f, pos + t.size()))  // find next occurrence of f
         {}
     }
References assert(), and t.
split() [1/2]
template<typename BasicJsonType > static std::vector<std::string> nlohmann::json_pointer< BasicJsonType >::split (const std::string & reference_string) inline static private
split the string input to reference tokens
Note
This function is only called by the json_pointer constructor. All exceptions below are documented there.
Exceptions
parse_error.107 if the pointer is not empty or begins with '/'
parse_error.108 if character '~' is not followed by '0' or '1'
Definition at line 776 of file json_pointer.hpp.
     {
         std::vector<std::string> result;
         // special case: empty reference string -> no reference tokens
         if (reference_string.empty())
         {
             return result;
         }
         // check if nonempty reference string begins with slash
         if (JSON_HEDLEY_UNLIKELY(reference_string[0] != '/'))
         {
             JSON_THROW(detail::parse_error::create(107, 1,
                                                    "JSON pointer must be empty or begin with '/' - was: '" +
                                                    reference_string + "'"));
         }
         // extract the reference tokens:
         // - slash: position of the last read slash (or end of string)
         // - start: position after the previous slash
         for (
             // search for the first slash after the first character
             std::size_t slash = reference_string.find_first_of('/', 1),
             // set the beginning of the first reference token
             start = 1;
             // we can stop if start == 0 (if slash == std::string::npos)
             start != 0;
             // set the beginning of the next reference token
             // (will eventually be 0 if slash == std::string::npos)
             start = (slash == std::string::npos) ? 0 : slash + 1,
             // find next slash
             slash = reference_string.find_first_of('/', start))
         {
             // use the text between the beginning of the reference token
             // (start) and the last slash (slash).
             auto reference_token = reference_string.substr(start, slash - start);
             // check reference tokens are properly escaped
             for (std::size_t pos = reference_token.find_first_of('~');
                     pos != std::string::npos;
                     pos = reference_token.find_first_of('~', pos + 1))
             {
                 assert(reference_token[pos] == '~');
                 // ~ must be followed by 0 or 1
                 if (JSON_HEDLEY_UNLIKELY(pos == reference_token.size() - 1 or
                                          (reference_token[pos + 1] != '0' and
                                           reference_token[pos + 1] != '1')))
                 {
                     JSON_THROW(detail::parse_error::create(108, 0, "escape character '~' must be followed with '0' or '1'"));
                 }
             }
             // finally, store the reference token
             unescape(reference_token);
             result.push_back(reference_token);
         }
         return result;
     }
References assert(), nlohmann::detail::parse_error::create(), JSON_HEDLEY_UNLIKELY, JSON_THROW, result, and nlohmann::json_pointer< BasicJsonType >::unescape().
split() [2/2]
template<typename BasicJsonType > static std::vector<std::string> nlohmann::json_pointer< BasicJsonType >::split (const std::string & reference_string) inline static private
split the string input to reference tokens
Note
This function is only called by the json_pointer constructor. All exceptions below are documented there.
Exceptions
parse_error.107 if the pointer is not empty or begins with '/'
parse_error.108 if character '~' is not followed by '0' or '1'
Definition at line 10850 of file json.hpp.
     {
         std::vector<std::string> result;
         // special case: empty reference string -> no reference tokens
         if (reference_string.empty())
         {
             return result;
         }
         // check if nonempty reference string begins with slash
         if (JSON_HEDLEY_UNLIKELY(reference_string[0] != '/'))
         {
             JSON_THROW(detail::parse_error::create(107, 1,
                                                    "JSON pointer must be empty or begin with '/' - was: '" +
                                                    reference_string + "'"));
         }
         // extract the reference tokens:
         // - slash: position of the last read slash (or end of string)
         // - start: position after the previous slash
         for (
             // search for the first slash after the first character
             std::size_t slash = reference_string.find_first_of('/', 1),
             // set the beginning of the first reference token
             start = 1;
             // we can stop if start == 0 (if slash == std::string::npos)
             start != 0;
             // set the beginning of the next reference token
             // (will eventually be 0 if slash == std::string::npos)
             start = (slash == std::string::npos) ? 0 : slash + 1,
             // find next slash
             slash = reference_string.find_first_of('/', start))
         {
             // use the text between the beginning of the reference token
             // (start) and the last slash (slash).
             auto reference_token = reference_string.substr(start, slash - start);
             // check reference tokens are properly escaped
             for (std::size_t pos = reference_token.find_first_of('~');
                     pos != std::string::npos;
                     pos = reference_token.find_first_of('~', pos + 1))
             {
                 assert(reference_token[pos] == '~');
                 // ~ must be followed by 0 or 1
                 if (JSON_HEDLEY_UNLIKELY(pos == reference_token.size() - 1 or
                                          (reference_token[pos + 1] != '0' and
                                           reference_token[pos + 1] != '1')))
                 {
                     JSON_THROW(detail::parse_error::create(108, 0, "escape character '~' must be followed with '0' or '1'"));
                 }
             }
             // finally, store the reference token
             unescape(reference_token);
             result.push_back(reference_token);
         }
         return result;
     }
References assert(), nlohmann::detail::parse_error::create(), JSON_HEDLEY_UNLIKELY, JSON_THROW, result, and nlohmann::json_pointer< BasicJsonType >::unescape().
to_string() [1/2]
template<typename BasicJsonType > std::string nlohmann::json_pointer< BasicJsonType >::to_string () const inline
return a string representation of the JSON pointer
Invariant
For each JSON pointer ptr, it holds:
ptr == json_pointer(ptr.to_string());
Returns
a string representation of the JSON pointer
@liveexample{The example shows the result of to_string.,json_pointer__to_string}
Since
version 2.0.0
Definition at line 64 of file json_pointer.hpp.
     {
         return std::accumulate(reference_tokens.begin(), reference_tokens.end(),
                                std::string{},
                                [](const std::string & a, const std::string & b)
         {
             return a + "/" + escape(b);
         });
     }
References nlohmann::json_pointer< BasicJsonType >::reference_tokens.
Referenced by main(), and nlohmann::json_pointer< BasicJsonType >::operator std::string().
to_string() [2/2]
template<typename BasicJsonType > std::string nlohmann::json_pointer< BasicJsonType >::to_string () const inline
return a string representation of the JSON pointer
Invariant
For each JSON pointer ptr, it holds:
ptr == json_pointer(ptr.to_string());
Returns
a string representation of the JSON pointer
@liveexample{The example shows the result of to_string.,json_pointer__to_string}
Since
version 2.0.0
Definition at line 10138 of file json.hpp.
     {
         return std::accumulate(reference_tokens.begin(), reference_tokens.end(),
                                std::string{},
                                [](const std::string & a, const std::string & b)
         {
             return a + "/" + escape(b);
         });
     }
References nlohmann::json_pointer< BasicJsonType >::reference_tokens.
top() [1/2]
template<typename BasicJsonType > json_pointer nlohmann::json_pointer< BasicJsonType >::top () const inline private
Definition at line 344 of file json_pointer.hpp.
     {
         if (JSON_HEDLEY_UNLIKELY(empty()))
         {
             JSON_THROW(detail::out_of_range::create(405, "JSON pointer has no parent"));
         }
         json_pointer result = *this;
         result.reference_tokens = {reference_tokens[0]};
         return result;
     }
References nlohmann::detail::out_of_range::create(), nlohmann::json_pointer< BasicJsonType >::empty(), JSON_HEDLEY_UNLIKELY, JSON_THROW, nlohmann::json_pointer< BasicJsonType >::reference_tokens, and result.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::patch(), and TEST_CASE().
top() [2/2]
template<typename BasicJsonType > json_pointer nlohmann::json_pointer< BasicJsonType >::top () const inline private
Definition at line 10418 of file json.hpp.
     {
         if (JSON_HEDLEY_UNLIKELY(empty()))
         {
             JSON_THROW(detail::out_of_range::create(405, "JSON pointer has no parent"));
         }
         json_pointer result = *this;
         result.reference_tokens = {reference_tokens[0]};
         return result;
     }
References nlohmann::detail::out_of_range::create(), nlohmann::json_pointer< BasicJsonType >::empty(), JSON_HEDLEY_UNLIKELY, JSON_THROW, nlohmann::json_pointer< BasicJsonType >::reference_tokens, and result.
unescape() [1/2]
template<typename BasicJsonType > static void nlohmann::json_pointer< BasicJsonType >::unescape (std::string & s) inline static private
unescape "~1" to tilde and "~0" to slash (order is important!)
Definition at line 871 of file json_pointer.hpp.
     {
         replace_substring(s, "~1", "/");
         replace_substring(s, "~0", "~");
     }
References nlohmann::json_pointer< BasicJsonType >::replace_substring().
Referenced by nlohmann::json_pointer< BasicJsonType >::split().
unescape() [2/2]
template<typename BasicJsonType > static void nlohmann::json_pointer< BasicJsonType >::unescape (std::string & s) inline static private
unescape "~1" to tilde and "~0" to slash (order is important!)
Definition at line 10945 of file json.hpp.
     {
         replace_substring(s, "~1", "/");
         replace_substring(s, "~0", "~");
     }
References nlohmann::json_pointer< BasicJsonType >::replace_substring().
unflatten() [1/2]
template<typename BasicJsonType > static BasicJsonType nlohmann::json_pointer< BasicJsonType >::unflatten (const BasicJsonType & value) inline static private
Parameters
[in] value flattened JSON
Returns
unflattened JSON
Exceptions
parse_error.109 if array index is not a number
type_error.314 if value is not an object
type_error.315 if object values are not primitive
type_error.313 if value cannot be unflattened
Definition at line 947 of file json_pointer.hpp.
     {
         if (JSON_HEDLEY_UNLIKELY(not value.is_object()))
         {
             JSON_THROW(detail::type_error::create(314, "only objects can be unflattened"));
         }
         BasicJsonType result;
         // iterate the JSON object values
         for (const auto& element : *value.m_value.object)
         {
             if (JSON_HEDLEY_UNLIKELY(not element.second.is_primitive()))
             {
                 JSON_THROW(detail::type_error::create(315, "values in object must be primitive"));
             }
             // assign value to reference pointed to by JSON pointer; Note that if
             // the JSON pointer is "" (i.e., points to the whole value), function
             // get_and_create returns a reference to result itself. An assignment
             // will then create a primitive value.
             json_pointer(element.first).get_and_create(result) = element.second;
         }
         return result;
     }
References nlohmann::detail::type_error::create(), JSON_HEDLEY_UNLIKELY, nlohmann::json_pointer< BasicJsonType >::json_pointer(), JSON_THROW, and result.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::unflatten().
unflatten() [2/2]
template<typename BasicJsonType > static BasicJsonType nlohmann::json_pointer< BasicJsonType >::unflatten (const BasicJsonType & value) inline static private
Parameters
[in] value flattened JSON
Returns
unflattened JSON
Exceptions
parse_error.109 if array index is not a number
type_error.314 if value is not an object
type_error.315 if object values are not primitive
type_error.313 if value cannot be unflattened
Definition at line 11021 of file json.hpp.
     {
         if (JSON_HEDLEY_UNLIKELY(not value.is_object()))
         {
             JSON_THROW(detail::type_error::create(314, "only objects can be unflattened"));
         }
         BasicJsonType result;
         // iterate the JSON object values
         for (const auto& element : *value.m_value.object)
         {
             if (JSON_HEDLEY_UNLIKELY(not element.second.is_primitive()))
             {
                 JSON_THROW(detail::type_error::create(315, "values in object must be primitive"));
             }
             // assign value to reference pointed to by JSON pointer; Note that if
             // the JSON pointer is "" (i.e., points to the whole value), function
             // get_and_create returns a reference to result itself. An assignment
             // will then create a primitive value.
             json_pointer(element.first).get_and_create(result) = element.second;
         }
         return result;
     }
References nlohmann::detail::type_error::create(), JSON_HEDLEY_UNLIKELY, nlohmann::json_pointer< BasicJsonType >::json_pointer(), JSON_THROW, and result.
Friends And Related Function Documentation
basic_json
template<template< typename, typename, typename... > class ObjectType, template< typename, typename... > class ArrayType, class StringType , class BooleanType , class NumberIntegerType , class NumberUnsignedType , class NumberFloatType , template< typename > class AllocatorType, template< typename, typename=void > class JSONSerializer> basic_json friend
Definition at line 22 of file json_pointer.hpp.
operator!= [1/2]
template<typename BasicJsonType > bool operator!= (json_pointer< BasicJsonType > const & lhs, json_pointer< BasicJsonType > const & rhs) friend
compares two JSON pointers for inequality
Parameters
[in] lhs JSON pointer to compare
[in] rhs JSON pointer to compare
Returns
whether lhs is not equal rhs
@complexity Linear in the length of the JSON pointer
@exceptionsafety No-throw guarantee: this function never throws exceptions.
Definition at line 1002 of file json_pointer.hpp.
     {
         return not (lhs == rhs);
     }
operator!= [2/2]
template<typename BasicJsonType > bool operator!= (json_pointer< BasicJsonType > const & lhs, json_pointer< BasicJsonType > const & rhs) friend
compares two JSON pointers for inequality
Parameters
[in] lhs JSON pointer to compare
[in] rhs JSON pointer to compare
Returns
whether lhs is not equal rhs
@complexity Linear in the length of the JSON pointer
@exceptionsafety No-throw guarantee: this function never throws exceptions.
Definition at line 11076 of file json.hpp.
     {
         return not (lhs == rhs);
     }
operator/ [1/6]
template<typename BasicJsonType > json_pointer operator/ (const json_pointer< BasicJsonType > & lhs, const json_pointer< BasicJsonType > & rhs) friend
create a new JSON pointer by appending the right JSON pointer at the end of the left JSON pointer
Parameters
[in] lhs JSON pointer
[in] rhs JSON pointer
Returns
a new JSON pointer with rhs appended to lhs
@liveexample{The example shows the usage of operator/.,json_pointer__operator_add_binary}
@complexity Linear in the length of lhs and rhs.
See also
operator/=(const json_pointer&) to append a JSON pointer
Since
version 3.6.0
Definition at line 162 of file json_pointer.hpp.
     {
         return json_pointer(lhs) /= rhs;
     }
operator/ [2/6]
template<typename BasicJsonType > json_pointer operator/ (const json_pointer< BasicJsonType > & lhs, const json_pointer< BasicJsonType > & rhs) friend
create a new JSON pointer by appending the right JSON pointer at the end of the left JSON pointer
Parameters
[in] lhs JSON pointer
[in] rhs JSON pointer
Returns
a new JSON pointer with rhs appended to lhs
@liveexample{The example shows the usage of operator/.,json_pointer__operator_add_binary}
@complexity Linear in the length of lhs and rhs.
See also
operator/=(const json_pointer&) to append a JSON pointer
Since
version 3.6.0
Definition at line 10236 of file json.hpp.
     {
         return json_pointer(lhs) /= rhs;
     }
operator/ [3/6]
template<typename BasicJsonType > json_pointer operator/ (const json_pointer< BasicJsonType > & ptr, std::size_t array_index) friend
create a new JSON pointer by appending the array-index-token at the end of the JSON pointer
Parameters
[in] ptr JSON pointer
[in] array_index array index
Returns
a new JSON pointer with array_index appended to ptr
@liveexample{The example shows the usage of operator/.,json_pointer__operator_add_binary}
@complexity Linear in the length of ptr.
See also
operator/=(std::size_t) to append an array index
Since
version 3.6.0
Definition at line 203 of file json_pointer.hpp.
     {
         return json_pointer(ptr) /= array_index;
     }
operator/ [4/6]
template<typename BasicJsonType > json_pointer operator/ (const json_pointer< BasicJsonType > & ptr, std::size_t array_index) friend
create a new JSON pointer by appending the array-index-token at the end of the JSON pointer
Parameters
[in] ptr JSON pointer
[in] array_index array index
Returns
a new JSON pointer with array_index appended to ptr
@liveexample{The example shows the usage of operator/.,json_pointer__operator_add_binary}
@complexity Linear in the length of ptr.
See also
operator/=(std::size_t) to append an array index
Since
version 3.6.0
Definition at line 10277 of file json.hpp.
     {
         return json_pointer(ptr) /= array_index;
     }
operator/ [5/6]
template<typename BasicJsonType > json_pointer operator/ (const json_pointer< BasicJsonType > & ptr, std::string token) friend
create a new JSON pointer by appending the unescaped token at the end of the JSON pointer
Parameters
[in] ptr JSON pointer
[in] token reference token
Returns
a new JSON pointer with unescaped token appended to ptr
@liveexample{The example shows the usage of operator/.,json_pointer__operator_add_binary}
@complexity Linear in the length of ptr.
See also
operator/=(std::string) to append a reference token
Since
version 3.6.0
Definition at line 183 of file json_pointer.hpp.
     {
         return json_pointer(ptr) /= std::move(token);
     }
operator/ [6/6]
template<typename BasicJsonType > json_pointer operator/ (const json_pointer< BasicJsonType > & ptr, std::string token) friend
create a new JSON pointer by appending the unescaped token at the end of the JSON pointer
Parameters
[in] ptr JSON pointer
[in] token reference token
Returns
a new JSON pointer with unescaped token appended to ptr
@liveexample{The example shows the usage of operator/.,json_pointer__operator_add_binary}
@complexity Linear in the length of ptr.
See also
operator/=(std::string) to append a reference token
Since
version 3.6.0
Definition at line 10257 of file json.hpp.
     {
         return json_pointer(ptr) /= std::move(token);
     }
operator== [1/2]
template<typename BasicJsonType > bool operator== (json_pointer< BasicJsonType > const & lhs, json_pointer< BasicJsonType > const & rhs) friend
compares two JSON pointers for equality
Parameters
[in] lhs JSON pointer to compare
[in] rhs JSON pointer to compare
Returns
whether lhs is equal to rhs
@complexity Linear in the length of the JSON pointer
@exceptionsafety No-throw guarantee: this function never throws exceptions.
Definition at line 985 of file json_pointer.hpp.
     {
         return lhs.reference_tokens == rhs.reference_tokens;
     }
operator== [2/2]
template<typename BasicJsonType > bool operator== (json_pointer< BasicJsonType > const & lhs, json_pointer< BasicJsonType > const & rhs) friend
compares two JSON pointers for equality
Parameters
[in] lhs JSON pointer to compare
[in] rhs JSON pointer to compare
Returns
whether lhs is equal to rhs
@complexity Linear in the length of the JSON pointer
@exceptionsafety No-throw guarantee: this function never throws exceptions.
Definition at line 11059 of file json.hpp.
     {
         return lhs.reference_tokens == rhs.reference_tokens;
     }
Member Data Documentation
reference_tokens
template<typename BasicJsonType > std::vector< std::string > nlohmann::json_pointer< BasicJsonType >::reference_tokens private
the reference tokens
Definition at line 1009 of file json_pointer.hpp.
Referenced by nlohmann::json_pointer< BasicJsonType >::back(), nlohmann::json_pointer< BasicJsonType >::contains(), nlohmann::json_pointer< BasicJsonType >::empty(), nlohmann::json_pointer< BasicJsonType >::get_and_create(), nlohmann::json_pointer< BasicJsonType >::get_checked(), nlohmann::json_pointer< BasicJsonType >::get_unchecked(), nlohmann::json_pointer< BasicJsonType >::operator/=(), nlohmann::json_pointer< BasicJsonType >::pop_back(), nlohmann::json_pointer< BasicJsonType >::push_back(), nlohmann::json_pointer< BasicJsonType >::to_string(), and nlohmann::json_pointer< BasicJsonType >::top().
The documentation for this class was generated from the following files:
mc_orchestrator/json-3.7.3/include/nlohmann/detail/json_pointer.hpp
mc_orchestrator/json-3.7.3/single_include/nlohmann/json.hpp