Mixed Criticality Orchestrator: BluechiUnitUsageCommand Class Reference
BluechiUnitUsageCommand Class Reference
#include <mco_bluechi_commands.hpp>
Public Member Functions
BluechiUnitUsageCommand (const std::string &app_name_)
~BluechiUnitUsageCommand ()=default
bool Execute () const override
Public Member Functions inherited from Command
virtual ~Command ()=default
Private Attributes
std::string app_name_
Detailed Description
Definition at line 94 of file mco_bluechi_commands.hpp.
Constructor & Destructor Documentation
BluechiUnitUsageCommand()
BluechiUnitUsageCommand::BluechiUnitUsageCommand (const std::string & app_name_)
Definition at line 401 of file mco_bluechi_commands.cpp.
{
     this->app_name_ = app_name;
 }
~BluechiUnitUsageCommand()
BluechiUnitUsageCommand::~BluechiUnitUsageCommand () default
Member Function Documentation
Execute()
bool BluechiUnitUsageCommand::Execute () const override virtual
Implements Command.
Definition at line 405 of file mco_bluechi_commands.cpp.
{
    //string pod_name = DatabaseHandler::GetInstance().ReadData(this->app_name_, kPodName);
    static int accumulated_memory = 0;
    string pod_name = this->app_name_;
    string command = kBluechiAsilPodUsage + pod_name + " > " + kOutputFile;
    int response = system(command.c_str());
    if (response == kSuccess) {
        string msg = "Pod usage details have been generated";
        cout << msg << endl;
        ifstream file(kOutputFile);
        string line;
        if (getline(file, line)) {
             istringstream iss(line);
             string name, cpu, memory, temp;
             iss >> name >> cpu >> memory;  // Extract the first 3 fields (name, CPU, memory usage)
             // Combine memory usage if it includes `/`
             while (iss >> temp) {
                 memory += " " + temp;
             }
             msg = "Pod name: " + name + " CPU: " + cpu + " Memory: " + memory;
             cout << msg << endl;
             // Remove "MB" from the memory value and convert to integer
             int memory_value = 0;
             if (memory.find("MB") != string::npos) {
                 memory_value = stoi(memory.substr(0, memory.size() - 2)); // Extract only used memory
             }
             accumulated_memory += memory_value; // Accumulate memory usage
             cout << "Accumulated Memory: " << accumulated_memory << " MB" << endl;
             nlohmann::json resourcesUsage = {
                 {"cpu", "0%"},
                 {"memory", std::to_string(accumulated_memory) + "Mi"}
             };
             DatabaseHandler::GetInstance().SaveData(asil_resource_usage, resourcesUsage);
             DatabaseHandler::GetInstance().AddData("cache", msg);
             return true;
          } else {
             string msg = "Failed to read the pod usage file";
             cout << msg << endl;
             DatabaseHandler::GetInstance().AddData("cache", msg);
             return false; // File read failure
         }
    } else {
     string msg = "Failed to generate pod usage details";
     cout << msg << endl;
     DatabaseHandler::GetInstance().AddData("cache", msg);
     return false;
    }
 }
References DatabaseHandler::AddData(), asil_resource_usage, DatabaseHandler::GetInstance(), kBluechiAsilPodUsage, kOutputFile, kSuccess, DatabaseHandler::SaveData(), and httplib::to_string().
Member Data Documentation
app_name_
std::string BluechiUnitUsageCommand::app_name_ private
Definition at line 96 of file mco_bluechi_commands.hpp.
The documentation for this class was generated from the following files:
mc_orchestrator/runtime/inc/mco_bluechi_commands.hpp
mc_orchestrator/runtime/src/mco_bluechi_commands.cpp