Mixed Criticality Orchestrator: fuzzer::MutationDispatcher Class Reference
fuzzer::MutationDispatcher Class Reference
#include <FuzzerMutate.h>
Classes
struct Mutator
Public Member Functions
MutationDispatcher (Random &Rand, const FuzzingOptions &Options)
~MutationDispatcher ()
void StartMutationSequence ()
Indicate that we are about to start a new sequence of mutations.
void PrintMutationSequence ()
Print the current sequence of mutations.
void RecordSuccessfulMutationSequence ()
Indicate that the current sequence of mutations was successfull.
size_t Mutate_Custom (uint8_t *Data, size_t Size, size_t MaxSize)
Mutates data by invoking user-provided mutator.
size_t Mutate_CustomCrossOver (uint8_t *Data, size_t Size, size_t MaxSize)
Mutates data by invoking user-provided crossover.
size_t Mutate_ShuffleBytes (uint8_t *Data, size_t Size, size_t MaxSize)
Mutates data by shuffling bytes.
size_t Mutate_EraseBytes (uint8_t *Data, size_t Size, size_t MaxSize)
Mutates data by erasing bytes.
size_t Mutate_InsertByte (uint8_t *Data, size_t Size, size_t MaxSize)
Mutates data by inserting a byte.
size_t Mutate_InsertRepeatedBytes (uint8_t *Data, size_t Size, size_t MaxSize)
Mutates data by inserting several repeated bytes.
size_t Mutate_ChangeByte (uint8_t *Data, size_t Size, size_t MaxSize)
Mutates data by chanding one byte.
size_t Mutate_ChangeBit (uint8_t *Data, size_t Size, size_t MaxSize)
Mutates data by chanding one bit.
size_t Mutate_CopyPart (uint8_t *Data, size_t Size, size_t MaxSize)
Mutates data by copying/inserting a part of data into a different place.
size_t Mutate_AddWordFromManualDictionary (uint8_t *Data, size_t Size, size_t MaxSize)
Mutates data by adding a word from the manual dictionary.
size_t Mutate_AddWordFromTemporaryAutoDictionary (uint8_t *Data, size_t Size, size_t MaxSize)
Mutates data by adding a word from the temporary automatic dictionary.
size_t Mutate_AddWordFromTORC (uint8_t *Data, size_t Size, size_t MaxSize)
Mutates data by adding a word from the TORC.
size_t Mutate_AddWordFromPersistentAutoDictionary (uint8_t *Data, size_t Size, size_t MaxSize)
Mutates data by adding a word from the persistent automatic dictionary.
size_t Mutate_ChangeASCIIInteger (uint8_t *Data, size_t Size, size_t MaxSize)
Tries to find an ASCII integer in Data, changes it to another ASCII int.
size_t Mutate_ChangeBinaryInteger (uint8_t *Data, size_t Size, size_t MaxSize)
Change a 1-, 2-, 4-, or 8-byte integer in interesting ways.
size_t Mutate_CrossOver (uint8_t *Data, size_t Size, size_t MaxSize)
CrossOver Data with some other element of the corpus.
size_t Mutate (uint8_t *Data, size_t Size, size_t MaxSize)
size_t DefaultMutate (uint8_t *Data, size_t Size, size_t MaxSize)
size_t CrossOver (const uint8_t *Data1, size_t Size1, const uint8_t *Data2, size_t Size2, uint8_t *Out, size_t MaxOutSize)
Creates a cross-over of two pieces of Data, returns its size.
void AddWordToManualDictionary (const Word &W)
void AddWordToAutoDictionary (DictionaryEntry DE)
void ClearAutoDictionary ()
void PrintRecommendedDictionary ()
void SetCorpus (const InputCorpus *Corpus)
Random & GetRand ()
Private Member Functions
size_t AddWordFromDictionary (Dictionary &D, uint8_t *Data, size_t Size, size_t MaxSize)
size_t MutateImpl (uint8_t *Data, size_t Size, size_t MaxSize, const std::vector< Mutator > &Mutators)
size_t InsertPartOf (const uint8_t *From, size_t FromSize, uint8_t *To, size_t ToSize, size_t MaxToSize)
size_t CopyPartOf (const uint8_t *From, size_t FromSize, uint8_t *To, size_t ToSize)
size_t ApplyDictionaryEntry (uint8_t *Data, size_t Size, size_t MaxSize, DictionaryEntry &DE)
template<class T >
DictionaryEntry MakeDictionaryEntryFromCMP (T Arg1, T Arg2, const uint8_t *Data, size_t Size)
Private Attributes
Random & Rand
const FuzzingOptions & Options
Dictionary ManualDictionary
Dictionary TempAutoDictionary
Dictionary PersistentAutoDictionary
std::vector< Mutator > CurrentMutatorSequence
std::vector< DictionaryEntry * > CurrentDictionaryEntrySequence
DictionaryEntry CmpDictionaryEntriesDeque [kCmpDictionaryEntriesDequeSize]
size_t CmpDictionaryEntriesDequeIdx = 0
const InputCorpus * Corpus = nullptr
std::vector< uint8_t > MutateInPlaceHere
std::vector< Mutator > Mutators
std::vector< Mutator > DefaultMutators
Static Private Attributes
static const size_t kCmpDictionaryEntriesDequeSize = 16
Detailed Description
Definition at line 21 of file FuzzerMutate.h.
Constructor & Destructor Documentation
MutationDispatcher()
fuzzer::MutationDispatcher::MutationDispatcher (Random & Rand, const FuzzingOptions & Options)
Definition at line 27 of file FuzzerMutate.cpp.
     : Rand(Rand), Options(Options) {
   DefaultMutators.insert(
       DefaultMutators.begin(),
       {
           {&MutationDispatcher::Mutate_EraseBytes, "EraseBytes"},
           {&MutationDispatcher::Mutate_InsertByte, "InsertByte"},
           {&MutationDispatcher::Mutate_InsertRepeatedBytes,
            "InsertRepeatedBytes"},
           {&MutationDispatcher::Mutate_ChangeByte, "ChangeByte"},
           {&MutationDispatcher::Mutate_ChangeBit, "ChangeBit"},
           {&MutationDispatcher::Mutate_ShuffleBytes, "ShuffleBytes"},
           {&MutationDispatcher::Mutate_ChangeASCIIInteger, "ChangeASCIIInt"},
           {&MutationDispatcher::Mutate_ChangeBinaryInteger, "ChangeBinInt"},
           {&MutationDispatcher::Mutate_CopyPart, "CopyPart"},
           {&MutationDispatcher::Mutate_CrossOver, "CrossOver"},
           {&MutationDispatcher::Mutate_AddWordFromManualDictionary,
            "ManualDict"},
           {&MutationDispatcher::Mutate_AddWordFromTemporaryAutoDictionary,
            "TempAutoDict"},
           {&MutationDispatcher::Mutate_AddWordFromPersistentAutoDictionary,
            "PersAutoDict"},
       });
   if(Options.UseCmp)
     DefaultMutators.push_back(
         {&MutationDispatcher::Mutate_AddWordFromTORC, "CMP"});
   if (EF->LLVMFuzzerCustomMutator)
     Mutators.push_back({&MutationDispatcher::Mutate_Custom, "Custom"});
   else
     Mutators = DefaultMutators;
   if (EF->LLVMFuzzerCustomCrossOver)
     Mutators.push_back(
         {&MutationDispatcher::Mutate_CustomCrossOver, "CustomCrossOver"});
 }
References DefaultMutators.
~MutationDispatcher()
fuzzer::MutationDispatcher::~MutationDispatcher () inline
Definition at line 24 of file FuzzerMutate.h.
 {}
Member Function Documentation
AddWordFromDictionary()
size_t fuzzer::MutationDispatcher::AddWordFromDictionary (Dictionary & D, uint8_t * Data, size_t Size, size_t MaxSize) private
Definition at line 265 of file FuzzerMutate.cpp.
{
   if (Size > MaxSize) return 0;
   if (D.empty()) return 0;
   DictionaryEntry &DE = D[Rand(D.size())];
   Size = ApplyDictionaryEntry(Data, Size, MaxSize, DE);
   if (!Size) return 0;
   DE.IncUseCount();
   CurrentDictionaryEntrySequence.push_back(&DE);
   return Size;
 }
References fuzzer::Dictionary::empty(), fuzzer::DictionaryEntry::IncUseCount(), and fuzzer::Dictionary::size().
AddWordToAutoDictionary()
void fuzzer::MutationDispatcher::AddWordToAutoDictionary (DictionaryEntry DE)
Definition at line 517 of file FuzzerMutate.cpp.
{
   static const size_t kMaxAutoDictSize = 1 << 14;
   if (TempAutoDictionary.size() >= kMaxAutoDictSize) return;
   TempAutoDictionary.push_back(DE);
 }
Referenced by fuzzer::TraceState::StopTraceRecording(), and TestAddWordFromDictionaryWithHint().
AddWordToManualDictionary()
void fuzzer::MutationDispatcher::AddWordToManualDictionary (const Word & W)
Definition at line 512 of file FuzzerMutate.cpp.
{
   ManualDictionary.push_back(
       {W, std::numeric_limits<size_t>::max()});
 }
Referenced by TestAddWordFromDictionary().
ApplyDictionaryEntry()
size_t fuzzer::MutationDispatcher::ApplyDictionaryEntry (uint8_t * Data, size_t Size, size_t MaxSize, DictionaryEntry & DE) private
Definition at line 176 of file FuzzerMutate.cpp.
{
   const Word &W = DE.GetW();
   bool UsePositionHint = DE.HasPositionHint() &&
                          DE.GetPositionHint() + W.size() < Size &&
                          Rand.RandBool();
   if (Rand.RandBool()) {  // Insert W.
     if (Size + W.size() > MaxSize) return 0;
     size_t Idx = UsePositionHint ? DE.GetPositionHint() : Rand(Size + 1);
     memmove(Data + Idx + W.size(), Data + Idx, Size - Idx);
     memcpy(Data + Idx, W.data(), W.size());
     Size += W.size();
   } else {  // Overwrite some bytes with W.
     if (W.size() > Size) return 0;
     size_t Idx = UsePositionHint ? DE.GetPositionHint() : Rand(Size - W.size());
     memcpy(Data + Idx, W.data(), W.size());
   }
   return Size;
 }
References fuzzer::FixedWord< kMaxSize >::data(), fuzzer::DictionaryEntry::GetPositionHint(), fuzzer::DictionaryEntry::GetW(), fuzzer::DictionaryEntry::HasPositionHint(), Idx, and fuzzer::FixedWord< kMaxSize >::size().
ClearAutoDictionary()
void fuzzer::MutationDispatcher::ClearAutoDictionary ()
Definition at line 523 of file FuzzerMutate.cpp.
{
   TempAutoDictionary.clear();
 }
Referenced by fuzzer::TraceState::StartTraceRecording().
CopyPartOf()
size_t fuzzer::MutationDispatcher::CopyPartOf (const uint8_t * From, size_t FromSize, uint8_t * To, size_t ToSize) private
Definition at line 279 of file FuzzerMutate.cpp.
{
   // Copy From[FromBeg, FromBeg + CopySize) into To[ToBeg, ToBeg + CopySize).
   size_t ToBeg = Rand(ToSize);
   size_t CopySize = Rand(ToSize - ToBeg) + 1;
   assert(ToBeg + CopySize <= ToSize);
   CopySize = std::min(CopySize, FromSize);
   size_t FromBeg = Rand(FromSize - CopySize + 1);
   assert(FromBeg + CopySize <= FromSize);
   memmove(To + ToBeg, From + FromBeg, CopySize);
   return ToSize;
 }
References assert().
CrossOver()
size_t fuzzer::MutationDispatcher::CrossOver (const uint8_t * Data1, size_t Size1, const uint8_t * Data2, size_t Size2, uint8_t * Out, size_t MaxOutSize)
Creates a cross-over of two pieces of Data, returns its size.
Definition at line 20 of file FuzzerCrossOver.cpp.
{
   assert(Size1 || Size2);
   MaxOutSize = Rand(MaxOutSize) + 1;
   size_t OutPos = 0;
   size_t Pos1 = 0;
   size_t Pos2 = 0;
   size_t *InPos = &Pos1;
   size_t InSize = Size1;
   const uint8_t *Data = Data1;
   bool CurrentlyUsingFirstData = true;
   while (OutPos < MaxOutSize && (Pos1 < Size1 || Pos2 < Size2)) {
     // Merge a part of Data into Out.
     size_t OutSizeLeft = MaxOutSize - OutPos;
     if (*InPos < InSize) {
       size_t InSizeLeft = InSize - *InPos;
       size_t MaxExtraSize = std::min(OutSizeLeft, InSizeLeft);
       size_t ExtraSize = Rand(MaxExtraSize) + 1;
       memcpy(Out + OutPos, Data + *InPos, ExtraSize);
       OutPos += ExtraSize;
       (*InPos) += ExtraSize;
     }
     // Use the other input data on the next iteration.
     InPos  = CurrentlyUsingFirstData ? &Pos2 : &Pos1;
     InSize = CurrentlyUsingFirstData ? Size2 : Size1;
     Data   = CurrentlyUsingFirstData ? Data2 : Data1;
     CurrentlyUsingFirstData = !CurrentlyUsingFirstData;
   }
   return OutPos;
 }
References assert(), and Rand.
Referenced by TEST().
DefaultMutate()
size_t fuzzer::MutationDispatcher::DefaultMutate (uint8_t * Data, size_t Size, size_t MaxSize)
Applies one of the default mutations. Provided as a service to mutation authors.
Definition at line 478 of file FuzzerMutate.cpp.
{
   return MutateImpl(Data, Size, MaxSize, DefaultMutators);
 }
Referenced by LLVMFuzzerMutate().
GetRand()
Random& fuzzer::MutationDispatcher::GetRand () inline
Definition at line 92 of file FuzzerMutate.h.
 { return Rand; }
References Rand.
Referenced by fuzzer::Fuzzer::MutateAndTestOne(), fuzzer::Fuzzer::ShuffleCorpus(), and fuzzer::TraceState::WantToHandleOneMoreMutation().
InsertPartOf()
size_t fuzzer::MutationDispatcher::InsertPartOf (const uint8_t * From, size_t FromSize, uint8_t * To, size_t ToSize, size_t MaxToSize) private
Definition at line 294 of file FuzzerMutate.cpp.
{
   if (ToSize >= MaxToSize) return 0;
   size_t AvailableSpace = MaxToSize - ToSize;
   size_t MaxCopySize = std::min(AvailableSpace, FromSize);
   size_t CopySize = Rand(MaxCopySize) + 1;
   size_t FromBeg = Rand(FromSize - CopySize + 1);
   assert(FromBeg + CopySize <= FromSize);
   size_t ToInsertPos = Rand(ToSize + 1);
   assert(ToInsertPos + CopySize <= MaxToSize);
   size_t TailSize = ToSize - ToInsertPos;
   if (To == From) {
     MutateInPlaceHere.resize(MaxToSize);
     memcpy(MutateInPlaceHere.data(), From + FromBeg, CopySize);
     memmove(To + ToInsertPos + CopySize, To + ToInsertPos, TailSize);
     memmove(To + ToInsertPos, MutateInPlaceHere.data(), CopySize);
   } else {
     memmove(To + ToInsertPos + CopySize, To + ToInsertPos, TailSize);
     memmove(To + ToInsertPos, From + FromBeg, CopySize);
   }
   return ToSize + CopySize;
 }
References assert().
MakeDictionaryEntryFromCMP()
template<class T > DictionaryEntry fuzzer::MutationDispatcher::MakeDictionaryEntryFromCMP (T Arg1, T Arg2, const uint8_t * Data, size_t Size) private
Definition at line 204 of file FuzzerMutate.cpp.
{
   ScopedDoingMyOwnMemmem scoped_doing_my_own_memmem;
   bool HandleFirst = Rand.RandBool();
   T ExistingBytes, DesiredBytes;
   Word W;
   const uint8_t *End = Data + Size;
   for (int Arg = 0; Arg < 2; Arg++) {
     ExistingBytes = HandleFirst ? Arg1 : Arg2;
     DesiredBytes = HandleFirst ? Arg2 : Arg1;
     DesiredBytes += Rand(-1, 1);
     if (Rand.RandBool()) ExistingBytes = Bswap(ExistingBytes);
     if (Rand.RandBool()) DesiredBytes = Bswap(DesiredBytes);
     HandleFirst = !HandleFirst;
     W.Set(reinterpret_cast<uint8_t*>(&DesiredBytes), sizeof(T));
     const size_t kMaxNumPositions = 8;
     size_t Positions[kMaxNumPositions];
     size_t NumPositions = 0;
     for (const uint8_t *Cur = Data;
          Cur < End && NumPositions < kMaxNumPositions; Cur++) {
       Cur = (uint8_t *)SearchMemory(Cur, End - Cur, &ExistingBytes, sizeof(T));
       if (!Cur) break;
       Positions[NumPositions++] = Cur - Data;
     }
     if (!NumPositions) break;
     return DictionaryEntry(W, Positions[Rand(NumPositions)]);
   }
   DictionaryEntry DE(W);
   return DE;
 }
References Arg2, fuzzer::Bswap(), fuzzer::SearchMemory(), and fuzzer::FixedWord< kMaxSize >::Set().
Mutate()
size_t fuzzer::MutationDispatcher::Mutate (uint8_t * Data, size_t Size, size_t MaxSize)
Applies one of the configured mutations. Returns the new size of data which could be up to MaxSize.
Definition at line 474 of file FuzzerMutate.cpp.
{
   return MutateImpl(Data, Size, MaxSize, Mutators);
 }
Referenced by fuzzer::Fuzzer::MinimizeCrashLoop(), fuzzer::Fuzzer::MutateAndTestOne(), and TEST().
Mutate_AddWordFromManualDictionary()
size_t fuzzer::MutationDispatcher::Mutate_AddWordFromManualDictionary (uint8_t * Data, size_t Size, size_t MaxSize)
Mutates data by adding a word from the manual dictionary.
Definition at line 165 of file FuzzerMutate.cpp.
{
   return AddWordFromDictionary(ManualDictionary, Data, Size, MaxSize);
 }
Referenced by TEST().
Mutate_AddWordFromPersistentAutoDictionary()
size_t fuzzer::MutationDispatcher::Mutate_AddWordFromPersistentAutoDictionary (uint8_t * Data, size_t Size, size_t MaxSize)
Mutates data by adding a word from the persistent automatic dictionary.
Definition at line 260 of file FuzzerMutate.cpp.
{
   return AddWordFromDictionary(PersistentAutoDictionary, Data, Size, MaxSize);
 }
Mutate_AddWordFromTemporaryAutoDictionary()
size_t fuzzer::MutationDispatcher::Mutate_AddWordFromTemporaryAutoDictionary (uint8_t * Data, size_t Size, size_t MaxSize)
Mutates data by adding a word from the temporary automatic dictionary.
Definition at line 171 of file FuzzerMutate.cpp.
{
   return AddWordFromDictionary(TempAutoDictionary, Data, Size, MaxSize);
 }
Referenced by TEST().
Mutate_AddWordFromTORC()
size_t fuzzer::MutationDispatcher::Mutate_AddWordFromTORC (uint8_t * Data, size_t Size, size_t MaxSize)
Mutates data by adding a word from the TORC.
Definition at line 235 of file FuzzerMutate.cpp.
{
   Word W;
   DictionaryEntry DE;
   if (Rand.RandBool()) {
     auto X = TPC.TORC8.Get(Rand.Rand());
     DE = MakeDictionaryEntryFromCMP(X.A, X.B, Data, Size);
   } else {
     auto X = TPC.TORC4.Get(Rand.Rand());
     if ((X.A >> 16) == 0 && (X.B >> 16) == 0 && Rand.RandBool())
       DE = MakeDictionaryEntryFromCMP((uint16_t)X.A, (uint16_t)X.B, Data,
                                       Size);
     else
       DE = MakeDictionaryEntryFromCMP(X.A, X.B, Data, Size);
   }
   Size = ApplyDictionaryEntry(Data, Size, MaxSize, DE);
   if (!Size) return 0;
   DictionaryEntry &DERef =
       CmpDictionaryEntriesDeque[CmpDictionaryEntriesDequeIdx++ %
                                 kCmpDictionaryEntriesDequeSize];
   DERef = DE;
   CurrentDictionaryEntrySequence.push_back(&DERef);
   return Size;
 }
References fuzzer::TableOfRecentCompares< T, kSizeT >::Get(), fuzzer::TracePC::TORC4, fuzzer::TracePC::TORC8, and fuzzer::TPC.
Mutate_ChangeASCIIInteger()
size_t fuzzer::MutationDispatcher::Mutate_ChangeASCIIInteger (uint8_t * Data, size_t Size, size_t MaxSize)
Tries to find an ASCII integer in Data, changes it to another ASCII int.
Definition at line 327 of file FuzzerMutate.cpp.
{
   if (Size > MaxSize) return 0;
   size_t B = Rand(Size);
   while (B < Size && !isdigit(Data[B])) B++;
   if (B == Size) return 0;
   size_t E = B;
   while (E < Size && isdigit(Data[E])) E++;
   assert(B < E);
   // now we have digits in [B, E).
   // strtol and friends don't accept non-zero-teminated data, parse it manually.
   uint64_t Val = Data[B] - '0';
   for (size_t i = B + 1; i < E; i++)
     Val = Val * 10 + Data[i] - '0';
   // Mutate the integer value.
   switch(Rand(5)) {
     case 0: Val++; break;
     case 1: Val--; break;
     case 2: Val /= 2; break;
     case 3: Val *= 2; break;
     case 4: Val = Rand(Val * Val); break;
     default: assert(0);
   }
   // Just replace the bytes with the new ones, don't bother moving bytes.
   for (size_t i = B; i < E; i++) {
     size_t Idx = E + B - i - 1;
     assert(Idx >= B && Idx < E);
     Data[Idx] = (Val % 10) + '0';
     Val /= 10;
   }
   return Size;
 }
References assert(), and Idx.
Referenced by TEST().
Mutate_ChangeBinaryInteger()
size_t fuzzer::MutationDispatcher::Mutate_ChangeBinaryInteger (uint8_t * Data, size_t Size, size_t MaxSize)
Change a 1-, 2-, 4-, or 8-byte integer in interesting ways.
Definition at line 386 of file FuzzerMutate.cpp.
{
   if (Size > MaxSize) return 0;
   switch (Rand(4)) {
     case 3: return ChangeBinaryInteger<uint64_t>(Data, Size, Rand);
     case 2: return ChangeBinaryInteger<uint32_t>(Data, Size, Rand);
     case 1: return ChangeBinaryInteger<uint16_t>(Data, Size, Rand);
     case 0: return ChangeBinaryInteger<uint8_t>(Data, Size, Rand);
     default: assert(0);
   }
   return 0;
 }
References assert().
Referenced by TEST().
Mutate_ChangeBit()
size_t fuzzer::MutationDispatcher::Mutate_ChangeBit (uint8_t * Data, size_t Size, size_t MaxSize)
Mutates data by chanding one bit.
Definition at line 157 of file FuzzerMutate.cpp.
{
   if (Size > MaxSize) return 0;
   size_t Idx = Rand(Size);
   Data[Idx] ^= 1 << Rand(8);
   return Size;
 }
References Idx.
Referenced by TEST().
Mutate_ChangeByte()
size_t fuzzer::MutationDispatcher::Mutate_ChangeByte (uint8_t * Data, size_t Size, size_t MaxSize)
Mutates data by chanding one byte.
Definition at line 149 of file FuzzerMutate.cpp.
{
   if (Size > MaxSize) return 0;
   size_t Idx = Rand(Size);
   Data[Idx] = RandCh(Rand);
   return Size;
 }
References Idx, and fuzzer::RandCh().
Referenced by TEST().
Mutate_CopyPart()
size_t fuzzer::MutationDispatcher::Mutate_CopyPart (uint8_t * Data, size_t Size, size_t MaxSize)
Mutates data by copying/inserting a part of data into a different place.
Definition at line 318 of file FuzzerMutate.cpp.
{
   if (Size > MaxSize) return 0;
   if (Rand.RandBool())
     return CopyPartOf(Data, Size, Data, Size);
   else
     return InsertPartOf(Data, Size, Data, Size, MaxSize);
 }
Referenced by TEST().
Mutate_CrossOver()
size_t fuzzer::MutationDispatcher::Mutate_CrossOver (uint8_t * Data, size_t Size, size_t MaxSize)
CrossOver Data with some other element of the corpus.
Definition at line 400 of file FuzzerMutate.cpp.
{
   if (Size > MaxSize) return 0;
   if (!Corpus || Corpus->size() < 2 || Size == 0) return 0;
   size_t Idx = Rand(Corpus->size());
   const Unit &O = (*Corpus)[Idx];
   if (O.empty()) return 0;
   MutateInPlaceHere.resize(MaxSize);
   auto &U = MutateInPlaceHere;
   size_t NewSize = 0;
   switch(Rand(3)) {
     case 0:
       NewSize = CrossOver(Data, Size, O.data(), O.size(), U.data(), U.size());
       break;
     case 1:
       NewSize = InsertPartOf(O.data(), O.size(), U.data(), U.size(), MaxSize);
       if (NewSize)
         break;
       // LLVM_FALLTHROUGH;
     case 2:
       NewSize = CopyPartOf(O.data(), O.size(), U.data(), U.size());
       break;
     default: assert(0);
   }
   assert(NewSize > 0 && "CrossOver returned empty unit");
   assert(NewSize <= MaxSize && "CrossOver returned overisized unit");
   memcpy(Data, U.data(), NewSize);
   return NewSize;
 }
References assert(), and Idx.
Mutate_Custom()
size_t fuzzer::MutationDispatcher::Mutate_Custom (uint8_t * Data, size_t Size, size_t MaxSize)
Mutates data by invoking user-provided mutator.
Definition at line 71 of file FuzzerMutate.cpp.
{
   return EF->LLVMFuzzerCustomMutator(Data, Size, MaxSize, Rand.Rand());
 }
References fuzzer::EF.
Mutate_CustomCrossOver()
size_t fuzzer::MutationDispatcher::Mutate_CustomCrossOver (uint8_t * Data, size_t Size, size_t MaxSize)
Mutates data by invoking user-provided crossover.
Definition at line 76 of file FuzzerMutate.cpp.
{
   if (!Corpus || Corpus->size() < 2 || Size == 0)
     return 0;
   size_t Idx = Rand(Corpus->size());
   const Unit &Other = (*Corpus)[Idx];
   if (Other.empty())
     return 0;
   MutateInPlaceHere.resize(MaxSize);
   auto &U = MutateInPlaceHere;
   size_t NewSize = EF->LLVMFuzzerCustomCrossOver(
       Data, Size, Other.data(), Other.size(), U.data(), U.size(), Rand.Rand());
   if (!NewSize)
     return 0;
   assert(NewSize <= MaxSize && "CustomCrossOver returned overisized unit");
   memcpy(Data, U.data(), NewSize);
   return NewSize;
 }
References assert(), fuzzer::EF, and Idx.
Mutate_EraseBytes()
size_t fuzzer::MutationDispatcher::Mutate_EraseBytes (uint8_t * Data, size_t Size, size_t MaxSize)
Mutates data by erasing bytes.
Definition at line 108 of file FuzzerMutate.cpp.
{
   assert(Size);
   if (Size == 1) return 0;
   size_t N = Rand(Size / 2) + 1;
   assert(N < Size);
   size_t Idx = Rand(Size - N + 1);
   // Erase Data[Idx:Idx+N].
   memmove(Data + Idx, Data + Idx + N, Size - Idx - N);
   // Printf("Erase: %zd %zd => %zd; Idx %zd\n", N, Size, Size - N, Idx);
   return Size - N;
 }
References assert(), Idx, and N.
Referenced by TEST().
Mutate_InsertByte()
size_t fuzzer::MutationDispatcher::Mutate_InsertByte (uint8_t * Data, size_t Size, size_t MaxSize)
Mutates data by inserting a byte.
Definition at line 121 of file FuzzerMutate.cpp.
{
   if (Size >= MaxSize) return 0;
   size_t Idx = Rand(Size + 1);
   // Insert new value at Data[Idx].
   memmove(Data + Idx + 1, Data + Idx, Size - Idx);
   Data[Idx] = RandCh(Rand);
   return Size + 1;
 }
References Idx, and fuzzer::RandCh().
Referenced by TEST().
Mutate_InsertRepeatedBytes()
size_t fuzzer::MutationDispatcher::Mutate_InsertRepeatedBytes (uint8_t * Data, size_t Size, size_t MaxSize)
Mutates data by inserting several repeated bytes.
Definition at line 131 of file FuzzerMutate.cpp.
{
   const size_t kMinBytesToInsert = 3;
   if (Size + kMinBytesToInsert >= MaxSize) return 0;
   size_t MaxBytesToInsert = std::min(MaxSize - Size, (size_t)128);
   size_t N = Rand(MaxBytesToInsert - kMinBytesToInsert + 1) + kMinBytesToInsert;
   assert(Size + N <= MaxSize && N);
   size_t Idx = Rand(Size + 1);
   // Insert new values at Data[Idx].
   memmove(Data + Idx + N, Data + Idx, Size - Idx);
   // Give preference to 0x00 and 0xff.
   uint8_t Byte = Rand.RandBool() ? Rand(256) : (Rand.RandBool() ? 0 : 255);
   for (size_t i = 0; i < N; i++)
     Data[Idx + i] = Byte;
   return Size + N;
 }
References assert(), Idx, and N.
Referenced by TEST().
Mutate_ShuffleBytes()
size_t fuzzer::MutationDispatcher::Mutate_ShuffleBytes (uint8_t * Data, size_t Size, size_t MaxSize)
Mutates data by shuffling bytes.
Definition at line 95 of file FuzzerMutate.cpp.
{
   if (Size > MaxSize) return 0;
   assert(Size);
   size_t ShuffleAmount =
       Rand(std::min(Size, (size_t)8)) + 1; // [1,8] and <= Size.
   size_t ShuffleStart = Rand(Size - ShuffleAmount);
   assert(ShuffleStart + ShuffleAmount <= Size);
   std::random_shuffle(Data + ShuffleStart, Data + ShuffleStart + ShuffleAmount,
                       Rand);
   return Size;
 }
References assert().
Referenced by TEST().
MutateImpl()
size_t fuzzer::MutationDispatcher::MutateImpl (uint8_t * Data, size_t Size, size_t MaxSize, const std::vector< Mutator > & Mutators) private
Definition at line 484 of file FuzzerMutate.cpp.
{
   assert(MaxSize > 0);
   if (Size == 0) {
     for (size_t i = 0; i < MaxSize; i++)
       Data[i] = RandCh(Rand);
     if (Options.OnlyASCII)
       ToASCII(Data, MaxSize);
     return MaxSize;
   }
   assert(Size > 0);
   // Some mutations may fail (e.g. can't insert more bytes if Size == MaxSize),
   // in which case they will return 0.
   // Try several times before returning un-mutated data.
   for (int Iter = 0; Iter < 100; Iter++) {
     auto M = Mutators[Rand(Mutators.size())];
     size_t NewSize = (this->*(M.Fn))(Data, Size, MaxSize);
     if (NewSize && NewSize <= MaxSize) {
       if (Options.OnlyASCII)
         ToASCII(Data, NewSize);
       CurrentMutatorSequence.push_back(M);
       return NewSize;
     }
   }
   return std::min(Size, MaxSize);
 }
References assert(), fuzzer::RandCh(), and fuzzer::ToASCII().
PrintMutationSequence()
void fuzzer::MutationDispatcher::PrintMutationSequence ()
Print the current sequence of mutations.
Definition at line 461 of file FuzzerMutate.cpp.
{
   Printf("MS: %zd ", CurrentMutatorSequence.size());
   for (auto M : CurrentMutatorSequence)
     Printf("%s-", M.Name);
   if (!CurrentDictionaryEntrySequence.empty()) {
     Printf(" DE: ");
     for (auto DE : CurrentDictionaryEntrySequence) {
       Printf("\"");
       PrintASCII(DE->GetW(), "\"-");
     }
   }
 }
References fuzzer::PrintASCII(), and fuzzer::Printf().
Referenced by fuzzer::Fuzzer::DumpCurrentUnit(), and fuzzer::Fuzzer::PrintStatusForNewUnit().
PrintRecommendedDictionary()
void fuzzer::MutationDispatcher::PrintRecommendedDictionary ()
Definition at line 446 of file FuzzerMutate.cpp.
{
   std::vector<DictionaryEntry> V;
   for (auto &DE : PersistentAutoDictionary)
     if (!ManualDictionary.ContainsWord(DE.GetW()))
       V.push_back(DE);
   if (V.empty()) return;
   Printf("###### Recommended dictionary. ######\n");
   for (auto &DE: V) {
     Printf("\"");
     PrintASCII(DE.GetW(), "\"");
     Printf(" # Uses: %zd\n", DE.GetUseCount());
   }
   Printf("###### End of recommended dictionary. ######\n");
 }
References fuzzer::PrintASCII(), and fuzzer::Printf().
Referenced by fuzzer::Fuzzer::Loop().
RecordSuccessfulMutationSequence()
void fuzzer::MutationDispatcher::RecordSuccessfulMutationSequence ()
Indicate that the current sequence of mutations was successfull.
Definition at line 436 of file FuzzerMutate.cpp.
{
   for (auto DE : CurrentDictionaryEntrySequence) {
     // PersistentAutoDictionary.AddWithSuccessCountOne(DE);
     DE->IncSuccessCount();
     // Linear search is fine here as this happens seldom.
     if (!PersistentAutoDictionary.ContainsWord(DE->GetW()))
       PersistentAutoDictionary.push_back({DE->GetW(), 1});
   }
 }
Referenced by fuzzer::Fuzzer::ReportNewCoverage().
SetCorpus()
void fuzzer::MutationDispatcher::SetCorpus (const InputCorpus * Corpus) inline
Definition at line 90 of file FuzzerMutate.h.
 { this->Corpus = Corpus; }
References Corpus.
Referenced by fuzzer::Fuzzer::Loop().
StartMutationSequence()
void fuzzer::MutationDispatcher::StartMutationSequence ()
Indicate that we are about to start a new sequence of mutations.
Definition at line 430 of file FuzzerMutate.cpp.
{
   CurrentMutatorSequence.clear();
   CurrentDictionaryEntrySequence.clear();
 }
Referenced by fuzzer::Fuzzer::MinimizeCrashLoop(), and fuzzer::Fuzzer::MutateAndTestOne().
Member Data Documentation
CmpDictionaryEntriesDeque
DictionaryEntry fuzzer::MutationDispatcher::CmpDictionaryEntriesDeque[kCmpDictionaryEntriesDequeSize] private
Definition at line 133 of file FuzzerMutate.h.
CmpDictionaryEntriesDequeIdx
size_t fuzzer::MutationDispatcher::CmpDictionaryEntriesDequeIdx = 0 private
Definition at line 134 of file FuzzerMutate.h.
Corpus
const InputCorpus* fuzzer::MutationDispatcher::Corpus = nullptr private
Definition at line 136 of file FuzzerMutate.h.
Referenced by SetCorpus().
CurrentDictionaryEntrySequence
std::vector<DictionaryEntry *> fuzzer::MutationDispatcher::CurrentDictionaryEntrySequence private
Definition at line 130 of file FuzzerMutate.h.
CurrentMutatorSequence
std::vector<Mutator> fuzzer::MutationDispatcher::CurrentMutatorSequence private
Definition at line 129 of file FuzzerMutate.h.
DefaultMutators
std::vector<Mutator> fuzzer::MutationDispatcher::DefaultMutators private
Definition at line 140 of file FuzzerMutate.h.
Referenced by MutationDispatcher().
kCmpDictionaryEntriesDequeSize
const size_t fuzzer::MutationDispatcher::kCmpDictionaryEntriesDequeSize = 16 static private
Definition at line 132 of file FuzzerMutate.h.
ManualDictionary
Dictionary fuzzer::MutationDispatcher::ManualDictionary private
Definition at line 121 of file FuzzerMutate.h.
MutateInPlaceHere
std::vector<uint8_t> fuzzer::MutationDispatcher::MutateInPlaceHere private
Definition at line 137 of file FuzzerMutate.h.
Mutators
std::vector<Mutator> fuzzer::MutationDispatcher::Mutators private
Definition at line 139 of file FuzzerMutate.h.
Options
const FuzzingOptions& fuzzer::MutationDispatcher::Options private
Definition at line 118 of file FuzzerMutate.h.
PersistentAutoDictionary
Dictionary fuzzer::MutationDispatcher::PersistentAutoDictionary private
Definition at line 127 of file FuzzerMutate.h.
Rand
Random& fuzzer::MutationDispatcher::Rand private
Definition at line 117 of file FuzzerMutate.h.
Referenced by CrossOver(), and GetRand().
TempAutoDictionary
Dictionary fuzzer::MutationDispatcher::TempAutoDictionary private
Definition at line 124 of file FuzzerMutate.h.
The documentation for this class was generated from the following files:
mc_orchestrator/json-3.7.3/test/thirdparty/Fuzzer/FuzzerMutate.h
mc_orchestrator/json-3.7.3/test/thirdparty/Fuzzer/FuzzerCrossOver.cpp
mc_orchestrator/json-3.7.3/test/thirdparty/Fuzzer/FuzzerMutate.cpp