Mixed Criticality Orchestrator: PodmanApplyPodCommand Class Reference
PodmanApplyPodCommand Class Reference
#include <mco_podman_commands.hpp>
Public Member Functions
PodmanApplyPodCommand (const std::string &app_name_)
~PodmanApplyPodCommand ()=default
bool Execute () const override
Public Member Functions inherited from Command
virtual ~Command ()=default
Private Attributes
std::string app_name_
Detailed Description
Definition at line 44 of file mco_podman_commands.hpp.
Constructor & Destructor Documentation
PodmanApplyPodCommand()
PodmanApplyPodCommand::PodmanApplyPodCommand (const std::string & app_name_)
Definition at line 70 of file mco_podman_commands.cpp.
{
     this->app_name_ = app_name;
 }
~PodmanApplyPodCommand()
PodmanApplyPodCommand::~PodmanApplyPodCommand () default
Member Function Documentation
Execute()
bool PodmanApplyPodCommand::Execute () const override virtual
Implements Command.
Definition at line 74 of file mco_podman_commands.cpp.
{
     string pod_definition = DatabaseHandler::GetInstance().ReadData(this->app_name_, kYamlPath);
     string command = kPodmanApplyPods + pod_definition + " > " + kOutputFile;
     // Execute the command using system()
     system(command.c_str());
     Invoker invoker;
     invoker.SetCommand(make_unique<PodmanGetPodNameCommand>(this->app_name_));
     if (invoker.Invoke()) {
             // Updating the list of running apps in the database
             DatabaseHandler::GetInstance().running_apps_.emplace(this->app_name_);
             DatabaseHandler::GetInstance().UpdateRunningApps(kRunningApps, DatabaseHandler::GetInstance().running_apps_);
             DatabaseHandler::GetInstance().deleted_apps_.erase(this->app_name_);
             DatabaseHandler::GetInstance().UpdateRunningApps(kDeletedApps, DatabaseHandler::GetInstance().deleted_apps_);
             // Handling app priority updates
             string app_priority = DatabaseHandler::GetInstance().ReadData(this->app_name_, kAppPriority);
             if (app_priority == kHighPriority) {
                 DatabaseHandler::GetInstance().priority_high_apps_.emplace(this->app_name_);
                 DatabaseHandler::GetInstance().UpdateRunningApps(kPriorityHighApps, DatabaseHandler::GetInstance().priority_high_apps_);
             } else if (app_priority == kMediumPriority) {
                 DatabaseHandler::GetInstance().priority_medium_apps_.emplace(this->app_name_);
                 DatabaseHandler::GetInstance().UpdateRunningApps(kPriorityMediumApps, DatabaseHandler::GetInstance().priority_medium_apps_);
             } else if (app_priority == kLowPriority) {
                 DatabaseHandler::GetInstance().priority_low_apps_.emplace(this->app_name_);
                 DatabaseHandler::GetInstance().UpdateRunningApps(kPriorityLowApps, DatabaseHandler::GetInstance().priority_low_apps_);
             } else {}
         string msg = "Pod name is: " + DatabaseHandler::GetInstance().ReadData(this->app_name_, kPodName);
         // LOG(INFO) << msg;
         cout << msg << endl;
         return true;
     }
     else {
         string msg = "Failed to create pod";
         // LOG(ERROR) << msg;
         cout << msg << endl;
        }
     return true;
 }
References DatabaseHandler::deleted_apps_, DatabaseHandler::GetInstance(), Invoker::Invoke(), kAppPriority, kDeletedApps, kHighPriority, kLowPriority, kMediumPriority, kOutputFile, kPodmanApplyPods, kPodName, kPriorityHighApps, kPriorityLowApps, kPriorityMediumApps, kRunningApps, kYamlPath, DatabaseHandler::priority_high_apps_, DatabaseHandler::priority_low_apps_, DatabaseHandler::priority_medium_apps_, DatabaseHandler::ReadData(), DatabaseHandler::running_apps_, Invoker::SetCommand(), and DatabaseHandler::UpdateRunningApps().
Member Data Documentation
app_name_
std::string PodmanApplyPodCommand::app_name_ private
Definition at line 46 of file mco_podman_commands.hpp.
The documentation for this class was generated from the following files:
mc_orchestrator/runtime/inc/mco_podman_commands.hpp
mc_orchestrator/runtime/src/mco_podman_commands.cpp