Mixed Criticality Orchestrator: K3sApplyPodCommand Class Reference
K3sApplyPodCommand Class Reference
#include <mco_k3s_commands.hpp>
Public Member Functions
K3sApplyPodCommand (const std::string &app_name_)
~K3sApplyPodCommand ()=default
bool Execute () const override
Public Member Functions inherited from Command
virtual ~Command ()=default
Private Attributes
std::string app_name_
Detailed Description
Definition at line 44 of file mco_k3s_commands.hpp.
Constructor & Destructor Documentation
K3sApplyPodCommand()
K3sApplyPodCommand::K3sApplyPodCommand (const std::string & app_name_)
Definition at line 109 of file mco_k3s_commands.cpp.
{
     this->app_name_ = app_name;
 }
~K3sApplyPodCommand()
K3sApplyPodCommand::~K3sApplyPodCommand () default
Member Function Documentation
Execute()
bool K3sApplyPodCommand::Execute () const override virtual
Implements Command.
Definition at line 114 of file mco_k3s_commands.cpp.
{
     // This method should contain the logic to create a new pod
     string command = kK3sApplyPods + DatabaseHandler::GetInstance().ReadData(this->app_name_, kYamlPath) + " -o json > " + kOutputFile;
     system(command.c_str());
     Invoker invoker;
     invoker.SetCommand(make_unique<K3sGetPodNameCommand>(this->app_name_));
     if(invoker.Invoke()){
         // Updating the list of running apps in the database
         DatabaseHandler::GetInstance().running_apps_.emplace(this->app_name_);
         DatabaseHandler::GetInstance().UpdateRunningApps(kRunningApps, DatabaseHandler::GetInstance().running_apps_);
         DatabaseHandler::GetInstance().deleted_apps_.erase(this->app_name_);
         DatabaseHandler::GetInstance().UpdateRunningApps(kDeletedApps, DatabaseHandler::GetInstance().deleted_apps_);
         string app_priority = DatabaseHandler::GetInstance().ReadData(this->app_name_, kAppPriority);
         if(app_priority == kHighPriority){
             DatabaseHandler::GetInstance().priority_high_apps_.emplace(this->app_name_);
             DatabaseHandler::GetInstance().UpdateRunningApps(kPriorityHighApps, DatabaseHandler::GetInstance().priority_high_apps_);
         } else if(app_priority == kMediumPriority){
             DatabaseHandler::GetInstance().priority_medium_apps_.emplace(this->app_name_);
             DatabaseHandler::GetInstance().UpdateRunningApps(kPriorityMediumApps, DatabaseHandler::GetInstance().priority_medium_apps_);
         } else if(app_priority == kLowPriority){
             DatabaseHandler::GetInstance().priority_low_apps_.emplace(this->app_name_);
             DatabaseHandler::GetInstance().UpdateRunningApps(kPriorityLowApps, DatabaseHandler::GetInstance().priority_low_apps_);
         } else {}
         string msg = "Pod name is: " + DatabaseHandler::GetInstance().ReadData(this->app_name_, kPodName);
         // LOG(INFO) << msg;
         std::cout << msg << endl;
         return true;
     } else{
         string msg = "Failed to create pod";
         // LOG(ERROR) << msg;
         cout << msg << endl;
     }
     return true;
 }
References DatabaseHandler::deleted_apps_, DatabaseHandler::GetInstance(), Invoker::Invoke(), kAppPriority, kDeletedApps, kHighPriority, kK3sApplyPods, kLowPriority, kMediumPriority, kOutputFile, kPodName, kPriorityHighApps, kPriorityLowApps, kPriorityMediumApps, kRunningApps, kYamlPath, DatabaseHandler::priority_high_apps_, DatabaseHandler::priority_low_apps_, DatabaseHandler::priority_medium_apps_, DatabaseHandler::ReadData(), DatabaseHandler::running_apps_, Invoker::SetCommand(), and DatabaseHandler::UpdateRunningApps().
Member Data Documentation
app_name_
std::string K3sApplyPodCommand::app_name_ private
Definition at line 46 of file mco_k3s_commands.hpp.
The documentation for this class was generated from the following files:
mc_orchestrator/runtime/inc/mco_k3s_commands.hpp
mc_orchestrator/runtime/src/mco_k3s_commands.cpp