Mixed Criticality Orchestrator: BluechiStartAsilUnitCommand Class Reference
BluechiStartAsilUnitCommand Class Reference
#include <mco_bluechi_commands.hpp>
Public Member Functions
BluechiStartAsilUnitCommand (const std::string &app_name_)
~BluechiStartAsilUnitCommand ()=default
bool Execute () const override
Public Member Functions inherited from Command
virtual ~Command ()=default
Private Attributes
std::string app_name_
Detailed Description
Definition at line 44 of file mco_bluechi_commands.hpp.
Constructor & Destructor Documentation
BluechiStartAsilUnitCommand()
BluechiStartAsilUnitCommand::BluechiStartAsilUnitCommand (const std::string & app_name_)
Definition at line 103 of file mco_bluechi_commands.cpp.
{
     this->app_name_ = app_name;
 }
~BluechiStartAsilUnitCommand()
BluechiStartAsilUnitCommand::~BluechiStartAsilUnitCommand () default
Member Function Documentation
Execute()
bool BluechiStartAsilUnitCommand::Execute () const override virtual
Implements Command.
Definition at line 107 of file mco_bluechi_commands.cpp.
{
     string container_path = DatabaseHandler::GetInstance().ReadData(asil, this->app_name_, kYamlPath);
     //string container_path = DatabaseHandler::GetInstance().ReadData(this->app_name_, kYamlPath);
     //cout<<container_path<<endl;
     string dest_path = kAsilSystemdPath + container_path.substr(container_path.find_last_of("/\\") + 1);
     cout << "Copying file to: " << dest_path << endl;
     // Using system command to copy the file
     string copy_command = "sudo cp " + container_path + " " + dest_path;
     int result = system(copy_command.c_str());
     if (result != kSuccess) {
         cerr << "Failed to copy the file." << endl;
         return 1;
     }
     // Reload systemd daemon
     string command = kBluechiGenerateServiceFile + kAsilNodeName;
     result = system(command.c_str());
     if (result != kSuccess) {
         cerr << "Failed to reload systemd daemon." << endl;
         return 1;
     }
     // Start the service (assuming service file name is the same as the container file)
     string service_file = app_name_ + ".service";
     cout << service_file << endl;
     string start_service_cmd = kBluechiApplyPods + kAsilNodeName + " " + service_file;
     // Start the service
     result = system(start_service_cmd.c_str());
     if (result != kSuccess) {
         cerr << "Failed to start the service." << endl;
         return 1;
     }
     DatabaseHandler::GetInstance().asil_b_running_apps_.emplace(this->app_name_);
     DatabaseHandler::GetInstance().UpdateRunningApps(kAsilRunningApps, DatabaseHandler::GetInstance().asil_b_running_apps_);
     DatabaseHandler::GetInstance().asil_b_stopped_apps_.erase(this->app_name_);
     DatabaseHandler::GetInstance().UpdateRunningApps(kAsilStoppedApps, DatabaseHandler::GetInstance().asil_b_stopped_apps_);
     return true;
 }
References asil, DatabaseHandler::asil_b_running_apps_, DatabaseHandler::asil_b_stopped_apps_, DatabaseHandler::GetInstance(), kAsilNodeName, kAsilRunningApps, kAsilStoppedApps, kAsilSystemdPath, kBluechiApplyPods, kBluechiGenerateServiceFile, kSuccess, kYamlPath, DatabaseHandler::ReadData(), result, and DatabaseHandler::UpdateRunningApps().
Member Data Documentation
app_name_
std::string BluechiStartAsilUnitCommand::app_name_ private
Definition at line 46 of file mco_bluechi_commands.hpp.
The documentation for this class was generated from the following files:
mc_orchestrator/runtime/inc/mco_bluechi_commands.hpp
mc_orchestrator/runtime/src/mco_bluechi_commands.cpp