Mixed Criticality Orchestrator: QmOtaHandler Class Reference
QmOtaHandler Class Reference
QmOtaHandler is handle OTA download of QM Infotainment apps.
#include <mco_qm_ota_handler.hpp>
Public Member Functions
void Init ()
Initialize QM Pod Handler.
bool OtaDownloadSuccessful ()
Check for successful OTA download.
Static Public Member Functions
static QmOtaHandler & GetInstance ()
Public static method getInstance(). This function is.
Private Member Functions
QmOtaHandler ()=default
Define constructor in the private section to make this class as singleton.
~QmOtaHandler ()=default
Define destructor in private section, so no one can delete the instance of this class.
QmOtaHandler (const QmOtaHandler &obj)
Define copy constructor in the private section, so that no one can voilate the singleton policy of this class.
void operator= (const QmOtaHandler &obj)
Define assignment operator in the private section, so that no one can voilate the singleton policy of this class.
Detailed Description
QmOtaHandler is handle OTA download of QM Infotainment apps.
Definition at line 14 of file mco_qm_ota_handler.hpp.
Constructor & Destructor Documentation
QmOtaHandler() [1/2]
QmOtaHandler::QmOtaHandler () private default
Define constructor in the private section to make this class as singleton.
~QmOtaHandler()
QmOtaHandler::~QmOtaHandler () private default
Define destructor in private section, so no one can delete the instance of this class.
QmOtaHandler() [2/2]
QmOtaHandler::QmOtaHandler (const QmOtaHandler & obj) inline private
Define copy constructor in the private section, so that no one can voilate the singleton policy of this class.
Definition at line 24 of file mco_qm_ota_handler.hpp.
 {}
Member Function Documentation
GetInstance()
QmOtaHandler & QmOtaHandler::GetInstance () static
Public static method getInstance(). This function is.
Definition at line 13 of file mco_qm_ota_handler.cpp.
 {
     static QmOtaHandler self{};
     return self;
 }
Referenced by main().
Init()
void QmOtaHandler::Init ()
Initialize QM Pod Handler.
Definition at line 40 of file mco_qm_ota_handler.cpp.
{
     // Check for successful OTA download
     while(true) {
         if(OtaDownloadSuccessful()){
             std::cout << "OTA download successful" << std::endl;
         } else {
             // std::cout << "OTA download failed" << std::endl;
         }
     }
 }
Referenced by main().
operator=()
void QmOtaHandler::operator= (const QmOtaHandler & obj) inline private
Define assignment operator in the private section, so that no one can voilate the singleton policy of this class.
Definition at line 27 of file mco_qm_ota_handler.hpp.
 {}
OtaDownloadSuccessful()
bool QmOtaHandler::OtaDownloadSuccessful ()
Check for successful OTA download.
Definition at line 19 of file mco_qm_ota_handler.cpp.
{
     // Check for successful OTA download
     std::string app_name = DatabaseHandler::GetInstance().ReadStringData(ota_downloaded_qm_app);
     if (app_name.empty()) {
         return false;
     }
     std::cout << "OTA Status: " << app_name << std::endl;
     kPath = kQmInfoGames;
     DatabaseHandler::GetInstance().AppendData(infotainment, "games", "downloaded", kPath);
     ConfigHandler configHandler;
     configHandler.SaveAppNameToDatabase(qm_infotainment_games_available, DatabaseHandler::GetInstance().qm_infotainment_games_available_, kPath);
     DatabaseHandler::GetInstance().AddData(available_qm_app, app_name);
     DatabaseHandler::GetInstance().AddData(ota_downloaded_qm_app, "");
     return true;
 }
References DatabaseHandler::AddData(), DatabaseHandler::AppendData(), available_qm_app, DatabaseHandler::GetInstance(), infotainment, kPath, kQmInfoGames, ota_downloaded_qm_app, qm_infotainment_games_available, DatabaseHandler::ReadStringData(), and ConfigHandler::SaveAppNameToDatabase().
The documentation for this class was generated from the following files:
mc_orchestrator/bl/inc/mco_qm_ota_handler.hpp
mc_orchestrator/bl/src/mco_qm_ota_handler.cpp