Mixed Criticality Orchestrator: Invoker Class Reference
Invoker Class Reference
#include <mco_commands.hpp>
Public Member Functions
void SetCommand (std::unique_ptr< Command > cmd)
bool Invoke ()
Private Attributes
std::unique_ptr< Command > command_
Detailed Description
Definition at line 15 of file mco_commands.hpp.
Member Function Documentation
Invoke()
bool Invoker::Invoke () inline
Definition at line 21 of file mco_commands.hpp.
                   {
         if (command_) {
             return command_->Execute();
         }
         return false;
     }
References command_.
Referenced by DeletePodObserver::DeleteAllPods(), K3sApplyPodCommand::Execute(), PodmanApplyPodCommand::Execute(), ConfigHandler::GetValue(), ResourceMonitorHandler::Init(), AvpTriggerMonitorHandler::Init(), UserAppControlHandler::PlayAsilApp(), UserAppControlHandler::PlayQmApp(), RespawnPodObserver::RespawnAllPods(), ServerHandler::StartMcOrchestratorServer(), UserAppControlHandler::StopAsilApp(), and UserAppControlHandler::StopQmApp().
SetCommand()
void Invoker::SetCommand (std::unique_ptr< Command > cmd) inline
Definition at line 18 of file mco_commands.hpp.
{
         command_ = std::move(cmd);
     }
References command_.
Referenced by DeletePodObserver::DeleteAllPods(), K3sApplyPodCommand::Execute(), PodmanApplyPodCommand::Execute(), ConfigHandler::GetValue(), ResourceMonitorHandler::Init(), AvpTriggerMonitorHandler::Init(), UserAppControlHandler::PlayAsilApp(), UserAppControlHandler::PlayQmApp(), RespawnPodObserver::RespawnAllPods(), ServerHandler::StartMcOrchestratorServer(), UserAppControlHandler::StopAsilApp(), and UserAppControlHandler::StopQmApp().
Member Data Documentation
command_
std::unique_ptr<Command> Invoker::command_ private
Definition at line 16 of file mco_commands.hpp.
Referenced by Invoke(), and SetCommand().
The documentation for this class was generated from the following file:
mc_orchestrator/runtime/inc/mco_commands.hpp