Mixed Criticality Orchestrator: benchmark::State Class Reference
benchmark::State Class Reference
#include <benchmark.h>
Classes
struct StateIterator
Public Member Functions
StateIterator begin ()
StateIterator end ()
bool KeepRunning ()
bool KeepRunningBatch (size_t n)
void PauseTiming ()
void ResumeTiming ()
void SkipWithError (const char *msg)
void SetIterationTime (double seconds)
void SetBytesProcessed (int64_t bytes)
int64_t bytes_processed () const
void SetComplexityN (int64_t complexity_n)
int64_t complexity_length_n ()
void SetItemsProcessed (int64_t items)
int64_t items_processed () const
void SetLabel (const char *label)
void SetLabel (const std::string &str)
int64_t range (std::size_t pos=0) const
int64_t range_x () const
int64_t range_y () const
size_t iterations () const
State (size_t max_iters, const std::vector< int64_t > &ranges, int thread_i, int n_threads, internal::ThreadTimer *timer, internal::ThreadManager *manager)
Public Attributes
const size_t max_iterations
UserCounters counters
const int thread_index
const int threads
Private Member Functions
void StartKeepRunning ()
bool KeepRunningInternal (size_t n, bool is_batch)
void FinishKeepRunning ()
State (const State &)
State & operator= (const State &)
Private Attributes
size_t total_iterations_
size_t batch_leftover_
bool started_
bool finished_
bool error_occurred_
std::vector< int64_t > range_
int64_t bytes_processed_
int64_t items_processed_
int64_t complexity_n_
internal::ThreadTimer * timer_
internal::ThreadManager * manager_
Friends
struct StateIterator
Detailed Description
Definition at line 420 of file benchmark.h.
Constructor & Destructor Documentation
State() [1/2]
benchmark::State::State (size_t max_iters, const std::vector< int64_t > & ranges, int thread_i, int n_threads, internal::ThreadTimer * timer, internal::ThreadManager * manager)
State() [2/2]
benchmark::State::State (const State &) private
Member Function Documentation
begin()
State::StateIterator benchmark::State::begin () inline
Definition at line 714 of file benchmark.h.
{
   return StateIterator(this);
 }
References StateIterator.
bytes_processed()
int64_t benchmark::State::bytes_processed () const inline
Definition at line 520 of file benchmark.h.
 { return bytes_processed_; }
References bytes_processed_.
complexity_length_n()
int64_t benchmark::State::complexity_length_n () inline
Definition at line 531 of file benchmark.h.
 { return complexity_n_; }
References complexity_n_.
end()
State::StateIterator benchmark::State::end () inline
Definition at line 717 of file benchmark.h.
{
   StartKeepRunning();
   return StateIterator();
 }
References StartKeepRunning(), and StateIterator.
FinishKeepRunning()
void benchmark::State::FinishKeepRunning () private
Referenced by KeepRunningInternal(), and benchmark::State::StateIterator::operator!=().
items_processed()
int64_t benchmark::State::items_processed () const inline
Definition at line 543 of file benchmark.h.
 { return items_processed_; }
References items_processed_.
iterations()
size_t benchmark::State::iterations () const inline
Definition at line 577 of file benchmark.h.
{
     if (BENCHMARK_BUILTIN_EXPECT(!started_, false)) {
       return 0;
     }
     return max_iterations - total_iterations_ + batch_leftover_;
   }
References batch_leftover_, BENCHMARK_BUILTIN_EXPECT, max_iterations, started_, and total_iterations_.
Referenced by Dump(), ParseFile(), and ParseString().
KeepRunning()
bool benchmark::State::KeepRunning () inline
Definition at line 637 of file benchmark.h.
{
   return KeepRunningInternal(1, /*is_batch=*/ false);
 }
References KeepRunningInternal().
Referenced by Dump(), ParseFile(), and ParseString().
KeepRunningBatch()
bool benchmark::State::KeepRunningBatch (size_t n) inline
Definition at line 642 of file benchmark.h.
{
   return KeepRunningInternal(n, /*is_batch=*/ true);
 }
References KeepRunningInternal(), and n.
KeepRunningInternal()
bool benchmark::State::KeepRunningInternal (size_t n, bool is_batch) inline private
Definition at line 647 of file benchmark.h.
{
   // total_iterations_ is set to 0 by the constructor, and always set to a
   // nonzero value by StartKepRunning().
   assert(n > 0);
   // n must be 1 unless is_batch is true.
   assert(is_batch || n == 1);
   if (BENCHMARK_BUILTIN_EXPECT(total_iterations_ >= n, true)) {
     total_iterations_ -= n;
     return true;
   }
   if (!started_) {
     StartKeepRunning();
     if (!error_occurred_ && total_iterations_ >= n) {
       total_iterations_-= n;
       return true;
     }
   }
   // For non-batch runs, total_iterations_ must be 0 by now.
   if (is_batch && total_iterations_ != 0) {
     batch_leftover_  = n - total_iterations_;
     total_iterations_ = 0;
     return true;
   }
   FinishKeepRunning();
   return false;
 }
References assert(), batch_leftover_, BENCHMARK_BUILTIN_EXPECT, error_occurred_, FinishKeepRunning(), n, started_, StartKeepRunning(), and total_iterations_.
Referenced by KeepRunning(), and KeepRunningBatch().
operator=()
State& benchmark::State::operator= (const State &) private
PauseTiming()
void benchmark::State::PauseTiming ()
Referenced by ParseFile(), and ParseString().
range()
int64_t benchmark::State::range (std::size_t pos = 0) const inline
Definition at line 565 of file benchmark.h.
{
     assert(range_.size() > pos);
     return range_[pos];
   }
References assert(), and range_.
Referenced by range_x(), and range_y().
range_x()
int64_t benchmark::State::range_x () const inline
Definition at line 571 of file benchmark.h.
 { return range(0); }
References range().
range_y()
int64_t benchmark::State::range_y () const inline
Definition at line 574 of file benchmark.h.
 { return range(1); }
References range().
ResumeTiming()
void benchmark::State::ResumeTiming ()
Referenced by ParseFile(), and ParseString().
SetBytesProcessed()
void benchmark::State::SetBytesProcessed (int64_t bytes) inline
Definition at line 517 of file benchmark.h.
 { bytes_processed_ = bytes; }
References bytes_processed_.
Referenced by Dump(), ParseFile(), and ParseString().
SetComplexityN()
void benchmark::State::SetComplexityN (int64_t complexity_n) inline
Definition at line 528 of file benchmark.h.
 { complexity_n_ = complexity_n; }
References complexity_n_.
SetItemsProcessed()
void benchmark::State::SetItemsProcessed (int64_t items) inline
Definition at line 540 of file benchmark.h.
 { items_processed_ = items; }
References items_processed_.
SetIterationTime()
void benchmark::State::SetIterationTime (double seconds)
SetLabel() [1/2]
void benchmark::State::SetLabel (const char * label)
Referenced by SetLabel().
SetLabel() [2/2]
void benchmark::State::SetLabel (const std::string & str) inline
Definition at line 559 of file benchmark.h.
{
     this->SetLabel(str.c_str());
   }
References SetLabel().
SkipWithError()
void benchmark::State::SkipWithError (const char * msg)
StartKeepRunning()
void benchmark::State::StartKeepRunning () private
Referenced by end(), and KeepRunningInternal().
Friends And Related Function Documentation
StateIterator
friend struct StateIterator friend
Definition at line 422 of file benchmark.h.
Referenced by begin(), and end().
Member Data Documentation
batch_leftover_
size_t benchmark::State::batch_leftover_ private
Definition at line 593 of file benchmark.h.
Referenced by iterations(), and KeepRunningInternal().
bytes_processed_
int64_t benchmark::State::bytes_processed_ private
Definition at line 606 of file benchmark.h.
Referenced by bytes_processed(), and SetBytesProcessed().
complexity_n_
int64_t benchmark::State::complexity_n_ private
Definition at line 609 of file benchmark.h.
Referenced by complexity_length_n(), and SetComplexityN().
counters
UserCounters benchmark::State::counters
Definition at line 613 of file benchmark.h.
error_occurred_
bool benchmark::State::error_occurred_ private
Definition at line 601 of file benchmark.h.
Referenced by KeepRunningInternal().
finished_
bool benchmark::State::finished_ private
Definition at line 600 of file benchmark.h.
items_processed_
int64_t benchmark::State::items_processed_ private
Definition at line 607 of file benchmark.h.
Referenced by items_processed(), and SetItemsProcessed().
manager_
internal::ThreadManager* benchmark::State::manager_ private
Definition at line 632 of file benchmark.h.
max_iterations
const size_t benchmark::State::max_iterations
Definition at line 596 of file benchmark.h.
Referenced by iterations().
range_
std::vector<int64_t> benchmark::State::range_ private
Definition at line 604 of file benchmark.h.
Referenced by range().
started_
bool benchmark::State::started_ private
Definition at line 599 of file benchmark.h.
Referenced by iterations(), and KeepRunningInternal().
thread_index
const int benchmark::State::thread_index
Definition at line 615 of file benchmark.h.
threads
const int benchmark::State::threads
Definition at line 617 of file benchmark.h.
timer_
internal::ThreadTimer* benchmark::State::timer_ private
Definition at line 631 of file benchmark.h.
total_iterations_
size_t benchmark::State::total_iterations_ private
Definition at line 588 of file benchmark.h.
Referenced by iterations(), and KeepRunningInternal().
The documentation for this class was generated from the following file:
mc_orchestrator/json-3.7.3/benchmarks/thirdparty/benchmark/include/benchmark/benchmark.h