Mixed Criticality Orchestrator: K3sPodUsageCommand Class Reference
K3sPodUsageCommand Class Reference
#include <mco_k3s_commands.hpp>
Public Member Functions
K3sPodUsageCommand (const std::string &app_name_)
~K3sPodUsageCommand ()=default
bool Execute () const override
Public Member Functions inherited from Command
virtual ~Command ()=default
Private Attributes
std::string app_name_
Detailed Description
Definition at line 74 of file mco_k3s_commands.hpp.
Constructor & Destructor Documentation
K3sPodUsageCommand()
K3sPodUsageCommand::K3sPodUsageCommand (const std::string & app_name_)
Definition at line 239 of file mco_k3s_commands.cpp.
{
     this->app_name_ = app_name;
 }
~K3sPodUsageCommand()
K3sPodUsageCommand::~K3sPodUsageCommand () default
Member Function Documentation
Execute()
bool K3sPodUsageCommand::Execute () const override virtual
Implements Command.
Definition at line 243 of file mco_k3s_commands.cpp.
{
     // This method should contain the logic to get the usage of a pod
     string pod_name = DatabaseHandler::GetInstance().ReadData(this->app_name_, kPodName);
     string command = kK3sPodUsage + pod_name + " > " + kOutputFile;
     int response = system(command.c_str());
     if (response == kSuccess){
         string msg = "Pod usage details have been generated";
         // LOG(INFO) << msg;
         cout << msg << endl;
         ifstream file(kOutputFile);
         string line;
         getline(file, line);  // Skip the header line
         while (getline(file, line)) {
             istringstream iss(line);
             string name, cpu, memory;
             iss >> name >> cpu >> memory;
             current_cpu = cpu;
             current_memory = memory;
         }
         msg = "Pod name: " + pod_name + " CPU: " + current_cpu + " Memory: " + current_memory;
         // LOG(INFO) << msg;
         cout << msg << endl;
         DatabaseHandler::GetInstance().AddData("cache", msg);
         return true;
     } else {
         string msg = "Failed to generate pod usage details";
         // LOG(ERROR) << msg;
         cout << msg << endl;
         DatabaseHandler::GetInstance().AddData("cache", msg);
         return false;
     }
 }
References DatabaseHandler::AddData(), current_cpu, current_memory, DatabaseHandler::GetInstance(), kK3sPodUsage, kOutputFile, kPodName, kSuccess, and DatabaseHandler::ReadData().
Member Data Documentation
app_name_
std::string K3sPodUsageCommand::app_name_ private
Definition at line 76 of file mco_k3s_commands.hpp.
The documentation for this class was generated from the following files:
mc_orchestrator/runtime/inc/mco_k3s_commands.hpp
mc_orchestrator/runtime/src/mco_k3s_commands.cpp