Mixed Criticality Orchestrator: fuzzer::DictionaryEntry Class Reference
fuzzer::DictionaryEntry Class Reference
#include <FuzzerDictionary.h>
Public Member Functions
DictionaryEntry ()
DictionaryEntry (Word W)
DictionaryEntry (Word W, size_t PositionHint)
const Word & GetW () const
bool HasPositionHint () const
size_t GetPositionHint () const
void IncUseCount ()
void IncSuccessCount ()
size_t GetUseCount () const
size_t GetSuccessCount () const
void Print (const char *PrintAfter="\n")
Private Attributes
Word W
size_t PositionHint = std::numeric_limits<size_t>::max()
size_t UseCount = 0
size_t SuccessCount = 0
Detailed Description
Definition at line 55 of file FuzzerDictionary.h.
Constructor & Destructor Documentation
DictionaryEntry() [1/3]
fuzzer::DictionaryEntry::DictionaryEntry () inline
Definition at line 57 of file FuzzerDictionary.h.
 {}
DictionaryEntry() [2/3]
fuzzer::DictionaryEntry::DictionaryEntry (Word W) inline
Definition at line 58 of file FuzzerDictionary.h.
 : W(W) {}
DictionaryEntry() [3/3]
fuzzer::DictionaryEntry::DictionaryEntry (Word W, size_t PositionHint) inline
Definition at line 59 of file FuzzerDictionary.h.
 : W(W), PositionHint(PositionHint) {}
Member Function Documentation
GetPositionHint()
size_t fuzzer::DictionaryEntry::GetPositionHint () const inline
Definition at line 63 of file FuzzerDictionary.h.
{
     assert(HasPositionHint());
     return PositionHint;
   }
References assert(), HasPositionHint(), and PositionHint.
Referenced by fuzzer::MutationDispatcher::ApplyDictionaryEntry(), and Print().
GetSuccessCount()
size_t fuzzer::DictionaryEntry::GetSuccessCount () const inline
Definition at line 70 of file FuzzerDictionary.h.
 {return SuccessCount; }
References SuccessCount.
GetUseCount()
size_t fuzzer::DictionaryEntry::GetUseCount () const inline
Definition at line 69 of file FuzzerDictionary.h.
 { return UseCount; }
References UseCount.
GetW()
const Word& fuzzer::DictionaryEntry::GetW () const inline
Definition at line 60 of file FuzzerDictionary.h.
 { return W; }
References W.
Referenced by fuzzer::MutationDispatcher::ApplyDictionaryEntry(), and fuzzer::Dictionary::ContainsWord().
HasPositionHint()
bool fuzzer::DictionaryEntry::HasPositionHint () const inline
Definition at line 62 of file FuzzerDictionary.h.
 { return PositionHint != std::numeric_limits<size_t>::max(); }
References PositionHint.
Referenced by fuzzer::MutationDispatcher::ApplyDictionaryEntry(), GetPositionHint(), and Print().
IncSuccessCount()
void fuzzer::DictionaryEntry::IncSuccessCount () inline
Definition at line 68 of file FuzzerDictionary.h.
 { SuccessCount++; }
References SuccessCount.
IncUseCount()
void fuzzer::DictionaryEntry::IncUseCount () inline
Definition at line 67 of file FuzzerDictionary.h.
 { UseCount++; }
References UseCount.
Referenced by fuzzer::MutationDispatcher::AddWordFromDictionary().
Print()
void fuzzer::DictionaryEntry::Print (const char * PrintAfter = "\n") inline
Definition at line 72 of file FuzzerDictionary.h.
{
     PrintASCII(W.data(), W.size());
     if (HasPositionHint())
       Printf("@%zd", GetPositionHint());
     Printf("%s", PrintAfter);
   }
References fuzzer::FixedWord< kMaxSize >::data(), GetPositionHint(), HasPositionHint(), fuzzer::PrintASCII(), fuzzer::Printf(), fuzzer::FixedWord< kMaxSize >::size(), and W.
Member Data Documentation
PositionHint
size_t fuzzer::DictionaryEntry::PositionHint = std::numeric_limits<size_t>::max() private
Definition at line 81 of file FuzzerDictionary.h.
Referenced by GetPositionHint(), and HasPositionHint().
SuccessCount
size_t fuzzer::DictionaryEntry::SuccessCount = 0 private
Definition at line 83 of file FuzzerDictionary.h.
Referenced by GetSuccessCount(), and IncSuccessCount().
UseCount
size_t fuzzer::DictionaryEntry::UseCount = 0 private
Definition at line 82 of file FuzzerDictionary.h.
Referenced by GetUseCount(), and IncUseCount().
W
Word fuzzer::DictionaryEntry::W private
Definition at line 80 of file FuzzerDictionary.h.
Referenced by GetW(), and Print().
The documentation for this class was generated from the following file:
mc_orchestrator/json-3.7.3/test/thirdparty/Fuzzer/FuzzerDictionary.h