Mixed Criticality Orchestrator: httplib::detail::mmap Class Reference
httplib::detail::mmap Class Reference
#include <httplib.h>
Public Member Functions
mmap (const char *path)
~mmap ()
bool open (const char *path)
void close ()
bool is_open () const
size_t size () const
const char * data () const
Private Attributes
int fd_
size_t size_
void * addr_
Detailed Description
Definition at line 2257 of file httplib.h.
Constructor & Destructor Documentation
mmap()
httplib::detail::mmap::mmap (const char * path) inline
Definition at line 2672 of file httplib.h.
     : hFile_(NULL), hMapping_(NULL)
 #else
     : fd_(-1)
 #endif
       ,
       size_(0), addr_(nullptr) {
   open(path);
 }
Referenced by open().
~mmap()
httplib::detail::mmap::~mmap () inline
Definition at line 2683 of file httplib.h.
 { close(); }
References close().
Member Function Documentation
close()
void httplib::detail::mmap::close () inline
Definition at line 2742 of file httplib.h.
{
 #if defined(_WIN32)
   if (addr_) {
     ::UnmapViewOfFile(addr_);
     addr_ = nullptr;
   }
   if (hMapping_) {
     ::CloseHandle(hMapping_);
     hMapping_ = NULL;
   }
   if (hFile_ != INVALID_HANDLE_VALUE) {
     ::CloseHandle(hFile_);
     hFile_ = INVALID_HANDLE_VALUE;
   }
 #else
   if (addr_ != nullptr) {
     munmap(addr_, size_);
     addr_ = nullptr;
   }
   if (fd_ != -1) {
     ::close(fd_);
     fd_ = -1;
   }
 #endif
   size_ = 0;
 }
References addr_, fd_, and size_.
Referenced by open(), and ~mmap().
data()
const char * httplib::detail::mmap::data () const inline
Definition at line 2738 of file httplib.h.
{
   return static_cast<const char *>(addr_);
 }
References addr_.
is_open()
bool httplib::detail::mmap::is_open () const inline
Definition at line 2734 of file httplib.h.
 { return addr_ != nullptr; }
References addr_.
open()
bool httplib::detail::mmap::open (const char * path) inline
Definition at line 2685 of file httplib.h.
{
   close();
 #if defined(_WIN32)
   std::wstring wpath;
   for (size_t i = 0; i < strlen(path); i++) {
     wpath += path[i];
   }
   hFile_ = ::CreateFile2(wpath.c_str(), GENERIC_READ, FILE_SHARE_READ,
                          OPEN_EXISTING, NULL);
   if (hFile_ == INVALID_HANDLE_VALUE) { return false; }
   LARGE_INTEGER size{};
   if (!::GetFileSizeEx(hFile_, &size)) { return false; }
   size_ = static_cast<size_t>(size.QuadPart);
   hMapping_ = ::CreateFileMappingFromApp(hFile_, NULL, PAGE_READONLY, size_,
                                          NULL);
   if (hMapping_ == NULL) {
     close();
     return false;
   }
   addr_ = ::MapViewOfFileFromApp(hMapping_, FILE_MAP_READ, 0, 0);
 #else
   fd_ = ::open(path, O_RDONLY);
   if (fd_ == -1) { return false; }
   struct stat sb;
   if (fstat(fd_, &sb) == -1) {
     close();
     return false;
   }
   size_ = static_cast<size_t>(sb.st_size);
   addr_ = ::mmap(NULL, size_, PROT_READ, MAP_PRIVATE, fd_, 0);
 #endif
   if (addr_ == nullptr) {
     close();
     return false;
   }
   return true;
 }
References addr_, close(), fd_, mmap(), size(), and size_.
size()
size_t httplib::detail::mmap::size () const inline
Definition at line 2736 of file httplib.h.
 { return size_; }
References size_.
Referenced by open().
Member Data Documentation
addr_
void* httplib::detail::mmap::addr_ private
Definition at line 2277 of file httplib.h.
Referenced by close(), data(), is_open(), and open().
fd_
int httplib::detail::mmap::fd_ private
Definition at line 2274 of file httplib.h.
Referenced by close(), and open().
size_
size_t httplib::detail::mmap::size_ private
Definition at line 2276 of file httplib.h.
Referenced by close(), open(), and size().
The documentation for this class was generated from the following file:
mc_orchestrator/httplib/httplib.h