Mixed Criticality Orchestrator: nlohmann::detail::primitive_iterator_t Class Reference
nlohmann::detail::primitive_iterator_t Class Reference
#include <primitive_iterator.hpp>
Public Member Functions
constexpr difference_type get_value () const noexcept
void set_begin () noexcept
set iterator to a defined beginning
void set_end () noexcept
set iterator to a defined past the end
constexpr bool is_begin () const noexcept
return whether the iterator can be dereferenced
constexpr bool is_end () const noexcept
return whether the iterator is at end
primitive_iterator_t operator+ (difference_type n) noexcept
primitive_iterator_t & operator++ () noexcept
const primitive_iterator_t operator++ (int) noexcept
primitive_iterator_t & operator-- () noexcept
const primitive_iterator_t operator-- (int) noexcept
primitive_iterator_t & operator+= (difference_type n) noexcept
primitive_iterator_t & operator-= (difference_type n) noexcept
constexpr difference_type get_value () const noexcept
void set_begin () noexcept
set iterator to a defined beginning
void set_end () noexcept
set iterator to a defined past the end
constexpr bool is_begin () const noexcept
return whether the iterator can be dereferenced
constexpr bool is_end () const noexcept
return whether the iterator is at end
primitive_iterator_t operator+ (difference_type n) noexcept
primitive_iterator_t & operator++ () noexcept
const primitive_iterator_t operator++ (int) noexcept
primitive_iterator_t & operator-- () noexcept
const primitive_iterator_t operator-- (int) noexcept
primitive_iterator_t & operator+= (difference_type n) noexcept
primitive_iterator_t & operator-= (difference_type n) noexcept
Private Types
using difference_type = std::ptrdiff_t
using difference_type = std::ptrdiff_t
Private Attributes
difference_type m_it = (std::numeric_limits<std::ptrdiff_t>::min)()
iterator as signed integer type
Static Private Attributes
static constexpr difference_type begin_value = 0
static constexpr difference_type end_value = begin_value + 1
Friends
constexpr friend bool operator== (primitive_iterator_t lhs, primitive_iterator_t rhs) noexcept
constexpr friend bool operator< (primitive_iterator_t lhs, primitive_iterator_t rhs) noexcept
constexpr friend difference_type operator- (primitive_iterator_t lhs, primitive_iterator_t rhs) noexcept
constexpr friend bool operator== (primitive_iterator_t lhs, primitive_iterator_t rhs) noexcept
constexpr friend bool operator< (primitive_iterator_t lhs, primitive_iterator_t rhs) noexcept
constexpr friend difference_type operator- (primitive_iterator_t lhs, primitive_iterator_t rhs) noexcept
Detailed Description
Definition at line 19 of file primitive_iterator.hpp.
Member Typedef Documentation
difference_type [1/2]
using nlohmann::detail::primitive_iterator_t::difference_type = std::ptrdiff_t private
Definition at line 22 of file primitive_iterator.hpp.
difference_type [2/2]
using nlohmann::detail::primitive_iterator_t::difference_type = std::ptrdiff_t private
Definition at line 9176 of file json.hpp.
Member Function Documentation
get_value() [1/2]
constexpr difference_type nlohmann::detail::primitive_iterator_t::get_value () const inline constexpr noexcept
Definition at line 30 of file primitive_iterator.hpp.
     {
         return m_it;
     }
References m_it.
Referenced by nlohmann::detail::iter_impl< BasicJsonType >::operator[]().
get_value() [2/2]
constexpr difference_type nlohmann::detail::primitive_iterator_t::get_value () const inline constexpr noexcept
Definition at line 9184 of file json.hpp.
     {
         return m_it;
     }
References m_it.
is_begin() [1/2]
constexpr bool nlohmann::detail::primitive_iterator_t::is_begin () const inline constexpr noexcept
return whether the iterator can be dereferenced
Definition at line 48 of file primitive_iterator.hpp.
     {
         return m_it == begin_value;
     }
References begin_value, and m_it.
Referenced by nlohmann::detail::iter_impl< BasicJsonType >::operator*(), and nlohmann::detail::iter_impl< BasicJsonType >::operator->().
is_begin() [2/2]
constexpr bool nlohmann::detail::primitive_iterator_t::is_begin () const inline constexpr noexcept
return whether the iterator can be dereferenced
Definition at line 9202 of file json.hpp.
     {
         return m_it == begin_value;
     }
References begin_value, and m_it.
is_end() [1/2]
constexpr bool nlohmann::detail::primitive_iterator_t::is_end () const inline constexpr noexcept
return whether the iterator is at end
Definition at line 54 of file primitive_iterator.hpp.
     {
         return m_it == end_value;
     }
References end_value, and m_it.
is_end() [2/2]
constexpr bool nlohmann::detail::primitive_iterator_t::is_end () const inline constexpr noexcept
return whether the iterator is at end
Definition at line 9208 of file json.hpp.
     {
         return m_it == end_value;
     }
References end_value, and m_it.
operator+() [1/2]
primitive_iterator_t nlohmann::detail::primitive_iterator_t::operator+ (difference_type n) inline noexcept
Definition at line 69 of file primitive_iterator.hpp.
     {
         auto result = *this;
         result += n;
         return result;
     }
References n, and result.
operator+() [2/2]
primitive_iterator_t nlohmann::detail::primitive_iterator_t::operator+ (difference_type n) inline noexcept
Definition at line 9223 of file json.hpp.
     {
         auto result = *this;
         result += n;
         return result;
     }
References n, and result.
operator++() [1/4]
primitive_iterator_t& nlohmann::detail::primitive_iterator_t::operator++ () inline noexcept
Definition at line 81 of file primitive_iterator.hpp.
     {
         ++m_it;
         return *this;
     }
References m_it.
operator++() [2/4]
primitive_iterator_t& nlohmann::detail::primitive_iterator_t::operator++ () inline noexcept
Definition at line 9235 of file json.hpp.
     {
         ++m_it;
         return *this;
     }
References m_it.
operator++() [3/4]
const primitive_iterator_t nlohmann::detail::primitive_iterator_t::operator++ (int) inline noexcept
Definition at line 87 of file primitive_iterator.hpp.
     {
         auto result = *this;
         ++m_it;
         return result;
     }
References m_it, and result.
operator++() [4/4]
const primitive_iterator_t nlohmann::detail::primitive_iterator_t::operator++ (int) inline noexcept
Definition at line 9241 of file json.hpp.
     {
         auto result = *this;
         ++m_it;
         return result;
     }
References m_it, and result.
operator+=() [1/2]
primitive_iterator_t& nlohmann::detail::primitive_iterator_t::operator+= (difference_type n) inline noexcept
Definition at line 107 of file primitive_iterator.hpp.
     {
         m_it += n;
         return *this;
     }
References m_it, and n.
operator+=() [2/2]
primitive_iterator_t& nlohmann::detail::primitive_iterator_t::operator+= (difference_type n) inline noexcept
Definition at line 9261 of file json.hpp.
     {
         m_it += n;
         return *this;
     }
References m_it, and n.
operator--() [1/4]
primitive_iterator_t& nlohmann::detail::primitive_iterator_t::operator-- () inline noexcept
Definition at line 94 of file primitive_iterator.hpp.
     {
         --m_it;
         return *this;
     }
References m_it.
operator--() [2/4]
primitive_iterator_t& nlohmann::detail::primitive_iterator_t::operator-- () inline noexcept
Definition at line 9248 of file json.hpp.
     {
         --m_it;
         return *this;
     }
References m_it.
operator--() [3/4]
const primitive_iterator_t nlohmann::detail::primitive_iterator_t::operator-- (int) inline noexcept
Definition at line 100 of file primitive_iterator.hpp.
     {
         auto result = *this;
         --m_it;
         return result;
     }
References m_it, and result.
operator--() [4/4]
const primitive_iterator_t nlohmann::detail::primitive_iterator_t::operator-- (int) inline noexcept
Definition at line 9254 of file json.hpp.
     {
         auto result = *this;
         --m_it;
         return result;
     }
References m_it, and result.
operator-=() [1/2]
primitive_iterator_t& nlohmann::detail::primitive_iterator_t::operator-= (difference_type n) inline noexcept
Definition at line 113 of file primitive_iterator.hpp.
     {
         m_it -= n;
         return *this;
     }
References m_it, and n.
operator-=() [2/2]
primitive_iterator_t& nlohmann::detail::primitive_iterator_t::operator-= (difference_type n) inline noexcept
Definition at line 9267 of file json.hpp.
     {
         m_it -= n;
         return *this;
     }
References m_it, and n.
set_begin() [1/2]
void nlohmann::detail::primitive_iterator_t::set_begin () inline noexcept
set iterator to a defined beginning
Definition at line 36 of file primitive_iterator.hpp.
     {
         m_it = begin_value;
     }
References begin_value, and m_it.
Referenced by nlohmann::detail::iter_impl< BasicJsonType >::set_begin().
set_begin() [2/2]
void nlohmann::detail::primitive_iterator_t::set_begin () inline noexcept
set iterator to a defined beginning
Definition at line 9190 of file json.hpp.
     {
         m_it = begin_value;
     }
References begin_value, and m_it.
set_end() [1/2]
void nlohmann::detail::primitive_iterator_t::set_end () inline noexcept
set iterator to a defined past the end
Definition at line 42 of file primitive_iterator.hpp.
     {
         m_it = end_value;
     }
References end_value, and m_it.
Referenced by nlohmann::detail::iter_impl< BasicJsonType >::set_begin(), and nlohmann::detail::iter_impl< BasicJsonType >::set_end().
set_end() [2/2]
void nlohmann::detail::primitive_iterator_t::set_end () inline noexcept
set iterator to a defined past the end
Definition at line 9196 of file json.hpp.
     {
         m_it = end_value;
     }
References end_value, and m_it.
Friends And Related Function Documentation
operator- [1/2]
constexpr friend difference_type operator- (primitive_iterator_t lhs, primitive_iterator_t rhs) friend
Definition at line 76 of file primitive_iterator.hpp.
     {
         return lhs.m_it - rhs.m_it;
     }
operator- [2/2]
constexpr friend difference_type operator- (primitive_iterator_t lhs, primitive_iterator_t rhs) friend
Definition at line 9230 of file json.hpp.
     {
         return lhs.m_it - rhs.m_it;
     }
operator< [1/2]
constexpr friend bool operator< (primitive_iterator_t lhs, primitive_iterator_t rhs) friend
Definition at line 64 of file primitive_iterator.hpp.
     {
         return lhs.m_it < rhs.m_it;
     }
operator< [2/2]
constexpr friend bool operator< (primitive_iterator_t lhs, primitive_iterator_t rhs) friend
Definition at line 9218 of file json.hpp.
     {
         return lhs.m_it < rhs.m_it;
     }
operator== [1/2]
constexpr friend bool operator== (primitive_iterator_t lhs, primitive_iterator_t rhs) friend
Definition at line 59 of file primitive_iterator.hpp.
     {
         return lhs.m_it == rhs.m_it;
     }
operator== [2/2]
constexpr friend bool operator== (primitive_iterator_t lhs, primitive_iterator_t rhs) friend
Definition at line 9213 of file json.hpp.
     {
         return lhs.m_it == rhs.m_it;
     }
Member Data Documentation
begin_value
static constexpr difference_type nlohmann::detail::primitive_iterator_t::begin_value = 0 static constexpr private
Definition at line 23 of file primitive_iterator.hpp.
Referenced by is_begin(), and set_begin().
end_value
static constexpr difference_type nlohmann::detail::primitive_iterator_t::end_value = begin_value + 1 static constexpr private
Definition at line 24 of file primitive_iterator.hpp.
Referenced by is_end(), and set_end().
m_it
difference_type nlohmann::detail::primitive_iterator_t::m_it = (std::numeric_limits<std::ptrdiff_t>::min)() private
iterator as signed integer type
Definition at line 27 of file primitive_iterator.hpp.
Referenced by get_value(), is_begin(), is_end(), operator++(), operator+=(), operator--(), operator-=(), set_begin(), set_end(), and TEST_CASE().
The documentation for this class was generated from the following files:
mc_orchestrator/json-3.7.3/include/nlohmann/detail/iterators/primitive_iterator.hpp
mc_orchestrator/json-3.7.3/single_include/nlohmann/json.hpp