Mixed Criticality Orchestrator: DatabaseHandler Class Reference
DatabaseHandler Class Reference
DatabaseHandler class handles the interaction with the database.
#include <mco_database_handler.hpp>
Public Member Functions
void Init ()
Initialize the database and connect to the database server. If the connection fails, it will try to reconnect 3 times.
bool ClearData ()
Clear all the data in the database.
bool AddData (const std::string &key, const std::string &value)
Add data to the database.
std::string ReadStringData (const std::string &key)
Read string data from the database.
std::list< std::string > ReadListData (const std::string &key)
Read List data from the database.
bool UpdateRunningApps (const std::string &key, const std::unordered_set< std::string > &running_apps)
Update the set of running apps in the database.
bool AddEvents (const std::string &key, const std::string &event)
Add events to the database.
bool DeleteKey (const std::string &key)
Delete the key from the database.
bool SaveData (const std::string &key, const nlohmann::json &data)
Save the JSON file data to the database.
std::string ReadData (const std::string &appName, const std::string &key)
Read the data from the database.
std::string ReadData (const std::string &appType, const std::string &searchKey, const std::string &valueKey)
Read the data from the database.
std::string AppendData (const std::string &appType, const std::string &appCategory, const std::string &appKey, const std::string &path)
Read the data from the database.
bool ModifyValue (const std::string &appName, const std::string &key, const std::string &newValue)
Modify the value of the key in the database.
Static Public Member Functions
static DatabaseHandler & GetInstance ()
Get the singleton instance of the DatabaseHandler class.
Public Attributes
std::unordered_set< std::string > running_apps_
Get the set of all available apps.
std::unordered_set< std::string > qm_infotainment_games_available_
Get the set of all available qm infotainment apps.
std::unordered_set< std::string > qm_infotainment_games_running_apps_
Get the set of running qm infotainment apps.
std::unordered_set< std::string > qm_infotainment_games_stopped_apps_
Get the set of stopped qm infotainment apps.
std::unordered_set< std::string > qm_infotainment_ott_available_
Get the set of all available qm infotainment ott apps.
std::unordered_set< std::string > qm_infotainment_ott_running_apps_
Get the set of running qm infotainment ott apps.
std::unordered_set< std::string > qm_infotainment_ott_stopped_apps_
Get the set of stopped qm infotainment apps.
std::unordered_set< std::string > asil_b_available_
Get the set of all available asil b apps.
std::unordered_set< std::string > asil_b_running_apps_
Get the set of running asil b apps.
std::unordered_set< std::string > asil_b_paused_apps_
Get the set of paused asil b apps.
std::unordered_set< std::string > asil_b_stopped_apps_
Get the set of stopped asil b apps.
std::unordered_set< std::string > priority_high_qm_running_apps_
Get the set of high priority running qm apps.
std::unordered_set< std::string > priority_medium_qm_running_apps_
Get the set of medium priority running qm apps.
std::unordered_set< std::string > priority_low_qm_running_apps_
Get the set of low priority running qm apps.
std::unordered_set< std::string > deleted_apps_
Get the set of all deleted apps.
std::unordered_set< std::string > priority_low_apps_
Get the set of low priority running apps.
std::unordered_set< std::string > priority_medium_apps_
Get the set of medium priority running apps.
std::unordered_set< std::string > priority_high_apps_
Get the set of high priority running apps.
Private Member Functions
void Reconnect ()
Reconnect to the database server.
nlohmann::json ReadData (const std::string &appName)
Read the application value from the database.
bool IsDatabaseAvailable ()
Check if the database server is available.
DatabaseHandler ()
Define the constructor in the private section to make this class a singleton.
~DatabaseHandler ()
Define destructor in private section, so no one can delete the instance of this class.
DatabaseHandler (DatabaseHandler const &)=delete
Define copy constructor in the private section, so that no one can voilate the singleton policy of this class.
void operator= (DatabaseHandler const &)=delete
Define assignment operator in the private section, so that no one can voilate the singleton policy of this class.
Private Attributes
cpp_redis::client client_
database client object to connect to the database server.
Detailed Description
DatabaseHandler class handles the interaction with the database.
Definition at line 12 of file mco_database_handler.hpp.
Constructor & Destructor Documentation
DatabaseHandler() [1/2]
DatabaseHandler::DatabaseHandler () private
Define the constructor in the private section to make this class a singleton.
Definition at line 14 of file mco_database_handler.cpp.
{
     client_.connect();
 }
~DatabaseHandler()
DatabaseHandler::~DatabaseHandler () private
Define destructor in private section, so no one can delete the instance of this class.
Definition at line 18 of file mco_database_handler.cpp.
{
     client_.disconnect();
 }
DatabaseHandler() [2/2]
DatabaseHandler::DatabaseHandler (DatabaseHandler const &) private delete
Define copy constructor in the private section, so that no one can voilate the singleton policy of this class.
Member Function Documentation
AddData()
bool DatabaseHandler::AddData (const std::string & key, const std::string & value)
Add data to the database.
Parameters
key The key as a string.
value The value as a string.
Returns
True if the data is added successfully, false otherwise.
Definition at line 66 of file mco_database_handler.cpp.
{
     if (!IsDatabaseAvailable()) {
         cerr << "Database is not available. Cannot add data." << endl;
         return false;
     }
     client_.set(key, value, [](cpp_redis::reply& reply) {
         if (reply.is_error()) {
             cerr << "Error adding data: " << reply.error() << endl;
             return false;
         }
     });
     client_.sync_commit();
     return true;
 }
Referenced by ResourceMonitorSubject::AverageResourceUtilization(), checkResourceAvailability(), K3sPodUsageCommand::Execute(), PodmanPodUsageCommand::Execute(), BluechiUnitUsageCommand::Execute(), ConfigHandler::GetValue(), AvpTriggerMonitorHandler::Init(), QmOtaHandler::OtaDownloadSuccessful(), UserAppControlHandler::PlayAsilApp(), and update_qm_available_resource().
AddEvents()
bool DatabaseHandler::AddEvents (const std::string & key, const std::string & event)
Add events to the database.
Parameters
key The key as a string.
events The events as a string.
Returns
True if the events are added successfully, false otherwise.
Definition at line 147 of file mco_database_handler.cpp.
{
     if (!IsDatabaseAvailable()) {
         cerr << "Database is not available. Cannot update running apps list." << endl;
         return false;
     }
     // Add the event to the lfo_events list
     client_.rpush("lfo_events", {event});
     // Ensure that all commands are executed before returning
     client_.sync_commit();
     return true;
 }
Referenced by UpdateEvent().
AppendData()
string DatabaseHandler::AppendData (const std::string & appType, const std::string & appCategory, const std::string & appKey, const std::string & path)
Read the data from the database.
Parameters
appName application name as a string.
key application parameter which we are interested
Returns
The value associated with the key as a string.
Definition at line 269 of file mco_database_handler.cpp.
{
     if (!IsDatabaseAvailable()) {
         cerr << "Database is not available. Cannot read data." << endl;
         return "";
     }
     nlohmann::json data;
     client_.get(appName, [&data](cpp_redis::reply& reply){
         if(reply.is_null()) {
             std::cerr << "Key not found" << std::endl;
         } else if(reply.is_error()) {
             std::cerr << "Error reading data: " << reply.error() << std::endl;
         } else {
             data = nlohmann::json::parse(reply.as_string());
         }
     });
     client_.sync_commit();  // Ensure that all commands are executed before returning
     // Ensure appCategory appKey array exist in the data
     if (!data.contains(appCategory)) {
         data[appCategory] = json::object();
     }
     if (!data[appCategory].contains(appKey)) {
         data[appCategory][appKey] = json::array();
     }
     // Iterate through the .json files in the specified directory
     for (const auto& entry : std::filesystem::directory_iterator(path)) {
         if (entry.path().extension() == ".json") {
             std::ifstream file(entry.path());
             if (!file.is_open()) {
                 std::cerr << "Could not open file: " << entry.path() << std::endl;
                 continue;
             }
             json file_data;
             try {
                 file >> file_data;
             } catch (const json::parse_error& e) {
                 std::cerr << "JSON parse error in file " << entry.path() << ": " << e.what() << std::endl;
                 continue;
             }
             // Append the content of each .json file to the appKey array
             for (auto& [key, value] : file_data.items()) {
                 json new_entry;
                 // Check if the key is not already present in data[appCategory][appKey]
                 bool key_exists = false;
                 for (const auto& item : data[appCategory][appKey]) {
                     if (item.contains(key)) {
                         key_exists = true;
                         break;
                     }
                 }
                 if (!key_exists) {
                     new_entry[key] = value;
                     data[appCategory][appKey].push_back(new_entry);
                     // SaveData(key, value);
                 } else {
                     std::cout << "Key " << key << " already exists in data[" << appCategory << "][" << appKey << "]" << std::endl;
                 }
             }
         }
     }
     // Update the key in the Redis database with the new content
     client_.set(appName, data.dump());
     client_.sync_commit();  // Ensure that all commands are executed before returning
     return data.dump();
 }
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::array(), client_, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::contains(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::dump(), IsDatabaseAvailable(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::items(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::object(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::push_back(), and nlohmann::detail::exception::what().
Referenced by QmOtaHandler::OtaDownloadSuccessful(), and ConfigHandler::UpdateDatabase().
ClearData()
bool DatabaseHandler::ClearData ()
Clear all the data in the database.
Returns
True if the data is cleared successfully, false otherwise.
Definition at line 44 of file mco_database_handler.cpp.
{
     if (!IsDatabaseAvailable()) {
         cerr << "Database is not available. Cannot clear data." << endl;
         return false;
     }
     client_.flushdb();
     client_.sync_commit();
     return true;
 }
Referenced by main().
DeleteKey()
bool DatabaseHandler::DeleteKey (const std::string & key)
Delete the key from the database.
Definition at line 161 of file mco_database_handler.cpp.
{
     if (!IsDatabaseAvailable()) {
         cerr << "Database is not available. Cannot clear data." << endl;
         return false;
     }
     auto delete_future = client_.del({key});
     client_.sync_commit();
     auto num_deleted = delete_future.get().as_integer();
     if (num_deleted == 0) {
         return false;
     } else {
         return true;
     }
 }
Referenced by ServerHandler::StartMcOrchestratorServer().
GetInstance()
DatabaseHandler & DatabaseHandler::GetInstance () static
Get the singleton instance of the DatabaseHandler class.
Returns
The singleton instance.
Definition at line 9 of file mco_database_handler.cpp.
{
     static DatabaseHandler instance;
     return instance;
 }
Referenced by ResourceMonitorSubject::AverageResourceUtilization(), checkResourceAvailability(), DeletePodObserver::DeleteAllPods(), K3sStarvePodCommand::Execute(), PodmanGetPodNameCommand::Execute(), BluechiGetUnitNameCommand::Execute(), K3sGetPodNameCommand::Execute(), K3sApplyPodCommand::Execute(), PodmanApplyPodCommand::Execute(), BluechiStartAsilUnitCommand::Execute(), K3sDeletePodCommand::Execute(), PodmanDeletePodCommand::Execute(), BluechiStopAsilUnitCommand::Execute(), PodmanCheckPodStatusCommand::Execute(), K3sCheckPodStatusCommand::Execute(), BluechiStartQmUnitCommand::Execute(), PodmanPodUsageCommand::Execute(), BluechiStopQmUnitCommand::Execute(), K3sPodUsageCommand::Execute(), BluechiCheckUnitStatusCommand::Execute(), BluechiUnitUsageCommand::Execute(), ConfigHandler::GetValue(), AvpTriggerMonitorHandler::Init(), ResourceMonitorHandler::Init(), UserAppControlHandler::Init(), main(), QmOtaHandler::OtaDownloadSuccessful(), UserAppControlHandler::PlayAsilApp(), UserAppControlHandler::PlayQmApp(), RespawnPodObserver::RespawnAllPods(), ConfigHandler::SaveAppNameToDatabase(), ConfigHandler::SaveFileContentToDatabase(), ServerHandler::StartMcOrchestratorServer(), UserAppControlHandler::StopAsilApp(), UserAppControlHandler::StopQmApp(), update_qm_available_resource(), ConfigHandler::UpdateDatabase(), UpdateEvent(), updateInitialSystemResources(), and updateResources().
Init()
void DatabaseHandler::Init ()
Initialize the database and connect to the database server. If the connection fails, it will try to reconnect 3 times.
Definition at line 54 of file mco_database_handler.cpp.
{
     for (int i = 0; i < 3; ++i) {
         if (IsDatabaseAvailable()) {
             return;
         }
         cerr << "Database is not available. Attempting to reconnect (" << i + 1 << "/3)..." << endl;
         Reconnect();
         this_thread::sleep_for(chrono::seconds(3));
     }
     cerr << "Failed to connect to Database after 3 attempts." << endl;
 }
Referenced by main().
IsDatabaseAvailable()
bool DatabaseHandler::IsDatabaseAvailable () private
Check if the database server is available.
Returns
True if the database server is available, false otherwise.
Definition at line 27 of file mco_database_handler.cpp.
{
     bool isAvailable = false;
     client_.ping([&isAvailable](cpp_redis::reply& reply) {
         isAvailable = !reply.is_error();
     });
     client_.sync_commit();
     if (!isAvailable) {
         Reconnect();
         // Recheck after reconnecting
         client_.ping([&isAvailable](cpp_redis::reply& reply) {
             isAvailable = !reply.is_error();
         });
         client_.sync_commit();
     }
     return isAvailable;
 }
Referenced by AppendData(), and ReadData().
ModifyValue()
bool DatabaseHandler::ModifyValue (const std::string & appName, const std::string & key, const std::string & newValue)
Modify the value of the key in the database.
Parameters
appName application name as a string.
key application parameter which we are interested
newValue new value to be updated for the key
Definition at line 364 of file mco_database_handler.cpp.
{
     // Reading the current JSON data
     json data = ReadData(appName);
     // Parse the JSON data and modify the key value
     for (auto& element : data) {
         if (element.find(key) != element.end()) {
             element[key] = newValue;
             break;
         }
     }
     // Save the modified data back to the database
     SaveData(appName, data);
     return true;
 }
References ReadData(), and SaveData().
Referenced by K3sStarvePodCommand::Execute(), K3sGetPodNameCommand::Execute(), PodmanGetPodNameCommand::Execute(), BluechiGetUnitNameCommand::Execute(), PodmanDeletePodCommand::Execute(), K3sDeletePodCommand::Execute(), K3sCheckPodStatusCommand::Execute(), PodmanCheckPodStatusCommand::Execute(), and BluechiCheckUnitStatusCommand::Execute().
operator=()
void DatabaseHandler::operator= (DatabaseHandler const &) private delete
Define assignment operator in the private section, so that no one can voilate the singleton policy of this class.
ReadData() [1/3]
json DatabaseHandler::ReadData (const std::string & appName) private
Read the application value from the database.
Parameters
appName application name as a string.
Returns
The value associated with the key as JSON.
Definition at line 343 of file mco_database_handler.cpp.
{
     if (!IsDatabaseAvailable()) {
         cerr << "Database is not available. Cannot read data." << endl;
         return "";
     }
     nlohmann::json data;
     client_.get(key, [&data](cpp_redis::reply& reply){
         if(reply.is_null()) {
             std::cerr << "Key not found" << std::endl;
         } else if(reply.is_error()) {
             std::cerr << "Error reading data: " << reply.error() << std::endl;
         } else {
             data = nlohmann::json::parse(reply.as_string());
         }
     });
     client_.sync_commit();  // Ensure that all commands are executed before returning
     return data;
 }
References client_, and IsDatabaseAvailable().
ReadData() [2/3]
string DatabaseHandler::ReadData (const std::string & appName, const std::string & key)
Read the data from the database.
Parameters
appName application name as a string.
key application parameter which we are interested
Returns
The value associated with the key as a string.
Definition at line 190 of file mco_database_handler.cpp.
{
     if (!IsDatabaseAvailable()) {
         cerr << "Database is not available. Cannot read data." << endl;
         return "";
     }
     nlohmann::json data;
     client_.get(appName, [&data](cpp_redis::reply& reply){
         if(reply.is_null()) {
             std::cerr << "Key not found" << std::endl;
         } else if(reply.is_error()) {
             std::cerr << "Error reading data: " << reply.error() << std::endl;
         } else {
             data = nlohmann::json::parse(reply.as_string());
         }
     });
     client_.sync_commit();  // Ensure that all commands are executed before returning
     std::string value = "";
     // for (auto& element : data) {    // Extract the field value from the JSON data
     //     if (element.find(field) != element.end()) {
     //         value = element[field];
     //         break;
     //     }
     // }
     if (data.contains(field)) {
         value = data[field].get<std::string>();
     } else {
         std::cerr << "Field '" << field << "' not found in JSON." << std::endl;
     }
     return value;
 }
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::contains(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get().
Referenced by K3sStarvePodCommand::Execute(), PodmanApplyPodCommand::Execute(), BluechiStartAsilUnitCommand::Execute(), K3sApplyPodCommand::Execute(), K3sDeletePodCommand::Execute(), PodmanDeletePodCommand::Execute(), BluechiStartQmUnitCommand::Execute(), PodmanPodUsageCommand::Execute(), K3sPodUsageCommand::Execute(), BluechiStopQmUnitCommand::Execute(), ModifyValue(), and ServerHandler::StartMcOrchestratorServer().
ReadData() [3/3]
string DatabaseHandler::ReadData (const std::string & appType, const std::string & searchKey, const std::string & valueKey)
Read the data from the database.
Parameters
appType application type as a string
searchKey application which we are interested
valuekey application parameter which we are interested
Returns
The value associated with the valuekey as a string.
Definition at line 224 of file mco_database_handler.cpp.
{
     if (!IsDatabaseAvailable()) {
         std::cerr << "Database is not available. Cannot read data." << std::endl;
         return "";
     }
     nlohmann::json data;
     // Fetch JSON data from Redis
     client_.get(appType, [&data](cpp_redis::reply& reply) {
         if (reply.is_null()) {
             std::cerr << "Key not found in Redis" << std::endl;
         } else if (reply.is_error()) {
             std::cerr << "Error reading data from Redis: " << reply.error() << std::endl;
         } else {
             try {
                 data = json::parse(reply.as_string());
             } catch (const json::parse_error& e) {
                 std::cerr << "JSON parse error from Redis: " << e.what() << std::endl;
             }
         }
     });
     client_.sync_commit();
     // Search for the "downloaded" key in any section of the JSON
     for (auto& [category, value] : data.items()) {
         if (value.contains("downloaded") && value["downloaded"].is_array()) {
             // Iterate through the "downloaded" array
             for (const auto& app : value["downloaded"]) {
                 if (app.contains(searchKey) && app[searchKey].is_array()) {
                     for (const auto& obj : app[searchKey]) {
                         if (obj.contains(valueKey)) {
                             if (obj[valueKey].is_object()) {
                                 return obj[valueKey].dump(); // Convert JSON object to string
                             } else if (obj[valueKey].is_string()) {
                                 return obj[valueKey].get<std::string>(); // Return as string
                             }
                         }
                     }
                 }
             }
         }
     }
 }
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get(), if(), and nlohmann::detail::exception::what().
ReadListData()
list< string > DatabaseHandler::ReadListData (const std::string & key)
Read List data from the database.
Parameters
key The key as a string.
Returns
List of strings associated with the key.
Definition at line 100 of file mco_database_handler.cpp.
{
     if (!IsDatabaseAvailable()) {
         cerr << "Database is not available. Cannot read data." << endl;
         return list<string>();
     }
     list<string> value_list;
     client_.lrange(key, 0, -1, [&value_list](cpp_redis::reply& reply) {
         if (reply.is_null()) {
             std::cerr << "Key not found" << std::endl;
         } else if (reply.is_error()) {
             std::cerr << "Error reading data: " << reply.error() << std::endl;
         } else if (reply.is_array()) {
             for (const auto& element : reply.as_array()) {
                 if (element.is_string()) {
                     value_list.push_back(element.as_string());
                 }
             }
         }
     });
     client_.sync_commit();
     return value_list;
 }
References if().
Referenced by DeletePodObserver::DeleteAllPods(), ConfigHandler::GetValue(), ResourceMonitorHandler::Init(), AvpTriggerMonitorHandler::Init(), UserAppControlHandler::Init(), UserAppControlHandler::PlayAsilApp(), RespawnPodObserver::RespawnAllPods(), ServerHandler::StartMcOrchestratorServer(), and update_qm_available_resource().
ReadStringData()
string DatabaseHandler::ReadStringData (const std::string & key)
Read string data from the database.
Parameters
key The key as a string.
Returns
The value associated with the key as a string.
Definition at line 81 of file mco_database_handler.cpp.
{
     if (!IsDatabaseAvailable()) {
         cerr << "Database is not available. Cannot read data." << endl;
         return "";
     }
     string value;
     client_.get(key, [&value](cpp_redis::reply& reply) {
         if (reply.is_null()) {
             // cerr << "Key not found" << endl;
         } else if (reply.is_error()) {
             cerr << "Error reading data: " << reply.error() << endl;
         } else {
             value = reply.as_string();
         }
     });
     client_.sync_commit();
     return value;
 }
References if().
Referenced by UserAppControlHandler::Init(), QmOtaHandler::OtaDownloadSuccessful(), and ServerHandler::StartMcOrchestratorServer().
Reconnect()
void DatabaseHandler::Reconnect () private
Reconnect to the database server.
Definition at line 22 of file mco_database_handler.cpp.
{
     client_.disconnect();
     client_.connect();
 }
SaveData()
bool DatabaseHandler::SaveData (const std::string & key, const nlohmann::json & data)
Save the JSON file data to the database.
Parameters
key app name
data JSON value in the form of nlohmann::json
Returns
true if the data is saved successfully, false otherwise.
Definition at line 178 of file mco_database_handler.cpp.
{
     if (!IsDatabaseAvailable()) {
         cerr << "Database is not available. Cannot save data." << endl;
         return false;
     }
     // Convert the JSON data to a string
     string data_str = data.dump();
     client_.set(key, data_str);
     client_.sync_commit();
     return true;
 }
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::dump().
Referenced by BluechiUnitUsageCommand::Execute(), UserAppControlHandler::Init(), ModifyValue(), UserAppControlHandler::PlayAsilApp(), UserAppControlHandler::PlayQmApp(), ConfigHandler::SaveFileContentToDatabase(), UserAppControlHandler::StopAsilApp(), UserAppControlHandler::StopQmApp(), update_qm_available_resource(), ConfigHandler::UpdateDatabase(), updateInitialSystemResources(), and updateResources().
UpdateRunningApps()
bool DatabaseHandler::UpdateRunningApps (const std::string & key, const std::unordered_set< std::string > & running_apps)
Update the set of running apps in the database.
Definition at line 124 of file mco_database_handler.cpp.
{
     if (!IsDatabaseAvailable()) {
         cerr << "Database is not available. Cannot update running apps list." << endl;
         return false;
     }
     // Wrap the key in a vector
     vector<string> keys = {key};
     // Delete the existing list in database
     client_.del(keys);
     // Convert the list to a vector
     vector<string> apps(running_apps.begin(), running_apps.end());
     // Add the apps to the database list
     client_.rpush(key, apps);
     // Ensure that all commands are executed before returning
     client_.sync_commit();
     return true;
 }
Referenced by BluechiStartAsilUnitCommand::Execute(), PodmanApplyPodCommand::Execute(), K3sApplyPodCommand::Execute(), K3sDeletePodCommand::Execute(), PodmanDeletePodCommand::Execute(), BluechiStopAsilUnitCommand::Execute(), BluechiStartQmUnitCommand::Execute(), BluechiStopQmUnitCommand::Execute(), and ConfigHandler::SaveAppNameToDatabase().
Member Data Documentation
asil_b_available_
std::unordered_set<std::string> DatabaseHandler::asil_b_available_
Get the set of all available asil b apps.
Definition at line 40 of file mco_database_handler.hpp.
asil_b_paused_apps_
std::unordered_set<std::string> DatabaseHandler::asil_b_paused_apps_
Get the set of paused asil b apps.
Definition at line 46 of file mco_database_handler.hpp.
asil_b_running_apps_
std::unordered_set<std::string> DatabaseHandler::asil_b_running_apps_
Get the set of running asil b apps.
Definition at line 43 of file mco_database_handler.hpp.
Referenced by BluechiStartAsilUnitCommand::Execute(), and BluechiStopAsilUnitCommand::Execute().
asil_b_stopped_apps_
std::unordered_set<std::string> DatabaseHandler::asil_b_stopped_apps_
Get the set of stopped asil b apps.
Definition at line 49 of file mco_database_handler.hpp.
Referenced by BluechiStartAsilUnitCommand::Execute(), and BluechiStopAsilUnitCommand::Execute().
client_
cpp_redis::client DatabaseHandler::client_ private
database client object to connect to the database server.
Definition at line 165 of file mco_database_handler.hpp.
Referenced by AppendData(), and ReadData().
deleted_apps_
std::unordered_set<std::string> DatabaseHandler::deleted_apps_
Get the set of all deleted apps.
Definition at line 61 of file mco_database_handler.hpp.
Referenced by K3sApplyPodCommand::Execute(), PodmanApplyPodCommand::Execute(), PodmanDeletePodCommand::Execute(), and K3sDeletePodCommand::Execute().
priority_high_apps_
std::unordered_set<std::string> DatabaseHandler::priority_high_apps_
Get the set of high priority running apps.
Definition at line 70 of file mco_database_handler.hpp.
Referenced by K3sApplyPodCommand::Execute(), PodmanApplyPodCommand::Execute(), PodmanDeletePodCommand::Execute(), and K3sDeletePodCommand::Execute().
priority_high_qm_running_apps_
std::unordered_set<std::string> DatabaseHandler::priority_high_qm_running_apps_
Get the set of high priority running qm apps.
Definition at line 52 of file mco_database_handler.hpp.
Referenced by BluechiStartQmUnitCommand::Execute(), and BluechiStopQmUnitCommand::Execute().
priority_low_apps_
std::unordered_set<std::string> DatabaseHandler::priority_low_apps_
Get the set of low priority running apps.
Definition at line 64 of file mco_database_handler.hpp.
Referenced by K3sApplyPodCommand::Execute(), PodmanApplyPodCommand::Execute(), PodmanDeletePodCommand::Execute(), and K3sDeletePodCommand::Execute().
priority_low_qm_running_apps_
std::unordered_set<std::string> DatabaseHandler::priority_low_qm_running_apps_
Get the set of low priority running qm apps.
Definition at line 58 of file mco_database_handler.hpp.
Referenced by BluechiStartQmUnitCommand::Execute(), and BluechiStopQmUnitCommand::Execute().
priority_medium_apps_
std::unordered_set<std::string> DatabaseHandler::priority_medium_apps_
Get the set of medium priority running apps.
Definition at line 67 of file mco_database_handler.hpp.
Referenced by K3sApplyPodCommand::Execute(), PodmanApplyPodCommand::Execute(), PodmanDeletePodCommand::Execute(), and K3sDeletePodCommand::Execute().
priority_medium_qm_running_apps_
std::unordered_set<std::string> DatabaseHandler::priority_medium_qm_running_apps_
Get the set of medium priority running qm apps.
Definition at line 55 of file mco_database_handler.hpp.
Referenced by BluechiStartQmUnitCommand::Execute(), and BluechiStopQmUnitCommand::Execute().
qm_infotainment_games_available_
std::unordered_set<std::string> DatabaseHandler::qm_infotainment_games_available_
Get the set of all available qm infotainment apps.
Definition at line 22 of file mco_database_handler.hpp.
qm_infotainment_games_running_apps_
std::unordered_set<std::string> DatabaseHandler::qm_infotainment_games_running_apps_
Get the set of running qm infotainment apps.
Definition at line 25 of file mco_database_handler.hpp.
Referenced by BluechiStartQmUnitCommand::Execute(), and BluechiStopQmUnitCommand::Execute().
qm_infotainment_games_stopped_apps_
std::unordered_set<std::string> DatabaseHandler::qm_infotainment_games_stopped_apps_
Get the set of stopped qm infotainment apps.
Definition at line 28 of file mco_database_handler.hpp.
Referenced by BluechiStartQmUnitCommand::Execute(), and BluechiStopQmUnitCommand::Execute().
qm_infotainment_ott_available_
std::unordered_set<std::string> DatabaseHandler::qm_infotainment_ott_available_
Get the set of all available qm infotainment ott apps.
Definition at line 31 of file mco_database_handler.hpp.
qm_infotainment_ott_running_apps_
std::unordered_set<std::string> DatabaseHandler::qm_infotainment_ott_running_apps_
Get the set of running qm infotainment ott apps.
Definition at line 34 of file mco_database_handler.hpp.
Referenced by BluechiStartQmUnitCommand::Execute(), and BluechiStopQmUnitCommand::Execute().
qm_infotainment_ott_stopped_apps_
std::unordered_set<std::string> DatabaseHandler::qm_infotainment_ott_stopped_apps_
Get the set of stopped qm infotainment apps.
Definition at line 37 of file mco_database_handler.hpp.
Referenced by BluechiStartQmUnitCommand::Execute(), and BluechiStopQmUnitCommand::Execute().
running_apps_
std::unordered_set<std::string> DatabaseHandler::running_apps_
Get the set of all available apps.
Definition at line 19 of file mco_database_handler.hpp.
Referenced by K3sApplyPodCommand::Execute(), PodmanApplyPodCommand::Execute(), PodmanDeletePodCommand::Execute(), K3sDeletePodCommand::Execute(), and ConfigHandler::SaveAppNameToDatabase().
The documentation for this class was generated from the following files:
mc_orchestrator/common/inc/mco_database_handler.hpp
mc_orchestrator/common/src/mco_database_handler.cpp