Mixed Criticality Orchestrator: nlohmann::detail::wide_string_input_adapter< WideStringType > Class Template Reference
nlohmann::detail::wide_string_input_adapter< WideStringType > Class Template Reference
#include <input_adapters.hpp>
Public Member Functions
wide_string_input_adapter (const WideStringType &w) noexcept
std::char_traits< char >::int_type get_character () noexcept override
get a character [0,255] or std::char_traits<char>::eof().
wide_string_input_adapter (const WideStringType &w) noexcept
std::char_traits< char >::int_type get_character () noexcept override
get a character [0,255] or std::char_traits<char>::eof().
Public Member Functions inherited from nlohmann::detail::input_adapter_protocol
virtual ~input_adapter_protocol ()=default
virtual ~input_adapter_protocol ()=default
Private Member Functions
template<size_t T>
void fill_buffer ()
template<size_t T>
void fill_buffer ()
Private Attributes
const WideStringType & str
the wstring to process
std::size_t current_wchar = 0
index of the current wchar in str
std::array< std::char_traits< char >::int_type, 4 > utf8_bytes = {{0, 0, 0, 0}}
a buffer for UTF-8 bytes
std::size_t utf8_bytes_index = 0
index to the utf8_codes array for the next valid byte
std::size_t utf8_bytes_filled = 0
number of valid bytes in the utf8_codes array
Detailed Description
template<typename WideStringType>
class nlohmann::detail::wide_string_input_adapter< WideStringType >
Definition at line 288 of file input_adapters.hpp.
Constructor & Destructor Documentation
wide_string_input_adapter() [1/2]
template<typename WideStringType > nlohmann::detail::wide_string_input_adapter< WideStringType >::wide_string_input_adapter (const WideStringType & w) inline explicit noexcept
Definition at line 291 of file input_adapters.hpp.
         : str(w)
     {}
wide_string_input_adapter() [2/2]
template<typename WideStringType > nlohmann::detail::wide_string_input_adapter< WideStringType >::wide_string_input_adapter (const WideStringType & w) inline explicit noexcept
Definition at line 4154 of file json.hpp.
         : str(w)
     {}
Member Function Documentation
fill_buffer() [1/2]
template<typename WideStringType > template<size_t T> void nlohmann::detail::wide_string_input_adapter< WideStringType >::fill_buffer () inline private
Definition at line 314 of file input_adapters.hpp.
     {
         wide_string_input_helper<WideStringType, T>::fill_buffer(str, current_wchar, utf8_bytes, utf8_bytes_index, utf8_bytes_filled);
     }
References nlohmann::detail::wide_string_input_adapter< WideStringType >::current_wchar, nlohmann::detail::wide_string_input_helper< WideStringType, T >::fill_buffer(), nlohmann::detail::wide_string_input_adapter< WideStringType >::str, nlohmann::detail::wide_string_input_adapter< WideStringType >::utf8_bytes, nlohmann::detail::wide_string_input_adapter< WideStringType >::utf8_bytes_filled, and nlohmann::detail::wide_string_input_adapter< WideStringType >::utf8_bytes_index.
fill_buffer() [2/2]
template<typename WideStringType > template<size_t T> void nlohmann::detail::wide_string_input_adapter< WideStringType >::fill_buffer () inline private
Definition at line 4177 of file json.hpp.
     {
         wide_string_input_helper<WideStringType, T>::fill_buffer(str, current_wchar, utf8_bytes, utf8_bytes_index, utf8_bytes_filled);
     }
References nlohmann::detail::wide_string_input_adapter< WideStringType >::current_wchar, nlohmann::detail::wide_string_input_helper< WideStringType, T >::fill_buffer(), nlohmann::detail::wide_string_input_adapter< WideStringType >::str, nlohmann::detail::wide_string_input_adapter< WideStringType >::utf8_bytes, nlohmann::detail::wide_string_input_adapter< WideStringType >::utf8_bytes_filled, and nlohmann::detail::wide_string_input_adapter< WideStringType >::utf8_bytes_index.
get_character() [1/2]
template<typename WideStringType > std::char_traits<char>::int_type nlohmann::detail::wide_string_input_adapter< WideStringType >::get_character () inline override virtual noexcept
get a character [0,255] or std::char_traits<char>::eof().
Implements nlohmann::detail::input_adapter_protocol.
Definition at line 295 of file input_adapters.hpp.
     {
         // check if buffer needs to be filled
         if (utf8_bytes_index == utf8_bytes_filled)
         {
             fill_buffer<sizeof(typename WideStringType::value_type)>();
             assert(utf8_bytes_filled > 0);
             assert(utf8_bytes_index == 0);
         }
         // use buffer
         assert(utf8_bytes_filled > 0);
         assert(utf8_bytes_index < utf8_bytes_filled);
         return utf8_bytes[utf8_bytes_index++];
     }
References assert(), nlohmann::detail::wide_string_input_adapter< WideStringType >::utf8_bytes, nlohmann::detail::wide_string_input_adapter< WideStringType >::utf8_bytes_filled, and nlohmann::detail::wide_string_input_adapter< WideStringType >::utf8_bytes_index.
get_character() [2/2]
template<typename WideStringType > std::char_traits<char>::int_type nlohmann::detail::wide_string_input_adapter< WideStringType >::get_character () inline override virtual noexcept
get a character [0,255] or std::char_traits<char>::eof().
Implements nlohmann::detail::input_adapter_protocol.
Definition at line 4158 of file json.hpp.
     {
         // check if buffer needs to be filled
         if (utf8_bytes_index == utf8_bytes_filled)
         {
             fill_buffer<sizeof(typename WideStringType::value_type)>();
             assert(utf8_bytes_filled > 0);
             assert(utf8_bytes_index == 0);
         }
         // use buffer
         assert(utf8_bytes_filled > 0);
         assert(utf8_bytes_index < utf8_bytes_filled);
         return utf8_bytes[utf8_bytes_index++];
     }
References assert(), nlohmann::detail::wide_string_input_adapter< WideStringType >::utf8_bytes, nlohmann::detail::wide_string_input_adapter< WideStringType >::utf8_bytes_filled, and nlohmann::detail::wide_string_input_adapter< WideStringType >::utf8_bytes_index.
Member Data Documentation
current_wchar
template<typename WideStringType > std::size_t nlohmann::detail::wide_string_input_adapter< WideStringType >::current_wchar = 0 private
index of the current wchar in str
Definition at line 323 of file input_adapters.hpp.
Referenced by nlohmann::detail::wide_string_input_adapter< WideStringType >::fill_buffer().
str
template<typename WideStringType > const WideStringType & nlohmann::detail::wide_string_input_adapter< WideStringType >::str private
the wstring to process
Definition at line 320 of file input_adapters.hpp.
Referenced by nlohmann::detail::wide_string_input_adapter< WideStringType >::fill_buffer().
utf8_bytes
template<typename WideStringType > std::array< std::char_traits< char >::int_type, 4 > nlohmann::detail::wide_string_input_adapter< WideStringType >::utf8_bytes = {{0, 0, 0, 0}} private
a buffer for UTF-8 bytes
Definition at line 326 of file input_adapters.hpp.
Referenced by nlohmann::detail::wide_string_input_adapter< WideStringType >::fill_buffer(), and nlohmann::detail::wide_string_input_adapter< WideStringType >::get_character().
utf8_bytes_filled
template<typename WideStringType > std::size_t nlohmann::detail::wide_string_input_adapter< WideStringType >::utf8_bytes_filled = 0 private
number of valid bytes in the utf8_codes array
Definition at line 331 of file input_adapters.hpp.
Referenced by nlohmann::detail::wide_string_input_adapter< WideStringType >::fill_buffer(), and nlohmann::detail::wide_string_input_adapter< WideStringType >::get_character().
utf8_bytes_index
template<typename WideStringType > std::size_t nlohmann::detail::wide_string_input_adapter< WideStringType >::utf8_bytes_index = 0 private
index to the utf8_codes array for the next valid byte
Definition at line 329 of file input_adapters.hpp.
Referenced by nlohmann::detail::wide_string_input_adapter< WideStringType >::fill_buffer(), and nlohmann::detail::wide_string_input_adapter< WideStringType >::get_character().
The documentation for this class was generated from the following files:
mc_orchestrator/json-3.7.3/include/nlohmann/detail/input/input_adapters.hpp
mc_orchestrator/json-3.7.3/single_include/nlohmann/json.hpp