Mixed Criticality Orchestrator: fuzzer::Random Class Reference
fuzzer::Random Class Reference
#include <FuzzerRandom.h>
Public Member Functions
Random (unsigned int seed)
size_t Rand ()
size_t RandBool ()
size_t operator() (size_t n)
intptr_t operator() (intptr_t From, intptr_t To)
std::mt19937 & Get_mt19937 ()
Private Attributes
std::mt19937 R
Detailed Description
Definition at line 18 of file FuzzerRandom.h.
Constructor & Destructor Documentation
Random()
fuzzer::Random::Random (unsigned int seed) inline
Definition at line 20 of file FuzzerRandom.h.
 : R(seed) {}
Member Function Documentation
Get_mt19937()
std::mt19937& fuzzer::Random::Get_mt19937 () inline
Definition at line 29 of file FuzzerRandom.h.
 { return R; }
References R.
Referenced by fuzzer::InputCorpus::ChooseUnitIdxToMutate().
operator()() [1/2]
intptr_t fuzzer::Random::operator() (intptr_t From, intptr_t To) inline
Definition at line 24 of file FuzzerRandom.h.
{
     assert(From < To);
     intptr_t RangeSize = To - From + 1;
     return operator()(RangeSize) + From;
   }
References assert(), and operator()().
operator()() [2/2]
size_t fuzzer::Random::operator() (size_t n) inline
Definition at line 23 of file FuzzerRandom.h.
 { return n ? Rand() % n : 0; }
References n, and Rand().
Referenced by operator()().
Rand()
size_t fuzzer::Random::Rand () inline
Definition at line 21 of file FuzzerRandom.h.
 { return R(); }
References R.
Referenced by operator()(), and RandBool().
RandBool()
size_t fuzzer::Random::RandBool () inline
Definition at line 22 of file FuzzerRandom.h.
 { return Rand() % 2; }
References Rand().
Referenced by fuzzer::ChangeBinaryInteger(), and fuzzer::RandCh().
Member Data Documentation
R
std::mt19937 fuzzer::Random::R private
Definition at line 31 of file FuzzerRandom.h.
Referenced by Get_mt19937(), and Rand().
The documentation for this class was generated from the following file:
mc_orchestrator/json-3.7.3/test/thirdparty/Fuzzer/FuzzerRandom.h