Mixed Criticality Orchestrator: mc_orchestrator/json-3.7.3/test/thirdparty/Fuzzer/test/DSOTestMain.cpp File Reference
DSOTestMain.cpp File Reference
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <cstdio>
Functions
int DSO1 (int a)
int DSO2 (int a)
int DSOTestExtra (int a)
int LLVMFuzzerTestOneInput (const uint8_t *Data, size_t Size)
Variables
static volatile int * nil = 0
Function Documentation
DSO1()
int DSO1 (int a)
Definition at line 6 of file DSO1.cpp.
                 {
   if (a < 123456)
     return 0;
   return 1;
 }
Referenced by LLVMFuzzerTestOneInput().
DSO2()
int DSO2 (int a)
Definition at line 6 of file DSO2.cpp.
                 {
   if (a < 3598235)
     return 0;
   return 1;
 }
Referenced by LLVMFuzzerTestOneInput().
DSOTestExtra()
int DSOTestExtra (int a)
Definition at line 6 of file DSOTestExtra.cpp.
{
   if (a < 452345)
     return 0;
   return 1;
 }
Referenced by LLVMFuzzerTestOneInput().
LLVMFuzzerTestOneInput()
int LLVMFuzzerTestOneInput (const uint8_t * Data, size_t Size)
Definition at line 16 of file DSOTestMain.cpp.
{
   int x, y, z;
   if (Size < sizeof(int) * 3) {
     x = y = z = 0;
   } else {
     memcpy(&x, Data + 0 * sizeof(int), sizeof(int));
     memcpy(&y, Data + 1 * sizeof(int), sizeof(int));
     memcpy(&z, Data + 2 * sizeof(int), sizeof(int));
   }
   int sum = DSO1(x) + DSO2(y) + (z ? DSOTestExtra(z) : 0);
   if (sum == 3) {
     fprintf(stderr, "BINGO %d %d %d\n", x, y, z);
     *nil = 0;
   }
   return 0;
 }
References DSO1(), DSO2(), DSOTestExtra(), and nil.
Variable Documentation
nil
volatile int* nil = 0 static
Definition at line 14 of file DSOTestMain.cpp.
Referenced by LLVMFuzzerTestOneInput().