Mixed Criticality Orchestrator: mc_orchestrator/json-3.7.3/test/thirdparty/fifo_map/fifo_map.hpp File Reference
fifo_map.hpp File Reference
#include <algorithm>
#include <cstdlib>
#include <functional>
#include <iostream>
#include <limits>
#include <map>
#include <memory>
#include <unordered_map>
#include <utility>
#include <vector>
Classes
class nlohmann::fifo_map_compare< Key >
class nlohmann::fifo_map< Key, T, Compare, Allocator >
Namespaces
nlohmann
namespace for Niels Lohmann
Functions
template<class Key , class T , class Compare , class Allocator >
void std::swap (nlohmann::fifo_map< Key, T, Compare, Allocator > &m1, nlohmann::fifo_map< Key, T, Compare, Allocator > &m2)
Function Documentation
swap()
template<class Key , class T , class Compare , class Allocator > void std::swap (nlohmann::fifo_map< Key, T, Compare, Allocator > & m1, nlohmann::fifo_map< Key, T, Compare, Allocator > & m2) inline
Definition at line 523 of file fifo_map.hpp.
 {
     m1.swap(m2);
 }
References nlohmann::fifo_map< Key, T, Compare, Allocator >::swap(), and std::swap().
Referenced by std::swap().