Mixed Criticality Orchestrator: mc_orchestrator/json-3.7.3/test/thirdparty/Fuzzer/FuzzerMain.cpp File Reference
FuzzerMain.cpp File Reference
#include "FuzzerDefs.h"
Functions
int LLVMFuzzerTestOneInput (const uint8_t *Data, size_t Size)
int main (int argc, char **argv)
Function Documentation
LLVMFuzzerTestOneInput()
int LLVMFuzzerTestOneInput (const uint8_t * Data, size_t Size)
Definition at line 28 of file fuzzer-parse_bson.cpp.
 {
     try
     {
         // step 1: parse input
         std::vector<uint8_t> vec1(data, data + size);
         json j1 = json::from_bson(vec1);
         if (j1.is_discarded())
         {
             return 0;
         }
         try
         {
             // step 2: round trip
             std::vector<uint8_t> vec2 = json::to_bson(j1);
             // parse serialization
             json j2 = json::from_bson(vec2);
             // serializations must match
             assert(json::to_bson(j2) == vec2);
         }
         catch (const json::parse_error&)
         {
             // parsing a BSON serialization must not fail
             assert(false);
         }
     }
     catch (const json::parse_error&)
     {
         // parse errors are ok, because input may be random bytes
     }
     catch (const json::type_error&)
     {
         // type errors can occur during parsing, too
     }
     catch (const json::out_of_range&)
     {
         // out of range errors can occur during parsing, too
     }
     // return 0 - non-zero return values are reserved for future use
     return 0;
 }
References AllocatedPointers, argv0, assert(), Counter, DSO1(), DSO2(), DSOTestExtra(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::dump(), Eq(), EQ(), f01(), f12(), f23(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::from_bson(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::from_cbor(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::from_msgpack(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::from_ubjson(), fuzzer::Hash(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::is_discarded(), kAllocatedPointersSize, kArraySize, Large, N, nil, Null, NumAllocatedPointers, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parse(), PrintOnce(), Ptr, SeedLargeBuffer, ShortSwitch(), simple_hash(), Sink, sink, SinkPtr, Switch(), t, t0, Target, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::to_bson(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::to_cbor(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::to_msgpack(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::to_ubjson(), and Zero.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 19 of file FuzzerMain.cpp.
{
   return fuzzer::FuzzerDriver(&argc, &argv, LLVMFuzzerTestOneInput);
 }
References argv, fuzzer::FuzzerDriver(), and LLVMFuzzerTestOneInput().