Mixed Criticality Orchestrator: mc_orchestrator/json-3.7.3/test/thirdparty/Fuzzer/FuzzerTracePC.cpp File Reference
FuzzerTracePC.cpp File Reference
#include "FuzzerCorpus.h"
#include "FuzzerDefs.h"
#include "FuzzerDictionary.h"
#include "FuzzerExtFunctions.h"
#include "FuzzerIO.h"
#include "FuzzerTracePC.h"
#include "FuzzerValueBitMap.h"
#include <map>
#include <sanitizer/coverage_interface.h>
#include <set>
#include <sstream>
Namespaces
fuzzer
Functions
static bool fuzzer::IsInterestingCoverageFile (std::string &File)
__attribute__ ((visibility("default"))) void __sanitizer_cov_trace_pc_guard(uint32_t *Guard)
assert (PowerOfTwoGeN >=N)
if (Idx >=N) Idx -
assert (Idx< N)
if((Val|Vals[Idx])< TwoIn32) fuzzer else fuzzer::TPC HandleCmp (PC+Idx, Val, Vals[Idx])
Variables
TracePC fuzzer::TPC
uint32_t * Stop
uint64_t Arg2
uint64_t * Cases
Counter
uint64_t N = Cases[0]
uint64_t * Vals = Cases + 2
char * PC = (char*)__builtin_return_address(0)
size_t Nlog = sizeof(long) * 8 - __builtin_clzl((long)N)
size_t PowerOfTwoGeN = 1U << Nlog
size_t Idx = Counter & (PowerOfTwoGeN - 1)
uint64_t TwoIn32 = 1ULL << 32
Function Documentation
__attribute__()
__attribute__ ((visibility("default")))
Definition at line 262 of file FuzzerTracePC.cpp.
{
   uintptr_t PC = (uintptr_t)__builtin_return_address(0);
   fuzzer::TPC.HandleTrace(Guard, PC);
 }
References fuzzer::TracePC::HandleTrace(), PC, and fuzzer::TPC.
assert() [1/2]
assert ()
assert() [2/2]
assert (PowerOfTwoGeN >= N)
Referenced by fuzzer::InputCorpus::AddFeature(), fuzzer::TraceState::AddMutation(), fuzzer::InputCorpus::AddToCorpus(), fuzzer::Fuzzer::AlarmCallback(), httplib::detail::stream_line_reader::append(), nlohmann::detail::dtoa_impl::append_exponent(), httplib::Server::apply_ranges(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::assert_invariant(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::basic_json(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::binary_reader(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::binary_writer(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_element_size(), fuzzer::ChangeBinaryInteger(), fuzzer::InputCorpus::ChooseUnitIdxToMutate(), fuzzer::InputCorpus::ChooseUnitToMutate(), httplib::ClientImpl::close_socket(), fuzzer::TracePC::CollectFeatures(), nlohmann::detail::dtoa_impl::compute_boundaries(), fuzzer::MutationDispatcher::CopyPartOf(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::create(), fuzzer::MutationDispatcher::CrossOver(), nlohmann::detail::serializer< BasicJsonType >::dump(), nlohmann::detail::serializer< BasicJsonType >::dump_escaped(), nlohmann::detail::serializer< BasicJsonType >::dump_float(), nlohmann::detail::serializer< BasicJsonType >::dump_integer(), httplib::detail::encode_url(), nlohmann::detail::json_sax_dom_callback_parser< BasicJsonType >::end_array(), nlohmann::detail::json_sax_dom_callback_parser< BasicJsonType >::end_object(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::exception_message(), fuzzer::Fuzzer::ExecuteCallback(), fuzzer::Fuzzer::FindExtraUnits(), nlohmann::detail::dtoa_impl::format_buffer(), fuzzer::Fuzzer::Fuzzer(), fuzzer::FuzzerDriver(), fuzzer::ValueBitMap::Get(), nlohmann::detail::dtoa_impl::get_cached_power_for_binary_exponent(), nlohmann::detail::input_buffer_adapter::get_character(), nlohmann::detail::wide_string_input_adapter< WideStringType >::get_character(), nlohmann::detail::lexer< BasicJsonType >::get_codepoint(), nlohmann::detail::lexer< BasicJsonType >::get_decimal_point(), httplib::detail::get_range_offset_and_length(), fuzzer::Fuzzer::GetCurrentUnitInFuzzingThead(), fuzzer::TracePC::GetPC(), fuzzer::GetPeakRSSMb(), fuzzer::DictionaryEntry::GetPositionHint(), nlohmann::detail::dtoa_impl::grisu2(), nlohmann::detail::dtoa_impl::grisu2_digit_gen(), nlohmann::detail::dtoa_impl::grisu2_round(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value(), nlohmann::detail::json_sax_dom_callback_parser< BasicJsonType >::handle_value(), fuzzer::TracePC::HandleInit(), nlohmann::detail::input_adapter::input_adapter(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::insert_iterator(), fuzzer::MutationDispatcher::InsertPartOf(), httplib::detail::is_valid_path(), nlohmann::detail::iter_impl< BasicJsonType >::iter_impl(), benchmark::State::KeepRunningInternal(), nlohmann::detail::iteration_proxy_value< IteratorType >::key(), nlohmann::detail::iter_impl< BasicJsonType >::key(), LLVMFuzzerInitialize(), LLVMFuzzerMutate(), LLVMFuzzerTestOneInput(), main(), httplib::detail::make_multipart_ranges_data(), fuzzer::Merger::Merge(), fuzzer::Fuzzer::Merge(), fuzzer::MinimizeCrashInput(), fuzzer::MinimizeCrashInputInternalStep(), fuzzer::Fuzzer::MinimizeCrashLoop(), fuzzer::MutationDispatcher::Mutate_ChangeASCIIInteger(), fuzzer::MutationDispatcher::Mutate_ChangeBinaryInteger(), fuzzer::MutationDispatcher::Mutate_CrossOver(), fuzzer::MutationDispatcher::Mutate_CustomCrossOver(), fuzzer::MutationDispatcher::Mutate_EraseBytes(), fuzzer::MutationDispatcher::Mutate_InsertRepeatedBytes(), fuzzer::MutationDispatcher::Mutate_ShuffleBytes(), fuzzer::Fuzzer::MutateAndTestOne(), fuzzer::MutationDispatcher::MutateImpl(), nlohmann::detail::lexer< BasicJsonType >::next_byte_in_range(), nlohmann::detail::dtoa_impl::diyfp::normalize(), nlohmann::detail::dtoa_impl::diyfp::normalize_to(), fuzzer::Random::operator()(), httplib::ThreadPool::worker::operator()(), nlohmann::detail::iter_impl< BasicJsonType >::operator*(), nlohmann::detail::iter_impl< BasicJsonType >::operator++(), benchmark::State::StateIterator::operator++(), nlohmann::detail::iter_impl< BasicJsonType >::operator+=(), nlohmann::detail::iter_impl< BasicJsonType >::operator-(), nlohmann::detail::iter_impl< BasicJsonType >::operator--(), nlohmann::detail::iter_impl< BasicJsonType >::operator->(), nlohmann::detail::iter_impl< BasicJsonType >::operator<(), nlohmann::detail::iter_impl< BasicJsonType >::operator==(), fuzzer::Dictionary::operator[](), nlohmann::detail::iter_impl< BasicJsonType >::operator[](), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::operator[](), fuzzer::Merger::Parse(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::parse_cbor_internal(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::parse_error(), nlohmann::detail::json_sax_dom_callback_parser< BasicJsonType >::parse_error(), fuzzer::ParseOneDictionaryEntry(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::patch(), httplib::detail::process_server_socket_core(), benchmark::State::range(), httplib::detail::read_content_chunked(), nlohmann::detail::serializer< BasicJsonType >::remove_sign(), nlohmann::json_pointer< BasicJsonType >::replace_substring(), fuzzer::InputCorpus::ResetFeatureSet(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax_parse(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::sax_parse(), nlohmann::detail::parser< BasicJsonType >::sax_parse_internal(), nlohmann::detail::lexer< BasicJsonType >::scan_literal(), nlohmann::detail::lexer< BasicJsonType >::scan_number(), nlohmann::detail::lexer< BasicJsonType >::scan_string(), httplib::ClientImpl::send(), httplib::ClientImpl::send_(), fuzzer::FixedWord< 27 >::Set(), nlohmann::detail::iter_impl< BasicJsonType >::set_begin(), nlohmann::detail::iter_impl< BasicJsonType >::set_end(), benchmark::BenchmarkReporter::SetErrorStream(), fuzzer::Fuzzer::SetMaxInputLen(), fuzzer::Fuzzer::SetMaxMutationLen(), benchmark::BenchmarkReporter::SetOutputStream(), httplib::ClientImpl::shutdown_ssl(), nlohmann::json_pointer< BasicJsonType >::split(), fuzzer::Fuzzer::StaticAlarmCallback(), fuzzer::Fuzzer::StaticCrashSignalCallback(), fuzzer::Fuzzer::StaticDeathCallback(), fuzzer::Fuzzer::StaticInterruptCallback(), httplib::Server::stop(), nlohmann::detail::dtoa_impl::diyfp::sub(), nlohmann::detail::to_chars(), fuzzer::TraceState::TryToAddDesiredData(), nlohmann::detail::lexer< BasicJsonType >::unget(), fuzzer::InputCorpus::ValidateFeatureSet(), fuzzer::TraceState::WantToHandleOneMoreMutation(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_element(), httplib::Server::write_content_with_provider(), httplib::Server::write_response_core(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_ubjson(), and fuzzer::Fuzzer::WriteToOutputCorpus().
HandleCmp()
if ((Val | Vals[Idx]) < TwoIn32) fuzzer else fuzzer::TPC HandleCmp (PC+ Idx, Val , Vals [Idx])
if()
if (Idx >= N)
Referenced by httplib::detail::create_client_socket(), httplib::Server::create_server_socket(), httplib::detail::read_content(), DatabaseHandler::ReadData(), DatabaseHandler::ReadListData(), and DatabaseHandler::ReadStringData().
Variable Documentation
Arg2
uint8_t Arg2
Initial value:
{
  fuzzer::TPC.HandleCmp(__builtin_return_address(0), Arg1, Arg2)
Definition at line 280 of file FuzzerTracePC.cpp.
Referenced by fuzzer::TracePC::HandleCmp(), fuzzer::TableOfRecentCompares< uint64_t, kTORCSize >::Insert(), and fuzzer::MutationDispatcher::MakeDictionaryEntryFromCMP().
Cases
uint64_t* Cases
Initial value:
{
  static thread_local size_t Counter
Definition at line 297 of file FuzzerTracePC.cpp.
Referenced by fuzzer::TraceState::TraceSwitchCallback().
Counter
Counter
Definition at line 303 of file FuzzerTracePC.cpp.
Referenced by fuzzer::TracePC::CollectFeatures(), and fuzzer::RunInMultipleProcesses().
Idx
size_t Idx = Counter & (PowerOfTwoGeN - 1)
Definition at line 314 of file FuzzerTracePC.cpp.
Referenced by fuzzer::InputCorpus::AddFeature(), fuzzer::ValueBitMap::AddValue(), fuzzer::TracePC::AddValueForMemcmp(), fuzzer::TracePC::AddValueForStrcmp(), fuzzer::MutationDispatcher::ApplyDictionaryEntry(), fuzzer::InputCorpus::ChooseUnitIdxToMutate(), fuzzer::TracePC::CollectFeatures(), fuzzer::InputCorpus::DeleteInput(), nlohmann::detail::from_json_tuple_impl(), fuzzer::ValueBitMap::Get(), fuzzer::InputCorpus::GetFeature(), fuzzer::TracePC::GetPC(), fuzzer::TracePC::HandleCallerCallee(), fuzzer::TracePC::HandleCmp(), fuzzer::TracePC::HandleTrace(), fuzzer::TableOfRecentCompares< uint64_t, kTORCSize >::Insert(), fuzzer::MutationDispatcher::Mutate_ChangeASCIIInteger(), fuzzer::MutationDispatcher::Mutate_ChangeBit(), fuzzer::MutationDispatcher::Mutate_ChangeByte(), fuzzer::MutationDispatcher::Mutate_CrossOver(), fuzzer::MutationDispatcher::Mutate_CustomCrossOver(), fuzzer::MutationDispatcher::Mutate_EraseBytes(), fuzzer::MutationDispatcher::Mutate_InsertByte(), fuzzer::MutationDispatcher::Mutate_InsertRepeatedBytes(), fuzzer::InputCorpus::operator[](), fuzzer::Dictionary::operator[](), and fuzzer::InputCorpus::ValidateFeatureSet().
N
uint64_t N = Cases[0]
Definition at line 304 of file FuzzerTracePC.cpp.
Referenced by __sanitizer_weak_hook_strcmp(), fuzzer::Fuzzer::CheckExitOnSrcPosOrItem(), fuzzer::TracePC::CollectFeatures(), fuzzer::ExecuteCommandAndReadOutput(), fuzzer::FreeHook(), nlohmann::detail::from_json(), nlohmann::detail::from_json_array_impl(), LLVMFuzzerTestOneInput(), main(), fuzzer::MallocHook(), fuzzer::MutationDispatcher::Mutate_EraseBytes(), fuzzer::MutationDispatcher::Mutate_InsertRepeatedBytes(), fuzzer::NumberOfCpuCores(), fuzzer::Merger::Parse(), fuzzer::InputCorpus::PrintFeatureSet(), fuzzer::Fuzzer::PrintStats(), TEST(), TEST_CASE(), fuzzer::InputCorpus::UpdateCorpusDistribution(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_cbor(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_msgpack().
Nlog
size_t Nlog = sizeof(long) * 8 - __builtin_clzl((long)N)
Definition at line 311 of file FuzzerTracePC.cpp.
PC
char* PC = (char*)__builtin_return_address(0)
Definition at line 306 of file FuzzerTracePC.cpp.
Referenced by __attribute__(), fuzzer::TracePC::AddValueForMemcmp(), fuzzer::TracePC::AddValueForStrcmp(), fuzzer::Fuzzer::CheckExitOnSrcPosOrItem(), fuzzer::DescribePC(), fuzzer::TracePC::HandleCmp(), fuzzer::TracePC::HandleTrace(), fuzzer::TracePC::PrintCoverage(), fuzzer::PrintPC(), and fuzzer::TraceState::TraceSwitchCallback().
PowerOfTwoGeN
size_t PowerOfTwoGeN = 1U << Nlog
Definition at line 312 of file FuzzerTracePC.cpp.
Stop
uint32_t* Stop
Initial value:
{
  fuzzer::TPC.HandleInit(Start, Stop)
Definition at line 269 of file FuzzerTracePC.cpp.
Referenced by fuzzer::TracePC::HandleInit(), and fuzzer::TracePC::PrintModuleInfo().
TwoIn32
uint64_t TwoIn32 = 1ULL << 32
Definition at line 318 of file FuzzerTracePC.cpp.
Vals
uint64_t* Vals = Cases + 2
Definition at line 305 of file FuzzerTracePC.cpp.