Mixed Criticality Orchestrator: mc_orchestrator/json-3.7.3/test/thirdparty/Fuzzer/FuzzerInterface.h File Reference
FuzzerInterface.h File Reference
#include <stddef.h>
#include <stdint.h>
Functions
int LLVMFuzzerTestOneInput (const uint8_t *Data, size_t Size)
int LLVMFuzzerInitialize (int *argc, char ***argv)
size_t LLVMFuzzerCustomMutator (uint8_t *Data, size_t Size, size_t MaxSize, unsigned int Seed)
size_t LLVMFuzzerCustomCrossOver (const uint8_t *Data1, size_t Size1, const uint8_t *Data2, size_t Size2, uint8_t *Out, size_t MaxOutSize, unsigned int Seed)
size_t LLVMFuzzerMutate (uint8_t *Data, size_t Size, size_t MaxSize)
Function Documentation
LLVMFuzzerCustomCrossOver()
size_t LLVMFuzzerCustomCrossOver (const uint8_t * Data1, size_t Size1, const uint8_t * Data2, size_t Size2, uint8_t * Out, size_t MaxOutSize, unsigned int Seed)
Definition at line 35 of file CustomCrossOverTest.cpp.
{
   static bool Printed;
   static size_t SeparatorLen = strlen(Separator);
   if (!Printed) {
     std::cerr << "In LLVMFuzzerCustomCrossover\n";
     Printed = true;
   }
   std::mt19937 R(Seed);
   size_t Offset1 = 0;
   size_t Len1 = R() % (Size1 - Offset1);
   size_t Offset2 = 0;
   size_t Len2 = R() % (Size2 - Offset2);
   size_t Size = Len1 + Len2 + SeparatorLen;
   if (Size > MaxOutSize)
     return 0;
   memcpy(Out, Data1 + Offset1, Len1);
   memcpy(Out + Len1, Separator, SeparatorLen);
   memcpy(Out + Len1 + SeparatorLen, Data2 + Offset2, Len2);
   return Len1 + Len2 + SeparatorLen;
 }
References Separator.
LLVMFuzzerCustomMutator()
size_t LLVMFuzzerCustomMutator (uint8_t * Data, size_t Size, size_t MaxSize, unsigned int Seed)
Definition at line 30 of file CustomMutatorTest.cpp.
{
   static bool Printed;
   if (!Printed) {
     std::cerr << "In LLVMFuzzerCustomMutator\n";
     Printed = true;
   }
   return LLVMFuzzerMutate(Data, Size, MaxSize);
 }
References LLVMFuzzerMutate().
LLVMFuzzerInitialize()
int LLVMFuzzerInitialize (int * argc, char *** argv)
Definition at line 16 of file AFLDriverTest.cpp.
{
   return 0;
 }
References argv, argv0, and assert().
Referenced by main().
LLVMFuzzerMutate()
size_t LLVMFuzzerMutate (uint8_t * Data, size_t Size, size_t MaxSize)
Definition at line 788 of file FuzzerLoop.cpp.
{
   assert(fuzzer::F);
   return fuzzer::F->GetMD().DefaultMutate(Data, Size, MaxSize);
 }
References assert(), fuzzer::MutationDispatcher::DefaultMutate(), fuzzer::F, and fuzzer::Fuzzer::GetMD().
Referenced by LLVMFuzzerCustomMutator().
LLVMFuzzerTestOneInput()
int LLVMFuzzerTestOneInput (const uint8_t * Data, size_t Size)
Definition at line 28 of file fuzzer-parse_bson.cpp.
 {
     try
     {
         // step 1: parse input
         std::vector<uint8_t> vec1(data, data + size);
         json j1 = json::from_bson(vec1);
         if (j1.is_discarded())
         {
             return 0;
         }
         try
         {
             // step 2: round trip
             std::vector<uint8_t> vec2 = json::to_bson(j1);
             // parse serialization
             json j2 = json::from_bson(vec2);
             // serializations must match
             assert(json::to_bson(j2) == vec2);
         }
         catch (const json::parse_error&)
         {
             // parsing a BSON serialization must not fail
             assert(false);
         }
     }
     catch (const json::parse_error&)
     {
         // parse errors are ok, because input may be random bytes
     }
     catch (const json::type_error&)
     {
         // type errors can occur during parsing, too
     }
     catch (const json::out_of_range&)
     {
         // out of range errors can occur during parsing, too
     }
     // return 0 - non-zero return values are reserved for future use
     return 0;
 }