Mixed Criticality Orchestrator: mc_orchestrator/json-3.7.3/test/src/fuzzer-parse_msgpack.cpp File Reference
fuzzer-parse_msgpack.cpp File Reference
#include <iostream>
#include <sstream>
#include <nlohmann/json.hpp>
Typedefs
using json = nlohmann::json
Functions
int LLVMFuzzerTestOneInput (const uint8_t *data, size_t size)
Typedef Documentation
json
using json = nlohmann::json
Definition at line 25 of file fuzzer-parse_msgpack.cpp.
Function Documentation
LLVMFuzzerTestOneInput()
int LLVMFuzzerTestOneInput (const uint8_t * data, size_t size)
Definition at line 28 of file fuzzer-parse_msgpack.cpp.
 {
     try
     {
         // step 1: parse input
         std::vector<uint8_t> vec1(data, data + size);
         json j1 = json::from_msgpack(vec1);
         try
         {
             // step 2: round trip
             std::vector<uint8_t> vec2 = json::to_msgpack(j1);
             // parse serialization
             json j2 = json::from_msgpack(vec2);
             // serializations must match
             assert(json::to_msgpack(j2) == vec2);
         }
         catch (const json::parse_error&)
         {
             // parsing a MessagePack serialization must not fail
             assert(false);
         }
     }
     catch (const json::parse_error&)
     {
         // parse errors are ok, because input may be random bytes
     }
     catch (const json::type_error&)
     {
         // type errors can occur during parsing, too
     }
     catch (const json::out_of_range&)
     {
         // out of range errors may happen if provided sizes are excessive
     }
     // return 0 - non-zero return values are reserved for future use
     return 0;
 }
References assert(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::from_msgpack(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::to_msgpack().