Mixed Criticality Orchestrator: mc_orchestrator/json-3.7.3/test/thirdparty/Fuzzer/FuzzerTraceState.cpp File Reference
FuzzerTraceState.cpp File Reference
#include "FuzzerDictionary.h"
#include "FuzzerInternal.h"
#include "FuzzerIO.h"
#include "FuzzerMutate.h"
#include "FuzzerRandom.h"
#include "FuzzerTracePC.h"
#include <algorithm>
#include <cstring>
#include <map>
#include <set>
#include <thread>
Classes
struct fuzzer::TraceBasedMutation
class fuzzer::TraceState
Namespaces
fuzzer
Macros
#define LLVM_FUZZER_DEFINES_SANITIZER_WEAK_HOOOKS 1
Functions
static size_t fuzzer::InternalStrnlen (const char *S, size_t MaxLen)
void __sanitizer_weak_hook_memcmp (void *caller_pc, const void *s1, const void *s2, size_t n, int result)
void __sanitizer_weak_hook_strncmp (void *caller_pc, const char *s1, const char *s2, size_t n, int result)
void __sanitizer_weak_hook_strcmp (void *caller_pc, const char *s1, const char *s2, int result)
void __sanitizer_weak_hook_strncasecmp (void *called_pc, const char *s1, const char *s2, size_t n, int result)
void __sanitizer_weak_hook_strcasecmp (void *called_pc, const char *s1, const char *s2, int result)
void __sanitizer_weak_hook_strstr (void *called_pc, const char *s1, const char *s2, char *result)
void __sanitizer_weak_hook_strcasestr (void *called_pc, const char *s1, const char *s2, char *result)
void __sanitizer_weak_hook_memmem (void *called_pc, const void *s1, size_t len1, const void *s2, size_t len2, void *result)
Variables
static bool fuzzer::RecordingMemcmp = false
static bool fuzzer::RecordingMemmem = false
static bool fuzzer::DoingMyOwnMemmem = false
static TraceState * fuzzer::TS
Macro Definition Documentation
LLVM_FUZZER_DEFINES_SANITIZER_WEAK_HOOOKS
#define LLVM_FUZZER_DEFINES_SANITIZER_WEAK_HOOOKS 1
Definition at line 261 of file FuzzerTraceState.cpp.
Function Documentation
__sanitizer_weak_hook_memcmp()
void __sanitizer_weak_hook_memcmp (void * caller_pc, const void * s1, const void * s2, size_t n, int result)
Definition at line 265 of file FuzzerTraceState.cpp.
{
   fuzzer::TPC.AddValueForMemcmp(caller_pc, s1, s2, n);
   if (!RecordingMemcmp) return;
   if (result == 0) return;  // No reason to mutate.
   if (n <= 1) return;  // Not interesting.
   TS->TraceMemcmpCallback(n, reinterpret_cast<const uint8_t *>(s1),
                           reinterpret_cast<const uint8_t *>(s2));
 }
References fuzzer::TracePC::AddValueForMemcmp(), n, fuzzer::RecordingMemcmp, result, fuzzer::TPC, fuzzer::TraceState::TraceMemcmpCallback(), and fuzzer::TS.
__sanitizer_weak_hook_memmem()
void __sanitizer_weak_hook_memmem (void * called_pc, const void * s1, size_t len1, const void * s2, size_t len2, void * result)
Definition at line 318 of file FuzzerTraceState.cpp.
{
   if (fuzzer::DoingMyOwnMemmem) return;
   TS->AddInterestingWord(reinterpret_cast<const uint8_t *>(s2), len2);
 }
References fuzzer::TraceState::AddInterestingWord(), fuzzer::DoingMyOwnMemmem, and fuzzer::TS.
__sanitizer_weak_hook_strcasecmp()
void __sanitizer_weak_hook_strcasecmp (void * called_pc, const char * s1, const char * s2, int result)
Definition at line 306 of file FuzzerTraceState.cpp.
{
   return __sanitizer_weak_hook_strcmp(called_pc, s1, s2, result);
 }
References __sanitizer_weak_hook_strcmp(), and result.
__sanitizer_weak_hook_strcasestr()
void __sanitizer_weak_hook_strcasestr (void * called_pc, const char * s1, const char * s2, char * result)
Definition at line 314 of file FuzzerTraceState.cpp.
{
   TS->AddInterestingWord(reinterpret_cast<const uint8_t *>(s2), strlen(s2));
 }
References fuzzer::TraceState::AddInterestingWord(), and fuzzer::TS.
__sanitizer_weak_hook_strcmp()
void __sanitizer_weak_hook_strcmp (void * caller_pc, const char * s1, const char * s2, int result)
Definition at line 289 of file FuzzerTraceState.cpp.
{
   fuzzer::TPC.AddValueForStrcmp(caller_pc, s1, s2, 64);
   if (!RecordingMemcmp) return;
   if (result == 0) return;  // No reason to mutate.
   size_t Len1 = strlen(s1);
   size_t Len2 = strlen(s2);
   size_t N = std::min(Len1, Len2);
   if (N <= 1) return;  // Not interesting.
   TS->TraceMemcmpCallback(N, reinterpret_cast<const uint8_t *>(s1),
                           reinterpret_cast<const uint8_t *>(s2));
 }
References fuzzer::TracePC::AddValueForStrcmp(), N, fuzzer::RecordingMemcmp, result, fuzzer::TPC, fuzzer::TraceState::TraceMemcmpCallback(), and fuzzer::TS.
Referenced by __sanitizer_weak_hook_strcasecmp().
__sanitizer_weak_hook_strncasecmp()
void __sanitizer_weak_hook_strncasecmp (void * called_pc, const char * s1, const char * s2, size_t n, int result)
Definition at line 302 of file FuzzerTraceState.cpp.
{
   return __sanitizer_weak_hook_strncmp(called_pc, s1, s2, n, result);
 }
References __sanitizer_weak_hook_strncmp(), n, and result.
__sanitizer_weak_hook_strncmp()
void __sanitizer_weak_hook_strncmp (void * caller_pc, const char * s1, const char * s2, size_t n, int result)
Definition at line 275 of file FuzzerTraceState.cpp.
{
   fuzzer::TPC.AddValueForStrcmp(caller_pc, s1, s2, n);
   if (!RecordingMemcmp) return;
   if (result == 0) return;  // No reason to mutate.
   size_t Len1 = fuzzer::InternalStrnlen(s1, n);
   size_t Len2 = fuzzer::InternalStrnlen(s2, n);
   n = std::min(n, Len1);
   n = std::min(n, Len2);
   if (n <= 1) return;  // Not interesting.
   TS->TraceMemcmpCallback(n, reinterpret_cast<const uint8_t *>(s1),
                           reinterpret_cast<const uint8_t *>(s2));
 }
References fuzzer::TracePC::AddValueForStrcmp(), fuzzer::InternalStrnlen(), n, fuzzer::RecordingMemcmp, result, fuzzer::TPC, fuzzer::TraceState::TraceMemcmpCallback(), and fuzzer::TS.
Referenced by __sanitizer_weak_hook_strncasecmp().
__sanitizer_weak_hook_strstr()
void __sanitizer_weak_hook_strstr (void * called_pc, const char * s1, const char * s2, char * result)
Definition at line 310 of file FuzzerTraceState.cpp.
{
   TS->AddInterestingWord(reinterpret_cast<const uint8_t *>(s2), strlen(s2));
 }
References fuzzer::TraceState::AddInterestingWord(), and fuzzer::TS.