Mixed Criticality Orchestrator: mc_orchestrator/json-3.7.3/test/src/fuzzer-parse_json.cpp File Reference
fuzzer-parse_json.cpp File Reference
#include <iostream>
#include <sstream>
#include <nlohmann/json.hpp>
Typedefs
using json = nlohmann::json
Functions
int LLVMFuzzerTestOneInput (const uint8_t *data, size_t size)
Typedef Documentation
json
using json = nlohmann::json
Definition at line 26 of file fuzzer-parse_json.cpp.
Function Documentation
LLVMFuzzerTestOneInput()
int LLVMFuzzerTestOneInput (const uint8_t * data, size_t size)
Definition at line 29 of file fuzzer-parse_json.cpp.
 {
     try
     {
         // step 1: parse input
         json j1 = json::parse(data, data + size);
         try
         {
             // step 2: round trip
             // first serialization
             std::string s1 = j1.dump();
             // parse serialization
             json j2 = json::parse(s1);
             // second serialization
             std::string s2 = j2.dump();
             // serializations must match
             assert(s1 == s2);
         }
         catch (const json::parse_error&)
         {
             // parsing a JSON serialization must not fail
             assert(false);
         }
     }
     catch (const json::parse_error&)
     {
         // parse errors are ok, because input may be random bytes
     }
     catch (const json::out_of_range&)
     {
         // out of range errors may happen if provided sizes are excessive
     }
     // return 0 - non-zero return values are reserved for future use
     return 0;
 }
References assert(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::dump(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parse().