Mixed Criticality Orchestrator: mc_orchestrator/json-3.7.3/test/thirdparty/Fuzzer/FuzzerLoop.cpp File Reference
FuzzerLoop.cpp File Reference
#include "FuzzerCorpus.h"
#include "FuzzerInternal.h"
#include "FuzzerIO.h"
#include "FuzzerMutate.h"
#include "FuzzerRandom.h"
#include "FuzzerTracePC.h"
#include <algorithm>
#include <cstring>
#include <memory>
#include <set>
Classes
struct fuzzer::MallocFreeTracer
Namespaces
fuzzer
Macros
#define NO_SANITIZE_MEMORY
#define CHECK_EXTERNAL_FUNCTION(fn)
Functions
static void fuzzer::MissingExternalApiFunction (const char *FnName)
void fuzzer::MallocHook (const volatile void *ptr, size_t size)
void fuzzer::FreeHook (const volatile void *ptr)
static void fuzzer::WarnOnUnsuccessfullMerge (bool DoWarn)
size_t LLVMFuzzerMutate (uint8_t *Data, size_t Size, size_t MaxSize)
Variables
static const size_t fuzzer::kMaxUnitSizeToPrint = 256
static Fuzzer * fuzzer::F
static MallocFreeTracer fuzzer::AllocTracer
Macro Definition Documentation
CHECK_EXTERNAL_FUNCTION
#define CHECK_EXTERNAL_FUNCTION (fn)
Value:
  do {                                                                         \
    if (!(EF->fn))                                                             \
      MissingExternalApiFunction(#fn);                                         \
  } while (false)
Definition at line 52 of file FuzzerLoop.cpp.
NO_SANITIZE_MEMORY
#define NO_SANITIZE_MEMORY
Definition at line 32 of file FuzzerLoop.cpp.
Function Documentation
LLVMFuzzerMutate()
size_t LLVMFuzzerMutate (uint8_t * Data, size_t Size, size_t MaxSize)
Definition at line 788 of file FuzzerLoop.cpp.
{
   assert(fuzzer::F);
   return fuzzer::F->GetMD().DefaultMutate(Data, Size, MaxSize);
 }
References assert(), fuzzer::MutationDispatcher::DefaultMutate(), fuzzer::F, and fuzzer::Fuzzer::GetMD().
Referenced by LLVMFuzzerCustomMutator().