Mixed Criticality Orchestrator: doctest::detail Namespace Reference
doctest::detail Namespace Reference
Namespaces
assertAction
binaryAssertComparison
has_insertion_operator_impl
Classes
class ContextScope
class ContextScopeBase
struct deferred_false
class ExceptionTranslator
OCLINT destructor of virtual class.
struct Expression_lhs
struct ExpressionDecomposer
struct has_insertion_operator
struct IExceptionTranslator
struct MessageBuilder
struct RelationalComparator
struct RelationalComparator< 0, L, R >
struct RelationalComparator< 1, L, R >
struct RelationalComparator< 2, L, R >
struct RelationalComparator< 3, L, R >
struct RelationalComparator< 4, L, R >
struct RelationalComparator< 5, L, R >
struct remove_const
struct remove_const< const T >
struct remove_reference
struct remove_reference< T & >
struct remove_reference< T && >
struct Result
struct ResultBuilder
struct StringMakerBase
struct StringMakerBase< true >
struct StringStream
struct StringStreamBase
struct StringStreamBase< true >
struct Subcase
struct TestCase
struct TestFailureException
struct TestSuite
Typedefs
typedef void(* funcType) ()
typedef void(* assert_handler) (const AssertData &)
typedef IReporter *(* reporterCreatorFunc) (const ContextOptions &)
Functions
void my_memcpy (void *dest, const void *src, unsigned num)
std::ostream * getTlsOss ()
String getTlsOssResult ()
String rawMemoryToString (const void *object, unsigned size)
template<typename T >
String rawMemoryToString (const T &object)
template<typename T >
const char * type_to_string ()
bool checkIfShouldThrow (assertType::Enum at)
void throwException ()
template<typename L , typename R >
String stringifyBinaryExpr (const L &lhs, const char *op, const R &rhs)
template<typename L , typename R >
bool eq (const L &lhs, const R &rhs)
template<typename L , typename R >
bool ne (const L &lhs, const R &rhs)
template<typename L , typename R >
bool lt (const L &lhs, const R &rhs)
template<typename L , typename R >
bool gt (const L &lhs, const R &rhs)
template<typename L , typename R >
bool le (const L &lhs, const R &rhs)
template<typename L , typename R >
bool ge (const L &lhs, const R &rhs)
int regTest (const TestCase &tc)
int setTestSuite (const TestSuite &ts)
bool isDebuggerActive ()
template<typename T >
int instantiationHelper (const T &)
void failed_out_of_a_testing_context (const AssertData &ad)
void decomp_assert (assertType::Enum at, const char *file, int line, const char *expr, Result result)
template<int comparison, typename L , typename R >
__attribute__ ((noinline)) void binary_assert(assertType
template<typename L >
__attribute__ ((noinline)) void unary_assert(assertType
void registerExceptionTranslatorImpl (const IExceptionTranslator *et)
template<typename T >
void toStream (std::ostream *s, const T &value)
void toStream (std::ostream *s, bool in)
void toStream (std::ostream *s, float in)
void toStream (std::ostream *s, double in)
void toStream (std::ostream *s, double long in)
void toStream (std::ostream *s, char in)
void toStream (std::ostream *s, char signed in)
void toStream (std::ostream *s, char unsigned in)
void toStream (std::ostream *s, int short in)
void toStream (std::ostream *s, int short unsigned in)
void toStream (std::ostream *s, int in)
void toStream (std::ostream *s, int unsigned in)
void toStream (std::ostream *s, int long in)
void toStream (std::ostream *s, int long unsigned in)
void toStream (std::ostream *s, int long long in)
void toStream (std::ostream *s, int long long unsigned in)
template<typename L >
ContextScope< L > MakeContextScope (const L &lambda)
void registerReporterImpl (const char *name, int prio, reporterCreatorFunc c, bool isReporter)
template<typename Reporter >
IReporter * reporterCreator (const ContextOptions &o)
template<>
const char * type_to_string< bool > ()
template<>
const char * type_to_string< float > ()
template<>
const char * type_to_string< double > ()
template<>
const char * type_to_string< long double > ()
template<>
const char * type_to_string< char > ()
template<>
const char * type_to_string< signed char > ()
template<>
const char * type_to_string< unsigned char > ()
template<>
const char * type_to_string< wchar_t > ()
template<>
const char * type_to_string< short int > ()
template<>
const char * type_to_string< unsigned short int > ()
template<>
const char * type_to_string< int > ()
template<>
const char * type_to_string< unsigned int > ()
template<>
const char * type_to_string< long int > ()
template<>
const char * type_to_string< unsigned long int > ()
template<>
const char * type_to_string< long long int > ()
template<>
const char * type_to_string< unsigned long long int > ()
Typedef Documentation
assert_handler
typedef void(* doctest::detail::assert_handler) (const AssertData &)
Definition at line 1577 of file doctest.h.
funcType
typedef void(* doctest::detail::funcType) ()
Definition at line 1233 of file doctest.h.
reporterCreatorFunc
typedef IReporter*(* doctest::detail::reporterCreatorFunc) (const ContextOptions &)
Definition at line 1707 of file doctest.h.
Function Documentation
__attribute__() [1/2]
template<int comparison, typename L , typename R > doctest::detail::__attribute__ ((noinline))
Definition at line 1371 of file doctest.h.
{
         bool failed = !RelationalComparator<comparison, L, R>()(lhs, rhs);
         // ###################################################################################
         // IF THE DEBUGGER BREAKS HERE - GO 1 LEVEL UP IN THE CALLSTACK FOR THE FAILING ASSERT
         // THIS IS THE EFFECT OF HAVING 'DOCTEST_CONFIG_SUPER_FAST_ASSERTS' DEFINED
         // ###################################################################################
         DOCTEST_ASSERT_OUT_OF_TESTS(stringifyBinaryExpr(lhs, ", ", rhs));
         DOCTEST_ASSERT_IN_TESTS(stringifyBinaryExpr(lhs, ", ", rhs));
     }
References DOCTEST_ASSERT_IN_TESTS, DOCTEST_ASSERT_OUT_OF_TESTS, and stringifyBinaryExpr().
__attribute__() [2/2]
template<typename L > doctest::detail::__attribute__ ((noinline))
OCLINT bitwise operator in conditional
Definition at line 1385 of file doctest.h.
{
         bool failed = !val;
         if(at & assertType::is_false)
             failed = !failed;
         // ###################################################################################
         // IF THE DEBUGGER BREAKS HERE - GO 1 LEVEL UP IN THE CALLSTACK FOR THE FAILING ASSERT
         // THIS IS THE EFFECT OF HAVING 'DOCTEST_CONFIG_SUPER_FAST_ASSERTS' DEFINED
         // ###################################################################################
         DOCTEST_ASSERT_OUT_OF_TESTS(toString(val));
         DOCTEST_ASSERT_IN_TESTS(toString(val));
     }
References DOCTEST_ASSERT_IN_TESTS, DOCTEST_ASSERT_OUT_OF_TESTS, doctest::assertType::is_false, and doctest::toString().
checkIfShouldThrow()
bool doctest::detail::checkIfShouldThrow (assertType::Enum at)
decomp_assert()
void doctest::detail::decomp_assert (assertType::Enum at, const char * file, int line, const char * expr, Result result)
eq()
template<typename L , typename R > bool doctest::detail::eq (const L & lhs, const R & rhs)
Definition at line 1114 of file doctest.h.
 {
failed_out_of_a_testing_context()
void doctest::detail::failed_out_of_a_testing_context (const AssertData & ad)
ge()
template<typename L , typename R > bool doctest::detail::ge (const L & lhs, const R & rhs)
Definition at line 1119 of file doctest.h.
 {
getTlsOss()
std::ostream* doctest::detail::getTlsOss ()
Referenced by doctest::detail::StringMakerBase< true >::convert().
getTlsOssResult()
String doctest::detail::getTlsOssResult ()
Referenced by doctest::detail::StringMakerBase< true >::convert().
gt()
template<typename L , typename R > bool doctest::detail::gt (const L & lhs, const R & rhs)
Definition at line 1117 of file doctest.h.
 {
instantiationHelper()
template<typename T > int doctest::detail::instantiationHelper (const T &)
Definition at line 1269 of file doctest.h.
 { return 0; }
isDebuggerActive()
bool doctest::detail::isDebuggerActive ()
le()
template<typename L , typename R > bool doctest::detail::le (const L & lhs, const R & rhs)
Definition at line 1118 of file doctest.h.
 {
lt()
template<typename L , typename R > bool doctest::detail::lt (const L & lhs, const R & rhs)
Definition at line 1116 of file doctest.h.
 {
MakeContextScope()
template<typename L > ContextScope<L> doctest::detail::MakeContextScope (const L & lambda)
Definition at line 1528 of file doctest.h.
{
         return ContextScope<L>(lambda);
     }
my_memcpy()
void doctest::detail::my_memcpy (void * dest, const void * src, unsigned num)
ne()
template<typename L , typename R > bool doctest::detail::ne (const L & lhs, const R & rhs)
Definition at line 1115 of file doctest.h.
 {
rawMemoryToString() [1/2]
template<typename T > String doctest::detail::rawMemoryToString (const T & object)
Definition at line 817 of file doctest.h.
{
         return rawMemoryToString(&object, sizeof(object));
     }
References rawMemoryToString().
rawMemoryToString() [2/2]
String doctest::detail::rawMemoryToString (const void * object, unsigned size)
Referenced by doctest::StringMaker< T * >::convert(), doctest::StringMaker< R C::* >::convert(), and rawMemoryToString().
registerExceptionTranslatorImpl()
void doctest::detail::registerExceptionTranslatorImpl (const IExceptionTranslator * et)
Referenced by doctest::registerExceptionTranslator().
registerReporterImpl()
void doctest::detail::registerReporterImpl (const char * name, int prio, reporterCreatorFunc c, bool isReporter)
Referenced by doctest::registerReporter().
regTest()
int doctest::detail::regTest (const TestCase & tc)
reporterCreator()
template<typename Reporter > IReporter* doctest::detail::reporterCreator (const ContextOptions & o)
Definition at line 1712 of file doctest.h.
{
         return new Reporter(o);
     }
setTestSuite()
int doctest::detail::setTestSuite (const TestSuite & ts)
stringifyBinaryExpr()
template<typename L , typename R > String doctest::detail::stringifyBinaryExpr (const L & lhs, const char * op, const R & rhs)
Definition at line 1009 of file doctest.h.
{
         return toString(lhs) + op + toString(rhs);
     }
References doctest::toString().
Referenced by __attribute__().
throwException()
void doctest::detail::throwException ()
toStream() [1/16]
void doctest::detail::toStream (std::ostream * s, bool in)
toStream() [2/16]
void doctest::detail::toStream (std::ostream * s, char in)
toStream() [3/16]
void doctest::detail::toStream (std::ostream * s, char signed in)
toStream() [4/16]
void doctest::detail::toStream (std::ostream * s, char unsigned in)
toStream() [5/16]
template<typename T > void doctest::detail::toStream (std::ostream * s, const T & value)
Definition at line 1461 of file doctest.h.
{
         StringStream<T>::convert(s, value);
     }
References doctest::detail::StringStreamBase< has_insertion_operator< T >::value >::convert().
Referenced by doctest::detail::MessageBuilder::operator<<().
toStream() [6/16]
void doctest::detail::toStream (std::ostream * s, double in)
toStream() [7/16]
void doctest::detail::toStream (std::ostream * s, double long in)
toStream() [8/16]
void doctest::detail::toStream (std::ostream * s, float in)
toStream() [9/16]
void doctest::detail::toStream (std::ostream * s, int in)
toStream() [10/16]
void doctest::detail::toStream (std::ostream * s, int long in)
toStream() [11/16]
void doctest::detail::toStream (std::ostream * s, int long long in)
toStream() [12/16]
void doctest::detail::toStream (std::ostream * s, int long long unsigned in)
toStream() [13/16]
void doctest::detail::toStream (std::ostream * s, int long unsigned in)
toStream() [14/16]
void doctest::detail::toStream (std::ostream * s, int short in)
toStream() [15/16]
void doctest::detail::toStream (std::ostream * s, int short unsigned in)
toStream() [16/16]
void doctest::detail::toStream (std::ostream * s, int unsigned in)
type_to_string()
template<typename T > const char* doctest::detail::type_to_string ()
Definition at line 822 of file doctest.h.
{
         return "<>";
     }
type_to_string< bool >()
template<> const char* doctest::detail::type_to_string< bool > () inline
Definition at line 2584 of file doctest.h.
 {
type_to_string< char >()
template<> const char* doctest::detail::type_to_string< char > () inline
Definition at line 2588 of file doctest.h.
 {
type_to_string< double >()
template<> const char* doctest::detail::type_to_string< double > () inline
Definition at line 2586 of file doctest.h.
 {
type_to_string< float >()
template<> const char* doctest::detail::type_to_string< float > () inline
Definition at line 2585 of file doctest.h.
 {
type_to_string< int >()
template<> const char* doctest::detail::type_to_string< int > () inline
Definition at line 2596 of file doctest.h.
 {
type_to_string< long double >()
template<> const char* doctest::detail::type_to_string< long double > () inline
Definition at line 2587 of file doctest.h.
 {
type_to_string< long int >()
template<> const char* doctest::detail::type_to_string< long int > () inline
Definition at line 2598 of file doctest.h.
 {
type_to_string< long long int >()
template<> const char* doctest::detail::type_to_string< long long int > () inline
Definition at line 2600 of file doctest.h.
 {
type_to_string< short int >()
template<> const char* doctest::detail::type_to_string< short int > () inline
Definition at line 2594 of file doctest.h.
 {
type_to_string< signed char >()
template<> const char* doctest::detail::type_to_string< signed char > () inline
Definition at line 2589 of file doctest.h.
 {
type_to_string< unsigned char >()
template<> const char* doctest::detail::type_to_string< unsigned char > () inline
Definition at line 2590 of file doctest.h.
 {
type_to_string< unsigned int >()
template<> const char* doctest::detail::type_to_string< unsigned int > () inline
Definition at line 2597 of file doctest.h.
 {
type_to_string< unsigned long int >()
template<> const char* doctest::detail::type_to_string< unsigned long int > () inline
Definition at line 2599 of file doctest.h.
 {
type_to_string< unsigned long long int >()
template<> const char* doctest::detail::type_to_string< unsigned long long int > () inline
Definition at line 2601 of file doctest.h.
 {
type_to_string< unsigned short int >()
template<> const char* doctest::detail::type_to_string< unsigned short int > () inline
Definition at line 2595 of file doctest.h.
 {
type_to_string< wchar_t >()
template<> const char* doctest::detail::type_to_string< wchar_t > () inline
Definition at line 2592 of file doctest.h.
 {