Mixed Criticality Orchestrator: httplib Namespace Reference
httplib Namespace Reference
Namespaces
detail
Classes
class Client
class ClientImpl
class ContentReader
class DataSink
struct MultipartFormData
struct MultipartFormDataProvider
struct Request
struct Response
class Result
class Server
class Stream
class TaskQueue
class ThreadPool
Typedefs
using Headers = std::multimap< std::string, std::string, detail::ci >
using Params = std::multimap< std::string, std::string >
using Match = std::smatch
using Progress = std::function< bool(uint64_t current, uint64_t total)>
using ResponseHandler = std::function< bool(const Response &response)>
using MultipartFormDataItems = std::vector< MultipartFormData >
using MultipartFormDataMap = std::multimap< std::string, MultipartFormData >
using ContentProvider = std::function< bool(size_t offset, size_t length, DataSink &sink)>
using ContentProviderWithoutLength = std::function< bool(size_t offset, DataSink &sink)>
using ContentProviderResourceReleaser = std::function< void(bool success)>
using MultipartFormDataProviderItems = std::vector< MultipartFormDataProvider >
using ContentReceiverWithProgress = std::function< bool(const char *data, size_t data_length, uint64_t offset, uint64_t total_length)>
using ContentReceiver = std::function< bool(const char *data, size_t data_length)>
using MultipartContentHeader = std::function< bool(const MultipartFormData &file)>
using Range = std::pair< ssize_t, ssize_t >
using Ranges = std::vector< Range >
using Logger = std::function< void(const Request &, const Response &)>
using SocketOptions = std::function< void(socket_t sock)>
Enumerations
enum StatusCode {
Continue_100 = 100, SwitchingProtocol_101 = 101, Processing_102 = 102, EarlyHints_103 = 103,
OK_200 = 200, Created_201 = 201, Accepted_202 = 202, NonAuthoritativeInformation_203 = 203,
NoContent_204 = 204, ResetContent_205 = 205, PartialContent_206 = 206, MultiStatus_207 = 207,
AlreadyReported_208 = 208, IMUsed_226 = 226, MultipleChoices_300 = 300, MovedPermanently_301 = 301,
Found_302 = 302, SeeOther_303 = 303, NotModified_304 = 304, UseProxy_305 = 305,
unused_306 = 306, TemporaryRedirect_307 = 307, PermanentRedirect_308 = 308, BadRequest_400 = 400,
Unauthorized_401 = 401, PaymentRequired_402 = 402, Forbidden_403 = 403, NotFound_404 = 404,
MethodNotAllowed_405 = 405, NotAcceptable_406 = 406, ProxyAuthenticationRequired_407 = 407, RequestTimeout_408 = 408,
Conflict_409 = 409, Gone_410 = 410, LengthRequired_411 = 411, PreconditionFailed_412 = 412,
PayloadTooLarge_413 = 413, UriTooLong_414 = 414, UnsupportedMediaType_415 = 415, RangeNotSatisfiable_416 = 416,
ExpectationFailed_417 = 417, ImATeapot_418 = 418, MisdirectedRequest_421 = 421, UnprocessableContent_422 = 422,
Locked_423 = 423, FailedDependency_424 = 424, TooEarly_425 = 425, UpgradeRequired_426 = 426,
PreconditionRequired_428 = 428, TooManyRequests_429 = 429, RequestHeaderFieldsTooLarge_431 = 431, UnavailableForLegalReasons_451 = 451,
InternalServerError_500 = 500, NotImplemented_501 = 501, BadGateway_502 = 502, ServiceUnavailable_503 = 503,
GatewayTimeout_504 = 504, HttpVersionNotSupported_505 = 505, VariantAlsoNegotiates_506 = 506, InsufficientStorage_507 = 507,
LoopDetected_508 = 508, NotExtended_510 = 510, NetworkAuthenticationRequired_511 = 511
}
enum Error {
Error::Success = 0, Error::Unknown, Error::Connection, Error::BindIPAddress,
Error::Read, Error::Write, Error::ExceedRedirectCount, Error::Canceled,
Error::SSLConnection, Error::SSLLoadingCerts, Error::SSLServerVerification, Error::UnsupportedMultipartBoundaryChars,
Error::Compression, Error::ConnectionTimeout, Error::ProxyConnection, Error::SSLPeerCouldBeClosed_
}
Functions
void default_socket_options (socket_t sock)
const char * status_message (int status)
std::string get_bearer_token_auth (const Request &req)
std::string to_string (Error error)
std::ostream & operator<< (std::ostream &os, const Error &obj)
std::string hosted_at (const std::string &hostname)
void hosted_at (const std::string &hostname, std::vector< std::string > &addrs)
std::string append_query_params (const std::string &path, const Params &params)
std::pair< std::string, std::string > make_range_header (const Ranges &ranges)
std::pair< std::string, std::string > make_basic_authentication_header (const std::string &username, const std::string &password, bool is_proxy=false)
std::pair< std::string, std::string > make_bearer_token_authentication_header (const std::string &token, bool is_proxy=false)
Typedef Documentation
ContentProvider
using httplib::ContentProvider = typedef std::function<bool(size_t offset, size_t length, DataSink &sink)>
Definition at line 483 of file httplib.h.
ContentProviderResourceReleaser
using httplib::ContentProviderResourceReleaser = typedef std::function<void(bool success)>
Definition at line 488 of file httplib.h.
ContentProviderWithoutLength
using httplib::ContentProviderWithoutLength = typedef std::function<bool(size_t offset, DataSink &sink)>
Definition at line 486 of file httplib.h.
ContentReceiver
using httplib::ContentReceiver = typedef std::function<bool(const char *data, size_t data_length)>
Definition at line 503 of file httplib.h.
ContentReceiverWithProgress
using httplib::ContentReceiverWithProgress = typedef std::function<bool(const char *data, size_t data_length, uint64_t offset, uint64_t total_length)>
Definition at line 500 of file httplib.h.
Headers
using httplib::Headers = typedef std::multimap<std::string, std::string, detail::ci>
Definition at line 430 of file httplib.h.
Logger
using httplib::Logger = typedef std::function<void(const Request &, const Response &)>
Definition at line 745 of file httplib.h.
Match
using httplib::Match = typedef std::smatch
Definition at line 433 of file httplib.h.
MultipartContentHeader
using httplib::MultipartContentHeader = typedef std::function<bool(const MultipartFormData &file)>
Definition at line 506 of file httplib.h.
MultipartFormDataItems
using httplib::MultipartFormDataItems = typedef std::vector<MultipartFormData>
Definition at line 446 of file httplib.h.
MultipartFormDataMap
using httplib::MultipartFormDataMap = typedef std::multimap<std::string, MultipartFormData>
Definition at line 447 of file httplib.h.
MultipartFormDataProviderItems
using httplib::MultipartFormDataProviderItems = typedef std::vector<MultipartFormDataProvider>
Definition at line 496 of file httplib.h.
Params
using httplib::Params = typedef std::multimap<std::string, std::string>
Definition at line 432 of file httplib.h.
Progress
using httplib::Progress = typedef std::function<bool(uint64_t current, uint64_t total)>
Definition at line 435 of file httplib.h.
Range
using httplib::Range = typedef std::pair<ssize_t, ssize_t>
Definition at line 531 of file httplib.h.
Ranges
using httplib::Ranges = typedef std::vector<Range>
Definition at line 532 of file httplib.h.
ResponseHandler
using httplib::ResponseHandler = typedef std::function<bool(const Response &response)>
Definition at line 438 of file httplib.h.
SocketOptions
using httplib::SocketOptions = typedef std::function<void(socket_t sock)>
Definition at line 747 of file httplib.h.
Enumeration Type Documentation
Error
enum httplib::Error strong
Enumerator
Success
Unknown
Connection
BindIPAddress
Read
Write
ExceedRedirectCount
Canceled
SSLConnection
SSLLoadingCerts
SSLServerVerification
UnsupportedMultipartBoundaryChars
Compression
ConnectionTimeout
ProxyConnection
SSLPeerCouldBeClosed_
Definition at line 1028 of file httplib.h.
                  {
   Success = 0,
   Unknown,
   Connection,
   BindIPAddress,
   Read,
   Write,
   ExceedRedirectCount,
   Canceled,
   SSLConnection,
   SSLLoadingCerts,
   SSLServerVerification,
   UnsupportedMultipartBoundaryChars,
   Compression,
   ConnectionTimeout,
   ProxyConnection,
   // For internal use only
   SSLPeerCouldBeClosed_,
 };
StatusCode
enum httplib::StatusCode
Enumerator
Continue_100
SwitchingProtocol_101
Processing_102
EarlyHints_103
OK_200
Created_201
Accepted_202
NonAuthoritativeInformation_203
NoContent_204
ResetContent_205
PartialContent_206
MultiStatus_207
AlreadyReported_208
IMUsed_226
MultipleChoices_300
MovedPermanently_301
Found_302
SeeOther_303
NotModified_304
UseProxy_305
unused_306
TemporaryRedirect_307
PermanentRedirect_308
BadRequest_400
Unauthorized_401
PaymentRequired_402
Forbidden_403
NotFound_404
MethodNotAllowed_405
NotAcceptable_406
ProxyAuthenticationRequired_407
RequestTimeout_408
Conflict_409
Gone_410
LengthRequired_411
PreconditionFailed_412
PayloadTooLarge_413
UriTooLong_414
UnsupportedMediaType_415
RangeNotSatisfiable_416
ExpectationFailed_417
ImATeapot_418
MisdirectedRequest_421
UnprocessableContent_422
Locked_423
FailedDependency_424
TooEarly_425
UpgradeRequired_426
PreconditionRequired_428
TooManyRequests_429
RequestHeaderFieldsTooLarge_431
UnavailableForLegalReasons_451
InternalServerError_500
NotImplemented_501
BadGateway_502
ServiceUnavailable_503
GatewayTimeout_504
HttpVersionNotSupported_505
VariantAlsoNegotiates_506
InsufficientStorage_507
LoopDetected_508
NotExtended_510
NetworkAuthenticationRequired_511
Definition at line 355 of file httplib.h.
                 {
   // Information responses
   Continue_100 = 100,
   SwitchingProtocol_101 = 101,
   Processing_102 = 102,
   EarlyHints_103 = 103,
   // Successful responses
   OK_200 = 200,
   Created_201 = 201,
   Accepted_202 = 202,
   NonAuthoritativeInformation_203 = 203,
   NoContent_204 = 204,
   ResetContent_205 = 205,
   PartialContent_206 = 206,
   MultiStatus_207 = 207,
   AlreadyReported_208 = 208,
   IMUsed_226 = 226,
   // Redirection messages
   MultipleChoices_300 = 300,
   MovedPermanently_301 = 301,
   Found_302 = 302,
   SeeOther_303 = 303,
   NotModified_304 = 304,
   UseProxy_305 = 305,
   unused_306 = 306,
   TemporaryRedirect_307 = 307,
   PermanentRedirect_308 = 308,
   // Client error responses
   BadRequest_400 = 400,
   Unauthorized_401 = 401,
   PaymentRequired_402 = 402,
   Forbidden_403 = 403,
   NotFound_404 = 404,
   MethodNotAllowed_405 = 405,
   NotAcceptable_406 = 406,
   ProxyAuthenticationRequired_407 = 407,
   RequestTimeout_408 = 408,
   Conflict_409 = 409,
   Gone_410 = 410,
   LengthRequired_411 = 411,
   PreconditionFailed_412 = 412,
   PayloadTooLarge_413 = 413,
   UriTooLong_414 = 414,
   UnsupportedMediaType_415 = 415,
   RangeNotSatisfiable_416 = 416,
   ExpectationFailed_417 = 417,
   ImATeapot_418 = 418,
   MisdirectedRequest_421 = 421,
   UnprocessableContent_422 = 422,
   Locked_423 = 423,
   FailedDependency_424 = 424,
   TooEarly_425 = 425,
   UpgradeRequired_426 = 426,
   PreconditionRequired_428 = 428,
   TooManyRequests_429 = 429,
   RequestHeaderFieldsTooLarge_431 = 431,
   UnavailableForLegalReasons_451 = 451,
   // Server error responses
   InternalServerError_500 = 500,
   NotImplemented_501 = 501,
   BadGateway_502 = 502,
   ServiceUnavailable_503 = 503,
   GatewayTimeout_504 = 504,
   HttpVersionNotSupported_505 = 505,
   VariantAlsoNegotiates_506 = 506,
   InsufficientStorage_507 = 507,
   LoopDetected_508 = 508,
   NotExtended_510 = 510,
   NetworkAuthenticationRequired_511 = 511,
 };
Function Documentation
append_query_params()
std::string httplib::append_query_params (const std::string & path, const Params & params) inline
Definition at line 5245 of file httplib.h.
{
   std::string path_with_query = path;
   const static std::regex re("[^?]+\\?.*");
   auto delm = std::regex_match(path, re) ? '&' : '?';
   path_with_query += delm + detail::params_to_query_str(params);
   return path_with_query;
 }
References httplib::detail::params_to_query_str().
Referenced by httplib::ClientImpl::Get().
default_socket_options()
void httplib::default_socket_options (socket_t sock) inline
Definition at line 1859 of file httplib.h.
{
   int yes = 1;
 #ifdef _WIN32
   setsockopt(sock, SOL_SOCKET, SO_REUSEADDR,
              reinterpret_cast<const char *>(&yes), sizeof(yes));
   setsockopt(sock, SOL_SOCKET, SO_EXCLUSIVEADDRUSE,
              reinterpret_cast<const char *>(&yes), sizeof(yes));
 #else
 #ifdef SO_REUSEPORT
   setsockopt(sock, SOL_SOCKET, SO_REUSEPORT,
              reinterpret_cast<const void *>(&yes), sizeof(yes));
 #else
   setsockopt(sock, SOL_SOCKET, SO_REUSEADDR,
              reinterpret_cast<const void *>(&yes), sizeof(yes));
 #endif
 #endif
 }
get_bearer_token_auth()
std::string httplib::get_bearer_token_auth (const Request & req) inline
Definition at line 1953 of file httplib.h.
{
   if (req.has_header("Authorization")) {
     static std::string BearerHeaderPrefix = "Bearer ";
     return req.get_header_value("Authorization")
         .substr(BearerHeaderPrefix.length());
   }
   return "";
 }
References httplib::Request::get_header_value(), and httplib::Request::has_header().
hosted_at() [1/2]
std::string httplib::hosted_at (const std::string & hostname) inline
Definition at line 5207 of file httplib.h.
{
   std::vector<std::string> addrs;
   hosted_at(hostname, addrs);
   if (addrs.empty()) { return std::string(); }
   return addrs[0];
 }
References hosted_at().
hosted_at() [2/2]
void httplib::hosted_at (const std::string & hostname, std::vector< std::string > & addrs) inline
Definition at line 5214 of file httplib.h.
{
   struct addrinfo hints;
   struct addrinfo *result;
   memset(&hints, 0, sizeof(struct addrinfo));
   hints.ai_family = AF_UNSPEC;
   hints.ai_socktype = SOCK_STREAM;
   hints.ai_protocol = 0;
   if (getaddrinfo(hostname.c_str(), nullptr, &hints, &result)) {
 #if defined __linux__ && !defined __ANDROID__
     res_init();
 #endif
     return;
   }
   for (auto rp = result; rp; rp = rp->ai_next) {
     const auto &addr =
         *reinterpret_cast<struct sockaddr_storage *>(rp->ai_addr);
     std::string ip;
     auto dummy = -1;
     if (detail::get_ip_and_port(addr, sizeof(struct sockaddr_storage), ip,
                                 dummy)) {
       addrs.push_back(ip);
     }
   }
   freeaddrinfo(result);
 }
References addr, httplib::detail::get_ip_and_port(), and result.
Referenced by hosted_at().
make_basic_authentication_header()
std::pair< std::string, std::string > httplib::make_basic_authentication_header (const std::string & username, const std::string & password, bool is_proxy = false) inline
Definition at line 5270 of file httplib.h.
{
   auto field = "Basic " + detail::base64_encode(username + ":" + password);
   auto key = is_proxy ? "Proxy-Authorization" : "Authorization";
   return std::make_pair(key, std::move(field));
 }
References httplib::detail::base64_encode().
Referenced by httplib::ClientImpl::write_request().
make_bearer_token_authentication_header()
std::pair<std::string, std::string> httplib::make_bearer_token_authentication_header (const std::string & token, bool is_proxy = false) inline
Definition at line 5278 of file httplib.h.
{
   auto field = "Bearer " + token;
   auto key = is_proxy ? "Proxy-Authorization" : "Authorization";
   return std::make_pair(key, std::move(field));
 }
Referenced by httplib::ClientImpl::write_request().
make_range_header()
std::pair< std::string, std::string > httplib::make_range_header (const Ranges & ranges) inline
Definition at line 5256 of file httplib.h.
{
   std::string field = "bytes=";
   auto i = 0;
   for (const auto &r : ranges) {
     if (i != 0) { field += ", "; }
     if (r.first != -1) { field += std::to_string(r.first); }
     field += '-';
     if (r.second != -1) { field += std::to_string(r.second); }
     i++;
   }
   return std::make_pair("Range", std::move(field));
 }
References to_string().
operator<<()
std::ostream & httplib::operator<< (std::ostream & os, const Error & obj) inline
Definition at line 2010 of file httplib.h.
{
   os << to_string(obj);
   os << " (" << static_cast<std::underlying_type<Error>::type>(obj) << ')';
   return os;
 }
References to_string().
status_message()
const char * httplib::status_message (int status) inline
Definition at line 1877 of file httplib.h.
{
   switch (status) {
   case StatusCode::Continue_100: return "Continue";
   case StatusCode::SwitchingProtocol_101: return "Switching Protocol";
   case StatusCode::Processing_102: return "Processing";
   case StatusCode::EarlyHints_103: return "Early Hints";
   case StatusCode::OK_200: return "OK";
   case StatusCode::Created_201: return "Created";
   case StatusCode::Accepted_202: return "Accepted";
   case StatusCode::NonAuthoritativeInformation_203:
     return "Non-Authoritative Information";
   case StatusCode::NoContent_204: return "No Content";
   case StatusCode::ResetContent_205: return "Reset Content";
   case StatusCode::PartialContent_206: return "Partial Content";
   case StatusCode::MultiStatus_207: return "Multi-Status";
   case StatusCode::AlreadyReported_208: return "Already Reported";
   case StatusCode::IMUsed_226: return "IM Used";
   case StatusCode::MultipleChoices_300: return "Multiple Choices";
   case StatusCode::MovedPermanently_301: return "Moved Permanently";
   case StatusCode::Found_302: return "Found";
   case StatusCode::SeeOther_303: return "See Other";
   case StatusCode::NotModified_304: return "Not Modified";
   case StatusCode::UseProxy_305: return "Use Proxy";
   case StatusCode::unused_306: return "unused";
   case StatusCode::TemporaryRedirect_307: return "Temporary Redirect";
   case StatusCode::PermanentRedirect_308: return "Permanent Redirect";
   case StatusCode::BadRequest_400: return "Bad Request";
   case StatusCode::Unauthorized_401: return "Unauthorized";
   case StatusCode::PaymentRequired_402: return "Payment Required";
   case StatusCode::Forbidden_403: return "Forbidden";
   case StatusCode::NotFound_404: return "Not Found";
   case StatusCode::MethodNotAllowed_405: return "Method Not Allowed";
   case StatusCode::NotAcceptable_406: return "Not Acceptable";
   case StatusCode::ProxyAuthenticationRequired_407:
     return "Proxy Authentication Required";
   case StatusCode::RequestTimeout_408: return "Request Timeout";
   case StatusCode::Conflict_409: return "Conflict";
   case StatusCode::Gone_410: return "Gone";
   case StatusCode::LengthRequired_411: return "Length Required";
   case StatusCode::PreconditionFailed_412: return "Precondition Failed";
   case StatusCode::PayloadTooLarge_413: return "Payload Too Large";
   case StatusCode::UriTooLong_414: return "URI Too Long";
   case StatusCode::UnsupportedMediaType_415: return "Unsupported Media Type";
   case StatusCode::RangeNotSatisfiable_416: return "Range Not Satisfiable";
   case StatusCode::ExpectationFailed_417: return "Expectation Failed";
   case StatusCode::ImATeapot_418: return "I'm a teapot";
   case StatusCode::MisdirectedRequest_421: return "Misdirected Request";
   case StatusCode::UnprocessableContent_422: return "Unprocessable Content";
   case StatusCode::Locked_423: return "Locked";
   case StatusCode::FailedDependency_424: return "Failed Dependency";
   case StatusCode::TooEarly_425: return "Too Early";
   case StatusCode::UpgradeRequired_426: return "Upgrade Required";
   case StatusCode::PreconditionRequired_428: return "Precondition Required";
   case StatusCode::TooManyRequests_429: return "Too Many Requests";
   case StatusCode::RequestHeaderFieldsTooLarge_431:
     return "Request Header Fields Too Large";
   case StatusCode::UnavailableForLegalReasons_451:
     return "Unavailable For Legal Reasons";
   case StatusCode::NotImplemented_501: return "Not Implemented";
   case StatusCode::BadGateway_502: return "Bad Gateway";
   case StatusCode::ServiceUnavailable_503: return "Service Unavailable";
   case StatusCode::GatewayTimeout_504: return "Gateway Timeout";
   case StatusCode::HttpVersionNotSupported_505:
     return "HTTP Version Not Supported";
   case StatusCode::VariantAlsoNegotiates_506: return "Variant Also Negotiates";
   case StatusCode::InsufficientStorage_507: return "Insufficient Storage";
   case StatusCode::LoopDetected_508: return "Loop Detected";
   case StatusCode::NotExtended_510: return "Not Extended";
   case StatusCode::NetworkAuthenticationRequired_511:
     return "Network Authentication Required";
   default:
   case StatusCode::InternalServerError_500: return "Internal Server Error";
   }
 }
References Accepted_202, AlreadyReported_208, BadGateway_502, BadRequest_400, Conflict_409, Continue_100, Created_201, EarlyHints_103, ExpectationFailed_417, FailedDependency_424, Forbidden_403, Found_302, GatewayTimeout_504, Gone_410, HttpVersionNotSupported_505, ImATeapot_418, IMUsed_226, InsufficientStorage_507, InternalServerError_500, LengthRequired_411, Locked_423, LoopDetected_508, MethodNotAllowed_405, MisdirectedRequest_421, MovedPermanently_301, MultipleChoices_300, MultiStatus_207, NetworkAuthenticationRequired_511, NoContent_204, NonAuthoritativeInformation_203, NotAcceptable_406, NotExtended_510, NotFound_404, NotImplemented_501, NotModified_304, OK_200, PartialContent_206, PayloadTooLarge_413, PaymentRequired_402, PermanentRedirect_308, PreconditionFailed_412, PreconditionRequired_428, Processing_102, ProxyAuthenticationRequired_407, RangeNotSatisfiable_416, RequestHeaderFieldsTooLarge_431, RequestTimeout_408, ResetContent_205, SeeOther_303, ServiceUnavailable_503, SwitchingProtocol_101, TemporaryRedirect_307, TooEarly_425, TooManyRequests_429, Unauthorized_401, UnavailableForLegalReasons_451, UnprocessableContent_422, UnsupportedMediaType_415, unused_306, UpgradeRequired_426, UriTooLong_414, UseProxy_305, and VariantAlsoNegotiates_506.
Referenced by httplib::Server::process_request(), and httplib::Server::write_response_core().
to_string()
std::string httplib::to_string (Error error) inline
Definition at line 1986 of file httplib.h.
{
   switch (error) {
   case Error::Success: return "Success (no error)";
   case Error::Connection: return "Could not establish connection";
   case Error::BindIPAddress: return "Failed to bind IP address";
   case Error::Read: return "Failed to read connection";
   case Error::Write: return "Failed to write connection";
   case Error::ExceedRedirectCount: return "Maximum redirect count exceeded";
   case Error::Canceled: return "Connection handling canceled";
   case Error::SSLConnection: return "SSL connection failed";
   case Error::SSLLoadingCerts: return "SSL certificate loading failed";
   case Error::SSLServerVerification: return "SSL server verification failed";
   case Error::UnsupportedMultipartBoundaryChars:
     return "Unsupported HTTP multipart boundary characters";
   case Error::Compression: return "Compression failed";
   case Error::ConnectionTimeout: return "Connection timed out";
   case Error::ProxyConnection: return "Proxy connection failed";
   case Error::Unknown: return "Unknown";
   default: break;
   }
   return "Invalid";
 }
References BindIPAddress, Canceled, Compression, Connection, ConnectionTimeout, ExceedRedirectCount, ProxyConnection, Read, SSLConnection, SSLLoadingCerts, SSLServerVerification, Success, Unknown, UnsupportedMultipartBoundaryChars, and Write.
Referenced by allocateQmResources(), httplib::Server::apply_ranges(), ResourceMonitorSubject::AverageResourceUtilization(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_array_size(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_entry_header_size(), fuzzer::Fuzzer::CrashResistantMerge(), nlohmann::detail::parse_error::create(), httplib::detail::create_socket(), nlohmann::detail::serializer< BasicJsonType >::dump_escaped(), BluechiUnitUsageCommand::Execute(), nlohmann::json_pointer< BasicJsonType >::flatten(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_bson_string(), nlohmann::json_pointer< BasicJsonType >::get_checked(), nlohmann::json_pointer< BasicJsonType >::get_unchecked(), nlohmann::detail::int_to_string(), int_to_string(), httplib::detail::make_content_range_header_field(), make_range_header(), nlohmann::detail::exception::name(), sax_event_consumer::number_integer(), sax_event_consumer::number_unsigned(), nlohmann::json_pointer< BasicJsonType >::operator/=(), operator<<(), nlohmann::detail::parse_error::position_string(), httplib::Server::process_request(), SECTION(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::start_array(), nlohmann::detail::json_sax_dom_callback_parser< BasicJsonType >::start_array(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::start_object(), nlohmann::detail::json_sax_dom_callback_parser< BasicJsonType >::start_object(), TEST_CASE(), TEST_CASE_TEMPLATE(), tryLockCore(), unlockCore(), update_qm_available_resource(), updateInitialSystemResources(), updateResources(), fuzzer::WorkerThread(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_array(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_unsigned(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number_with_ubjson_prefix(), and httplib::ClientImpl::write_request().