Mixed Criticality Orchestrator: benchmark Namespace Reference
benchmark Namespace Reference
Namespaces
cycleclock
internal
Classes
class Barrier
class BenchmarkReporter
struct ChooseClockType
class ConsoleReporter
class Counter
struct CPUInfo
class CSVReporter
class Fixture
class JSONReporter
struct LeastSq
class Mutex
class MutexLock
class Regex
class State
struct Statistics
Typedefs
typedef std::map< std::string, Counter > UserCounters
typedef double() BigOFunc(int64_t)
typedef double() StatisticsFunc(const std::vector< double > &)
typedef std::condition_variable Condition
Enumerations
enum TimeUnit { kNanosecond, kMicrosecond, kMillisecond }
enum BigO {
oNone, o1, oN, oNSquared,
oNCubed, oLogN, oNLogN, oAuto,
oLambda
}
enum LogColor {
COLOR_DEFAULT, COLOR_RED, COLOR_GREEN, COLOR_YELLOW,
COLOR_BLUE, COLOR_MAGENTA, COLOR_CYAN, COLOR_WHITE
}
Functions
void Initialize (int *argc, char **argv)
bool ReportUnrecognizedArguments (int argc, char **argv)
size_t RunSpecifiedBenchmarks ()
size_t RunSpecifiedBenchmarks (BenchmarkReporter *console_reporter)
size_t RunSpecifiedBenchmarks (BenchmarkReporter *console_reporter, BenchmarkReporter *file_reporter)
template<class Tp >
void DoNotOptimize (Tp const &value)
internal::Benchmark * RegisterBenchmark (const char *name, internal::Function *fn)
void ClearRegisteredBenchmarks ()
const char * GetTimeUnitString (TimeUnit unit)
double GetTimeUnitMultiplier (TimeUnit unit)
std::string FormatString (const char *msg, va_list args)
std::string FormatString (const char *msg,...)
void ColorPrintf (std::ostream &out, LogColor color, const char *fmt, va_list args)
void ColorPrintf (std::ostream &out, LogColor color, const char *fmt,...)
bool IsColorTerminal ()
bool ParseInt32 (const std::string &src_text, const char *str, int32_t *value)
bool BoolFromEnv (const char *flag, bool default_val)
int32_t Int32FromEnv (const char *flag, int32_t default_val)
double DoubleFromEnv (const char *flag, double default_val)
const char * StringFromEnv (const char *flag, const char *default_val)
bool ParseBoolFlag (const char *str, const char *flag, bool *value)
bool ParseInt32Flag (const char *str, const char *flag, int32_t *value)
bool ParseDoubleFlag (const char *str, const char *flag, double *value)
bool ParseStringFlag (const char *str, const char *flag, std::string *value)
bool IsFlag (const char *str, const char *flag)
bool IsTruthyFlagValue (const std::string &value)
std::vector< BenchmarkReporter::Run > ComputeBigO (const std::vector< BenchmarkReporter::Run > &reports)
std::string GetBigOString (BigO complexity)
void SleepForMilliseconds (int milliseconds)
void SleepForSeconds (double seconds)
std::vector< BenchmarkReporter::Run > ComputeStats (const std::vector< BenchmarkReporter::Run > &reports)
double StatisticsMean (const std::vector< double > &v)
double StatisticsMedian (const std::vector< double > &v)
double StatisticsStdDev (const std::vector< double > &v)
void AppendHumanReadable (int n, std::string *str)
std::string HumanReadableNumber (double n, double one_k=1024.0)
std::string StrFormat (const char *format,...)
std::ostream & StrCatImp (std::ostream &out) BENCHMARK_NOEXCEPT
template<class First , class... Rest>
std::ostream & StrCatImp (std::ostream &out, First &&f, Rest &&... rest)
template<class... Args>
std::string StrCat (Args &&... args)
void ReplaceAll (std::string *str, const std::string &from, const std::string &to)
double ProcessCPUUsage ()
double ChildrenCPUUsage ()
double ThreadCPUUsage ()
double ChronoClockNow ()
std::string LocalDateTimeString ()
Variables
const int kNumMillisPerSecond = 1000
const int kNumMicrosPerMilli = 1000
const int kNumMicrosPerSecond = kNumMillisPerSecond * 1000
const int kNumNanosPerMicro = 1000
const int kNumNanosPerSecond = kNumNanosPerMicro * kNumMicrosPerSecond
Typedef Documentation
BigOFunc
typedef double() benchmark::BigOFunc(int64_t)
Definition at line 388 of file benchmark.h.
Condition
typedef std::condition_variable benchmark::Condition
Definition at line 69 of file mutex.h.
StatisticsFunc
typedef double() benchmark::StatisticsFunc(const std::vector< double > &)
Definition at line 392 of file benchmark.h.
UserCounters
typedef std::map<std::string, Counter> benchmark::UserCounters
Definition at line 373 of file benchmark.h.
Enumeration Type Documentation
BigO
enum benchmark::BigO
Enumerator
oNone
o1
oN
oNSquared
oNCubed
oLogN
oNLogN
oAuto
oLambda
Definition at line 384 of file benchmark.h.
 { oNone, o1, oN, oNSquared, oNCubed, oLogN, oNLogN, oAuto, oLambda };
LogColor
enum benchmark::LogColor
Enumerator
COLOR_DEFAULT
COLOR_RED
COLOR_GREEN
COLOR_YELLOW
COLOR_BLUE
COLOR_MAGENTA
COLOR_CYAN
COLOR_WHITE
Definition at line 9 of file colorprint.h.
               {
   COLOR_DEFAULT,
   COLOR_RED,
   COLOR_GREEN,
   COLOR_YELLOW,
   COLOR_BLUE,
   COLOR_MAGENTA,
   COLOR_CYAN,
   COLOR_WHITE
 };
TimeUnit
enum benchmark::TimeUnit
Enumerator
kNanosecond
kMicrosecond
kMillisecond
Definition at line 378 of file benchmark.h.
 { kNanosecond, kMicrosecond, kMillisecond };
Function Documentation
AppendHumanReadable()
void benchmark::AppendHumanReadable (int n, std::string * str)
BoolFromEnv()
bool benchmark::BoolFromEnv (const char * flag, bool default_val)
ChildrenCPUUsage()
double benchmark::ChildrenCPUUsage ()
ChronoClockNow()
double benchmark::ChronoClockNow () inline
Definition at line 38 of file timers.h.
{
   typedef ChooseClockType::type ClockType;
   using FpSeconds = std::chrono::duration<double, std::chrono::seconds::period>;
   return FpSeconds(ClockType::now().time_since_epoch()).count();
 }
Referenced by benchmark::internal::ThreadTimer::StartTimer(), and benchmark::internal::ThreadTimer::StopTimer().
ClearRegisteredBenchmarks()
void benchmark::ClearRegisteredBenchmarks ()
ColorPrintf() [1/2]
void benchmark::ColorPrintf (std::ostream & out, LogColor color, const char * fmt, va_list args)
ColorPrintf() [2/2]
void benchmark::ColorPrintf (std::ostream & out, LogColor color, const char * fmt, ...)
ComputeBigO()
std::vector<BenchmarkReporter::Run> benchmark::ComputeBigO (const std::vector< BenchmarkReporter::Run > & reports)
ComputeStats()
std::vector<BenchmarkReporter::Run> benchmark::ComputeStats (const std::vector< BenchmarkReporter::Run > & reports)
DoNotOptimize()
template<class Tp > void benchmark::DoNotOptimize (Tp const & value) inline
Definition at line 337 of file benchmark.h.
{
   internal::UseCharPointer(&reinterpret_cast<char const volatile&>(value));
 }
References benchmark::internal::UseCharPointer().
DoubleFromEnv()
double benchmark::DoubleFromEnv (const char * flag, double default_val)
FormatString() [1/2]
std::string benchmark::FormatString (const char * msg, va_list args)
FormatString() [2/2]
std::string benchmark::FormatString (const char * msg, ...)
GetBigOString()
std::string benchmark::GetBigOString (BigO complexity)
GetTimeUnitMultiplier()
double benchmark::GetTimeUnitMultiplier (TimeUnit unit) inline
Definition at line 1442 of file benchmark.h.
{
   switch (unit) {
     case kMillisecond:
       return 1e3;
     case kMicrosecond:
       return 1e6;
     case kNanosecond:
     default:
       return 1e9;
   }
 }
References kMicrosecond, kMillisecond, and kNanosecond.
GetTimeUnitString()
const char* benchmark::GetTimeUnitString (TimeUnit unit) inline
Definition at line 1430 of file benchmark.h.
{
   switch (unit) {
     case kMillisecond:
       return "ms";
     case kMicrosecond:
       return "us";
     case kNanosecond:
     default:
       return "ns";
   }
 }
References kMicrosecond, kMillisecond, and kNanosecond.
HumanReadableNumber()
std::string benchmark::HumanReadableNumber (double n, double one_k = 1024.0)
Initialize()
void benchmark::Initialize (int * argc, char ** argv)
Int32FromEnv()
int32_t benchmark::Int32FromEnv (const char * flag, int32_t default_val)
IsColorTerminal()
bool benchmark::IsColorTerminal ()
IsFlag()
bool benchmark::IsFlag (const char * str, const char * flag)
IsTruthyFlagValue()
bool benchmark::IsTruthyFlagValue (const std::string & value)
LocalDateTimeString()
std::string benchmark::LocalDateTimeString ()
ParseBoolFlag()
bool benchmark::ParseBoolFlag (const char * str, const char * flag, bool * value)
ParseDoubleFlag()
bool benchmark::ParseDoubleFlag (const char * str, const char * flag, double * value)
ParseInt32()
bool benchmark::ParseInt32 (const std::string & src_text, const char * str, int32_t * value)
ParseInt32Flag()
bool benchmark::ParseInt32Flag (const char * str, const char * flag, int32_t * value)
ParseStringFlag()
bool benchmark::ParseStringFlag (const char * str, const char * flag, std::string * value)
ProcessCPUUsage()
double benchmark::ProcessCPUUsage ()
RegisterBenchmark()
internal::Benchmark * benchmark::RegisterBenchmark (const char * name, internal::Function * fn) inline
Definition at line 972 of file benchmark.h.
{
   return internal::RegisterBenchmarkInternal(
       ::new internal::FunctionBenchmark(name, fn));
 }
References benchmark::internal::RegisterBenchmarkInternal().
ReplaceAll()
void benchmark::ReplaceAll (std::string * str, const std::string & from, const std::string & to)
ReportUnrecognizedArguments()
bool benchmark::ReportUnrecognizedArguments (int argc, char ** argv)
RunSpecifiedBenchmarks() [1/3]
size_t benchmark::RunSpecifiedBenchmarks ()
RunSpecifiedBenchmarks() [2/3]
size_t benchmark::RunSpecifiedBenchmarks (BenchmarkReporter * console_reporter)
RunSpecifiedBenchmarks() [3/3]
size_t benchmark::RunSpecifiedBenchmarks (BenchmarkReporter * console_reporter, BenchmarkReporter * file_reporter)
SleepForMilliseconds()
void benchmark::SleepForMilliseconds (int milliseconds)
SleepForSeconds()
void benchmark::SleepForSeconds (double seconds)
StatisticsMean()
double benchmark::StatisticsMean (const std::vector< double > & v)
StatisticsMedian()
double benchmark::StatisticsMedian (const std::vector< double > & v)
StatisticsStdDev()
double benchmark::StatisticsStdDev (const std::vector< double > & v)
StrCat()
template<class... Args> std::string benchmark::StrCat (Args &&... args) inline
Definition at line 29 of file string_util.h.
{
   std::ostringstream ss;
   StrCatImp(ss, std::forward<Args>(args)...);
   return ss.str();
 }
References ss, and StrCatImp().
StrCatImp() [1/2]
std::ostream& benchmark::StrCatImp (std::ostream & out) inline
Definition at line 17 of file string_util.h.
{
   return out;
 }
Referenced by StrCat(), and StrCatImp().
StrCatImp() [2/2]
template<class First , class... Rest> std::ostream& benchmark::StrCatImp (std::ostream & out, First && f, Rest &&... rest) inline
Definition at line 22 of file string_util.h.
{
   out << std::forward<First>(f);
   return StrCatImp(out, std::forward<Rest>(rest)...);
 }
References StrCatImp().
StrFormat()
std::string benchmark::StrFormat (const char * format, ...)
StringFromEnv()
const char* benchmark::StringFromEnv (const char * flag, const char * default_val)
ThreadCPUUsage()
double benchmark::ThreadCPUUsage ()
Referenced by benchmark::internal::ThreadTimer::StartTimer(), and benchmark::internal::ThreadTimer::StopTimer().
Variable Documentation
kNumMicrosPerMilli
const int benchmark::kNumMicrosPerMilli = 1000
Definition at line 6 of file sleep.h.
kNumMicrosPerSecond
const int benchmark::kNumMicrosPerSecond = kNumMillisPerSecond * 1000
Definition at line 7 of file sleep.h.
kNumMillisPerSecond
const int benchmark::kNumMillisPerSecond = 1000
Definition at line 5 of file sleep.h.
kNumNanosPerMicro
const int benchmark::kNumNanosPerMicro = 1000
Definition at line 8 of file sleep.h.
kNumNanosPerSecond
const int benchmark::kNumNanosPerSecond = kNumNanosPerMicro * kNumMicrosPerSecond
Definition at line 9 of file sleep.h.