Mixed Criticality Orchestrator: fuzzer Namespace Reference
fuzzer Namespace Reference
Classes
class Dictionary
class DictionaryEntry
struct ExternalFunctions
class FixedWord
struct FlagDescription
class Fuzzer
struct FuzzingOptions
class InputCorpus
struct InputInfo
struct MallocFreeTracer
struct MergeFileInfo
struct Merger
class MutationDispatcher
class Random
struct ScopedDoingMyOwnMemmem
struct TableOfRecentCompares
struct TraceBasedMutation
class TracePC
class TraceState
struct ValueBitMap
Typedefs
typedef std::vector< uint8_t > Unit
typedef std::vector< Unit > UnitVector
typedef int(* UserCallback) (const uint8_t *Data, size_t Size)
typedef FixedWord< 27 > Word
Functions
template<class T >
T Min (T a, T b)
template<class T >
T Max (T a, T b)
int FuzzerDriver (int *argc, char ***argv, UserCallback Callback)
uint8_t Bswap (uint8_t x)
uint16_t Bswap (uint16_t x)
uint32_t Bswap (uint32_t x)
uint64_t Bswap (uint64_t x)
bool ParseOneDictionaryEntry (const std::string &Str, Unit *U)
bool ParseDictionaryFile (const std::string &Text, std::vector< Unit > *Units)
static void PrintHelp ()
static const char * FlagValue (const char *Param, const char *Name)
static long MyStol (const char *Str)
static bool ParseOneFlag (const char *Param)
static void ParseFlags (const std::vector< std::string > &Args)
static void PulseThread ()
static void WorkerThread (const std::string &Cmd, std::atomic< unsigned > *Counter, unsigned NumJobs, std::atomic< bool > *HasErrors)
std::string CloneArgsWithoutX (const std::vector< std::string > &Args, const char *X1, const char *X2)
static int RunInMultipleProcesses (const std::vector< std::string > &Args, unsigned NumWorkers, unsigned NumJobs)
static void RssThread (Fuzzer *F, size_t RssLimitMb)
static void StartRssThread (Fuzzer *F, size_t RssLimitMb)
int RunOneTest (Fuzzer *F, const char *InputFilePath, size_t MaxLen)
static bool AllInputsAreFiles ()
int MinimizeCrashInput (const std::vector< std::string > &Args)
int MinimizeCrashInputInternalStep (Fuzzer *F, InputCorpus *Corpus)
long GetEpoch (const std::string &Path)
Unit FileToVector (const std::string &Path, size_t MaxSize, bool ExitOnError)
std::string FileToString (const std::string &Path)
void CopyFileToErr (const std::string &Path)
void WriteToFile (const Unit &U, const std::string &Path)
void ReadDirToVectorOfUnits (const char *Path, std::vector< Unit > *V, long *Epoch, size_t MaxSize, bool ExitOnError)
std::string DirPlusFile (const std::string &DirPath, const std::string &FileName)
void DupAndCloseStderr ()
void CloseStdout ()
void Printf (const char *Fmt,...)
std::string DirName (const std::string &FileName)
bool IsFile (const std::string &Path)
void ListFilesInDirRecursive (const std::string &Dir, long *Epoch, std::vector< std::string > *V, bool TopDir)
char GetSeparator ()
FILE * OpenFile (int Fd, const char *Mode)
int CloseFile (int Fd)
int DuplicateFile (int Fd)
void RemoveFile (const std::string &Path)
static void MissingExternalApiFunction (const char *FnName)
void MallocHook (const volatile void *ptr, size_t size)
void FreeHook (const volatile void *ptr)
static void WarnOnUnsuccessfullMerge (bool DoWarn)
static void PrintASCII (const Word &W, const char *PrintAfter)
static char RandCh (Random &Rand)
template<class T >
size_t ChangeBinaryInteger (uint8_t *Data, size_t Size, Random &Rand)
void ComputeSHA1 (const uint8_t *Data, size_t Len, uint8_t *Out)
std::string Sha1ToString (const uint8_t Sha1[kSHA1NumBytes])
std::string Hash (const Unit &U)
static bool IsInterestingCoverageFile (std::string &File)
static size_t InternalStrnlen (const char *S, size_t MaxLen)
void PrintHexArray (const uint8_t *Data, size_t Size, const char *PrintAfter)
void Print (const Unit &v, const char *PrintAfter)
void PrintASCIIByte (uint8_t Byte)
void PrintASCII (const uint8_t *Data, size_t Size, const char *PrintAfter)
void PrintASCII (const Unit &U, const char *PrintAfter)
bool ToASCII (uint8_t *Data, size_t Size)
bool IsASCII (const Unit &U)
bool IsASCII (const uint8_t *Data, size_t Size)
std::string Base64 (const Unit &U)
std::string DescribePC (const char *SymbolizedFMT, uintptr_t PC)
void PrintPC (const char *SymbolizedFMT, const char *FallbackFMT, uintptr_t PC)
unsigned NumberOfCpuCores ()
bool ExecuteCommandAndReadOutput (const std::string &Command, std::string *Out)
void PrintHexArray (const Unit &U, const char *PrintAfter="")
void SetSignalHandler (const FuzzingOptions &Options)
void SleepSeconds (int Seconds)
unsigned long GetPid ()
size_t GetPeakRSSMb ()
int ExecuteCommand (const std::string &Command)
FILE * OpenProcessPipe (const char *Command, const char *Mode)
const void * SearchMemory (const void *haystack, size_t haystacklen, const void *needle, size_t needlelen)
std::string CloneArgsWithoutX (const std::vector< std::string > &Args, const char *X)
Variables
ExternalFunctions * EF = nullptr
struct {
} Flags
static const FlagDescription FlagDescriptions []
static const size_t kNumFlags
static std::vector< std::string > * Inputs
static std::string * ProgName
static std::mutex Mu
static FILE * OutputFile = stderr
static const size_t kMaxUnitSizeToPrint = 256
static Fuzzer * F
static MallocFreeTracer AllocTracer
static const int kSHA1NumBytes = 20
TracePC TPC
static bool RecordingMemcmp = false
static bool RecordingMemmem = false
static bool DoingMyOwnMemmem = false
static TraceState * TS
Typedef Documentation
Unit
typedef std::vector<uint8_t> fuzzer::Unit
Definition at line 71 of file FuzzerDefs.h.
UnitVector
typedef std::vector<Unit> fuzzer::UnitVector
Definition at line 72 of file FuzzerDefs.h.
UserCallback
typedef int(* fuzzer::UserCallback) (const uint8_t *Data, size_t Size)
Definition at line 73 of file FuzzerDefs.h.
Word
typedef FixedWord<27> fuzzer::Word
Definition at line 53 of file FuzzerDictionary.h.
Function Documentation
AllInputsAreFiles()
static bool fuzzer::AllInputsAreFiles () static
Definition at line 272 of file FuzzerDriver.cpp.
{
   if (Inputs->empty()) return false;
   for (auto &Path : *Inputs)
     if (!IsFile(Path))
       return false;
   return true;
 }
References Inputs, and IsFile().
Referenced by FuzzerDriver().
Base64()
std::string fuzzer::Base64 (const Unit & U)
Definition at line 154 of file FuzzerUtil.cpp.
{
   static const char Table[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                               "abcdefghijklmnopqrstuvwxyz"
                               "0123456789+/";
   std::string Res;
   size_t i;
   for (i = 0; i + 2 < U.size(); i += 3) {
     uint32_t x = (U[i] << 16) + (U[i + 1] << 8) + U[i + 2];
     Res += Table[(x >> 18) & 63];
     Res += Table[(x >> 12) & 63];
     Res += Table[(x >> 6) & 63];
     Res += Table[x & 63];
   }
   if (i + 1 == U.size()) {
     uint32_t x = (U[i] << 16);
     Res += Table[(x >> 18) & 63];
     Res += Table[(x >> 12) & 63];
     Res += "==";
   } else if (i + 2 == U.size()) {
     uint32_t x = (U[i] << 16) + (U[i + 1] << 8);
     Res += Table[(x >> 18) & 63];
     Res += Table[(x >> 12) & 63];
     Res += Table[(x >> 6) & 63];
     Res += "=";
   }
   return Res;
 }
Referenced by TEST(), and fuzzer::Fuzzer::WriteUnitToFileWithPrefix().
Bswap() [1/4]
uint16_t fuzzer::Bswap (uint16_t x) inline
Definition at line 83 of file FuzzerDefs.h.
 { return __builtin_bswap16(x); }
Bswap() [2/4]
uint32_t fuzzer::Bswap (uint32_t x) inline
Definition at line 84 of file FuzzerDefs.h.
 { return __builtin_bswap32(x); }
Bswap() [3/4]
uint64_t fuzzer::Bswap (uint64_t x) inline
Definition at line 85 of file FuzzerDefs.h.
 { return __builtin_bswap64(x); }
Bswap() [4/4]
uint8_t fuzzer::Bswap (uint8_t x) inline
Definition at line 82 of file FuzzerDefs.h.
 { return x; }
Referenced by ChangeBinaryInteger(), and fuzzer::MutationDispatcher::MakeDictionaryEntryFromCMP().
ChangeBinaryInteger()
template<class T > size_t fuzzer::ChangeBinaryInteger (uint8_t * Data, size_t Size, Random & Rand)
Definition at line 362 of file FuzzerMutate.cpp.
{
   if (Size < sizeof(T)) return 0;
   size_t Off = Rand(Size - sizeof(T) + 1);
   assert(Off + sizeof(T) <= Size);
   T Val;
   if (Off < 64 && !Rand(4)) {
     Val = Size;
     if (Rand.RandBool())
       Val = Bswap(Val);
   } else {
     memcpy(&Val, Data + Off, sizeof(Val));
     T Add = Rand(21);
     Add -= 10;
     if (Rand.RandBool())
       Val = Bswap(T(Bswap(Val) + Add)); // Add assuming different endiannes.
     else
       Val = Val + Add;               // Add assuming current endiannes.
     if (Add == 0 || Rand.RandBool()) // Maybe negate.
       Val = -Val;
   }
   memcpy(Data + Off, &Val, sizeof(Val));
   return Size;
 }
References assert(), Bswap(), and fuzzer::Random::RandBool().
CloneArgsWithoutX() [1/2]
std::string fuzzer::CloneArgsWithoutX (const std::vector< std::string > & Args, const char * X) inline
Definition at line 65 of file FuzzerUtil.h.
{
   return CloneArgsWithoutX(Args, X, X);
 }
References CloneArgsWithoutX().
CloneArgsWithoutX() [2/2]
std::string fuzzer::CloneArgsWithoutX (const std::vector< std::string > & Args, const char * X1, const char * X2)
Definition at line 222 of file FuzzerDriver.cpp.
{
   std::string Cmd;
   for (auto &S : Args) {
     if (FlagValue(S.c_str(), X1) || FlagValue(S.c_str(), X2))
       continue;
     Cmd += S + " ";
   }
   return Cmd;
 }
References FlagValue().
Referenced by CloneArgsWithoutX(), fuzzer::Fuzzer::CrashResistantMerge(), MinimizeCrashInput(), and RunInMultipleProcesses().
CloseFile()
int fuzzer::CloseFile (int Fd)
Referenced by CloseStdout(), and DupAndCloseStderr().
CloseStdout()
void fuzzer::CloseStdout ()
Definition at line 105 of file FuzzerIO.cpp.
                    {
   CloseFile(1);
 }
References CloseFile().
Referenced by FuzzerDriver().
ComputeSHA1()
void fuzzer::ComputeSHA1 (const uint8_t * Data, size_t Len, uint8_t * Out)
Definition at line 202 of file FuzzerSHA1.cpp.
{
   sha1nfo s;
   sha1_init(&s);
   sha1_write(&s, (const char*)Data, Len);
   memcpy(Out, sha1_result(&s), HASH_LENGTH);
 }
References HASH_LENGTH.
Referenced by fuzzer::InputCorpus::AddToCorpus(), and Hash().
CopyFileToErr()
void fuzzer::CopyFileToErr (const std::string & Path)
Definition at line 57 of file FuzzerIO.cpp.
{
   Printf("%s", FileToString(Path).c_str());
 }
References FileToString(), and Printf().
Referenced by WorkerThread().
DescribePC()
std::string fuzzer::DescribePC (const char * SymbolizedFMT, uintptr_t PC)
Definition at line 182 of file FuzzerUtil.cpp.
{
   if (!EF->__sanitizer_symbolize_pc) return "<can not symbolize>";
   char PcDescr[1024];
   EF->__sanitizer_symbolize_pc(reinterpret_cast<void*>(PC),
                                SymbolizedFMT, PcDescr, sizeof(PcDescr));
   PcDescr[sizeof(PcDescr) - 1] = 0;  // Just in case.
   return PcDescr;
 }
References EF, and PC.
Referenced by fuzzer::Fuzzer::CheckExitOnSrcPosOrItem(), fuzzer::TracePC::PrintCoverage(), and PrintPC().
DirName()
std::string fuzzer::DirName (const std::string & FileName)
Referenced by fuzzer::TracePC::PrintCoverage().
DirPlusFile()
std::string fuzzer::DirPlusFile (const std::string & DirPath, const std::string & FileName)
Definition at line 87 of file FuzzerIO.cpp.
{
   return DirPath + GetSeparator() + FileName;
 }
References GetSeparator().
Referenced by fuzzer::InputCorpus::DeleteInput(), and fuzzer::Fuzzer::WriteToOutputCorpus().
DupAndCloseStderr()
void fuzzer::DupAndCloseStderr ()
Definition at line 92 of file FuzzerIO.cpp.
{
   int OutputFd = DuplicateFile(2);
   if (OutputFd > 0) {
     FILE *NewOutputFile = OpenFile(OutputFd, "w");
     if (NewOutputFile) {
       OutputFile = NewOutputFile;
       if (EF->__sanitizer_set_report_fd)
         EF->__sanitizer_set_report_fd(reinterpret_cast<void *>(OutputFd));
       CloseFile(2);
     }
   }
 }
References CloseFile(), DuplicateFile(), EF, OpenFile(), and OutputFile.
Referenced by FuzzerDriver().
DuplicateFile()
int fuzzer::DuplicateFile (int Fd)
Referenced by DupAndCloseStderr().
ExecuteCommand()
int fuzzer::ExecuteCommand (const std::string & Command)
Referenced by fuzzer::Fuzzer::CrashResistantMerge(), MinimizeCrashInput(), and WorkerThread().
ExecuteCommandAndReadOutput()
bool fuzzer::ExecuteCommandAndReadOutput (const std::string & Command, std::string * Out)
Definition at line 208 of file FuzzerUtil.cpp.
{
   FILE *Pipe = OpenProcessPipe(Command.c_str(), "r");
   if (!Pipe) return false;
   char Buff[1024];
   size_t N;
   while ((N = fread(Buff, 1, sizeof(Buff), Pipe)) > 0)
     Out->append(Buff, N);
   return true;
 }
References N, and OpenProcessPipe().
Referenced by fuzzer::TracePC::PrintCoverage().
FileToString()
std::string fuzzer::FileToString (const std::string & Path)
Definition at line 51 of file FuzzerIO.cpp.
{
   std::ifstream T(Path);
   return std::string((std::istreambuf_iterator<char>(T)),
                      std::istreambuf_iterator<char>());
 }
Referenced by CopyFileToErr(), and FuzzerDriver().
FileToVector()
Unit fuzzer::FileToVector (const std::string & Path, size_t MaxSize, bool ExitOnError)
Definition at line 33 of file FuzzerIO.cpp.
{
   std::ifstream T(Path);
   if (ExitOnError && !T) {
     Printf("No such directory: %s; exiting\n", Path.c_str());
     exit(1);
   }
   T.seekg(0, T.end);
   size_t FileLen = T.tellg();
   if (MaxSize)
     FileLen = std::min(FileLen, MaxSize);
   T.seekg(0, T.beg);
   Unit Res(FileLen);
   T.read(reinterpret_cast<char *>(Res.data()), FileLen);
   return Res;
 }
References Printf().
Referenced by fuzzer::Fuzzer::CrashResistantMerge(), fuzzer::Fuzzer::CrashResistantMergeInternalStep(), MinimizeCrashInput(), MinimizeCrashInputInternalStep(), ReadDirToVectorOfUnits(), and RunOneTest().
FlagValue()
static const char* fuzzer::FlagValue (const char * Param, const char * Name) static
Definition at line 105 of file FuzzerDriver.cpp.
{
   size_t Len = strlen(Name);
   if (Param[0] == '-' && strstr(Param + 1, Name) == Param + 1 &&
       Param[Len + 1] == '=')
       return &Param[Len + 2];
   return nullptr;
 }
Referenced by CloneArgsWithoutX(), and ParseOneFlag().
FreeHook()
void fuzzer::FreeHook (const volatile void * ptr)
Definition at line 152 of file FuzzerLoop.cpp.
{
   size_t N = AllocTracer.Frees++;
   if (int TraceLevel = AllocTracer.TraceLevel) {
     Printf("FREE[%zd]   %p\n", N, ptr);
     if (TraceLevel >= 2 && EF)
       EF->__sanitizer_print_stack_trace();
   }
 }
References AllocTracer, EF, fuzzer::MallocFreeTracer::Frees, N, Printf(), and fuzzer::MallocFreeTracer::TraceLevel.
Referenced by fuzzer::Fuzzer::Fuzzer().
FuzzerDriver()
int fuzzer::FuzzerDriver (int * argc, char *** argv, UserCallback Callback)
Definition at line 356 of file FuzzerDriver.cpp.
{
   using namespace fuzzer;
   assert(argc && argv && "Argument pointers cannot be nullptr");
   EF = new ExternalFunctions();
   if (EF->LLVMFuzzerInitialize)
     EF->LLVMFuzzerInitialize(argc, argv);
   const std::vector<std::string> Args(*argv, *argv + *argc);
   assert(!Args.empty());
   ProgName = new std::string(Args[0]);
   ParseFlags(Args);
   if (Flags.help) {
     PrintHelp();
     return 0;
   }
   if (Flags.minimize_crash)
     return MinimizeCrashInput(Args);
   if (Flags.close_fd_mask & 2)
     DupAndCloseStderr();
   if (Flags.close_fd_mask & 1)
     CloseStdout();
   if (Flags.jobs > 0 && Flags.workers == 0) {
     Flags.workers = std::min(NumberOfCpuCores() / 2, Flags.jobs);
     if (Flags.workers > 1)
       Printf("Running %u workers\n", Flags.workers);
   }
   if (Flags.workers > 0 && Flags.jobs > 0)
     return RunInMultipleProcesses(Args, Flags.workers, Flags.jobs);
   const size_t kMaxSaneLen = 1 << 20;
   const size_t kMinDefaultLen = 64;
   FuzzingOptions Options;
   Options.Verbosity = Flags.verbosity;
   Options.MaxLen = Flags.max_len;
   Options.UnitTimeoutSec = Flags.timeout;
   Options.ErrorExitCode = Flags.error_exitcode;
   Options.TimeoutExitCode = Flags.timeout_exitcode;
   Options.MaxTotalTimeSec = Flags.max_total_time;
   Options.DoCrossOver = Flags.cross_over;
   Options.MutateDepth = Flags.mutate_depth;
   Options.UseCounters = Flags.use_counters;
   Options.UseIndirCalls = Flags.use_indir_calls;
   Options.UseMemcmp = Flags.use_memcmp;
   Options.UseMemmem = Flags.use_memmem;
   Options.UseCmp = Flags.use_cmp;
   Options.UseValueProfile = Flags.use_value_profile;
   Options.Shrink = Flags.shrink;
   Options.ShuffleAtStartUp = Flags.shuffle;
   Options.PreferSmall = Flags.prefer_small;
   Options.ReloadIntervalSec = Flags.reload;
   Options.OnlyASCII = Flags.only_ascii;
   Options.OutputCSV = Flags.output_csv;
   Options.DetectLeaks = Flags.detect_leaks;
   Options.TraceMalloc = Flags.trace_malloc;
   Options.RssLimitMb = Flags.rss_limit_mb;
   if (Flags.runs >= 0)
     Options.MaxNumberOfRuns = Flags.runs;
   if (!Inputs->empty() && !Flags.minimize_crash_internal_step)
     Options.OutputCorpus = (*Inputs)[0];
   Options.ReportSlowUnits = Flags.report_slow_units;
   if (Flags.artifact_prefix)
     Options.ArtifactPrefix = Flags.artifact_prefix;
   if (Flags.exact_artifact_path)
     Options.ExactArtifactPath = Flags.exact_artifact_path;
   std::vector<Unit> Dictionary;
   if (Flags.dict)
     if (!ParseDictionaryFile(FileToString(Flags.dict), &Dictionary))
       return 1;
   if (Flags.verbosity > 0 && !Dictionary.empty())
     Printf("Dictionary: %zd entries\n", Dictionary.size());
   bool DoPlainRun = AllInputsAreFiles();
   Options.SaveArtifacts =
       !DoPlainRun || Flags.minimize_crash_internal_step;
   Options.PrintNewCovPcs = Flags.print_pcs;
   Options.PrintFinalStats = Flags.print_final_stats;
   Options.PrintCorpusStats = Flags.print_corpus_stats;
   Options.PrintCoverage = Flags.print_coverage;
   Options.DumpCoverage = Flags.dump_coverage;
   if (Flags.exit_on_src_pos)
     Options.ExitOnSrcPos = Flags.exit_on_src_pos;
   if (Flags.exit_on_item)
     Options.ExitOnItem = Flags.exit_on_item;
   unsigned Seed = Flags.seed;
   // Initialize Seed.
   if (Seed == 0)
     Seed = (std::chrono::system_clock::now().time_since_epoch().count() << 10) +
            GetPid();
   if (Flags.verbosity)
     Printf("INFO: Seed: %u\n", Seed);
   Random Rand(Seed);
   auto *MD = new MutationDispatcher(Rand, Options);
   auto *Corpus = new InputCorpus(Options.OutputCorpus);
   auto *F = new Fuzzer(Callback, *Corpus, *MD, Options);
   for (auto &U: Dictionary)
     if (U.size() <= Word::GetMaxSize())
       MD->AddWordToManualDictionary(Word(U.data(), U.size()));
   StartRssThread(F, Flags.rss_limit_mb);
   Options.HandleAbrt = Flags.handle_abrt;
   Options.HandleBus = Flags.handle_bus;
   Options.HandleFpe = Flags.handle_fpe;
   Options.HandleIll = Flags.handle_ill;
   Options.HandleInt = Flags.handle_int;
   Options.HandleSegv = Flags.handle_segv;
   Options.HandleTerm = Flags.handle_term;
   SetSignalHandler(Options);
   if (Flags.minimize_crash_internal_step)
     return MinimizeCrashInputInternalStep(F, Corpus);
   if (DoPlainRun) {
     Options.SaveArtifacts = false;
     int Runs = std::max(1, Flags.runs);
     Printf("%s: Running %zd inputs %d time(s) each.\n", ProgName->c_str(),
            Inputs->size(), Runs);
     for (auto &Path : *Inputs) {
       auto StartTime = system_clock::now();
       Printf("Running: %s\n", Path.c_str());
       for (int Iter = 0; Iter < Runs; Iter++)
         RunOneTest(F, Path.c_str(), Options.MaxLen);
       auto StopTime = system_clock::now();
       auto MS = duration_cast<milliseconds>(StopTime - StartTime).count();
       Printf("Executed %s in %zd ms\n", Path.c_str(), (long)MS);
     }
     Printf("***\n"
            "*** NOTE: fuzzing was not performed, you have only\n"
            "***       executed the target code on a fixed set of inputs.\n"
            "***\n");
     F->PrintFinalStats();
     exit(0);
   }
   if (Flags.merge) {
     if (Options.MaxLen == 0)
       F->SetMaxInputLen(kMaxSaneLen);
     if (TPC.UsingTracePcGuard()) {
       if (Flags.merge_control_file)
         F->CrashResistantMergeInternalStep(Flags.merge_control_file);
       else
         F->CrashResistantMerge(Args, *Inputs);
     } else {
       F->Merge(*Inputs);
     }
     exit(0);
   }
   size_t TemporaryMaxLen = Options.MaxLen ? Options.MaxLen : kMaxSaneLen;
   UnitVector InitialCorpus;
   for (auto &Inp : *Inputs) {
     Printf("Loading corpus dir: %s\n", Inp.c_str());
     ReadDirToVectorOfUnits(Inp.c_str(), &InitialCorpus, nullptr,
                            TemporaryMaxLen, /*ExitOnError=*/false);
   }
   if (Options.MaxLen == 0) {
     size_t MaxLen = 0;
     for (auto &U : InitialCorpus)
       MaxLen = std::max(U.size(), MaxLen);
     F->SetMaxInputLen(std::min(std::max(kMinDefaultLen, MaxLen), kMaxSaneLen));
   }
   if (InitialCorpus.empty()) {
     InitialCorpus.push_back(Unit({'\n'}));  // Valid ASCII input.
     if (Options.Verbosity)
       Printf("INFO: A corpus is not provided, starting from an empty corpus\n");
   }
   F->ShuffleAndMinimize(&InitialCorpus);
   InitialCorpus.clear();  // Don't need this memory any more.
   F->Loop();
   if (Flags.verbosity)
     Printf("Done %d runs in %zd second(s)\n", F->getTotalNumberOfRuns(),
            F->secondsSinceProcessStartUp());
   F->PrintFinalStats();
   exit(0);  // Don't let F destroy itself.
 }
References AllInputsAreFiles(), argv, fuzzer::FuzzingOptions::ArtifactPrefix, assert(), CloseStdout(), fuzzer::Fuzzer::CrashResistantMerge(), fuzzer::Fuzzer::CrashResistantMergeInternalStep(), fuzzer::FuzzingOptions::DetectLeaks, fuzzer::FuzzingOptions::DoCrossOver, fuzzer::FuzzingOptions::DumpCoverage, DupAndCloseStderr(), EF, fuzzer::Dictionary::empty(), fuzzer::FuzzingOptions::ErrorExitCode, fuzzer::FuzzingOptions::ExactArtifactPath, fuzzer::FuzzingOptions::ExitOnItem, fuzzer::FuzzingOptions::ExitOnSrcPos, F, FileToString(), Flags, fuzzer::FixedWord< 27 >::GetMaxSize(), GetPid(), fuzzer::Fuzzer::getTotalNumberOfRuns(), fuzzer::FuzzingOptions::HandleAbrt, fuzzer::FuzzingOptions::HandleBus, fuzzer::FuzzingOptions::HandleFpe, fuzzer::FuzzingOptions::HandleIll, fuzzer::FuzzingOptions::HandleInt, fuzzer::FuzzingOptions::HandleSegv, fuzzer::FuzzingOptions::HandleTerm, Inputs, fuzzer::Fuzzer::Loop(), fuzzer::FuzzingOptions::MaxLen, fuzzer::FuzzingOptions::MaxNumberOfRuns, fuzzer::FuzzingOptions::MaxTotalTimeSec, fuzzer::Fuzzer::Merge(), MinimizeCrashInput(), MinimizeCrashInputInternalStep(), fuzzer::FuzzingOptions::MutateDepth, NumberOfCpuCores(), fuzzer::FuzzingOptions::OnlyASCII, fuzzer::FuzzingOptions::OutputCorpus, fuzzer::FuzzingOptions::OutputCSV, ParseDictionaryFile(), ParseFlags(), fuzzer::FuzzingOptions::PreferSmall, fuzzer::FuzzingOptions::PrintCorpusStats, fuzzer::FuzzingOptions::PrintCoverage, Printf(), fuzzer::FuzzingOptions::PrintFinalStats, fuzzer::Fuzzer::PrintFinalStats(), PrintHelp(), fuzzer::FuzzingOptions::PrintNewCovPcs, ProgName, ReadDirToVectorOfUnits(), fuzzer::FuzzingOptions::ReloadIntervalSec, fuzzer::FuzzingOptions::ReportSlowUnits, fuzzer::FuzzingOptions::RssLimitMb, RunInMultipleProcesses(), RunOneTest(), fuzzer::FuzzingOptions::SaveArtifacts, fuzzer::Fuzzer::secondsSinceProcessStartUp(), fuzzer::Fuzzer::SetMaxInputLen(), SetSignalHandler(), fuzzer::FuzzingOptions::Shrink, fuzzer::Fuzzer::ShuffleAndMinimize(), fuzzer::FuzzingOptions::ShuffleAtStartUp, fuzzer::Dictionary::size(), StartRssThread(), fuzzer::FuzzingOptions::TimeoutExitCode, TPC, fuzzer::FuzzingOptions::TraceMalloc, fuzzer::FuzzingOptions::UnitTimeoutSec, fuzzer::FuzzingOptions::UseCmp, fuzzer::FuzzingOptions::UseCounters, fuzzer::FuzzingOptions::UseIndirCalls, fuzzer::FuzzingOptions::UseMemcmp, fuzzer::FuzzingOptions::UseMemmem, fuzzer::FuzzingOptions::UseValueProfile, fuzzer::TracePC::UsingTracePcGuard(), and fuzzer::FuzzingOptions::Verbosity.
Referenced by main().
GetEpoch()
long fuzzer::GetEpoch (const std::string & Path)
Definition at line 26 of file FuzzerIO.cpp.
{
   struct stat St;
   if (stat(Path.c_str(), &St))
     return 0;  // Can't stat, be conservative.
   return St.st_mtime;
 }
Referenced by fuzzer::Fuzzer::Fuzzer(), and ReadDirToVectorOfUnits().
GetPeakRSSMb()
size_t fuzzer::GetPeakRSSMb ()
Definition at line 113 of file afl_driver.cpp.
                       {
   struct rusage usage;
   if (getrusage(RUSAGE_SELF, &usage))
     return 0;
   if (LIBFUZZER_LINUX) {
     // ru_maxrss is in KiB
     return usage.ru_maxrss >> 10;
   } else if (LIBFUZZER_APPLE) {
     // ru_maxrss is in bytes
     return usage.ru_maxrss >> 20;
   }
   assert(0 && "GetPeakRSSMb() is not implemented for your platform");
   return 0;
 }
References assert().
Referenced by fuzzer::Fuzzer::PrintFinalStats(), fuzzer::Fuzzer::PrintStats(), fuzzer::Fuzzer::RssLimitCallback(), RssThread(), and write_extra_stats().
GetPid()
unsigned long fuzzer::GetPid ()
Referenced by fuzzer::Fuzzer::AlarmCallback(), fuzzer::Fuzzer::CrashCallback(), fuzzer::Fuzzer::CrashResistantMerge(), FuzzerDriver(), fuzzer::Fuzzer::HandleMalloc(), fuzzer::Fuzzer::InterruptCallback(), and fuzzer::Fuzzer::RssLimitCallback().
GetSeparator()
char fuzzer::GetSeparator ()
Referenced by DirPlusFile().
Hash()
std::string fuzzer::Hash (const Unit & U)
Definition at line 216 of file FuzzerSHA1.cpp.
{
   uint8_t Hash[kSHA1NumBytes];
   ComputeSHA1(U.data(), U.size(), Hash);
   return Sha1ToString(Hash);
 }
References ComputeSHA1(), kSHA1NumBytes, and Sha1ToString().
Referenced by fuzzer::InputCorpus::AddToCorpus(), fuzzer::InputCorpus::HasUnit(), LLVMFuzzerTestOneInput(), MinimizeCrashInput(), simple_hash(), TEST(), fuzzer::Fuzzer::WriteToOutputCorpus(), and fuzzer::Fuzzer::WriteUnitToFileWithPrefix().
InternalStrnlen()
static size_t fuzzer::InternalStrnlen (const char * S, size_t MaxLen) static
Definition at line 246 of file FuzzerTraceState.cpp.
{
   size_t Len = 0;
   for (; Len < MaxLen && S[Len]; Len++) {}
   return Len;
 }
Referenced by __sanitizer_weak_hook_strncmp().
IsASCII() [1/2]
bool fuzzer::IsASCII (const uint8_t * Data, size_t Size)
Definition at line 75 of file FuzzerUtil.cpp.
{
   for (size_t i = 0; i < Size; i++)
     if (!(isprint(Data[i]) || isspace(Data[i]))) return false;
   return true;
 }
IsASCII() [2/2]
bool fuzzer::IsASCII (const Unit & U)
Definition at line 73 of file FuzzerUtil.cpp.
 { return IsASCII(U.data(), U.size()); }
Referenced by fuzzer::Fuzzer::WriteToOutputCorpus().
IsFile()
bool fuzzer::IsFile (const std::string & Path)
Referenced by AllInputsAreFiles().
IsInterestingCoverageFile()
static bool fuzzer::IsInterestingCoverageFile (std::string & File) static
Definition at line 70 of file FuzzerTracePC.cpp.
{
   if (File.find("compiler-rt/lib/") != std::string::npos)
     return false; // sanitizer internal.
   if (File.find("/usr/lib/") != std::string::npos)
     return false;
   if (File.find("/usr/include/") != std::string::npos)
     return false;
   if (File == "<null>")
     return false;
   return true;
 }
Referenced by fuzzer::TracePC::PrintCoverage().
ListFilesInDirRecursive()
void fuzzer::ListFilesInDirRecursive (const std::string & Dir, long * Epoch, std::vector< std::string > * V, bool TopDir)
Referenced by fuzzer::Fuzzer::CrashResistantMerge(), and ReadDirToVectorOfUnits().
MallocHook()
void fuzzer::MallocHook (const volatile void * ptr, size_t size)
Definition at line 141 of file FuzzerLoop.cpp.
{
   size_t N = AllocTracer.Mallocs++;
   F->HandleMalloc(size);
   if (int TraceLevel = AllocTracer.TraceLevel) {
     Printf("MALLOC[%zd] %p %zd\n", N, ptr, size);
     if (TraceLevel >= 2 && EF)
       EF->__sanitizer_print_stack_trace();
   }
 }
References AllocTracer, EF, F, fuzzer::Fuzzer::HandleMalloc(), fuzzer::MallocFreeTracer::Mallocs, N, Printf(), and fuzzer::MallocFreeTracer::TraceLevel.
Referenced by fuzzer::Fuzzer::Fuzzer().
Max()
template<class T > T fuzzer::Max (T a, T b)
Definition at line 57 of file FuzzerDefs.h.
 { return a > b ? a : b; }
Min()
template<class T > T fuzzer::Min (T a, T b)
Definition at line 56 of file FuzzerDefs.h.
 { return a < b ? a : b; }
Referenced by fuzzer::TracePC::CollectFeatures(), and fuzzer::TracePC::GetNumPCs().
MinimizeCrashInput()
int fuzzer::MinimizeCrashInput (const std::vector< std::string > & Args)
Definition at line 280 of file FuzzerDriver.cpp.
{
   if (Inputs->size() != 1) {
     Printf("ERROR: -minimize_crash should be given one input file\n");
     exit(1);
   }
   std::string InputFilePath = Inputs->at(0);
   std::string BaseCmd =
       CloneArgsWithoutX(Args, "minimize_crash", "exact_artifact_path");
   auto InputPos = BaseCmd.find(" " + InputFilePath + " ");
   assert(InputPos != std::string::npos);
   BaseCmd.erase(InputPos, InputFilePath.size() + 1);
   if (Flags.runs <= 0 && Flags.max_total_time == 0) {
     Printf("INFO: you need to specify -runs=N or "
            "-max_total_time=N with -minimize_crash=1\n"
            "INFO: defaulting to -max_total_time=600\n");
     BaseCmd += " -max_total_time=600";
   }
   // BaseCmd += " >  /dev/null 2>&1 ";
   std::string CurrentFilePath = InputFilePath;
   while (true) {
     Unit U = FileToVector(CurrentFilePath);
     if (U.size() < 2) {
       Printf("CRASH_MIN: '%s' is small enough\n", CurrentFilePath.c_str());
       return 0;
     }
     Printf("CRASH_MIN: minimizing crash input: '%s' (%zd bytes)\n",
            CurrentFilePath.c_str(), U.size());
     auto Cmd = BaseCmd + " " + CurrentFilePath;
     Printf("CRASH_MIN: executing: %s\n", Cmd.c_str());
     int ExitCode = ExecuteCommand(Cmd);
     if (ExitCode == 0) {
       Printf("ERROR: the input %s did not crash\n", CurrentFilePath.c_str());
       exit(1);
     }
     Printf("CRASH_MIN: '%s' (%zd bytes) caused a crash. Will try to minimize "
            "it further\n",
            CurrentFilePath.c_str(), U.size());
     std::string ArtifactPath = "minimized-from-" + Hash(U);
     Cmd += " -minimize_crash_internal_step=1 -exact_artifact_path=" +
         ArtifactPath;
     Printf("CRASH_MIN: executing: %s\n", Cmd.c_str());
     ExitCode = ExecuteCommand(Cmd);
     if (ExitCode == 0) {
       if (Flags.exact_artifact_path) {
         CurrentFilePath = Flags.exact_artifact_path;
         WriteToFile(U, CurrentFilePath);
       }
       Printf("CRASH_MIN: failed to minimize beyond %s (%d bytes), exiting\n",
              CurrentFilePath.c_str(), U.size());
       return 0;
     }
     CurrentFilePath = ArtifactPath;
     Printf("\n\n\n\n\n\n*********************************\n");
   }
   return 0;
 }
References assert(), CloneArgsWithoutX(), ExecuteCommand(), FileToVector(), Flags, Hash(), Inputs, Printf(), and WriteToFile().
Referenced by FuzzerDriver().
MinimizeCrashInputInternalStep()
int fuzzer::MinimizeCrashInputInternalStep (Fuzzer * F, InputCorpus * Corpus)
Definition at line 341 of file FuzzerDriver.cpp.
{
   assert(Inputs->size() == 1);
   std::string InputFilePath = Inputs->at(0);
   Unit U = FileToVector(InputFilePath);
   assert(U.size() > 2);
   Printf("INFO: Starting MinimizeCrashInputInternalStep: %zd\n", U.size());
   Corpus->AddToCorpus(U, 0);
   F->SetMaxInputLen(U.size());
   F->SetMaxMutationLen(U.size() - 1);
   F->MinimizeCrashLoop(U);
   Printf("INFO: Done MinimizeCrashInputInternalStep, no crashes found\n");
   exit(0);
   return 0;
 }
References fuzzer::InputCorpus::AddToCorpus(), assert(), F, FileToVector(), Inputs, fuzzer::Fuzzer::MinimizeCrashLoop(), Printf(), fuzzer::Fuzzer::SetMaxInputLen(), and fuzzer::Fuzzer::SetMaxMutationLen().
Referenced by FuzzerDriver().
MissingExternalApiFunction()
static void fuzzer::MissingExternalApiFunction (const char * FnName) static
Definition at line 45 of file FuzzerLoop.cpp.
{
   Printf("ERROR: %s is not defined. Exiting.\n"
          "Did you use -fsanitize-coverage=... to build your code?\n",
          FnName);
   exit(1);
 }
References Printf().
MyStol()
static long fuzzer::MyStol (const char * Str) static
Definition at line 114 of file FuzzerDriver.cpp.
{
   long Res = 0;
   long Sign = 1;
   if (*Str == '-') {
     Str++;
     Sign = -1;
   }
   for (size_t i = 0; Str[i]; i++) {
     char Ch = Str[i];
     if (Ch < '0' || Ch > '9')
       return Res;
     Res = Res * 10 + (Ch - '0');
   }
   return Res * Sign;
 }
Referenced by ParseOneFlag().
NumberOfCpuCores()
unsigned fuzzer::NumberOfCpuCores ()
Definition at line 198 of file FuzzerUtil.cpp.
{
   unsigned N = std::thread::hardware_concurrency();
   if (!N) {
     Printf("WARNING: std::thread::hardware_concurrency not well defined for "
            "your platform. Assuming CPU count of 1.\n");
     N = 1;
   }
   return N;
 }
References N, and Printf().
Referenced by FuzzerDriver().
OpenFile()
FILE* fuzzer::OpenFile (int Fd, const char * Mode)
Referenced by DupAndCloseStderr().
OpenProcessPipe()
FILE* fuzzer::OpenProcessPipe (const char * Command, const char * Mode)
Referenced by ExecuteCommandAndReadOutput().
ParseDictionaryFile()
bool fuzzer::ParseDictionaryFile (const std::string & Text, std::vector< Unit > * Units)
Definition at line 127 of file FuzzerUtil.cpp.
{
   if (Text.empty()) {
     Printf("ParseDictionaryFile: file does not exist or is empty\n");
     return false;
   }
   std::istringstream ISS(Text);
   Units->clear();
   Unit U;
   int LineNo = 0;
   std::string S;
   while (std::getline(ISS, S, '\n')) {
     LineNo++;
     size_t Pos = 0;
     while (Pos < S.size() && isspace(S[Pos])) Pos++;  // Skip spaces.
     if (Pos == S.size()) continue;  // Empty line.
     if (S[Pos] == '#') continue;  // Comment line.
     if (ParseOneDictionaryEntry(S, &U)) {
       Units->push_back(U);
     } else {
       Printf("ParseDictionaryFile: error in line %d\n\t\t%s\n", LineNo,
              S.c_str());
       return false;
     }
   }
   return true;
 }
References ParseOneDictionaryEntry(), and Printf().
Referenced by FuzzerDriver(), and TEST().
ParseFlags()
static void fuzzer::ParseFlags (const std::vector< std::string > & Args) static
Definition at line 176 of file FuzzerDriver.cpp.
{
   for (size_t F = 0; F < kNumFlags; F++) {
     if (FlagDescriptions[F].IntFlag)
       *FlagDescriptions[F].IntFlag = FlagDescriptions[F].Default;
     if (FlagDescriptions[F].UIntFlag)
       *FlagDescriptions[F].UIntFlag =
           static_cast<unsigned int>(FlagDescriptions[F].Default);
     if (FlagDescriptions[F].StrFlag)
       *FlagDescriptions[F].StrFlag = nullptr;
   }
   Inputs = new std::vector<std::string>;
   for (size_t A = 1; A < Args.size(); A++) {
     if (ParseOneFlag(Args[A].c_str())) continue;
     Inputs->push_back(Args[A]);
   }
 }
References fuzzer::FlagDescription::Default, F, FlagDescriptions, Inputs, fuzzer::FlagDescription::IntFlag, kNumFlags, ParseOneFlag(), fuzzer::FlagDescription::StrFlag, and fuzzer::FlagDescription::UIntFlag.
Referenced by FuzzerDriver().
ParseOneDictionaryEntry()
bool fuzzer::ParseOneDictionaryEntry (const std::string & Str, Unit * U)
Definition at line 81 of file FuzzerUtil.cpp.
{
   U->clear();
   if (Str.empty()) return false;
   size_t L = 0, R = Str.size() - 1;  // We are parsing the range [L,R].
   // Skip spaces from both sides.
   while (L < R && isspace(Str[L])) L++;
   while (R > L && isspace(Str[R])) R--;
   if (R - L < 2) return false;
   // Check the closing "
   if (Str[R] != '"') return false;
   R--;
   // Find the opening "
   while (L < R && Str[L] != '"') L++;
   if (L >= R) return false;
   assert(Str[L] == '\"');
   L++;
   assert(L <= R);
   for (size_t Pos = L; Pos <= R; Pos++) {
     uint8_t V = (uint8_t)Str[Pos];
     if (!isprint(V) && !isspace(V)) return false;
     if (V =='\\') {
       // Handle '\\'
       if (Pos + 1 <= R && (Str[Pos + 1] == '\\' || Str[Pos + 1] == '"')) {
         U->push_back(Str[Pos + 1]);
         Pos++;
         continue;
       }
       // Handle '\xAB'
       if (Pos + 3 <= R && Str[Pos + 1] == 'x'
            && isxdigit(Str[Pos + 2]) && isxdigit(Str[Pos + 3])) {
         char Hex[] = "0xAA";
         Hex[2] = Str[Pos + 2];
         Hex[3] = Str[Pos + 3];
         U->push_back(strtol(Hex, nullptr, 16));
         Pos += 3;
         continue;
       }
       return false;  // Invalid escape.
     } else {
       // Any other character.
       U->push_back(V);
     }
   }
   return true;
 }
References assert().
Referenced by ParseDictionaryFile(), and TEST().
ParseOneFlag()
static bool fuzzer::ParseOneFlag (const char * Param) static
Definition at line 130 of file FuzzerDriver.cpp.
{
   if (Param[0] != '-') return false;
   if (Param[1] == '-') {
     static bool PrintedWarning = false;
     if (!PrintedWarning) {
       PrintedWarning = true;
       Printf("INFO: libFuzzer ignores flags that start with '--'\n");
     }
     for (size_t F = 0; F < kNumFlags; F++)
       if (FlagValue(Param + 1, FlagDescriptions[F].Name))
         Printf("WARNING: did you mean '%s' (single dash)?\n", Param + 1);
     return true;
   }
   for (size_t F = 0; F < kNumFlags; F++) {
     const char *Name = FlagDescriptions[F].Name;
     const char *Str = FlagValue(Param, Name);
     if (Str)  {
       if (FlagDescriptions[F].IntFlag) {
         int Val = MyStol(Str);
         *FlagDescriptions[F].IntFlag = Val;
         if (Flags.verbosity >= 2)
           Printf("Flag: %s %d\n", Name, Val);;
         return true;
       } else if (FlagDescriptions[F].UIntFlag) {
         unsigned int Val = std::stoul(Str);
         *FlagDescriptions[F].UIntFlag = Val;
         if (Flags.verbosity >= 2)
           Printf("Flag: %s %u\n", Name, Val);
         return true;
       } else if (FlagDescriptions[F].StrFlag) {
         *FlagDescriptions[F].StrFlag = Str;
         if (Flags.verbosity >= 2)
           Printf("Flag: %s %s\n", Name, Str);
         return true;
       } else {  // Deprecated flag.
         Printf("Flag: %s: deprecated, don't use\n", Name);
         return true;
       }
     }
   }
   Printf("\n\nWARNING: unrecognized flag '%s'; "
          "use -help=1 to list all flags\n\n", Param);
   return true;
 }
References F, FlagDescriptions, Flags, FlagValue(), fuzzer::FlagDescription::IntFlag, kNumFlags, MyStol(), fuzzer::FlagDescription::Name, Printf(), fuzzer::FlagDescription::StrFlag, and fuzzer::FlagDescription::UIntFlag.
Referenced by ParseFlags().
Print()
void fuzzer::Print (const Unit & v, const char * PrintAfter)
Definition at line 34 of file FuzzerUtil.cpp.
{
   PrintHexArray(v.data(), v.size(), PrintAfter);
 }
References PrintHexArray().
PrintASCII() [1/3]
void fuzzer::PrintASCII (const uint8_t * Data, size_t Size, const char * PrintAfter)
Definition at line 49 of file FuzzerUtil.cpp.
{
   for (size_t i = 0; i < Size; i++)
     PrintASCIIByte(Data[i]);
   Printf("%s", PrintAfter);
 }
References PrintASCIIByte(), and Printf().
PrintASCII() [2/3]
void fuzzer::PrintASCII (const Unit & U, const char * PrintAfter)
Definition at line 55 of file FuzzerUtil.cpp.
{
   PrintASCII(U.data(), U.size(), PrintAfter);
 }
References PrintASCII().
PrintASCII() [3/3]
static void fuzzer::PrintASCII (const Word & W, const char * PrintAfter) static
Definition at line 23 of file FuzzerMutate.cpp.
{
   PrintASCII(W.data(), W.size(), PrintAfter);
 }
References fuzzer::FixedWord< kMaxSize >::data(), and fuzzer::FixedWord< kMaxSize >::size().
Referenced by fuzzer::Fuzzer::DumpCurrentUnit(), fuzzer::DictionaryEntry::Print(), PrintASCII(), fuzzer::MutationDispatcher::PrintMutationSequence(), fuzzer::MutationDispatcher::PrintRecommendedDictionary(), fuzzer::TraceState::StopTraceRecording(), and fuzzer::TraceState::TraceMemcmpCallback().
PrintASCIIByte()
void fuzzer::PrintASCIIByte (uint8_t Byte)
Definition at line 38 of file FuzzerUtil.cpp.
{
   if (Byte == '\\')
     Printf("\\\\");
   else if (Byte == '"')
     Printf("\\\"");
   else if (Byte >= 32 && Byte < 127)
     Printf("%c", Byte);
   else
     Printf("\\x%02x", Byte);
 }
References Printf().
Referenced by PrintASCII().
Printf()
void fuzzer::Printf (const char * Fmt, ...)
Definition at line 109 of file FuzzerIO.cpp.
{
   va_list ap;
   va_start(ap, Fmt);
   vfprintf(OutputFile, Fmt, ap);
   va_end(ap);
   fflush(OutputFile);
 }
References OutputFile.
Referenced by fuzzer::InputCorpus::AddFeature(), fuzzer::InputCorpus::AddToCorpus(), fuzzer::Fuzzer::AlarmCallback(), fuzzer::Fuzzer::CheckExitOnSrcPosOrItem(), CopyFileToErr(), fuzzer::Fuzzer::CrashCallback(), fuzzer::Fuzzer::CrashResistantMerge(), fuzzer::Fuzzer::CrashResistantMergeInternalStep(), fuzzer::InputCorpus::DeleteInput(), fuzzer::Fuzzer::DumpCurrentUnit(), FileToVector(), FreeHook(), FuzzerDriver(), fuzzer::Fuzzer::HandleMalloc(), fuzzer::Fuzzer::InterruptCallback(), MallocHook(), fuzzer::Fuzzer::Merge(), MinimizeCrashInput(), MinimizeCrashInputInternalStep(), MissingExternalApiFunction(), NumberOfCpuCores(), ParseDictionaryFile(), ParseOneFlag(), fuzzer::Merger::ParseOrExit(), fuzzer::DictionaryEntry::Print(), PrintASCII(), PrintASCIIByte(), fuzzer::TracePC::PrintCoverage(), fuzzer::InputCorpus::PrintFeatureSet(), fuzzer::Fuzzer::PrintFinalStats(), PrintHelp(), PrintHexArray(), fuzzer::TracePC::PrintModuleInfo(), fuzzer::MutationDispatcher::PrintMutationSequence(), PrintPC(), fuzzer::MutationDispatcher::PrintRecommendedDictionary(), fuzzer::InputCorpus::PrintStats(), fuzzer::Fuzzer::PrintStats(), fuzzer::Fuzzer::PrintStatusForNewUnit(), PulseThread(), ReadDirToVectorOfUnits(), fuzzer::Fuzzer::RereadOutputCorpus(), fuzzer::Fuzzer::RssLimitCallback(), fuzzer::Fuzzer::RunOne(), fuzzer::Fuzzer::SetMaxInputLen(), fuzzer::Fuzzer::ShuffleAndMinimize(), fuzzer::MallocFreeTracer::Start(), fuzzer::MallocFreeTracer::Stop(), fuzzer::TraceState::StopTraceRecording(), fuzzer::TraceState::TraceMemcmpCallback(), fuzzer::TraceState::TraceSwitchCallback(), fuzzer::Fuzzer::TryDetectingAMemoryLeak(), fuzzer::InputCorpus::ValidateFeatureSet(), WarnOnUnsuccessfullMerge(), WorkerThread(), fuzzer::Fuzzer::WriteToOutputCorpus(), and fuzzer::Fuzzer::WriteUnitToFileWithPrefix().
PrintHelp()
static void fuzzer::PrintHelp () static
Definition at line 78 of file FuzzerDriver.cpp.
{
   Printf("Usage:\n");
   auto Prog = ProgName->c_str();
   Printf("\nTo run fuzzing pass 0 or more directories.\n");
   Printf("%s [-flag1=val1 [-flag2=val2 ...] ] [dir1 [dir2 ...] ]\n", Prog);
   Printf("\nTo run individual tests without fuzzing pass 1 or more files:\n");
   Printf("%s [-flag1=val1 [-flag2=val2 ...] ] file1 [file2 ...]\n", Prog);
   Printf("\nFlags: (strictly in form -flag=value)\n");
   size_t MaxFlagLen = 0;
   for (size_t F = 0; F < kNumFlags; F++)
     MaxFlagLen = std::max(strlen(FlagDescriptions[F].Name), MaxFlagLen);
   for (size_t F = 0; F < kNumFlags; F++) {
     const auto &D = FlagDescriptions[F];
     if (strstr(D.Description, "internal flag") == D.Description) continue;
     Printf(" %s", D.Name);
     for (size_t i = 0, n = MaxFlagLen - strlen(D.Name); i < n; i++)
       Printf(" ");
     Printf("\t");
     Printf("%d\t%s\n", D.Default, D.Description);
   }
   Printf("\nFlags starting with '--' will be ignored and "
             "will be passed verbatim to subprocesses.\n");
 }
References F, FlagDescriptions, kNumFlags, n, Printf(), and ProgName.
Referenced by FuzzerDriver().
PrintHexArray() [1/2]
void fuzzer::PrintHexArray (const uint8_t * Data, size_t Size, const char * PrintAfter)
Definition at line 27 of file FuzzerUtil.cpp.
{
   for (size_t i = 0; i < Size; i++)
     Printf("0x%x,", (unsigned)Data[i]);
   Printf("%s", PrintAfter);
 }
References Printf().
Referenced by fuzzer::Fuzzer::DumpCurrentUnit(), and Print().
PrintHexArray() [2/2]
void fuzzer::PrintHexArray (const Unit & U, const char * PrintAfter = "")
PrintPC()
void fuzzer::PrintPC (const char * SymbolizedFMT, const char * FallbackFMT, uintptr_t PC)
Definition at line 191 of file FuzzerUtil.cpp.
{
   if (EF->__sanitizer_symbolize_pc)
     Printf("%s", DescribePC(SymbolizedFMT, PC).c_str());
   else
     Printf(FallbackFMT, PC);
 }
References DescribePC(), EF, PC, and Printf().
Referenced by fuzzer::TracePC::PrintNewPCs().
PulseThread()
static void fuzzer::PulseThread () static
Definition at line 195 of file FuzzerDriver.cpp.
{
   while (true) {
     SleepSeconds(600);
     std::lock_guard<std::mutex> Lock(Mu);
     Printf("pulse...\n");
   }
 }
References Mu, Printf(), and SleepSeconds().
Referenced by RunInMultipleProcesses().
RandCh()
static char fuzzer::RandCh (Random & Rand) static
Definition at line 65 of file FuzzerMutate.cpp.
{
   if (Rand.RandBool()) return Rand(256);
   const char *Special = "!*'();:@&=+$,/?%#[]012Az-`~.\xff\x00";
   return Special[Rand(sizeof(Special) - 1)];
 }
References fuzzer::Random::RandBool().
Referenced by fuzzer::MutationDispatcher::Mutate_ChangeByte(), fuzzer::MutationDispatcher::Mutate_InsertByte(), and fuzzer::MutationDispatcher::MutateImpl().
ReadDirToVectorOfUnits()
void fuzzer::ReadDirToVectorOfUnits (const char * Path, std::vector< Unit > * V, long * Epoch, size_t MaxSize, bool ExitOnError)
Definition at line 69 of file FuzzerIO.cpp.
{
   long E = Epoch ? *Epoch : 0;
   std::vector<std::string> Files;
   ListFilesInDirRecursive(Path, Epoch, &Files, /*TopDir*/true);
   size_t NumLoaded = 0;
   for (size_t i = 0; i < Files.size(); i++) {
     auto &X = Files[i];
     if (Epoch && GetEpoch(X) < E) continue;
     NumLoaded++;
     if ((NumLoaded & (NumLoaded - 1)) == 0 && NumLoaded >= 1024)
       Printf("Loaded %zd/%zd files from %s\n", NumLoaded, Files.size(), Path);
     auto S = FileToVector(X, MaxSize, ExitOnError);
     if (!S.empty())
       V->push_back(S);
   }
 }
References FileToVector(), GetEpoch(), ListFilesInDirRecursive(), and Printf().
Referenced by FuzzerDriver(), fuzzer::Fuzzer::Merge(), and fuzzer::Fuzzer::RereadOutputCorpus().
RemoveFile()
void fuzzer::RemoveFile (const std::string & Path)
Referenced by fuzzer::Fuzzer::CrashResistantMerge(), and fuzzer::InputCorpus::DeleteInput().
RssThread()
static void fuzzer::RssThread (Fuzzer * F, size_t RssLimitMb) static
Definition at line 248 of file FuzzerDriver.cpp.
{
   while (true) {
     SleepSeconds(1);
     size_t Peak = GetPeakRSSMb();
     if (Peak > RssLimitMb)
       F->RssLimitCallback();
   }
 }
References F, GetPeakRSSMb(), fuzzer::Fuzzer::RssLimitCallback(), and SleepSeconds().
Referenced by StartRssThread().
RunInMultipleProcesses()
static int fuzzer::RunInMultipleProcesses (const std::vector< std::string > & Args, unsigned NumWorkers, unsigned NumJobs) static
Definition at line 233 of file FuzzerDriver.cpp.
{
   std::atomic<unsigned> Counter(0);
   std::atomic<bool> HasErrors(false);
   std::string Cmd = CloneArgsWithoutX(Args, "jobs", "workers");
   std::vector<std::thread> V;
   std::thread Pulse(PulseThread);
   Pulse.detach();
   for (unsigned i = 0; i < NumWorkers; i++)
     V.push_back(std::thread(WorkerThread, Cmd, &Counter, NumJobs, &HasErrors));
   for (auto &T : V)
     T.join();
   return HasErrors ? 1 : 0;
 }
References CloneArgsWithoutX(), Counter, PulseThread(), and WorkerThread().
Referenced by FuzzerDriver().
RunOneTest()
int fuzzer::RunOneTest (Fuzzer * F, const char * InputFilePath, size_t MaxLen)
Definition at line 263 of file FuzzerDriver.cpp.
{
   Unit U = FileToVector(InputFilePath);
   if (MaxLen && MaxLen < U.size())
     U.resize(MaxLen);
   F->RunOne(U.data(), U.size());
   F->TryDetectingAMemoryLeak(U.data(), U.size(), true);
   return 0;
 }
References F, FileToVector(), fuzzer::Fuzzer::RunOne(), and fuzzer::Fuzzer::TryDetectingAMemoryLeak().
Referenced by FuzzerDriver().
SearchMemory()
const void* fuzzer::SearchMemory (const void * haystack, size_t haystacklen, const void * needle, size_t needlelen)
Referenced by fuzzer::MutationDispatcher::MakeDictionaryEntryFromCMP(), and fuzzer::TraceState::TryToAddDesiredData().
SetSignalHandler()
void fuzzer::SetSignalHandler (const FuzzingOptions & Options)
Referenced by FuzzerDriver().
Sha1ToString()
std::string fuzzer::Sha1ToString (const uint8_t Sha1[kSHA1NumBytes])
Definition at line 209 of file FuzzerSHA1.cpp.
{
   std::stringstream SS;
   for (int i = 0; i < kSHA1NumBytes; i++)
     SS << std::hex << std::setfill('0') << std::setw(2) << (unsigned)Sha1[i];
   return SS.str();
 }
References kSHA1NumBytes.
Referenced by fuzzer::InputCorpus::AddToCorpus(), fuzzer::InputCorpus::DeleteInput(), fuzzer::Fuzzer::DumpCurrentUnit(), Hash(), and fuzzer::InputCorpus::PrintStats().
SleepSeconds()
void fuzzer::SleepSeconds (int Seconds)
Referenced by PulseThread(), and RssThread().
StartRssThread()
static void fuzzer::StartRssThread (Fuzzer * F, size_t RssLimitMb) static
Definition at line 257 of file FuzzerDriver.cpp.
{
   if (!RssLimitMb) return;
   std::thread T(RssThread, F, RssLimitMb);
   T.detach();
 }
References F, and RssThread().
Referenced by FuzzerDriver().
ToASCII()
bool fuzzer::ToASCII (uint8_t * Data, size_t Size)
Definition at line 59 of file FuzzerUtil.cpp.
{
   bool Changed = false;
   for (size_t i = 0; i < Size; i++) {
     uint8_t &X = Data[i];
     auto NewX = X;
     NewX &= 127;
     if (!isspace(NewX) && !isprint(NewX))
       NewX = ' ';
     Changed |= NewX != X;
     X = NewX;
   }
   return Changed;
 }
Referenced by fuzzer::MutationDispatcher::MutateImpl().
WarnOnUnsuccessfullMerge()
static void fuzzer::WarnOnUnsuccessfullMerge (bool DoWarn) static
Definition at line 219 of file FuzzerLoop.cpp.
{
   if (!DoWarn) return;
   Printf(
    "***\n"
    "***\n"
    "***\n"
    "*** NOTE: merge did not succeed due to a failure on one of the inputs.\n"
    "*** You will need to filter out crashes from the corpus, e.g. like this:\n"
    "***   for f in WITH_CRASHES/*; do ./fuzzer $f && cp $f NO_CRASHES; done\n"
    "*** Future versions may have crash-resistant merge, stay tuned.\n"
    "***\n"
    "***\n"
    "***\n");
 }
References Printf().
Referenced by fuzzer::Fuzzer::DumpCurrentUnit().
WorkerThread()
static void fuzzer::WorkerThread (const std::string & Cmd, std::atomic< unsigned > * Counter, unsigned NumJobs, std::atomic< bool > * HasErrors) static
Definition at line 203 of file FuzzerDriver.cpp.
{
   while (true) {
     unsigned C = (*Counter)++;
     if (C >= NumJobs) break;
     std::string Log = "fuzz-" + std::to_string(C) + ".log";
     std::string ToRun = Cmd + " > " + Log + " 2>&1\n";
     if (Flags.verbosity)
       Printf("%s", ToRun.c_str());
     int ExitCode = ExecuteCommand(ToRun);
     if (ExitCode != 0)
       *HasErrors = true;
     std::lock_guard<std::mutex> Lock(Mu);
     Printf("================== Job %u exited with exit code %d ============\n",
            C, ExitCode);
     fuzzer::CopyFileToErr(Log);
   }
 }
References CopyFileToErr(), ExecuteCommand(), Flags, Mu, Printf(), and httplib::to_string().
Referenced by RunInMultipleProcesses().
WriteToFile()
void fuzzer::WriteToFile (const Unit & U, const std::string & Path)
Definition at line 61 of file FuzzerIO.cpp.
{
   // Use raw C interface because this function may be called from a sig handler.
   FILE *Out = fopen(Path.c_str(), "w");
   if (!Out) return;
   fwrite(U.data(), sizeof(U[0]), U.size(), Out);
   fclose(Out);
 }
Referenced by MinimizeCrashInput(), fuzzer::Fuzzer::WriteToOutputCorpus(), and fuzzer::Fuzzer::WriteUnitToFileWithPrefix().
Variable Documentation
AllocTracer
MallocFreeTracer fuzzer::AllocTracer static
Definition at line 138 of file FuzzerLoop.cpp.
Referenced by fuzzer::Fuzzer::ExecuteCallback(), FreeHook(), and MallocHook().
DoingMyOwnMemmem
bool fuzzer::DoingMyOwnMemmem = false static
Definition at line 35 of file FuzzerTraceState.cpp.
Referenced by __sanitizer_weak_hook_memmem(), fuzzer::ScopedDoingMyOwnMemmem::ScopedDoingMyOwnMemmem(), and fuzzer::ScopedDoingMyOwnMemmem::~ScopedDoingMyOwnMemmem().
EF
ExternalFunctions * fuzzer::EF = nullptr
Definition at line 543 of file FuzzerDriver.cpp.
Referenced by fuzzer::Fuzzer::AlarmCallback(), fuzzer::Fuzzer::CrashCallback(), DescribePC(), DupAndCloseStderr(), FreeHook(), fuzzer::Fuzzer::Fuzzer(), FuzzerDriver(), fuzzer::Fuzzer::HandleMalloc(), MallocHook(), fuzzer::MutationDispatcher::Mutate_Custom(), fuzzer::MutationDispatcher::Mutate_CustomCrossOver(), fuzzer::Fuzzer::PrepareCounters(), fuzzer::TracePC::PrintCoverage(), PrintPC(), fuzzer::Fuzzer::RecordMaxCoverage(), fuzzer::Fuzzer::ResetCounters(), fuzzer::Fuzzer::ResetEdgeCoverage(), fuzzer::Fuzzer::RssLimitCallback(), fuzzer::Fuzzer::SetDeathCallback(), TEST(), TestAddWordFromDictionary(), TestAddWordFromDictionaryWithHint(), TestChangeASCIIInteger(), TestChangeBinaryInteger(), TestChangeBit(), TestChangeByte(), TestCopyPart(), TestEraseBytes(), TestInsertByte(), TestInsertRepeatedBytes(), TestShuffleBytes(), and fuzzer::Fuzzer::TryDetectingAMemoryLeak().
F
Fuzzer* fuzzer::F static
Definition at line 59 of file FuzzerLoop.cpp.
Referenced by fuzzer::Fuzzer::CrashResistantMerge(), fuzzer::Fuzzer::CrashResistantMergeInternalStep(), fuzzer::Fuzzer::Fuzzer(), FuzzerDriver(), LLVMFuzzerMutate(), MallocHook(), MinimizeCrashInputInternalStep(), ParseFlags(), ParseOneFlag(), PrintHelp(), RssThread(), RunOneTest(), StartRssThread(), fuzzer::Fuzzer::StaticAlarmCallback(), fuzzer::Fuzzer::StaticCrashSignalCallback(), fuzzer::Fuzzer::StaticDeathCallback(), and fuzzer::Fuzzer::StaticInterruptCallback().
FlagDescriptions
const FlagDescription fuzzer::FlagDescriptions[] static
Initial value:
{
#define FUZZER_DEPRECATED_FLAG(Name)
#define FUZZER_FLAG_INT(Name, Default, Description)
#define FUZZER_FLAG_UNSIGNED(Name, Default, Description)
#define FUZZER_FLAG_STRING(Name, Description)
# 65 "/home/komal/workspace/Denso/container-manager/mc_orchestrator/json-3.7.3/test/thirdparty/Fuzzer/FuzzerDriver.cpp" 2
}
Definition at line 55 of file FuzzerDriver.cpp.
Referenced by ParseFlags(), ParseOneFlag(), and PrintHelp().
Flags
struct { ... } fuzzer::Flags
Referenced by FuzzerDriver(), MinimizeCrashInput(), ParseOneFlag(), and WorkerThread().
Inputs
std::vector<std::string>* fuzzer::Inputs static
Definition at line 75 of file FuzzerDriver.cpp.
Referenced by AllInputsAreFiles(), FuzzerDriver(), MinimizeCrashInput(), MinimizeCrashInputInternalStep(), and ParseFlags().
kMaxUnitSizeToPrint
const size_t fuzzer::kMaxUnitSizeToPrint = 256 static
Definition at line 41 of file FuzzerLoop.cpp.
Referenced by fuzzer::Fuzzer::DumpCurrentUnit(), and fuzzer::Fuzzer::WriteUnitToFileWithPrefix().
kNumFlags
const size_t fuzzer::kNumFlags static
Initial value:
=
    sizeof(FlagDescriptions) / sizeof(FlagDescriptions[0])
Definition at line 72 of file FuzzerDriver.cpp.
Referenced by ParseFlags(), ParseOneFlag(), and PrintHelp().
kSHA1NumBytes
const int fuzzer::kSHA1NumBytes = 20 static
Definition at line 22 of file FuzzerSHA1.h.
Referenced by fuzzer::InputCorpus::AddToCorpus(), Hash(), and Sha1ToString().
Mu
std::mutex fuzzer::Mu static
Definition at line 193 of file FuzzerDriver.cpp.
Referenced by PulseThread(), and WorkerThread().
OutputFile
FILE* fuzzer::OutputFile = stderr static
Definition at line 24 of file FuzzerIO.cpp.
Referenced by DupAndCloseStderr(), and Printf().
ProgName
std::string* fuzzer::ProgName static
Definition at line 76 of file FuzzerDriver.cpp.
Referenced by FuzzerDriver(), and PrintHelp().
RecordingMemcmp
bool fuzzer::RecordingMemcmp = false static
Definition at line 33 of file FuzzerTraceState.cpp.
Referenced by __sanitizer_weak_hook_memcmp(), __sanitizer_weak_hook_strcmp(), __sanitizer_weak_hook_strncmp(), fuzzer::TraceState::StartTraceRecording(), fuzzer::TraceState::StopTraceRecording(), and fuzzer::TraceState::TraceMemcmpCallback().
RecordingMemmem
bool fuzzer::RecordingMemmem = false static
Definition at line 34 of file FuzzerTraceState.cpp.
Referenced by fuzzer::TraceState::AddInterestingWord(), and fuzzer::TraceState::StartTraceRecording().
TPC
TracePC fuzzer::TPC
Definition at line 29 of file FuzzerTracePC.cpp.
Referenced by __attribute__(), __sanitizer_weak_hook_memcmp(), __sanitizer_weak_hook_strcmp(), __sanitizer_weak_hook_strncmp(), fuzzer::TracePC::AddValueForMemcmp(), fuzzer::TracePC::AddValueForStrcmp(), fuzzer::Fuzzer::CheckExitOnSrcPosOrItem(), fuzzer::Fuzzer::CrashResistantMergeInternalStep(), fuzzer::Fuzzer::ExecuteCallback(), fuzzer::Fuzzer::FindExtraUnits(), fuzzer::Fuzzer::Fuzzer(), FuzzerDriver(), fuzzer::MutationDispatcher::Mutate_AddWordFromTORC(), fuzzer::Fuzzer::PrintFinalStats(), fuzzer::Fuzzer::PrintStats(), fuzzer::Fuzzer::ReportNewCoverage(), and fuzzer::Fuzzer::RunOne().
TS
TraceState* fuzzer::TS static
Definition at line 229 of file FuzzerTraceState.cpp.
Referenced by __sanitizer_weak_hook_memcmp(), __sanitizer_weak_hook_memmem(), __sanitizer_weak_hook_strcasestr(), __sanitizer_weak_hook_strcmp(), __sanitizer_weak_hook_strncmp(), __sanitizer_weak_hook_strstr(), fuzzer::Fuzzer::InitializeTraceState(), fuzzer::Fuzzer::StartTraceRecording(), and fuzzer::Fuzzer::StopTraceRecording().