Mixed Criticality Orchestrator: httplib::detail Namespace Reference
httplib::detail Namespace Reference
Namespaces
udl
Classes
class BufferStream
struct ci
class compressor
class ContentProviderAdapter
class decompressor
class MatcherBase
class mmap
class MultipartFormDataParser
class nocompressor
class PathParamsMatcher
class RegexMatcher
struct scope_exit
class SocketStream
class stream_line_reader
Enumerations
enum EncodingType { EncodingType::None = 0, EncodingType::Gzip, EncodingType::Brotli }
Functions
template<class T , class... Args>
std::enable_if<!std::is_array< T >::value, std::unique_ptr< T > >::type make_unique (Args &&...args)
template<class T >
std::enable_if< std::is_array< T >::value, std::unique_ptr< T > >::type make_unique (std::size_t n)
ssize_t write_headers (Stream &strm, const Headers &headers)
template<typename T , typename U >
void duration_to_sec_and_usec (const T &duration, U callback)
uint64_t get_header_value_u64 (const Headers &headers, const std::string &key, size_t id, uint64_t def)
std::string encode_query_param (const std::string &value)
std::string decode_url (const std::string &s, bool convert_plus_to_space)
void read_file (const std::string &path, std::string &out)
std::string trim_copy (const std::string &s)
void split (const char *b, const char *e, char d, std::function< void(const char *, const char *)> fn)
void split (const char *b, const char *e, char d, size_t m, std::function< void(const char *, const char *)> fn)
bool process_client_socket (socket_t sock, time_t read_timeout_sec, time_t read_timeout_usec, time_t write_timeout_sec, time_t write_timeout_usec, std::function< bool(Stream &)> callback)
socket_t create_client_socket (const std::string &host, const std::string &ip, int port, int address_family, bool tcp_nodelay, SocketOptions socket_options, time_t connection_timeout_sec, time_t connection_timeout_usec, time_t read_timeout_sec, time_t read_timeout_usec, time_t write_timeout_sec, time_t write_timeout_usec, const std::string &intf, Error &error)
const char * get_header_value (const Headers &headers, const std::string &key, size_t id=0, const char *def=nullptr)
std::string params_to_query_str (const Params &params)
void parse_query_text (const std::string &s, Params &params)
bool parse_multipart_boundary (const std::string &content_type, std::string &boundary)
bool parse_range_header (const std::string &s, Ranges &ranges)
int close_socket (socket_t sock)
ssize_t send_socket (socket_t sock, const void *ptr, size_t size, int flags)
ssize_t read_socket (socket_t sock, void *ptr, size_t size, int flags)
EncodingType encoding_type (const Request &req, const Response &res)
bool is_hex (char c, int &v)
bool from_hex_to_i (const std::string &s, size_t i, size_t cnt, int &val)
std::string from_i_to_hex (size_t n)
size_t to_utf8 (int code, char *buff)
std::string base64_encode (const std::string &in)
bool is_file (const std::string &path)
bool is_dir (const std::string &path)
bool is_valid_path (const std::string &path)
std::string encode_url (const std::string &s)
std::string file_extension (const std::string &path)
bool is_space_or_tab (char c)
std::pair< size_t, size_t > trim (const char *b, const char *e, size_t left, size_t right)
std::string trim_double_quotes_copy (const std::string &s)
template<typename T >
ssize_t handle_EINTR (T fn)
ssize_t select_read (socket_t sock, time_t sec, time_t usec)
ssize_t select_write (socket_t sock, time_t sec, time_t usec)
Error wait_until_socket_is_ready (socket_t sock, time_t sec, time_t usec)
bool is_socket_alive (socket_t sock)
bool keep_alive (socket_t sock, time_t keep_alive_timeout_sec)
template<typename T >
bool process_server_socket_core (const std::atomic< socket_t > &svr_sock, socket_t sock, size_t keep_alive_max_count, time_t keep_alive_timeout_sec, T callback)
template<typename T >
bool process_server_socket (const std::atomic< socket_t > &svr_sock, socket_t sock, size_t keep_alive_max_count, time_t keep_alive_timeout_sec, time_t read_timeout_sec, time_t read_timeout_usec, time_t write_timeout_sec, time_t write_timeout_usec, T callback)
int shutdown_socket (socket_t sock)
template<typename BindOrConnect >
socket_t create_socket (const std::string &host, const std::string &ip, int port, int address_family, int socket_flags, bool tcp_nodelay, SocketOptions socket_options, BindOrConnect bind_or_connect)
void set_nonblocking (socket_t sock, bool nonblocking)
bool is_connection_error ()
bool bind_ip_address (socket_t sock, const std::string &host)
std::string if2ip (int address_family, const std::string &ifn)
bool get_ip_and_port (const struct sockaddr_storage &addr, socklen_t addr_len, std::string &ip, int &port)
void get_local_ip_and_port (socket_t sock, std::string &ip, int &port)
void get_remote_ip_and_port (socket_t sock, std::string &ip, int &port)
constexpr unsigned int str2tag_core (const char *s, size_t l, unsigned int h)
unsigned int str2tag (const std::string &s)
std::string find_content_type (const std::string &path, const std::map< std::string, std::string > &user_data, const std::string &default_content_type)
bool can_compress_content_type (const std::string &content_type)
bool has_header (const Headers &headers, const std::string &key)
bool compare_case_ignore (const std::string &a, const std::string &b)
template<typename T >
bool parse_header (const char *beg, const char *end, T fn)
bool read_headers (Stream &strm, Headers &headers)
bool read_content_with_length (Stream &strm, uint64_t len, Progress progress, ContentReceiverWithProgress out)
void skip_content_with_length (Stream &strm, uint64_t len)
bool read_content_without_length (Stream &strm, ContentReceiverWithProgress out)
template<typename T >
bool read_content_chunked (Stream &strm, T &x, ContentReceiverWithProgress out)
bool is_chunked_transfer_encoding (const Headers &headers)
template<typename T , typename U >
bool prepare_content_receiver (T &x, int &status, ContentReceiverWithProgress receiver, bool decompress, U callback)
template<typename T >
bool read_content (Stream &strm, T &x, size_t payload_max_length, int &status, Progress progress, ContentReceiverWithProgress receiver, bool decompress)
bool write_data (Stream &strm, const char *d, size_t l)
template<typename T >
bool write_content (Stream &strm, const ContentProvider &content_provider, size_t offset, size_t length, T is_shutting_down, Error &error)
template<typename T >
bool write_content (Stream &strm, const ContentProvider &content_provider, size_t offset, size_t length, const T &is_shutting_down)
template<typename T >
bool write_content_without_length (Stream &strm, const ContentProvider &content_provider, const T &is_shutting_down)
template<typename T , typename U >
bool write_content_chunked (Stream &strm, const ContentProvider &content_provider, const T &is_shutting_down, U &compressor, Error &error)
template<typename T , typename U >
bool write_content_chunked (Stream &strm, const ContentProvider &content_provider, const T &is_shutting_down, U &compressor)
template<typename T >
bool redirect (T &cli, Request &req, Response &res, const std::string &path, const std::string &location, Error &error)
void parse_disposition_params (const std::string &s, Params &params)
std::string to_lower (const char *beg, const char *end)
std::string random_string (size_t length)
std::string make_multipart_data_boundary ()
bool is_multipart_boundary_chars_valid (const std::string &boundary)
template<typename T >
std::string serialize_multipart_formdata_item_begin (const T &item, const std::string &boundary)
std::string serialize_multipart_formdata_item_end ()
std::string serialize_multipart_formdata_finish (const std::string &boundary)
std::string serialize_multipart_formdata_get_content_type (const std::string &boundary)
std::string serialize_multipart_formdata (const MultipartFormDataItems &items, const std::string &boundary, bool finish=true)
bool range_error (Request &req, Response &res)
std::pair< size_t, size_t > get_range_offset_and_length (Range r, size_t content_length)
std::string make_content_range_header_field (const std::pair< size_t, size_t > &offset_and_length, size_t content_length)
template<typename SToken , typename CToken , typename Content >
bool process_multipart_ranges_data (const Request &req, const std::string &boundary, const std::string &content_type, size_t content_length, SToken stoken, CToken ctoken, Content content)
void make_multipart_ranges_data (const Request &req, Response &res, const std::string &boundary, const std::string &content_type, size_t content_length, std::string &data)
size_t get_multipart_ranges_data_length (const Request &req, const std::string &boundary, const std::string &content_type, size_t content_length)
template<typename T >
bool write_multipart_ranges_data (Stream &strm, const Request &req, Response &res, const std::string &boundary, const std::string &content_type, size_t content_length, const T &is_shutting_down)
bool expect_content (const Request &req)
bool has_crlf (const std::string &s)
bool parse_www_authenticate (const Response &res, std::map< std::string, std::string > &auth, bool is_proxy)
Enumeration Type Documentation
EncodingType
enum httplib::detail::EncodingType strong
Enumerator
None
Gzip
Brotli
Definition at line 2125 of file httplib.h.
 { None = 0, Gzip, Brotli };
Function Documentation
base64_encode()
std::string httplib::detail::base64_encode (const std::string & in) inline
Definition at line 2365 of file httplib.h.
{
   static const auto lookup =
       "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
   std::string out;
   out.reserve(in.size());
   auto val = 0;
   auto valb = -6;
   for (auto c : in) {
     val = (val << 8) + static_cast<uint8_t>(c);
     valb += 8;
     while (valb >= 0) {
       out.push_back(lookup[(val >> valb) & 0x3F]);
       valb -= 6;
     }
   }
   if (valb > -6) { out.push_back(lookup[((val << 8) >> (valb + 8)) & 0x3F]); }
   while (out.size() % 4) {
     out.push_back('=');
   }
   return out;
 }
References c.
Referenced by httplib::make_basic_authentication_header().
bind_ip_address()
bool httplib::detail::bind_ip_address (socket_t sock, const std::string & host) inline
Definition at line 3216 of file httplib.h.
{
   struct addrinfo hints;
   struct addrinfo *result;
   memset(&hints, 0, sizeof(struct addrinfo));
   hints.ai_family = AF_UNSPEC;
   hints.ai_socktype = SOCK_STREAM;
   hints.ai_protocol = 0;
   if (getaddrinfo(host.c_str(), "0", &hints, &result)) { return false; }
   auto ret = false;
   for (auto rp = result; rp; rp = rp->ai_next) {
     const auto &ai = *rp;
     if (!::bind(sock, ai.ai_addr, static_cast<socklen_t>(ai.ai_addrlen))) {
       ret = true;
       break;
     }
   }
   freeaddrinfo(result);
   return ret;
 }
References result.
Referenced by create_client_socket().
can_compress_content_type()
bool httplib::detail::can_compress_content_type (const std::string & content_type) inline
Definition at line 3512 of file httplib.h.
{
   using udl::operator""_t;
   auto tag = str2tag(content_type);
   switch (tag) {
   case "image/svg+xml"_t:
   case "application/javascript"_t:
   case "application/json"_t:
   case "application/xml"_t:
   case "application/protobuf"_t:
   case "application/xhtml+xml"_t: return true;
   default:
     return !content_type.rfind("text/", 0) && tag != "text/event-stream"_t;
   }
 }
References str2tag().
Referenced by encoding_type().
close_socket()
int httplib::detail::close_socket (socket_t sock) inline
Definition at line 2771 of file httplib.h.
{
 #ifdef _WIN32
   return closesocket(sock);
 #else
   return close(sock);
 #endif
 }
Referenced by httplib::ClientImpl::close_socket(), create_socket(), httplib::Server::listen_internal(), httplib::Server::process_and_close_socket(), and httplib::Server::stop().
compare_case_ignore()
bool httplib::detail::compare_case_ignore (const std::string & a, const std::string & b) inline
Definition at line 3772 of file httplib.h.
{
   if (a.size() != b.size()) { return false; }
   for (size_t i = 0; i < b.size(); i++) {
     if (::tolower(a[i]) != ::tolower(b[i])) { return false; }
   }
   return true;
 }
Referenced by is_chunked_transfer_encoding(), and parse_header().
create_client_socket()
socket_t httplib::detail::create_client_socket (const std::string & host, const std::string & ip, int port, int address_family, bool tcp_nodelay, SocketOptions socket_options, time_t connection_timeout_sec, time_t connection_timeout_usec, time_t read_timeout_sec, time_t read_timeout_usec, time_t write_timeout_sec, time_t write_timeout_usec, const std::string & intf, Error & error) inline
Definition at line 3283 of file httplib.h.
{
   auto sock = create_socket(
       host, ip, port, address_family, 0, tcp_nodelay, std::move(socket_options),
       [&](socket_t sock2, struct addrinfo &ai) -> bool {
         if (!intf.empty()) {
 #ifdef USE_IF2IP
           auto ip_from_if = if2ip(address_family, intf);
           if (ip_from_if.empty()) { ip_from_if = intf; }
           if (!bind_ip_address(sock2, ip_from_if)) {
             error = Error::BindIPAddress;
             return false;
           }
 #endif
         }
         set_nonblocking(sock2, true);
         auto ret =
             ::connect(sock2, ai.ai_addr, static_cast<socklen_t>(ai.ai_addrlen));
         if (ret < 0) {
           if (is_connection_error()) {
             error = Error::Connection;
             return false;
           }
           error = wait_until_socket_is_ready(sock2, connection_timeout_sec,
                                              connection_timeout_usec);
           if (error != Error::Success) { return false; }
         }
         set_nonblocking(sock2, false);
         {
 #ifdef _WIN32
           auto timeout = static_cast<uint32_t>(read_timeout_sec * 1000 +
                                                read_timeout_usec / 1000);
           setsockopt(sock2, SOL_SOCKET, SO_RCVTIMEO,
                      reinterpret_cast<const char *>(&timeout), sizeof(timeout));
 #else
           timeval tv;
           tv.tv_sec = static_cast<long>(read_timeout_sec);
           tv.tv_usec = static_cast<decltype(tv.tv_usec)>(read_timeout_usec);
           setsockopt(sock2, SOL_SOCKET, SO_RCVTIMEO,
                      reinterpret_cast<const void *>(&tv), sizeof(tv));
 #endif
         }
         {
 #ifdef _WIN32
           auto timeout = static_cast<uint32_t>(write_timeout_sec * 1000 +
                                                write_timeout_usec / 1000);
           setsockopt(sock2, SOL_SOCKET, SO_SNDTIMEO,
                      reinterpret_cast<const char *>(&timeout), sizeof(timeout));
 #else
           timeval tv;
           tv.tv_sec = static_cast<long>(write_timeout_sec);
           tv.tv_usec = static_cast<decltype(tv.tv_usec)>(write_timeout_usec);
           setsockopt(sock2, SOL_SOCKET, SO_SNDTIMEO,
                      reinterpret_cast<const void *>(&tv), sizeof(tv));
 #endif
         }
         error = Error::Success;
         return true;
       });
   if (sock != INVALID_SOCKET) {
     error = Error::Success;
   } else {
     if (error == Error::Success) { error = Error::Connection; }
   }
   return sock;
 }
References bind_ip_address(), httplib::BindIPAddress, httplib::Connection, create_socket(), if(), is_connection_error(), set_nonblocking(), httplib::Success, and wait_until_socket_is_ready().
Referenced by httplib::ClientImpl::create_client_socket().
create_socket()
template<typename BindOrConnect > socket_t httplib::detail::create_socket (const std::string & host, const std::string & ip, int port, int address_family, int socket_flags, bool tcp_nodelay, SocketOptions socket_options, BindOrConnect bind_or_connect)
Definition at line 3065 of file httplib.h.
{
   // Get address info
   const char *node = nullptr;
   struct addrinfo hints;
   struct addrinfo *result;
   memset(&hints, 0, sizeof(struct addrinfo));
   hints.ai_socktype = SOCK_STREAM;
   hints.ai_protocol = 0;
   if (!ip.empty()) {
     node = ip.c_str();
     // Ask getaddrinfo to convert IP in c-string to address
     hints.ai_family = AF_UNSPEC;
     hints.ai_flags = AI_NUMERICHOST;
   } else {
     if (!host.empty()) { node = host.c_str(); }
     hints.ai_family = address_family;
     hints.ai_flags = socket_flags;
   }
 #ifndef _WIN32
   if (hints.ai_family == AF_UNIX) {
     const auto addrlen = host.length();
     if (addrlen > sizeof(sockaddr_un::sun_path)) { return INVALID_SOCKET; }
     auto sock = socket(hints.ai_family, hints.ai_socktype, hints.ai_protocol);
     if (sock != INVALID_SOCKET) {
       sockaddr_un addr{};
       addr.sun_family = AF_UNIX;
       std::copy(host.begin(), host.end(), addr.sun_path);
       hints.ai_addr = reinterpret_cast<sockaddr *>(&addr);
       hints.ai_addrlen = static_cast<socklen_t>(
           sizeof(addr) - sizeof(addr.sun_path) + addrlen);
       fcntl(sock, F_SETFD, FD_CLOEXEC);
       if (socket_options) { socket_options(sock); }
       if (!bind_or_connect(sock, hints)) {
         close_socket(sock);
         sock = INVALID_SOCKET;
       }
     }
     return sock;
   }
 #endif
   auto service = std::to_string(port);
   if (getaddrinfo(node, service.c_str(), &hints, &result)) {
 #if defined __linux__ && !defined __ANDROID__
     res_init();
 #endif
     return INVALID_SOCKET;
   }
   for (auto rp = result; rp; rp = rp->ai_next) {
     // Create a socket
 #ifdef _WIN32
     auto sock =
         WSASocketW(rp->ai_family, rp->ai_socktype, rp->ai_protocol, nullptr, 0,
                    WSA_FLAG_NO_HANDLE_INHERIT | WSA_FLAG_OVERLAPPED);
     if (sock == INVALID_SOCKET) {
       sock = socket(rp->ai_family, rp->ai_socktype, rp->ai_protocol);
     }
 #else
     auto sock = socket(rp->ai_family, rp->ai_socktype, rp->ai_protocol);
 #endif
     if (sock == INVALID_SOCKET) { continue; }
 #ifndef _WIN32
     if (fcntl(sock, F_SETFD, FD_CLOEXEC) == -1) {
       close_socket(sock);
       continue;
     }
 #endif
     if (tcp_nodelay) {
       auto yes = 1;
 #ifdef _WIN32
       setsockopt(sock, IPPROTO_TCP, TCP_NODELAY,
                  reinterpret_cast<const char *>(&yes), sizeof(yes));
 #else
       setsockopt(sock, IPPROTO_TCP, TCP_NODELAY,
                  reinterpret_cast<const void *>(&yes), sizeof(yes));
 #endif
     }
     if (socket_options) { socket_options(sock); }
     if (rp->ai_family == AF_INET6) {
       auto no = 0;
 #ifdef _WIN32
       setsockopt(sock, IPPROTO_IPV6, IPV6_V6ONLY,
                  reinterpret_cast<const char *>(&no), sizeof(no));
 #else
       setsockopt(sock, IPPROTO_IPV6, IPV6_V6ONLY,
                  reinterpret_cast<const void *>(&no), sizeof(no));
 #endif
     }
     // bind or connect
     if (bind_or_connect(sock, *rp)) {
       freeaddrinfo(result);
       return sock;
     }
     close_socket(sock);
   }
   freeaddrinfo(result);
   return INVALID_SOCKET;
 }
References addr, close_socket(), INVALID_SOCKET, result, and httplib::to_string().
Referenced by create_client_socket(), and httplib::Server::create_server_socket().
decode_url()
std::string httplib::detail::decode_url (const std::string & s, bool convert_plus_to_space) inline
Definition at line 2502 of file httplib.h.
{
   std::string result;
   for (size_t i = 0; i < s.size(); i++) {
     if (s[i] == '%' && i + 1 < s.size()) {
       if (s[i + 1] == 'u') {
         auto val = 0;
         if (from_hex_to_i(s, i + 2, 4, val)) {
           // 4 digits Unicode codes
           char buff[4];
           size_t len = to_utf8(val, buff);
           if (len > 0) { result.append(buff, len); }
           i += 5; // 'u0000'
         } else {
           result += s[i];
         }
       } else {
         auto val = 0;
         if (from_hex_to_i(s, i + 1, 2, val)) {
           // 2 digits hex codes
           result += static_cast<char>(val);
           i += 2; // '00'
         } else {
           result += s[i];
         }
       }
     } else if (convert_plus_to_space && s[i] == '+') {
       result += ' ';
     } else {
       result += s[i];
     }
   }
   return result;
 }
References from_hex_to_i(), result, and to_utf8().
Referenced by httplib::detail::MultipartFormDataParser::parse(), parse_header(), and httplib::ClientImpl::redirect().
duration_to_sec_and_usec()
template<typename T , typename U > void httplib::detail::duration_to_sec_and_usec (const T & duration, U callback) inline
Definition at line 1803 of file httplib.h.
{
   auto sec = std::chrono::duration_cast<std::chrono::seconds>(duration).count();
   auto usec = std::chrono::duration_cast<std::chrono::microseconds>(
                   duration - std::chrono::seconds(sec))
                   .count();
   callback(static_cast<time_t>(sec), static_cast<time_t>(usec));
 }
References sec.
Referenced by httplib::ClientImpl::set_connection_timeout(), httplib::Server::set_idle_interval(), httplib::Server::set_read_timeout(), httplib::ClientImpl::set_read_timeout(), httplib::Server::set_write_timeout(), and httplib::ClientImpl::set_write_timeout().
encode_query_param()
std::string httplib::detail::encode_query_param (const std::string & value) inline
Definition at line 2449 of file httplib.h.
{
   std::ostringstream escaped;
   escaped.fill('0');
   escaped << std::hex;
   for (auto c : value) {
     if (std::isalnum(static_cast<uint8_t>(c)) || c == '-' || c == '_' ||
         c == '.' || c == '!' || c == '~' || c == '*' || c == '\'' || c == '(' ||
         c == ')') {
       escaped << c;
     } else {
       escaped << std::uppercase;
       escaped << '%' << std::setw(2)
               << static_cast<int>(static_cast<unsigned char>(c));
       escaped << std::nouppercase;
     }
   }
   return escaped.str();
 }
References c.
Referenced by params_to_query_str().
encode_url()
std::string httplib::detail::encode_url (const std::string & s) inline
Definition at line 2470 of file httplib.h.
{
   std::string result;
   result.reserve(s.size());
   for (size_t i = 0; s[i]; i++) {
     switch (s[i]) {
     case ' ': result += "%20"; break;
     case '+': result += "%2B"; break;
     case '\r': result += "%0D"; break;
     case '\n': result += "%0A"; break;
     case '\'': result += "%27"; break;
     case ',': result += "%2C"; break;
     // case ':': result += "%3A"; break; // ok? probably...
     case ';': result += "%3B"; break;
     default:
       auto c = static_cast<uint8_t>(s[i]);
       if (c >= 0x80) {
         result += '%';
         char hex[4];
         auto len = snprintf(hex, sizeof(hex) - 1, "%02X", c);
         assert(len == 2);
         result.append(hex, static_cast<size_t>(len));
       } else {
         result += s[i];
       }
       break;
     }
   }
   return result;
 }
References assert(), c, and result.
Referenced by httplib::ClientImpl::write_request().
encoding_type()
EncodingType httplib::detail::encoding_type (const Request & req, const Response & res) inline
Definition at line 3530 of file httplib.h.
{
   auto ret =
       detail::can_compress_content_type(res.get_header_value("Content-Type"));
   if (!ret) { return EncodingType::None; }
   const auto &s = req.get_header_value("Accept-Encoding");
   (void)(s);
 #ifdef CPPHTTPLIB_BROTLI_SUPPORT
   // TODO: 'Accept-Encoding' has br, not br;q=0
   ret = s.find("br") != std::string::npos;
   if (ret) { return EncodingType::Brotli; }
 #endif
 #ifdef CPPHTTPLIB_ZLIB_SUPPORT
   // TODO: 'Accept-Encoding' has gzip, not gzip;q=0
   ret = s.find("gzip") != std::string::npos;
   if (ret) { return EncodingType::Gzip; }
 #endif
   return EncodingType::None;
 }
References Brotli, can_compress_content_type(), httplib::Request::get_header_value(), httplib::Response::get_header_value(), Gzip, None, and nlohmann::detail::void().
Referenced by httplib::Server::apply_ranges(), and httplib::Server::write_content_with_provider().
expect_content()
bool httplib::detail::expect_content (const Request & req) inline
Definition at line 4905 of file httplib.h.
{
   if (req.method == "POST" || req.method == "PUT" || req.method == "PATCH" ||
       req.method == "PRI" || req.method == "DELETE") {
     return true;
   }
   // TODO: check if Content-Length is set
   return false;
 }
References httplib::Request::method.
Referenced by httplib::Server::routing().
file_extension()
std::string httplib::detail::file_extension (const std::string & path) inline
Definition at line 2548 of file httplib.h.
{
   std::smatch m;
   static auto re = std::regex("\\.([a-zA-Z0-9]+)$");
   if (std::regex_search(path, m, re)) { return m[1].str(); }
   return std::string();
 }
Referenced by find_content_type().
find_content_type()
std::string httplib::detail::find_content_type (const std::string & path, const std::map< std::string, std::string > & user_data, const std::string & default_content_type) inline
Definition at line 3447 of file httplib.h.
{
   auto ext = file_extension(path);
   auto it = user_data.find(ext);
   if (it != user_data.end()) { return it->second; }
   using udl::operator""_t;
   switch (str2tag(ext)) {
   default: return default_content_type;
   case "css"_t: return "text/css";
   case "csv"_t: return "text/csv";
   case "htm"_t:
   case "html"_t: return "text/html";
   case "js"_t:
   case "mjs"_t: return "text/javascript";
   case "txt"_t: return "text/plain";
   case "vtt"_t: return "text/vtt";
   case "apng"_t: return "image/apng";
   case "avif"_t: return "image/avif";
   case "bmp"_t: return "image/bmp";
   case "gif"_t: return "image/gif";
   case "png"_t: return "image/png";
   case "svg"_t: return "image/svg+xml";
   case "webp"_t: return "image/webp";
   case "ico"_t: return "image/x-icon";
   case "tif"_t: return "image/tiff";
   case "tiff"_t: return "image/tiff";
   case "jpg"_t:
   case "jpeg"_t: return "image/jpeg";
   case "mp4"_t: return "video/mp4";
   case "mpeg"_t: return "video/mpeg";
   case "webm"_t: return "video/webm";
   case "mp3"_t: return "audio/mp3";
   case "mpga"_t: return "audio/mpeg";
   case "weba"_t: return "audio/webm";
   case "wav"_t: return "audio/wave";
   case "otf"_t: return "font/otf";
   case "ttf"_t: return "font/ttf";
   case "woff"_t: return "font/woff";
   case "woff2"_t: return "font/woff2";
   case "7z"_t: return "application/x-7z-compressed";
   case "atom"_t: return "application/atom+xml";
   case "pdf"_t: return "application/pdf";
   case "json"_t: return "application/json";
   case "rss"_t: return "application/rss+xml";
   case "tar"_t: return "application/x-tar";
   case "xht"_t:
   case "xhtml"_t: return "application/xhtml+xml";
   case "xslt"_t: return "application/xslt+xml";
   case "xml"_t: return "application/xml";
   case "gz"_t: return "application/gzip";
   case "zip"_t: return "application/zip";
   case "wasm"_t: return "application/wasm";
   }
 }
References file_extension(), and str2tag().
Referenced by httplib::Server::handle_file_request().
from_hex_to_i()
bool httplib::detail::from_hex_to_i (const std::string & s, size_t i, size_t cnt, int & val) inline
Definition at line 2304 of file httplib.h.
{
   if (i >= s.size()) { return false; }
   val = 0;
   for (; cnt; i++, cnt--) {
     if (!s[i]) { return false; }
     auto v = 0;
     if (is_hex(s[i], v)) {
       val = val * 16 + v;
     } else {
       return false;
     }
   }
   return true;
 }
References is_hex().
Referenced by decode_url().
from_i_to_hex()
std::string httplib::detail::from_i_to_hex (size_t n) inline
Definition at line 2321 of file httplib.h.
{
   static const auto charset = "0123456789abcdef";
   std::string ret;
   do {
     ret = charset[n & 15] + ret;
     n >>= 4;
   } while (n > 0);
   return ret;
 }
References n.
Referenced by write_content_chunked().
get_header_value()
const char * httplib::detail::get_header_value (const Headers & headers, const std::string & key, size_t id = 0, const char * def = nullptr) inline
Definition at line 3762 of file httplib.h.
{
   auto rng = headers.equal_range(key);
   auto it = rng.first;
   std::advance(it, static_cast<ssize_t>(id));
   if (it != rng.second) { return it->second.c_str(); }
   return def;
 }
Referenced by httplib::Request::get_header_value(), httplib::Response::get_header_value(), httplib::Result::get_request_header_value(), is_chunked_transfer_encoding(), and httplib::Request::is_multipart_form_data().
get_header_value_u64()
uint64_t httplib::detail::get_header_value_u64 (const Headers & headers, const std::string & key, size_t id, uint64_t def) inline
Definition at line 1811 of file httplib.h.
{
   auto rng = headers.equal_range(key);
   auto it = rng.first;
   std::advance(it, static_cast<ssize_t>(id));
   if (it != rng.second) {
     return std::strtoull(it->second.data(), nullptr, 10);
   }
   return def;
 }
Referenced by httplib::Request::get_header_value_u64(), httplib::Response::get_header_value_u64(), and httplib::Result::get_request_header_value_u64().
get_ip_and_port()
bool httplib::detail::get_ip_and_port (const struct sockaddr_storage & addr, socklen_t addr_len, std::string & ip, int & port) inline
Definition at line 3363 of file httplib.h.
{
   if (addr.ss_family == AF_INET) {
     port = ntohs(reinterpret_cast<const struct sockaddr_in *>(&addr)->sin_port);
   } else if (addr.ss_family == AF_INET6) {
     port =
         ntohs(reinterpret_cast<const struct sockaddr_in6 *>(&addr)->sin6_port);
   } else {
     return false;
   }
   std::array<char, NI_MAXHOST> ipstr{};
   if (getnameinfo(reinterpret_cast<const struct sockaddr *>(&addr), addr_len,
                   ipstr.data(), static_cast<socklen_t>(ipstr.size()), nullptr,
                   0, NI_NUMERICHOST)) {
     return false;
   }
   ip = ipstr.data();
   return true;
 }
References addr.
Referenced by get_local_ip_and_port(), get_remote_ip_and_port(), and httplib::hosted_at().
get_local_ip_and_port()
void httplib::detail::get_local_ip_and_port (socket_t sock, std::string & ip, int & port) inline
Definition at line 3385 of file httplib.h.
{
   struct sockaddr_storage addr;
   socklen_t addr_len = sizeof(addr);
   if (!getsockname(sock, reinterpret_cast<struct sockaddr *>(&addr),
                    &addr_len)) {
     get_ip_and_port(addr, addr_len, ip, port);
   }
 }
References addr, and get_ip_and_port().
Referenced by httplib::detail::SocketStream::get_local_ip_and_port().
get_multipart_ranges_data_length()
size_t httplib::detail::get_multipart_ranges_data_length (const Request & req, const std::string & boundary, const std::string & content_type, size_t content_length) inline
Definition at line 4871 of file httplib.h.
{
   size_t data_length = 0;
   process_multipart_ranges_data(
       req, boundary, content_type, content_length,
       [&](const std::string &token) { data_length += token.size(); },
       [&](const std::string &token) { data_length += token.size(); },
       [&](size_t /*offset*/, size_t length) {
         data_length += length;
         return true;
       });
   return data_length;
 }
References process_multipart_ranges_data().
Referenced by httplib::Server::apply_ranges().
get_range_offset_and_length()
std::pair<size_t, size_t> httplib::detail::get_range_offset_and_length (Range r, size_t content_length) inline
Definition at line 4795 of file httplib.h.
{
   assert(r.first != -1 && r.second != -1);
   assert(0 <= r.first && r.first < static_cast<ssize_t>(content_length));
   assert(r.first <= r.second &&
          r.second < static_cast<ssize_t>(content_length));
   return std::make_pair(r.first, static_cast<size_t>(r.second - r.first) + 1);
 }
References assert().
Referenced by httplib::Server::apply_ranges(), process_multipart_ranges_data(), and httplib::Server::write_content_with_provider().
get_remote_ip_and_port()
void httplib::detail::get_remote_ip_and_port (socket_t sock, std::string & ip, int & port) inline
Definition at line 3394 of file httplib.h.
{
   struct sockaddr_storage addr;
   socklen_t addr_len = sizeof(addr);
   if (!getpeername(sock, reinterpret_cast<struct sockaddr *>(&addr),
                    &addr_len)) {
 #ifndef _WIN32
     if (addr.ss_family == AF_UNIX) {
 #if defined(__linux__)
       struct ucred ucred;
       socklen_t len = sizeof(ucred);
       if (getsockopt(sock, SOL_SOCKET, SO_PEERCRED, &ucred, &len) == 0) {
         port = ucred.pid;
       }
 #elif defined(SOL_LOCAL) && defined(SO_PEERPID) // __APPLE__
       pid_t pid;
       socklen_t len = sizeof(pid);
       if (getsockopt(sock, SOL_LOCAL, SO_PEERPID, &pid, &len) == 0) {
         port = pid;
       }
 #endif
       return;
     }
 #endif
     get_ip_and_port(addr, addr_len, ip, port);
   }
 }
References addr, and get_ip_and_port().
Referenced by httplib::detail::SocketStream::get_remote_ip_and_port().
handle_EINTR()
template<typename T > ssize_t httplib::detail::handle_EINTR (T fn) inline
Definition at line 2779 of file httplib.h.
{
   ssize_t res = 0;
   while (true) {
     res = fn();
     if (res < 0 && errno == EINTR) { continue; }
     break;
   }
   return res;
 }
Referenced by read_socket(), select_read(), select_write(), send_socket(), and wait_until_socket_is_ready().
has_crlf()
bool httplib::detail::has_crlf (const std::string & s) inline
Definition at line 4914 of file httplib.h.
{
   auto p = s.c_str();
   while (*p) {
     if (*p == '\r' || *p == '\n') { return true; }
     p++;
   }
   return false;
 }
Referenced by httplib::Request::set_header(), httplib::Response::set_header(), and httplib::Response::set_redirect().
has_header()
bool httplib::detail::has_header (const Headers & headers, const std::string & key) inline
Definition at line 3758 of file httplib.h.
{
   return headers.find(key) != headers.end();
 }
Referenced by httplib::Request::has_header(), and read_content().
if2ip()
std::string httplib::detail::if2ip (int address_family, const std::string & ifn) inline
Definition at line 3245 of file httplib.h.
{
   struct ifaddrs *ifap;
   getifaddrs(&ifap);
   std::string addr_candidate;
   for (auto ifa = ifap; ifa; ifa = ifa->ifa_next) {
     if (ifa->ifa_addr && ifn == ifa->ifa_name &&
         (AF_UNSPEC == address_family ||
          ifa->ifa_addr->sa_family == address_family)) {
       if (ifa->ifa_addr->sa_family == AF_INET) {
         auto sa = reinterpret_cast<struct sockaddr_in *>(ifa->ifa_addr);
         char buf[INET_ADDRSTRLEN];
         if (inet_ntop(AF_INET, &sa->sin_addr, buf, INET_ADDRSTRLEN)) {
           freeifaddrs(ifap);
           return std::string(buf, INET_ADDRSTRLEN);
         }
       } else if (ifa->ifa_addr->sa_family == AF_INET6) {
         auto sa = reinterpret_cast<struct sockaddr_in6 *>(ifa->ifa_addr);
         if (!IN6_IS_ADDR_LINKLOCAL(&sa->sin6_addr)) {
           char buf[INET6_ADDRSTRLEN] = {};
           if (inet_ntop(AF_INET6, &sa->sin6_addr, buf, INET6_ADDRSTRLEN)) {
             // equivalent to mac's IN6_IS_ADDR_UNIQUE_LOCAL
             auto s6_addr_head = sa->sin6_addr.s6_addr[0];
             if (s6_addr_head == 0xfc || s6_addr_head == 0xfd) {
               addr_candidate = std::string(buf, INET6_ADDRSTRLEN);
             } else {
               freeifaddrs(ifap);
               return std::string(buf, INET6_ADDRSTRLEN);
             }
           }
         }
       }
     }
   }
   freeifaddrs(ifap);
   return addr_candidate;
 }
is_chunked_transfer_encoding()
bool httplib::detail::is_chunked_transfer_encoding (const Headers & headers) inline
Definition at line 3959 of file httplib.h.
{
   return compare_case_ignore(
       get_header_value(headers, "Transfer-Encoding", 0, ""), "chunked");
 }
References compare_case_ignore(), and get_header_value().
Referenced by read_content().
is_connection_error()
bool httplib::detail::is_connection_error () inline
Definition at line 3208 of file httplib.h.
{
 #ifdef _WIN32
   return WSAGetLastError() != WSAEWOULDBLOCK;
 #else
   return errno != EINPROGRESS;
 #endif
 }
Referenced by create_client_socket().
is_dir()
bool httplib::detail::is_dir (const std::string & path) inline
Definition at line 2402 of file httplib.h.
{
   struct stat st;
   return stat(path.c_str(), &st) >= 0 && S_ISDIR(st.st_mode);
 }
Referenced by httplib::Server::set_mount_point().
is_file()
bool httplib::detail::is_file (const std::string & path) inline
Definition at line 2393 of file httplib.h.
{
 #ifdef _WIN32
   return _access_s(path.c_str(), 0) == 0;
 #else
   struct stat st;
   return stat(path.c_str(), &st) >= 0 && S_ISREG(st.st_mode);
 #endif
 }
Referenced by httplib::Server::handle_file_request().
is_hex()
bool httplib::detail::is_hex (char c, int & v) inline
Definition at line 2290 of file httplib.h.
{
   if (0x20 <= c && isdigit(c)) {
     v = c - '0';
     return true;
   } else if ('A' <= c && c <= 'F') {
     v = c - 'A' + 10;
     return true;
   } else if ('a' <= c && c <= 'f') {
     v = c - 'a' + 10;
     return true;
   }
   return false;
 }
References c.
Referenced by from_hex_to_i().
is_multipart_boundary_chars_valid()
bool httplib::detail::is_multipart_boundary_chars_valid (const std::string & boundary) inline
Definition at line 4682 of file httplib.h.
{
   auto valid = true;
   for (size_t i = 0; i < boundary.size(); i++) {
     auto c = boundary[i];
     if (!std::isalnum(c) && c != '-' && c != '_') {
       valid = false;
       break;
     }
   }
   return valid;
 }
References c.
Referenced by httplib::ClientImpl::Post(), and httplib::ClientImpl::Put().
is_socket_alive()
bool httplib::detail::is_socket_alive (socket_t sock) inline
Definition at line 2927 of file httplib.h.
{
   const auto val = detail::select_read(sock, 0, 0);
   if (val == 0) {
     return true;
   } else if (val < 0 && errno == EBADF) {
     return false;
   }
   char buf[1];
   return detail::read_socket(sock, &buf[0], sizeof(buf), MSG_PEEK) > 0;
 }
References read_socket(), and select_read().
Referenced by httplib::detail::SocketStream::is_writable(), and httplib::ClientImpl::send_().
is_space_or_tab()
bool httplib::detail::is_space_or_tab (char c) inline
Definition at line 2555 of file httplib.h.
 { return c == ' ' || c == '\t'; }
References c.
Referenced by parse_header(), and trim().
is_valid_path()
bool httplib::detail::is_valid_path (const std::string & path) inline
Definition at line 2407 of file httplib.h.
{
   size_t level = 0;
   size_t i = 0;
   // Skip slash
   while (i < path.size() && path[i] == '/') {
     i++;
   }
   while (i < path.size()) {
     // Read component
     auto beg = i;
     while (i < path.size() && path[i] != '/') {
       if (path[i] == '\0') {
         return false;
       } else if (path[i] == '\\') {
         return false;
       }
       i++;
     }
     auto len = i - beg;
     assert(len > 0);
     if (!path.compare(beg, len, ".")) {
       ;
     } else if (!path.compare(beg, len, "..")) {
       if (level == 0) { return false; }
       level--;
     } else {
       level++;
     }
     // Skip slash
     while (i < path.size() && path[i] == '/') {
       i++;
     }
   }
   return true;
 }
References assert().
Referenced by httplib::Server::handle_file_request().
keep_alive()
bool httplib::detail::keep_alive (socket_t sock, time_t keep_alive_timeout_sec) inline
Definition at line 2992 of file httplib.h.
{
   using namespace std::chrono;
   auto start = steady_clock::now();
   while (true) {
     auto val = select_read(sock, 0, 10000);
     if (val < 0) {
       return false;
     } else if (val == 0) {
       auto current = steady_clock::now();
       auto duration = duration_cast<milliseconds>(current - start);
       auto timeout = keep_alive_timeout_sec * 1000;
       if (duration.count() > timeout) { return false; }
       std::this_thread::sleep_for(std::chrono::milliseconds(1));
     } else {
       return true;
     }
   }
 }
References select_read().
Referenced by process_server_socket_core().
make_content_range_header_field()
std::string httplib::detail::make_content_range_header_field (const std::pair< size_t, size_t > & offset_and_length, size_t content_length) inline
Definition at line 4804 of file httplib.h.
{
   auto st = offset_and_length.first;
   auto ed = st + offset_and_length.second - 1;
   std::string field = "bytes ";
   field += std::to_string(st);
   field += "-";
   field += std::to_string(ed);
   field += "/";
   field += std::to_string(content_length);
   return field;
 }
References httplib::to_string().
Referenced by httplib::Server::apply_ranges(), and process_multipart_ranges_data().
make_multipart_data_boundary()
std::string httplib::detail::make_multipart_data_boundary () inline
Definition at line 4678 of file httplib.h.
{
   return "--cpp-httplib-multipart-data-" + detail::random_string(16);
 }
References random_string().
Referenced by httplib::Server::apply_ranges(), httplib::ClientImpl::Post(), and httplib::ClientImpl::Put().
make_multipart_ranges_data()
void httplib::detail::make_multipart_ranges_data (const Request & req, Response & res, const std::string & boundary, const std::string & content_type, size_t content_length, std::string & data) inline
Definition at line 4855 of file httplib.h.
{
   process_multipart_ranges_data(
       req, boundary, content_type, content_length,
       [&](const std::string &token) { data += token; },
       [&](const std::string &token) { data += token; },
       [&](size_t offset, size_t length) {
         assert(offset + length <= content_length);
         data += res.body.substr(offset, length);
         return true;
       });
 }
References assert(), httplib::Response::body, and process_multipart_ranges_data().
Referenced by httplib::Server::apply_ranges().
make_unique() [1/2]
template<class T , class... Args> std::enable_if<!std::is_array<T>::value, std::unique_ptr<T> >::type httplib::detail::make_unique (Args &&... args)
Definition at line 304 of file httplib.h.
{
   return std::unique_ptr<T>(new T(std::forward<Args>(args)...));
 }
make_unique() [2/2]
template<class T > std::enable_if<std::is_array<T>::value, std::unique_ptr<T> >::type httplib::detail::make_unique (std::size_t n)
Definition at line 310 of file httplib.h.
{
   typedef typename std::remove_extent<T>::type RT;
   return std::unique_ptr<T>(new RT[n]);
 }
References n.
params_to_query_str()
std::string httplib::detail::params_to_query_str (const Params & params) inline
Definition at line 4291 of file httplib.h.
{
   std::string query;
   for (auto it = params.begin(); it != params.end(); ++it) {
     if (it != params.begin()) { query += "&"; }
     query += it->first;
     query += "=";
     query += encode_query_param(it->second);
   }
   return query;
 }
References encode_query_param().
Referenced by httplib::append_query_params(), httplib::ClientImpl::Post(), and httplib::ClientImpl::Put().
parse_disposition_params()
void httplib::detail::parse_disposition_params (const std::string & s, Params & params) inline
Definition at line 4337 of file httplib.h.
{
   std::set<std::string> cache;
   split(s.data(), s.data() + s.size(), ';', [&](const char *b, const char *e) {
     std::string kv(b, e);
     if (cache.find(kv) != cache.end()) { return; }
     cache.insert(kv);
     std::string key;
     std::string val;
     split(b, e, '=', [&](const char *b2, const char *e2) {
       if (key.empty()) {
         key.assign(b2, e2);
       } else {
         val.assign(b2, e2);
       }
     });
     if (!key.empty()) {
       params.emplace(trim_double_quotes_copy((key)),
                      trim_double_quotes_copy((val)));
     }
   });
 }
References split().
Referenced by httplib::detail::MultipartFormDataParser::parse().
parse_header()
template<typename T > bool httplib::detail::parse_header (const char * beg, const char * end, T fn) inline
Definition at line 3781 of file httplib.h.
{
   // Skip trailing spaces and tabs.
   while (beg < end && is_space_or_tab(end[-1])) {
     end--;
   }
   auto p = beg;
   while (p < end && *p != ':') {
     p++;
   }
   if (p == end) { return false; }
   auto key_end = p;
   if (*p++ != ':') { return false; }
   while (p < end && is_space_or_tab(*p)) {
     p++;
   }
   if (p < end) {
     auto key_len = key_end - beg;
     if (!key_len) { return false; }
     auto key = std::string(beg, key_end);
     auto val = compare_case_ignore(key, "Location")
                    ? std::string(p, end)
                    : decode_url(std::string(p, end), false);
     fn(std::move(key), std::move(val));
     return true;
   }
   return false;
 }
References compare_case_ignore(), decode_url(), and is_space_or_tab().
Referenced by httplib::detail::MultipartFormDataParser::parse(), read_content_chunked(), and read_headers().
parse_multipart_boundary()
bool httplib::detail::parse_multipart_boundary (const std::string & content_type, std::string & boundary) inline
Definition at line 4326 of file httplib.h.
{
   auto boundary_keyword = "boundary=";
   auto pos = content_type.find(boundary_keyword);
   if (pos == std::string::npos) { return false; }
   auto end = content_type.find(';', pos);
   auto beg = pos + strlen(boundary_keyword);
   boundary = trim_double_quotes_copy(content_type.substr(beg, end - beg));
   return !boundary.empty();
 }
References trim_double_quotes_copy().
Referenced by httplib::Server::read_content_core().
parse_query_text()
void httplib::detail::parse_query_text (const std::string & s, Params & params) inline
Definition at line 4303 of file httplib.h.
{
   std::set<std::string> cache;
   split(s.data(), s.data() + s.size(), '&', [&](const char *b, const char *e) {
     std::string kv(b, e);
     if (cache.find(kv) != cache.end()) { return; }
     cache.insert(kv);
     std::string key;
     std::string val;
     split(b, e, '=', [&](const char *b2, const char *e2) {
       if (key.empty()) {
         key.assign(b2, e2);
       } else {
         val.assign(b2, e2);
       }
     });
     if (!key.empty()) {
       params.emplace(decode_url(key, true), decode_url(val, true));
     }
   });
 }
References split().
Referenced by httplib::Server::read_content().
parse_range_header()
bool httplib::detail::parse_range_header (const std::string & s, Ranges & ranges) inline
Definition at line 4364 of file httplib.h.
{
 #endif
   static auto re_first_range = std::regex(R"(bytes=(\d*-\d*(?:,\s*\d*-\d*)*))");
   std::smatch m;
   if (std::regex_match(s, m, re_first_range)) {
     auto pos = static_cast<size_t>(m.position(1));
     auto len = static_cast<size_t>(m.length(1));
     auto all_valid_ranges = true;
     split(&s[pos], &s[pos + len], ',', [&](const char *b, const char *e) {
       if (!all_valid_ranges) { return; }
       static auto re_another_range = std::regex(R"(\s*(\d*)-(\d*))");
       std::cmatch cm;
       if (std::regex_match(b, e, cm, re_another_range)) {
         ssize_t first = -1;
         if (!cm.str(1).empty()) {
           first = static_cast<ssize_t>(std::stoll(cm.str(1)));
         }
         ssize_t last = -1;
         if (!cm.str(2).empty()) {
           last = static_cast<ssize_t>(std::stoll(cm.str(2)));
         }
         if (first != -1 && last != -1 && first > last) {
           all_valid_ranges = false;
           return;
         }
         ranges.emplace_back(std::make_pair(first, last));
       }
     });
     return all_valid_ranges;
   }
   return false;
 #ifdef CPPHTTPLIB_NO_EXCEPTIONS
 }
 #else
 } catch (...) { return false; }
References split().
Referenced by httplib::Server::process_request().
parse_www_authenticate()
bool httplib::detail::parse_www_authenticate (const Response & res, std::map< std::string, std::string > & auth, bool is_proxy) inline
Definition at line 5158 of file httplib.h.
{
   auto auth_key = is_proxy ? "Proxy-Authenticate" : "WWW-Authenticate";
   if (res.has_header(auth_key)) {
     static auto re = std::regex(R"~((?:(?:,\s*)?(.+?)=(?:"(.*?)"|([^,]*))))~");
     auto s = res.get_header_value(auth_key);
     auto pos = s.find(' ');
     if (pos != std::string::npos) {
       auto type = s.substr(0, pos);
       if (type == "Basic") {
         return false;
       } else if (type == "Digest") {
         s = s.substr(pos + 1);
         auto beg = std::sregex_iterator(s.begin(), s.end(), re);
         for (auto i = beg; i != std::sregex_iterator(); ++i) {
           const auto &m = *i;
           auto key = s.substr(static_cast<size_t>(m.position(1)),
                               static_cast<size_t>(m.length(1)));
           auto val = m.length(2) > 0
                          ? s.substr(static_cast<size_t>(m.position(2)),
                                     static_cast<size_t>(m.length(2)))
                          : s.substr(static_cast<size_t>(m.position(3)),
                                     static_cast<size_t>(m.length(3)));
           auth[key] = val;
         }
         return true;
       }
     }
   }
   return false;
 }
References httplib::Response::get_header_value(), and httplib::Response::has_header().
Referenced by httplib::ClientImpl::handle_request().
prepare_content_receiver()
template<typename T , typename U > bool httplib::detail::prepare_content_receiver (T & x, int & status, ContentReceiverWithProgress receiver, bool decompress, U callback)
Definition at line 3965 of file httplib.h.
{
   if (decompress) {
     std::string encoding = x.get_header_value("Content-Encoding");
     std::unique_ptr<decompressor> decompressor;
     if (encoding == "gzip" || encoding == "deflate") {
 #ifdef CPPHTTPLIB_ZLIB_SUPPORT
       decompressor = detail::make_unique<gzip_decompressor>();
 #else
       status = StatusCode::UnsupportedMediaType_415;
       return false;
 #endif
     } else if (encoding.find("br") != std::string::npos) {
 #ifdef CPPHTTPLIB_BROTLI_SUPPORT
       decompressor = detail::make_unique<brotli_decompressor>();
 #else
       status = StatusCode::UnsupportedMediaType_415;
       return false;
 #endif
     }
     if (decompressor) {
       if (decompressor->is_valid()) {
         ContentReceiverWithProgress out = [&](const char *buf, size_t n,
                                               uint64_t off, uint64_t len) {
           return decompressor->decompress(buf, n,
                                           [&](const char *buf2, size_t n2) {
                                             return receiver(buf2, n2, off, len);
                                           });
         };
         return callback(std::move(out));
       } else {
         status = StatusCode::InternalServerError_500;
         return false;
       }
     }
   }
   ContentReceiverWithProgress out = [&](const char *buf, size_t n, uint64_t off,
                                         uint64_t len) {
     return receiver(buf, n, off, len);
   };
   return callback(std::move(out));
 }
References httplib::detail::decompressor::decompress(), httplib::InternalServerError_500, httplib::detail::decompressor::is_valid(), n, and httplib::UnsupportedMediaType_415.
Referenced by read_content().
process_client_socket()
bool httplib::detail::process_client_socket (socket_t sock, time_t read_timeout_sec, time_t read_timeout_usec, time_t write_timeout_sec, time_t write_timeout_usec, std::function< bool(Stream &)> callback) inline
Definition at line 3046 of file httplib.h.
{
   SocketStream strm(sock, read_timeout_sec, read_timeout_usec,
                     write_timeout_sec, write_timeout_usec);
   return callback(strm);
 }
Referenced by httplib::ClientImpl::process_socket().
process_multipart_ranges_data()
template<typename SToken , typename CToken , typename Content > bool httplib::detail::process_multipart_ranges_data (const Request & req, const std::string & boundary, const std::string & content_type, size_t content_length, SToken stoken, CToken ctoken, Content content)
Definition at line 4819 of file httplib.h.
{
   for (size_t i = 0; i < req.ranges.size(); i++) {
     ctoken("--");
     stoken(boundary);
     ctoken("\r\n");
     if (!content_type.empty()) {
       ctoken("Content-Type: ");
       stoken(content_type);
       ctoken("\r\n");
     }
     auto offset_and_length =
         get_range_offset_and_length(req.ranges[i], content_length);
     ctoken("Content-Range: ");
     stoken(make_content_range_header_field(offset_and_length, content_length));
     ctoken("\r\n");
     ctoken("\r\n");
     if (!content(offset_and_length.first, offset_and_length.second)) {
       return false;
     }
     ctoken("\r\n");
   }
   ctoken("--");
   stoken(boundary);
   ctoken("--");
   return true;
 }
References get_range_offset_and_length(), make_content_range_header_field(), and httplib::Request::ranges.
Referenced by get_multipart_ranges_data_length(), make_multipart_ranges_data(), and write_multipart_ranges_data().
process_server_socket()
template<typename T > bool httplib::detail::process_server_socket (const std::atomic< socket_t > & svr_sock, socket_t sock, size_t keep_alive_max_count, time_t keep_alive_timeout_sec, time_t read_timeout_sec, time_t read_timeout_usec, time_t write_timeout_sec, time_t write_timeout_usec, T callback) inline
Definition at line 3032 of file httplib.h.
{
   return process_server_socket_core(
       svr_sock, sock, keep_alive_max_count, keep_alive_timeout_sec,
       [&](bool close_connection, bool &connection_closed) {
         SocketStream strm(sock, read_timeout_sec, read_timeout_usec,
                           write_timeout_sec, write_timeout_usec);
         return callback(strm, close_connection, connection_closed);
       });
 }
References process_server_socket_core().
Referenced by httplib::Server::process_and_close_socket().
process_server_socket_core()
template<typename T > bool httplib::detail::process_server_socket_core (const std::atomic< socket_t > & svr_sock, socket_t sock, size_t keep_alive_max_count, time_t keep_alive_timeout_sec, T callback) inline
Definition at line 3013 of file httplib.h.
{
   assert(keep_alive_max_count > 0);
   auto ret = false;
   auto count = keep_alive_max_count;
   while (svr_sock != INVALID_SOCKET && count > 0 &&
          keep_alive(sock, keep_alive_timeout_sec)) {
     auto close_connection = count == 1;
     auto connection_closed = false;
     ret = callback(close_connection, connection_closed);
     if (!ret || connection_closed) { break; }
     count--;
   }
   return ret;
 }
References assert(), INVALID_SOCKET, and keep_alive().
Referenced by process_server_socket().
random_string()
std::string httplib::detail::random_string (size_t length) inline
Definition at line 4656 of file httplib.h.
{
   static const char data[] =
       "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
   // std::random_device might actually be deterministic on some
   // platforms, but due to lack of support in the c++ standard library,
   // doing better requires either some ugly hacks or breaking portability.
   static std::random_device seed_gen;
   // Request 128 bits of entropy for initialization
   static std::seed_seq seed_sequence{seed_gen(), seed_gen(), seed_gen(),
                                      seed_gen()};
   static std::mt19937 engine(seed_sequence);
   std::string result;
   for (size_t i = 0; i < length; i++) {
     result += data[engine() % (sizeof(data) - 1)];
   }
   return result;
 }
References result.
Referenced by httplib::ClientImpl::handle_request(), and make_multipart_data_boundary().
range_error()
bool httplib::detail::range_error (Request & req, Response & res) inline
Definition at line 4739 of file httplib.h.
{
   if (!req.ranges.empty() && 200 <= res.status && res.status < 300) {
     ssize_t contant_len = static_cast<ssize_t>(
         res.content_length_ ? res.content_length_ : res.body.size());
     ssize_t prev_first_pos = -1;
     ssize_t prev_last_pos = -1;
     size_t overwrapping_count = 0;
     // NOTE: The following Range check is based on '14.2. Range' in RFC 9110
     // 'HTTP Semantics' to avoid potential denial-of-service attacks.
     // https://www.rfc-editor.org/rfc/rfc9110#section-14.2
     // Too many ranges
     if (req.ranges.size() > CPPHTTPLIB_RANGE_MAX_COUNT) { return true; }
     for (auto &r : req.ranges) {
       auto &first_pos = r.first;
       auto &last_pos = r.second;
       if (first_pos == -1 && last_pos == -1) {
         first_pos = 0;
         last_pos = contant_len;
       }
       if (first_pos == -1) {
         first_pos = contant_len - last_pos;
         last_pos = contant_len - 1;
       }
       if (last_pos == -1) { last_pos = contant_len - 1; }
       // Range must be within content length
       if (!(0 <= first_pos && first_pos <= last_pos &&
             last_pos <= contant_len - 1)) {
         return true;
       }
       // Ranges must be in ascending order
       if (first_pos <= prev_first_pos) { return true; }
       // Request must not have more than two overlapping ranges
       if (first_pos <= prev_last_pos) {
         overwrapping_count++;
         if (overwrapping_count > 2) { return true; }
       }
       prev_first_pos = (std::max)(prev_first_pos, first_pos);
       prev_last_pos = (std::max)(prev_last_pos, last_pos);
     }
   }
   return false;
 }
References httplib::Response::body, httplib::Response::content_length_, CPPHTTPLIB_RANGE_MAX_COUNT, httplib::Request::ranges, and httplib::Response::status.
Referenced by httplib::Server::process_request().
read_content()
template<typename T > bool httplib::detail::read_content (Stream & strm, T & x, size_t payload_max_length, int & status, Progress progress, ContentReceiverWithProgress receiver, bool decompress)
Definition at line 4013 of file httplib.h.
{
   return prepare_content_receiver(
       x, status, std::move(receiver), decompress,
       [&](const ContentReceiverWithProgress &out) {
         auto ret = true;
         auto exceed_payload_max_length = false;
         if (is_chunked_transfer_encoding(x.headers)) {
           ret = read_content_chunked(strm, x, out);
         } else if (!has_header(x.headers, "Content-Length")) {
           ret = read_content_without_length(strm, out);
         } else {
           auto len = get_header_value_u64(x.headers, "Content-Length", 0, 0);
           if (len > payload_max_length) {
             exceed_payload_max_length = true;
             skip_content_with_length(strm, len);
             ret = false;
           } else if (len > 0) {
             ret = read_content_with_length(strm, len, std::move(progress), out);
           }
         }
         if (!ret) {
           status = exceed_payload_max_length ? StatusCode::PayloadTooLarge_413
                                              : StatusCode::BadRequest_400;
         }
         return ret;
       });
 } // namespace detail
References httplib::BadRequest_400, has_header(), if(), is_chunked_transfer_encoding(), httplib::PayloadTooLarge_413, prepare_content_receiver(), and read_content_with_length().
Referenced by httplib::ClientImpl::process_request(), and httplib::Server::read_content_core().
read_content_chunked()
template<typename T > bool httplib::detail::read_content_chunked (Stream & strm, T & x, ContentReceiverWithProgress out) inline
Definition at line 3905 of file httplib.h.
{
   const auto bufsiz = 16;
   char buf[bufsiz];
   stream_line_reader line_reader(strm, buf, bufsiz);
   if (!line_reader.getline()) { return false; }
   unsigned long chunk_len;
   while (true) {
     char *end_ptr;
     chunk_len = std::strtoul(line_reader.ptr(), &end_ptr, 16);
     if (end_ptr == line_reader.ptr()) { return false; }
     if (chunk_len == ULONG_MAX) { return false; }
     if (chunk_len == 0) { break; }
     if (!read_content_with_length(strm, chunk_len, nullptr, out)) {
       return false;
     }
     if (!line_reader.getline()) { return false; }
     if (strcmp(line_reader.ptr(), "\r\n") != 0) { return false; }
     if (!line_reader.getline()) { return false; }
   }
   assert(chunk_len == 0);
   // Trailer
   if (!line_reader.getline()) { return false; }
   while (strcmp(line_reader.ptr(), "\r\n") != 0) {
     if (line_reader.size() > CPPHTTPLIB_HEADER_MAX_LENGTH) { return false; }
     // Exclude line terminator
     constexpr auto line_terminator_len = 2;
     auto end = line_reader.ptr() + line_reader.size() - line_terminator_len;
     parse_header(line_reader.ptr(), end,
                  [&](std::string &&key, std::string &&val) {
                    x.headers.emplace(std::move(key), std::move(val));
                  });
     if (!line_reader.getline()) { return false; }
   }
   return true;
 }
References assert(), CPPHTTPLIB_HEADER_MAX_LENGTH, httplib::detail::stream_line_reader::getline(), parse_header(), httplib::detail::stream_line_reader::ptr(), read_content_with_length(), and httplib::detail::stream_line_reader::size().
read_content_with_length()
bool httplib::detail::read_content_with_length (Stream & strm, uint64_t len, Progress progress, ContentReceiverWithProgress out) inline
Definition at line 3856 of file httplib.h.
{
   char buf[CPPHTTPLIB_RECV_BUFSIZ];
   uint64_t r = 0;
   while (r < len) {
     auto read_len = static_cast<size_t>(len - r);
     auto n = strm.read(buf, (std::min)(read_len, CPPHTTPLIB_RECV_BUFSIZ));
     if (n <= 0) { return false; }
     if (!out(buf, static_cast<size_t>(n), r, len)) { return false; }
     r += static_cast<uint64_t>(n);
     if (progress) {
       if (!progress(r, len)) { return false; }
     }
   }
   return true;
 }
References CPPHTTPLIB_RECV_BUFSIZ, n, and httplib::Stream::read().
Referenced by read_content(), and read_content_chunked().
read_content_without_length()
bool httplib::detail::read_content_without_length (Stream & strm, ContentReceiverWithProgress out) inline
Definition at line 3889 of file httplib.h.
{
   char buf[CPPHTTPLIB_RECV_BUFSIZ];
   uint64_t r = 0;
   for (;;) {
     auto n = strm.read(buf, CPPHTTPLIB_RECV_BUFSIZ);
     if (n <= 0) { return true; }
     if (!out(buf, static_cast<size_t>(n), r, 0)) { return false; }
     r += static_cast<uint64_t>(n);
   }
   return true;
 }
References CPPHTTPLIB_RECV_BUFSIZ, n, and httplib::Stream::read().
read_file()
void httplib::detail::read_file (const std::string & path, std::string & out) inline
Definition at line 2539 of file httplib.h.
{
   std::ifstream fs(path, std::ios_base::binary);
   fs.seekg(0, std::ios_base::end);
   auto size = fs.tellg();
   fs.seekg(0);
   out.resize(static_cast<size_t>(size));
   fs.read(&out[0], static_cast<std::streamsize>(size));
 }
read_headers()
bool httplib::detail::read_headers (Stream & strm, Headers & headers) inline
Definition at line 3817 of file httplib.h.
{
   const auto bufsiz = 2048;
   char buf[bufsiz];
   stream_line_reader line_reader(strm, buf, bufsiz);
   for (;;) {
     if (!line_reader.getline()) { return false; }
     // Check if the line ends with CRLF.
     auto line_terminator_len = 2;
     if (line_reader.end_with_crlf()) {
       // Blank line indicates end of headers.
       if (line_reader.size() == 2) { break; }
 #ifdef CPPHTTPLIB_ALLOW_LF_AS_LINE_TERMINATOR
     } else {
       // Blank line indicates end of headers.
       if (line_reader.size() == 1) { break; }
       line_terminator_len = 1;
     }
 #else
     } else {
       continue; // Skip invalid line.
     }
 #endif
     if (line_reader.size() > CPPHTTPLIB_HEADER_MAX_LENGTH) { return false; }
     // Exclude line terminator
     auto end = line_reader.ptr() + line_reader.size() - line_terminator_len;
     parse_header(line_reader.ptr(), end,
                  [&](std::string &&key, std::string &&val) {
                    headers.emplace(std::move(key), std::move(val));
                  });
   }
   return true;
 }
References CPPHTTPLIB_HEADER_MAX_LENGTH, httplib::detail::stream_line_reader::end_with_crlf(), httplib::detail::stream_line_reader::getline(), parse_header(), httplib::detail::stream_line_reader::ptr(), and httplib::detail::stream_line_reader::size().
Referenced by httplib::Server::process_request(), and httplib::ClientImpl::process_request().
read_socket()
ssize_t httplib::detail::read_socket (socket_t sock, void * ptr, size_t size, int flags) inline
Definition at line 2789 of file httplib.h.
{
   return handle_EINTR([&]() {
     return recv(sock,
 #ifdef _WIN32
                 static_cast<char *>(ptr), static_cast<int>(size),
 #else
                 ptr, size,
 #endif
                 flags);
   });
 }
References handle_EINTR().
Referenced by is_socket_alive(), and httplib::detail::SocketStream::read().
redirect()
template<typename T > bool httplib::detail::redirect (T & cli, Request & req, Response & res, const std::string & path, const std::string & location, Error & error) inline
Definition at line 4265 of file httplib.h.
{
   Request new_req = req;
   new_req.path = path;
   new_req.redirect_count_ -= 1;
   if (res.status == StatusCode::SeeOther_303 &&
       (req.method != "GET" && req.method != "HEAD")) {
     new_req.method = "GET";
     new_req.body.clear();
     new_req.headers.clear();
   }
   Response new_res;
   auto ret = cli.send(new_req, new_res, error);
   if (ret) {
     req = new_req;
     res = new_res;
     if (res.location.empty()) { res.location = location; }
   }
   return ret;
 }
References httplib::Request::body, httplib::Request::headers, httplib::Response::location, httplib::Request::method, httplib::Request::path, httplib::Request::redirect_count_, httplib::SeeOther_303, and httplib::Response::status.
Referenced by httplib::ClientImpl::redirect().
select_read()
ssize_t httplib::detail::select_read (socket_t sock, time_t sec, time_t usec) inline
Definition at line 2814 of file httplib.h.
{
 #ifdef CPPHTTPLIB_USE_POLL
   struct pollfd pfd_read;
   pfd_read.fd = sock;
   pfd_read.events = POLLIN;
   auto timeout = static_cast<int>(sec * 1000 + usec / 1000);
   return handle_EINTR([&]() { return poll(&pfd_read, 1, timeout); });
 #else
 #ifndef _WIN32
   if (sock >= FD_SETSIZE) { return -1; }
 #endif
   fd_set fds;
   FD_ZERO(&fds);
   FD_SET(sock, &fds);
   timeval tv;
   tv.tv_sec = static_cast<long>(sec);
   tv.tv_usec = static_cast<decltype(tv.tv_usec)>(usec);
   return handle_EINTR([&]() {
     return select(static_cast<int>(sock + 1), &fds, nullptr, nullptr, &tv);
   });
 #endif
 }
References handle_EINTR(), and sec.
Referenced by httplib::detail::SocketStream::is_readable(), is_socket_alive(), keep_alive(), and httplib::Server::listen_internal().
select_write()
ssize_t httplib::detail::select_write (socket_t sock, time_t sec, time_t usec) inline
Definition at line 2842 of file httplib.h.
{
 #ifdef CPPHTTPLIB_USE_POLL
   struct pollfd pfd_read;
   pfd_read.fd = sock;
   pfd_read.events = POLLOUT;
   auto timeout = static_cast<int>(sec * 1000 + usec / 1000);
   return handle_EINTR([&]() { return poll(&pfd_read, 1, timeout); });
 #else
 #ifndef _WIN32
   if (sock >= FD_SETSIZE) { return -1; }
 #endif
   fd_set fds;
   FD_ZERO(&fds);
   FD_SET(sock, &fds);
   timeval tv;
   tv.tv_sec = static_cast<long>(sec);
   tv.tv_usec = static_cast<decltype(tv.tv_usec)>(usec);
   return handle_EINTR([&]() {
     return select(static_cast<int>(sock + 1), nullptr, &fds, nullptr, &tv);
   });
 #endif
 }
References handle_EINTR(), and sec.
Referenced by httplib::detail::SocketStream::is_writable().
send_socket()
ssize_t httplib::detail::send_socket (socket_t sock, const void * ptr, size_t size, int flags) inline
Definition at line 2801 of file httplib.h.
{
   return handle_EINTR([&]() {
     return send(sock,
 #ifdef _WIN32
                 static_cast<const char *>(ptr), static_cast<int>(size),
 #else
                 ptr, size,
 #endif
                 flags);
   });
 }
References handle_EINTR().
Referenced by httplib::detail::SocketStream::write().
serialize_multipart_formdata()
std::string httplib::detail::serialize_multipart_formdata (const MultipartFormDataItems & items, const std::string & boundary, bool finish = true) inline
Definition at line 4725 of file httplib.h.
{
   std::string body;
   for (const auto &item : items) {
     body += serialize_multipart_formdata_item_begin(item, boundary);
     body += item.content + serialize_multipart_formdata_item_end();
   }
   if (finish) { body += serialize_multipart_formdata_finish(boundary); }
   return body;
 }
References serialize_multipart_formdata_finish(), serialize_multipart_formdata_item_begin(), and serialize_multipart_formdata_item_end().
Referenced by httplib::ClientImpl::get_multipart_content_provider(), httplib::ClientImpl::Post(), and httplib::ClientImpl::Put().
serialize_multipart_formdata_finish()
std::string httplib::detail::serialize_multipart_formdata_finish (const std::string & boundary) inline
Definition at line 4715 of file httplib.h.
{
   return "--" + boundary + "--\r\n";
 }
Referenced by httplib::ClientImpl::get_multipart_content_provider(), and serialize_multipart_formdata().
serialize_multipart_formdata_get_content_type()
std::string httplib::detail::serialize_multipart_formdata_get_content_type (const std::string & boundary) inline
Definition at line 4720 of file httplib.h.
{
   return "multipart/form-data; boundary=" + boundary;
 }
Referenced by httplib::ClientImpl::Post(), and httplib::ClientImpl::Put().
serialize_multipart_formdata_item_begin()
template<typename T > std::string httplib::detail::serialize_multipart_formdata_item_begin (const T & item, const std::string & boundary) inline
Definition at line 4696 of file httplib.h.
{
   std::string body = "--" + boundary + "\r\n";
   body += "Content-Disposition: form-data; name=\"" + item.name + "\"";
   if (!item.filename.empty()) {
     body += "; filename=\"" + item.filename + "\"";
   }
   body += "\r\n";
   if (!item.content_type.empty()) {
     body += "Content-Type: " + item.content_type + "\r\n";
   }
   body += "\r\n";
   return body;
 }
Referenced by httplib::ClientImpl::get_multipart_content_provider(), and serialize_multipart_formdata().
serialize_multipart_formdata_item_end()
std::string httplib::detail::serialize_multipart_formdata_item_end () inline
Definition at line 4712 of file httplib.h.
 { return "\r\n"; }
Referenced by httplib::ClientImpl::get_multipart_content_provider(), and serialize_multipart_formdata().
set_nonblocking()
void httplib::detail::set_nonblocking (socket_t sock, bool nonblocking) inline
Definition at line 3197 of file httplib.h.
{
 #ifdef _WIN32
   auto flags = nonblocking ? 1UL : 0UL;
   ioctlsocket(sock, FIONBIO, &flags);
 #else
   auto flags = fcntl(sock, F_GETFL, 0);
   fcntl(sock, F_SETFL,
         nonblocking ? (flags | O_NONBLOCK) : (flags & (~O_NONBLOCK)));
 #endif
 }
Referenced by create_client_socket().
shutdown_socket()
int httplib::detail::shutdown_socket (socket_t sock) inline
Definition at line 3056 of file httplib.h.
{
 #ifdef _WIN32
   return shutdown(sock, SD_BOTH);
 #else
   return shutdown(sock, SHUT_RDWR);
 #endif
 }
Referenced by httplib::Server::listen_internal(), httplib::Server::process_and_close_socket(), httplib::ClientImpl::shutdown_socket(), and httplib::Server::stop().
skip_content_with_length()
void httplib::detail::skip_content_with_length (Stream & strm, uint64_t len) inline
Definition at line 3878 of file httplib.h.
{
   char buf[CPPHTTPLIB_RECV_BUFSIZ];
   uint64_t r = 0;
   while (r < len) {
     auto read_len = static_cast<size_t>(len - r);
     auto n = strm.read(buf, (std::min)(read_len, CPPHTTPLIB_RECV_BUFSIZ));
     if (n <= 0) { return; }
     r += static_cast<uint64_t>(n);
   }
 }
References CPPHTTPLIB_RECV_BUFSIZ, n, and httplib::Stream::read().
split() [1/2]
void httplib::detail::split (const char * b, const char * e, char d, size_t m, std::function< void(const char *, const char *)> fn) inline
Definition at line 2585 of file httplib.h.
{
   size_t i = 0;
   size_t beg = 0;
   size_t count = 1;
   while (e ? (b + i < e) : (b[i] != '\0')) {
     if (b[i] == d && count < m) {
       auto r = trim(b, e, beg, i);
       if (r.first < r.second) { fn(&b[r.first], &b[r.second]); }
       beg = i + 1;
       count++;
     }
     i++;
   }
   if (i) {
     auto r = trim(b, e, beg, i);
     if (r.first < r.second) { fn(&b[r.first], &b[r.second]); }
   }
 }
References trim().
Referenced by parse_disposition_params(), parse_query_text(), and parse_range_header().
split() [2/2]
void httplib::detail::split (const char * b, const char * e, char d, std::function< void(const char *, const char *)> fn) inline
Definition at line 2580 of file httplib.h.
{
   return split(b, e, d, (std::numeric_limits<size_t>::max)(), std::move(fn));
 }
Referenced by httplib::Server::parse_request_line().
str2tag()
unsigned int httplib::detail::str2tag (const std::string & s) inline
Definition at line 3434 of file httplib.h.
{
   return str2tag_core(s.data(), s.size(), 0);
 }
References str2tag_core().
Referenced by can_compress_content_type(), and find_content_type().
str2tag_core()
constexpr unsigned int httplib::detail::str2tag_core (const char * s, size_t l, unsigned int h) inline constexpr
Definition at line 3422 of file httplib.h.
{
   return (l == 0)
              ? h
              : str2tag_core(
                    s + 1, l - 1,
                    // Unsets the 6 high bits of h, therefore no overflow happens
                    (((std::numeric_limits<unsigned int>::max)() >> 6) &
                     h * 33) ^
                        static_cast<unsigned char>(*s));
 }
Referenced by httplib::detail::udl::operator""_t(), and str2tag().
to_lower()
std::string httplib::detail::to_lower (const char * beg, const char * end) inline
Definition at line 4646 of file httplib.h.
{
   std::string out;
   auto it = beg;
   while (it != end) {
     out += static_cast<char>(::tolower(*it));
     it++;
   }
   return out;
 }
to_utf8()
size_t httplib::detail::to_utf8 (int code, char * buff) inline
Definition at line 2331 of file httplib.h.
{
   if (code < 0x0080) {
     buff[0] = static_cast<char>(code & 0x7F);
     return 1;
   } else if (code < 0x0800) {
     buff[0] = static_cast<char>(0xC0 | ((code >> 6) & 0x1F));
     buff[1] = static_cast<char>(0x80 | (code & 0x3F));
     return 2;
   } else if (code < 0xD800) {
     buff[0] = static_cast<char>(0xE0 | ((code >> 12) & 0xF));
     buff[1] = static_cast<char>(0x80 | ((code >> 6) & 0x3F));
     buff[2] = static_cast<char>(0x80 | (code & 0x3F));
     return 3;
   } else if (code < 0xE000) { // D800 - DFFF is invalid...
     return 0;
   } else if (code < 0x10000) {
     buff[0] = static_cast<char>(0xE0 | ((code >> 12) & 0xF));
     buff[1] = static_cast<char>(0x80 | ((code >> 6) & 0x3F));
     buff[2] = static_cast<char>(0x80 | (code & 0x3F));
     return 3;
   } else if (code < 0x110000) {
     buff[0] = static_cast<char>(0xF0 | ((code >> 18) & 0x7));
     buff[1] = static_cast<char>(0x80 | ((code >> 12) & 0x3F));
     buff[2] = static_cast<char>(0x80 | ((code >> 6) & 0x3F));
     buff[3] = static_cast<char>(0x80 | (code & 0x3F));
     return 4;
   }
   // NOTREACHED
   return 0;
 }
Referenced by decode_url().
trim()
std::pair<size_t, size_t> httplib::detail::trim (const char * b, const char * e, size_t left, size_t right) inline
Definition at line 2557 of file httplib.h.
{
   while (b + left < e && is_space_or_tab(b[left])) {
     left++;
   }
   while (right > 0 && is_space_or_tab(b[right - 1])) {
     right--;
   }
   return std::make_pair(left, right);
 }
References is_space_or_tab().
Referenced by split(), and trim_copy().
trim_copy()
std::string httplib::detail::trim_copy (const std::string & s) inline
Definition at line 2568 of file httplib.h.
{
   auto r = trim(s.data(), s.data() + s.size(), 0, s.size());
   return s.substr(r.first, r.second - r.first);
 }
References trim().
Referenced by httplib::detail::MultipartFormDataParser::parse().
trim_double_quotes_copy()
std::string httplib::detail::trim_double_quotes_copy (const std::string & s) inline
Definition at line 2573 of file httplib.h.
{
   if (s.length() >= 2 && s.front() == '"' && s.back() == '"') {
     return s.substr(1, s.size() - 2);
   }
   return s;
 }
Referenced by parse_multipart_boundary().
wait_until_socket_is_ready()
Error httplib::detail::wait_until_socket_is_ready (socket_t sock, time_t sec, time_t usec) inline
Definition at line 2870 of file httplib.h.
{
 #ifdef CPPHTTPLIB_USE_POLL
   struct pollfd pfd_read;
   pfd_read.fd = sock;
   pfd_read.events = POLLIN | POLLOUT;
   auto timeout = static_cast<int>(sec * 1000 + usec / 1000);
   auto poll_res = handle_EINTR([&]() { return poll(&pfd_read, 1, timeout); });
   if (poll_res == 0) { return Error::ConnectionTimeout; }
   if (poll_res > 0 && pfd_read.revents & (POLLIN | POLLOUT)) {
     auto error = 0;
     socklen_t len = sizeof(error);
     auto res = getsockopt(sock, SOL_SOCKET, SO_ERROR,
                           reinterpret_cast<char *>(&error), &len);
     auto successful = res >= 0 && !error;
     return successful ? Error::Success : Error::Connection;
   }
   return Error::Connection;
 #else
 #ifndef _WIN32
   if (sock >= FD_SETSIZE) { return Error::Connection; }
 #endif
   fd_set fdsr;
   FD_ZERO(&fdsr);
   FD_SET(sock, &fdsr);
   auto fdsw = fdsr;
   auto fdse = fdsr;
   timeval tv;
   tv.tv_sec = static_cast<long>(sec);
   tv.tv_usec = static_cast<decltype(tv.tv_usec)>(usec);
   auto ret = handle_EINTR([&]() {
     return select(static_cast<int>(sock + 1), &fdsr, &fdsw, &fdse, &tv);
   });
   if (ret == 0) { return Error::ConnectionTimeout; }
   if (ret > 0 && (FD_ISSET(sock, &fdsr) || FD_ISSET(sock, &fdsw))) {
     auto error = 0;
     socklen_t len = sizeof(error);
     auto res = getsockopt(sock, SOL_SOCKET, SO_ERROR,
                           reinterpret_cast<char *>(&error), &len);
     auto successful = res >= 0 && !error;
     return successful ? Error::Success : Error::Connection;
   }
   return Error::Connection;
 #endif
 }
References httplib::Connection, httplib::ConnectionTimeout, handle_EINTR(), sec, and httplib::Success.
Referenced by create_client_socket().
write_content() [1/2]
template<typename T > bool httplib::detail::write_content (Stream & strm, const ContentProvider & content_provider, size_t offset, size_t length, const T & is_shutting_down) inline
Definition at line 4108 of file httplib.h.
{
   auto error = Error::Success;
   return write_content(strm, content_provider, offset, length, is_shutting_down,
                        error);
 }
Referenced by write_multipart_ranges_data().
write_content() [2/2]
template<typename T > bool httplib::detail::write_content (Stream & strm, const ContentProvider & content_provider, size_t offset, size_t length, T is_shutting_down, Error & error) inline
Definition at line 4070 of file httplib.h.
{
   size_t end_offset = offset + length;
   auto ok = true;
   DataSink data_sink;
   data_sink.write = [&](const char *d, size_t l) -> bool {
     if (ok) {
       if (strm.is_writable() && write_data(strm, d, l)) {
         offset += l;
       } else {
         ok = false;
       }
     }
     return ok;
   };
   data_sink.is_writable = [&]() -> bool { return strm.is_writable(); };
   while (offset < end_offset && !is_shutting_down()) {
     if (!strm.is_writable()) {
       error = Error::Write;
       return false;
     } else if (!content_provider(offset, end_offset - offset, data_sink)) {
       error = Error::Canceled;
       return false;
     } else if (!ok) {
       error = Error::Write;
       return false;
     }
   }
   error = Error::Success;
   return true;
 }
References httplib::DataSink::is_writable, httplib::Stream::is_writable(), httplib::DataSink::write, and write_data().
Referenced by httplib::Server::write_content_with_provider(), and httplib::ClientImpl::write_content_with_provider().
write_content_chunked() [1/2]
template<typename T , typename U > bool httplib::detail::write_content_chunked (Stream & strm, const ContentProvider & content_provider, const T & is_shutting_down, U & compressor) inline
Definition at line 4256 of file httplib.h.
{
   auto error = Error::Success;
   return write_content_chunked(strm, content_provider, is_shutting_down,
                                compressor, error);
 }
write_content_chunked() [2/2]
template<typename T , typename U > bool httplib::detail::write_content_chunked (Stream & strm, const ContentProvider & content_provider, const T & is_shutting_down, U & compressor, Error & error) inline
Definition at line 4152 of file httplib.h.
{
   size_t offset = 0;
   auto data_available = true;
   auto ok = true;
   DataSink data_sink;
   data_sink.write = [&](const char *d, size_t l) -> bool {
     if (ok) {
       data_available = l > 0;
       offset += l;
       std::string payload;
       if (compressor.compress(d, l, false,
                               [&](const char *data, size_t data_len) {
                                 payload.append(data, data_len);
                                 return true;
                               })) {
         if (!payload.empty()) {
           // Emit chunked response header and footer for each chunk
           auto chunk =
               from_i_to_hex(payload.size()) + "\r\n" + payload + "\r\n";
           if (!strm.is_writable() ||
               !write_data(strm, chunk.data(), chunk.size())) {
             ok = false;
           }
         }
       } else {
         ok = false;
       }
     }
     return ok;
   };
   data_sink.is_writable = [&]() -> bool { return strm.is_writable(); };
   auto done_with_trailer = [&](const Headers *trailer) {
     if (!ok) { return; }
     data_available = false;
     std::string payload;
     if (!compressor.compress(nullptr, 0, true,
                              [&](const char *data, size_t data_len) {
                                payload.append(data, data_len);
                                return true;
                              })) {
       ok = false;
       return;
     }
     if (!payload.empty()) {
       // Emit chunked response header and footer for each chunk
       auto chunk = from_i_to_hex(payload.size()) + "\r\n" + payload + "\r\n";
       if (!strm.is_writable() ||
           !write_data(strm, chunk.data(), chunk.size())) {
         ok = false;
         return;
       }
     }
     static const std::string done_marker("0\r\n");
     if (!write_data(strm, done_marker.data(), done_marker.size())) {
       ok = false;
     }
     // Trailer
     if (trailer) {
       for (const auto &kv : *trailer) {
         std::string field_line = kv.first + ": " + kv.second + "\r\n";
         if (!write_data(strm, field_line.data(), field_line.size())) {
           ok = false;
         }
       }
     }
     static const std::string crlf("\r\n");
     if (!write_data(strm, crlf.data(), crlf.size())) { ok = false; }
   };
   data_sink.done = [&](void) { done_with_trailer(nullptr); };
   data_sink.done_with_trailer = [&](const Headers &trailer) {
     done_with_trailer(&trailer);
   };
   while (data_available && !is_shutting_down()) {
     if (!strm.is_writable()) {
       error = Error::Write;
       return false;
     } else if (!content_provider(offset, 0, data_sink)) {
       error = Error::Canceled;
       return false;
     } else if (!ok) {
       error = Error::Write;
       return false;
     }
   }
   error = Error::Success;
   return true;
 }
References httplib::detail::compressor::compress(), httplib::DataSink::done, httplib::DataSink::done_with_trailer, from_i_to_hex(), httplib::DataSink::is_writable, httplib::Stream::is_writable(), nlohmann::detail::void(), httplib::DataSink::write, and write_data().
Referenced by httplib::Server::write_content_with_provider(), and httplib::ClientImpl::write_content_with_provider().
write_content_without_length()
template<typename T > bool httplib::detail::write_content_without_length (Stream & strm, const ContentProvider & content_provider, const T & is_shutting_down) inline
Definition at line 4118 of file httplib.h.
{
   size_t offset = 0;
   auto data_available = true;
   auto ok = true;
   DataSink data_sink;
   data_sink.write = [&](const char *d, size_t l) -> bool {
     if (ok) {
       offset += l;
       if (!strm.is_writable() || !write_data(strm, d, l)) { ok = false; }
     }
     return ok;
   };
   data_sink.is_writable = [&]() -> bool { return strm.is_writable(); };
   data_sink.done = [&](void) { data_available = false; };
   while (data_available && !is_shutting_down()) {
     if (!strm.is_writable()) {
       return false;
     } else if (!content_provider(offset, 0, data_sink)) {
       return false;
     } else if (!ok) {
       return false;
     }
   }
   return true;
 }
References httplib::DataSink::done, httplib::DataSink::is_writable, httplib::Stream::is_writable(), nlohmann::detail::void(), httplib::DataSink::write, and write_data().
Referenced by httplib::Server::write_content_with_provider().
write_data()
bool httplib::detail::write_data (Stream & strm, const char * d, size_t l) inline
Definition at line 4059 of file httplib.h.
{
   size_t offset = 0;
   while (offset < l) {
     auto length = strm.write(d + offset, l - offset);
     if (length < 0) { return false; }
     offset += static_cast<size_t>(length);
   }
   return true;
 }
References httplib::Stream::write().
Referenced by write_content(), write_content_chunked(), write_content_without_length(), httplib::ClientImpl::write_request(), and httplib::Server::write_response_core().
write_headers()
ssize_t httplib::detail::write_headers (Stream & strm, const Headers & headers) inline
Definition at line 4045 of file httplib.h.
{
   ssize_t write_len = 0;
   for (const auto &x : headers) {
     auto len =
         strm.write_format("%s: %s\r\n", x.first.c_str(), x.second.c_str());
     if (len < 0) { return len; }
     write_len += len;
   }
   auto len = strm.write("\r\n");
   if (len < 0) { return len; }
   write_len += len;
   return write_len;
 }
References httplib::Stream::write(), and httplib::Stream::write_format().
write_multipart_ranges_data()
template<typename T > bool httplib::detail::write_multipart_ranges_data (Stream & strm, const Request & req, Response & res, const std::string & boundary, const std::string & content_type, size_t content_length, const T & is_shutting_down) inline
Definition at line 4891 of file httplib.h.
{
   return process_multipart_ranges_data(
       req, boundary, content_type, content_length,
       [&](const std::string &token) { strm.write(token); },
       [&](const std::string &token) { strm.write(token); },
       [&](size_t offset, size_t length) {
         return write_content(strm, res.content_provider_, offset, length,
                              is_shutting_down);
       });
 }
References httplib::Response::content_provider_, process_multipart_ranges_data(), httplib::Stream::write(), and write_content().
Referenced by httplib::Server::write_content_with_provider().