Mixed Criticality Orchestrator: udt Namespace Reference
udt Namespace Reference
Classes
struct address
struct age
struct contact
struct contact_book
struct name
struct person
Enumerations
enum country { country::china, country::france, country::russia }
Functions
template<typename BasicJsonType >
void to_json (BasicJsonType &j, age a)
template<typename BasicJsonType >
void to_json (BasicJsonType &j, const name &n)
template<typename BasicJsonType >
void to_json (BasicJsonType &j, country c)
template<typename BasicJsonType >
void to_json (BasicJsonType &j, const person &p)
void to_json (nlohmann::json &j, const address &a)
void to_json (nlohmann::json &j, const contact &c)
void to_json (nlohmann::json &j, const contact_book &cb)
bool operator== (age lhs, age rhs)
bool operator== (const address &lhs, const address &rhs)
bool operator== (const name &lhs, const name &rhs)
bool operator== (const person &lhs, const person &rhs)
bool operator== (const contact &lhs, const contact &rhs)
bool operator== (const contact_book &lhs, const contact_book &rhs)
template<typename BasicJsonType >
void from_json (const BasicJsonType &j, age &a)
template<typename BasicJsonType >
void from_json (const BasicJsonType &j, name &n)
template<typename BasicJsonType >
void from_json (const BasicJsonType &j, country &c)
template<typename BasicJsonType >
void from_json (const BasicJsonType &j, person &p)
void from_json (const nlohmann::json &j, address &a)
void from_json (const nlohmann::json &j, contact &c)
void from_json (const nlohmann::json &j, contact_book &cb)
Enumeration Type Documentation
country
enum udt::country strong
Enumerator
china
france
russia
Definition at line 42 of file unit-udt.cpp.
 {
     china,
     france,
     russia
 };
Function Documentation
from_json() [1/7]
template<typename BasicJsonType > void udt::from_json (const BasicJsonType & j, age & a)
Definition at line 185 of file unit-udt.cpp.
 {
     a.m_val = j.template get<int>();
 }
References udt::age::m_val.
from_json() [2/7]
template<typename BasicJsonType > void udt::from_json (const BasicJsonType & j, country & c)
Definition at line 197 of file unit-udt.cpp.
 {
     const auto str = j.template get<std::string>();
     static const std::map<std::string, country> m =
     {
         {u8"中华人民共和国", country::china},
         {"France", country::france},
         {u8"Российская Федерация", country::russia}
     };
     const auto it = m.find(str);
     // TODO test exceptions
     c = it->second;
 }
References c, china, france, and russia.
from_json() [3/7]
template<typename BasicJsonType > void udt::from_json (const BasicJsonType & j, name & n)
Definition at line 191 of file unit-udt.cpp.
 {
     n.m_val = j.template get<std::string>();
 }
References udt::name::m_val, and n.
from_json() [4/7]
template<typename BasicJsonType > void udt::from_json (const BasicJsonType & j, person & p)
Definition at line 213 of file unit-udt.cpp.
 {
     p.m_age = j["age"].template get<age>();
     p.m_name = j["name"].template get<name>();
     p.m_country = j["country"].template get<country>();
 }
References udt::person::m_age, udt::person::m_country, and udt::person::m_name.
from_json() [5/7]
void udt::from_json (const nlohmann::json & j, address & a)
Definition at line 220 of file unit-udt.cpp.
 {
     a.m_val = j.get<std::string>();
 }
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get(), and udt::address::m_val.
from_json() [6/7]
void udt::from_json (const nlohmann::json & j, contact & c)
Definition at line 225 of file unit-udt.cpp.
 {
     c.m_person = j["person"].get<person>();
     c.m_address = j["address"].get<address>();
 }
References c, and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get().
from_json() [7/7]
void udt::from_json (const nlohmann::json & j, contact_book & cb)
Definition at line 231 of file unit-udt.cpp.
 {
     cb.m_book_name = j["name"].get<name>();
     cb.m_contacts = j["contacts"].get<std::vector<contact>>();
 }
References cb, and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get().
operator==() [1/6]
bool udt::operator== (age lhs, age rhs)
Definition at line 148 of file unit-udt.cpp.
 {
     return lhs.m_val == rhs.m_val;
 }
References udt::age::m_val.
operator==() [2/6]
bool udt::operator== (const address & lhs, const address & rhs)
Definition at line 153 of file unit-udt.cpp.
 {
     return lhs.m_val == rhs.m_val;
 }
References udt::address::m_val.
operator==() [3/6]
bool udt::operator== (const contact & lhs, const contact & rhs)
Definition at line 168 of file unit-udt.cpp.
 {
     return std::tie(lhs.m_person, lhs.m_address) ==
            std::tie(rhs.m_person, rhs.m_address);
 }
References udt::contact::m_address, and udt::contact::m_person.
operator==() [4/6]
bool udt::operator== (const contact_book & lhs, const contact_book & rhs)
Definition at line 174 of file unit-udt.cpp.
 {
     return std::tie(lhs.m_book_name, lhs.m_contacts) ==
            std::tie(rhs.m_book_name, rhs.m_contacts);
 }
References udt::contact_book::m_book_name, and udt::contact_book::m_contacts.
operator==() [5/6]
bool udt::operator== (const name & lhs, const name & rhs)
Definition at line 158 of file unit-udt.cpp.
 {
     return lhs.m_val == rhs.m_val;
 }
References udt::name::m_val.
operator==() [6/6]
bool udt::operator== (const person & lhs, const person & rhs)
Definition at line 163 of file unit-udt.cpp.
 {
     return std::tie(lhs.m_name, lhs.m_age) == std::tie(rhs.m_name, rhs.m_age);
 }
References udt::person::m_age, and udt::person::m_name.
to_json() [1/7]
template<typename BasicJsonType > void udt::to_json (BasicJsonType & j, age a)
Definition at line 98 of file unit-udt.cpp.
 {
     j = a.m_val;
 }
References udt::age::m_val.
to_json() [2/7]
template<typename BasicJsonType > void udt::to_json (BasicJsonType & j, const name & n)
Definition at line 104 of file unit-udt.cpp.
 {
     j = n.m_val;
 }
References udt::name::m_val, and n.
to_json() [3/7]
template<typename BasicJsonType > void udt::to_json (BasicJsonType & j, const person & p)
Definition at line 127 of file unit-udt.cpp.
 {
     j = BasicJsonType{{"age", p.m_age}, {"name", p.m_name}, {"country", p.m_country}};
 }
References udt::person::m_age, udt::person::m_country, and udt::person::m_name.
to_json() [4/7]
template<typename BasicJsonType > void udt::to_json (BasicJsonType & j, country c)
Definition at line 110 of file unit-udt.cpp.
 {
     switch (c)
     {
         case country::china:
             j = u8"中华人民共和国";
             return;
         case country::france:
             j = "France";
             return;
         case country::russia:
             j = u8"Российская Федерация";
             return;
     }
 }
References c, china, france, and russia.
to_json() [5/7]
void udt::to_json (nlohmann::json & j, const address & a)
Definition at line 132 of file unit-udt.cpp.
 {
     j = a.m_val;
 }
References udt::address::m_val.
to_json() [6/7]
void udt::to_json (nlohmann::json & j, const contact & c)
Definition at line 137 of file unit-udt.cpp.
 {
     j = json{{"person", c.m_person}, {"address", c.m_address}};
 }
References c.
to_json() [7/7]
void udt::to_json (nlohmann::json & j, const contact_book & cb)
Definition at line 142 of file unit-udt.cpp.
 {
     j = json{{"name", cb.m_book_name}, {"contacts", cb.m_contacts}};
 }
References cb.