Mixed Criticality Orchestrator: doctest Namespace Reference
doctest Namespace Reference
Namespaces
assertType
Color
detail
TestCaseFailureReason
Classes
class Approx
struct AssertData
class Context
struct ContextOptions
OCLINT too many fields.
struct CurrentTestCaseStats
struct description
struct expected_failures
struct IContextScope
struct IReporter
struct may_fail
struct MessageData
struct QueryData
struct should_fail
struct skip
class String
struct StringMaker
struct StringMaker< R C::* >
struct StringMaker< T * >
struct SubcaseSignature
struct test_suite
struct TestCaseData
struct TestCaseException
struct TestRunStats
struct timeout
Functions
bool operator== (const String &lhs, const String &rhs)
bool operator!= (const String &lhs, const String &rhs)
bool operator< (const String &lhs, const String &rhs)
bool operator> (const String &lhs, const String &rhs)
bool operator<= (const String &lhs, const String &rhs)
bool operator>= (const String &lhs, const String &rhs)
std::ostream & operator<< (std::ostream &s, const String &in)
const char * assertString (assertType::Enum at)
const char * failureString (assertType::Enum at)
const char * skipPathFromFilename (const char *file)
template<typename T >
String toString (const T &value)
String toString (bool in)
String toString (float in)
String toString (double in)
String toString (double long in)
String toString (char in)
String toString (char signed in)
String toString (char unsigned in)
String toString (int short in)
String toString (int short unsigned in)
String toString (int in)
String toString (int unsigned in)
String toString (int long in)
String toString (int long unsigned in)
String toString (int long long in)
String toString (int long long unsigned in)
String toString (std::nullptr_t in)
String toString (const Approx &in)
const ContextOptions * getContextOptions ()
template<typename T >
int registerExceptionTranslator (String(*translateFunction)(T))
template<typename Reporter >
int registerReporter (const char *name, int priority, bool isReporter)
Variables
bool is_running_in_test
Function Documentation
assertString()
const char* doctest::assertString (assertType::Enum at)
failureString()
const char* doctest::failureString (assertType::Enum at)
getContextOptions()
const ContextOptions* doctest::getContextOptions ()
Referenced by doctest::detail::Expression_lhs< L >::__attribute__(), and doctest::detail::ResultBuilder::__attribute__().
operator!=()
bool doctest::operator!= (const String & lhs, const String & rhs)
operator<()
bool doctest::operator< (const String & lhs, const String & rhs)
operator<<()
std::ostream& doctest::operator<< (std::ostream & s, const String & in)
operator<=()
bool doctest::operator<= (const String & lhs, const String & rhs)
operator==()
bool doctest::operator== (const String & lhs, const String & rhs)
operator>()
bool doctest::operator> (const String & lhs, const String & rhs)
operator>=()
bool doctest::operator>= (const String & lhs, const String & rhs)
registerExceptionTranslator()
template<typename T > int doctest::registerExceptionTranslator (String(*)(T) translateFunction)
Definition at line 1552 of file doctest.h.
{
     DOCTEST_CLANG_SUPPRESS_WARNING_WITH_PUSH("-Wexit-time-destructors")
     static detail::ExceptionTranslator<T> exceptionTranslator(translateFunction);
     DOCTEST_CLANG_SUPPRESS_WARNING_POP
     detail::registerExceptionTranslatorImpl(&exceptionTranslator);
     return 0;
 }
References DOCTEST_CLANG_SUPPRESS_WARNING_POP, DOCTEST_CLANG_SUPPRESS_WARNING_WITH_PUSH, and doctest::detail::registerExceptionTranslatorImpl().
registerReporter()
template<typename Reporter > int doctest::registerReporter (const char * name, int priority, bool isReporter)
Definition at line 1718 of file doctest.h.
{
     detail::registerReporterImpl(name, priority, detail::reporterCreator<Reporter>, isReporter);
     return 0;
 }
References doctest::detail::registerReporterImpl().
skipPathFromFilename()
const char* doctest::skipPathFromFilename (const char * file)
toString() [1/18]
String doctest::toString (bool in)
toString() [2/18]
String doctest::toString (char in)
toString() [3/18]
String doctest::toString (char signed in)
toString() [4/18]
String doctest::toString (char unsigned in)
toString() [5/18]
String doctest::toString (const Approx & in)
toString() [6/18]
template<typename T > String doctest::toString (const T & value)
Definition at line 853 of file doctest.h.
{
     return StringMaker<T>::convert(value);
 }
References doctest::detail::StringMakerBase< detail::has_insertion_operator< T >::value >::convert().
Referenced by doctest::detail::Expression_lhs< L >::__attribute__(), doctest::detail::ResultBuilder::__attribute__(), doctest::detail::__attribute__(), doctest::detail::StringStreamBase< has_insertion_operator< T >::value >::convert(), and doctest::detail::stringifyBinaryExpr().
toString() [7/18]
String doctest::toString (double in)
toString() [8/18]
String doctest::toString (double long in)
toString() [9/18]
String doctest::toString (float in)
toString() [10/18]
String doctest::toString (int in)
toString() [11/18]
String doctest::toString (int long in)
toString() [12/18]
String doctest::toString (int long long in)
toString() [13/18]
String doctest::toString (int long long unsigned in)
toString() [14/18]
String doctest::toString (int long unsigned in)
toString() [15/18]
String doctest::toString (int short in)
toString() [16/18]
String doctest::toString (int short unsigned in)
toString() [17/18]
String doctest::toString (int unsigned in)
toString() [18/18]
String doctest::toString (std::nullptr_t in)
Variable Documentation
is_running_in_test
bool doctest::is_running_in_test