Mixed Criticality Orchestrator: benchmark::internal Namespace Reference
benchmark::internal Namespace Reference
Classes
class Benchmark
class CheckHandler
class FunctionBenchmark
class LogType
class ThreadManager
class ThreadTimer
Typedefs
typedef void() Function(State &)
typedef void() AbortHandlerT()
typedef std::basic_ostream< char > &() EndLType(std::basic_ostream< char > &)
Enumerations
enum ReportMode { RM_Unspecified, RM_Default, RM_ReportAggregatesOnly }
Functions
void UseCharPointer (char const volatile *)
Benchmark * RegisterBenchmarkInternal (Benchmark *)
int InitializeStreams ()
template<typename T , size_t N>
char(& ArraySizeHelper (T(&array)[N]))[N]
template<typename T , size_t N>
char(& ArraySizeHelper (const T(&array)[N]))[N]
bool FindBenchmarksInternal (const std::string &re, std::vector< Benchmark::Instance > *benchmarks, std::ostream *Err)
bool IsZero (double n)
ConsoleReporter::OutputOptions GetOutputOptions (bool force_no_color=false)
AbortHandlerT *& GetAbortHandler ()
void CallAbortHandler ()
void Finish (UserCounters *l, double time, double num_threads)
void Increment (UserCounters *l, UserCounters const &r)
bool SameNames (UserCounters const &l, UserCounters const &r)
template<class Tp >
LogType & operator<< (LogType &log, Tp const &value)
LogType & operator<< (LogType &log, EndLType *m)
int & LogLevel ()
LogType & GetNullLogInstance ()
LogType & GetErrorLogInstance ()
LogType & GetLogInstanceForLevel (int level)
Variables
static int stream_init_anchor = InitializeStreams()
Typedef Documentation
AbortHandlerT
typedef void() benchmark::internal::AbortHandlerT()
Definition at line 14 of file check.h.
EndLType
typedef std::basic_ostream<char>&() benchmark::internal::EndLType(std::basic_ostream< char > &)
Definition at line 12 of file log.h.
Function
typedef void() benchmark::internal::Function(State &)
Definition at line 724 of file benchmark.h.
Enumeration Type Documentation
ReportMode
enum benchmark::internal::ReportMode
Enumerator
RM_Unspecified
RM_Default
RM_ReportAggregatesOnly
Definition at line 406 of file benchmark.h.
   : unsigned
 #else
 #endif
   {
   RM_Unspecified,  // The mode has not been manually specified
   RM_Default,      // The mode is user-specified as default.
   RM_ReportAggregatesOnly
 };
Function Documentation
ArraySizeHelper() [1/2]
template<typename T , size_t N> char(& benchmark::internal::ArraySizeHelper (const T(&) array[N]))[N]
ArraySizeHelper() [2/2]
template<typename T , size_t N> char(& benchmark::internal::ArraySizeHelper (T(&) array[N]))[N]
CallAbortHandler()
void benchmark::internal::CallAbortHandler () inline
Definition at line 21 of file check.h.
{
   GetAbortHandler()();
   std::abort();  // fallback to enforce noreturn
 }
References GetAbortHandler().
Referenced by benchmark::internal::CheckHandler::~CheckHandler().
FindBenchmarksInternal()
bool benchmark::internal::FindBenchmarksInternal (const std::string & re, std::vector< Benchmark::Instance > * benchmarks, std::ostream * Err)
Finish()
void benchmark::internal::Finish (UserCounters * l, double time, double num_threads)
GetAbortHandler()
AbortHandlerT*& benchmark::internal::GetAbortHandler () inline
Definition at line 16 of file check.h.
{
   static AbortHandlerT* handler = &std::abort;
   return handler;
 }
Referenced by CallAbortHandler().
GetErrorLogInstance()
LogType& benchmark::internal::GetErrorLogInstance () inline
Definition at line 54 of file log.h.
{
   static LogType log(&std::clog);
   return log;
 }
Referenced by GetLogInstanceForLevel().
GetLogInstanceForLevel()
LogType& benchmark::internal::GetLogInstanceForLevel (int level) inline
Definition at line 59 of file log.h.
{
   if (level <= LogLevel()) {
     return GetErrorLogInstance();
   }
   return GetNullLogInstance();
 }
References GetErrorLogInstance(), GetNullLogInstance(), and LogLevel().
GetNullLogInstance()
LogType& benchmark::internal::GetNullLogInstance () inline
Definition at line 49 of file log.h.
{
   static LogType log(nullptr);
   return log;
 }
Referenced by GetLogInstanceForLevel().
GetOutputOptions()
ConsoleReporter::OutputOptions benchmark::internal::GetOutputOptions (bool force_no_color = false)
Increment()
void benchmark::internal::Increment (UserCounters * l, UserCounters const & r)
InitializeStreams()
int benchmark::internal::InitializeStreams ()
IsZero()
bool benchmark::internal::IsZero (double n)
LogLevel()
int& benchmark::internal::LogLevel () inline
Definition at line 44 of file log.h.
{
   static int log_level = 0;
   return log_level;
 }
Referenced by GetLogInstanceForLevel().
operator<<() [1/2]
LogType& benchmark::internal::operator<< (LogType & log, EndLType * m) inline
Definition at line 37 of file log.h.
{
   if (log.out_) {
     *log.out_ << m;
   }
   return log;
 }
References benchmark::internal::LogType::out_.
operator<<() [2/2]
template<class Tp > LogType& benchmark::internal::operator<< (LogType & log, Tp const & value)
Definition at line 30 of file log.h.
{
   if (log.out_) {
     *log.out_ << value;
   }
   return log;
 }
References benchmark::internal::LogType::out_.
RegisterBenchmarkInternal()
Benchmark* benchmark::internal::RegisterBenchmarkInternal (Benchmark *)
Referenced by benchmark::RegisterBenchmark().
SameNames()
bool benchmark::internal::SameNames (UserCounters const & l, UserCounters const & r)
UseCharPointer()
void benchmark::internal::UseCharPointer (char const volatile *)
Referenced by benchmark::DoNotOptimize().
Variable Documentation
stream_init_anchor
int benchmark::internal::stream_init_anchor = InitializeStreams() static
Definition at line 289 of file benchmark.h.