Mixed Criticality Orchestrator: FFI/QM_partition_level_memory_restriction/pacman_Qm_application/resource-utilizer-pinned.cpp File Reference
resource-utilizer-pinned.cpp File Reference
#include <iostream>
#include <vector>
#include <thread>
#include <chrono>
#include <atomic>
#include <cmath>
#include <iomanip>
#include <string>
#include <csignal>
#include <memory>
#include <algorithm>
#include <sstream>
#include <cstring>
#include <mutex>
#include <condition_variable>
#include <fstream>
#include <set>
#include <filesystem>
#include <sys/resource.h>
#include <unistd.h>
#include <pthread.h>
#include <sys/sysinfo.h>
#include <fcntl.h>
Functions
std::atomic< bool > stopRequested (false)
void signalHandler (int signal)
std::string formatSize (size_t bytesSize)
size_t convertToBytes (double gbAmount)
size_t getProcessMemoryUsage ()
int getCpuCount ()
void setThreadAffinity (int coreId)
void ensureLockDirectoryExists ()
bool tryLockCore (int coreId)
void unlockCore (int coreId)
std::vector< int > allocateAvailableCores (int numCores)
void releaseAllocatedCores ()
void exitHandler ()
void singleCoreWorker (int cpuPercent, int coreId)
std::vector< std::unique_ptr< std::vector< char > > > fillMemory (double targetGb, int stepMb=100, double delaySec=1.0)
void utilizeResources (double targetGb=0, int cpuCores=0, int cpuPercent=100, int stepMb=100, double delaySec=1.0, int startCoreId=-1)
void printUsage (const char *programName)
int main (int argc, char *argv[])
Variables
std::mutex consoleMutex
std::vector< int > allocatedCores
const std::string LOCK_DIR = "/tmp/resource-utilizer-locks/"
Function Documentation
allocateAvailableCores()
std::vector<int> allocateAvailableCores (int numCores)
Definition at line 168 of file resource-utilizer-pinned.cpp.
{
     std::vector<int> cores;
     int totalCores = getCpuCount();
     ensureLockDirectoryExists();
     // Try to allocate the requested number of cores
     for (int i = 0; i < totalCores && cores.size() < static_cast<size_t>(numCores); ++i) {
         if (tryLockCore(i)) {
             cores.push_back(i);
         }
     }
     return cores;
 }
References ensureLockDirectoryExists(), getCpuCount(), and tryLockCore().
Referenced by utilizeResources().
convertToBytes()
size_t convertToBytes (double gbAmount)
Definition at line 68 of file resource-utilizer-pinned.cpp.
{
     return static_cast<size_t>(gbAmount * 1024 * 1024 * 1024);
 }
Referenced by fillMemory().
ensureLockDirectoryExists()
void ensureLockDirectoryExists ()
Definition at line 112 of file resource-utilizer-pinned.cpp.
{
     std::filesystem::path dir(LOCK_DIR);
     if (!std::filesystem::exists(dir)) {
         std::filesystem::create_directories(dir);
     }
 }
References LOCK_DIR.
Referenced by allocateAvailableCores().
exitHandler()
void exitHandler ()
Definition at line 193 of file resource-utilizer-pinned.cpp.
                    {
     releaseAllocatedCores();
 }
References releaseAllocatedCores().
Referenced by main().
fillMemory()
std::vector<std::unique_ptr<std::vector<char> > > fillMemory (double targetGb, int stepMb = 100, double delaySec = 1.0)
Definition at line 233 of file resource-utilizer-pinned.cpp.
   {
     std::vector<std::unique_ptr<std::vector<char>>> memoryBlocks;
     std::cout << "Starting memory filler. Target: " << targetGb << " GB" << std::endl;
     if (targetGb != static_cast<int>(targetGb)) {
         // Show fractional breakdown for clarity
         int gbPart = static_cast<int>(targetGb);
         int mbPart = static_cast<int>((targetGb - gbPart) * 1024);
         std::cout << "  (" << gbPart << " GB and " << mbPart << " MB)" << std::endl;
     }
     // Calculate target in bytes
     size_t targetBytes = convertToBytes(targetGb);
     size_t stepBytes = static_cast<size_t>(stepMb) * 1024 * 1024;
     try {
         // Initial memory usage
         size_t initialUsage = getProcessMemoryUsage();
         size_t currentUsage = initialUsage;
         // Main allocation loop
         while (currentUsage < targetBytes && !stopRequested.load()) {
             // Create a new memory block
             auto memoryBlock = std::make_unique<std::vector<char>>(stepBytes, 1);
             memoryBlocks.push_back(std::move(memoryBlock));
             // Update current usage
             currentUsage = getProcessMemoryUsage();
             // Calculate and display progress
             size_t allocated = currentUsage - initialUsage;
             double progressPercent = std::min(100.0, (static_cast<double>(allocated) /
                                              (targetBytes - initialUsage)) * 100.0);
             // Print progress
             std::cout << "\rAllocated: " << formatSize(allocated) << " / "
                       << targetGb << " GB (" << std::fixed << std::setprecision(1)
                       << progressPercent << "%)";
             std::cout.flush();
             // Slow down to make the increase gradual
             std::this_thread::sleep_for(std::chrono::duration<double>(delaySec));
         }
         if (!stopRequested.load()) {
             std::cout << "\nReached target memory usage." << std::endl;
         }
     } catch (const std::bad_alloc&) {
         std::cout << "\nMemory Error: Cannot allocate more memory. System limit reached." << std::endl;
     } catch (const std::exception& e) {
         std::cout << "\nError during memory allocation: " << e.what() << std::endl;
     }
     return memoryBlocks;
 }
References convertToBytes(), formatSize(), getProcessMemoryUsage(), and stopRequested().
Referenced by utilizeResources().
formatSize()
std::string formatSize (size_t bytesSize)
Definition at line 52 of file resource-utilizer-pinned.cpp.
{
     const char* units[] = {"B", "KB", "MB", "GB"};
     double size = static_cast<double>(bytesSize);
     int unitIndex = 0;
     while (size >= 1024.0 && unitIndex < 3) {
         size /= 1024.0;
         unitIndex++;
     }
     std::ostringstream oss;
     oss << std::fixed << std::setprecision(2) << size << " " << units[unitIndex];
     return oss.str();
 }
Referenced by fillMemory().
getCpuCount()
int getCpuCount ()
Definition at line 94 of file resource-utilizer-pinned.cpp.
                   {
     return std::thread::hardware_concurrency();
 }
Referenced by allocateAvailableCores(), and utilizeResources().
getProcessMemoryUsage()
size_t getProcessMemoryUsage ()
Definition at line 73 of file resource-utilizer-pinned.cpp.
{
 #ifdef _WIN32
     PROCESS_MEMORY_COUNTERS_EX pmc;
     GetProcessMemoryInfo(GetCurrentProcess(), (PROCESS_MEMORY_COUNTERS*)&pmc, sizeof(pmc));
     return pmc.WorkingSetSize;
 #else
     // Linux
     FILE* file = fopen("/proc/self/statm", "r");
     if (file) {
         long rss;
         if (fscanf(file, "%*s %ld", &rss) == 1) {
             fclose(file);
             return rss * sysconf(_SC_PAGESIZE);
         }
         fclose(file);
     }
     return 0;
 #endif
 }
Referenced by fillMemory().
main()
int main (int argc, char * argv[])
Definition at line 417 of file resource-utilizer-pinned.cpp.
{
     // Default values
     double memory = 0;
     int cpu = 0;
     int cpuPercent = 100;
     int step = 100;
     double delay = 1.0;
     int startCore = -1;  // -1 means auto-allocate
     bool memorySpecified = false;
     // Parse command line arguments
     for (int i = 1; i < argc; ++i) {
         std::string arg = argv[i];
         if (arg == "--memory" && i + 1 < argc) {
             memory = std::stod(argv[++i]);
             memorySpecified = true;
         } else if (arg == "--cpu" && i + 1 < argc) {
             cpu = std::stoi(argv[++i]);
         } else if (arg == "--cpu-percent" && i + 1 < argc) {
             cpuPercent = std::stoi(argv[++i]);
         } else if (arg == "--step" && i + 1 < argc) {
             step = std::stoi(argv[++i]);
         } else if (arg == "--delay" && i + 1 < argc) {
             delay = std::stod(argv[++i]);
         } else if (arg == "--start-core" && i + 1 < argc) {
             startCore = std::stoi(argv[++i]);
         } else if (arg == "--help") {
             printUsage(argv[0]);
             return 0;
         } else {
             std::cerr << "Unknown option: " << arg << std::endl;
             printUsage(argv[0]);
             return 1;
         }
     }
     // Validate arguments
     if (memorySpecified && memory <= 0) {
         std::cerr << "Error: Memory target must be greater than 0 GB" << std::endl;
         return 1;
     }
     if (cpuPercent < 1 || cpuPercent > 100) {
         std::cerr << "Error: CPU percentage must be between 1 and 100" << std::endl;
         return 1;
     }
     if (cpu == 0 && !memorySpecified) {
         std::cerr << "Error: Must specify at least one resource to utilize (--memory and/or --cpu)" << std::endl;
         return 1;
     }
     // Set up signal handling for Ctrl+C
     std::signal(SIGINT, signalHandler);
     // Register exit handler to ensure we release locks on exit
     std::atexit(exitHandler);
     // Run the resource utilization
     utilizeResources(memory, cpu, cpuPercent, step, delay, startCore);
     return 0;
 }
References argv, exitHandler(), printUsage(), signalHandler(), and utilizeResources().
printUsage()
void printUsage (const char * programName)
Definition at line 399 of file resource-utilizer-pinned.cpp.
{
     std::cout << "Usage:\n\n";
     std::cout << "# CPU only: Use 2 cores at 70% each\n";
     std::cout << programName << " --cpu 2 --cpu-percent 70\n\n";
     std::cout << "# Memory only: Allocate 3.2GB of memory\n";
     std::cout << programName << " --memory 3.2\n\n";
     std::cout << "# Both: Use 1 core at 100% and 1GB of memory\n";
     std::cout << programName << " --cpu 1 --memory 1\n\n";
     std::cout << "# With manual core selection: Use cores 4, 5, 6\n";
     std::cout << programName << " --cpu 3 --start-core 4\n\n";
     std::cout << "# Full options example\n";
     std::cout << programName << " --cpu 2 --cpu-percent 80 --memory 4.5 --step 50 --delay 0.5\n";
 }
Referenced by main().
releaseAllocatedCores()
void releaseAllocatedCores ()
Definition at line 185 of file resource-utilizer-pinned.cpp.
{
     for (int coreId : allocatedCores) {
         unlockCore(coreId);
     }
     allocatedCores.clear();
 }
References allocatedCores, and unlockCore().
Referenced by exitHandler(), and utilizeResources().
setThreadAffinity()
void setThreadAffinity (int coreId)
Definition at line 99 of file resource-utilizer-pinned.cpp.
{
 #ifdef _WIN32
     SetThreadAffinityMask(GetCurrentThread(), (1ULL << coreId));
 #else
     // Linux
     cpu_set_t cpuset;
     CPU_ZERO(&cpuset);
     CPU_SET(coreId, &cpuset);
     pthread_setaffinity_np(pthread_self(), sizeof(cpu_set_t), &cpuset);
 #endif
 }
Referenced by singleCoreWorker().
signalHandler()
void signalHandler (int signal)
Definition at line 44 of file resource-utilizer-pinned.cpp.
{
     if (signal == SIGINT) {
         std::cout << "\nInterrupted by user. Releasing resources..." << std::endl;
         stopRequested.store(true);
     }
 }
References stopRequested().
Referenced by main().
singleCoreWorker()
void singleCoreWorker (int cpuPercent, int coreId)
Definition at line 198 of file resource-utilizer-pinned.cpp.
{
     try {
         // Set thread affinity to pin to a specific core
         setThreadAffinity(coreId);
         // Calculate work/sleep ratio based on target percentage
         const double cycleTime = 0.01; // Total cycle time in seconds
         const double workTime = cycleTime * (cpuPercent / 100.0);
         const double sleepTime = cycleTime - workTime;
         // Get high-resolution timing
         using Clock = std::chrono::high_resolution_clock;
         using Duration = std::chrono::duration<double>;
         while (!stopRequested.load()) {
             // Work phase - busy loop to consume CPU
             auto startTime = Clock::now();
             while (Duration(Clock::now() - startTime).count() < workTime) {
                 // Busy loop
                 // Add a small calculation to prevent compiler optimization
                 volatile double x = std::sin(static_cast<double>(Clock::now().time_since_epoch().count()));
             }
             // Sleep phase - release CPU
             if (sleepTime > 0) {
                 std::this_thread::sleep_for(std::chrono::duration<double>(sleepTime));
             }
         }
     } catch (const std::exception& e) {
         std::lock_guard<std::mutex> lock(consoleMutex);
         std::cerr << "Error in CPU worker thread on core " << coreId << ": " << e.what() << std::endl;
     }
 }
References consoleMutex, setThreadAffinity(), and stopRequested().
Referenced by utilizeResources().
stopRequested()
std::atomic<bool> stopRequested (false)
Referenced by fillMemory(), signalHandler(), singleCoreWorker(), and utilizeResources().
tryLockCore()
bool tryLockCore (int coreId)
Definition at line 120 of file resource-utilizer-pinned.cpp.
{
     std::string lockFile = LOCK_DIR + "core_" + std::to_string(coreId) + ".lock";
 #ifdef _WIN32
     HANDLE fileHandle = CreateFile(
         lockFile.c_str(),
         GENERIC_WRITE,
         0,  // No sharing
         NULL,
         CREATE_NEW,  // Only create if it doesn't exist
         FILE_ATTRIBUTE_NORMAL,
         NULL
     );
     if (fileHandle == INVALID_HANDLE_VALUE) {
         return false;
     }
     // Write PID to the file
     DWORD pid = GetCurrentProcessId();
     DWORD bytesWritten;
     WriteFile(fileHandle, &pid, sizeof(pid), &bytesWritten, NULL);
     // Don't close the handle - keep it open to maintain the lock
     return true;
 #else
     // Linux
     int fd = open(lockFile.c_str(), O_CREAT | O_EXCL | O_WRONLY, 0644);
     if (fd == -1) {
         return false;
     }
     // Write PID to the file
     pid_t pid = getpid();
     write(fd, &pid, sizeof(pid));
     // Don't close the file descriptor - keep it open to maintain the lock
     return true;
 #endif
 }
References LOCK_DIR, and httplib::to_string().
Referenced by allocateAvailableCores().
unlockCore()
void unlockCore (int coreId)
Definition at line 162 of file resource-utilizer-pinned.cpp.
{
     std::string lockFile = LOCK_DIR + "core_" + std::to_string(coreId) + ".lock";
     std::filesystem::remove(lockFile);
 }
References LOCK_DIR, and httplib::to_string().
Referenced by releaseAllocatedCores().
utilizeResources()
void utilizeResources (double targetGb = 0, int cpuCores = 0, int cpuPercent = 100, int stepMb = 100, double delaySec = 1.0, int startCoreId = -1)
Definition at line 295 of file resource-utilizer-pinned.cpp.
   {
     std::vector<std::thread> cpuThreads;
     std::vector<std::unique_ptr<std::vector<char>>> memoryBlocks;
     std::cout << "Press Ctrl+C to stop the program at any time" << std::endl;
     // Start CPU utilization if requested
     if (cpuCores > 0) {
         int maxCores = getCpuCount();
         int coresToUse = std::min(cpuCores, maxCores);
         // Ensure CPU percentage is valid
         cpuPercent = std::max(1, std::min(100, cpuPercent));
         // Auto-allocate cores if startCoreId is -1
         if (startCoreId == -1) {
             allocatedCores = allocateAvailableCores(coresToUse);
             if (allocatedCores.size() < static_cast<size_t>(coresToUse)) {
                 std::cout << "Warning: Could only allocate " << allocatedCores.size()
                           << " cores out of " << coresToUse << " requested." << std::endl;
                 coresToUse = allocatedCores.size();
             }
             std::cout << "Starting CPU utilization on " << coresToUse << " cores at "
                       << cpuPercent << "% per core" << std::endl;
             if (coresToUse > 0) {
                 std::cout << "Using CPU cores: ";
                 for (size_t i = 0; i < allocatedCores.size(); ++i) {
                     std::cout << allocatedCores[i];
                     if (i < allocatedCores.size() - 1) {
                         std::cout << ", ";
                     }
                 }
                 std::cout << std::endl;
             }
             // Start a thread for each allocated core
             for (int coreId : allocatedCores) {
                 cpuThreads.emplace_back(singleCoreWorker, cpuPercent, coreId);
             }
         } else {
             // Manual core allocation using specified start core ID
             std::cout << "Starting CPU utilization on " << coresToUse << " cores at "
                       << cpuPercent << "% per core" << std::endl;
             std::cout << "Using CPU cores: ";
             for (int i = 0; i < coresToUse; ++i) {
                 int coreId = (startCoreId + i) % maxCores;
                 std::cout << coreId;
                 if (i < coresToUse - 1) {
                     std::cout << ", ";
                 }
                 cpuThreads.emplace_back(singleCoreWorker, cpuPercent, coreId);
             }
             std::cout << std::endl;
         }
         std::cout << "Each thread is pinned to a specific CPU core" << std::endl;
     }
     // Start memory utilization if requested
     if (targetGb > 0) {
         memoryBlocks = fillMemory(targetGb, stepMb, delaySec);
     }
     // Keep running if either CPU or memory is being utilized
     if (cpuCores > 0 || targetGb > 0) {
         std::cout << "\nResources allocated. Press Ctrl+C to exit and release resources." << std::endl;
         // Keep the program running until interrupted
         while (!stopRequested.load()) {
             std::this_thread::sleep_for(std::chrono::seconds(1));
         }
     } else {
         std::cout << "No resources were requested to be utilized." << std::endl;
     }
     // Signal and wait for all threads to complete
     stopRequested.store(true);
     for (auto& thread : cpuThreads) {
         if (thread.joinable()) {
             thread.join();
         }
     }
     // Release memory explicitly
     memoryBlocks.clear();
     // Release core locks
     releaseAllocatedCores();
     std::cout << "Resources released." << std::endl;
 }
References allocateAvailableCores(), allocatedCores, fillMemory(), getCpuCount(), releaseAllocatedCores(), singleCoreWorker(), and stopRequested().
Referenced by main().
Variable Documentation
allocatedCores
std::vector<int> allocatedCores
Definition at line 38 of file resource-utilizer-pinned.cpp.
Referenced by releaseAllocatedCores(), and utilizeResources().
consoleMutex
std::mutex consoleMutex
Definition at line 37 of file resource-utilizer-pinned.cpp.
Referenced by singleCoreWorker().
LOCK_DIR
const std::string LOCK_DIR = "/tmp/resource-utilizer-locks/"
Definition at line 41 of file resource-utilizer-pinned.cpp.
Referenced by ensureLockDirectoryExists(), tryLockCore(), and unlockCore().