Mixed Criticality Orchestrator: mc_orchestrator/json-3.7.3/doc/examples/sax_parse.cpp File Reference
sax_parse.cpp File Reference
#include <iostream>
#include <iomanip>
#include <sstream>
#include <nlohmann/json.hpp>
Classes
class sax_event_consumer
Typedefs
using json = nlohmann::json
Functions
int main ()
for (auto &event :sec.events)
Variables
Animated __pad3__
Animated IDs
Animated Distance
sax_event_consumer sec
bool result = json::sax_parse(text, &sec)
Typedef Documentation
json
using json = nlohmann::json
Definition at line 6 of file sax_parse.cpp.
Function Documentation
for()
for (auto &event :sec. events)
Definition at line 117 of file sax_parse.cpp.
                      : sec.events)
     {
         std::cout << "(" << event << ") ";
     }
main()
int main ()
Definition at line 89 of file sax_parse.cpp.
 {
     // a JSON text
     auto text = R"(
     {
         "Image": {
             "Width":  800,
             "Height": 600,
             "Title":  "View from 15th Floor",
             "Thumbnail": {
                 "Url":    "http://www.example.com/image/481989943",
                 "Height": 125,
                 "Width":  100
             },
Variable Documentation
__pad3__
Animated __pad3__
Definition at line 102 of file sax_parse.cpp.
Distance
Animated Distance
Definition at line 104 of file sax_parse.cpp.
IDs
Animated IDs
Definition at line 104 of file sax_parse.cpp.
result
bool result = json::sax_parse(text, &sec)
Definition at line 114 of file sax_parse.cpp.
Referenced by __sanitizer_weak_hook_memcmp(), __sanitizer_weak_hook_strcasecmp(), __sanitizer_weak_hook_strcmp(), __sanitizer_weak_hook_strncasecmp(), __sanitizer_weak_hook_strncmp(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::begin(), httplib::detail::bind_ip_address(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_array_size(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_object_size(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::cbegin(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::cend(), httplib::detail::create_socket(), httplib::detail::decode_url(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::diff(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::dump(), httplib::detail::encode_url(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::end(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::erase(), BluechiStartAsilUnitCommand::Execute(), BluechiStartQmUnitCommand::Execute(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::find(), nlohmann::json_pointer< BasicJsonType >::flatten(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::flatten(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::from_bson(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::from_cbor(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::from_msgpack(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::from_ubjson(), nlohmann::json_pointer< BasicJsonType >::get_and_create(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_bson_cstr(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_bson_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_cbor_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_msgpack_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_string(), nlohmann::detail::lexer< BasicJsonType >::get_token_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_size_type(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_size_value(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::get_ubjson_string(), httplib::hosted_at(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::insert_iterator(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::meta(), nlohmann::detail::primitive_iterator_t::operator+(), nlohmann::detail::iter_impl< BasicJsonType >::operator+(), nlohmann::detail::primitive_iterator_t::operator++(), nlohmann::detail::iter_impl< BasicJsonType >::operator++(), nlohmann::detail::iter_impl< BasicJsonType >::operator-(), nlohmann::detail::primitive_iterator_t::operator--(), nlohmann::detail::iter_impl< BasicJsonType >::operator--(), nlohmann::detail::parser< BasicJsonType >::parse(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parse(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::patch(), httplib::detail::random_string(), nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax_parse(), nlohmann::detail::parser< BasicJsonType >::sax_parse(), nlohmann::json_pointer< BasicJsonType >::split(), TEST_CASE(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::to_bson(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::to_cbor(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::to_msgpack(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::to_ubjson(), nlohmann::json_pointer< BasicJsonType >::top(), and nlohmann::json_pointer< BasicJsonType >::unflatten().
sec
sax_event_consumer sec
Definition at line 111 of file sax_parse.cpp.
Referenced by httplib::detail::duration_to_sec_and_usec(), httplib::detail::select_read(), httplib::detail::select_write(), httplib::ClientImpl::set_connection_timeout(), httplib::Client::set_connection_timeout(), httplib::Server::set_idle_interval(), httplib::Server::set_keep_alive_timeout(), httplib::Server::set_read_timeout(), httplib::ClientImpl::set_read_timeout(), httplib::Client::set_read_timeout(), httplib::Server::set_write_timeout(), httplib::ClientImpl::set_write_timeout(), httplib::Client::set_write_timeout(), and httplib::detail::wait_until_socket_is_ready().