Mixed Criticality Orchestrator: httplib::ClientImpl::Socket Struct Reference
httplib::ClientImpl::Socket Struct Reference
#include <httplib.h>
Public Member Functions
bool is_open () const
Public Attributes
socket_t sock = (-1)
Detailed Description
Definition at line 1317 of file httplib.h.
Member Function Documentation
is_open()
bool httplib::ClientImpl::Socket::is_open () const inline
Definition at line 1323 of file httplib.h.
 { return sock != INVALID_SOCKET; }
References INVALID_SOCKET, and sock.
Referenced by httplib::ClientImpl::is_socket_open(), and httplib::ClientImpl::send_().
Member Data Documentation
sock
socket_t httplib::ClientImpl::Socket::sock = (-1)
Definition at line 1318 of file httplib.h.
Referenced by is_open(), httplib::ClientImpl::send_(), and httplib::ClientImpl::socket().
The documentation for this struct was generated from the following file:
mc_orchestrator/httplib/httplib.h