Mixed Criticality Orchestrator: fuzzer::Merger Struct Reference
fuzzer::Merger Struct Reference
#include <FuzzerMerge.h>
Public Member Functions
bool Parse (std::istream &IS, bool ParseCoverage)
bool Parse (const std::string &Str, bool ParseCoverage)
void ParseOrExit (std::istream &IS, bool ParseCoverage)
size_t Merge (std::vector< std::string > *NewFiles)
Public Attributes
std::vector< MergeFileInfo > Files
size_t NumFilesInFirstCorpus = 0
size_t FirstNotProcessedFile = 0
std::string LastFailure
Detailed Description
Definition at line 56 of file FuzzerMerge.h.
Member Function Documentation
Merge()
size_t fuzzer::Merger::Merge (std::vector< std::string > * NewFiles)
Definition at line 116 of file FuzzerMerge.cpp.
{
   NewFiles->clear();
   assert(NumFilesInFirstCorpus <= Files.size());
   std::set<uint32_t> AllFeatures;
   // What features are in the initial corpus?
   for (size_t i = 0; i < NumFilesInFirstCorpus; i++) {
     auto &Cur = Files[i].Features;
     AllFeatures.insert(Cur.begin(), Cur.end());
   }
   size_t InitialNumFeatures = AllFeatures.size();
   // Remove all features that we already know from all other inputs.
   for (size_t i = NumFilesInFirstCorpus; i < Files.size(); i++) {
     auto &Cur = Files[i].Features;
     std::vector<uint32_t> Tmp;
     std::set_difference(Cur.begin(), Cur.end(), AllFeatures.begin(),
                         AllFeatures.end(), std::inserter(Tmp, Tmp.begin()));
     Cur.swap(Tmp);
   }
   // Sort. Give preference to
   //   * smaller files
   //   * files with more features.
   std::sort(Files.begin() + NumFilesInFirstCorpus, Files.end(),
             [&](const MergeFileInfo &a, const MergeFileInfo &b) -> bool {
               if (a.Size != b.Size)
                 return a.Size < b.Size;
               return a.Features.size() > b.Features.size();
             });
   // One greedy pass: add the file's features to AllFeatures.
   // If new features were added, add this file to NewFiles.
   for (size_t i = NumFilesInFirstCorpus; i < Files.size(); i++) {
     auto &Cur = Files[i].Features;
     // Printf("%s -> sz %zd ft %zd\n", Files[i].Name.c_str(),
     //       Files[i].Size, Cur.size());
     size_t OldSize = AllFeatures.size();
     AllFeatures.insert(Cur.begin(), Cur.end());
     if (AllFeatures.size() > OldSize)
       NewFiles->push_back(Files[i].Name);
   }
   return AllFeatures.size() - InitialNumFeatures;
 }
References assert(), Files, and NumFilesInFirstCorpus.
Referenced by fuzzer::Fuzzer::CrashResistantMerge(), Merge(), and TEST().
Parse() [1/2]
bool fuzzer::Merger::Parse (const std::string & Str, bool ParseCoverage)
Definition at line 24 of file FuzzerMerge.cpp.
{
   std::istringstream SS(Str);
   return Parse(SS, ParseCoverage);
 }
References Parse().
Parse() [2/2]
bool fuzzer::Merger::Parse (std::istream & IS, bool ParseCoverage)
Definition at line 48 of file FuzzerMerge.cpp.
{
   LastFailure.clear();
   std::string Line;
   // Parse NumFiles.
   if (!std::getline(IS, Line, '\n')) return false;
   std::istringstream L1(Line);
   size_t NumFiles = 0;
   L1 >> NumFiles;
   if (NumFiles == 0 || NumFiles > 10000000) return false;
   // Parse NumFilesInFirstCorpus.
   if (!std::getline(IS, Line, '\n')) return false;
   std::istringstream L2(Line);
   NumFilesInFirstCorpus = NumFiles + 1;
   L2 >> NumFilesInFirstCorpus;
   if (NumFilesInFirstCorpus > NumFiles) return false;
   // Parse file names.
   Files.resize(NumFiles);
   for (size_t i = 0; i < NumFiles; i++)
     if (!std::getline(IS, Files[i].Name, '\n'))
       return false;
   // Parse STARTED and DONE lines.
   size_t ExpectedStartMarker = 0;
   const size_t kInvalidStartMarker = -1;
   size_t LastSeenStartMarker = kInvalidStartMarker;
   while (std::getline(IS, Line, '\n')) {
     std::istringstream ISS1(Line);
     std::string Marker;
     size_t N;
     ISS1 >> Marker;
     ISS1 >> N;
     if (Marker == "STARTED") {
       // STARTED FILE_ID FILE_SIZE
       if (ExpectedStartMarker != N)
         return false;
       ISS1 >> Files[ExpectedStartMarker].Size;
       LastSeenStartMarker = ExpectedStartMarker;
       assert(ExpectedStartMarker < Files.size());
       ExpectedStartMarker++;
     } else if (Marker == "DONE") {
       // DONE FILE_SIZE COV1 COV2 COV3 ...
       size_t CurrentFileIdx = N;
       if (CurrentFileIdx != LastSeenStartMarker)
         return false;
       LastSeenStartMarker = kInvalidStartMarker;
       if (ParseCoverage) {
         auto &V = Files[CurrentFileIdx].Features;
         V.clear();
         while (ISS1 >> std::hex >> N)
           V.push_back(N);
         std::sort(V.begin(), V.end());
       }
     } else {
       return false;
     }
   }
   if (LastSeenStartMarker != kInvalidStartMarker)
     LastFailure = Files[LastSeenStartMarker].Name;
   FirstNotProcessedFile = ExpectedStartMarker;
   return true;
 }
References assert(), Files, FirstNotProcessedFile, LastFailure, N, and NumFilesInFirstCorpus.
Referenced by Merge(), Parse(), ParseOrExit(), and TEST().
ParseOrExit()
void fuzzer::Merger::ParseOrExit (std::istream & IS, bool ParseCoverage)
Definition at line 29 of file FuzzerMerge.cpp.
{
   if (!Parse(IS, ParseCoverage)) {
     Printf("MERGE: failed to parse the control file (unexpected error)\n");
     exit(1);
   }
 }
References Parse(), and fuzzer::Printf().
Referenced by fuzzer::Fuzzer::CrashResistantMerge(), and fuzzer::Fuzzer::CrashResistantMergeInternalStep().
Member Data Documentation
Files
std::vector<MergeFileInfo> fuzzer::Merger::Files
Definition at line 57 of file FuzzerMerge.h.
Referenced by fuzzer::Fuzzer::CrashResistantMergeInternalStep(), Merge(), Parse(), and TEST().
FirstNotProcessedFile
size_t fuzzer::Merger::FirstNotProcessedFile = 0
Definition at line 59 of file FuzzerMerge.h.
Referenced by fuzzer::Fuzzer::CrashResistantMergeInternalStep(), Parse(), and TEST().
LastFailure
std::string fuzzer::Merger::LastFailure
Definition at line 60 of file FuzzerMerge.h.
Referenced by fuzzer::Fuzzer::CrashResistantMergeInternalStep(), Parse(), and TEST().
NumFilesInFirstCorpus
size_t fuzzer::Merger::NumFilesInFirstCorpus = 0
Definition at line 58 of file FuzzerMerge.h.
Referenced by Merge(), Parse(), and TEST().
The documentation for this struct was generated from the following files:
mc_orchestrator/json-3.7.3/test/thirdparty/Fuzzer/FuzzerMerge.h
mc_orchestrator/json-3.7.3/test/thirdparty/Fuzzer/FuzzerMerge.cpp