Mixed Criticality Orchestrator: nlohmann::adl_serializer< typename, typename > Struct Template Reference
nlohmann::adl_serializer< typename, typename > Struct Template Reference
default JSONSerializer template argument
#include <adl_serializer.hpp>
Static Public Member Functions
template<typename BasicJsonType , typename ValueType >
static auto from_json (BasicJsonType &&j, ValueType &val) noexcept(noexcept(::nlohmann::from_json(std::forward< BasicJsonType >(j), val))) -> decltype(::nlohmann::from_json(std::forward< BasicJsonType >(j), val), void())
convert a JSON value to any value type
template<typename BasicJsonType , typename ValueType >
static auto to_json (BasicJsonType &j, ValueType &&val) noexcept(noexcept(::nlohmann::to_json(j, std::forward< ValueType >(val)))) -> decltype(::nlohmann::to_json(j, std::forward< ValueType >(val)), void())
convert any value type to a JSON value
template<typename BasicJsonType , typename ValueType >
static auto from_json (BasicJsonType &&j, ValueType &val) noexcept(noexcept(::nlohmann::from_json(std::forward< BasicJsonType >(j), val))) -> decltype(::nlohmann::from_json(std::forward< BasicJsonType >(j), val), void())
convert a JSON value to any value type
template<typename BasicJsonType , typename ValueType >
static auto to_json (BasicJsonType &j, ValueType &&val) noexcept(noexcept(::nlohmann::to_json(j, std::forward< ValueType >(val)))) -> decltype(::nlohmann::to_json(j, std::forward< ValueType >(val)), void())
convert any value type to a JSON value
Detailed Description
template<typename, typename>
struct nlohmann::adl_serializer< typename, typename >
default JSONSerializer template argument
This serializer ignores the template arguments and uses ADL (argument-dependent lookup) for serialization.
Definition at line 12 of file adl_serializer.hpp.
Member Function Documentation
from_json() [1/2]
template<typename , typename > template<typename BasicJsonType , typename ValueType > static auto nlohmann::adl_serializer< typename, typename >::from_json (BasicJsonType && j, ValueType & val) -> decltype(::nlohmann::from_json(std::forward<BasicJsonType>(j), val), void()) inline static noexcept
convert a JSON value to any value type
This function is usually called by the get() function of the basic_json class (either explicit or via conversion operators).
Parameters
[in] j JSON value to read from
[in,out] val value to write to
Definition at line 24 of file adl_serializer.hpp.
     {
         ::nlohmann::from_json(std::forward<BasicJsonType>(j), val);
     }
References nlohmann::detail::from_json().
from_json() [2/2]
template<typename , typename > template<typename BasicJsonType , typename ValueType > static auto nlohmann::adl_serializer< typename, typename >::from_json (BasicJsonType && j, ValueType & val) -> decltype(::nlohmann::from_json(std::forward<BasicJsonType>(j), val), void()) inline static noexcept
convert a JSON value to any value type
This function is usually called by the get() function of the basic_json class (either explicit or via conversion operators).
Parameters
[in] j JSON value to read from
[in,out] val value to write to
Definition at line 3810 of file json.hpp.
     {
         ::nlohmann::from_json(std::forward<BasicJsonType>(j), val);
     }
References nlohmann::detail::from_json().
to_json() [1/2]
template<typename , typename > template<typename BasicJsonType , typename ValueType > static auto nlohmann::adl_serializer< typename, typename >::to_json (BasicJsonType & j, ValueType && val) -> decltype(::nlohmann::to_json(j, std::forward<ValueType>(val)), void()) inline static noexcept
convert any value type to a JSON value
This function is usually called by the constructors of the basic_json class.
Parameters
[in,out] j JSON value to write to
[in] val value to read from
Definition at line 41 of file adl_serializer.hpp.
     {
         ::nlohmann::to_json(j, std::forward<ValueType>(val));
     }
References nlohmann::detail::to_json().
to_json() [2/2]
template<typename , typename > template<typename BasicJsonType , typename ValueType > static auto nlohmann::adl_serializer< typename, typename >::to_json (BasicJsonType & j, ValueType && val) -> decltype(::nlohmann::to_json(j, std::forward<ValueType>(val)), void()) inline static noexcept
convert any value type to a JSON value
This function is usually called by the constructors of the basic_json class.
Parameters
[in,out] j JSON value to write to
[in] val value to read from
Definition at line 3827 of file json.hpp.
     {
         ::nlohmann::to_json(j, std::forward<ValueType>(val));
     }
References nlohmann::detail::to_json().
The documentation for this struct was generated from the following files:
mc_orchestrator/json-3.7.3/include/nlohmann/adl_serializer.hpp
mc_orchestrator/json-3.7.3/single_include/nlohmann/json.hpp