Mixed Criticality Orchestrator: fuzzer::ValueBitMap Struct Reference
fuzzer::ValueBitMap Struct Reference
#include <FuzzerValueBitMap.h>
Public Member Functions
void Reset ()
bool AddValue (uintptr_t Value)
bool Get (uintptr_t Idx)
size_t GetNumBitsSinceLastMerge () const
bool MergeFrom (ValueBitMap &Other)
template<class Callback >
void ForEach (Callback CB)
Static Public Attributes
static const size_t kMapSizeInBits = 65371
static const size_t kMapSizeInBitsAligned = 65536
static const size_t kBitsInWord = (sizeof(uintptr_t) * 8)
static const size_t kMapSizeInWords = kMapSizeInBitsAligned / kBitsInWord
static const size_t kNumberOfItems = kMapSizeInBits
Private Member Functions
uintptr_t Map[kMapSizeInWords] __attribute__ ((aligned(512)))
Private Attributes
size_t NumBits = 0
Detailed Description
Definition at line 20 of file FuzzerValueBitMap.h.
Member Function Documentation
__attribute__()
uintptr_t Map [kMapSizeInWords] fuzzer::ValueBitMap::__attribute__ ((aligned(512))) private
AddValue()
bool fuzzer::ValueBitMap::AddValue (uintptr_t Value) inline
Definition at line 32 of file FuzzerValueBitMap.h.
{
     uintptr_t Idx = Value < kMapSizeInBits ? Value : Value % kMapSizeInBits;
     uintptr_t WordIdx = Idx / kBitsInWord;
     uintptr_t BitIdx = Idx % kBitsInWord;
     uintptr_t Old = Map[WordIdx];
     uintptr_t New = Old | (1UL << BitIdx);
     Map[WordIdx] = New;
     return New != Old;
   }
References Idx, kBitsInWord, and kMapSizeInBits.
Referenced by fuzzer::TracePC::HandleValueProfile().
ForEach()
template<class Callback > void fuzzer::ValueBitMap::ForEach (Callback CB) inline
Definition at line 72 of file FuzzerValueBitMap.h.
{
     for (size_t i = 0; i < kMapSizeInWords; i++)
       if (uintptr_t M = Map[i])
         for (size_t j = 0; j < sizeof(M) * 8; j++)
           if (M & ((uintptr_t)1 << j))
             CB(i * sizeof(M) * 8 + j);
   }
References kMapSizeInWords.
Referenced by fuzzer::TracePC::CollectFeatures().
Get()
bool fuzzer::ValueBitMap::Get (uintptr_t Idx) inline
Definition at line 42 of file FuzzerValueBitMap.h.
{
     assert(Idx < kMapSizeInBits);
     uintptr_t WordIdx = Idx / kBitsInWord;
     uintptr_t BitIdx = Idx % kBitsInWord;
     return Map[WordIdx] & (1UL << BitIdx);
   }
References assert(), Idx, kBitsInWord, and kMapSizeInBits.
GetNumBitsSinceLastMerge()
size_t fuzzer::ValueBitMap::GetNumBitsSinceLastMerge () const inline
Definition at line 49 of file FuzzerValueBitMap.h.
 { return NumBits; }
References NumBits.
Referenced by fuzzer::Fuzzer::PrintStats().
MergeFrom()
bool fuzzer::ValueBitMap::MergeFrom (ValueBitMap & Other) inline
Definition at line 54 of file FuzzerValueBitMap.h.
{
     uintptr_t Res = 0;
     size_t OldNumBits = NumBits;
     for (size_t i = 0; i < kMapSizeInWords; i++) {
       auto O = Other.Map[i];
       auto M = Map[i];
       if (O) {
         Map[i] = (M |= O);
         Other.Map[i] = 0;
       }
       if (M)
         Res += __builtin_popcountl(M);
     }
     NumBits = Res;
     return OldNumBits < NumBits;
   }
References kMapSizeInWords, and NumBits.
Referenced by fuzzer::TracePC::UpdateValueProfileMap().
Reset()
void fuzzer::ValueBitMap::Reset () inline
Definition at line 28 of file FuzzerValueBitMap.h.
 { memset(Map, 0, sizeof(Map)); }
Referenced by fuzzer::TracePC::ResetMaps().
Member Data Documentation
kBitsInWord
const size_t fuzzer::ValueBitMap::kBitsInWord = (sizeof(uintptr_t) * 8) static
Definition at line 23 of file FuzzerValueBitMap.h.
Referenced by AddValue(), and Get().
kMapSizeInBits
const size_t fuzzer::ValueBitMap::kMapSizeInBits = 65371 static
Definition at line 21 of file FuzzerValueBitMap.h.
Referenced by AddValue(), and Get().
kMapSizeInBitsAligned
const size_t fuzzer::ValueBitMap::kMapSizeInBitsAligned = 65536 static
Definition at line 22 of file FuzzerValueBitMap.h.
kMapSizeInWords
const size_t fuzzer::ValueBitMap::kMapSizeInWords = kMapSizeInBitsAligned / kBitsInWord static
Definition at line 24 of file FuzzerValueBitMap.h.
Referenced by ForEach(), and MergeFrom().
kNumberOfItems
const size_t fuzzer::ValueBitMap::kNumberOfItems = kMapSizeInBits static
Definition at line 26 of file FuzzerValueBitMap.h.
NumBits
size_t fuzzer::ValueBitMap::NumBits = 0 private
Definition at line 81 of file FuzzerValueBitMap.h.
Referenced by GetNumBitsSinceLastMerge(), and MergeFrom().
The documentation for this struct was generated from the following file:
mc_orchestrator/json-3.7.3/test/thirdparty/Fuzzer/FuzzerValueBitMap.h