Mixed Criticality Orchestrator: mc_orchestrator/json-3.7.3/test/src/unit-alt-string.cpp File Reference
unit-alt-string.cpp File Reference
#include "doctest_compatibility.h"
#include <nlohmann/json.hpp>
#include <string>
#include <utility>
Classes
class alt_string
Typedefs
using alt_json = nlohmann::basic_json< std::map, std::vector, alt_string, bool, std::int64_t, std::uint64_t, double, std::allocator, nlohmann::adl_serializer >
Functions
bool operator< (const char *op1, const alt_string &op2)
void int_to_string (alt_string &target, std::size_t value)
TEST_CASE ("alternative string type")
Typedef Documentation
alt_json
using alt_json = nlohmann::basic_json < std::map, std::vector, alt_string, bool, std::int64_t, std::uint64_t, double, std::allocator, nlohmann::adl_serializer >
Definition at line 172 of file unit-alt-string.cpp.
Function Documentation
int_to_string()
void int_to_string (alt_string & target, std::size_t value)
Definition at line 158 of file unit-alt-string.cpp.
 {
     target = std::to_string(value).c_str();
 }
References httplib::to_string().
operator<()
bool operator< (const char * op1, const alt_string & op2)
Definition at line 175 of file unit-alt-string.cpp.
 {
     return op1 < op2.str_impl;
 }
References alt_string::str_impl.
TEST_CASE()
TEST_CASE ("alternative string type")
Definition at line 180 of file unit-alt-string.cpp.
 {
     SECTION("dump")
     {
         {
             alt_json doc;
             doc["pi"] = 3.141;
             alt_string dump = doc.dump();
             CHECK(dump == R"({"pi":3.141})");
         }
         {
             alt_json doc;
             doc["happy"] = true;
             alt_string dump = doc.dump();
             CHECK(dump == R"({"happy":true})");
         }
         {
             alt_json doc;
             doc["name"] = "I'm Batman";
             alt_string dump = doc.dump();
             CHECK(dump == R"({"name":"I'm Batman"})");
         }
         {
             alt_json doc;
             doc["nothing"] = nullptr;
             alt_string dump = doc.dump();
             CHECK(dump == R"({"nothing":null})");
         }
         {
             alt_json doc;
             doc["answer"]["everything"] = 42;
             alt_string dump = doc.dump();
             CHECK(dump == R"({"answer":{"everything":42}})");
         }
         {
             alt_json doc;
             doc["list"] = { 1, 0, 2 };
             alt_string dump = doc.dump();
             CHECK(dump == R"({"list":[1,0,2]})");
         }
         {
             alt_json doc;
             doc["list"] = { 1, 0, 2 };
             alt_string dump = doc.dump();
             CHECK(dump == R"({"list":[1,0,2]})");
         }
     }
     SECTION("parse")
     {
         auto doc = alt_json::parse("{\"foo\": \"bar\"}");
         alt_string dump = doc.dump();
         CHECK(dump == R"({"foo":"bar"})");
     }
     SECTION("items")
     {
         auto doc = alt_json::parse("{\"foo\": \"bar\"}");
         for ( auto item : doc.items() )
         {
             CHECK( item.key() == "foo" );
             CHECK( item.value() == "bar" );
         }
         auto doc_array = alt_json::parse("[\"foo\", \"bar\"]");
         for ( auto item : doc_array.items() )
         {
             if (item.key() == "0" )
             {
                 CHECK( item.value() == "foo" );
             }
             else if (item.key() == "1" )
             {
                 CHECK( item.value() == "bar" );
             }
             else
             {
                 CHECK( false );
             }
         }
     }
     SECTION("equality")
     {
         alt_json doc;
         doc["Who are you?"] = "I'm Batman";
         CHECK("I'm Batman" == doc["Who are you?"]);
         CHECK(doc["Who are you?"]  == "I'm Batman");
         CHECK_FALSE("I'm Batman" != doc["Who are you?"]);
         CHECK_FALSE(doc["Who are you?"]  != "I'm Batman");
         CHECK("I'm Bruce Wayne" != doc["Who are you?"]);
         CHECK(doc["Who are you?"]  != "I'm Bruce Wayne");
         CHECK_FALSE("I'm Bruce Wayne" == doc["Who are you?"]);
         CHECK_FALSE(doc["Who are you?"]  == "I'm Bruce Wayne");
         {
             const alt_json& const_doc = doc;
             CHECK("I'm Batman" == const_doc["Who are you?"]);
             CHECK(const_doc["Who are you?"] == "I'm Batman");
             CHECK_FALSE("I'm Batman" != const_doc["Who are you?"]);
             CHECK_FALSE(const_doc["Who are you?"] != "I'm Batman");
             CHECK("I'm Bruce Wayne" != const_doc["Who are you?"]);
             CHECK(const_doc["Who are you?"] != "I'm Bruce Wayne");
             CHECK_FALSE("I'm Bruce Wayne" == const_doc["Who are you?"]);
             CHECK_FALSE(const_doc["Who are you?"] == "I'm Bruce Wayne");
         }
     }
 }
References CHECK, CHECK_FALSE, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::dump(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parse(), and SECTION.