Mixed Criticality Orchestrator: mc_orchestrator/json-3.7.3/test/src/unit-meta.cpp File Reference
unit-meta.cpp File Reference
#include "doctest_compatibility.h"
#include <nlohmann/json.hpp>
Functions
TEST_CASE ("version information")
Function Documentation
TEST_CASE()
TEST_CASE ("version information")
Definition at line 35 of file unit-meta.cpp.
 {
     SECTION("meta()")
     {
         json j = json::meta();
         CHECK(j["name"] == "JSON for Modern C++");
         CHECK(j["copyright"] == "(C) 2013-2017 Niels Lohmann");
         CHECK(j["url"] == "https://github.com/nlohmann/json");
         CHECK(j["version"] == json(
         {
             {"string", "3.7.3"},
             {"major", 3},
             {"minor", 7},
             {"patch", 3}
         }));
         CHECK(j.find("platform") != j.end());
         CHECK(j.at("compiler").find("family") != j.at("compiler").end());
         CHECK(j.at("compiler").find("version") != j.at("compiler").end());
         CHECK(j.at("compiler").find("c++") != j.at("compiler").end());
     }
 }
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::at(), CHECK, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::end(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::find(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::meta(), and SECTION.